### ISSUE TITLE
File does not exist: /var/www/web379/html/kanboard/kanboard/

### ISSUE THREAD

**Issue by dj-hedgehog** [fguillot/kanboard#1001]
I've uploaded the latest kanboard to my PHP shared host and get a blank page when accessing the kanboard URL (in my case http://project-clix.com).

In my error-log I have this message but the file is there:

`File does not exist: /var/www/web379/html/kanboard/kanboard/`

You can access the phpinfo() here: http://project-clix.com/test.php

**Comment by deliciousbob** [comment]
Hi, i had the same issue with a wrong config settings when usesing mysql as database.
I also had the issue with an clean install on my linux vserver, sqlite was installed but not activated in apache. You could eather change the config to usw mysql or check if sqlite is the issue (if you try other tools that use sqlite)
kind regards Robert
