### ISSUE TITLE
Blank page (Empty file)

### ISSUE THREAD

**Issue by theSouL** [fguillot/kanboard#1005]
Hello, when I try to acces to kanboard (after some server problems), I get a blank page, an empty file.

Apache logs:

>[Thu Jul 09 09:55:16.614775 2015] [:error] [pid 26635] [client 88.7.105.200:53069] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Driver/Sqlite.php:22\nStack trace:\n#0 /var/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Driver/Sqlite.php(22): PDO->__construct('sqlite:data/db....')\n#1 /var/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php(81): PicoDb\\Driver\\Sqlite->__construct(Array)\n#2 /var/www/kanboard/app/ServiceProvider/DatabaseProvider.php(63): PicoDb\\Database->__construct(Array)\n#3 /var/www/kanboard/app/ServiceProvider/DatabaseProvider.php(27): ServiceProvider\\DatabaseProvider->getSqliteInstance()\n#4 /var/www/kanboard/app/ServiceProvider/DatabaseProvider.php(13): ServiceProvider\\DatabaseProvider->getInstance()\n#5 /var/www/kanboard/vendor/pimple/pimple/src/Pimple/Container.php(273): ServiceProvider\\DatabaseProvider->register(Object(Pimple\\Container))\n#6 /var/www/kanboard/app/common.php(26): Pimple\\Container->register(Object(ServiceProvider\\DatabaseProvider))\n#7 /var/www/kanboard/index.php(4): require in /var/www/kanboard/vendor/fguillot/picodb/lib/PicoDb/Driver/Sqlite.php on line 22

Debian stable, and I have php5-sqlite installed. Also php5-mysql (if needed). I would like to get back all the data.

Thanks!

**Comment by froschdesign** [comment]
@theSouL 
The error message includes the problem:

> 'PDOException' with message 'could not find driver'

The [PDO driver for SQLite](http://php.net/manual/en/ref.pdo-sqlite.php) is missing.

**This is not a Kanboard error!**

**Comment by theSouL** [comment]
Hi @froschdesign thanks for your answer.

I know isn't a Kanboard error, but I'm not into php and web applications, so I didn't know where to ask.

As I said, I have [php5-sqlite](https://packages.debian.org/sid/php5-sqlite) installed. So, maybe I miss more packages?

**Comment by froschdesign** [comment]
> So, maybe I miss more packages?

Yes, as I said: PDO driver for SQLite!

**Comment by BlueTeck** [comment]
After installing the web server may need to be restarted.

**Comment by theSouL** [comment]
@froschdesign Hahaha!

Sorry, I was using the sqlite3 package instead of sqlite. Thank you very much! I should be banned from this repo haha :P 

Thanks, problem solved ^^

**Comment by froschdesign** [comment]
@theSouL 
No problem. Please close this issue!
