### ISSUE TITLE
Wrong carriage return in description-field

### ISSUE THREAD

**Issue by Black-LotusCY** [fguillot/kanboard#1006]
If [return] is inserted within a description-field, it later disappears.
Example:

Line 1
Line 2

-> Is shown as "Line 1 Line 2".

2x[return] solves the problem but is annoying.
Also 2x[return] makes a new HTML P-Tag for the new line, 1x[return] doesn't.

**Comment by froschdesign** [comment]
This is the expected behaviour. Please look at the formatting syntax of Markdown:

>  Leave 2 spaces at the end of a line to do a line break

https://en.wikipedia.org/wiki/Markdown#Example

**Comment by Black-LotusCY** [comment]
Seems you are right, i just read the suggested page by Kanboard and there was nothing about this behaviour:
http://kanboard.net/documentation/syntax-guide

Still i find this interesting because what is a single return for, if not a new line?
Maybe Kanboard could get a setting for this like "treat_single_return_as_new_line" or would this be forbidden by the markup-standardization?

Furthermore: The internal link to markup-help in Kanboard should link to a page with all information in my opinion. So the actual page (http://kanboard.net/documentation/syntax-guide) should be updated or maybe the link can directly link to the wiki-page? :)

**Comment by froschdesign** [comment]
> Maybe Kanboard could get a setting for this like "treat_single_return_as_new_line" 

:-1:  for this. 

> or would this be forbidden by the markup-standardization?

It would be no longer markdown.

> maybe the link can directly link to the wiki-page?

Look in the first sentence of the page. :wink:

**Comment by Black-LotusCY** [comment]
Got this, thanks for the information :)
