### ISSUE TITLE
Filters on board display for stand up meeting

### ISSUE THREAD

**Issue by divansantana** [fguillot/kanboard#1007]
Kanban is for visualising work and is often used in stand up meetings in teams.

We currently duplicate information on a physical board and ideally would prefer to just use one system (kanboard) and in the morning simply display the board on proj/screen.

One typically discusses:
1) What each individual worked on the previous day
2) What one plans on working on today
3) Any pressing issues/tasks one should be working on.

(1) This is currently a challenge with kanboard. Atlassian's JIRA and Agile board has a quick filter predefined called "Recently updated". And another "Only my issues". It's useful if kanboard had the filter and the board only displayed any tasks that were worked on (in WIP column, or was moved or was updated/commented on etc) yesterday. One then simply clicks that for the stand up and tasks about the tasks being displayed.
(2) Clicking the "Only my issues" filter would help in talking about what one plans to do today, based on tasks displayed on the board once filter is applied.
(3) Can is already solved as one can view the board and look at the various tasks based on category and colour to see what's important or what needs priority.

If one can achieve this with Kanboard, it would help a lot for stand up meetings.

**Comment by oliviermaridat** [comment]
In the development branch (this is very new), there is a new filter "assignee:me" which display "Only my issues". You can check the syntax for all filters here: http://kanboard.net/documentation/search

As far as I know, there is no "Recently updated" filter. I suppose that it is possible to as such a filter, because cards are highlighted on the board when they were updated recently.

**Comment by sparkles645** [comment]
(1) --> Kanboard also has this filter - see screenshot below
(2) --> Kanboard can filter out a users tasks, and then you see only the tasks assigned to this user
(3) --> Can also sort by category (and color can be assigned through "Automatic actions" to specific categories)

![lazy](https://cloud.githubusercontent.com/assets/10092252/8624809/fb765edc-273a-11e5-99cf-16e24e0fd79b.png)


* Reading the docs and trying it out recommended.

**Comment by fguillot** [comment]
Now there is a filter for recently updated tasks in master: `updated:recently` or `modified:yesterday` etc...

You can also combine multiple filters together: `assignee:"Bob L'éponge" updated:recently column:"Work in progress"`.

**Comment by divansantana** [comment]
Great, I plan to test this out in the future and report back. Thanks :)
