### ISSUE TITLE
Hide columns?

### ISSUE THREAD

**Issue by poVoq** [fguillot/kanboard#101]
A little button to hide individual columns (maybe make some hidden by default? Some workflow steps might not be used that often) would be nice for boards with a lot of columns or when working on a smaller screen.

**Comment by bastiao** [comment]
+1

**Comment by jniggemann** [comment]
+1

**Comment by semka** [comment]
+1

**Comment by Chiliec** [comment]
+1

**Comment by fguillot** [comment]
This feature is now implemented in the development branch: https://github.com/fguillot/kanboard/blob/master/docs/board-show-hide-columns.markdown

**Comment by DoumeDuSud** [comment]
thank you @fguillot  :-)
