### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by Black-LotusCY** [fguillot/kanboard#1010]
`app/Template/task/changes.php `
In Line 28 the description "New color" is hardcoded, so no translation in any language will work correctly there.

**Comment by fguillot** [comment]
Actually, it's translated.

The function `t()` is used: https://github.com/fguillot/kanboard/blob/master/app/Template/task/changes.php#L28 and the translation is there: https://github.com/fguillot/kanboard/blob/master/app/Locale/fr_FR/translations.php#L911

**Comment by Black-LotusCY** [comment]
In my Kanboard "New color" isn't translated to german while the rest is. Thought this would be the code where the bug happens. Will look into it more detailed.

**Comment by fguillot** [comment]
Anyone that speak German can update the translation file.

Apparently the translation is there is the development version: https://github.com/fguillot/kanboard/blob/master/app/Locale/de_DE/translations.php#L909
