### ISSUE TITLE
1.0.16: Cumulative flow chart counts closed tasks

### ISSUE THREAD

**Issue by jniggemann** [fguillot/kanboard#1014]
Besides using KB "normally", I use it in a probably non-standard way: I keep a personal kanboard that serves a both a "inbox" (in a GTD sense) as well as a to-do-list ("next actions" in a GTD sense).

I recently upgraded to 1.0.16 and noticed a change in behaviour:
Since the upgrade, the cumulative flowchart counts tasks even if they're closed, see image.
![screenshot_2015-07-13_10-51-16](https://cloud.githubusercontent.com/assets/1318059/8646084/3b3944b2-294d-11e5-99c9-30c7e271edd9.png)

Is there a way I can make it not count closed tasks, or can you please make this user-configurable?

**Comment by knoddle** [comment]
I support the idea of making closed tasks optional in Cumulative flow diagrams. Would it also be possible to restrict the diagram to only include tasks that were closed during the start-end period? Currently it seems all closed tasks are included regardless of when they were closed.

**Comment by fguillot** [comment]
There is now a settings option to exclude or include closed tasks in the CFD.

**Comment by jniggemann** [comment]
Thank you!
