### ISSUE TITLE
Info about name of login after login

### ISSUE THREAD

**Issue by bsduser** [fguillot/kanboard#1023]
Hello

Thanks for very good and simple panel !!

But one thing can be improved or add. 

After logged I want to see what login I use.

Regards 
BSDuser

**Comment by Chaosmeister** [comment]
In the top-right corner of the browser there is a "logout" button. Right next to it is your current login.

**Comment by bsduser** [comment]
I don't have this info : 
1.0.16 (firefox and opera)
![top](https://cloud.githubusercontent.com/assets/2902635/8694193/7852514a-2add-11e5-93ea-b9d5951180a8.png)

**Comment by Chaosmeister** [comment]
I tried with firefox 39 and chrome 43.0.2357.134 m with the latest stable of kanboard (1.0.16)
![image](https://cloud.githubusercontent.com/assets/13346344/8694307/5da2301c-2ade-11e5-9d91-f1bb550cab94.png)

**Comment by froschdesign** [comment]
@bsduser 
I think, your screen size is too small. The username is there, but hidden:

```css
@media only screen and (max-width: 1024px) {
    .hide-tablet {
        display: none;
    }
}
```
https://github.com/fguillot/kanboard/blob/master/app/Template/layout.php#L61

**Comment by bsduser** [comment]
@froschdesign 
I've right. Thanks for this.
