### ISSUE TITLE
Google Auth - Problem and solution

### ISSUE THREAD

**Issue by dreamerworks** [fguillot/kanboard#1024]
Setting up Google Auth like explained here:http://kanboard.net/documentation/google-authentication
It says:
   Fill the form, the redirect URL must be: http://YOUR_SERVER/?controller=user&action=google
But on Google Developer Console, when creating a client ID we see:
"Authorized redirect URIs" 
"One URI per line. Needs to have a protocol, no URL fragments, and no relative paths. Can't be a public IP Address." 
This invalidates the "?controller=user&action=google" part of the instructions. 
I wouldn't mention it if it worked, but it breaks the google auth.

I found a simple (yet not the best) solution for this:

 - on "app/Auth/Google.php":

    - comment lines 88,89,90

    - line 97, replace:

        $currentUri->getAbsoluteUri()

        by

        $this->helper->url->base().'google_callback.php'

- then create  a file called "google_callback.php" on the root of kanboard with a content similar to index.php with a little change:

    <?php
    require __DIR__.'/app/common.php';
    use Core\Router;
    $router = new Router($container,'User','google');
    $router->execute();

This solved my problem. Of course in google developer console I placed:

http://YOUR_SERVER/google_callback.php

**Comment by dreamerworks** [comment]
Well, this solution is not complete.
It works for connecting a user to a google account, but it fails when I try to login with a google account.
I will try to find more on how and why.

**Comment by dreamerworks** [comment]
Ok... so, modify google_callback.php to:
```php
   <?php

    require __DIR__.'/app/common.php';

    use Core\Router;

    if (isset($_GET) && $_GET["controller"] && $_GET["controller"] == "app") {
        $router = new Router($container,'app');
    } else {
        $router = new Router($container,'User','google');
    }

    $router->execute();
```

**Comment by dreamerworks** [comment]
To go around that... on "google_callback.php"
```php
<?php

    require __DIR__.'/app/common.php';

use Helper\Url;

if (isset($_GET) && $_GET["controller"] && $_GET["controller"] == "app") {
    header('Location: ' . Url::server()."?controller=app#");
} else {
    header('Location: ' . Url::server().'?controller=User&action=google&'.$_SERVER['QUERY_STRING']);
}
```

It seems to be working well.

**Comment by fguillot** [comment]
OAuth2 authentication implementation have been changed in the last development version. Issues like these should not happen anymore.
