### ISSUE TITLE
Group based access and LDAP groups

### ISSUE THREAD

**Issue by branek** [fguillot/kanboard#1027]
Adding group based access would be interesting for companies that use LDAP server.

It's easy to test if LDAP user is member of a group, and than to grant/forbid access to project based on membership.

**Comment by oliviermaridat** [comment]
:+1:

**Comment by lazki** [comment]
:+1:

**Comment by dvr123** [comment]
:+1:

**Comment by sparkles645** [comment]
+1

**Comment by alexgoesgit** [comment]
+1

**Comment by mekhanique** [comment]
All add a +1 to this.  Businesses frequently prefer to enable access to applications and projects within those applications on a group-by-group basis.

**Comment by woollensocks** [comment]
:+1:

**Comment by mekhanique** [comment]
Addition to the feature request here:  can we define a LDAP group to be "Admins" by default.

**Comment by RainerW** [comment]
+1

**Comment by fguillot** [comment]
I started to implement this feature in the development version.

Doc: https://github.com/fguillot/kanboard/blob/master/doc/ldap-group-sync.markdown

At the moment, only Kanboard groups (Admins, Project Admins, Users) are defined according to the LDAP groups. I tested only with Active Directory for now...

**Comment by fguillot** [comment]
This feature is now available in the latest stable version: http://kanboard.net/documentation/ldap-group-sync
