### ISSUE TITLE
Missing /vendor/ directory in current code...

### ISSUE THREAD

**Issue by worsco** [fguillot/kanboard#1028]
If you download the current .zip of kanboard, the /vendor/ directory is missing -- yet app/common.php is looking for it:

app/common.php:require dirname(__DIR__) . '/vendor/autoload.php';

**Comment by BlueTeck** [comment]
If you use the download from github you have to run composer install.

https://github.com/fguillot/kanboard/blob/master/docs/update.markdown

**Comment by worsco** [comment]
'composer install' completed the install!  Thank you.  My mistake.
