### ISSUE TITLE
Adding Sub Column Support

### ISSUE THREAD

**Issue by mangopudding** [fguillot/kanboard#1029]
Hi there.

I had reviewed the list of feature requests and I don't think I saw this particular one - if it's a duplicate feature request - my appologies.  

I'd like to know if it's possible to add sub-column support.

Take a look at the attached screen shot.

<img width="611" alt="sub column example" src="https://cloud.githubusercontent.com/assets/5124548/8703044/13158a0c-2ad0-11e5-962c-c9365cb5638f.png">

**Comment by BlueTeck** [comment]
see #955 #530

**Comment by mangopudding** [comment]
Thanks.  See those issues now.
