### ISSUE TITLE
[Feature Request] Summary Page for Notifications

### ISSUE THREAD

**Issue by akluthe** [fguillot/kanboard#1031]
I know we have the Activity Steams. These are nice. But they show everything. Right?

I'm already inundated with email and although we have notifications setup in hipchat, they feel too passive for me not to miss something happening on the boards.

I wish there was a way I could go to an inbox-like page with summary of notifications I have received in the last few days, or they could pile up until dismissed. Some kind of icon/visual reference to the count by my login would really round out the notifications feature.

**Comment by BlueTeck** [comment]
Reference #752

**Comment by fguillot** [comment]
With the last development branch, there is now "web notifications" similar to Github and instead of receiving emails you have a list of notifications in the user interface. Then you can mark everything a read...
