### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by cesaric** [fguillot/kanboard#1034]
I just did git pull & going through I get the following warning when I click "Average time into each column" for a project report: 

**Warning: Division by zero in /Users/robert/Workspace/zagweb76/kanboard/app/Model/ProjectAnalytic.php on line 177**

Which then triggers a few subsequent:

**Warning: Cannot modify header information - headers already sent by (output started at /Users/robert/Workspace/zagweb76/kanboard/app/Model/ProjectAnalytic.php:177) in /Users/robert/Workspace/zagweb76/kanboard/app/Core/Response.php on line 57**

All other reports are working fine.

**Comment by fguillot** [comment]
It's fixed in master. Thanks.
