### ISSUE TITLE
[Update documentation] LDAP-integration; allow within SElinux (etc.) or set permissive 

### ISSUE THREAD

**Issue by CoMPaTech** [fguillot/kanboard#1037]
2 notes on documentation; one on selinux and one on filtering

1)
Small note on the LDAP integration, at least under RHEL-based like CentOS you should either set SElinux to permissive or allow apache to reach out to LDAP.

So the quickest solution would be to set SElinux to permissive (canon-approach), the nearest could be to ```setsebool -P httpd_can_network_connect=1``` (shotgun) but there might be some more decent way to neatly allow LDAP-authentication.

2)
Smaller note is that LDAP_USER_PATTERN also for OpenLDAP can be used as filter (instead of the default uid=%s) for example (&(objectClass=user)(uid=%s)(!(ou:dn::=trainees)))

**Comment by fguillot** [comment]
The doc have been updated.
