### ISSUE TITLE
When moving a task across projects, when selecting the project, dynamically loading other properties can be slow and timeout

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1041]
When on a slow web host (ex: a shared hosting service), there are sometimes some delays for requests, and this can be felt in the "Move task" form when you select the Project, which affects the available swimlanes, columns and categories. You will then get "Read the_website_address" in the browser (Firefox) statusbar for a few seconds, and at the end the data might not load (timeout?).

You can make the problem worse by rapidly switching between values in the "Project" combobox, as this screencast illustrates: http://jeff.ecchi.ca/public/kanboard-2015-07-20.webm

**Comment by fguillot** [comment]
I added a loading icon to indicate to the user that something is loading. And fixed the "rapid switching", that will have no effect, I mean the browser will not reload the page again if it's already trying to download the page.

**Comment by nekohayo** [comment]
Thanks, the loading icon is a nice addition, and somehow the whole thing feels faster (strange!), but there seems to be a backend issue remaining, where sometimes the request gets completely ignored. Updated screencast: http://jeff.ecchi.ca/public/kanboard-2015-07-20-2.webm

In that one you can see that sometimes the loading icon/spinner doesn't appear at all, and at those times the "swimlanes" field doesn't change/reset properly... race condition?
