### ISSUE TITLE
Allow setting session expiration.

### ISSUE THREAD

**Issue by docwhat** [fguillot/kanboard#1042]
We have security requirements that say that sessions cannot be more than X hours without requiring re-authentication.

With the above use-case, it would be nice to be able to set a configuration (e.g. `SESSION_LENGTH`) which would:

1. Set the maximum length of a session.
2. Disable the remember me (it isn't needed, everyone should be remembered for `SESSION_LENGTH`).

**Comment by fguillot** [comment]
I added new config parameters for that in the development branch:

- https://github.com/fguillot/kanboard/blob/master/docs/config.markdown#rememberme-authentication-settings
- https://github.com/fguillot/kanboard/blob/master/docs/config.markdown#session

**Comment by docwhat** [comment]
Yay!
