### ISSUE TITLE
Add setting to disable Time tracking ?

### ISSUE THREAD

**Issue by jeje99** [fguillot/kanboard#1043]
Hi,

Kanboard is an excellent tools to plan stuff. But, the time tracking is a bit anoying for people like me who don't want to use it.

Is it possible to add a setting to disable this feature ?

**Comment by fguillot** [comment]
There is now a settings to disable that.

**Comment by jeje99** [comment]
Thanks !

**Comment by GitHub-Lover** [comment]
Sorry, I can not find this, where can I set to disable time tracking?

**Comment by jeje99** [comment]
Hi,

My kanboard is in french. But you can find this option,  in global setting of Kanboard app : in the menu "agenda parameter". 
There a group options called "Suivi du temps par rapport aux sous-tâches" (sorry I can't translate).

**Comment by fguillot** [comment]
Settings > Project Settings > Trigger automatically subtask time tracking

or

Préférences > Paramètres du projet > Déclencher automatiquement le suivi du temps pour les sous-tâches
