### ISSUE TITLE
Reloading (F5) the board corrupts the information tooltips

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1044]
before:
![image](https://cloud.githubusercontent.com/assets/13346344/8804444/a18d2bd6-2fcc-11e5-9d6d-92d88e815ff3.png)

after:
![image](https://cloud.githubusercontent.com/assets/13346344/8804464/abc3e4dc-2fcc-11e5-9e59-16411a744328.png)

**Comment by fguillot** [comment]
Yes, this issue have been fixed in the development branch.
