### ISSUE TITLE
create task per mail fetch

### ISSUE THREAD

**Issue by deecey** [fguillot/kanboard#1046]
Hi,
I'd love to create kanboard tasks by simply sending an E-Mail to my own adress. Functionality should be similar to the postie plugin for wordpress (https://wordpress.org/plugins/postie/), although no special features are necessary. The core function of fetching the account an create tasks from the given title and body text would be great and enough ;-)
Regards, Chris

**Comment by BlueTeck** [comment]
You could create tasks via email.

**Comment by deecey** [comment]
Yea, but I have to use an external (paid) service to do it..
Although, perhaps I just didn't understand this description correctly:

> Incoming emails workflow

> You send an email to a specific address, by example something+myproject@inbound.mydomain.tld
> Your email is forwarded to the third-party SMTP servers
> The SMTP provider call the Kanboard webhook with the email in JSON or multipart/form-data formats
> Kanboard parse the received email and create the task to the right project
> Note: New tasks are automatically created in the first column.

so, let's say the URL of my kanboard is www.testurl.com/kanboard and the project I want to create tasks in is "project_one". What is the target E-Mail adress I should send my tasks to? Is it kanboard+project_one@testurl.com?

thanks, Chris

**Comment by middeke** [comment]
Sorry, page not found!
http://kanboard.net/documentation/email-tasks

**Comment by froschdesign** [comment]
@middeke 
Wrong address! See: http://kanboard.net/documentation/create-tasks-by-email

**Comment by deecey** [comment]
Yes, but that's the page I already cited above. 

Do I have to use one of the given external services or can I use an arbitrary E-Mail account, from which the tasks are fetched?

**Comment by froschdesign** [comment]
> Yes, but that's the page I already cited above.

Ignore this, it was a message to @middeke.

> Do I have to use one of the given external services or can I use an arbitrary E-Mail account…

External service or write your own script which uses the Kanboard API and executed by a cronjob.

**Comment by middeke** [comment]
**@froschdesign**
ah, OK, it was the link from the mail-integration sites like: http://kanboard.net/documentation/mailgun that was not found

**Comment by deecey** [comment]
Ok, thanks for your help. In this case, I would like to label this as a feature request ;-)

**Comment by c0mputerking** [comment]
I would also like to be able to create tasks via email using my own smtp server, is it possible maybe i just did not find the link?

**Comment by psy-q** [comment]
Take a look at #1158.
