### ISSUE TITLE
XMPP integration

### ISSUE THREAD

**Issue by prabhanjan-kv** [fguillot/kanboard#1048]
Hi , 
I am trying to integrate jabber to the kanboard application , Filled up everything in the 
"Settings > Integrations > Jabber" but I am not able to see the Jabber client Adium in the application 

As I am new to the interface , Please help me out . 
I have even checked with http://kanboard.net/documentation/jabber but no luck

Thanks

**Comment by fguillot** [comment]
What is not working exactly? are you sure that the settings you entered are correct? did you enable the debug mode like described in the troubleshooting section?

**Comment by prabhanjan-kv** [comment]
Hi, Thanks for the comment , 
I have entered the xmpp configuration settings in the integration part and also enabled debug mode but I am not able to see any chat related client in the board , Is it anything else I have to do ..

**Comment by fguillot** [comment]
I don't really understand what you mean, there is no chat client in Kanboard, you have to use any Jabber client. Adium is just a jabber desktop client among many others.
