### ISSUE TITLE
CalDAV tasks support?

### ISSUE THREAD

**Issue by poVoq** [fguillot/kanboard#105]
Probably a lower priority feature request, but what about CalDAV task support?
http://en.wikipedia.org/wiki/CalDAV

Would be nice to have Kanboard interact with a PIM (Thunderbird for example).

**Comment by BlueTeck** [comment]
#490

**Comment by mluepkes** [comment]
So, ical is included in your calendar submit?

**Comment by BlueTeck** [comment]
In this version it is not included, it is just a calendar view using fullcalendar.io

If have started to implement ical, but i was not so happy with it...

**Comment by mluepkes** [comment]
How about using something like: [jasvrcek/ICS](https://github.com/markuspoerschke/iCal/releases) or [markuspoerschke/iCal](https://github.com/jasvrcek/ICS)
I'll put that on my todo list. If you beat me to it, I'll not complain ;)

**Comment by fguillot** [comment]
I wrote a very quick prototype to estimate the complexity of that (branch ical).

- For me, the easiest solution is to generate *.ics calendar events, seems to works well with Apple Calendar or any compatible calendar software.
- The full Caldav server solution with http://sabre.io/dav/ is more complex and include a huge dependency. There are all features available, multiple users/calendars and read/write...

So having a read-only calendar for each user and each project should not be very hard. Those public endpoint can be protected by a token like feeds or public boards.

**Comment by fguillot** [comment]
iCal feeds are now available in the development branch. You can synchronize your Kanboard calendars with almost any calendar programs Outlook, Apple Calendar + iOS, Google Calendar + Android...

More info here: http://kanboard.net/documentation/ical

Note: I'm currently testing this feature...
