### ISSUE TITLE
EmailClient.php ignores MAIL_TRANSPORT via mail (php mail function)

### ISSUE THREAD

**Issue by MatteoOs** [fguillot/kanboard#1051]
Emails are not sent via the built in PHP mail function if it is set in the configs. The Comment in the config file allows the following settings:
// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"

This may be due to the fact that this setting is not implemented in ./apps/core/EmailClient.php:

"switch (MAIL_TRANSPORT) {
		
            case 'sendgrid':
                $this->sendgrid->sendEmail($email, $name, $subject, $html, $author);
                break;
            case 'mailgun':
                $this->mailgun->sendEmail($email, $name, $subject, $html, $author);
                break;
            case 'postmark':
                $this->postmark->sendEmail($email, $name, $subject, $html, $author);
                break;
            default:
                $this->smtp->sendEmail($email, $name, $subject, $html, $author);
        }"

I suggest the sth similar to the following:

"switch (MAIL_TRANSPORT) {
		
            case 'sendgrid':
                $this->sendgrid->sendEmail($email, $name, $subject, $html, $author);
                break;
            case 'mailgun':
                $this->mailgun->sendEmail($email, $name, $subject, $html, $author);
                break;
            case 'postmark':
                $this->postmark->sendEmail($email, $name, $subject, $html, $author);
                break;

            case 'mail':
                $headers  = 'MIME-Version: 1.0' . "\r\n";
                $headers .= 'Content-type: text/html; charset=utf8' . "\r\n";
                mail($email,$subject,$html,$headers);
                break;

            default:
                $this->smtp->sendEmail($email, $name, $subject, $html, $author);
        }"

**Comment by fguillot** [comment]
It's implemented here: https://github.com/fguillot/kanboard/blob/master/app/Integration/Smtp.php#L55-L67 by using the library SwiftMailer.
