### ISSUE TITLE
Show task complexity in task detail view

### ISSUE THREAD

**Issue by jakoubek** [fguillot/kanboard#1052]
The complexity of a task should be shown in the task details (<div class"... task-show-details">...). Currently it's only shown on the board and when editing the task.

**Comment by TabDambrine** [comment]
Hi,

As far as i can remember it always have been shown on the task details page at the bottom right of the task (per example on the demo website (once logged in) : http://demo.kanboard.net/project/1/task/3 the complexity is 8).

**Comment by jakoubek** [comment]
Suddenly the numbers appear - obviously it was to far right for my eyes ....

Issue can be closed.
