### ISSUE TITLE
Enable support for Github Enterprise when using github auth

### ISSUE THREAD

**Issue by mekhanique** [fguillot/kanboard#1053]
The Github auth part is nice,  but you will find many orgs that prefer not to host their code on Github.com.  That said, they may still use github,  just the enterprise version instead.  This should be a simple change to pull out the hard coded URI for github.com and allow a user to insert the proper equivalent in to the config.php file.

**Comment by fguillot** [comment]
According their documentation, the support of OAuth for Github Enterprise will be removed in November 2015: https://help.github.com/enterprise/2.2/admin/guides/user-management/using-github-oauth/

**Comment by mekhanique** [comment]
I thought I remembered a conversation about this with github, the gist of which was "misleading article".  Let me verify with them that this functionality is being fully remove and get back to you.

**Comment by mekhanique** [comment]
Okay, got a response back from Github and I am correct.  What's actually being turned off is the ability for github enterprise instances to oauth link to github.com (as they've provided other auth solutions there).   Application oauth linkages shall continue to work.   Relevant excerpt from my conversation with them below:

	
Colin Seymour (GitHub Enterprise)
Jul 28, 9:40 AM 

So if I understand correctly, applications will still be able to authenticate against my internal enterprise instance (which is what I want to maintain). 
Is my understanding correct?

Yes. That is correct and this won't be changing any time soon.

— Colin

Cheers,
Steve

**Comment by fguillot** [comment]
It's now possible to define custom urls for Github OAuth (in dev version only).

See https://github.com/fguillot/kanboard/blob/master/docs/github-authentication.markdown#github-entreprise

**Comment by mekhanique** [comment]
Thanks!
