### ISSUE TITLE
Filter for user and categories

### ISSUE THREAD

**Issue by middeke** [fguillot/kanboard#1055]
Hi,

the new filter ist really great, but is there a way to reactivate the filter shortcuts für user and category in the project view in KB 1.0.17 like it was before? The category filter got all items automatically, I need this for my usecase.

THX,
Martin

**Comment by AlGates2k** [comment]
Same here. The category filter was perfect. Without, it makes things more complicated. :-(

**Comment by iaanus** [comment]
+1

**Comment by McodeMe** [comment]
Reintegration of user filter is needed, as one can easily check over all users what tasks they are having at the moment.

**Comment by julizei** [comment]
+1

**Comment by epaiva** [comment]
+1

**Comment by fguillot** [comment]
It's now in master. The user and category dropdown populates the filter field automatically.

**Comment by middeke** [comment]
THX!!!
Great Work!!
