### ISSUE TITLE
Can Admin View All Projects, All Users In Calendar?

### ISSUE THREAD

**Issue by ansh0603** [fguillot/kanboard#1057]
We need a view for Admin, having - Filter By All Projects plus Filter By All Users in Calendar 

controller=calendar&action=show&project_id = 
All Projects

![capture](https://cloud.githubusercontent.com/assets/13551686/8952608/f0563f12-35f5-11e5-80c0-ce665d75d29e.PNG)

**Comment by ansh0603** [comment]
We need 1 More filter "Filter By Project" in above view.
Can Admin view Multiple Projects - Multiple Users in One Calendar?

**Comment by fguillot** [comment]
This view doesn't exists anymore in the last version of Kanboard. In the user calendar, you can see only projects where you are member.
