### ISSUE TITLE
Minor UI regression: collapsed view, cannot open task details in background tab

### ISSUE THREAD

**Issue by TheIndifferent** [fguillot/kanboard#1061]
In version 1.0.16 I used middle mouse button in collapsed view to open multiple tasks in new tabs and go trough tabs. In 1.0.17 only the first mouse button goes to task in current tab, cannot click on the task with middle mouse button.

**Comment by fguillot** [comment]
It's now fixed in master.

**Comment by TheIndifferent** [comment]
Works now in 1.0.18, thanx!
