### ISSUE TITLE
Closed Tasks Page Not Found Bug

### ISSUE THREAD

**Issue by conmurray** [fguillot/kanboard#1063]
![p1](https://cloud.githubusercontent.com/assets/3668847/9005868/af87174c-3779-11e5-909a-02849e910df8.jpg)
![p2](https://cloud.githubusercontent.com/assets/3668847/9005877/c425bd84-3779-11e5-9a86-aff3fe6e94d8.jpg)

Reproduced on my own board and the Demo board aswell.

Issue: Get page not found when I click this link http://demo.kanboard.net/?controller=project&action=tasks&project_id=1

How to reproduce:
Go to http://demo.kanboard.net/project/1
Click on the link for 1 closed tasks. 
It will bring you to the page mentioned in the issue.

Not sure what I should see here.

Secondly the docs state (http://kanboard.net/documentation/closing-tasks)
that "When a task is closed, they are hidden from the board. However, you can always access to the list of closed tasks from the board menu Board > Actions > Completed tasks."

I cannot see this particular option anywhere in the current stable release build. 

Hope that helps

Conor

**Comment by fguillot** [comment]
The link was wrong and the documentation not updated. It's now fixed in the development branch.

To see closed tasks, just use the filter dropdown next to a search form and choose "closed tasks".

Thanks to report this issue.
