### ISSUE TITLE
Search by task id or title : number in title

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1064]
We have a task with the number 8873 (Version/Buildnumber) - in the title.
We noticed that if we try to filter with that number, no task is displayed as the Advanced Search Syntax tries to find a task with that ID. Filtering for "8873" gave no result as well.

Since we can filter it with other parts of the title, this is not so critical for us.

**Comment by fguillot** [comment]
Yes, when you enter an integer only that will search by task id and not by task title.

**Comment by Chaosmeister** [comment]
So there is no way to filter for numbers in the task title?
maybe you could implement this if I filter like "number"

Frédéric Guillot <notifications@github.com> schrieb am Do., 13. Aug. 2015
um 01:12 Uhr:

**Comment by fguillot** [comment]
This behavior have been modified in the dev version. Now, if you enter an integer only that will search in task id but also in the task title.

See https://github.com/fguillot/kanboard/blob/master/docs/search.markdown#search-by-task-id-or-title
