### ISSUE TITLE
Service Timeout  when using github webhook

### ISSUE THREAD

**Issue by KabbAmine** [fguillot/kanboard#1065]
Hi, thanks for this wonderful application.

I wanted to link a kanboard project to a [simple github repo](https://github.com/KabbAmine/test-with-kanboard2), so I've followed all instructions provided [here](http://kanboard.net/documentation/github-webhooks).

But when I created an issue in the repo, the event wasn't delivered and I had `We couldn’t deliver this payload: Service Timeout `. I've checked & re-checked the payload URL and its the correct one.

So, did I miss something?
Thanks in advance.

**Comment by fguillot** [comment]
Did you check if Github really call your web server? check the access log files of your web server, you should see the http request made by Github..

**Comment by KabbAmine** [comment]
Ooh my bad, I was using `localhost` as a URL  :sweat_smile: 
It works well now, thanks.

Issue closed.

**Comment by ashishkarpe-compumatrice** [comment]
@fguillot my access log my_jenkins_serverip/log/all there no request from my GitHub now what to troubleshoot next ?
