### ISSUE TITLE
issue with js files when behind ssl

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1067]
I don't get
- the date picker
- the calendar view
- moving of tasks
- the actions dropdown

If I turn off ssl (using Cloudflare's flexible SSL) it works.

Any idea?

**Comment by fguillot** [comment]
Open the developer tools in Chrome or Firefox and check the network tab to see what is going on.

**Comment by thob** [comment]
It's a Cloudflare issue. Their _Rocket Loader_ is the culprit

**Comment by tencrocs** [comment]
Hi, cloudflare suggest to add data-cfasync="false" in the javascript tag to exclude it from being parsed by rocket loader. Hope to see this added.
