### ISSUE TITLE
[IMP] Pop-up view of subtask status toggling does not update instantly when clicking (like it used to)- KB v 1 0 1 7

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1070]
**Pop-up overview of subtasks status does not update when clicking to toggle status. (shame, cause this was a very effective way to update status if many sub-tasks on the task / long list)**

However, the change is status from the click **is registered** within KB, but you must "un-mouse" the pop-up and "re-mouse" so the pop-up comes back to see the change in status toggle.

See screenshot to clarify what I mean by the above;

![2015-08-02_17-04-01](https://cloud.githubusercontent.com/assets/10092252/9026705/514cabc6-3939-11e5-8ef1-07ad697b8aa5.png)

**Comment by fguillot** [comment]
I fixed a regression related to that a couple of days ago: https://github.com/fguillot/kanboard/commit/2eeb58ae0321f584652714080649302c3f83a831

You can try to apply the fix manually that should resolve your problem while waiting the next release.

**Comment by sparkles645** [comment]
Can wait for next release. =)
