### ISSUE TITLE
Toggle subtask status on board view calling the wrong template

### ISSUE THREAD

**Issue by hurisheng** [fguillot/kanboard#1075]
### Reproduce steps:
1. Create a task and a subtask of it.
2. Switch to board view.
3. Hover over the subtask icon on the lower right corner of the task created in step #1.
4. Click the subtask shown in the tooltip.
You will get error message in web server log. My instance is Nginx, so I got the error:
```
2015/08/05 15:54:29 [error] 22715#0: *8657 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'LogicException' with message 'Unable to load the template: "board/subtasks"' in /opt/kanboard/app/Core/Template.php:39
Stack trace:
#0 /opt/kanboard/app/Controller/Subtask.php(192): Core\Template->render('board/subtasks', Array)
#1 /opt/kanboard/app/Core/Router.php(213): Controller\Subtask->toggleStatus()
#2 /opt/kanboard/app/Core/Router.php(188): Core\Router->load('/opt/kanboard/a...', 'subtask', '\Controller\Sub...', 'togglestatus')
#3 /opt/kanboard/index.php(5): Core\Router->dispatch('/?controller=su...', 'controller=subt...')
#4 {main}
  thrown in /opt/kanboard/app/Core/Template.php on line 39" while reading response header from upstream, client: 219.137.135.142, server: kb.iwode.com, request: "GET /?controller=subtask&action=toggleStatus&task_id=13&subtask_id=4&redirect=board HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "kb.iwode.com", referrer: "http://kb.iwode.com/?controller=board&action=show&project_id=2"
```

### Possible solution:
I have checked the source file, I found it might be calling the wrong template file `board/subtasks`. The right one maybe 'board/tooltip_subtasks'. I modified the file and it works well.

**Comment by hurisheng** [comment]
It seems the issue has been resolved a few days ago, so close it right now.

**Comment by fguillot** [comment]
You are both right, this bug have been fixed here: https://github.com/fguillot/kanboard/commit/2eeb58ae0321f584652714080649302c3f83a831
