### ISSUE TITLE
Tasks in the Done column still appear at the top of my Tasks list

### ISSUE THREAD

**Issue by golharam** [fguillot/kanboard#1078]
I have due dates on my tasks.  When I complete a task, I move it to the Done column, however it continues to appear at the top of my tasks list.  I don't want to mark the task as Closed.  Is it possible to have the task removed from My Tasks list since its in the Done column?

**Comment by fguillot** [comment]
The "Done" column is just a title that can be changed at any time, if you don't want to close the task use a more specific filter in the search box.
