### ISSUE TITLE
[FR?] Project Hours Overview

### ISSUE THREAD

**Issue by LukeHartcher** [fguillot/kanboard#1079]
Not sure if this is a feature request or not - is there a page/report that shows the total Project Task Hours estimated against actual? At a task level with totals would be ideal. Basically this will show that the project is estimated to be 100 hours and we have spent 50 hours etc, and the same for each task.

Does such a page/report exist?

If not it could be as simple as adding the Time Estimated and Time Spent to the List View for the project, with a Total line somewhere.

**Comment by fguillot** [comment]
Not yet available, in the meantime you can export the tasks in CSV and sum the column time spent/estimated.

**Comment by peripatetic-sojourner** [comment]
@LukeHartcher This was released in 1.0.23. Could you take a look and comment if this can be closed, or what's missing?
