### ISSUE TITLE
Security Bug !!!

### ISSUE THREAD

**Issue by rstoltenberg** [fguillot/kanboard#1080]
If an unauthorized user opens the link of a projekt task, he could read them!

Tested on demo.kanboard.net and also our local installation.

steps @ demo.kanboard.net:

Revoked user1 the right of "project with swimlanes", then open the private project of user1 and open the task "Something to do" ... url: http://demo.kanboard.net/project/3/task/13

Now you can edit the url to http://demo.kanboard.net/project/3/task/6 ... 6 is the task id of the "projekt with swimlanes" task "Feature #1".

In the url, the project id could be missmatch with the task id, e.g. allowed 3-13, denied 2-6. But on opening to read the task, it will not be checked if the task id belongs to the given project id, e.g. 3-6 (no refernce exists).

So any user can open any task only each action will be forbidden, but the task would be opened to read!

**Comment by fguillot** [comment]
It's now fixed in master. Thanks.

**Comment by laupkram** [comment]
@fguillot  I think security issues must not be disclosed in github and must be directly send to developer's email.
