### ISSUE TITLE
BUG: Start progress of subtask in dashboard leads to error 

### ISSUE THREAD

**Issue by 4leben** [fguillot/kanboard#1081]
*Steps to reproduce*

* create task with subtasks
* go to dashboard
* start progress of subtasks
* error occurs 

Fatal error: Uncaught exception 'LogicException' with message 'Unable to load the template: "board/subtasks"' in C:\xampp\htdocs\kanboard\app\Core\Template.php:39 Stack trace: #0 C:\xampp\htdocs\kanboard\app\Controller\Subtask.php(192): Core\Template->render('board/subtasks', Array) #1 C:\xampp\htdocs\kanboard\app\Core\Router.php(213): Controller\Subtask->toggleStatus() #2 C:\xampp\htdocs\kanboard\app\Core\Router.php(188): Core\Router->load('C:\\xampp\\htdocs...', 'subtask', '\\Controller\\Sub...', 'togglestatus') #3 C:\xampp\htdocs\kanboard\index.php(5): Core\Router->dispatch('/kanboard/?cont...', 'controller=subt...') #4 {main} thrown in C:\xampp\htdocs\kanboard\app\Core\Template.php on line 39

**Comment by fguillot** [comment]
Yes, it's already reported here #1070 and #1075 and fixed here https://github.com/fguillot/kanboard/commit/2eeb58ae0321f584652714080649302c3f83a831
