### ISSUE TITLE
Unable to reorder Projects by priority in dashboard

### ISSUE THREAD

**Issue by c33f** [fguillot/kanboard#1082]
Hi,
I using more and more KB for pro and personal use.
I would liek to be able to sort Projects in the Dashboard by priority.
For instance I would like to have project15 always on the top row of the dashboard.
I could not find a way to do it.
Is this a feature that couldbe implemented or did I miss something ?
Thank you for your great work.

**Comment by fguillot** [comment]
There is no priority per project.

**Comment by c33f** [comment]
Ok. Is there a way I could sort them in the dashboard (not only alphabetically) ? kind of workaround.
Maybe per id but it doesn't show in the bashboad and it doesn't seem possible to chaneg projet's id .
It would great if it could be added to the wishlist.

**Comment by mfgeo** [comment]
Indeed this would be useful for us.

Is there any reason this is a bad idea?

**Comment by PIMJIM** [comment]
I also think this would be a great feature to add.

**Comment by fguillot** [comment]
Sorry, I prefer to keep Kanboard simple so this feature won't be developed.

**Comment by cube3j** [comment]
Hi, I also think it was a good idea (may be later)
