### ISSUE TITLE
Error 403 on some page and on board

### ISSUE THREAD

**Issue by dantahoua** [fguillot/kanboard#1083]
Hello.
I have a 403 error on some page, hard to tell why because there is no log as it's a 403 error!
If I want to modify a column for example:
`http://kanboard.lesaintdev.com/board/?controller=column&action=edit&project_id=1&column_id=3`
I have the classic Apache "You don't have permission to access /board/ on this server."
Note that I tried direct installation on the absolute path (without a subfolder) and the error is the same.
The error is the same when clicking on the "+" on the board (any column)... 
On my local machine, everything works fine, maybe a folder right on the server?
Any idea?

**Comment by fguillot** [comment]
Did you check the apache error log to see if you have more details?

**Comment by dantahoua** [comment]
Yes, I have nothing. I even try the dev version, same error... Seems to be a problem witht he "column" controller cause I can edit user for exemple...

**Comment by fguillot** [comment]
That may be related to your Apache settings, pretty hard to help without more details about your setup.

**Comment by dantahoua** [comment]
Hum yes I understand. I'll try to compare the Apache setting between the server and my two local machine, I'll keep you in touch.
