### ISSUE TITLE
Enable/disable rewrite doesn't appear to properly work in Seamonkey?

### ISSUE THREAD

**Issue by maqueen** [fguillot/kanboard#1084]
When enabled basically only displays base system without any css or graphics, etc.

**Comment by fguillot** [comment]
Are you sure that it's related to seamonkey? please provide more details about your setup to be able to troubleshoot something.

**Comment by maqueen** [comment]
Hi,

Honestly I'm not sure. Just looking over things I did read that certain
functions may not necessarily work in all browsers. Seamonkey is also
latest.

Debian Jessie, Apache, latest stable Kanboard installed in
/var/www/html/ using sqlite. Config.php still set at defaults. Toggled
ENABLE_URL_REWRITE between false and true. With negative results using
'true'.

Frédéric Guillot:

**Comment by fguillot** [comment]
The issue is related to your server configuration, check if mod_rewrite is enabled and if you have the option `AllowOverride All` for the document root.
