### ISSUE TITLE
The subtask state must be changeable

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#1085]
Hello!

Currently the subtask state (to do, doing and done) don't chage when you click it.
From **to do** to **doing** is fine, but to immediately change to **doing** to **done** doesn't work.
To allow us to change between these 3 states, at will, would be nice.

Best regards,
Ben Hur

**Comment by fguillot** [comment]
That works for me, please provide more details that will help to see if there is a bug with a specific environment...

**Comment by oxydron** [comment]
Hi, sorry for not being more desciptive.
Steps to reproduce the 'bug':
1 - Create a task
2 - Create a subtask
3 - Click on it to change its status to "doing"
4 - Click again and again.
Result: I can't change between the status/symbols below just clicking, only after a unknown time has passed.

![kanban_01](https://cloud.githubusercontent.com/assets/331134/9249561/610a6844-419c-11e5-8311-565848da98c0.png)

**Comment by donpatzone** [comment]
Is it possible that it might be related to [#1148](https://github.com/fguillot/kanboard/issues/1148)?
Changing the state of the icons is working for me as well, but it triggers a page refresh, which also means that going immediately from _not started_ to _completed_ is not possible. If it does not go to _completed_ at all I assume it might be a browser issue.

**Comment by oxydron** [comment]
My Chrome version is 46.0.2490.33 beta-m, the latest to date.
My problem is that I can't go to *not started* to *completed* in a small time interval.
For example, if I change the subtask to *started* and then click again to change it to *completed* it'll not work. But if I try it again in the next day (maybe a couple of hours later?), it works.

**Comment by donpatzone** [comment]
Did you try with an alternative browser?
If you use extensions, did you try to disable them? You use the beta version of Chrome. Does it work with the stable release?

**Comment by oxydron** [comment]
Same problem on Firefox 41.0 (no extensions).
Clicking on a *completed* task doesn't change its status ever and, **curiosly**, when I click on a completed subtask, it scrolls the page until the end.

**Comment by donpatzone** [comment]
What web server do you use?

**Comment by oxydron** [comment]
Apache 2.4.16 Win32 (x86)
PHP 5.6.13 Thread Safe x86

Important to note that I can do the status change from the general view, the problem only occurs when I'm inside a task.

![kb](https://cloud.githubusercontent.com/assets/331134/10100233/7d21939a-6366-11e5-991b-7d161c25c4ea.png)

**Comment by fguillot** [comment]
Try to upgrade to the latest version of KB.
