### ISSUE TITLE
Move subtasks need to be easier

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#1086]
Hello!

Currently we need to click on **Move Up** or **Move Down** to move sub task.
Would be nicer and easier if we could only click and drop it on the right place.

Best regards o/

**Comment by DoumeDuSud** [comment]
+1 pour cette possiblité

**Comment by fguillot** [comment]
It's available.

**Comment by DoumeDuSud** [comment]
merci beaucoup pour tout ce beau travail @fguillot
