### ISSUE TITLE
Closed tasks link renders page not found

### ISSUE THREAD

**Issue by josejfernandez** [fguillot/kanboard#1087]
Hi,

This happens in 1.0.17. This is what I've done:

1. Create a project.
2. Create 2 tasks.
3. Close one of them.
4. Go to project > settings at http://localhost/kanboard/project/1
5. See that Kanboard lists them ok: 1 tasks on the board, 1 closed tasks
6. Click on "1 closed tasks", which points to http://localhost/kanboard/?controller=project&action=tasks&project_id=1
7. See the error page: Page not found!

Looking at the code, there's no tasks() in Project.php controller.
PS: the software is awesome and incredibly useful.

**Comment by fguillot** [comment]
It's was already reported and fixed, see https://github.com/fguillot/kanboard/issues/1063

Thanks
