### ISSUE TITLE
nginx rewrite rule?

### ISSUE THREAD

**Issue by lifehome** [fguillot/kanboard#1089]
Can't see it anywhere, nor I could convert the rewrite rule from .htaccess...
Any idea to do so?

**Comment by RemiZOffAlex** [comment]
Nginx not work with .htaccess!

https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

**Comment by fguillot** [comment]
I will update the doc when I will have 5min to test with nginx.

**Comment by fguillot** [comment]
This config is working for me: https://github.com/fguillot/kanboard/blob/master/doc/nice-urls.markdown#nginx-configuration-example
