### ISSUE TITLE
Not able to get the home page on local server

### ISSUE THREAD

**Issue by kunal382** [fguillot/kanboard#1102]
Hello Team,

I have prepared inhouse server (Cent OS 7) to test the functionality of Kanboard and all seems to be installed correctly and configured as per the instruction given on the kanboard page.

When i tried accessing the server via web browser it is showing only files & folders inside kanboard directory. Which is reflecting in link given below.

Can someone please help me as to where and what steps I might have missed?

![image](https://cloud.githubusercontent.com/assets/13808928/9288650/dea60f64-436e-11e5-9d46-24fdeb1f085b.png)

Please let us know if any more information is needed.

Regards,
Kunal Desai

**Comment by kunal382** [comment]
Can someone please help me here?

**Comment by froschdesign** [comment]
This is a problem in your server configuration and has nothing to do with Kanboard.

**Comment by kunal382** [comment]
Can you please give me some hints where i might be wrong? So will concentrate there...

Thanks in advance.

**Comment by froschdesign** [comment]
Please look into the docs of your web server. (e.g. [Apache - DirectoryIndex Directive](https://httpd.apache.org/docs/2.4/en/mod/mod_dir.html#directoryindex))

After this, please close this issue. This is not a support forum. Thanks!

**Comment by fguillot** [comment]
If you follow this documentation that should work: https://github.com/fguillot/kanboard/blob/master/docs/centos-installation.markdown#centos-7

**Comment by kunal382** [comment]
fguillot - Thanks for the link. I already prepared my server with the help of above link only.

Still getting the same screen as above. Any more suggestion?

**Comment by fguillot** [comment]
1. Check if php is correctly installed: create a phpinfo.php file with `<?php phpinfo(); ?>` and open it in your browser, that must works
2. Check that DirectoryIndex directive in your Apache is correctly configured

**Comment by kunal382** [comment]
Thank you so much actually there was 1 php package was missing i have installed that and all are fixed now.

Thanks again.
