### ISSUE TITLE
New automatic action

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1108]
Would it be possible to have an automatic action along the lines of "Start a task" - so, say, when I move a task in to a given column, it will set the start date?

**Comment by fguillot** [comment]
There is already one automatic action to set automatically the start date?

https://github.com/fguillot/kanboard/blob/master/docs/automatic-actions.markdown#i-want-to-set-the-start-date-automatically-when-the-task-is-moved-to-the-column-work-in-progress

**Comment by AlgyTaylor** [comment]
You're right, I'm blind ;)
