### ISSUE TITLE
Update the "Closed date"

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#1115]
The "Closed date" of task is used in the calendar view which is good. However, I often forget to close a task just when it is finished. Therefore I can't use the calendar view to remember when exactly I did a task.
It may be useful to add the possibility to update the "Closed date" on closed tasks. In the "Update task" view for example, or near the "Start date, Time estimated, ..." in the header of the task view, or anywhere else.

**Comment by fguillot** [comment]
Duplicate with #419
