### ISSUE TITLE
Important Security Error (v.1.0.17): Chang task_id in URL to get forbidden tasks

### ISSUE THREAD

**Issue by Smiles123** [fguillot/kanboard#1118]
Important Security Error (v.1.0.17):
If you change the tast_id of any (and change the project_id to a project, where you have the permission) url, you can view and edit every task without the need of any permissions.
With this you can change informations of projects you aren't even allowed to view.

PS: Do not use this trick to gather or change information without permission.

**Comment by fguillot** [comment]
It's already reported and fixed, see #1080

**Comment by Smiles123** [comment]
Perfect, sorry, i haven't found that one with search... thanks for the quick reply :)
