### ISSUE TITLE
Add a screenshot broken?

### ISSUE THREAD

**Issue by cesaric** [fguillot/kanboard#1119]
I'm on a Mac (10.9.5).  Adding a screenshot via paste in Firefox (v 40.0) and Safari (v 7.1.8) might be broken.  

In Chrome (v 44.0.2403), it's working fine.

In Firefox, pasting a screenshot doesn't render the image.  It does add what appears to be a plain white image but it appears to crash something; rendering the "save" or "cancel" button impotent.  I did find this online example which works for me in Firefox: http://codingmiles.com/demo/editable_div_paste/   So I'm assuming it's a fixable bug.

In Safari, the image will paste but it won't save.  I've never tested in Safari so I'm not sure if it ever worked.

All tests were against commit 104f692 (latest pull at the time of this writing).

**Comment by fguillot** [comment]
- That never worked with Safari since beginning, if someone have a workaround...
- You are right, it's broken at the moment with Firefox 40.0 on Mac OS, I will try to fix that in the next couple of days

**Comment by fguillot** [comment]
- It's now fixed in master for Firefox 40.
- This feature doesn't work with Safari due to this bug in webkit: https://bugs.webkit.org/show_bug.cgi?id=49141
