### ISSUE TITLE
Jabber serveraddress syntax check fails

### ISSUE THREAD

**Issue by Smiles123** [fguillot/kanboard#1120]
Filled the Jabber integration form of the Project and it wont allow server-domain...
![server-addressuberprufung](https://cloud.githubusercontent.com/assets/13852001/9356220/933e9fbe-467f-11e5-83fb-181672b3f040.png)

**Comment by fguillot** [comment]
Example? How to reproduce your issue? What is the exact problem?

**Comment by Smiles123** [comment]
for example i have put in the data for our local jabber server which is jabber.example.office
and tried to save the configuration the example how i typed the address is in the screenshot above...

**Comment by fguillot** [comment]
If you enter something like `tcp://jabber.example.office:5222` that should work. What is the issue exactly? error message?
