### ISSUE TITLE
Rounding Gantt Percentages and Default filter on board/gantt chart 

### ISSUE THREAD

**Issue by flyingwhalebone** [fguillot/kanboard#1124]
I just wanted to open by saying that Kanboard is absolutely fantastic. My team was playing around with Redmine/Openproject but we are liking this a lot better.

We are currently running a version of the nightly build so we can get access to the Gantt chart, however we have noticed two issues.

1.) If you add an odd number of columns to a project, and this results in a percentage with a repeating decimal, then percentages on the gantt chart go out to the 8th or 7th decimal place. So progress shows as 33.333333333333%. We found that we were able to fix this by adding a round() to the GetProgress function in model\tasklist.php 

2.) The next thing we noticed is that even when a task is placed in the final column, it only shows as 75% or 83% done. Never 100%. Looking at the code, we found a line that says Closed Task Status = 100%. But when you close a task, it disappears from the gantt chart AND all the analytics. 

I believe this might have something to do with the way kanboard defaults to filter:open. Im going to admit that my php is weak but Im wondering, is there a place somewhere in to code to change the default filtering behavior from open to all and would this change how the analytics and gantt filter works, so that closed tasks still show up? 

Thank you for your time.

**Comment by fguillot** [comment]
Both issues you have mentioned are fixed in the dev branch. The progress is rounded and task closed are shown now.

The Gantt chart feature is not yet ready, the development still in progress.

Thanks.
