### ISSUE TITLE
Keyboard shortcuts doesn't work

### ISSUE THREAD

**Issue by alishir** [fguillot/kanboard#1129]
Recently I upgrade kanboard to 1.0.17, but unfortunately keyboard shortcuts doesn't work to switch between calendar view and list view.

**Comment by fguillot** [comment]
It works for me with Firefox/Safari/Chrome/Internet Explorer under Mac OS and Windows.

**Comment by alishir** [comment]
I am using Debian Jessie with Iceweasel. The shortcut is "v<space>c" am I right?

**Comment by fguillot** [comment]
It's `v then c` or `v l`, `v b` (do not press both keys in the same time)

**Comment by alishir** [comment]
I also checked Chromium, and it doesn't work.

**Comment by alishir** [comment]
keyboard shortcuts work for each project, but it is not work on dashboard page.

**Comment by fguillot** [comment]
The keyboard shortcuts you have mentioned above will work only where the "view switcher" is present. That will not work on the dashboard.

**Comment by alishir** [comment]
Thanks for your explanation. There is some similarity in dashboard and individual project pages, so I thinks adding shortcuts on dashboard will be a good feature.
