### ISSUE TITLE
kanboard + ssl proxy

### ISSUE THREAD

**Issue by ShinyShrimp** [fguillot/kanboard#1130]
hi,

I used version 1.0.12 with my ssl-proxy and this works like charm but now I tried to to use the current version 1.0.17 and ssl-proxy is not working. first it is loading the site but without css and if I click something I get this: 
![image](https://cloud.githubusercontent.com/assets/11614619/9418827/2512c298-4857-11e5-87cf-7c27d7c7fa64.png)

url is wrong it should be https://ssl-account.com/taskboard.jan-asmuth.de/...

what can I do?

**Comment by fguillot** [comment]
Did you try to define the url in settings > application url?

**Comment by ShinyShrimp** [comment]
yes but the problem still remains

![image](https://cloud.githubusercontent.com/assets/11614619/9494244/37884b1c-4c05-11e5-988c-6b809299fb82.png)
![image](https://cloud.githubusercontent.com/assets/11614619/9494260/4862a1bc-4c05-11e5-9253-505d98886e34.png)

**Comment by fguillot** [comment]
The error message is related to Apache and not Kanboard.
