### ISSUE TITLE
Make link to documentation in params

### ISSUE THREAD

**Issue by skobeo** [fguillot/kanboard#1131]
hi,
first, fantastic job. KB is great!
would it be possible to have all links to kb.net/documentation in a config param to be able to host the proprer documentation ?

thx

**Comment by fguillot** [comment]
I already plan to have the documentation embedded into Kanboard itself.

**Comment by fguillot** [comment]
The doc is now part of Kanboard.

**Comment by xtrails101** [comment]
I know this is closed but in 1.0.18 there is only al link to the doc in the admin settings. There is no prominent link on the dashboard. That would make it easier for normal users to find the documentation.

Maybe you can add a small question mark on the top right?
