### ISSUE TITLE
Set session name in config.php

### ISSUE THREAD

**Issue by marienfressinaud** [fguillot/kanboard#1132]
I'm working on a specific multi-users installation of Kanboard where each user owns its Kanboard data (one SQLite file per user).

In few words, here is how it works:

- One Kanboard installation
- A "users" directory which contains database and files for each user
- A specific URL (e.g. "kanboard.exemple/u_my_user") loads information for corresponding user (e.g. "my_user") thanks to a specific `config.php` file

My problem is when a user is logged in an instance of Kanboard, he is logged in for *all* instances (because there is only one installation of Kanboard of course). To fix this, I need to set dynamically the session name.

Steps to fix it:
- In `config.php`, add a `SESSION_NAME` constant (I guess we need to add it to `app/constants.php` and `config.default.php` too to do it properly)
- In `app/Core/Session.php`, [line 61](https://github.com/fguillot/kanboard/blob/master/app/Core/Session.php#L61), use `SESSION_NAME` instead of `__S`

Tell me if you're interesting and I'll do a PR.

**Comment by marienfressinaud** [comment]
I just realised that my work is not working anymore with Kanboard 1.0.17 (I was working with 1.0.16) because links are absolute now (so "/u_my_user" is removed). I will probably use subdomains instead and so this ticket is not required anymore for my work.

**Comment by fguillot** [comment]
If it's not required anymore, I closed it.
