### ISSUE TITLE
Allow regular users to create group projects

### ISSUE THREAD

**Issue by mogthesprog** [fguillot/kanboard#1133]
First of all, love this software. Cracking job. :)

At the moment if you want a user to be able to create a group project then they need to be an administrator. It would be great if a regular user could create a project and invite other members of kanboard to work on the project too. If they are an administrator then they have access to every project, which isn't ideal.

**Comment by fguillot** [comment]
In the current development version a new role "Project Admin" have been introduced to solve this issue. It's a group to allow people to create multi users projects but they cannot change application settings.

**Comment by mogthesprog** [comment]
Great stuff :) Exactly what i was looking for.

Thanks for the speedy response.
