### ISSUE TITLE
Bug - Changing name of files which has first cyrilic word in its name

### ISSUE THREAD

**Issue by Folcky** [fguillot/kanboard#1136]
Hi!

I tried to attach a file to my task, for example **"Оценка.xlsx"** and as a result I have the file **".xlsx"** atached without first word...
If "_" added to the begining of the name(_Оценка.xlsx), name will not be changed.

Here it is screenshot, when I attached 2 files: **"Постановка задачи.docx"*** and "_Постановка задачи.docx"
In first case we have **"задачи.docx"** atached (...

![image](https://cloud.githubusercontent.com/assets/758787/9466317/a2634708-4b3c-11e5-823a-3ba0e84cac9e.png)

Thank you for solving it

**Comment by fguillot** [comment]
I reproduced your issue and it's now fixed in master.

Thanks for reporting that.

**Comment by Folcky** [comment]
Super!
