### ISSUE TITLE
Strange / rare bug: Apache crashing

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1140]
I have a really, really peculiar bug going on, which is causing Apache to crash!

First, the server set up:
- Windows Server 2008 Standard Edition Service Pack 2
- Compiler: MSVC11 (Visual C++ 2012) 
- Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.15 
- PHP 5.5.15
- Postgres 9.4

The problem row (id 666 - it had to be, didn't it? ;-)) appears to be in the Tasks table:

    666;"Fix validation emails";"''";1440573696;"red";2;6;2;3;TRUE;;0;0;4;2;1440582167;"''";1440582167;0;0;4;1440583931;0;0;0;0;0;;

caused when I access via http://--host--/project/2/task/666

Apache gives these helpful details:

    Problem signature:
      Problem Event Name:	APPCRASH
      Application Name:	httpd.exe
      Application Version:	2.4.10.0
      Application Timestamp:	53c79afa
      Fault Module Name:	php5ts.dll
      Fault Module Version:	5.5.15.0
      Fault Module Timestamp:	53d03624
      Exception Code:	c00000fd
      Exception Offset:	0011ee72
      OS Version:	6.0.6002.2.2.0.16.7
      Locale ID:	2057
      Additional Information 1:	ce16
      Additional Information 2:	66b0df064fd5c5f2376a115b922f4999
      Additional Information 3:	b8b5
      Additional Information 4:	0cc1be44f0f94ac4e74c589b1d57128d

It only occurs when accessing that task, not seen it before anywhere. Let me know if there's any other details I can furnish you with ... I imagine this one is going to be a difficult one to sort out!!

**Comment by AlgyTaylor** [comment]
Associated data in comment column, possibly be related (also crashes when I try to preview the comments):

    1634;666;2;1440585992;"Moved to column Work in progress";""
    1632;666;2;1440583931;"Moved to column Priority";""
    1630;666;2;1440582356;"Registration email has errors, see below
    1629;666;2;1440582167;"Moved to column Work in progress";""
    1625;666;2;1440581544;"Moved to column Priority";""
    1623;666;2;1440580742;"Moved to column Work in progress";""

**Comment by fguillot** [comment]
Do you have anything in the Apache error log?

**Comment by AlgyTaylor** [comment]
Crashed again today ... had a look at the error log, it was exiting with 
   Parent: child process exited with status 3221225725

In case anyone else runs in to this, turns out Apache on Windows has a low default stack size, and you can fix it by upping it a bit, adding the below to the bottom of httpd.conf (or something similar):

    
    <IfModule mpm_winnt_module>
       ThreadStackSize 8888888
    </IfModule>

 :)
