### ISSUE TITLE
Feature or BUG solving request - Search task by title is unsuccess (

### ISSUE THREAD

**Issue by Folcky** [fguillot/kanboard#1141]
Hi!
I have read article "Advanced Search Syntax" http://kanboard.net/documentation/search 
**Search by task id or title**
Search by task id and task title: 123

But as I understand it works sql like '123%' and not as '%123%'.

For example If I write "50259" in filter field, I will not find "ITGC 50529 - blabla" task in title. And If I write "ITGC 50529", task  with title "ITGC 50529 - blabla" will be finded! )

Thank you for solving

**Comment by BlueTeck** [comment]
Are you using the dev version or stable? This change is only in the dev version at the moment.

**Comment by Folcky** [comment]
Strage I am using https://github.com/fguillot/kanboard/archive/master.zip downloaded 24.08.2015

**Comment by fguillot** [comment]
Already fixed, see #1064
