### ISSUE TITLE
Dragging issues on tablets

### ISSUE THREAD

**Issue by jvlekken** [fguillot/kanboard#1142]
First of all: Great job on this application Frédéric, it has been working great so far.

I only have a small issue when using the drag drop functionality on an iPad, which doesn't seem to work.

The dragging works well on desktop so I thought it was not yet supported, but I just found out that the online demo of kanboard does not have this issue.
So I guess I'm missing something on my side.

Does anyone have seen similar issues? I'm not noticing any error indications.

Kind regards!

**Comment by fguillot** [comment]
Which version of Kanboard are you using?

If you are using the last dev version, it's normal I removed the touch features to avoid accidental moves until I found a better solution.

**Comment by n1trux** [comment]
I think you could implement a click-n-hold functionality (a second?) if a mobile browser is detected.

This way you won't move the cards accidentally and are still able to do so.

**Comment by fguillot** [comment]
There is now a special icon to move task on touch devices to avoid accidental moves. At the moment, this is only solution I found to be compatible with column scrolling, jquery sortable and touch events.

@n1trux it was the first solution I tried but that was not working with individual column scrolling

If someone have a better solution, send a pull-request :)
