### ISSUE TITLE
Incorrect task count on dashboard

### ISSUE THREAD

**Issue by mrozigor** [fguillot/kanboard#1143]
I have a few projects on dashboard with few tasks every. There are also few closed tasks in 'Done' column, but they are not counted in dashboard 'My Projects' -> 'Columns' summary (they are counted in project summary).

**Comment by fguillot** [comment]
Only open tasks are displayed/counted on the dashboard. This is the expected behavior.

**Comment by mrozigor** [comment]
Ok. Thanks for answer ;)
