### ISSUE TITLE
Add description field to swimlane

### ISSUE THREAD

**Issue by fabiano-pereira** [fguillot/kanboard#1144]
It would be nice to have a Description field when creating swimlanes, similar to the one available when creating tasks.

I volunteer myself to implement this change, if the feature request is accepted.

**Comment by fguillot** [comment]
The pull-request will be accepted if you respect the same logic as the existing code base. I think that should be similar to the project/column/category descriptions (display that in a tooltip).

**Comment by fabiano-pereira** [comment]
I am implementing this new field.
As a new column "description" must be created in the "swinlanes" table, where can I add this information so that existing instalations can be properly updated? Is there a db structure verification script, or just a note in the ChangeLog does the trick?

**Comment by fguillot** [comment]
Add a new migration: https://github.com/fguillot/kanboard/tree/master/app/Schema

**Comment by fabiano-pereira** [comment]
I've just noticed I forgot to update the file "app/Api/Swimlane.php". As the changes are simple, do you want me to create another pull request, or you will add these missing changes during the merge?

**Comment by fguillot** [comment]
Add the missing part to the existing pull-request if possible.

**Comment by fabiano-pereira** [comment]
Done.

**Comment by fguillot** [comment]
It's merged. Thanks
