### ISSUE TITLE
Search comments

### ISSUE THREAD

**Issue by mursonic** [fguillot/kanboard#1145]
Would it be possible to search within the comments?

Thanks a lot!

**Comment by tloehr** [comment]
oh yes. i would like this function, too.

**Comment by HenLab** [comment]
vote for this!

**Comment by deliciousbob** [comment]
That would be great :) a global search for comments would really be a nice and helpfull feature

**Comment by froggay** [comment]
indeed, it would be a great addition !

**Comment by fguillot** [comment]
It's now possible in the development branch.

**Comment by OWENCRUZ** [comment]
Waiting for this feature.
