### ISSUE TITLE
Page refreshes after toggling sub-task status

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#1148]
Hi,

first of all, thanks for the effort you put into this program. I 

It is rather a small issue.
I have a task with many sub-tasks. When I complete the sub-task the page does a complete refresh and I have to scroll down again to the next task in the list.
The same applies when I try to rearrange them 

Would it be possible to only refresh the state of the individual task instead of the whole page?

Thank you!

**Comment by fguillot** [comment]
It's now available in the master branch.
