### ISSUE TITLE
Import Option

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#115]
HI

There must be option to import tasks from the excel sheet, and there must be option to bind fields while importing like the project name, task name, assignee, column, coulur, due date etc

**Comment by bastiao** [comment]
True story and makes life easier to use an API when creating the Webhooks I think?

**Comment by iM4rv** [comment]
Any importfeature available yet?

**Comment by sparkles645** [comment]
@ashbike made this a while ago - 
https://github.com/ashbike/csv2kanboard>

**Comment by reachingmike** [comment]
Does https://github.com/ashbike/csv2kanboard still function - it hasn't been updated for some months and I have to admit - I haven't been able to get it to import. It would be great to have this as native functionality.

**Comment by ashbike** [comment]
It does. You see an error while importing?

**Comment by reachingmike** [comment]
No error - I'm probably using it wrong. I downloaded an existing install to my laptop and ran the command in terminal as I don't have ssh access to the server at the moment - the script did output 'Finished' to the terminal though.

**Comment by fguillot** [comment]
There is now a basic CSV import for tasks in the development version.

More complex solution (Excel import or automated import etc..) have to be done with plugins or with an external script.

**Comment by OWENCRUZ** [comment]
Hi @fguillot , any news about this important feature? +1 on this.
