### ISSUE TITLE
no notifications

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1150]
they are enabled but nothing happens. Where can I check if I'm missing something.
Thanks

**Comment by Little-Ben** [comment]
Check the cofig file, if email is properly configured

**Comment by thob** [comment]
done this and changed it to smtp. let's see.
_comments should trigger a notification, right?_

**Comment by Little-Ben** [comment]
Jap. But no notifications are sent for your own actions. So test it with another account.

**Comment by thob** [comment]
nope. doesn't work. do I miss something.

**Comment by thob** [comment]
these are my setting in config.php
`// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'smtp');`
`// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'smtp.gmail.com');
define('MAIL_SMTP_PORT', 465);
define('MAIL_SMTP_USERNAME', 'nnnnnn@gmail.com');
define('MAIL_SMTP_PASSWORD', 'xxxxx');
define('MAIL_SMTP_ENCRYPTION', tls); // Valid values are "null", "ssl" or "tls"`

do I miss something?

**Comment by Little-Ben** [comment]
Try SSL instead of TLS. 465 is the SSL port, see
https://support.google.com/a/answer/176600?hl=en

**Comment by thob** [comment]
thanks. made my day! Still wondering why the default notifications didn't work.
