### ISSUE TITLE
different database schema : use column fields

### ISSUE THREAD

**Issue by mslokhat** [fguillot/kanboard#1151]
Hi,

i'm thinking of integrating Kanboard with an existing application (namely corebos - vtiger) which have his own database structure on project, task, milestones,... 

I see in the models that you have hard coded the fields and tables names . 

what would be in your opinion the best way for using the sames tables without breaking any of the 2 applications ?

Table Project :
field : id     ===> projectid
field : name ===> projectname

my idea :
1. use an array of fields in config file 
ex : project['id'] = 'projectid';
project['name'] = 'name'; 
project['table'] = 'project'; // Project table name

2. use the webservices at kanboard side (ie modifiy the models) : Kanboard to corebos
and json api at corebos side : corebos to kanboard.

Thanks & Rgds

Said

**Comment by froschdesign** [comment]
> what would be in your opinion the best way for using the sames tables without breaking any of the 2 applications ?

Using the same database and the same tables? This will break the applications!

The solution is already there: [Json-RPC API](http://kanboard.net/documentation/api-json-rpc) and [Webhooks](http://kanboard.net/documentation/webhooks)

**Comment by mslokhat** [comment]
Hi,

if i understand :
An external URL can be called automatically when an event occurs in Kanboard
there's no event for project creation though

do you have any complete sample how it works (webhook) and what it should return ?

**Comment by mslokhat** [comment]
Hi, i got it finally, thanks
