### ISSUE TITLE
IMP - KB 1 0 18 - Gantt view makes scroll bar for long task titles

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1153]
* Been playing around a bit with the Gantt view, 
* really like the Gantt approach for team planning purposes.

Improvement:
* **If the title of the task is long, the gantt view creates a scroll box which covers the text.**
**See left side of screenshot**

![2015-08-30_22-42-14](https://cloud.githubusercontent.com/assets/10092252/9569362/d6740caa-4f68-11e5-9094-a9431a650528.png)

**Comment by fguillot** [comment]
Are you using Windows? which browser?

**Comment by Inawire** [comment]
I get this in Firefox 40.0.3. Forced me to de-verbose a few of my Task titles (which was probably good).

**Comment by sparkles645** [comment]
Windows.
Firefox 40.0.3

**Comment by sparkles645** [comment]
Same result with with IE v 11.0.96

**Comment by fguillot** [comment]
This issue is fixed in the development branch. (tested only with IE11 at the moment)
