### ISSUE TITLE
Allow multiple private projects with same name

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#1155]
Hi,

I wanted to ask it is possible to allow multiple ___private projects___  with the same name each created by a _different_ user. Currently you get the error "_This project must be unique_", which is perfectly understandable for open projects.  

An idea would be that the first of those private projects to become open should be able to keep the name on a "first come, first serve" basis while other private projects must be renamed by the respective project manager, if they want it to be open as well so as to not running into naming issues.

Would that be possible?

Best Regards

**Comment by fguillot** [comment]
The last development branch allow multiple projects with the same name.

See the ChangeLog for more info: https://github.com/fguillot/kanboard/commit/adb35896d8c5bcc6673188921868e472ba35278e#diff-02f0b547c2779d25cff89672135f20e3R6
