### ISSUE TITLE
Notifications via SMTP - Links in email footer not working correctly

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#1157]
Hi,

I just enabled SMTP notification within our Kanboard installation and so far it working as expected. However each email has two links, which give direct access to the relevant task or board. Those however do not work.  
Upon closer inspection I noticed that the URL used is invalid - a slash is missing.

Instead of showing https://example.com/project/1/task/22 it is https://example.__comproject__/1/task/22
and https://example.com/board/1 it is https://example.__comboard__/1

I have URL rewrite enabled in the config.php file. When I disable it it works as expected.

Best Regards

**Comment by fguillot** [comment]
Did you set a slash at the end for the application url in settings?

**Comment by donpatzone** [comment]
Yes, 
this is my config
```httpd.conf
<VirtualHost *:443>
    ServerName kanboard.local/
    DocumentRoot "C:/web/kanboard/"
    SSLEngine on 
    SSLCertificateFile {PathtoCert}
    SSLCertificateKeyFile {PathtoCertKey}
    <Directory "C:/web/kanboard">
        AllowOverride all 
        Order Allow,Deny
        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by fguillot** [comment]
You don't need to have a trailing slash for the ServerName in your Apache config. I was talking about the Kanboard configuration: settings > application > application url.

**Comment by donpatzone** [comment]
That was indeed the problem. Thank you for the help.
