### ISSUE TITLE
swimlanes are fixed height. they used to be height according to tasks?

### ISSUE THREAD

**Issue by lbtw** [fguillot/kanboard#1159]
swimlanes were sized to the height of the tasks in them in 1.0.15

in version  1.0.18 they are fixed height

**Comment by fguillot** [comment]
Yes, and what is the problem with that?

**Comment by lbtw** [comment]
This results in less content on screen and reduces the utility of collapsible tasks. All of which I really appreciated.

**Comment by McodeMe** [comment]
A workaround to get the old behaviour:
- get development version
- edit  assets/js/src/Board.js and remove or comment line where fixed height of 500 is set
```javascript   
 Board.prototype.resizeColumnHeight = function() {
            [..]
            if ($(this).height() > 500) {
              //   $(this).height(500);           -- comment this line
            }
```
- return to kanboard directory and *Make js* to create new **app.js**
  Hint: On my Debian installation i had to change  yuicompressor to yui-compressor in the **Makefile**.
- copy the new assets/js/app.js into your running installation

**Comment by sparkles645** [comment]
* Agree with @lbtw - I now have to do more scrolling - and the majority of the swimlane is blank space.
* This alters the user experience.
* Personally I enjoyed the board more when it  automatically "contracted" the height according to the size of the tasks in the swimlane

**Comment by mrfyx** [comment]
Agree with previous comments, if there are too much tasks in a swimlane, a scroll bar appears. If there are few tasks in the swimlane, there is lot of empty space. It is not user friendly.
I hope this behavior can be configure in the next release in the setting for example.

**Comment by froschdesign** [comment]
> I hope this behavior can be configure in the next release in the setting for example.

Oh no, not an extra setting! Automatically height is good.

**Comment by c99ipnerd** [comment]
I also would love to have this back too. Maybe the fixed height could go into the compact view action.

**Comment by sparkles645** [comment]
+1 for making it a setting, since keeping fixed height appears to be the direction.
Having issues getting accustomed with the fixed height - especially for boards with many swimlanes.

**Comment by mn26826** [comment]
Auto-height is the better way IMO. Maybe in combination with a max-height. Are there more tasks that need more space there could be a scrollbar inside the cell or an "expand"-link to deactivate the max-height style...

**Comment by fguillot** [comment]
There is a toggle switch now in the dev version.

**Comment by sparkles645** [comment]
Thank you.
Tested - feels like home again. 
=)
