### ISSUE TITLE
Dependencies graph

### ISSUE THREAD

**Issue by xavividal** [fguillot/kanboard#1165]
Will be great to have a page where you can view visually as a tree the dependencies between tasks.

**Comment by xavividal** [comment]
If I have enough time I will do a fork and develop some ideas related to this feature request.

**Comment by SR253** [comment]
+1

**Comment by kwijk** [comment]
See also #901 that describes the same thing

**Comment by xavividal** [comment]
![graph](https://cloud.githubusercontent.com/assets/176446/10157859/1c8a0e88-668e-11e5-8067-b7003537ef71.png)

I've a version running on my fork ("graph" branch). What do you think? I'm using "visjs" library and rendering the tasks with links (and additional info on tooltip)

**Comment by kwijk** [comment]
Whow, thats cool and is very visual!  
Something like this would be very useful in creative sessions where projects are discussed by a team and new ideas are worked out from a vague course idea to detailed Tasks.
Would be great if in such a view:
- user could add an item 
- user could set the relation between two items.
- do the above two in one go, e.g by right clicking an item and selecting 'add child' from a menu..

The view reminds me very much of a mindmap..... also very useful for creating Tasks in a brainstorm session.

**Comment by xavividal** [comment]
Yeah, creating new tasks from visual nodes is possible. Needs some work on events and stuff like this.

The first milestone will be the read-only version.

Later, we can improve it with more features.

At now, I'm using the hover event to show additional task info (points, assignee, project, etc.)

In a few days I'll have the pull request ready to pass to @fguillot 

Thanks for checking out !

**Comment by xavividal** [comment]
Ah, the library used is http://visjs.org if somebody want to play around and throw more ideas.

**Comment by SR253** [comment]
Looks really great!

**Comment by fguillot** [comment]
It's very nice but I think that would be a good candidate for a plugin. In the current development branch, there is a very first version of a plugin api and I started to move some features to plugins to have a smaller code base.

The plugin documentation is here: https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown

To add the menu is the sidebar, you can use the hook "template:task:sidebar:information" and the rest of the code can be moved easily.

There are some plugin examples here: https://github.com/kanboard/

**Comment by froschdesign** [comment]
>  I think that would be a good candidate for a plugin.

:+1:

**Comment by xavividal** [comment]
Ok, I'll wait for a stable release of plugin architecture. Next version, maybe?

**Comment by iPublicis** [comment]
+1

**Comment by DevOps-Haze** [comment]
This sounds exactly like what our DevOps team is looking for. Is this plugin available yet ?

**Comment by xavividal** [comment]
Nope yet, now the Plugin API is stable I'll port the this plugin soon.

**Comment by robclarkey** [comment]
+1 for this too. Look forward to seeing it as a plugin!

**Comment by xavividal** [comment]
Hi, this is a first version of this feature using a plugin (0.0.1).

https://github.com/xavividal/kanboard-plugin-relationgraph

Feel free to use, comment, create issues, etc...

**Comment by xavividal** [comment]
Hi @fguillot, you can close this issue if you want. Any improvement to this plugin will be done there.

Thanks !
