### ISSUE TITLE
[1.0.18][Bug] Task dropdown menu in Board View enclosed within column

### ISSUE THREAD

**Issue by 0xff-fanatic** [fguillot/kanboard#1166]
Hi. As of 1.0.18, in Board View the task dropdown menu seems to be clipped by the column boundaries. I don't recall this being an issue in 1.0.17 - I didn't notice the dropdown menu being clipped then.

Repro:
*(Tested on IE 11 and Chrome 45)*
1. Create any task via the '+' button in the Board View.
2. Click the task ID of the created task to invoke the dropdown menu.

![image](https://cloud.githubusercontent.com/assets/14084369/9621556/659f1f94-515a-11e5-93a9-b33ceb60c4d7.png)
*This issue becomes obvious in Compact View.*

**Comment by akluthe** [comment]
I'm having a vertical version of this.


![initial](https://cloud.githubusercontent.com/assets/2624953/9666598/b81758bc-523c-11e5-8fbc-c599d68e7fd4.PNG)
![scrolled](https://cloud.githubusercontent.com/assets/2624953/9666600/b9a0379e-523c-11e5-887e-1bbff12dd5f6.PNG)

**Comment by fguillot** [comment]
It's fixed in the dev branch. That needs to be tested with several browsers but that should be ok.

**Comment by 0xff-fanatic** [comment]
Looks good on 1.0.19 now, at least on IE 11 and Chrome 45. Thanks!
