### ISSUE TITLE
Edit Pinboard Form

### ISSUE THREAD

**Issue by rstoltenberg** [fguillot/kanboard#1167]
We need the following option(s) at the "edit pinboard" - form:

* on creating a new column, a button to put the column to the top of the list
* additional buttons to the existing columns to move them directly to the top/bottom of the list

**Comment by rstoltenberg** [comment]
Is it planed to implement these functionality soon?

**Comment by fguillot** [comment]
With the last version, you can change the position of the columns by drag and drop.
