### ISSUE TITLE
GitLab : External authentication failed

### ISSUE THREAD

**Issue by Gu3** [fguillot/kanboard#1168]
Hi ! 
I follow every single step of the documentation : "Gitlab Authentication", but every time the only issues is "External authentication failed" ! 
I've got a self-hosted gitlab, kanboard config file is update.
I  register the application on gitlab.

Any clues ? 

Best regards.
Vincent.

**Comment by fguillot** [comment]
Activate the debug mode to see if there is any error message in the log files. Did you link successfully your user account? the error is happening only at the login?

**Comment by fguillot** [comment]
I think you have the same issue as the ticket #1179
