### ISSUE TITLE
Gantt chart : Show project's members on grantt chart.

### ISSUE THREAD

**Issue by drasi** [fguillot/kanboard#1169]
Hi.
When I move mouse cursor over gannt chart it show start and end date.
Is it possible to show all project's members in gantt chart when mouse cursor is over it?

Best Regards

**Comment by fguillot** [comment]
It's already there for the "projects gantt chart", but not the "task gantt chart".

**Comment by drasi** [comment]
Thank you fguillot for very fast response. 
I meant in project grant chart like this.
![screenshot_2015-09-03-06-52-26](https://cloud.githubusercontent.com/assets/3869694/9647674/d7f32ae0-5209-11e5-89ed-75a249d952d1.png)

**Comment by fguillot** [comment]
It's already there:

![gantt-users-tooltip](https://cloud.githubusercontent.com/assets/323546/9695750/0dadcb52-5333-11e5-9052-7845ac023da7.png)

**Comment by drasi** [comment]
Thank you  fguillot.
