### ISSUE TITLE
404 Error after Update

### ISSUE THREAD

**Issue by deecey** [fguillot/kanboard#1172]
Hi there,
I updated kanboard to the latest version and now I get a 404 if I try to go to kanboard (also if I try to request the index.php directly, see screenshot). In winscp I see the folders and files in the second screenshot.
My old installation works fine in the same parent directory?!
Help would be very appreciated, since I'd like to use the new projectmanagement tools :-)
Thanks, Chris
![kanerror1](https://cloud.githubusercontent.com/assets/13447926/9655875/9444940c-5234-11e5-9b63-ae07b5665315.jpg)
![kanerror2](https://cloud.githubusercontent.com/assets/13447926/9655880/995c4df4-5234-11e5-94fd-03442ce5385c.jpg)

**Comment by leomelzer** [comment]
@deecey Can you double check the [`.htaccess`](https://github.com/fguillot/kanboard/blob/master/.htaccess) file was copied and is working?
You'll probably also want to copy your old, existing `config.php` to this directory.

**Comment by deecey** [comment]
@leomelzer hm, I do not use an own config.php; how can I check if .htaccess is working (it is existing on the server)? But since you mentioned it: I also have a .htaccess in the parent directory to secure the kanboard. is this a problem?

**Comment by leomelzer** [comment]
@deecey The .htaccess in the parent directory shouldn't be the problem though you could try renaming it temporarily to foo.htaccess or similar. To verify mod_rewrite works at all, check your phpinfo() or php.ini if you have access to that. StackOverflow has plenty posts on how to verify it is working, e.g. https://stackoverflow.com/questions/9234289/verify-if-htaccess-file-is-running

**Comment by deecey** [comment]
@leomelzer I got it: deactivated the .htaccess in the kanboard folder and have it activated in the parent folder.. Thanks a lot for your help!
BR, Chris

**Comment by Torsten-K** [comment]
In my case, it helped to write the following into the .htaccess, after the line RewriteEngine On:  

    RewriteBase /
