### ISSUE TITLE
Additional vertical scrollbar with collapsed columns

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1173]
An additional vertical scrollbar appears if at least 1 column is collapsed and one swimlane has so many taskitems that it gets it's own scrollbar. This vertical scrollbar seems to serve no purpose since the browser-scrollbar would do the same.

__no collapsed column & no items__
everything is fine. Also no problem if columns would be collapsed now.
![kanboard columns without scrollbars](https://cloud.githubusercontent.com/assets/13346344/9661661/f88fbe74-525b-11e5-8533-deb8eebbff5f.png)

__no collapsed column & many items__
so fields get their own scrollbars
![kanboard columns with scrollbars](https://cloud.githubusercontent.com/assets/13346344/9661687/1e60b6bc-525c-11e5-90a1-da7f238ff8a6.png)

__collapsed columns & many items__
the highlighted scrollbar appears.
![kanboard collapsed columns with scrollbars](https://cloud.githubusercontent.com/assets/13346344/9661728/592cf67a-525c-11e5-8f9b-5ea904ed06d2.png)

**Comment by fguillot** [comment]
Which OS and browser is it?

**Comment by Chaosmeister** [comment]
Windows 8.1 with the latest chrome

Frédéric Guillot <notifications@github.com> schrieb am Fr., 4. Sep. 2015
01:05:

**Comment by Chaosmeister** [comment]
It may be important that the collapsed column "Testing" has many items in another swimlane below.

**Comment by fguillot** [comment]
It's fixed in the development branch. The scrollbar doesn't appears anymore on Windows.
