### ISSUE TITLE
Text wraps for items in the list of filters

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1175]
With some terrible languages (such as French :) the double line spacing combined with end-of-line wrapping is problematic, as some lines are fairly long and, when they wrap, it's hard to visually distinguish items from "previous items that were wrapped":

![kanboard filters wrap](https://cloud.githubusercontent.com/assets/479401/9667583/982b5d60-524a-11e5-83b5-a0bff65020c3.png)

**Comment by fguillot** [comment]
The dropdown menu has been improved (in master):

![dropdown](https://cloud.githubusercontent.com/assets/323546/9866386/c5a227d6-5b2f-11e5-9868-3bb54209183e.png)
