### ISSUE TITLE
Strange grey bar at the bottom of each board

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1176]
I'm not sure what this is, it looks like a glitch but it's persistent and below all boards?
This is with version 1.0.18 but it was there before, too. Tested on the latest Firefox.

![kanboard grey bar](https://cloud.githubusercontent.com/assets/479401/9668152/e3935c5a-524d-11e5-9295-07a1855c3973.png)

**Comment by nekohayo** [comment]
Not totally sure, but this might be caused in part by

* overflow-x: scroll;  in #board-container
* padding-bottom: 20px;  in body
* and some other stuff?

It should be noted that in addition to the per-column scrolls that were recently implemented in 1.0.18, there seems to still be a global vertical scroll that sometimes kicks on because of this; I'm not sure if that's intentional or not?

**Comment by fguillot** [comment]
If you update KB, the horizontal scrollbar will appear only if horizontal scrolling is enabled, in compact mode that should not be visible.
