### ISSUE TITLE
Long (sub)task titles on Gantt chart will cause vertical scrolling of the title

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1177]
On some browsers, such as the GTK3-based Firefox on Linux, when a title is too long it will scroll horizontally... but the addition of that scrollbar will obscure the contents and cause vertical scroll:

![kanboard gant title overflow](https://cloud.githubusercontent.com/assets/479401/9668297/bc9a89b0-524e-11e5-854d-24d01bdc8110.png)

**Comment by fguillot** [comment]
Duplicate with #1153
