### ISSUE TITLE
Gitlab Authentication issue

### ISSUE THREAD

**Issue by CptMonkeyFist** [fguillot/kanboard#1179]
I followed the instructions for setting up Gitlab Authentication. I had a few issues. 
For the sake of protecting my installation during setup let's say my installations are located:
```
Kanboard - http://bogus.com/kanboard
Gitlab - http://bogus.com:5060
```
What I have done:
* I tried this from your instructions:
```
Go to your user profile
Click on External accounts
Click on the link Link my Gitlab Account
You are redirected to the Gitlab authorization form
Authorize Kanboard by clicking on the button Accept
Your account is now linked.
```
When I click on External accounts, nothing is displayed. This is true for the local admin account as well as the new remote account I created which has my gitlab username.

* Gitlab - Created an Admin Application for kanboard. Specified my callback url that I got from kanboard->integrations. Copied my Application Id and Secret for future reference.

* Kanboard - Created config.php from template. Modified the following:
```
define('GITLAB_AUTH', true);
define('GITLAB_CLIENT_ID', '[Copied_ID]');
define('GITLAB_CLIENT_SECRET', '[Copied_Secret]');
define('GITLAB_OAUTH_AUTHORIZE_URL', 'http://bogus.com:5060/oauth/authorize');
define('GITLAB_OAUTH_TOKEN_URL', 'http://bogus.com:5060/oauth/token');
define('GITLAB_API_URL', 'http://bogus.com:5060/api/v3/');
```
If I click on the "Login with my Gitlab Account" from my kanban installation it brings me to my gitlab login page. I log in and it takes me to the gitlab front page and doesn't redirect. If I go back to the kanban installation and click "Login with my Gitlab Account" again then I get a page from Gitlab that says, "An error has occurred. The redirect uri included is not valid."

For reference the redirect URL I am using is http://bogus.com/kanboard/?controller=oauth&action=gitlab.

**Comment by fguillot** [comment]
An issue related to Gitlab Auth have been fixed 2 days ago, a typo in external accounts template page prevents the link to be displayed.

See this commit https://github.com/fguillot/kanboard/commit/a6f6790d085d3477b9e7f1ba20abd4a051439d2d for the fix (basically rename GITHUB_AUTH to GITALB_AUTH. That should work after changing that.

**Comment by CptMonkeyFist** [comment]
I put in the code change you showed and now I do get a page that allows me to connect my gitlab account and it does say "Account linked" but when I try to login using gitlab I get the same result, "An error has occurred. The redirect uri included is not valid."

**Comment by ashbike** [comment]
Not sure, perhaps something wrong with Gitlab?

This works just fine and asks for authorization:
```
https://my.gitlab.host/oauth/authorize?client_id=XXXXXX&redirect_uri=http%3A%2F%2Flocalhost%3A81%2Ftest&response_type=code

*** Redirect URI: http://localhost:81/test. Or redirect URI: http://localhost:81/test/a=b works as well ***
```

But, not this. It shows that invalid URI message.
```
https://my.gitlab.host/oauth/authorize?client_id=XXXXXX&redirect_uri=http%3A%2F%2Flocalhost%3A81%2Ftest%3Fa%3Db&response_type=code

*** Redirect URI: http://localhost:81/test?a=b
```

It seems it does not like that ? separator. 

Running against locally hosted Gitlab 7.14.1.

**Comment by pa-de-solminihac** [comment]
I removed the `?controller=oauth&action=gitlab` part from the **Redirect URL** in my gitlab and it's ok now. Thank you @ashbike for pointing out.

**Comment by CptMonkeyFist** [comment]
Well if I remove ?controller=oauth&action=gitlab then it accepts that as a valid redirect URI but displays a different problem. If I click Authorize then it takes me back to Kanboard and Kanboard says "External authentication failed". If I click "Login with my Gitlab Account" again it loops back to the Authorize page.

I am going to post about the question mark thing on the Gitlab project page, but it's possible they don't care about resolving bugs for people using the community edition in a timely manner.

**Comment by ashbike** [comment]
Removing the query string will not work with Kanboard since it doesn't know what to do after redirection. This is essentially a Gitlab problem, and if we want to fix it, it will just be an ugly hack. Hope Gitlab fixes it.

**Comment by waja** [comment]
@ashbike do you have a gitlab issue or any other reference for this problem?

**Comment by CptMonkeyFist** [comment]
I created an [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/2443) in the repository for the community edition of gitlab. To no surprise, the Gitlab folks have done nothing with it even after a month of it sitting there. If you guys want to continue with this then I suggest you take it up with the folks at Gitlab. I have moved on from kanboard/gitlab integration.

**Comment by fguillot** [comment]
- With the last dev version, Gitlab OAuth works only if you have enabled url rewriting (nice urls).
- Gitlab doesn't seems to support callback url with query string parameters as mentioned above.

Since it's not anymore a Kanboard issue I close this ticket.

**Comment by waja** [comment]
@fguillot it would be great to have a note in the gitlab integration documentation about that.

**Comment by fguillot** [comment]
@waja it's already there: https://github.com/fguillot/kanboard/blob/master/doc/gitlab-authentication.markdown#known-issues (the doc will be synced with the website for the next release).
