### ISSUE TITLE
Nice Urls

### ISSUE THREAD

**Issue by synox** [fguillot/kanboard#118]
Hi! 

nice urls would be great, e.g. `/kanboard/board/show/1`
instead of `/kanboard/?controller=board&action=show&project_id=1`

**Comment by fguillot** [comment]
Url rewriting is now in the development branch, see here for the doc: https://github.com/fguillot/kanboard/blob/master/docs/nice-urls.markdown

Kanboard is able to work indifferently with url rewriting enabled or not.

Note: It's very alpha at the moment.
