### ISSUE TITLE
Deprecation warning $HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by mdawart** [fguillot/kanboard#1180]
I got an warning e.g. on moving cards to another column
```
Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```
Server runs PHP 5.6

**Comment by fguillot** [comment]
This issue is not related to Kanboard but to your PHP configuration.

Kanboard doesn't use `$HTTP_RAW_POST_DATA`. You should modify your php.ini with 'always_populate_raw_post_data' to '-1'.
