### ISSUE TITLE
[Impr] Don't reset Filter on Dropdown Selection

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1181]
Filter via Dropdown will reset all other filters, it would be nice, if the new filter will be added to the already selected one. This also allows multiple selections i.e. select two users or two categories.

Example:
Current behaviour:
Select User filter via Dropdown -> status:open assignee:"Timo"
Select Categroy filter via Dropdown -> status:open category:"Test"

Improvement:
Select User filter via Dropdown -> status:open assignee:"Timo"
Select Categroy filter via Dropdown -> status:open assignee:"Timo" category:"Test"

What do you think?

**Comment by BlueTeck** [comment]
-> like the Github Issue Filter

**Comment by fguillot** [comment]
users and categories dropdowns append the filters now instead of replacing evrything

**Comment by lehrhardt** [comment]
Is there a way to enable the old behavior? We use kanboard to cycle through each user tasks in the morning and the old behavior was exactly what we expected there. Now we have to reset the filter each time we switch to a different user.

**Comment by BlueTeck** [comment]
You could change the coding, it is a little change. 
https://github.com/fguillot/kanboard/blob/master/app/Template/project/filters.php#L83
Change data-append-filter to data-filter

Our you could use the new Custom filters, you could create your own filters via GUI.
