### ISSUE TITLE
[FR] Add custom filters

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1182]
Add Custom filters, which could be added via GUI (Database entry).

![capture](https://cloud.githubusercontent.com/assets/1961634/9682017/0430359a-5303-11e5-921f-471c17909103.PNG)

What do you think?

**Comment by fguillot** [comment]
+1

**Comment by mcfog** [comment]
+1

and custom filter might be  personal/public visible,  and project/global visible

**Comment by BlueTeck** [comment]
Should I send a PR or do you want to realise it?

**Comment by fguillot** [comment]
I'm busy to improve something else, if you want to send a PR, let me know how you want to implement that before to start coding it.

**Comment by BlueTeck** [comment]
new table:
| filter [key]                                      | project_id (key) | user_id (key) | is_shared | name          |
|---------------------------------------------------|------------------|---------------|-----------|---------------|
| category:"internal test" category:"business test" | 1                | 1             | 1         | all tests     |
| assignee:"admin" assignee:"user1"                 | 1                | 1             | 0         | frontend team |
|                                                   |                  |               |           |               |

filter = the filter
project_id = project_id
user_id = creator of the filter
is_shared = flag if the custom filter is only for the creator or for every member in that board
name = name of that filter

in the board it is displayed like the screenshot above, but there could be a save button behind the filter box, which opens a popup to save a new filter. And there should be a new page (under the actions dropdown) to maintain existing filters.

Did I missed something?

**Comment by fguillot** [comment]
@BlueTeck sounds good

**Comment by BlueTeck** [comment]
I will send the PR in a few hours

**Comment by anklaa** [comment]
It would be great to define personal/global custom filters for the global search.
If I want to get an overview for all project. 
![2016-08-11 10_12_53-dashboard for andre](https://cloud.githubusercontent.com/assets/20811086/17582506/60ceca08-5fac-11e6-999d-d2e62d84e44f.png)
