### ISSUE TITLE
LDAP AD authentication fails wrong username/password error

### ISSUE THREAD

**Issue by xtrails101** [fguillot/kanboard#1189]
Hi,
on ubuntu 14.04 LTS we are trying to configure authentication to our Windows Server 2012.
On the windows server we can see that user@domain.global is trying to authenticate but we get the error "wrong username or password.

The user "user@domain.global" that is allowed to read the LDAP tree is located in the standard CN Users. Here we have all the system users. The other (real) users, that should be authenticated through kanboard are in another CN, as you can see in the config file below.
We have used a different php script to try authenticating to the AD and that works, so username and credentials are OK.

Maybe we have an error in our config file or missing something else. Maybe it has to do with Windows Server 2012? Or that kanboard can actually not talk to WinServer 2012?

Thanks in advance for your support
Best regards Ralf

This is our config.php

// Enable LDAP authentication (false by default)
define('LDAP_AUTH', true);

// LDAP server hostname
define('LDAP_SERVER', '192.168.88.45');

// LDAP server port (389 by default)
define('LDAP_PORT', 389);

// By default, require certificate to be verified for ldaps:// style URL. Set to false to skip the verification.
define('LDAP_SSL_VERIFY', true);

// Enable LDAP START_TLS
define('LDAP_START_TLS', false);

// LDAP bind type: "anonymous", "user" (use the given user/password from the form) and "proxy" (a specific user to browse the LDAP directory)
define('LDAP_BIND_TYPE', 'user');

// LDAP username to connect with. null for anonymous bind (by default).
// Or for user bind type, you can use a pattern: %s@kanboard.local
define('LDAP_USERNAME', 'user@domain.global');

// LDAP password to connect with. null for anonymous bind (by default).
define('LDAP_PASSWORD', '1234999');

// LDAP account base, i.e. root of all user account
// Example: ou=People,dc=example,dc=com
define('LDAP_ACCOUNT_BASE', 'CN=LINK-Fertigungssteuerung,CN=Benutzer,CN=LINK-GmbH,DC=link,DC=global');

// LDAP query pattern to use when searching for a user account
// Example for ActiveDirectory: '(&(objectClass=user)(sAMAccountName=%s))'
// Example for OpenLDAP: 'uid=%s'
define('LDAP_USER_PATTERN', '(&(objectClass=user)(sAMAccountName=%s))');

// Name of an attribute of the user account object which should be used as the full name of the user.
define('LDAP_ACCOUNT_FULLNAME', 'displayname');

// Name of an attribute of the user account object which should be used as the email of the user.
define('LDAP_ACCOUNT_EMAIL', 'mail');

// Name of an attribute of the user account object which should be used as the id of the user.
// Example for ActiveDirectory: 'samaccountname'
// Example for OpenLDAP: 'uid'
define('LDAP_ACCOUNT_ID', 'samaccountname');

// By default Kanboard lowercase the ldap username to avoid duplicate users (the database is case sensitive)
// Set to true if you want to preserve the case
define('LDAP_USERNAME_CASE_SENSITIVE', false);

// Automatically create user account
define('LDAP_ACCOUNT_CREATION', true);

**Comment by jtourt** [comment]
Take a look here:
http://kanboard.net/documentation/ldap-authentication

There are 3 possible ways to browse the LDAP directory:
- Anonymous browsing
- Proxy user
- User credentials

You are mixing the settings for "Proxy user" and "User credentials".

Try changing LDAP_BIND_TYPE to "proxy".

**Comment by xtrails101** [comment]
Oh, yes, now I understand.
OK changed that and tried it again.
Unfortunately no luck :-(
Next week I will have a meeting with the admin of the windows machine, so I have access to the windows security protocol.
Thanks so far, I will update this with the result next week.

**Comment by xtrails101** [comment]
OK, we made it!
We use the user authentication and set the null in LDAP_PASSWORD in '...'. Without the '...' we get an error on the Windows Server because of wrong username and password.
Thanks for the tip and this great piece of software, so happy that it works now.
