### ISSUE TITLE
"Authentication failed" when trying to use API via curl

### ISSUE THREAD

**Issue by fbartels** [fguillot/kanboard#1210]
Hi, 

I've recently set up Kanboard 1.0.17 (and during my test also upgraded to 1.0.18) along with authentication based on OpenLDAP and storage in MySQL.

Today I wanted to toy around with the JSON Api and tried the example from the documentation, but I always get a json reply with "Authentication failed". I tried the same example (with an updated secrect) against demo.kanban.net and here it works. 

Interestingly I also enabled debug logging in config.php, but don't see any new lines in debug.log while executing the query.

Is there a chance that there is a general problem with the api, when using ldap auth? Is there anything else I can check or increase for further debugging?

**Comment by fguillot** [comment]
What kind of authentication did you use? user access or application access? can you give an example of the request your are doing?

**Comment by fbartels** [comment]
Hi, my first tries were with the user access, but then I went over to the jsonrpc user, since I had no luck with the user access.

I use the following command:
```
curl \
-u "jsonrpc:995cb74be2e56ba0782d5496e622bc308652e60d0e8f30c6a23e80277007" \
-d '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 1}' \
--insecure \
https://kanboard.myhost/jsonrpc.php
```
I just added the --insecure compared to the example on the wiki as I am using a self signed certificate. During my tests I even did a reset of the token (and then updated to token in the query). 

I uploaded my config.php to a Gist:
https://gist.github.com/fbartels/6584f52d32fc1980e7f8

**Comment by fbartels** [comment]
Hi,
since I updated to 1.0.22 yesterday I again wanted to give the api another try. But while I am successful in connecting to demo.kanboard.net I still am not able to connect to my system (same script just updated url and secret).

Anyone else having problems with the api and users in ldap? Is there anything I can do to help debug this?

**Comment by fguillot** [comment]
I just tried with Kanboard configured with LDAP and it's working for me. Both access method are working (user and administrative access).

What happen if you run the curl command in verbose mode and what happen in the debug log?

**Comment by fbartels** [comment]
Thanks for looking into this. Here is the requested output:

user access:
```
[2016-01-09 11:18:58] [info] User not found in LDAP server
[2016-01-09 11:18:58] [debug] SELECT * FROM `actions`
[2016-01-09 11:18:58] [debug] DURATION=7.5101852416992E-5
[2016-01-09 11:18:58] [debug] SELECT * FROM `action_has_params`
[2016-01-09 11:18:58] [debug] DURATION=4.7922134399414E-5
[2016-01-09 11:18:58] [debug] SELECT `value` FROM `settings`   WHERE `option` = ?    LIMIT 1
[2016-01-09 11:18:58] [debug] DURATION=7.2002410888672E-5
[2016-01-09 11:18:58] [debug] SELECT `value` FROM `settings`   WHERE `option` = ?    LIMIT 1
[2016-01-09 11:18:58] [debug] DURATION=5.8174133300781E-5
[2016-01-09 11:18:58] [debug] SELECT `value` FROM `settings`   WHERE `option` = ?    LIMIT 1
[2016-01-09 11:18:58] [debug] DURATION=8.392333984375E-5
[2016-01-09 11:18:58] [debug] SELECT 1 FROM `users`  WHERE `username` = ? AND `lock_expiration_date` != ? AND `lock_expiration_date` >= ?
[2016-01-09 11:18:58] [debug] DURATION=0.00018310546875
[2016-01-09 11:18:58] [debug] SELECT `id`, `password` FROM `users`   WHERE `username` = ? AND `disable_login_form` = ? AND `is_ldap_user` = ?    LIMIT 1
[2016-01-09 11:18:58] [debug] DURATION=4.6014785766602E-5
[2016-01-09 11:18:58] [debug] SQL_QUERIES=7
[2016-01-09 11:18:58] [debug] RENDERING=1452334738.7191
[2016-01-09 11:18:58] [debug] MEMORY=2.73M
[2016-01-09 11:18:58] [debug] URI=/jsonrpc.php
[2016-01-09 11:18:58] [debug] ###############################################
```

```
* Hostname was NOT found in DNS cache
*   Trying x.x.x.x...
* Connected to kanboard.xxx.xx (x.x.x.x) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
...
* 	 SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'x.x@x.x'
> POST /jsonrpc.php HTTP/1.1
> Authorization: Basic xxx
> User-Agent: curl/7.35.0
> Host: kanboard.xxx.xx
> Accept: */*
> Content-Type: application/json
> Content-Length: 60
> 
* upload completely sent off: 60 out of 60 bytes
< HTTP/1.1 401 Unauthorized
< Date: Sat, 09 Jan 2016 10:18:58 GMT
* Server Apache/2.2.16 (Debian) is not blacklisted
< Server: Apache/2.2.16 (Debian)
< X-Powered-By: PHP/5.3.3-7+squeeze28
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="JsonRPC"
< Transfer-Encoding: chunked
< Content-Type: application/json
< 
* Connection #0 to host kanboard.xxx.xx left intact
{"error": "Authentication failed"}
```

Admin access looks basically the same, even with the "User not found in LDAP server" in the debug.log.

Could this be related to the fact that I am using email addresses as login? or is "* Authentication problem. Ignoring this." this the issue?

**Comment by mhoennig** [comment]
Same problem here. Tried both user application access. As it's only a test site, it does not have a proper SSL certificate. Log looks basically the same as above.

**Comment by fbartels** [comment]
@mhoennig the proposed workaround in https://github.com/fguillot/kanboard/issues/1953#issuecomment-213753050 solves this issue.

**Comment by fguillot** [comment]
You should try this workaround if you use Apache+php-fpm: https://github.com/fguillot/kanboard/blob/master/doc/faq.markdown#authentication-failure-with-the-api-and-apache--php-fpm
