### ISSUE TITLE
[Feature Request] Auto-color tasks based on board column they are in

### ISSUE THREAD

**Issue by sonictk** [fguillot/kanboard#1211]
This would be a nice option to have for easily determining the state of tasks. For example, if I could have tasks in my Backlog coloured grey, tasks in the WIP column colored yellow, and tasks that were done coloured green, I feel like this would be a massive boost in productivity using Kanboard to easily identify "which tasks are in what state", rather than having to manually colour them; they would automatically color-code themselves when I drag-and-drop tasks between their states.

**Comment by TabDambrine** [comment]
Hi,

There is an automatic action "Assign a color when the task is moved to a specific column" you can set to your project to have this behaviour.

**Comment by sonictk** [comment]
Oh, nice! Is there a way I can automatically save out a project template with these automatic actions already setup so I don't have to keep re-defining them for each project?

**Comment by TabDambrine** [comment]
That's exactly how i work : I created a template project (private and inactive) that i can duplicate when i want to create a new project with the same settings, (categories, automatic actions, columns, and so forth.

**Comment by sonictk** [comment]
Nice! That works for me, eventually would be cool to integrate this sort of thing in the create new project UI i.e. "base off existing project" or something like that. :)
