### ISSUE TITLE
Mysql.php not processing correctly/completely

### ISSUE THREAD

**Issue by Corsair086** [fguillot/kanboard#1213]
Hi!

Downloaded and installed version 1.0.18 and configured it to use MySQL.  All required configurations stated at http://kanboard.net/documentation/mysql-configuration were completed.

At initial connection to Kanboard through the browser it added on 31 tables to the kanboard database before the webpage went idle and was blank (no errors, nothing).  Upon refresh of webpage errors were received similar to those provided by user c99ipnerd in issue #845.  

I followed the instructions provided by fguillot to modify the schema_version to skip the erroring functions in Mysql.php, but **I had to manually do this for nearly all functions version_1 through version_73** before Kanboard would finish the remaining steps before showing the login page.

Why so many duplicate failures within the code and partial completion of the Mysql build?  Is this a problem with Kanboard build logic or a problem with PHP/MySQL?

There were a small handful of functions in between 1 and 73 which still had to execute so that by the time it was done creating all tables (final count: 38) and updates had been made.  Very time consuming.

**Comment by fguillot** [comment]
My guess is the first time the process probably timed out and left the schema creation procedure in inconsistent state. It can happen on low cost and overloaded web hosting providers. Usually that take less than one second to create all tables.

Can you give more details about your environment? os/php/webhosting provider?

**Comment by Corsair086** [comment]
Sure!  The installation is on a virtual server created with VMWare with the following specifications:
* Intel Xeon E5-2670 @ 2.60 GHz
* 12.0 GB of RAM
* 64-bit OS, Windows Server 2008 R2 Standard
* 100 GB hard drive (pool size)
* IIS 7
--
* PHP Version 5.6.10 w/ required extensions per instructions.
* MySQL 5.6.26 

The same server is also server a few other hosted applications.

System is internally-hosted, in our rack, on the same LAN.  It is not on the Internet or served by a third-party provider.

Let me know if there's any other details I can provide you may be interested in!

**Comment by fguillot** [comment]
There is now an alternative method to initialize the database the first time for Mysql and Postgres. 

Instead of running all schema migrations one by one which can slow down the process, it's possible to import directly the final SQL schema.

The procedure is documented here: http://kanboard.net/documentation/mysql-configuration (Section importing SQL dump)

I think that will solve your issue.
