### ISSUE TITLE
vertical scrollbar per column

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#1214]
We've just updated to kanboard 1.0.18 and now we have vertical scrollbars per column if there are more tasks than the screen height. Is there any switch to get rid of these column scrollbars and just have a global scrollbar for the whole board like it used to be in earlier versions?

**Comment by Corsair086** [comment]
I tested this on the demo site, as my team just started with 1.0.18 has hasn't seen the prior versions.  I would agree with you about having an **option** to set the vertical scrollbar by column or by page, as there are use cases for both styles.

**Comment by lehrhardt** [comment]
Yeah, an option for this would be nice.

**Comment by DoumeDuSud** [comment]
:+1:

**Comment by RageAgainstTheVM** [comment]
Agreed.  This should be selectable similar to how horizontal scrolling can be disabled via enabling compact mode.

**Comment by fguillot** [comment]
This feature is available since a while now.
