### ISSUE TITLE
Combined task board

### ISSUE THREAD

**Issue by crsaracco** [fguillot/kanboard#1216]
As a single user of Kanboard without a team to collaborate with, I would like to have the following workflow:

 - Multiple projects, each with their own default color (see #1215)
 - A combined task board view, with all of the tasks from all of the projects shown on one page

This way I have the option of seeing only one project, or looking at all of the tasks as a whole that I have to work on.

**Comment by fguillot** [comment]
As I understand it, it's a duplicate of #426
