### ISSUE TITLE
due date

### ISSUE THREAD

**Issue by snekjar** [fguillot/kanboard#1228]
hi, 
i'm using kanboard in wampserver 2.5,
is this normal there is no way to plan a task after 23years? (we are in 2015, no way to put a
deadline after 2038...)
thx!
s
-------------------------------------------------------------------------------------------------------------
( ! ) Notice: A non well formed numeric value encountered in C:\wamp\www\app\Model\DateParser.php on line 216
Call Stack
#	Time	Memory	Function	Location
1	0.0000	251856	{main}( )	..\index.php:0
2	0.0170	2072504	Core\Router->dispatch( )	..\index.php:5
3	0.0170	2073040	Core\Router->load( )	..\Router.php:226
4	0.0240	2822608	Controller\Taskmodification->update( )	..\Router.php:254
5	0.0290	3146144	Controller\Taskmodification->edit( )	..\Taskmodification.php:165
6	0.0300	3155336	Model\DateParser->format( )	..\Taskmodification.php:114
7	0.0300	3155672	date ( )	..\DateParser.php:216
-------------------------------------------------------------------------------------------------------------

**Comment by TabDambrine** [comment]
Could it be related to the 2038 timestamp bug ?

**Comment by snekjar** [comment]
is this a kanboard issue or a wamp issue ? or something else ?

**Comment by TabDambrine** [comment]
it's an issue related to the unix timestamp it could be quite global you can have more info [on wikipedia](https://en.wikipedia.org/wiki/Year_2038_problem) 
I'm not sure it's the case here, that's why i'm just popping the idea.

On my setup (Windows, IIS) the limit date I can use is 01/01/2038 using the 2nd of january 2038 causes the same error you have.

**Comment by snekjar** [comment]
so i will plan my retirement for 2038 lol ! the last deadline ! after apocalyse, all in the desert with dogs and guns ! does fguillot know the pb? is will there be an update ?

**Comment by fguillot** [comment]
This issue come from the year 2038 timestamp bug: https://en.wikipedia.org/wiki/Year_2038_problem

- If you run php compiled in 32 bits that will fail, you must use the 64 bits version
- If you use Mysql or Postgres, I increased the size of the columns in the development branch so you can store 64bits timestamps (date > 2038)

With the last dev version, you can use Kanboard for another century :)

**Comment by snekjar** [comment]
hi,
i've changed the php version of wamp to a 64bit one, but the issue still exists...

**Comment by snekjar** [comment]
hi, i'm trying too with ovh, i have set-up htaccess for 5_4 php
always the same pb...maybe can you help me....
thx!
s
here the link
http://braoffice.com/kanboard/

**Comment by snekjar** [comment]
it's a test demo with admin/admin

**Comment by snekjar** [comment]
i'm creating log / pwd: test / test2038
keep in touch!
s

**Comment by snekjar** [comment]
hi, i have installed in wamp all these versions:
httpd-2.4.16-x64-vc11 (apache)
mysql-5.6.27-winx64
php-5.6.14-Win32-VC11-x64 (thread version)
and still the issue...
i'm so now trying to build my own server, no choice....
maybe a vps, i don't know, i'm a newbie in this field...

PS: what configuration do you have in demo.kanboard.net ?
thx
s

**Comment by snekjar** [comment]
ok, wampserver must have php7 so i must wait, i will see that on linux,
do you know some good practices ?

**Comment by snekjar** [comment]
ok...ubuntu install version is easier....thx! nice tool!
have fun developers!
s
