### ISSUE TITLE
Automatic action to set start date of a trask when moved to a column

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#1229]
We usually have a backlog column where tasks are parked with no start date. But when a task is moved to the right column, which can be Analyze, develop etc, then when the task work begins. At that stage, it would be handy to have start date automatically set. 

So, an event: when task moved to a column.
an action: set start date to current date.

**Comment by oliviermaridat** [comment]
This action is already available: "Update start date"

**Comment by mrozigor** [comment]
Event name = Move a task to another column
Action name = Automatically update the start date

**Comment by fguillot** [comment]
It's already there.
