### ISSUE TITLE
[API] getOverdueTasks + getProjectActivity for Users

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1232]
Hi @fguillot,

i'm currently changing from jsonrpc to user api (http://github.com/BlueTeck/kanboard_angular).

Could you please allow the two methods for the user API:

- getOverdueTasks 
- getProjectActivity

getOverdueTask also needs an update, at the moment it is for all projects, not only for the allowed ones.

What do you think, and should I send a PR or do you want to make this little change by your own?

thanks,
Timo

**Comment by BlueTeck** [comment]
getOverdueTask needs an update, at the moment it is for all projects, there should be a other method, getMyOverdueTasks for ths user.

Should I send a PR or do you want to make this little change by your own?

**Comment by fguillot** [comment]
If you have time send the PR, I will add the automated tests.

**Comment by BlueTeck** [comment]
- [x] new getMyOverdueTasks
- [x] new getOverdueTasksByProject
- [x] allow getProjectActivity for user
- [ ] docu

**Comment by BlueTeck** [comment]
Here it is: PR #1243

**Comment by BlueTeck** [comment]
merged
