### ISSUE TITLE
Error Creating Remote User

### ISSUE THREAD

**Issue by mangopudding** [fguillot/kanboard#1235]
Hi there.

When I try to create a remote user with just the user name - all I get is a blank screen after clicking Save button.

In reviewing the debug log, I'm seeing an error:

General error: 1366 Incorrect integer value: '' for column 'gitlab_id' at row 1

I do not have GitLab enabled - but if I put in a random number in the GitLab Id field when creating a remote user - it works.

**Comment by fguillot** [comment]
Are you using Mysql?

**Comment by mangopudding** [comment]
Yes. I am using MySQL

**Comment by fguillot** [comment]
It's now fixed in the development branch.

Thanks to report that.
