### ISSUE TITLE
 "Child"  tasks derived from  subtasks

### ISSUE THREAD

**Issue by marbico** [fguillot/kanboard#1236]
Hi, 
It would be nice to have an option to create   a "child"  task derived from  a subtask of the given "parent" task to simulate so called "task group".
Regards,
Marbi

**Comment by BlueTeck** [comment]
Something like #873 ? Or did you mean something else?

**Comment by marbico** [comment]
I think so.
Great.
When can we expect the implementation?
Best, Marbico

2015-09-16 11:35 GMT+02:00 Timo <notifications@github.com>:

> Something like #873 <https://github.com/fguillot/kanboard/issues/873> ?
> Or did you mean something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fguillot/kanboard/issues/1236#issuecomment-140686175>.
>



-- 

Marek Bisztyga

Marbico

E-mail: marbico.eu@gmail.com

www.goldenline.pl/marek-bisztyga2/

www.linkedin.com/pub/marek-bisztyga/30/513/97

Uwaga!

Treść i załączniki tej wiadomości przeznaczone są wyłącznie dla osoby lub
podmiotu, do którego jest zaadresowana i może zawierać treści poufne i/lub
chronione przed ujawnieniem.
Wgląd w treść wiadomości otrzymanej omyłkowo, dalsze jej przekazywanie,
rozpowszechnianie, innego rodzaju wykorzystanie, bądź podjęcie
jakichkolwiek działań w oparciu o zawarte w niej informacje przez osobę lub
podmiot nie będący adresatem, jest niedozwolone. Odbiorca korespondencji,
który otrzymał ją omyłkowo, proszony jest o zawiadomienie nadawcy i trwałe
usunięcie tego materiału z komputera. Dziękujemy.

Attention!
The information contained in this communication and its attachment(s) is
intended only for the person or entity to which it is addressed and may
contain information that is confidential and/or exempt from disclosure. Any
review, retransmission, dissemination, other use of, or taking of any
action in reliance upon this information by person or entity other than the
intended recipient is strictly prohibited. If you have received this
communication in error, please notify the sender and delete the
communication without retaining any copies.

**Comment by fguillot** [comment]
You can already link tasks together and use the relation "is a child of". Or if you would like to convert a subtask into task it's a duplicate of #873.
