### ISSUE TITLE
Hide column in board view

### ISSUE THREAD

**Issue by lowk3y** [fguillot/kanboard#1240]
.. another useful feature would be to be able to hide specific column in board view; for instance hiding "Backlog" column, so the team is not disturbed with tasks in backlog when viewing the board, and keeping focus on WIP columns :)

**Comment by BlueTeck** [comment]
That is already implemented. Try to click on the column name in board view.

**Comment by lowk3y** [comment]
Oh, stupid me! Haven't noticed .. sorry and thank you for clearing that out :)
