### ISSUE TITLE
kanboard can not be installed，Centos+Nginx+MySQL+PHP

### ISSUE THREAD

**Issue by PoNote** [fguillot/kanboard#1242]
Kanboard can not be installed
My Server: Centos+Nginx+MySQL+PHP

But I can install kanboard on my PC localhost: Windows7+Apache+MySQL+PHP

**Comment by fguillot** [comment]
How can I guess? do you have any error, what did you investigate to solve the problem? did you check the log files? are you sure that the problem come from Kanboard and not your environment? what is not working exactly?
