### ISSUE TITLE
Bug with subtask timer?

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#1245]
There may be a bug with the subtask's timer. With an "in progress" subtask (opened since 23h), when I try to finish it, after a very long time (and I may have an error 500 instead of the actual kanboard page), it indicates that I spent "103306.5h" on the task. Or something similar.

I am on "master" branch. I don't have time at the moment to perform more test, does anyone else has this issue?

**Comment by fguillot** [comment]
Did you check for php errors in log files (apache..) ?

**Comment by fguillot** [comment]
Fixed by the pull-request of @ukko
