### ISSUE TITLE
[CELEBRATION] KB starred 1000 times

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1250]
Yay...
![2015-09-20_21-17-52](https://cloud.githubusercontent.com/assets/10092252/9982444/47e82c16-5fdd-11e5-9cad-8ada73621efd.jpg)

**Comment by fguillot** [comment]
:)

**Comment by EpocDotFr** [comment]
ACHIEVEMENT GET!

You deserve it :) Everyobe deserve it!

**Comment by TabDambrine** [comment]
+1

**Comment by BlueTeck** [comment]
:+1:

**Comment by ashbike** [comment]
:+1:

**Comment by AlgyTaylor** [comment]
:+1:
