### ISSUE TITLE
problem to use native and local calendar

### ISSUE THREAD

**Issue by rainwolf60** [fguillot/kanboard#1251]
please help me that how can i use local calendar in kanboard.
because i saw fa.js that is the Farsi language calendar template in vendor folder but i dont know how to call in in kanboard application.

**Comment by fguillot** [comment]
1. Kanboard have to be translated in Farsi (https://github.com/fguillot/kanboard/blob/master/doc/translations.markdown)
2. Add the Javascript translation in the Makefile (https://github.com/fguillot/kanboard/blob/master/Makefile#L9)
3. Build the assets like described in the documentation: https://github.com/fguillot/kanboard/blob/master/doc/assets.markdown

**Comment by rainwolf60** [comment]
first of all thank you for your quick reply and Developing lovely, suitable and genius Kanboard.
unfortunately the answer was a little complicated for me to know how to do it myself.the first step was ok but 2 and 3 steps where confusing.I must say that i translated program user interface by adding Farsi Translation to kanboard befor and it was successfully done.now the user interface and menu is in Farsi Language.now my problem is only the kanboard`s calendar.i found a file named " fa.js "  in "  assets\js\vendor\lang "  location.when i opened it i saw that it is a Farsi Translated Theme for kanboards Calendar.now i have this "Fa.js" but i dont know how to replace "fa.js" with current calendar and by changing wich files manually i can call "fa.js" instead of current calendar.

**Comment by fguillot** [comment]
To translate the calendar, you just need to add "fa" in the list of files inside the Makefile and rebuild the assets.

If you have translated Kanboard in Farsi you can already send pull-request, I will modify the rest.
