### ISSUE TITLE
Normal project member can't see Gantt view

### ISSUE THREAD

**Issue by nodomain** [fguillot/kanboard#1252]
Sorry if I open this issue due to my own mistake but I am pretty sure that I configured everything fine. I am project admin and can switch to the gantt view - another user is no project admin and can't swith to the gantt view, there is no button for it.

Version 1.0.18

**Comment by fguillot** [comment]
Yes, it's the expected behaviour only project admins or project managers can see the Gantt chart.

**Comment by nodomain** [comment]
... and the project was set to "private" - so I could not set the member to manager. Now I figured it out. Perhaps an infobox or something similar in the GUI would support here.
17. Oktober 2015 03:46 Uhr, "Frédéric Guillot"  schrieb:
	Yes, it's the expected behaviour only project admins or project managers can see the Gantt chart.

**Comment by nodomain** [comment]
... and the project was set to "private" - so I could not set the member to manager. Now I figured it out. Perhaps an infobox or something similar in the GUI would support here.

**Comment by rseabra** [comment]
Why not allow project members to see the gantt charts? I can't fathom why and it would beneficial for members to be able to grasp the broader view of the project rather than the demeaning consignment to just their tasks.

**Comment by asmwarrior** [comment]
[Gant Chart only visible for Project Manager · Issue #1667 · kanboard/kanboard](https://github.com/kanboard/kanboard/issues/1667#issuecomment-296101144) this is the method to solve OP's issue.
