### ISSUE TITLE
Branch out sub-lists

### ISSUE THREAD

**Issue by AndyCoach** [fguillot/kanboard#1255]
Hello, can top level lists have sub-headings just like in kanbantool.com?
Thanks,
Andy

![image](https://cloud.githubusercontent.com/assets/13875336/10000733/9e1c4b04-6063-11e5-9990-77375b1272aa.png)

**Comment by BlueTeck** [comment]
Duplicate #530 and other

**Comment by fguillot** [comment]
Closing duplicate.
