### ISSUE TITLE
Fatal SQL Exception

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1257]
Heya,

I've got a bit of a bug report for ya ...

**System:**
Kanboard 1.0.18
Windows Server 2008 SP2
Apache 2.4
Postgres 9.4
PHP 5.4

I've added some 'is a milestone of' links to a task on Kanboard, and it's resulted in this error

    Fatal error:  Uncaught exception 'PicoDb\SQLException' with message 'SQL error' in E:\WebServer\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php:319

    Stack trace:
    #0 E:\WebServer\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php(276): PicoDb\Database-&gt;handleSqlError(Object(PDOException))
    #1 E:\WebServer\kanban\vendor\fguillot\picodb\lib\PicoDb\Table.php(274): PicoDb\Database-&gt;execute('SELECT (SELECT ...', Array)
    #2 E:\WebServer\kanban\app\Model\TaskFilter.php(668): PicoDb\Table-&gt;findAll()
    #3 E:\WebServer\kanban\app\Controller\Board.php(55): Model\TaskFilter-&gt;getBoard(53)
    #4 E:\WebServer\kanban\app\Core\Router.php(254): Controller\Board-&gt;show()
    #5 E:\WebServer\kanban\app\Core\Router.php(226): Core\Router-&gt;load('E:\\WebServer\\ka...', 'board', '\\Controller\\Boa...', 'show')
    #6 E:\WebServer\kanban\index.php(5): Core\Router-&gt;dispatch('/board/53', '')
    #7 {main}
    thrown in <b>E:\WebServer\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php</b> on line <b>319</b><br />

The relevant records in the 'tasks' database table are:

    752;"Talk to person1";"''";1442910288;"blue";53;233;2;1;TRUE;;0;1442962800;197;2;1442910662;"''";0;0;0;0;1442910319;0;0;0;0;0;;
    755;"Talk to person2";"''";1442910689;"blue";53;232;2;3;TRUE;;0;0;197;2;1442910689;"''";;0;0;0;1442910689;0;0;0;0;0;;
    756;"Talk to person3";"''";1442910701;"blue";53;232;2;4;TRUE;;0;0;197;2;1442910701;"''";;0;0;0;1442910701;0;0;0;0;0;;
    757;"Talk to person4";"''";1442910729;"blue";53;232;2;5;TRUE;;0;0;197;2;1442910729;"''";;0;0;0;1442910729;0;0;0;0;0;;
    754;"Talk to person5";"''";1442910678;"blue";53;232;2;2;TRUE;;0;0;197;2;1442910678;"''";;0;0;0;1442910678;0;0;0;0;0;;
    758;"Reduce to shortlist";"Reduced to a shortlist that can be presented to the Strategy Group";1442910771;"purple";53;232;2;6;TRUE;;0;0;187;2;1442910826;"''";;0;0;0;1442910771;0;0;0;0;0;;

... and in "task has links" ...

    87;9;758;752
    88;8;752;758
    89;9;758;754
    90;8;754;758
    91;9;758;755
    92;8;755;758
    94;8;756;758
    95;9;758;757
    96;8;757;758
    93;9;758;756

Let me know if there's any other information I can provide that might be handy!

**Comment by AlgyTaylor** [comment]
Removing those links from the task_has_links table seems to solve the problem, so presumably it's something to do with those ...

**Comment by fguillot** [comment]
This bug is now fixed in master, the fix is here: https://github.com/fguillot/kanboard/commit/370361330aeb37f02e87ab78ae38521da774c957#diff-64bf774cdba3c65fdd9d79ba19efe108R96

Other databases (Mysql and Sqlite) was ignoring silently this error.

Thanks to report that.
