### ISSUE TITLE
Avatar for users

### ISSUE THREAD

**Issue by biazouk** [fguillot/kanboard#126]
Profile picture or avatar for user.
Image on tasks rather than name, with name label when you hover over the image.

**Comment by nekohayo** [comment]
There is also the potential for this to create a more compact design, by replacing the full-length name labels in the board view by icons that contain either the (gr)avatar or, if no image is available, the first letter of the firstname with a unique color, like Google Documents does:

![foo](https://cloud.githubusercontent.com/assets/479401/8356875/df296be6-1b25-11e5-9785-fb3928f6812c.png)

This would make it future-proof for a case where a task can have multiple people assigned/co-assigned to it, as per issue #85. Of course, the image above is just an example of the "fake avatars with letters" concept, the layout of them is intended to be much more compact (in a line) on the board view, like Trello does:

![home-hero_es](https://cloud.githubusercontent.com/assets/479401/8356955/484a8d76-1b26-11e5-83e9-cd20071d5f37.png)

**Comment by NinjaPewPew** [comment]
I hope this will come true :+1:

**Comment by tk-wfischer** [comment]
I'd also love this feature :-)

**Comment by cmitasch** [comment]
:thumbsup:

**Comment by mcorteel** [comment]
Gravatar also provides Identicons like this:
![Identicon](http://www.gravatar.com/avatar/3b3be63a4c2aba9b013787725dfce802?d=identicon)
This would be really easy to implement and this way, each user would have a unique avatar when gravatar integration is active. We could then integrate more avatars. @fguillot  what do you think?

**Comment by nekohayo** [comment]
@mcorteel well, in terms of informativeness those gravatar identicons are useless compared to the letter-based ones; and, on a sidenote, I really cannot expect my users to _ever_ bother setting up a gravatar account (vs me uploading a profile picture for them in the kanboard admin interface), they have zero interest in technology.

That said, "gravatar for real avatars + fallback to letter-based identicons à la Google" would be a reasonable compromise.

**Comment by fguillot** [comment]
All right, I think it's time to have avatars in Kanboard.

For a first iteration, having the possibility to upload an image and fallback to a letter-based identicon would be a good start. Letter-based avatars are the default on Google and Apple products and I assume they are better UX designer than me :)

Now the big question is where to place the avatar on the card? the bottom left seems to be the more appropriate.

**Comment by mcorteel** [comment]
Something like that?
![spectacle qb6748](https://cloud.githubusercontent.com/assets/6164603/13872757/e0c9404a-ecec-11e5-949d-0e6391366398.png)

**Comment by TabDambrine** [comment]
:+1: 
What would be the rules to identify which avatars to display ?

Based on the assignee ? 
Based on the users who have commented the task ?

I like the idea of letter-based avatars, some of my users don't want a picture profile and it could be a good option in that case.

**Comment by Busfreak** [comment]
What about using Laravolt's package?
https://github.com/laravolt/avatar
"Display unique avatar for any user based on their name. Can be used as default avatar when user has not uploaded the avatar image itself."

**Comment by mcorteel** [comment]
I don't think this requires an external library. I implemented my mockup this morning using [this idea](http://stackoverflow.com/a/3724219) from stackoverflow. It just requires a small change in the function that displays the avatar.

**Comment by mcorteel** [comment]
I guess the rules could be as follows:
- Gravatar enabled:
  - User has an email address and a registered gravatar => show gravatar
  - User doesn't have an email address or no registered gravatar => show identicon
- Gravatar disabled:
  - Show the user's initial on a colored background

This could all be overruled if we included a profile picture setting in Kanboard. But the advantage of the aforementioned solution is that it doesn't require important code changes (well I already have a branch that does this and I can submit a PR).

**Comment by NinjaPewPew** [comment]
Glad this will happen. I like the @mcorteel's idea with the cards.

Just a little side note. I know Gravatar is quite popular in the private sector, but a lot of companies don't allow Employees to register there company email address at external web services. So I think a mechanic to upload images would be greatly appreciated by many (me included).

**Comment by nekohayo** [comment]
@mcorteel I still think the following hybrid approach would make more sense, if you folks don't want to implement a standalone "upload an avatar" local system:

* Gravatar enabled and user has an email address and a registered gravatar => show gravatar
* Gravatar disabled OR user doesn't have a gravatar associated with the email address => Show the user's initial on a colored background

In other words: no identicon, those are useless (they were meant as decorations for blog commenting systems where the username is shown alongside the icon; they are not replacements for the username).

**Comment by fguillot** [comment]
Avatars are now available in 1.0.27, you have the choice between:
- Letter based avatars (default)
- Gravatar
- Upload an image
- Google avatar if you have the plugin GoogleAuth

**Comment by nekohayo** [comment]
Hi @fguillot, finally got around to testing out 1.0.27 today, and it's _very_ cool! However, there is a small bug: "letter-based" avatars are only displayed where there is no email address associated with the user account at all; in the case where the account has an email address set in it but does not use gravatar, the gravatar logo/default-image gets displayed instead of the letter-based one. It would be best if we could detect that there is no "real" gravatar for a given email address and fallback to letter-based depictions in that case. Should I open a new issue for this...?

**Comment by nekohayo** [comment]
Alright, there are now issues #2185, #2184, #2183 and #2172 about the remaining bugs I could find.
