### ISSUE TITLE
keep translations.php during update

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1262]
I have to modify _(localize)_ some words in my use case. I do this in _translations.php_ is there a preferred way to make sure this file doesn't get overwritten during updates and that I'm not missing new strings.

Thanks

**Comment by BlueTeck** [comment]
You could try to use the new plugin system in the development version.

https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown#plugin-translations

**Comment by thob** [comment]
thanks but not with a little help as I'm just a _power user_ ;-)

**Comment by BlueTeck** [comment]
at the moment we have to wait for the next release anyway, until the new plugin methods are final

**Comment by BlueTeck** [comment]
Here is the needed plugin, which could be used in the next kanboard release:
https://github.com/BlueTeck/kanboard_plugin_overwrite_translation

**Comment by thob** [comment]
:+1:
