### ISSUE TITLE
How to add AD groups?

### ISSUE THREAD

**Issue by lowabr** [fguillot/kanboard#1265]
Hello,

I'd like to add specific Active Directory groups so that the users who belong to that group can only logon to the app.

How can I accomplish this?

Thanks,
Lowell

**Comment by fguillot** [comment]
There is an example here: https://github.com/fguillot/kanboard/blob/master/doc/ldap-group-sync.markdown#filter-kanboard-access-based-on-the-ldap-group

**Comment by lowabr** [comment]
That works! Thank you!
