### ISSUE TITLE
[Plugin][Idea] Overview

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1269]
Hi @fguillot 
an overview about the installed plugins in the admin settings would be nice. Something like this:

# Installed Plugins
| Pluginname         | Pluginauthor     | Pluginversion | Pluginhomepage                                 |
|--------------------|------------------|---------------|------------------------------------------------|
| Budget plugin      | Frederic Guillot | 1.0           | https://github.com/kanboard/plugin-budget      |
| Example CSS plugin | oliverh72        | 2.1           | https://github.com/kanboard/plugin-example-css |

The plugin.php could get a new method like getPluginInfo wich returns the needed information.

Regards,
Timo

**Comment by froschdesign** [comment]
My suggestion:

- set the link on the plugin name and remove the "Pluginhomepage" column
- add a column for the plugin description

**Comment by fguillot** [comment]
It's planned. And maybe later the possibility to upload plugins directly through the user interface.

**Comment by BlueTeck** [comment]
:+1: perfect

**Comment by fguillot** [comment]
It's now in master.
