### ISSUE TITLE
[Improvement] Make projects clickble from a task perspective.

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#1273]
Sup' guys o/

![kb](https://cloud.githubusercontent.com/assets/331134/10079228/3d1bb462-62bf-11e5-88c7-519ee0d831bd.png)

For example, KB > Sprint > bla bla bla
Make the **Sprint** clickble and remove the "Go back to board" link.
I think it's more intuitive.

What do you think?

**Comment by fguillot** [comment]
Not necessarily, you don't have to guess where the link on the project will redirect.
