### ISSUE TITLE
Collapse Column Headings into a Single Row

### ISSUE THREAD

**Issue by AndyCoach** [fguillot/kanboard#1278]
It appears column headings have to be the same across all swimlanes. If I collapse all of my swimlanes, I end up with several rows of the same column labels, seems like a waste of space. See image. 
![kanboard_headings](https://cloud.githubusercontent.com/assets/13875336/10115920/1beba39c-63e1-11e5-9a31-8ca05f4af0dd.PNG)

I wonder if the column headings could appear just once on the page.

**Comment by fguillot** [comment]
The swimlane layout have been changed in the development version, the column headers are not duplicated anymore.

**Comment by AndyCoach** [comment]
"changed in the development version, the column headers are not duplicated anymore." - is that version available for install?

**Comment by BlueTeck** [comment]
@AndyCoach To use the development You have to download this repository and run composer install afterwards. 

https://github.com/fguillot/kanboard/blob/master/doc/installation.markdown#from-the-repository-development-version

**Comment by AndyCoach** [comment]
Thank you BlueTeck, I will try that version.
