### ISSUE TITLE
Floating Horizontal Scroll Bar?

### ISSUE THREAD

**Issue by AndyCoach** [fguillot/kanboard#1279]
I am setting up Kanboard for use in project management. Swimlanes are project types; columns are key milestones in the project's life cycle. With large quantities of projects, the vertical height of the expanded Board grows and at quickly it becomes impossible to scroll to the right or left without first scrolling all the way to the bottom of the page, until the horizontal scroll bar appears. 

Can that scroll bar be fixed in location and always visible?

**Comment by sparkles645** [comment]
* If you click down the scroll-wheel on the mouse, you can scroll to the right / left - without having to go all the way to the bottom to locate the horizontal scroll bar.

**Comment by AndyCoach** [comment]
Thanks for the tip, it works well!
