### ISSUE TITLE
Must refresh page after each column change

### ISSUE THREAD

**Issue by AndyCoach** [fguillot/kanboard#1280]
After I drag a task to another column, I am unable to "grab" another task to move. I have to press F5, refresh the page, and only then I can drag another task box., Using Chrome. Is this a bug?

**Comment by BlueTeck** [comment]
Yes it is a bug, i've no problem with Chrome. which version are you using?

**Comment by AndyCoach** [comment]
I just updated Chrome to Version 45.0.2454.101 m and the problem has gone away.

**Comment by fguillot** [comment]
- Can you describe with more details how you installed Kanboard? (server, os, php version, database type, hosting provider)
- When you move a task somewhere else, did you see a loading icon in the bottom right?

**Comment by lucpavot** [comment]
Hi,

I got frequently this bug too:
http://g.recordit.co/cNhwWhqc9m.gif

It happens if we try to move a task before the end of the loader at the bottom right is done. And then it's stuck and you can't do anything except refreshing.

Tested in the demo version : http://demo.kanboard.net/board/2

**Comment by AndyCoach** [comment]
RE: "how you installed Kanboard? (server, os, php version, database type, hosting provider)"

PHP Version 5.4.24
MySQL Version 5.5.42-cll
Server Os: Linux etcvps88.arvixevps.com 2.6.18-308.20.1.el5 #1 SMP Tue Nov 13 10:15:12 EST 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AndyCoach** [comment]
If I wait until the loading icon in the lower right hand corner finishes spinning and disappears, then I can move another task. This would be OK, however, it takes quite a bit of time for for the icon to finish, so moving tasks in a staff meeting setting is simply too slow. Is this being considered for improvement? Otherwise this is a deal killer for me, unfortunately.

**Comment by BlueTeck** [comment]
You could enable debugging/logging in your config, to see why it is so slow.

**Comment by AndyCoach** [comment]
Thank you for the tip BlueTeck. 

By the way, does Kanboard run on Sqlite? If so, might it help if I moved it to MySQL?

**Comment by BlueTeck** [comment]
By default it runs on sqlite, but you could change to mysql/postgresql via config.
