### ISSUE TITLE
[IMP] Unfortunate consequences of implementing #1278 (current dev)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1285]
* Current dev version

* Implementation of not repeating columns headers - ref #1278  -  introduces an **unfortunate effect** on boards with many swimlanes.

*  The "waste of space"-claim/medicine - now has left us with a solution that involves a lot more work.
* Now not possible to use the "+" to create new task in the target location (have to create in in the default swimlane and move it)
* Also impossible to know which column you are moving the task to (unless you have a special memory in your brain), as column titles are not visible when scrolled down on the board. 

**Suggest re-considering this change and reverting to the way it was.** Less work creating new tasks and knowing where you are moving the task trumps space-waste or alternative with having to collapse/expand all swimlanes to see tasks down the board to keep track of your column headers

**Comment by thob** [comment]
I don't know how the new UI looks but from what you write I'd say a **+** should be there to allow contextual task creation

**Comment by BlueTeck** [comment]
@sparkles645 I agree with the missing headers on a large board. But if you create a new task, you could select the swimlane in the popover:

![image](https://cloud.githubusercontent.com/assets/1961634/10130727/18a71ae0-65cb-11e5-937f-b664ddc760f3.png)

**Comment by sparkles645** [comment]
@BlueTeck 
* Personally I could live with defining the swimlane along with the task, but I'm more concerned for our users that are used to / "trained" to the having the "+" button closeby when they are viewing a swimlane... I don't wish to create confusion and frustration by changing their workflow. I recognize that this one isn't a leap, but it is still a change in how it has been working up until now. I believe the majority use the "+" sign when creating new tasks, based on what I've observed.
* **Still an issue** with the column titles coming out of view when scrolling down. Floating column titles sound weird at first though - or is that just me(?)
**SIDE-NOTE**
* The potenial in a custom field / tag possibility - ref #262 , #646, #998  - would probably eradicate the need for so many swimlanes in some of our boards... (some boards have 30+ swimlanes, currently no way around that with our use case at the moment)

**Comment by thob** [comment]
Kanbanflow has it like so

![Kanbanflow](https://kanbanflow.com/img/premium-screenshots/Swimlanes.png)

**Comment by fguillot** [comment]
Effectively, after using using for a while it's not efficient. To create a task to another swimlane I have 2 more actions to do that I didn't need to do before. So I will change again the user interface, in master we have currently:

![swimlane-change](https://cloud.githubusercontent.com/assets/323546/10152921/6d5c4132-6625-11e5-874f-2b6567092a92.png)

So I will do another change later this week to repeat the column header below each swimlane name.

For reference the current layout look like that for the last stable version:

![swimlanes](https://cloud.githubusercontent.com/assets/323546/10152984/c66fc9a6-6625-11e5-9e80-db2f953af3a0.png)

My initial goal was to remove the space wasted on the left by the swimlane column name.

@sparkles645 What is your use case to have so many swimlanes and why tags may be a solution for that?

**Comment by sparkles645** [comment]
@fguillot 

**Description of use case:**

* Tasks on board organized by and possible to sorted **by the following dimensions**:

* User/assignee responsible - (a given duh!)

* Category - determines the type of / nature of the task - 

categories are typically across all "global" / interdepartmental boards - and I'm paraphrasing here to express their intention and avoid abbreviations: 

* administrative (blah blah blah, paperwork, managerial domain) 
* planned work/operations (things you are supposed to be doing/working on)
* interruption/failure (a.k.a. "Oh, Shit", mobilize and fix it - depending on how important it it) 
* MOM system (software, use what you've learned to prevent the same thing from happening again) 
* reported deviation/unwanted incident (computer says someone else say'd you have to fix this, HSE related)

* We use Complexity to describe the priority of the task. 
A "1" task is of highest priority, a "2" task is of lesser priority .... and so on for the (limited) range we use. Since complexity is viewed on the task, it is easy to get a feel for what's important and what can wait when seeing the front of the cards. If you see a "4", then you know it's not that in a hurry to get fixed, some "5"s probably fall into the "won't fix" territory.

* The swimlanes are currently being used to gather **all tasks that relate to a single objects or asset**. Example - **all tasks related to factory # 1 is** put in the swimlane "Factory # 1 - <facility name>" 

* When you need the overview of what to deal with next for that site/asset, you can just review the swimlane.

* **If tags were available**, one could for example easily filter out all open tasks of category "Oh shit" for "Factory #1".

* In this way, tags would allow us to keep both the type of task (category) and also the asset/object dimension in the filtering - and **we could remove many of the swimlanes** without mixing it all.

* Some of our users have complained that so many swimlanes make the board large and hard to manage. They'd rather have an (asset/object) "tag" dimension to work with. (we actually did a survey on it) But mixing all the tasks together - (between all the "factories") - would create utter chaos on the board, so we need to keep tasks relating to different objects/assets separated.

* Hope this describes the use case in sufficient degree to make it understandable.

* We are very grateful for the toggle - removing fixed height - ref #1159 - as people were about to be wearing out their scroll-wheels to move around. Now back in "compact" feel and only see what you've filtered out.

**Comment by jtourt** [comment]
@fguillot 

If the plan is to add another header to each swimlane, that change may add more wasted screen space to boards with many swimlanes than will be saved by removing the swimlane column on the left.

Each swimlane would contain a row with the swimlane name and below it a column header row?

![doubled-column-headers](https://cloud.githubusercontent.com/assets/14179005/10192891/9f0e21fe-674d-11e5-8912-9cc5d70c60b1.png)

**Comment by fguillot** [comment]
I changed again the layout, so now column headers are repeated for each swimlane.

However, I have to keep the column titles at the top for the first swimlane otherwise collapsing column doesn't work (css/html glitch)...

@jtourt that use a little more space vertically but horizontally you can have more columns.
