### ISSUE TITLE
App for Android (smartphone and tablet)

### ISSUE THREAD

**Issue by biazouk** [fguillot/kanboard#129]
:)
Synchronized with the server entered.

**Comment by levlaz** [comment]
Perhaps it would make sense not to create a separate app but instead have the webapp be more responsive on a mobile device. The benefit of this is that it will run on pretty much any device without the need for a separate app. 

This is especially nice for FirefoxOS, Android, Windows Phone and the upcoming Ubuntu phones since they all support HTML5 webapps pretty well. 

@fguillot Do you have any plans for a responsive mobile interface? If we were to create one would this be something that you would merge or would you prefer this to be a separate app all together?

**Comment by BlueTeck** [comment]
@levlaz what about notifications, share button from other apps? This is not possible in webapps, or am i wrong? In general i agree with your, webapp is the best, not my native android try.

**Comment by biazouk** [comment]
@levlaz, the idea is just like the @DoumeDuSud said: "to have access to information offline on his mobile, without being dependant of internet connexion."

Unfortunately I still do not develop for mobile devices. I hope to soon take a course.

**Comment by levlaz** [comment]
@biazouk @BlueTeck Yes, this is a very important feature. Luckily it is possible to store data locally in web apps on FirefoxOS, android and other platforms. There is no limitation using this approach. 

FWIF everything in firefoxOS (including the operating system is a web app). Depending on how it is built, packaged, and deployed will prov

**Comment by biazouk** [comment]
Truth @levlaz!!! Could be done that way then! ;)

**Comment by levlaz** [comment]
@biazouk I agree, it would be really nice because we could have one app that just works everywhere. :)

**Comment by biazouk** [comment]
Yeah @levlaz! Perfect, better than I imagined! ;)

**Comment by fguillot** [comment]
I agree with the responsive design on mobile device, actually it's not too bad on my smartphone in landscape mode.

My concern, is how to display the board in portrait?

For the offline mode, it's more tricky, you have to handle the fact the application is multi-users, so you need to have a "smart" synchronization system. Maybe the first and easy step is to have a read-only access when the device is offline.

**Comment by levlaz** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Frederic,

Thanks so much for taking the time to respond to this request!
Landscape mode works great for me currently and I was thinking of the
portrait mode as well. I think the best approach may be to split each
board on a project into an individual screen when in portrait mode and
allow the user to simply swipe or slide to the right or left to change
views to a different board.

As far as multiple users, this is an interesting issue. I agree that
getting data to sync offline first is a very reasonable approach.

Best,
Lev

On 01/12/2015 05:59 PM, Frédéric Guillot wrote:
> I agree with the responsive design on mobile device, actually it's
>  not too bad on my smartphone in landscape mode.
> 
> My concern, is how to display the board in portrait?
> 
> For the offline mode, it's more tricky, you have to handle the fact
> the application is multi-users, so you need to have a "smart" 
> synchronization system. Maybe the first and easy step is to have a
>  read-only access when the device is offline.
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/fguillot/kanboard/issues/129#issuecomment-69664089
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJUtdbaAAoJEGdDlSTynDmsU8EP/17ihTCDo9UNA1p3855E24YZ
gsvyyz0V4ly1CPQr4fxX4+2CnKTAh6dYN4vt9FkbpzXIP9u1dM9d/07FRjBrw03v
R+HxAF5Btva0Ey30iZ/KQxGqbBneGBc3k/paxK+rSmI/rtFf5g/FXaBSWzKjXnfj
Wa/oSbfIyz2dxJ+tsHoYZImTv+PjJ8QJpBWrgPspZmT5rLYyhTqCXtB+iL2JuUMd
24KMPECcsGICOiVvUS+w0BtwVb37d81V95klf6pEXY8Yw0l3SHb9xE5I2Pb+xhwz
VbH6OPKow71QSDf4MiIFc3uw7n+0Fqjtwyq0NKPNgBrPb86o07H5NM6iGpzroECd
YJUYUyU1f+ZQNZHY8SRpUpbNMDIciKUPEbzow+JB9sGf6fINpy9aYx5AA0A0NJ29
f46P7CTu1xfOn4Rlj9vNjUXbEiDQ6f97vkcUwBF4E+ytv8a+UKLJPq7oIktHGWbf
bpDa6yIDQpLEhXlmULLCv7a495xQy6PzjnlNSd1ZF0JIyTCqJwK3hs2lHvMgIUSb
7bLN4A0fMrvGpW8/JQd6UsQpNLPkkW0Y1ou4aqVqnthUwJrRWd15/yqp9jO5AKHo
YArpVImcOYYJQSu2GSIIAp21zvl/XcRSwLHW91/FL8PPEob9cUG0qMzZUQDi7Esn
LG92/JJMn4HD2Hc2f2QK
=5qth
-----END PGP SIGNATURE-----

**Comment by shimza** [comment]
What's wrong with the Trello method?

They put each column on a single portrait screen - you flick through them
like you would pictures, left to right.

While mobile, it's generally about ticking off tasks that have been
completed, not really about moving tasks between columns anyway.

Shimon

**Comment by levlaz** [comment]
There is nothing wrong with the trello method. That is exactly what I was suggesting.

**Comment by fguillot** [comment]
How do you slide or swap from one screen to another in javascript?

**Comment by shimza** [comment]
Swiping can be done in a few ways.... personally, I think the swipejs
method is quite clean.

http://hammerjs.github.io/recognizer-swipe/
http://stereobit.github.io/dragend/
http://blog.timothyandrew.net/blog/2013/04/05/using-swipe-dot-js-to-swipe-between-pages-of-a-web-app/
http://swipejs.com

plenty of ways to skin a fish.

**Comment by wiLLow86** [comment]
Hello, any news on here?

**Comment by BlueTeck** [comment]
I am currently playing around with with AngularJS and Kanboard, but at the moment it is just a ugly playground ;)

https://github.com/BlueTeck/kanboard_angular

**Comment by fguillot** [comment]
There is now a user api if someone want to create a mobile app. This api can be extended easily.

**Comment by swalladge** [comment]
Just discovered https://github.com/andresth/Kandroid that looks quite promising for those of you looking for an Android app.

**Comment by aljawaid** [comment]
@swalladge If only there was an apk file for that lol

**Comment by swalladge** [comment]
@aljawaid there are - check the [releases page](https://github.com/andresth/Kandroid/releases).
