### ISSUE TITLE
Copy Automatic actions from one project to another

### ISSUE THREAD

**Issue by CoyotteDundee** [fguillot/kanboard#1293]
Hello,

Playing for a few weeks now with KB and very pleased with it.
I especially like to possibility to assign colors to task categories using automatic actions.
Unfortunately, I haven't found a way to copy a set of actions to another project. Re-creating all actions for all project is a lot of work and a bit annoying... 
Maybe could other user find interesting to have, on the automatic action page, an option to copy actions from another project.

Best regards,

Michel

**Comment by sparkles645** [comment]
* You can duplicate the project where you've defined the actions that you want. (Settings --> Duplicate)

![2015-09-29_19-41-50](https://cloud.githubusercontent.com/assets/10092252/10172927/2704af0e-66e2-11e5-9a7c-bde7d71be883.jpg)

**Comment by fguillot** [comment]
With the last development branch, you can import automatic actions from another project.
