### ISSUE TITLE
Default filter empty

### ISSUE THREAD

**Issue by markfqs** [fguillot/kanboard#1295]
Hi

First, congratulations for the easy to use and deploy application-

I'm try to tune a bit the 'Reset filters' action unsuccessfully. and I ask for help or enhancement if you consider.

Basically I want that the 'default' filter (the filter used by default and set by the 'Reset filter' action), to be the empty filter (i.e. show all tasks either open or closed).

I can set the filter text box empty and I get the result I want, but the 'Reset filter' action sets it again to default 'status:open'.

I tried to modify app/Template/app/filter_helper.php, setting the 'data-filter' attribute to empty for 'Reset filter', but no success: it stills set it to 'status:open'.

I checked the expression <?= isset($reset) ? $reset : '' ?> is '$reset' any configurable item?

Thanks

**Comment by fguillot** [comment]
the `$reset` variable is defined here https://github.com/fguillot/kanboard/blob/master/app/Template/project/filters.php#L64, you can replace the value by the one you want and remove it completely...

But the pull-request about custom filters will be merged soon, so you will be able to add your own set of filters.

**Comment by markfqs** [comment]
Thanks for the quick response.

Although I can set my default filter I'm unable to set it to what I want: NO FILTER AT ALL.

If I set the filter to empty string '', I can't see the closed tasks:

<?= $this->render('app/filters_helper', array('reset' => '')) ?>

The only way it works is if manually delete the filter expression that appear on the filter text-box. Should I set it to something like NULL ?

My goal is to always see all the tasks, even the closed ones (so we know how much of the work is already done but still keep tracking of end-dates and time used)

Another part on which I'm trying to get this is on the DashBoard, which shows a summary of tasks on each column. This view also hides the closed tasks number. .  I suposse this needs to be modified on the app/Template/project/show.php file?

Thanks

**Comment by fguillot** [comment]
With the last master, if you define the value `status:all` for the `$reset` variable you will see all tasks (open and close) when you select the menu "reset filters".

**Comment by glennca** [comment]
if you grep, you shall find.
edit the following file:  app/Model/UserSession.php L135

Excellent initiative by fguillot to start this useful project... love it so far...

**Comment by michaelmcdonald** [comment]
This seems to have broken. Using `status:all` will now only display closed tasks and hide open.

**Comment by dbielz** [comment]
I also prefer to have an unfiltered view as default when changing projects and when clicking on 'Reset Filter'.
As for version 1.0.33 you need to modify three files to achieve that:

./app/Core/User/UserSession.php
L 168:
```
<         return ! empty($this->sessionStorage->filters[$project_id]) ? $this->sessionStorage->filters[$project_id] : 'status:open';
---
>         return ! empty($this->sessionStorage->filters[$project_id]) ? $this->sessionStorage->filters[$project_id] : '';
```
./app/Template/project_view/show.php
L 38:
```
<             <li><?= $this->url->link(t('%d tasks on the board', $stats['nb_active_tasks']), 'BoardViewController', 'show', array('project_id' => $project['id'], 'search' => 'status:open')) ?></li>
---
>             <li><?= $this->url->link(t('%d tasks on the board', $stats['nb_active_tasks']), 'BoardViewController', 'show', array('project_id' => $project['id'])) ?></li>
```
and
./app/Template/project_header/search.php
L 10:
```
<                 <?= $this->render('app/filters_helper', array('reset' => 'status:open', 'project' => $project)) ?>
---
>                 <?= $this->render('app/filters_helper', array('project' => $project)) ?>
```
To dev: wouldn't it be nicer to have this as default or at least to have some configurable default than to have forced everyone to only see active tasks?
