### ISSUE TITLE
White Screen "Error 500"

### ISSUE THREAD

**Issue by fvmuijen** [fguillot/kanboard#1296]
Yesterday 09-29-'15, I installed the latest Kanboard version on Ubuntu, 
but i get the white screen with "error 500" 

My Linux skils are not that good (anymore :) ) so detailed ideas/help are very welcome !

kind regards,
Frans

**Comment by BlueTeck** [comment]
Did you tried to enable debugging and check the logs?https://github.com/fguillot/kanboard/blob/master/doc/config.markdown#enabledisable-debug-mode

**Comment by fvmuijen** [comment]
just renaming the is the trick, including the "Debug ON" ?

**Comment by BlueTeck** [comment]
copy config.default.php to config.php and change define('DEBUG', false); to define('DEBUG', true);

**Comment by fvmuijen** [comment]
need to restart anything (restarted Apache already)?

**Comment by fvmuijen** [comment]
rebooted the server; no good
activated the debugging mode; where are the logfiles?

**Comment by fvmuijen** [comment]
![image](https://cloud.githubusercontent.com/assets/14887247/10165395/565ecbd6-66bf-11e5-9c0c-4dbf53609558.png)

**Comment by BlueTeck** [comment]
sqlite pdo driver is missing. try

sudo apt-get install php5-sqlite
sudo /etc/init.d/apache2 restart

**Comment by fvmuijen** [comment]
@BlueTeck: __Thanks for the help !  __

Kanboard is running now !  (..so i can make my teamleader happy now :8ball: !)
