### ISSUE TITLE
Incorrect Format for API Endpoint Link

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1301]
The API Endpoint link is missing path name and a forward slash.

Steps to reproduce:

1. From the main dashboard page click "Settings" in the bread crumb navigation.

2. In the left hand link list, click API

3. The API endpoint page shows a link in the format:

"mydomainname.comjsonrpc.php"

Expectation was that the correct format would be displayed, which in a default configuration is:

"mydomainname.com/kanboard/jsonrpc.php"

Kanboard Version: 1.0.18
Browser: Chrome Version 45.0.2454.101 m

**Comment by fguillot** [comment]
The url displayed will use the value entered in the field "application url" otherwise if empty that will guess the url from the information provided by the web server. So check the defined value for the application url.

**Comment by phillc73** [comment]
The Application URL field defaults to:

mydomainname.com

I've not entered anything in here that I recall, although I may have in my frenzy of setup activity.

I access the board at:

mydomainname.com/kanboard

This is why I found it strange that the API endpoint showed something different. Even if I was accessing the board directly at mydomainname.com, perhaps the API endpoint should still insert the relevant trailing slash, to create a valid URL.

**Comment by fguillot** [comment]
The trailing slash is now added automatically since a while.
