### ISSUE TITLE
Enhancement Request: Integration with Spark Messaging

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1302]
Spark is an open source cross platform messaging client:

http://www.igniterealtime.org/projects/spark/

This request is for the client to be integrated into Kanboard, in a similar manner to the current Jabber integration.

Ideally, users would be authenticated to Spark using either their username and password, or via LDAP if LDAP authentication is being used for Kanboard access.

Ideally messaging could be configured for "All Activity" or only "Activity for Assigned Tasks"

**Comment by fguillot** [comment]
Spark seems to be a XMPP client, there is already a plugin for Jabber?
