### ISSUE TITLE
Enhancement Request: Add List and Gantt View to Dashboard

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1305]
It would be useful to add linked icons for both the List and Gantt views from the main project Dashboard and My Projects pages.

Currently, there is only an icon for the Calendar view and clicking the text defaults to Board view.

The rationale behind this request is my attempt to migrate users to a single project management tool - Kanboard - from a diverse range of other tools including ToDoist (List view) and Microsoft Project (Gantt view). It would be useful to allow users who prefer these alternative task management approaches to be able to view their preference screens in a single click.

**EDIT:**

An acceptable, and maybe better, alternative to the above request would be to set a default view during new user creation, and obviously allow users to change this view from their profile page themselves. 

The default view would then load the associated page any time the project name is clicked - on the dashboard, in My Project, in My Tasks etc.

The set default drop down would then of course default to Board view.

**Comment by fguillot** [comment]
I just added direct links to the list and gantt chart in both pages. (only in master at the moment)
