### ISSUE TITLE
Long Task Titles Hidden by Scroll Bar in Gantt View

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1306]
Please see attached image.

There is a tiny up/down arrow on the right of the task title, but clicking "down" simply hides the text under the line above.

![longtitlesgantt](https://cloud.githubusercontent.com/assets/815126/10195606/bc242af4-678e-11e5-81f6-238bb78d6346.png)

**Comment by BlueTeck** [comment]
duplicate of #1163 #1177 #1153

**Comment by phillc73** [comment]
Sorry about that. Should have searched harder. I'll close this one.
