### ISSUE TITLE
Syslog issue

### ISSUE THREAD

**Issue by jackthesamourai** [fguillot/kanboard#1307]
Hi
This is FYI

In the file "\vendor\fguillot\simpleLogger\src\SimpleLogger\Syslog.php", line 24-25 there is a call to syslog and openlog. Those functions are deactivated on the version of PHP I use in my web provider (LWS), I was thrown a fatal error.

I have deactivated the following block and it works fine now: 
/*public function __construct($syslog_ident = 'PHP', $syslog_facility = LOG_USER)
    {
        if (! openlog($syslog_ident, LOG_ODELAY | LOG_PID, $syslog_facility)) {
            throw new RuntimeException('Unable to connect to syslog.');
        }
    }*/

**Comment by mrozigor** [comment]
Same in my provider.

**Comment by fguillot** [comment]
I added a new config parameter in the dev branch to disable syslog. Changing this settings to false should avoid any code change.

Doc Link: https://github.com/fguillot/kanboard/blob/master/doc/config.markdown#logging
