### ISSUE TITLE
stop timer is broken (subtasks)

### ISSUE THREAD

**Issue by bastiao** [fguillot/kanboard#1308]
when I click in stop a subtask it redirects to:
/kanboard/?controller=subtask&action=toggleStatus&task_id=534&subtask_id=129&redirect=task
but it is not found (from nginx)
after refresh, appears things like this: 13604.25h spent 1h estimated
any ideas why?

Happened in: master branch.

**Comment by TabDambrine** [comment]
Looks very similar to #1245.

**Comment by bastiao** [comment]
Probably. Any ideas what the commit that fixes the issue?

**Comment by BlueTeck** [comment]
I think this commit fixed it commit 930406bf70e42413a83114b9530b3f63ccf9419f

**Comment by bastiao** [comment]
yes, fixed
