### ISSUE TITLE
Cancel Closing a Task Link Does Not Respond

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1314]
Steps to re-produce:

1. View a specific Task summary page, this could be accessed by clicking on the Task name from the Board view.

2. Select Close this Task in the left navigation menu

3. On the resulting page, asking if you really want to close the Task, click Cancel.

4. No response.

Expected behaviour was the page would reload the Task Summary.

Kanboard Version: 1.0.18
Browser: Chromium Version 45.0.2454.101 Built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

**Comment by fguillot** [comment]
This issue has been fixed in the development branch.

Thanks.
