### ISSUE TITLE
Enhancement Request: Analyse Estimated Time vs Actual Time

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1317]
I'd like to know how good my Task time estimation is. For example, if the Task is estimated to take 4 hours, but is complete in 2.3, this is useful data for not only current resource planning, but also future task estimation.

A report in the Analytics section detailing Estimated Time vs Actual Time, on both Open Tasks (so work in progress) and also Closed Tasks (completed work) would be useful. The Open Task view would only show tasks where some actual time has been logged.

**Comment by antonioseric** [comment]
+1

**Comment by peripatetic-sojourner** [comment]
@antonioseric @phillc73 This was released as a report under 1.0.23. Could you take a look and let @fguillot know if he can close this issue?
