### ISSUE TITLE
Content Security Policy issue

### ISSUE THREAD

**Issue by unnikked** [fguillot/kanboard#1319]
I'm using Chrome 45.0.2454.101 on Ubuntu and I get those error messages in Chrome Dev Tools

```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256--o6dUkqHoadD_Wh8b-7IDgA_5zPbO_7bQ04JhJcxTDk='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

```
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-lsLpqtO2oyldxjRzHG9eRmiNMGfVWGy7G38B4WLyass='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```

The effect is that I'm unable for example to use drang & drop to move cards between columns.

I'm using the latest stable version `1.0.18`. Before to post I searched but I found only this issue #168

Sorry if I made a duplicate.

**Comment by fguillot** [comment]
I tested with Chrome Version 45.0.2454.101 (64-bit) and I didn't see any issue?

Kanboard doesn't use inline Javascript by the way.

**Comment by unnikked** [comment]
I've investigated further and I've found the "issue". Since I use Cloudflare to serve my personal instance, the service put some inline javascript into the page. 

I don't understand why the same problem do not occur on Android Chrome. 

I hope someone can help in this.

**Comment by unnikked** [comment]
I found the solution in case someone use also CloudFlare, I added a custom page rule on all the domain that serves the instance of Kanboard like the following

![schermata del 2015-10-04 11 03 28](https://cloud.githubusercontent.com/assets/2611548/10267128/a8221c18-6a87-11e5-8327-84ffcbc56e5d.png)

`App` and `Performance` **must be** on `off`.
