### ISSUE TITLE
Announce of Framaboard (Kanboard-inside)

### ISSUE THREAD

**Issue by marienfressinaud** [fguillot/kanboard#1324]
Hello everybody,

first of all, thank you all for your work on Kanboard, it is a great tool :).

I'm not sure I should open a ticket for that but since I can't find any mailing-list, I do that here.

Just to let you know that Framasoft (a French association, well-known for its "de-google-ify Internet" campaign http://degooglisons-internet.org/) is about to release a service based on Kanboard, known by the name of Framaboard (https://framaboard.org/).

We are still working on it before the official release on Wednesday but I think its better to ping you first (Frédéric was already aware about Framaboard, thank you again for your reactivity!).

The official repository (README is in French) is on our Gitlab: https://git.framasoft.org/marien.fressinaud/Framaboard

So what's next? Well, we have already some feedback thanks to our "Colibris" (i.e. Framasoft community) and I will probably open some tickets in the next few days. Note that the biggest complaint is about UX (User eXperience) and we, at Framasoft, would really appreciate to help you to improve that.

Best,
Marien

**Comment by fguillot** [comment]
cool :) I will post a news on the website

**Comment by TabDambrine** [comment]
:+1:

**Comment by phillc73** [comment]
Good luck! 

Which aspects of the user experience is your community unhappy with?

**Comment by pyg77** [comment]
@phillc73 
We're unhappy with nothing in kanboard, but we wanted to provide easy "register your own kanboard" easyly.
E.g: by registering (totally free and with strong ethical charter) on framaboard, you can access to phillc73.framaboard.org (a standard kanboard installation) in seconds. No server or skills needed.
The development of this functionnality is of course libre software and developped by @marienfressinaud : https://git.framasoft.org/marien.fressinaud/Framaboard/

@fguillot : please note that Framaboard is out! http://framablog.org/2015/10/07/framaboard-les-libristes-ont-reinvente-le-tableau-blanc-mais-en-mieux/ :)

**Comment by phillc73** [comment]
@pyg77 That's a great idea! Especially for those without the technical skills to host their own Kanboard.

**Comment by fguillot** [comment]
Just posted a news: http://kanboard.net/news/framaboard

**Comment by marienfressinaud** [comment]
Thanks! :)
