### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by danielraknes** [fguillot/kanboard#1326]
Just testing v1.0.18. I think the norwegian translation file needs adjustment cause the letters æ, ø and å makes the whole word disapear. For example "swimlanes" means "svømmebaner" in norwegian and if you set norwegian language, you can not modify swimlanes (or see the word swimlanes in settings). Is the anything I can do? Replace æ by &aelig;, ø by &oslash; and å by &aring; if that helps?  

Sincerely,
Danny

**Comment by BlueTeck** [comment]
You could try to experiment with the translation and replace characters /app/Locale/nb_NO/translations.php

**Comment by danielraknes** [comment]
Hi!

I have replaced:

æ with “&aering;”
ø with “&oslash;”
å with “&aring;”
and Å with “&Aring;”

Now it works on my installation.

New version of the file is attached.

Mvh
Daniel<http://mittomrade/Person.aspx?accountname=common%5CRADA>

Fra: Timo [mailto:notifications@github.com]
Sendt: 6. oktober 2015 11:39
Til: fguillot/kanboard
Kopi: Raknes Daniel Wik
Emne: Re: [kanboard] Norwegian translation (#1326)


You could try to experiment with the translation and replace characters /app/Locale/nb_NO/translations.php

**Comment by fguillot** [comment]
The translation file is badly encoded, it need to be converted in utf-8 to see special characters like ø correctly without to have to use html entities.

**Comment by danielraknes** [comment]
Hi!

Now i have converted the file from ISO-8859-15 to UTF-8, and it works fine on my localhost.

Converted version with special characters attached.

Mvh
Daniel<http://mittomrade/Person.aspx?accountname=common%5CRADA>

Fra: Frédéric Guillot [mailto:notifications@github.com]
Sendt: 7. oktober 2015 04:39
Til: fguillot/kanboard
Kopi: Raknes Daniel Wik
Emne: Re: [kanboard] Norwegian translation (#1326)


The translation file is badly encoded, it need to be converted in utf-8 to see special characters like ø correctly without to have to use html entities.

**Comment by fguillot** [comment]
I converted the file master and now it works.

Thanks to report this issue.
