### ISSUE TITLE
[FR] - visual report with background image (jpg, png) and editor to place data parameters

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1333]
* First off, I apologize for the volume of text in this FR.  
 - I'll try keeping it as short and sweet as possible.

* The following is a description and illustration of a few different use cases for the suggested feature - in hope that others / @fguillot  **see the potensial applications for this in their own use of KB** - and hence **will support/contribute with ideas in refining it and perhaps getting it implemented**. 

* IMHO I believe that implementing this FR **would give KB an edge that others do not offer** (at least, I haven't seen it anywhere else in such an intuitive software as KB) 

**Why this feature(?):**
* I come from an engineering approach to KB use. 
 - I'm not unfamiliar with the SW / developer world (I'm a poor/terrible coder, small scripting at best), but my main background is from physical engineering - as in things you can touch with your hand and kick when they don't work.
 - Main use of Kanboard is to keep the overview of things that need to get done (in a team setting) and a tool to help getting them done/keeping track of where you (or others) are with the task. 
 - In the practical engineering world (bringing it from paper/plans to real life) - with larger (and sometimes also with smaller) projects - there are a few obvious enemies on the road to successful completion of your work. Some of the worst, in my experience are **complexity, people and meetings**.
 - What I love about KB, is that once you've figured out what needs to be done (read as: meetings), you can **very simply** create that task and assign someone (read as: people) to it. And further, it then doesn't go away by itself, someone (read as: people) actually has to follow up on it to get it off the board. <3 (Sure, the assignee can cheat and remove it, but the point is - the road between "hey, this need to be done" to "you have the ball" has become very short and efficient )

* So far, so well. 
 - KB works very well for distributing work and keeping track of work. 
 - It supports the user/assignee, **but does it also support the manager/head of the team?** 
 - Yes it does. 
 - There's analytics, and in current master there is a 'web reports' initiative going on. 
 - However, in certain settings - the manager's or team leader's role is to oversee the progress, helicopter view. When assignees are overloaded with work OR progress / focus on certain parts of the project are falling behind - it is a managerial responsibility to address the situation - either by prioritizing (or by taking names and kicking ass!) - depending on the situation.
* This is where the known enemy **complexity** sometimes succeeds in clouding the scene, because difficulty in communication / scope of the work makes it hard to navigate in the situation. Complexity then contributes to loss of clear and efficient prioritizing.

* The **goal of this suggested feature** is to allow keeping a **simple model for communicating the work scope** - even if the reality of the project (when you drill down) is far more complex. 

**SUMMARY - core of the IDEA/FR - allow creating custom graphical report views - with a background image (.jpg, .png, created by the user) - and overlay boxes (from KB) that can drag-dropped to a specific part on background image.**

(so, what the heck does - that mean???)

* I'll try to show you, to make it clear. 

**How would it look in Kanboard (described by a non-coder)**

![steps](https://cloud.githubusercontent.com/assets/10092252/10318465/e93a4bce-6c69-11e5-8a75-142c6698128d.png)

**PRESENTED USE CASES:**

1. Building a bridge
2. Running a barn/farmhouse (for other people's horses)
3. Planning a political campaign tour

**USE CASE - 1. Building a bridge**
* Who am I: 
 - Hired as project manager in a project where a bridge is to be built. 
 - Don't know much about bridges, but pretty decent at project management.
 - The people working in the project team are highly skilled engineers/specialists, but they have a tendency to throw around fancy bridge jargon and words that only they understand and think that they are very important.
 - Getting everyone involved in the project to communicate on the same level / stay on point - is difficult in meetings
 - As project manager - introduce Kanboard and enforce use of it in the project 
 - Main goal is to achieve levelled communication when discussing progress of the project when team is gathered in meetings.
 - Kanboard is used to delegate work to and within the different teams working on the project.
 - A board is established with the following Swimlanes (based on project managers lack of insight into how bridge building works)
** Swimlanes in Project "We build a bridge!"**
 - Left side (of the bridge)
 - Tower 1
 - Part in the middle (of the bridge)
 - Tower 2
 - Right side (of the bridge)
 
 **On the visual report, the blue numbers now show the open tasks in those swimlanes**

![20151006_bridge_basic](https://cloud.githubusercontent.com/assets/10092252/10318155/6c0e899a-6c68-11e5-8b01-57e2f4e33eaf.png)

**THE PROJECT TEAM COMPLAINS PROFUSELY ABOUT THE VISUAL MODEL, SAYING THAT IT DOESN'T DESCRIBE THE COMPLEXITY OF BRIDGE-BUILDING AT ALL**
Thus, we change / alter the model (background image) to better support the project scope and parts of the bridge that needs to be worked on in terms of planning and engineering.

End up with the following swimlanes and the following visual report:
** Swimlanes in Project "We build a bridge!"**
 - Left side (of the bridge)
 - Tower 1
 - Blinking thingy(s) on top
 - Cables
 - Part in the middle (of the bridge)
 - Tower 2
 - Right side (of the bridge)

![20151006_bridge_adv](https://cloud.githubusercontent.com/assets/10092252/10318172/8579b9c2-6c68-11e5-8d4c-330fbcb57186.png)

* **NOW - in meetings and in the everyday life of the project, it is easy to see number of tasks active on the different parts of the bridge.
The report makes it clear to everyone involved that right side of the bridge requires more resources and attention, due to many tasks.** 
* As the project keeps progressing, the model (background image) and the reporting parameters are adapted.
 - Everyone communicates - based on the visual model - when in team meetings and do drill downs on the tasks relating to the different parts of the bridge in each meeting to see what's most important and what's next.
 - A simple MSPaint sketch and data reported directly from Kanboard now has established a joint communication model for the project that everyone can see and relate to - details are kept on the board and on the tasks, but the model provides the overview and grounds for prioritizing and discussing.

USE CASE - 2. Running a barn/farmhouse (for other people's horses)

* **Who am I**: 
 - I run a barn where other peoples horse's are kept (just to be clear - this is fictional - in real life I do not run a farm and I don't know jack shit about horses)
 - There are employees at the barn (stable, janitorial, maintenance)
 - Kanboard is used to administrate tasks
 - The visualreport shows everyone on a big-screen TV - with the BLUE NUMBERS - how many tasks are open on the different parts of the farm
 - As the manager / barn owner, a quick look at the visualreport reveals that **Stall B needs attention, there is alot of barn maintenance piling up and Horse C should be priority**

The board consists either of Swimlanes or has Categories "Horsefood", "Field and fence maintenance", "Horse trailer maintenance", "Barn maintenance", "Horse A", "Horse B", "Horse C", "Horse D", "Stall A", "Stall B", "Stall C", "Stall D"

* When horse B (named "Dr. Pepper") dies in a fire-tornado (probably too detailed for a feature request description, I know) - all I have to do is **change the background image** when a new horse arrives to live in the barn. 
* The report still works as before, just with a new horse face on it. 

![horsie](https://cloud.githubusercontent.com/assets/10092252/10318306/1687794a-6c69-11e5-8aa7-9a5202581a2f.png)

USE CASE - 3. Planning a political campaign tour

* A team is planning a campaign tour
* The tour is to have 4 stops along the way
* The visualreport created shows at a quick glance the number of tasks in the column "Committed" in the project "Planning campaign tour"
* The goal is to have 10 committed plans for each stop along the way. While the team is working on detailing new ones, a quick look at the visual report shows how far along they are.
* For the manager of the team, a quick glance on the visual report shows that, Stop # 3 need more attention 

![political_campaign](https://cloud.githubusercontent.com/assets/10092252/10318318/21a9c0da-6c69-11e5-9614-abce382e60ea.png)

**Comment by fguillot** [comment]
Sorry, I'm closing this issue, seems too complex and no body up-vote.

**Comment by sparkles645** [comment]
Yeah, didn't catch. :)
