### ISSUE TITLE
Duplicating project not working properly

### ISSUE THREAD

**Issue by raidlman** [fguillot/kanboard#1335]
When duplicating a project with all parts of the project, all tasks from the original project end up in the first column/backlog and not in the same column as in the original project.

Version: 1.0.18.

**Comment by raidlman** [comment]
There seem to be an issue with the swimlanes as well. All tasks are duplicated into one swimlane.

**Comment by fguillot** [comment]
I just changed that in the development branch. Now, duplicated tasks will be copied in the same column.

Thanks.
