### ISSUE TITLE
Kanboard behind the proxy

### ISSUE THREAD

**Issue by semka** [fguillot/kanboard#1338]
Guys from our IT department are a bit paranoid, so Kanboard is deployed to the server behind proxy.
Everything works fine except integrations which rely on webhooks, for example Slack integration.

I didn't find any configuration options or even code related to configuring proxy server for outgoing webhooks. 

Is this possible, to use integrations while server is behind proxy?

**Comment by fguillot** [comment]
I just added this feature in the dev version: https://github.com/fguillot/kanboard/blob/master/doc/config.markdown#http-client-proxy

The next stable release will include that.

**Comment by semka** [comment]
Thanks, Frederic! I will test this code tonight.

**Comment by semka** [comment]
Work like a charm :)
