### ISSUE TITLE
[Imp] Custom Filter option to select append/new filter

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1340]
Idea to improve my custom filter function:

Add an option if a custom filter should reset the current filter, or if it appends the custom filter.

Reference: https://github.com/fguillot/kanboard/issues/1181

If I have some time, I will add this feature, maybe on the weekend. or someone else is faster ;)

**Comment by lehrhardt** [comment]
that would be awesome...

**Comment by thob** [comment]
:+1:
