### ISSUE TITLE
support for `@user` and `#label` use when creating new cards. 

### ISSUE THREAD

**Issue by letsgo008** [fguillot/kanboard#1342]
When creating a new [mini]card, typing @ or # brings up an auto-complete box for board members

The textual tags are removed from the card title before saving to maintain sanity. If a label doesn't have a name, the name of its colour is used (i.e. red, purple, etc).

**Comment by oxydron** [comment]
:+1:

**Comment by BenWShade** [comment]
Yes (related), can we have a tags field as well?

**Comment by oxydron** [comment]
@fguillot Sorry for the last duplicate issues. I'll search first before post my requests.

Great job!
