### ISSUE TITLE
User import from csv file ?

### ISSUE THREAD

**Issue by SebCanet** [fguillot/kanboard#1343]
Hello,
thanks a lot for this project, it works fine ! And it's really easy to understand to kids.
But as my students are quite 140...I cannot create each account...can it possible to feature a way to import user ? with password ?
Or can I add this user information in a specific file ???

Thanks a lot.

**Comment by BlueTeck** [comment]
By default this is not possible.

You could code something like this: https://github.com/ashbike/csv2kanboard

Or in some database tools you could import/export data, so you could modify your user table.

**Comment by SebCanet** [comment]
Yes, but what I ask is a new function for Kanboard :-D

**Comment by fguillot** [comment]
I added this feature in the development branch. The same thing will be added to import tasks.

At the moment, it works but it's not yet tested with all major spreadsheet software (Excel, LibreOffice, Numbers, Google Docs...). That will be the case when the tasks import will be implemented.

**Comment by froschdesign** [comment]
@fguillot 
Why is this a core feature?! This should be implemented as a plugin. (imo)

**Comment by fguillot** [comment]
@froschdesign It's just a basic CSV import, if people need something more complex like importing a Excel spreadsheet (*.xlsx) that should be a plugin or a separate script.

**Comment by froschdesign** [comment]
> It's just a basic CSV import

I saw that. But why is this "basic CSV import" not a plugin? CSV import is not a (main) task for a kanban board.

- All (main) tasks for kanban board should be in the core.
- All helper functions, external services and all other extensions should be outsourced as plugins.

Github, Mailgun, Jabber and Co. are perfect candidates for plugins!

(imo)

**Comment by fguillot** [comment]
@froschdesign Why CSV import is part of the core? because several people are switching from one software to another one (KB) and providing an easy way to import existing tasks or users allow them to trying out the software quickly without having to search for external plugins. And it's not really a big deal for the CSV import at the moment, I can move that to a plugin very easily later if I change my mind.

I already planned to move all existing integrations to plugins but before doing that I want to provide a better plugin API for the authentication, notifications, etc. Iterations after iterations the core becomes better.

**Comment by SebCanet** [comment]
Merci mille fois ! Exactement ce qu'il me fallait ! Je vais pouvoir commencer avec mes classes rapidement, surtout que Kanboard est ce que je cherchais : un mélange entre le Gantt et les taches.

Je ferai des publications académiques là-dessus et j'en parlerai en formation.

Désolé d'avoir suscité autant de discussions...

**Comment by froschdesign** [comment]
@fguillot 
> because several people are switching from one software to another one (KB) and providing an easy way to import existing tasks

Right, but this is not the question. 

> users allow them to trying out the software quickly without having to search for external plugins

You can ship / bundle Kanboard with (preinstalled) plugins.

> I already planned to move all existing integrations to plugins

Great. Now we are on the right track. :wink: 

> but before doing that I want to provide a better plugin API

I'm on your side. :+1: 

@SebCanet 
> Désolé d'avoir suscité autant de discussions...

At this point, discussions are good. No problem!
