### ISSUE TITLE
Equation support

### ISSUE THREAD

**Issue by bachmeil** [fguillot/kanboard#1348]
I really like the fact that Kanboard uses Markdown. However, I'm limited by the lack of equation support. Is there a way I can add the MathJax CDN? I can customize the CSS by going to Settings > Application settings but I'm not seeing an option that would allow me to add a link to a CDN.

**Comment by BlueTeck** [comment]
In the next release you could do it with the new plugin system: https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown

**Comment by bachmeil** [comment]
Looks great! I'll have to give it a try.

**Comment by bachmeil** [comment]
I'm reopening because I figured out how to do it with the current release. Looking at the plugin system, I'm not seeing how it will change what needs to be done.

I went into app/Template/layout.php and added

```
<script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
```

before `</head>`. I had to change the security settings to allow this script in app/Core/Response.php. Inside `public function csp` I changed

```
        $policies['default-src'] = "'self'";
        $values = '';
```

to 

```
        $policies['default-src'] = "'self'";
        $policies['script-src'] = "localhost:8001/ https://cdn.mathjax.org/";
        $values = '';
```

AFAICT, it will still be necessary to change the security settings in Response.php even with the new plugin system.

**Comment by fguillot** [comment]
I added a new method to override the default CSP rules: https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown#override-http-content-security-policy

Note: the plugin api is not complete, it's the first draft, if something is missing it can easily added.
