### ISSUE TITLE
[Workflow Question] Is there a way to add subprojects to projects

### ISSUE THREAD

**Issue by dennschu** [fguillot/kanboard#1349]
### Our scenario: 

As web development agency we build and extend cms with a set of packages with their own/independent development cycle. Further development of a package gets triggered through requirements for the base project (cms development).

### How we use Kanboard for such a scenario:

We create one board for every new cms project and every package has also its own board (we have *global* list of package boards that are used for all cms projects). When there is a requirement of a customer for which we build a cms that requires to extend a package then we list the task of package extension at the cms board and track the afford there.

### Problems that result from this workflow:

- the documentation of package extension tasks through their board has gaps in the case where extensions took place in cms projects
- we could not resolve the value of a package based on spent hours because the task was tracked on a cms project
- we could not resolve (from the scope of a package board) where the actual extension took place (in what cms project)

### How we tried to solve that issue with a manual workaround:

- after an extension task was finished (task moved to done column at the cms board) we manually duplicate this task to the package board

### Issues/pain points with our workaround:

- during a development cycle we dont see what package extensions took place from the board scope of a particular package
- the manual process of duplicating tasks is error prone so that a developer: (a) forget to duplicate the task (b) duplicates the task to the wrong package board
- correct/realistic analytics/value of a package can only be resolved when all package extension tasks pn cms boards where finished and were duplicated to package board

## Questions:

1. Is there a way to resolve our pain points with features of version 1.0.18 of kanboard that we have overlooked?
2. Is it a feature request?

**Comment by dennschu** [comment]
@fguillot Do you have any suggestions?

**Comment by fguillot** [comment]
If I understand correctly, you have by example these boards:

- CMS for customer X
- CMS for customer Z
- Package A
- Package B

The customer X want a new feature but that involve a development in the package B, you would like to have one task in the board for the customer and the same task in the board of the package like that:

- CMS for customer X
  - Task 1: New feature Y
- Package B
  - Task 2: New feature Y

The task properties will be the same between the 2 tasks board (time tracking and position). Basically, it's like "synchronizing" the 2 tasks properties or having a single task attached to multiple projects.

Is my understanding correct? If yes, this feature doesn't exists.

- You can still use task links to keep track of the request: "Task 2 on the board Package B is related to the task 1 on the board CMS for customer X".
- For the rest, I don't have a better idea at the moment, maybe developing a custom automatic action can do the job of synching the 2 tasks.
