### ISSUE TITLE
issue with htaccess in v1019

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1351]
Just uploaded a vanilla 1.0.19 to my server **(1.0.18 is working fine there)** and got this

`[Sun Oct 11 12:35:03 2015] /.htaccess: Invalid command '[IfVersion', perhaps misspelled or defined by a module not included in the server configuration`

if I rename the .htaccess to _.htaccess_old_ I just get a blank page the error log returns `PHP Fatal error:  require(): Failed opening required '…board/vendor/autoload.php' (include_path='.:/usr/share/php5.5') in /…board/app/common.php on line 3`

Any idea?

**Comment by alirz23** [comment]
looks like the mod_version is not included in apache confg, do you have the apache version module loaded? if not you can enable it by running `a2enmod version`

**Comment by fguillot** [comment]
I just updated the .htaccess recently with a check on mod_version, seems to work with the default configuration of Debian 6/7/8, Ubuntu 14.04 and Centos 6/7.

**Comment by fguillot** [comment]
By the way, I released 1.0.19 after you created your message (10 minutes ago).

**Comment by thob** [comment]
I'm on a managed VPS on Debian Squeeze. Don't know what Apache v is running

**Comment by thob** [comment]
looking good now, thanks - just curious to learn what I was missing
