### ISSUE TITLE
JS is not working on board page

### ISSUE THREAD

**Issue by alirz23** [fguillot/kanboard#1355]
Hi,

After you click on the "add a new task" and lets say you cancel it for some reason after the popover is closed the javascript on the page does not work. the swimlane collapse and expand buttons don't work anymore.

btw how are the assets being loaded I looked everywhere could not find reference to js files.

**Comment by oparoz** [comment]
@fguillot something added these past 3-4 days broke the routing I think. From the board, we're automagically redirected to the dashboard and there are 2 headers. Some task quick actions don't work well. It's impossible to edit tasks.

It seems to come from the background updater since it happens after 10 seconds or so.

**Comment by oparoz** [comment]
![double_header](https://cloud.githubusercontent.com/assets/323220/10429257/844a203a-70f7-11e5-98b0-2baa43d1a2f0.png)

**Comment by fguillot** [comment]
Are you sure that the problem is not related to your server installation/configuration? did you flush the php opcache, close all user sessions? do you have any sort of magic proxy that alter the javascript like Cloudflare or stuff like that?

**Comment by oparoz** [comment]
You're right. Got a 503 in another session. Restarted PHP and the problem went away. Sorry for the noise.

**Comment by BlueTeck** [comment]
Could confirm the probem of @alirz23. Click on plus to create a new task, cancel, try to collapse swimlane does not work. (latest Chrome)

**Comment by alirz23** [comment]
@fguillot I cloned the repo on my development machine everything is local no proxy in place I have a fixed the bug let me do PR
