### ISSUE TITLE
use Kanboard as vendor prefix in namespaces

### ISSUE THREAD

**Issue by jakoch** [fguillot/kanboard#1356]
Hey Frédéric,

thank you for introducing the plugin API. Its a great feature addition to the system.
Please let me suggest a small namespace change to make things more clear.
The idea is to add "Kanboard" as top-level vendor prefix to the namespace.

Instead of `namespace Plugin\Foobar;` it will be `namespace Kanboard\Plugin\Foobar;`.
Then the namespace itself expresses to which "vendor" a "plugin" belongs.

The same namespace change might be applied to the "base" classes living inside the "/app" folder. 
That means the use-statement in plugins changes from 
 `use Core\Plugin\Base;` to `use Kanboard\Core\Plugin\Base;`

I know, that this minimal change affects a whole bunch of files, but with the arrival of the plugin system its probably the right time to make it, before more plugins are written without a vendor prefix.

Regards, Jens

**Comment by oparoz** [comment]
I agree. It was confusing to see `Core` as the "vendor"

**Comment by fguillot** [comment]
Yup, I was thinking about that, make sense after all. I will do the crazy search and replace.

**Comment by fguillot** [comment]
This change have been made to the development branch.

**Comment by martinfrances107** [comment]
I am getting a autoloading failure after this change is pulled.

[14-Oct-2015 13:32:17 Europe/Berlin] PHP Fatal error:  Class 'Kanboard\ServiceProvider\LoggingProvider' not found in /xx/kanboard/app/common.php on line 27

flushing caches and restarting the php service does not fix it.

As far as I can see the changes to the LoggingProvider class look ok ... I am not sure what is wrong.

**Comment by fguillot** [comment]
@martinfrances107 did you regenerate the composer autoloader?

```
git pull && composer install && service apache2 reload
```

**Comment by martinfrances107** [comment]
Thank you,  the composer install was the part I was missing :)

**Comment by oparoz** [comment]
All plugins have to be deleted or Kanboard won't work any more.
