### ISSUE TITLE
Search: filter by swimlane

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#1358]
This can be particularly useful when in list or gantt view, especially if you're using swimlanes for milestones

**Comment by fguillot** [comment]
You can already do it: https://github.com/fguillot/kanboard/blob/master/doc/search.markdown#search-by-swimlane

**Comment by oparoz** [comment]
Thank you, for some reason, it was missing from the in-app doc I was looking at, but I can't reproduce the problem at the minute, so I must have been temporarily blind ;)
