### ISSUE TITLE
Link to "closed tasks" in project summary

### ISSUE THREAD

**Issue by danielraknes** [fguillot/kanboard#1359]
Hi!

In the project summary page there is a link to closed tasks.

When I click on the link, I get a "Page not found".  
http://localhost/kanboard/?controller=project&action=show&project_id=1
  
Should'nt this link be like this instead? (project -> projectinfo)
http://localhost/kanboard/?controller=projectinfo&action=tasks&project_id=1

Best regards 
Danny

**Comment by fguillot** [comment]
You should upgrade because this issue have been fixed a while ago.
