### ISSUE TITLE
Task Title Allow Markdown

### ISSUE THREAD

**Issue by duanebc** [fguillot/kanboard#1366]
It will be great to be able to format the data on each Task.  I think converting this to markdown will allow this functionality.

**Comment by froschdesign** [comment]
:-1: 
This brings only disturbance in the board / cards.

Use colors to highlight a card.

**Comment by alirz23** [comment]
perhaps in description but how does markdown in title makes sense

**Comment by 85pando** [comment]
The only thing that would make sense here in my opinion would be to emphasize text with **bold** or _italic_ in titles, but I'd rather agree with @froschdesign here, that this would disturbe the board.

**Comment by EpocDotFr** [comment]
:-1:

**Comment by duanebc** [comment]
When working on a ticketing system we had a physical kanban board, that we've spent some time with and came up with a structure that we like that I'm having a hard time representing with just a string.  Unless, we can use new lines, and grow the size of cards (I'm still within my first week).  Things like bolt text, new lines, and text alignment is more what I'm looking for.

**Comment by froschdesign** [comment]
> Things like bolt text, new lines, and text alignment is more what I'm looking for.

A title should contain only critical information. If you need text formatting, then your title is wrong.

**Comment by duanebc** [comment]
When working with a ticketing system, there may be some information that you may want to highlight that's visible.  Allowing HTML or some sort of formatting will definitely benefit.  While the information is critical that we're looking to display, the way it can be displayed is what we're looking at.

**Comment by froschdesign** [comment]
> While the information is critical that we're looking to display, the way it can be displayed is what we're looking at.

It's a *only* title!

(Btw. you can create your [own implementation](http://kanboard.net/documentation/plugins) to handle text formatting for titles.)

**Comment by oxydron** [comment]
I think that exists a difference between a **feature exist** and people **using it**. See, I agree with most people here, saying that a title is already important and doesn't need to emphasize nothing, but for some people that disagree with us, it is important. Different teams has different needs.

And the best thing, people are not **obliged** to use it, if it is implemented! Then, for those who think that title doesn't need any markdown, nothing will change really.

I upvote this request. :+1:

**Comment by 85pando** [comment]
So you are using the title more in the sense of "displayed text" it makes more sense to say that you want to be able to format it. For me titles have been just for displaying the topic of the note, all other information is in the description, which I was always glad about not having displayed directly on the note.

With your further description it is better understandable, what you want this feature for. Still I would prefer (knowing some of the people I work with) that this might (if implemented) be a board-wide option that can be disabled.

**Comment by froschdesign** [comment]
@oxydron 
> And the best thing, people are not obliged to use it, if it is implemented!

@85pando
> …(if implemented) be a board-wide option that can be disabled.

The choice is yours: Create a plugin or create the next [feature creep](https://en.wikipedia.org/wiki/Feature_creep) monster!

**Comment by oxydron** [comment]
@85pando Do you use every feature of Kanboard? I think most here don't.
And WOW such a feature creep, to allow people to format text in *italic* or **bold** OMG!!!

**Comment by froschdesign** [comment]
> I believe most here don't use every single feature of Kanboard and there it is.

Right! And why would you implement a function, which is used by less than 20% of the users?

> And wow, such a feature creep, to allow people to format text in italic or bold.

[Have a look!](https://github.com/fguillot/kanboard/issues?q=is%3Aopen+is%3Aissue+label%3A"feature+request")

**Comment by sparkles645** [comment]
:-1:

**Comment by fguillot** [comment]
Won't be part of the core, if someone want that make a plugin.
