### ISSUE TITLE
compose.lock

### ISSUE THREAD

**Issue by reiner** [fguillot/kanboard#1367]
Hey there, when I try to update to the new version I get:

error: Your local changes to 'composer.lock' would be overwritten by merge.  Aborting.

I am actually logged off. What else can I do?

Thank you very much and keep up the great work!
Reiner

**Comment by fguillot** [comment]
Probably because you have done a `composer update` instead of `composer install`. Just revert the file: `git checkout composer.lock` and check with `git status` what else you have modified...

**Comment by reiner** [comment]
thank you, this worked.
