### ISSUE TITLE
[Improvement] Choose wich colors will be visible and usable

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#1370]
It's a very nice feature to have square for colors to colorize tasks, but, in most teams I think that 3 or 4 colors will be used the most to represent categories or importance levels.

If we could set which colors will be visible, would be nice.

Best regards,
Ben Hur

**Comment by sparkles645** [comment]
@oxydron 
Doesn't this request kind of contractict your original request - ref #1071 ?

* We use "Categories" and "Automatic actions" to decide the colors of the task - **would that solve your use case?**

**Comment by BenWShade** [comment]
And choose the exact colours in settings. We have colour blind people on the team and they can't tell the difference between 80% of the current default colours so is useless to them. If they could edit the default colours to make them 'more different' then all the team could use the colours fully.

Great job so far. 
Thanks

**Comment by oxydron** [comment]
@BenWShade  :+1: even better indeed.

@manuelflara :+1: Good work.

Great job guys!

**Comment by manuelflara** [comment]
I tried to address both of your concerns when writing the code for my pull request. 

Hopefully it fulfills your needs :)
