### ISSUE TITLE
insert of remote users from a ldap/ad server are not made with lowercase 

### ISSUE THREAD

**Issue by Lumin0s** [fguillot/kanboard#1376]
When kanboard is configured to use Active directory or LDAP, if user exist in LDAP with uppercase like "USername" for example it is inserted in sqlite (probably mysql also ) with uppercase same like in LDAP "USername", kanboard should make it with lowercase (an older version worked corectly) and kanboard deny user because in database he expect to find user with lowercase if below option is set to false:
define('LDAP_USERNAME_CASE_SENSITIVE', false);

**Comment by Lumin0s** [comment]
same like #1373

**Comment by Lumin0s** [comment]
Hi 
a workaround until a patch is released
kanboard/app/Auth/Ldap.php 
on line 387 change like below


          // 'username' => $username,
           'username' => strtolower($username),

**Comment by mrajwadk** [comment]
Yup... that works... thanks...

**Comment by sparkles645** [comment]
@mrajwadk : reason for converting to lower caps --> see #578

**Comment by Lumin0s** [comment]
but not converting to lower caps

**Comment by fguillot** [comment]
You should try again with the latest stable version. Kanboard lowercase the username by default, see: http://kanboard.net/documentation/ldap-parameters
