### ISSUE TITLE
Feature Request: Change Language per Project

### ISSUE THREAD

**Issue by phillc73** [fguillot/kanboard#1377]
I work in a multi-language workplace. English is generally the language used within the company, as we have employees of many different nationalities and English is common. However, the native language of the majority of employees is German.

Our Kanboard installation is in English, and I don't wish to change this.

However, some teams have requested the possibility to have just their projects in German.

At the moment, I cannot see a way to set language preferences per project, rather just for the entire installation. This request is therefore to add an option to set the project language, independent of the overall installation language setting.

**Comment by oxydron** [comment]
:+1: It is a good idea.

**Comment by TabDambrine** [comment]
I'm skeptical about this FR. I'm pretty sure the option of per-user language (see #451) is a better option.

**Comment by sparkles645** [comment]
:-1:

**Comment by phillc73** [comment]
I think @TabDambrine is right. The per-user language will satisfy my requirement.

I'm going to close this.

**Comment by thob** [comment]
One benefit of per project language settings is that notification that go to Slack or others are independent of  user settings _(imagine I set my language to Russian and the team only speaks German)_
