### ISSUE TITLE
Minimized Card - Description not visible

### ISSUE THREAD

**Issue by elvince** [fguillot/kanboard#1378]
Hi,

When minimizing cards on the board, the decription is not available.
I don't know if it's a bug as when we hover the title link, the title is put in the tootip or if it's a new feature to add the small icon to have the description in this mode.

thanks,

**Comment by sparkles645** [comment]
@elvince 
* Not a bug.
* Since minimizing cards -  a.k.a. "Collapse tasks" - was introduced in v 1.0.12, description icon has **not been present** on the collapsed task.

**Comment by elvince** [comment]
Thanks,

I implemented locally, but I didn't take into account the Title length. So on big title, it goes over the icon ^^

in /app/Template/board/task_private.php

Line 23:

add:
```php
<?php if (! empty($task['description'])): ?>
        <span title="<?= t('Description') ?>" class="tooltip" data-href="<?= $this->url->href('board', 'description', array('task_id' => $task['id'], 'project_id' => $task['project_id'])) ?>">
            <i class="fa fa-file-text-o"></i>
        </span>
    <?php endif ?>
```
