### ISSUE TITLE
Moving tasks on board not working as it used to work (KB 1.0.19)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1380]
Noticed this behaviour - first in 1.0.18
* In 1.0.19 it's become worse.
* Instead of writing alot - I'll describe it with a .gif below.
* **The tasks won't "hook onto" in the receiving column at first**
* **If close to the title of the column, and after "warming up" - it works.**
* Really strange

**System:** 	
* Linux ws02k41 3.16.0-0.bpo.4-amd64 # 1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 

**Running:** Apache/2.2.22 

**Browser** Firefox 41.0.2

![1](https://cloud.githubusercontent.com/assets/10092252/10548485/67401886-743b-11e5-8a55-91b0eb7f035c.gif)

**Comment by sparkles645** [comment]
The lastest version that is quick for "proper use" on our big server  - is 1.0.16 - that is before (gut feeling) "Move board collapse/expand mode to server side to avoid board flickering" - introduced in 1.0.17 - **is the server more loaded from 1.0.17 and onwards - could that be a reason**?

**Comment by fguillot** [comment]
If you disable the "max column height / vertical column scrolling" as it's seems to be the case in your screencap, the drop zone for the task is the top of the column, the placeholder is the same height as the task. I know that it's something to improve...

Can you validate that if you enable the "max. column height" it works correctly?

**Comment by sparkles645** [comment]
Confirmed.
* With "Set maximum column height" active = not an issue, work fine moving tasks between columns
* With "Remove maximum column height" active = issue is present, have to move task close to column title to make it "catch"

**Comment by fguillot** [comment]
This issue is now fixed in the dev branch.
