### ISSUE TITLE
Have to click 2-3 times in menu to get reaction from server (KB 1.0.1.9)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#1381]
* My off-site personal (testing) server is located at a well-renowned national company that carries a lot of traffic and have high capacity on their servers. 
* When clicking menues in KB 1.0.1.9, I experience that I have to provoke menu and click 2-3 times (repeat procedure) before I get a response and my command is actuated in the browser. (tested on different computers)
* **Is it just me having this experience with 1.0.19?**
* Doesn't happen every time, but once-in-every 10-or-12 "menu access" attempts

System: Linux ws02k41 3.16.0-0.bpo.4-amd64 # 1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64

Running: Apache/2.2.22

Browser Firefox 41.0.2

**Comment by fguillot** [comment]
- Enable the debug mode
- Open the file `data/debug.log`
- You will see the execution time for each SQL query and each HTTP request
- If the page rendering time is greater than few hundred milliseconds that means something is wrong
- Most often, that comes from a slow SMTP server when Kanboard is sending notifications or a slow Integrations... Do you have configured anything special in Kanboard?

**Comment by sparkles645** [comment]
No special notification / mail setup on this instance.

* Turns out - it's a hitbox issue in the menu - clicking the icon or just outside the text doesn't initiate the action - have to **hit the text exactly** to get the action.

**Comment by fguillot** [comment]
It's now fixed in master. Thanks.
