### ISSUE TITLE
Markdown WYSIWYG Editor Plugin

### ISSUE THREAD

**Issue by sebastiantiede** [fguillot/kanboard#1384]
https://github.com/sebastiantiede/kanboard-plugin-wysiwyg

This plugin overrides core comment textareas and extends it with common shortcuts like bold, italic.

Any suggestions / corrections are welcome.

**Comment by BlueTeck** [comment]
:+1:

**Comment by sparkles645** [comment]
:+1:

**Comment by Chaosmeister** [comment]
:+1:

**Comment by fguillot** [comment]
Do you want me to publish your plugin on kanboard's website?

**Comment by sebastiantiede** [comment]
yes of course

**Comment by fguillot** [comment]
http://kanboard.net/plugin/wysiwyg
