### ISSUE TITLE
upload file error

### ISSUE THREAD

**Issue by gaust** [fguillot/kanboard#1386]
Hi, on windows 7, apache 2.4.9, php 5.5.12
i've got this error when trying to upload a file 

( ! ) Warning: move_uploaded_file(data/files/\10\31\c89eb5bda92d1141cde845e68ed5d9173dab1831): failed to open stream: No such file or directory in C:\Program Files (x86)\WAMP\www\kanboard\app\Core\ObjectStorage\FileStorage.php on line 114
Call Stack
#	Time	Memory	Function	Location
1	0.0000	249360	{main}( )	..\index.php:0
2	0.0210	2188408	Core\Router->dispatch( )	..\index.php:5
3	0.0310	3179384	Controller\File->save( )	..\Router.php:225
4	0.0320	3293720	Model\File->uploadFiles( )	..\File.php:65
5	0.0330	3334848	Core\ObjectStorage\FileStorage->moveUploadedFile( )	..\File.php:286
6	0.0330	3335080	move_uploaded_file ( )	..\FileStorage.php:114

( ! ) Warning: move_uploaded_file(): Unable to move 'C:\Program Files (x86)\WAMP\tmp\php2892.tmp' to 'data/files/\10\31\c89eb5bda92d1141cde845e68ed5d9173dab1831' in C:\Program Files (x86)\WAMP\www\kanboard\app\Core\ObjectStorage\FileStorage.php on line 114
Call Stack
#	Time	Memory	Function	Location
1	0.0000	249360	{main}( )	..\index.php:0
2	0.0210	2188408	Core\Router->dispatch( )	..\index.php:5
3	0.0310	3179384	Controller\File->save( )	..\Router.php:225
4	0.0320	3293720	Model\File->uploadFiles( )	..\File.php:65
5	0.0330	3334848	Core\ObjectStorage\FileStorage->moveUploadedFile( )	..\File.php:286
6	0.0330	3335080	move_uploaded_file ( )	..\FileStorage.php:114

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\Program Files (x86)\WAMP\www\kanboard\app\Core\ObjectStorage\FileStorage.php:114) in C:\Program Files (x86)\WAMP\www\kanboard\app\Core\Response.php on line 73
Call Stack
#	Time	Memory	Function	Location
1	0.0000	249360	{main}( )	..\index.php:0
2	0.0210	2188408	Core\Router->dispatch( )	..\index.php:5
3	0.0310	3179384	Controller\File->save( )	..\Router.php:225
4	0.0591	3696208	Core\Response->redirect( )	..\File.php:69
5	0.0591	3696400	header ( )	..\Response.php:73

Any idea? thanks !

**Comment by gaust** [comment]
if i hit back on the error and go to the task, the file appeared to be here but is empty.

**Comment by fguillot** [comment]
It's now working on Windows with the last master. Thanks.
