### ISSUE TITLE
Wunderlist plugin

### ISSUE THREAD

**Issue by EpocDotFr** [fguillot/kanboard#1387]
https://github.com/EpocDotFr/kanboard-wunderlist

This plugin allow you to import [Wunderlist](http://www.wunderlist.com/) tasks and lists directly from the user interface of Kanboard by uploading a Wunderlist export file. It is the successor of [this script](https://github.com/EpocDotFr/WunderlistToKanboard).

This plugin is WIP.

**Comment by EpocDotFr** [comment]
Version 1.0-beta just landed: https://github.com/EpocDotFr/kanboard-wunderlist/releases/tag/v1.0-beta

**Comment by EpocDotFr** [comment]
Version 1.0 available.

**Comment by fguillot** [comment]
Do you want me to list your plugin on Kanboard's website?

**Comment by EpocDotFr** [comment]
Yup :smile:
