### ISSUE TITLE
Reverse proxy user is only checked at login

### ISSUE THREAD

**Issue by mbugeia** [fguillot/kanboard#1391]
I use Kanboard with reverse proxy authentification and I have kind of a security issue.

1. a user1 is logged in
2. user1 logged out of the reverse proxy
3. user2 logged in on the reverse proxy and go to kanboard
4. user2 is connected to kanboard with the credential of user1

The reason seems to be simple: kanboard doesn't check if the session user match the reverse proxy user so while the kanboard session exist, the user doesn't change. And a reverse proxy only take care of destroying its own sessions, not the applications ones.

I can mitigate the risk by setting a short SESSION_DURATION in config file but for me it's not a very good solution. Kanboard should always check that the session's user is the same as the user sent by the reverse proxy. 

I believe this has to happen in this function: https://github.com/fguillot/kanboard/blob/master/app/Model/Authentication.php#L44-L51
What do you think ?

**Comment by fguillot** [comment]
I added a check in master that should fix your issue.

**Comment by mbugeia** [comment]
Nice! I tested your fix, it works, a little bug however, now when user2 login it first get a blank page, but after a refresh everything is ok.

**Comment by fguillot** [comment]
Do you have any php errors? How is configured your reverse proxy setup? which software do you use?

**Comment by mbugeia** [comment]
No php errors, I checked all the log. My reverse proxy is configured like this https://github.com/mbugeia/kanboard_ynh/blob/master/conf/config.php the reverse proxy is ssowat which send the REMOTE_USER param with each request.

The exact issue is that when I try to access https://domain.tld/kanboard with the second user I'm stuck on a blank page on https://domain.tld/kanboard/?controller=auth&action=login and I have to go a second time to https://domain.tld/kanboard to make it work.

With debug activated here is the blank page request:
http://paste.yunohost.org/gifimuduye.lua

**Comment by mbugeia** [comment]
Looking at the code the reason seems to be that if a the reverse proxy user doesn't match the session user, the session is closed but kanboard don't automatically try to login with the new reverse proxy user.

**Comment by fguillot** [comment]
Right

**Comment by fguillot** [comment]
Can you check if your issue is solved with the last version of the master branch?

Thanks

**Comment by mbugeia** [comment]
The issue is now fully solved. Good work, thank you very much.

For you to know Kanboard is now, since 3 weeks, an official app in Yunohost. :smiley:  That's mean it's a one click install in the web administration for all users.
Announcement here: https://forum.yunohost.org/t/yunohost-and-internet-cube-surveillance-report-3/1033

**Comment by fguillot** [comment]
Awesome :)

So I close this issue.
