### ISSUE TITLE
Import what is exported

### ISSUE THREAD

**Issue by Joan-Andreu** [fguillot/kanboard#1393]
We have the "exports" action, but no import action.

It would be great if the project manager could exports/imports all tasks, and it would be awesome if an automatic exports by mail would be possible to trigger at a selected hour of the day.

In other online project I always use exports as a backup of all the tasks. A manager/user can delete a task by error, etc...

Thank you and happy to see you in FramaBoard !

Joan.

**Comment by fguillot** [comment]
There is already a import feature in the development branch.

**Comment by emanueledf** [comment]
Hi there, 
I think it would be useful if export and import shares the same csv template.
At the moment they are different. What do you think?
Thank you for your work, kanboard is great!
Ciao,
Emanuele
