### ISSUE TITLE
Summary of a project doesn't show the closed tasks

### ISSUE THREAD

**Issue by jfrenard** [fguillot/kanboard#1395]
Hello,
If I want to have on the dashboard, section "My Tasks", just tasks not completed, I must close those which are completed. But, in this case, the summary of the project doesn't take into account the closed one. Look the attached files for example: this project has 11 tasks, each completed. I closed 2 to make it undisplayed.
Is ther a way to solve this now or, if not, could it be integrated in a future release?
Thank you.
![kanboard_dashboard](https://cloud.githubusercontent.com/assets/15198873/10631478/a0f71cea-77de-11e5-99d6-2e418b6ea56b.png)
![kanboard_dashboard_my_tasks](https://cloud.githubusercontent.com/assets/15198873/10631479/a0fd18f2-77de-11e5-8956-a7a3c263d9b6.png)

**Comment by fguillot** [comment]
This is the expected behaviour, the dashboard show only open tasks. If you want to see closed tasks, you have to use the search form by using the query "status:closed" or if you want to see both "status:all".

**Comment by jfrenard** [comment]
Thank you for the tip "status:all". It's ok for the dashboard of tasks but not for the dashboard of projects.
I found a way with automatic action: when the task is moved to "completed" it assigns "nobody". So, the project manager has a complete overall vision and the members don't have opened tasks anymore while there are completed.
