### ISSUE TITLE
Kanboard export: csv file empty

### ISSUE THREAD

**Issue by jfrenard** [fguillot/kanboard#1396]
Hello,
everything is in the title: whatever I do, every csv export produces an empty file except headline.
Is there something to activate?
Thank you.

**Comment by fguillot** [comment]
Do you have tasks created in the date range you have specified?

**Comment by jfrenard** [comment]
I thought so and I figured out what was the matter. Actually, the point is the creation date of the task, not the execution date... Am I right if I say that export concerns the lead time, not cycle time?

**Comment by fguillot** [comment]
Correct, it's based on the creation date.
