### ISSUE TITLE
PHP JSON rpc fails to create task when date is given

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#1398]
I am trying to create a task passing due date. If I pass due date, it does not create the task, and returns blank. I have tried several combination of date format. 

date_default_timezone_set('UTC');
$date= date('c');
//$date= date('Y-m-d\TH:i:s');
//$date=strtotime('now') ;
echo "Date: " . $date ."\n";
$task = $client->createTask(array('owner_id'=>2, 'creator_id'=>2, 'project_id'=>19, 'title'=>'title','description'=>'description','date_due'=>$date));
echo "Task ID:" . $task . "\n";

Response comes as:

==> Response:
{
    "jsonrpc": "2.0",
    "id": 1241178442,
    "result": false
}

Without date, it works fine. 

How do I get the right date format?

**Comment by BlueTeck** [comment]
Did you tested this? 

```php
date('Y-m-d')
```

https://github.com/fguillot/kanboard/blob/master/tests/functionals/ApiTest.php#L1062

**Comment by fguillot** [comment]
Use the ISO8601 date format: "2015-10-24"
