### ISSUE TITLE
gitlab authentication error

### ISSUE THREAD

**Issue by scottder** [fguillot/kanboard#1400]
I am attempting to set the stable release with gitlab. I have gotten as far as getting it to redirect to an internal insance of gitlab and I am able to authorize it to connect with kanboard but then when I get back to the login "External authentication failed" the debug look like they are gettng what they need from gitlab but then the user is not created.

**Comment by waja** [comment]
Did you have a look into Debug logging?

```sh
$ grep DEBUG config.default.php
define('DEBUG', false);
define('DEBUG_FILE', __DIR__.'/data/debug.log');
```

**Comment by scottder** [comment]
Yes. It was in those logs where I saw that kanboard was getting back what looks like appropriate info from gitlab. But then I'd get the above error and no kanboard user was created.

**Comment by waja** [comment]
Do you think without a bit more info (for example the corresponding logs) anybody is able to help you? Telling others 'It doesn't work, please help!' might a bit unhelpful to help you with your problem.

**Comment by fguillot** [comment]
Note that Gitlab OAuth is working only if you have enabled url rewriting for Kanboard because Gitlab doesn't support url with query string arguments.

**Comment by scottder** [comment]
What sort of rewriting needs to be done?

**Comment by waja** [comment]
http://kanboard.net/documentation/gitlab-authentication#known-issues
http://kanboard.net/documentation/nice-urls

**Comment by scottder** [comment]
Ok I have that enabled, do i need to change the gitlab redirect uri?

**Comment by scottder** [comment]
Nevermind, I found the oath url in interrogations. Still is returning the error however.

**Comment by grzegorzkluczek** [comment]
Finally I was able to make gitlab auth working, but it was tricky. Here's what I did

#### 1. Rewrite
First of all, you need to turn on url rewriting:

  1. Enable mod_rewrite
  ```sh
  $ sudo a2enmod rewrite
  ```

  2. Comment out the ENABLE_URL_REWRITE in config.php (or set it to true):
  ```php
  // Enable/disable url rewrite
  //define('ENABLE_URL_REWRITE', false);
  ```

#### 2. HTACCESS
Second, somehow I was missing [.htaccess](.htaccess) in root directory, which prevented mod_rewrite from working.

#### 3. External user
Create external user in kanboard and make sure you fill Gitlab Id. You can check your gitlab user id with api:
```sh
$ curl -k https://your.gitlab.com/api/v3/users?private_token=TOKEN
```
You can check your token value in your profile settings: https://your.gitlab.com/profile/account

#### 4. Gitlab Redirect
After you enable url rewrite, you should update callback url in gitlab to be like:
```
https://your.kanban.com/oauth/gitlab
```

**Comment by at15** [comment]
I  got similar issue, and solved by create remote user in admin panel. It seems the gitlab integration does not create new user if it does not exists.

**Comment by ahmader** [comment]
Thank you @at15, your hint helped me to trace the problem and find a workaround, now I can successfully login using GitLab

modify the file: **_app/User/OAuthUserProvider.php_**

```php
    public function isUserCreationAllowed() 
    {
        return true; // change to true
    }
```

and 

```php
    public function getUsername()
    {
        return $this->user['username']; // return the username
    }
```

@fguillot Can you look into this? is it ok to use the above workaround ?

**Comment by fguillot** [comment]
Gitlab auth have been moved to a plugin now. If you have any problem, open issues here: https://github.com/kanboard/plugin-gitlab-auth
