### ISSUE TITLE
Create teams

### ISSUE THREAD

**Issue by jfrenard** [fguillot/kanboard#1401]
Hello,
it would be useful to have the possibility to create teams, kind of logical entity in which we can group users (for the moment, I use swimlanes to manage tasks between teams).
Thank you.

**Comment by TabDambrine** [comment]
:+1:

**Comment by BlueTeck** [comment]
->  #522

**Comment by bdrayer** [comment]
Would be a great idea to add group supports. Especially for adding rights to a Project.

**Comment by BlueTeck** [comment]
Now work in progress :smile: 

https://github.com/fguillot/kanboard/commit/e582d4047b061f0c17e6366fed2bf1cabd624c10

**Comment by bdrayer** [comment]
Great thank you in advance :-)

**Comment by fguillot** [comment]
Teams have been implemented in the development branch. You could test this feature and report potential bugs if you would like to.
