### ISSUE TITLE
SMTP: Hostname

### ISSUE THREAD

**Issue by GitHub-Lover** [fguillot/kanboard#1403]
I use for notifications (e.g. overdue) SMTP host for sending. I did copy my info from my mail-program to config.php:

```
define('MAIL_FROM', 'noreply@[..]');
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_SMTP_HOSTNAME', 'arcadius.metanet.ch');
define('MAIL_SMTP_PORT', '465');
define('MAIL_SMTP_USERNAME', 'noreply@[..]');
define('MAIL_SMTP_PASSWORD', '[..]');
define('MAIL_SMTP_ENCRYPTION', 'ssl'); // Valid values are "null", "ssl" or "tls"
```

**./kanboard  notification:overdue-tasks 
did not work (without any error-message).**

When I did ping arcadius.metanet.ch then i get this back:
```
64 bytes from arcadius.ch-meta.net (80.74.141.2): icmp_req=1 ttl=58 time=13.0 ms
```

So I changed MAIL_SMTP_HOSTNAME in config.php to arcadius.ch-meta.net and from that moment:

**./kanboard  notification:overdue-tasks 
did work.**

Why is my mail-program working with hostname arcadius.metanet.ch and Kanboard not? Is this an issue of your code?

Thank you.

**Comment by waja** [comment]
Maybe you should try to enable Debug Logging:

```sh
$ grep DEBUG config.default.php
define('DEBUG', false);
define('DEBUG_FILE', __DIR__.'/data/debug.log');
```

This might help to trace your problem down instead then "doesn't work"

**Comment by sanjayrup** [comment]
you can try to set 80.74.141.2 for smtp hostname. Maybe a dns resolve problem from you server ?

**Comment by GitHub-Lover** [comment]
sorry, guys. I'm a bit confused: in the moment both 'arcadius.metanet.ch' and 'arcadius.ch-meta.net' works fine.

I thought it is a issue of reverse DNS, that kanboard only accept hostnames for mailserver which are the reverse-DNS-name.

@fguillot this issue can be closed. Thank you for all.
