### ISSUE TITLE
Please add a link on login, where user can reset password

### ISSUE THREAD

**Issue by GitHub-Lover** [fguillot/kanboard#1406]
We have this in other Web-app like this:

- User click for password-reset-request to e-mail of user
- Kanboard would send a link. When the user clicks on it: Kanboard set a new password and send it to user. Sent link will be invalid from this moment (alternatively: link leads to a site where user can change password).

Thank you.

**Comment by francoisjacquet** [comment]
+1 for this feature.
And thank you for your great work in use @ [Framaboard](https://framaboard.org)!

**Comment by marienfressinaud** [comment]
It would be a great feature for Framaboard indeed :+1:. For the moment we implemented a small admin interface to be able to reset passwords but we have to do it manually for each user.

**Comment by marienfressinaud** [comment]
For your information, I opened [a post on Framacolibri (fr)](https://framacolibri.org/t/developpeur-systeme-de-reinitialisation-du-mot-de-passe-pour-framaboard/628) (Framasoft's community tool) to ask if someone wants to work on this feature.

Wait and see… :)

**Comment by fguillot** [comment]
It can also be done with a plugin.

**Comment by iPublicis** [comment]
+1 for this one :)

@fguillot why using a plugin for this task? Resetting a password is a basic requirement for any software like this one. If using LDAP or other external service the dedicated plugin should implement it with something like http://logout.sh/computers/ldap/

**Comment by fguillot** [comment]
This feature has been added into the development branch of Kanboard.

To make it work, the user must have an email address and Kanboard must be configured to send emails. This feature can also be disabled from the settings page.

**Comment by marienfressinaud** [comment]
Thanks @fguillot!
