### ISSUE TITLE
SMTP Mail Notification does not work for SMTPS servers in PHP 5.6 and above

### ISSUE THREAD

**Issue by weizenspreu** [fguillot/kanboard#1408]
PHP 5.6 introduced peer validation as a default for TLS connections:
http://php.net/manual/en/migration56.openssl.php

As it is, kanboard does not allow the administrator to configure socket-specific parameters that are required to make SMTPS connections work in PHP 5.6. Unfortunately, SwiftMailer (that is used as the mail framework) does not support to configure socket-specific parameters by default:
https://github.com/swiftmailer/swiftmailer/issues/544

In order to solve the problem, the ./kanboard/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php file has to be extended in method _establishSocketConnection() between line 262 and 263 (before the call to stream_socket_client()) with the following:

    $options['ssl']['verify_peer'] = MAIL_SMTP_SSL_VERIFY_PEER;
    $options['ssl']['peer_name']   = MAIL_SMTP_SSL_PEER_NAME;
    $options['ssl']['ciphers']     = MAIL_SMTP_SSL_CIPHERS;
    $options['ssl']['cafile']      = MAIL_SMTP_SSL_CAFILE;

Now the conf.php file can be extended appropriately:

    define("MAIL_SMTP_SSL_VERIFY_PEER", true);
    define("MAIL_SMTP_SSL_PEER_NAME",   "smtp.example.com");
    define("MAIL_SMTP_SSL_CIPHERS",     "HIGH:!aNULL:!eNULL:!3DES:!MD5:!RC4:@STRENGTH");
    define("MAIL_SMTP_SSL_CAFILE",      "/path/to/server/ca.pem");

PHPMailer supports this socket-specific configuration by default, while SwiftMailer still has not released version 5.4.2, which would include the necessary change:
https://github.com/acinelli/swiftmailer/commit/71dfa16d65a8703a309f10af9fbb188e488120c5

**Comment by fguillot** [comment]
With valid SSL certificates you should not need to modify anything. But you should be able to install the missing certificate on the operating system to avoid manual modification of the application?

I'm using PHP >= 5.6 on multiple operating systems and I don't have any problem as long as the certificate is valid.

**Comment by weizenspreu** [comment]
You get problems with PHPs way of handling certificates as soon as you're using a chroot environment. At least that's what I found out.

**Comment by tscs37** [comment]
I'm having this issue too, I used the fix, which does correct the issue, it would be nice if the fix goes upstream (or some other solution).
