### ISSUE TITLE
More granular roles and state-changes

### ISSUE THREAD

**Issue by weizenspreu** [fguillot/kanboard#1409]
At the moment any project member is allowed to create new tasks and to change the state of existing tasks at will. It would be nice to have more granular roles so that only members with a specific role are allowed to create tasks, while members with other roles are allowed to change the state of the task from one specific state to another specific state.

**Comment by oxydron** [comment]
:+1: 
Administrators, moderators and users.

**Comment by fguillot** [comment]
There are more application and project roles now: see https://github.com/fguillot/kanboard/blob/master/doc/roles.markdown
