### ISSUE TITLE
Missing Boardview screenshot-previews that were migrated from Version <1.0.19.

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1410]
Very good job on Version 1.0.20! The UI finally behaves wonderfully.

The fallback from #1375 works in the Taskview, but the Previews are still missing in the Boardview:

![image](https://cloud.githubusercontent.com/assets/13346344/10725534/f5c70612-7bcc-11e5-8456-7d1d24cb73ba.png)

They are still missing after the fallback created the preview in the Taskview.

"open file" displays the screenshot correctly.

Again:
Server: IIS (Version 8.5.9600.16384) on Windows 8.1 Enterprise.
Browser: Latest Chrome on Windows 8.1.

**Comment by BlueTeck** [comment]
If I remember correct, there was no preview in board view. The icon only indicates, that the attachment is an image.

**Comment by Chaosmeister** [comment]
My fault! I just tried with 1.0.16 and it also does not display a preview but the screenshot-icon.
I had this image in my mind, where the boardview would also display previews of screenshots.
