### ISSUE TITLE
server error on incorrect plugin.php

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1419]
Yesterday I tried to install this [plugin](https://github.com/sebastiantiede/kanboard-plugin-wysiwyg) which was not updated to 1.0.20 yet.
The plugin.php was missing the "kanboard\" in the namespace and use directives.

After I added them, the plugin worked without a problem.

But finding the error was extremely hard:
With the incorrect plugin.php our IIS only returned "Internal Server Error (500)".
Even without the plugin.php the server responds with "Internal Server Error (500)".
Enabling debug in kanboard did not help either.
After I compared the plugin.php of an working plugin with the incorrect plugin.php, I was able to identify and fix the issue.

Could you improve the errorhandling for plugins so kanboard won't become unusable while trying out plugins?

There are some cases where the whole kanboard becomes unusable:
- a completely empty folder in the plugin directory - name doesn't matter.
- the plugin's folder has a different name than written in the plugin.php.
- the plugin.php is incorrect.

Server: Windows 8 - IIS 8.5.9600.16384

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
The error handling of plugins have been improved in master, that will display a better error message now.

However PHP errors still handled by the default PHP error handlers. In your case, your server configuration seems to generate an error 500 and probably output the exact cause in the event logger.
