### ISSUE TITLE
Default 'change assignee/category' buttons for tasks in board view

### ISSUE THREAD

**Issue by aliusmiles** [fguillot/kanboard#1420]
Would be nice to have some default buttons for tasks without assigned assignee/category, so task could be updated directly from board view, without editing.

**Comment by Chaosmeister** [comment]
Click on the number of the task:

![image](https://cloud.githubusercontent.com/assets/13346344/10813632/c0753eba-7e20-11e5-972d-2c732aa381e7.png)

**Comment by aliusmiles** [comment]
I've totally missed this, thanks!
