### ISSUE TITLE
API call using Java always returns 401 Unauthorized

### ISSUE THREAD

**Issue by BaydushLC** [fguillot/kanboard#1421]
Any calls to API using Javaas in sample form web site fails.  Sample below run against demo site returns 401 Unauthorized.

        RestTemplate restTemplate = new RestTemplate();

        String url = "http://demo.kanboard.net/jsonrpc.php";
        String requestJson = "{\"jsonrpc\": \"2.0\", \"method\": \"getVersion\", \"id\": 1661138292}";
        String user = "demo";
        String apiToken = "demo123";

        // encode api token
        byte[] xApiAuthTokenBytes = String.join(":", user, apiToken).getBytes("utf-8");
        String xApiAuthToken = Base64.getEncoder().encodeToString(xApiAuthTokenBytes);

        // consume request
        HttpHeaders headers = new HttpHeaders();
        headers.add("X-API-Auth", xApiAuthToken);
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<String> entity = new HttpEntity<String>(requestJson, headers);
        try
        {
        	String answer = restTemplate.postForObject(url, entity, String.class);
        	System.out.println(answer);
        }
        catch( Exception e )
        {
        	System.out.println( e.getMessage() );
        }

**Comment by BaydushLC** [comment]
Discovered define('API_AUTHENTICATION_HEADER', ''); configuration not set.  Basic authentication was failing also.  Once 'API_AUTHENTICATION_HEADER' was set to 'X-API-Auth', the appropriate authentication worked.

**Comment by cduquev** [comment]
The basic authentication method only worked for me on localhost. In case of  Json-RPC Client/Server library in PHP we have to use this method instead:
 $authToken = base64_encode($_GET["username"].":".$_GET["pass"]);
 $client = new \JsonRPC\Client(http://mykanbanurl.com/jsonrpc.php,10,['X-API-Auth: '.$authToken]);

And of course setting API_AUTHENTICATION_HEADER to 'X-API-Auth'

**Comment by jfancsali** [comment]
I resolved my 401 error from the Java implementation by ..

replacing ...
headers.add("X-API-Auth", xApiAuthToken);

with ...
headers.add("Authorization", "Basic " + xApiAuthToken);
