### ISSUE TITLE
Bug in export Daily project summary

### ISSUE THREAD

**Issue by Kolesar** [fguillot/kanboard#1423]
Dear,

Please change first letter to lowercase in Export.php file
`https://github.com/fguillot/kanboard/blob/master/app/Controller/Export.php#L73`

from:
`$this->common('ProjectDailyColumnStats', 'getAggregatedMetrics', t('Summary'), 'summary', t('Daily project summary export'));`
to:
`$this->common('projectDailyColumnStats', 'getAggregatedMetrics', t('Summary'), 'summary', t('Daily project summary export'));`

**Comment by fguillot** [comment]
This bug is fixed in master. Thanks.
