### ISSUE TITLE
Question: Custom translations

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1424]
Hi,

I'd like to add a workplace-specific translation, to change the 'score' ("Complexity") to say "Samples" - each task might have a set number of (biological) samples associated with it, and for stats purposes I'd like to be able to draw a graph to say "N samples were processed in month M".

I've tried creating my own copy of a translation file (with just "language" and "complexity" specified) in a file "/app/Locale/en_GB/translations.php", but it doesn't seem to work and there's nothing in the docs to say how to do this ... would it be possible for a bit of help as to how I can do this?

Thanks,
Algy

**Comment by BlueTeck** [comment]
You could use this plugin, but I have to adjust the namespace, so that it it working for 1.0.20

https://github.com/BlueTeck/kanboard_plugin_overwrite_translation

**Comment by AlgyTaylor** [comment]
Thanks @BlueTeck  - you're a star :)
