### ISSUE TITLE
Bug: Date selector broken

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#1425]
On the new version of Kanboard (1.0.20), in Firefox & Chrome, I can't select start dates outside the current month - if I press the next month or previous month on start date (see screenshot) ,the dialog box disappears ...

![kanboard-selector](https://cloud.githubusercontent.com/assets/1220211/10787458/fc733eac-7d68-11e5-8ab9-ba62b904a1c6.png)

**Comment by BlueTeck** [comment]
see #1415

**Comment by fguillot** [comment]
This issue is now fixed in master.
