### ISSUE TITLE
Error 500 (empty page)

### ISSUE THREAD

**Issue by sanjayrup** [fguillot/kanboard#1427]
Hello,

I have try Kanboard and cannot have any home page, or login page or nothing !

I have try nightly, and normal zip. Normal zip return an error with require autoload.php, vendor folder is missing ? So i have download nightly build.

My config: 
- Debian 8.2
- Apache 2.4.10-10+deb8u3 (amd64) 
- PHP 7.0 RC5 (Dotdeb  7.0.0~rc5-1~dotdeb+8.1) WITH curl, gd, imap, sqlite, mysql, pspell, snmp.
- Mariadb 10.1.8+maria-1~jessie (amd64)

./kanboard command line report a lot of "Cannot adopt OID in NET-SNMP-EXTEND-MIB" 
Resolved by "apt-get install snmp-mibs-downloader".

I have try :
- Copy config.default.php  to config.php with define('DEBUG', true); (Error 500)
- Change MySQL config in config.php. (Kanboard is creating table than Error 500).
- Delete all table, import MySQL Shema .sql (Error 500).
- Go back with define('DB_DRIVER', 'sqlite');  (Error 500).

- config.php i have try

define('LDAP_AUTH', false);
define('GOOGLE_AUTH', false);
define('GITHUB_AUTH', false);
define('ENABLE_HSTS', false);
define('ENABLE_XFRAME', false);
define('ENABLE_SYSLOG', true); //try false too
define('ENABLE_URL_REWRITE', true);  //try false too

debug.log have only
[2015-10-27 20:29:34] [debug] START_REQUEST=/kanboard/
[2015-10-27 20:30:58] [debug] START_REQUEST=/kanboard/
...
[2015-10-27 21:37:16] [debug] START_REQUEST=/kanboard/

Apache error log is also empty.

Connexion to database is OK (Kanboard is creating 31 tables if i don't import schema)

I have try on index.php
error_reporting(E_ALL);
ini_set("display_errors", 'on');

Failed require autoload.php with normal zip, and Nightlybuild => Error 500

Try this two line also in app/common.php after and even before require config.

I have try to edit .htaccess too with Only : 
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]

Rewrite module in ON on Apache2.

I have try, on index.php

die("EOL"); before all => 200 with EOL
die("EOL"); before echo 'Internal Error: '.$e->getMessage(); => Error 500
die("EOL"); before  $container['router']->dispatch(...); => 200 with EOL
die("EOL"); AFTER  $container['router']->dispatch(...); => ERROR 500

Any idea ?

Thank you

**Comment by BlueTeck** [comment]
Failed require autoload.php with normal zip, and Nightlybuild => Error 500

-> try composer install

**Comment by sanjayrup** [comment]
vendor folder is not missing in Nightlybuild.

I have

rm -rf kanboard/
unzip kanboard-nightly-build.zip

i get : Internal Error: SQLSTATE[HY000] [14] unable to open database file (this is normal)
chmod -R 777 kanboard/data

Now /data/db.sqlite is create => Error 500
set debug to true => Error 500 nothing change

cp kanboard/config.default.php kanboard/config.php
data/debug.log is create with 
[2015-10-28 13:06:41] [debug] START_REQUEST=/kanboard/
But nothing has change => Error 500.

I will try normal zip with composer maybe, or normal zip, with nightlybuild vendor folder.

**Comment by sanjayrup** [comment]
Try to debug. 

Error 500 is beggin with :  app/Core/Router.php line 226.

If i comment 
//$instance->beforeAction($this->controller, $this->action);

Get a 200 with KB Page not found.

Replace with : die($this->controller ." && ".$this->action );

controller = app
action = index

I will see "beforeAction" and come back if i have some new

**Comment by sanjayrup** [comment]
So, in "beforeAction" 

/app/Controller/Base.php line 101.

Comment //$this->session->open($this->helper->url->dir()); into beforeAction function solve the 500.

Now i have login page, and debug.log is more verbose ! 

i will see WTF into "session->open" function and come back.

**Comment by sanjayrup** [comment]
OK. I have found what was the problem :

        // Enable strict mode
        if (version_compare(PHP_VERSION, '7.0.0') < 0) {
            //ini_set('session.use_strict_mode', '1');
        }

PHP_VERSION is 7.0.0RC5. 
Version_compare return -1

ini_set('session.use_strict_mode', '1');  make the Error 500.

**Comment by fguillot** [comment]
If `session.use_strict_mode` is causing an error, you should check your php/server configuration.
