### ISSUE TITLE
Cards are blocked and not allowed to drag on board

### ISSUE THREAD

**Issue by aquimi** [fguillot/kanboard#1429]
The cards are blocked to move more than 5 times to any lane.

My browser is Chrome and Firefox, in both there is the same problem

Please tell me if there is already a solution to this problem.

I am working on windows

**Comment by Chaosmeister** [comment]
:+1: 

I could reproduce this issue - not after exactly 5 times, but after dragging a task and then immediately clicking again to move the task, before the column/swimlane was able to register the task.

In this case, drag & drop will only drag texts, links or icons, or will select the text.
Clicking on a task still opens the taskview - just moving the tasks is disabled.

Reloading the page fixes this issue.

**Comment by aquimi** [comment]
Correct, but should not be so, my users do not like the idea of being refreshing the board when they block the cards

**Comment by Chaosmeister** [comment]
Also correct!
I just desrcibed the exact way to reproduce this issue.
The provided solution was only a workaround.
This definitely needs to be fixed.

**Comment by thomasweissgerber** [comment]
subscribing.

ive just ran into the same thing on chromium Version 45.0.2454.101 Ubuntu 14.04 (64-bit)

**Comment by facciocose** [comment]
Same problem here. We are using kanboard in a team with different browser and operating systems and the problem seems to be platform independent.

**Comment by lehrhardt** [comment]
experiencing the same issue with the latest version of kanboard.

**Comment by fguillot** [comment]
- Can you confirm that: when the issue is occurring the small loading icon at the bottom right still visible?
- Can you tell me how many tasks do you have on the board and which database driver you are using?
- Can you give the duration on the HTTP request (latency) that save the new task position on the board? (Open the Chrome developer console > tab Network > Filter by XHR then move a task and look at the column "time" for the http request that contains `...controller=board&action=save...`)

Thanks

**Comment by fguillot** [comment]
And can you also tell me if you have any integrations configured (smtp server, slack, etc..)

**Comment by facciocose** [comment]
I can confirm that this problem appears when you edit a task while the board is updating (loading icon).
I have slack integration configured.

![schermata 2015-11-19 alle 16 34 17](https://cloud.githubusercontent.com/assets/126668/11274934/8585eb62-8edb-11e5-92b0-bbc8d217f75a.png)

**Comment by fguillot** [comment]
Open a new issue if that happens again with the last Kanboard version.
