### ISSUE TITLE
Plugins Mattermost (personal clone of Slack)

### ISSUE THREAD

**Issue by miguipda** [fguillot/kanboard#1432]
Hi,

as I just saw that a Slack plugins exist, could somebody do a Mattermost plugins because I want to use a personal hosted Mattermost (better clone of slack) at work and will be interested to integrate those both solution as the perfect local hosted solution.
http://www.mattermost.org/features/

Sincerely thanks and have a nice day.

Miguipda ;-)

**Comment by fguillot** [comment]
I made a plugin for Mattermost here: https://github.com/kanboard/plugin-mattermost

It's the first release, it work only with the last version of Kanboard.
