### ISSUE TITLE
Migrating kanboard data to docker version of kanboard

### ISSUE THREAD

**Issue by heenameena** [fguillot/kanboard#1434]
Hi,

Currently we are using kanboard with sqlite database on ubuntu host, we have create several projects, tasks within the this tool. Now we want to use docker version of kanboard, however I want to copy database on to docker version of kanboard so that we can resume using all the projects and tasks that we created earlier.
Not sure how I can achieve this. Please advise. I appreciate your suggestions and instructions if you have any. Thank you.

**Comment by Chaosmeister** [comment]
Just copy the complete "data" folder to your new installation.
it's really as simple as that, since the data folder contains all information needed for your kanboard projects.
