### ISSUE TITLE
CONFIG SMTP Undefined class constant 'TYPE_EMAIL'

### ISSUE THREAD

**Issue by jclafuente** [fguillot/kanboard#1435]
Fatal error: Undefined class constant 'TYPE_EMAIL' in /home/jclafuente/public_html/kanboard/app/Controller/User.php on line 98

someone could help me with this inconvenite???

**Comment by netickfr** [comment]
Same problem here :(

**Comment by fguillot** [comment]
This is a regression in the last release, that need to be fixed.

**Comment by netickfr** [comment]
Thanks for your answer

**Comment by ordilibre** [comment]
If you can't wait, change the line 98 in the file kanboard/app/Controller/User.php.
Add the $ sign before TYPE_EMAIL

- original source :

$this->userNotificationType->saveSelectedTypes($user_id, array(NotificationType::TYPE_EMAIL));

- after :

$this->userNotificationType->saveSelectedTypes($user_id, array(NotificationType::$TYPE_EMAIL));

**Comment by netickfr** [comment]
Thank you ;)

-- 
Mickaël Canu
contact@netick.fr


Le 10 novembre 2015 à 23:01:31, ordilibre (notifications@github.com) a écrit:

If you can't wait, change the line 98 in the file kanboard/app/Controller/User.php.
Add the $ sign before TYPE_EMAIL

original source :
$this->userNotificationType->saveSelectedTypes($user_id, array(NotificationType::TYPE_EMAIL));

after :
$this->userNotificationType->saveSelectedTypes($user_id, array(NotificationType::$TYPE_EMAIL));

**Comment by fguillot** [comment]
This issue have been fixed in the master branch.

The fix is here: https://github.com/fguillot/kanboard/commit/2fc402f6733573627ad25394d109b9f848ef04f6

Note: the proposed fix by @ordilibre is wrong

Thanks to report that.
