### ISSUE TITLE
Missing "index.php" in URL causes error 500

### ISSUE THREAD

**Issue by rwimpers** [fguillot/kanboard#1437]
Hello!

I have a problem setting up kanboard:

I uploaded kanboard onto my webspace via ftp.
Before that I just changed the database driver to MySql and inserted the credentials.

When I call the site in my browser (www.domain.com/kanboard/index.php) the MySql database is created (I see several tables in mysqladmin), but then the browser shows an "Internal Server Error".

I noticed that URL looked like this:
http://www.domain.com/kanbboard/?controller=auth&action=login

When I change the URL to this...
http://www.domain.com/kanbboard/index.php?controller=auth&action=login
...I get the login page.

When I insert the credentials here, I get the "Internal Server Error" again.
And the URL looks like this:
http://www.domain.com/kanbboard/?controller=auth&action=check

It seems that the "index.php" is always missing. And I have no clue why.

Can anyone give me a hint where I could search for the problem?

This is what I know about the server:
- Apache (2.4.10)
- PHP (5.54)
- MySQL (5.6.19)

Kind regards
René

**Comment by Chaosmeister** [comment]
On our Webserver (IIS) we added index.php to the standard-documents.
So IIS knows to also try index.php when www.domain.com/kanboard is called.

Can you configure the standard-documents on your server?

**Comment by rwimpers** [comment]
Thanks for the reply.
My web hoster allows to set the default-documents in the ".htaccess" file:
I have to use this entry: DirectoryIndex index.php

When I replace the .htaccess file of the kanboard web with a file that only contains this line, it seems to work.

But the .htaccess file, which is included in kanboard by default, already has some content.
When I add the "DirectoryIndex" to the existing .htaccess file it doesn't work.

I assume that the default content is needed, so I am not sure, if it is wise to remove the existing lines.

**Comment by Chaosmeister** [comment]
I'm not very experienced with .htaccess files, but in this case it seems to enable some URL-rewriting and some safety for config files.

you could try to disable the URL rewriting in the .htaccess and see if this solves the problem.
also [Kanboard URL-rewriting](http://kanboard.net/documentation/nice-urls).

**Comment by rwimpers** [comment]
I am not sure what exactly I have to change in the default .htaccess file. 
Currently I keep the file with just the "DirectoryIndex".

Perhaps someone with more experience in .htaccess files can post some further information.

Nevertheless, thanks, Chaosmeister, your hint helped me to get a big step further.

**Comment by fguillot** [comment]
If you have access to Apache error logs, check there to see the exact error message. Otherwise, you have to proceed by elimination to find what is wrong. Try to remove the .htaccess, if it works put it back and find the instructions in the .htaccess that cause the issue.
