### ISSUE TITLE
Is there any chance to get rid of the top notification?

### ISSUE THREAD

**Issue by antiphasis** [fguillot/kanboard#1439]
It causes the whole website to jump around - and that is, especially when setting up kanboard or adding users or configure projects - quite annoying. Or working with the time sheet - adding time slots for the weekly schedule.

**Comment by shimza** [comment]
I agree. It makes more sense to use the accepted modern practice of an
overlay that uses the same timings, instead of pushing it all down.

**Comment by fguillot** [comment]
I merged a pull-request that place the notification at the bottom of page.
