### ISSUE TITLE
Wrong values in "lead and cycle time" reports after shutdown of the server during the weekend

### ISSUE THREAD

**Issue by mrfyx** [fguillot/kanboard#1444]
After a shutdown of the kanboard server during a weekend, the report shows negative values.

See attach screenshot
![clipboard 1](https://cloud.githubusercontent.com/assets/7872032/10886856/664b20e6-8184-11e5-80fd-cc364c5d403d.png)

**Comment by fguillot** [comment]
The values shown by the chart are calculated daily by the cronjob or when you move a task. So, if you have stopped the server no calculation have been made.

However, that should not show negative value, need to be fixed.

**Comment by fguillot** [comment]
The negative values are now fixed in master.
