### ISSUE TITLE
Unable to select more than one Project to receive notifications from

### ISSUE THREAD

**Issue by sbanks15** [fguillot/kanboard#1453]
Under any users account, we are unable to select more than one project under the title:
"I want to receive notifications only for those projects:"

There are 3 Projects available I can tick all 3 and choose save, but only the last Project will be ticked when the page reloads. 

If I only select one and choose save, that one will stay active. So its only on Multiple selections that the problem exists.  

Is this a known bug or something new/specific to us?

**Comment by sed-sytarchuk** [comment]
We are having this issues as well in Kanboard version 1.0.20

**Comment by fguillot** [comment]
The selection of projects will be saved only if the checkbox "Enable notifications" is selected at the top, is it the case?

**Comment by sed-sytarchuk** [comment]
Yes, I do have the "Enable Notifications" checkbox enabled.

When I select project A and then project B and click save, only project B gets saved.

When I select project B and then project A and click save, only project B gets saved.

**Comment by sbanks15** [comment]
Yes, As do we. "Enable Notifications" checkbox is enabled. 

We have 3 Projects, ProjA Proj B and ProjC

If you select all 3, ProjC is selected, 
If you select ProjA and ProjB, ProjB is selected. 
IF you select ProjA and ProjC, ProjC is selected. 
If you only select one Project then that Project remains selected. 

We would like to receive notifications from all Projects if possible.

**Comment by fguillot** [comment]
This issue should be fixed in 1.0.27.
