### ISSUE TITLE
Fatal error: Class 'Kanboard\ServiceProvider\LoggingProvider' not found

### ISSUE THREAD

**Issue by teknopol** [fguillot/kanboard#1455]
Hi, 

I tried to install the 1.20 version with zip package.
I got this error:

Fatal error: Class 'Kanboard\ServiceProvider\LoggingProvider' not found in /MYSERVERLOCATION/app/common.php on line 26

How to fix this issue?

Thanks

**Comment by fguillot** [comment]
Check if Kanboard is installed correctly, some files are probably missing.
