### ISSUE TITLE
Calendar locale do not respect application locale

### ISSUE THREAD

**Issue by honda2** [fguillot/kanboard#1458]
I have tried to set some locales other than english, but calendar seems to not respect this. for example cs_CZ locale sets calendar to chinese. It appears that fullcalendar plufin used for this is fed by wrong locale javascript file.

**Comment by fguillot** [comment]
This a bug in KB, there is no translation available for cs_CZ in full calendar, so that should fallback to english and not show chinese.

**Comment by honda2** [comment]
Hello, there is one in source, as I could find it in js/vendor/lang/cs.js (https://github.com/fguillot/kanboard/blob/master/assets/js/vendor/lang/cs.js) and in fullcalendar repository (https://github.com/fullcalendar/fullcalendar/tree/master/lang)

**Comment by fguillot** [comment]
I fixed this issue in master. The fix is here: https://github.com/fguillot/kanboard/commit/bf2cf457c34c363918cbd55ae33ccf3f736c9244
