### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by polom** [fguillot/kanboard#1461]
Hi,

I was hoping to get a more responsive layout. As I've found, I could modify the stylesheet but the board view is structured with a big table containing all columns. I was wondering if we could not remove table and add CSS to keep columns side by side in a "desktop" view but on top of each other on a mobile for example.
I could not find other related issue or signs that someone else is working on it.

**Comment by fguillot** [comment]
Even if the board is using table html tags, you should be able to scroll horizontally. The current layout is not really adapted for smartphone, developing a native app will be probably better...

But if you would like to work on that, you can create a plugin (or a pull-request if that doesn't involve any breaking changes) and override the default layout.
