### ISSUE TITLE
Notification Mail : undefined variable

### ISSUE THREAD

**Issue by TabDambrine** [fguillot/kanboard#1462]
Hi,
I searched a bit about the subject but didn't find anything.

Since I upgraded kanboard to 1.0.20 I receive erros in notification mails :

Notice: Undefined variable: changes in path\app\Template\notification\task_update.php on line 3 

I'm not sure whether it's a bug inside 1.0.20 of kanboard or if I missed something during the upgrade.

Thanks.

**Comment by TabDambrine** [comment]
Hi there,

I have foud out that this mail is sent when the description of the task is modified. I then receive 2 mails :  first one is the error mail and the second one is the mail with the description change.

I will try from a fresh install of 1.0.20 to see if it's due to this version or if it comes from the migration i made.

**Comment by BlueTeck** [comment]
1.0.21 is out, with some bugfixes

**Comment by TabDambrine** [comment]
Yeap i planned to make the migration soon so i'll see if this issue is fixed. The thing is that i'm not even sure it's an kanboard issue, looks like i'm the only one affected so it might be my install that is broken.

I'll keep you up about this subject.

**Comment by fguillot** [comment]
Closing this ticket, reopen if necessary.

**Comment by TabDambrine** [comment]
Hi,

I installed the 1.0.22 version of kanboard (from the stable zip), I then copied the data directory (as well as config.php and web.config for IIS to work well) into it.

My problem is still there, every time a description is modified inside a task, two mails are sent with same object and one of them has the following error message :

Notice: Undefined variable: changes in path_to_kanboard\app\Template\notification\task_update.php on line 3

The second has the correct description change with the new text in it.

I'm using sqlite db on windows server does one of these two things can have such an impact ?

**Comment by TabDambrine** [comment]
Hi, a few updates : 
we did a migration into a mysql database (not without some troubles to keep all the data correct from the sqlite file).

The problem is still there : if a user modifes a task description then 2 notifications are saved, one without "changes" and one with "changes". 2 mails are still sent one of them containing the error message.

Is it normal that a description change insert 2 rows in project_activities with event_name = task.update ? what kind of information can i provide to help with this ?

**Comment by fguillot** [comment]
Do you have any automatic actions configured in your project? if yes, which one?

**Comment by TabDambrine** [comment]
Oops I edited the wrong comment : 

Yes, i have automatic actions : "Assign a color based on a category", it's the only one used but for 6 different color/category.


I posted this but not on the last comment (my bad):
"Update : I figured out it only concerns projects with automatic actions, the only one we use is the action that "assing a color based on a category", hope this will help."

**Comment by fguillot** [comment]
I'm not able to reproduce the issue with this scenario:

1. Configure a user with email notifications
2. Create a new project
3. Create some categories
4. Add automatic actions "Assign a color based on a category"
5. Create new tasks
6. Change the category
7. Watch the log files and emails but no errors visible

**Comment by TabDambrine** [comment]
Once the category is set i am able to trigger the mail by for example editing the description.

My usual scenario is :

1. to 6. like yours
7. change description
8. two mails are sent one with the error.

**Comment by TabDambrine** [comment]
This issue is not present anymore in 1.0.24 it might be related to the fix concerning color automatic actions.

Thanks.
