### ISSUE TITLE
scrollers

### ISSUE THREAD

**Issue by brontosaurusrex** [fguillot/kanboard#1463]
Browser scrollers are active on an empty board, i'd call that a visual bug (osx firefox and safari).

**Comment by fguillot** [comment]
I'm using OS X with Safari/Chrome/Firefox and I don't see any scrollbar, can you make a screenshot?

**Comment by brontosaurusrex** [comment]
sure:
http://shrani.si/f/1B/fS/1tR6Xto6/1/kanboard.png

**Comment by darkocobe** [comment]
I have same issues but with IE only. I can't collapse swimlines and scroll-bar are shown even if not needed. But everything works on Firefox or Chrome.

**Comment by fguillot** [comment]
This issue is now fixed in the development version.

Thanks.
