### ISSUE TITLE
Production app 1.17 to 1.20

### ISSUE THREAD

**Issue by diegoseso** [fguillot/kanboard#1466]
Hi, first of all I want to thank you fguillot and all of the contributors for the great work, I am working in a company that has a production set of kanboard on its 1.17 version, we are willing to work with plugins and start contributing too so we feel the need to upgrade to 1.20, btw we are using mysql setup, how could we manage the upgrade since I see there are changes in mysql database on versions, Is it safe to do it? , I have read the documentation but I feel that could be more involved than what it says.

**Comment by Chaosmeister** [comment]
Hey,

Our company started with Kanboard 1.15, also with mysql, and continually updated the kanboard installation with every update without any problems.

You could simply test if it works by copying the "data" directory to the newly extracted kanboard installation. I'd suggest keeping a safe copy of your complete production kanboard folder to be able to restore it if any issues occur.

however all user-data is stored in the "data" directory and should be interchangable between different versions.

We delete that backup with every new successful installation :+1:

**Comment by fguillot** [comment]
- Kanboard will run database migrations automatically for you when you update from one version to another one.
- Always do backup of your data folder and your database before.
- Always read the ChangeLog file to check for breaking changes to may apply to you (https://github.com/fguillot/kanboard/blob/master/ChangeLog)
