### ISSUE TITLE
Features and future vision of this tool

### ISSUE THREAD

**Issue by JMetai** [fguillot/kanboard#1468]
Hi Frederick,

We are currently using your tool, and we would like to add additional features to this tool and planning to contribute back to the project. I'd like to discuss what features we are planning to add and how our enhancements/features fit with your future vision of your tool. Please let me know how I can reach out to you to discuss further.

Thanks,
Janga

**Comment by fguillot** [comment]
You can simply describe publicly what you would like to do here, especially if you are planning to contribute back to the project.

**Comment by JMetai** [comment]
Please let me know if any of them already available or someone working on or doesn't fit with future vision of your tool. Thank you and appreciated for giving back such a great tool to the community.

Here are the list of features that we would like to add to the Kanboard and contribute back to the project:

1. Link project cards (tasks) between boards and on the same board
2. Provide an email notification for the assignee of a card if they are not also the creator of the card
3. Provide an email notification to a user and the command center lead when an item is overdue
4. Sort cards in date order or priority order
5. Have ability to collaborate on other applications (example – MS Excel)
6. Support business day logic for items. Most of our items are due on Business Day “X” of the month
    Calendar to show all items due on a given day, and provide gantt chart of tasks (project cards) till      
    due date
7. Provide a view for customers to view work in progress and completed tasks on boards (read only  
    access)
8. Provide a “Delivered” date in addition to a due date. Delivered date should reflect when an item   
    moved into the Done column
9. Provide automatic coloring suggestions based on the category assigned. E.g., if an item is 
    assigned to Sales category, color it green by default
10.Put Recurring date logic, start date on the initial card “edit” view. This will allow us to create 
     recurring work, and manage it more efficiently
11.Reporting - Show dashboard views and other reports. Support 4 quadrant (Economics, Talent 
     etc.) view

**Comment by fguillot** [comment]
Sorry to answer so lately,

- 1) 2) 6) and 9) are already available if I understand correctly
- 7) In the next release a new role "Project Viewer" have been introduced to have read-only access to projects
- 8) Can be added in master easily
- The rest can probably be added with plugins
