### ISSUE TITLE
Issue with category selection

### ISSUE THREAD

**Issue by jniggemann** [fguillot/kanboard#1469]
I just updated from 1.0.18 to 1.0.20 and am seeing something which may be intentional or an error.
I can reproduce this as follows:
* Select a board - the search bar reads `status:open`
* Select a category 'catA' using the dropdown - the search bar reads `status:open category:"catA"`
* Select a category 'catB' using the dropdown - the search bar reads `status:open category:"catA"  category:"catB"`  
The second category is now **added** to the selection instead of **replacing** it.

IMHO the selected category should replace the previous one. Being able to configure this would, of course, also be OK...

**Comment by jniggemann** [comment]
Hmm, considering commit 58c74b80d2c9b8d51df91a7287a22e5d3f99391c this is an intentional change. Can you please make this configurable somehow?

**Comment by jniggemann** [comment]
IMHO it's helpful to explain my usecase:
I'm using KB as a personal kanboard using a single board for work-related tasks as well as private ones and some hobby stuff. I separate these tasks using categories like 'work', 'private', 'hobby' and so on.

When at work, I filter for the category 'work' and start working on the items.
The thing is, I can work from home and vice versa. When I already filtered for 'work' and then apply a filter the category 'private', I want only private tasks to be visible so I can decide what to do next.
I guess one could say that I'm using the categories in a GTD "context" way...

**Comment by lrrb** [comment]
In Kanboard 1.0.20, you can create your own filters (menu Actions => Custom filters). With this option, you can recreate filters by category with the previous behavior.

**Comment by jniggemann** [comment]
Thank you, that helps.

For the time being, I'll use a local patch I created that reverts to the old behaviour... Should that patch stop working, I'll use the custom filters instead.

**Comment by BlueTeck** [comment]
see https://github.com/fguillot/kanboard/issues/1438#issuecomment-152773062

**Comment by jniggemann** [comment]
Yeah, that kinda works, but it overwrites the initial "status:open", leading to the display of all closed items.
I also miss the "all categories" filter, but at least I can recreate it using the custom filters.
