### ISSUE TITLE
duplicate key value violates unique constraint "project_daily_column_stats_idx"

### ISSUE THREAD

**Issue by nlevchuk** [fguillot/kanboard#1474]
Hi guys!

I have found one error related with the project in my postgresql log. I don't know why this happened but you can try to reproduce this error during test the project locally.

```
< 2015-11-09 09:53:24.972 CET >ERROR:  duplicate key value violates unique constraint "project_daily_column_stats_idx"
< 2015-11-09 09:53:24.972 CET >DETAIL:  Key (day, project_id, column_id)=(2015-11-09, 1, 1) already exists.
< 2015-11-09 09:53:24.972 CET >STATEMENT:  INSERT INTO "project_daily_summaries" ("day", "project_id", "column_id", "total", "score") VALUES ($1, $2, $3, $4, $5)
```

**Comment by fguillot** [comment]
This message was coming from a workaround for "INSERT ON DUPLICATE KEY UPDATE...". It's now fixed in the development branch and the error message won't appear anymore in postgres logs.

Thanks.

**Comment by nlevchuk** [comment]
@fguillot thanks. Could you show me corrected code or commit?

**Comment by fguillot** [comment]
https://github.com/fguillot/kanboard/commit/0a7370b9e5652918ad9386baa81cc12627069755

btw I will publish a new stable release today with many bug fixes.

**Comment by nlevchuk** [comment]
@fguillot im glad to hear it. thanks a lot
