### ISSUE TITLE
SplFileObject::fputcsv() seulement en PHP 5.4

### ISSUE THREAD

**Issue by JulienRollais** [fguillot/kanboard#1475]
Bonjour,
En PHP 5.3.3
en exportant les tâches d'un projet, il se produit cette erreur
PHP Fatal error:  Call to undefined method SplFileObject::fputcsv() in /php/kanboard/app/Core/Csv.php on line 170,

Le SplFileObject::fputcsv() est compatible seulement 5.4. Dans votre http://kanboard.net/documentation/installation, il faudrait enlever la compatibilité 5.3.3

A moins que vous ayez un moyen de contournement ?

**Comment by fguillot** [comment]
C'est maintenant corrigé dans la branche master, l'export est de nouveau compatible avec PHP 5.3.

Merci d'avoir rapporté le problème.
