### ISSUE TITLE
Hook for template:project:filters needed

### ISSUE THREAD

**Issue by middeke** [fguillot/kanboard#1478]
Hi Frédéric,

I want to add some functionality in the filter-bar.
Could you please add a hook?
Something like:
```
<?= $this->hook->render('template:project:filters', array('project' => $project)) ?>
```
in line 100 in app/Template/projects/filters.php

or even something to edit the whole filter?

THX!!

**Comment by BlueTeck** [comment]
Other topic regarding filters and plugins #1411

**Comment by fguillot** [comment]
I added 2 new template hooks: https://github.com/fguillot/kanboard/commit/9deeaa4ef1e74531f5f7d99c5de423303ddda7ed

- `template:project:header:before`
- `template:project:header:after`

Let me know if you need new hooks, thanks.

**Comment by middeke** [comment]
Great, THX!!
