### ISSUE TITLE
File downloads from a task does not work

### ISSUE THREAD

**Issue by xavividal** [fguillot/kanboard#1482]
The downloaded files always ends with .html extension.

Uploaded file:
test.pdf

Downloaded file:
test.pdf.html

**Comment by fguillot** [comment]
Can you describe your environment to try to understand where the problem come from? (browser/os and server). Thanks

**Comment by xavividal** [comment]
Sorry for the missing info.

Apache 2.4 + PHP 5.6.15 + Safari (El Capitan OS X 10.11.1)

**Comment by fguillot** [comment]
I have the same configuration on my laptop and I can reproduce the issue with Safari.

The problem come from Safari, I need to investigate to understand why the browser append ".html" at the end.

**Comment by fguillot** [comment]
I pushed a fix in master and now it's working with Safari.

Thanks to report this bug.
