### ISSUE TITLE
Unable to select time in drop-down of Start date of task

### ISSUE THREAD

**Issue by golharam** [fguillot/kanboard#1483]
Version 1.0.20
When viewing a task and trying to set the Start Date/Time, I can drop down and view the calendar, but when I try to select an hour from the hour time dropdown list, the calendar collapses.  I think its because the calendar loses focus and closes, not realizing it should stay open because the focus went to the hour dropdown list box.

**Comment by fguillot** [comment]
Yes, this bug have been fixed in the development branch. A new release will be published soon with bug fixes.
