### ISSUE TITLE
Problems logging in via. Gitlab

### ISSUE THREAD

**Issue by dalenoe** [fguillot/kanboard#1485]
I receive the following error: It loads gitlab, then I get this error..

The redirect URI included is not valid.

I have tried with enable_url_rewrite as both true and false and the result is the same. It's apache with mod_rewrite enabled.

**Comment by dalenoe** [comment]
With mod_rewrite set to true, I get 404's. So I think it's either mod_rewrite, or the .htaccess

**Comment by dalenoe** [comment]
Ok. Part of the problem was I didn't have allowoverride all set in the apache/virtual host configuration.

**Comment by dalenoe** [comment]
@fguillot Is there any way to import everything I have going on already in gitlab. Projects, Issues/Tasks, Comments..

**Comment by fguillot** [comment]
There is no tool to import everything from Gitlab to Kanboard. At the moment, there is only a web hook integration. But you can probably write a script that use the API of Gitlab.

**Comment by dalenoe** [comment]
Dang, would be so nice to pull data in from a existing gitlab instance. I am still having problems with gitlab login. I get External authentication failed.

**Comment by dalenoe** [comment]
@fguillot After the integration and webhooks are setup. Whenever a comment is added on the board, it doesn't show up within gitlab? Isn't it supposed to send the comment using a webhook?

**Comment by peripatetic-sojourner** [comment]
@dalenoe I just got the External Auth piece working for GitLab. Unfortunately, it doesn't work as described. I had to create the remote user first, with the GitLab id linking users so the lookup would work. It seems that there is a problem somewhere that is preventing the user from being created in Kanboard. I haven't had time to isolate the problem.

**Comment by peripatetic-sojourner** [comment]
@dalenoe  Okay, so I took a look at the source and reread the docs, and it was a misunderstanding on my part. Gitlab auth is on a strictly per user basis. It is up the the user or admin to link their account. It does not create accounts. Did you link the account?
