### ISSUE TITLE
Dropdown menu links are only clickable on the caption

### ISSUE THREAD

**Issue by PBrn46** [fguillot/kanboard#1487]
When mouse-over on the drop-down menu items they do highlight, but when clicking on them the menu is dismissed with no action, when clicking anywhere but on the text. The link seems to be only on the text rather than the entire menu item. This is repeatable in both Chrome and FireFox using v1.0.20.

**Comment by sparkles645** [comment]
Related / same observation as #1381

**Comment by fguillot** [comment]
This feature is now implemented in the master branch.

Thanks.
