### ISSUE TITLE
Bad username or password

### ISSUE THREAD

**Issue by heenameena** [fguillot/kanboard#1488]
I am getting bad username or password error. I am using docker image kanboard/kanboad:stable version and copied over my db.sqlite file to the docker host and created the container with -v flag with folder location where I copied my db.sqlite file.
When I try to login I get this error. Please advise.
I am not using any LDAP or external authentications.

Docker host is RHEL 7.x and let me know if you need any more details.

Thanks!

**Comment by mrfyx** [comment]
Same problem here, one of the user stay block on login page with catpcha but picture doesn't appear.
I try to change the password as admin but it seems to doesn't work.
To solve the problem, I edit the database, reset the password and the "loginfailed" counter.

version : 1.0.21

**Comment by Vanco** [comment]
I have the same captcha problem, and finally google and fixed by install the php-gd module.  
```
yum install php-gd
```

**Comment by fguillot** [comment]
@heenameena Did you check if your volume is correctly mounted in your container?
