### ISSUE TITLE
Multi project board

### ISSUE THREAD

**Issue by livier** [fguillot/kanboard#1490]
Excuse my english if it not so good
I discover Kanban, thamks to framaboard.org.
For anyone with a Attention Deficit Disorder (ADD) as me, it may help ;-)
Boards are very fine, but I can only see a board about each project.
I would like to have an overview off all my tasks in this kind of board.
Or, more specifically, all tasks in specifics states (all "work in progress" in all projets) . An ADD may have too much and forget half of them, if there is no way to check what are they.
I undertand each projet may have differents types off states (I use it). Then it would be fine to have, in the "my projects" table a way to select witch columns off witch projet we should visalize in the ad-hoc Board should be generated.
Am I clear ? Thanks for goog job ;-)

**Comment by mrfyx** [comment]
On the home page, you can filter task assignee to you. You will see all tasks of all projects.
Then you can add more filter, for example column:"Work in progress".
However, there is not board view only the tasks list.

You can also use kanboard in another way. Create only one project and use swimlanes to split your tasks in different projects on the same board.

**Comment by tornade69** [comment]
Hi,
I use this tip, but how can i save it in filter drop down. A this time i use URL bookmark. 
Great software.

**Comment by fguillot** [comment]
Closing duplicate.
