### ISSUE TITLE
Bring the task reference field to the frontend.

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1491]
On some days our team creates more kanboard tasks as we can work on.  
This leaves us with a lot of tasks and the overview gets lost more and more.

The filter and searchbar already help a lot, but some kind of __tag__ would even increase the productivity.

How we work with kanboard: _(possibly unimportant)_
- We use swimlanes for our products (desktop / web-version / documentation etc)
- We use columns for the progress (new / in progress / finished / etc) - simplified
- We use categories for a rough classification (bug / feature request / etc)

It would be nice to be able to add searchable texts / tags to each task, so we would not have to overload our Descriptions/Titles.

for example:  
- customer names
- external supplier issue-ids
- inhouse tags to find similar tasks

The reference might be what we are looking for:  
- It's already integrated in the search
- It would be able to store the tags we need

Reference #1223

Best regards!
Tomas

**Comment by BlueTeck** [comment]
You could write your own plugin and use the  [metadata feature](https://github.com/fguillot/kanboard/commit/9283fb88d80cb355ff98364a9a57b657fc511d98)

You could also take a look at https://github.com/fguillot/kanboard/issues/646 or https://github.com/fguillot/kanboard/issues/1411#issuecomment-158904040

**Comment by Chaosmeister** [comment]
Thanks!
I will try the plugin path.
