### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1498]
I'm currently working through the documentation to create a plugin.

In http://kanboard.net/documentation/plugin-registration the examplecode below 
#### Plugin Registration File
displays
`class Plugin extends Plugin\Base`
but should be
`class Plugin extends Base`

otherwise the browser displays
>Fatal error: Class 'Kanboard\Plugin\ShowRef\Plugin\Base' not found in G:\dev\Apache\htdocs\kanboard\plugins\ShowRef\Plugin.php on line 8

-------------------------

Then later on that site there is a spelling error:

>Your plugin registration class also inherit from Kanboard\Core\Base, that means you can access to all classes and methods of Kanboard easily.

I think should be:
>Your plugin registration class can also inherit from Kanboard\Core\Base, that way you can access all classes and methods of Kanboard easily.

**Comment by fguillot** [comment]
The documentation have been updated in the development branch. Thanks.
