### ISSUE TITLE
Feature request : allow user registration on a project

### ISSUE THREAD

**Issue by pyg77** [fguillot/kanboard#1503]
It would be great to have an option "this project allow registration" with:
  1. a form to request an account (user / name / email / pass)
  2. an email sent to the project admin (defaulted to kanboard admin)
  3. an interface for the admin to see wich member apply (and when) and to grant them access (Project users management page already do the job, I think)

It would be usefull in case you have a high number of local users for a same project and to avoid project admin to create them one by one.

**Comment by pyg77** [comment]
Another solution would be the possibility to mass-add user by importing a list of email addresses (sending them to a unique link to create an account).

**Comment by fguillot** [comment]
Duplicate with #570
