### ISSUE TITLE
Expanding Column Widths 

### ISSUE THREAD

**Issue by mhagemann01** [fguillot/kanboard#1504]
We are checking out KB Dashboard and I was wondering if someone could tell me how to expand the column widths.  The default is too small, I'd like to see more of the project name but it's getting cut off.  We have plenty of real estate to work with.

thanks,

**Comment by wozsoft** [comment]
The short answer is that you can't change the width of the 'projects' column on your dashboard through a user setting.

It is set by a .css class called ".column-25" which means that it takes up 25% of the available width on the table. Adjust your window size and you can see what happens to all of the columns as you make it wider or narrower.

There is a quick and dirty way to change it for your own installation, but there are consequences.

Consider a Plugin or some custom Javascript to provide a drag to widen function.
