### ISSUE TITLE
LDAP/AD Authentication using the Root DN is Failing

### ISSUE THREAD

**Issue by darkocobe** [fguillot/kanboard#1509]
Hi,

We are using AD/LDAP for authentication to the application and we have one problem. We were testing the application with one specific OU it worked, but now we want to include every user to authenticate. Our users are in several OUs in the root of the domain. Including every OU I think is not supported because I can't make it working, but also putting the Root DN is not working. 

Our config:
define('LDAP_ACCOUNT_BASE', 'OU=EMEA,DC=domain,DC=local');
define('LDAP_USER_PATTERN', '(&(objectClass=user)(sAMAccountName=%s))');

Doesn't work (no one can authenticate):
define('LDAP_ACCOUNT_BASE', 'DC=domain,DC=local');
define('LDAP_USER_PATTERN', '(&(objectClass=user)(sAMAccountName=%s))');

Our users are in multiple OUs in the root EMEA, APAC ...

Regards,
Darko

**Comment by fguillot** [comment]
You should test again with the latest stable version, a lot of changes have been made for LDAP authentication. I have tested with users located in different OU and configuring the Root DN in KB, it's working fine for me. My test Active Directory server is configured with the default settings.
