### ISSUE TITLE
activity long length?

### ISSUE THREAD

**Issue by Povezi** [fguillot/kanboard#1510]
Is it possible to configure longer activity logs (for project)? Now we sometimes see only last few hours... :8ball:

**Comment by sparkles645** [comment]
@Povezi -> you can change what shows up at the main board activity list by editing /app/Controller/app.php

We keep it at 200.

![2015-12-01_20-36-07](https://cloud.githubusercontent.com/assets/10092252/11511811/6280981c-986b-11e5-8a96-a4ef92d844cf.jpg)

**Comment by Povezi** [comment]
Sparkles, you are the best! :+1: 
I have found it here: 
/app/Controller/Activity.php
changed this: 
'events' => $this->projectActivity->getProject($project['id']),
to:
'events' => $this->projectActivity->getProject($project['id'], 250),

**Comment by sparkles645** [comment]
:thumbsup:
