### ISSUE TITLE
Upgrading from  V1.0.16 fails

### ISSUE THREAD

**Issue by JUPohl** [fguillot/kanboard#1512]
I'm running  1.0.16 under Apache Tomcat 7. I tried to upgrade to the latest Kanboard version but it failed. I always got a "resource not available" for any newer version. I don't see any error messages in the logs. Any important thing that has been changed I missed so far? Is there any debug or log mode available?

**Comment by BlueTeck** [comment]
Which Version do you want to install? Github or one from Kanboard.net?

**Comment by JUPohl** [comment]
Kanboard.net

**Comment by fguillot** [comment]
Check the error logs of your web server and the Kanboard's ChangeLog.
