### ISSUE TITLE
Inconsistent ldap filters

### ISSUE THREAD

**Issue by elacour** [fguillot/kanboard#1513]
(tested on OpenLDAP)
If we set for example:

define('LDAP_USER_PATTERN', '(&(uid=%s)(eneAllowedServices=kanboard))');

auth works fine, but user search by email (through API) doesn't works because Auth::Ldap->getLookupQuery add extra parenthesis and produce:

(&((&(uid=%s)(eneAllowedServices=kanboard)))(mail=....))

which is an invalid filter.

if we remove extra parenthesis in config file, then auth does not works because "&(uid=%s)(eneAllowedServices=kanboard)" is an invalid filter.

I think the best would be to force users to enter a valid filter in config file, then in Auth::Ldap->getLookupQuery add parenthesis only if needed.

**Comment by fguillot** [comment]
This piece of code have been removed from the current development branch. The next stable version will use only what you have specified.

**Comment by fguillot** [comment]
Closing this ticket because it's not relevant anymore with the last stable version.
