### ISSUE TITLE
The Board Page will disappear.

### ISSUE THREAD

**Issue by biganter** [fguillot/kanboard#1516]
System Environment:
Kanboard 1.0.21 + Nginx 1.80 

Installation is OK, i can config the project and user. 
But I find a issues  that is when i click to the "Board" page. The page will show in 10 seconds, and then it will be blank. use the debug tool , the html as follow: 
'<'html'>'
'<'head'>'...'<'/head'>'
'<'body'>'
'<'header'>'...'<'/header'>'  
'<'section class='page''>'
  '<'section id="main"'>'...'<'/section'>'
'<'/section'>'
'<'div role="log"'>''<'/div'>'
'<'img/'>'
'<'/body'>'
'<'/html'>'

 " This is blank and have no more div , no error  in log file "

**Comment by biganter** [comment]
I  Change the "check-url" to "reload-url" in  app.js , can fix it .

reload_url
http://127.0.0.1:9100/?controller=board&action=show&project_id=1&search=status

check_url
http://127.0.0.1:9100/?controller=board&action=check&project_id=1&timestamp=1449125527&_=1449125527137

**Comment by johnleta** [comment]
Can you be more specific?  I could not find the any part of the links above in the app.js file.
