### ISSUE TITLE
2FA page should warn if you try to save already enabled settings

### ISSUE THREAD

**Issue by bjauy** [fguillot/kanboard#1520]
I've been trying to enable 2FA:
1. Enable 2FA & save settings
2. Check if code is correctly verified
3. Save settings again

After few failed attempts I have realised that step 3 wasn't necessary and that each time it generated new secret. 

In my opinion it would be better to either disable saving settings again if state of checkbox hasn't changed, change button's caption when 2FA is enabled (to something like "generate new secret") or at least add sort of warning for users trying to save 2FA.

**Comment by bjauy** [comment]
Also, wouldn't it be better to be able to enable 2FA only after test code has been verified correctly?

**Comment by fguillot** [comment]
In the development branch, the 2FA configuration page have been improved, it's enabled only if the code has been verified correctly.

Thanks.
