### ISSUE TITLE
Class '\Kanboard\Auth\Database' not found

### ISSUE THREAD

**Issue by bjauy** [fguillot/kanboard#1521]
I have updated local installation to 91bdf6aa When trying to login I receive:

```Fatal error: Class '\Kanboard\Auth\Database' not found in /srv/http/kanboard/app/Model/Authentication.php on line 29 ```

**Comment by waja** [comment]
Did you update your assets with composer?

**Comment by waja** [comment]
See http://kanboard.net/documentation/installation

**Comment by bjauy** [comment]
I guess http://kanboard.net/documentation/update would be more relevant in this case. 

If updating assets means using ```composer install``` after pulling from this repo then yes, I've updated dependencies of kanboard.

**Comment by bjauy** [comment]
Missing class has been removed in aforementioned commit (91bdf6a), is this to be expected as part of greater changes or accidental removal?

**Comment by waja** [comment]
I would recommend to use release tags for productional use. :-)

**Comment by bjauy** [comment]
This time it was sufficient to checkout previous commit :) Fortunately, I'm not using this version as production.

I'll leave this issue open because I'm not sure if the class was expected to be removed. If it was, feel free to close.

**Comment by vpadhariya** [comment]
I just installed, using mysql and got the same error. waiting for the fixes.

**Comment by fguillot** [comment]
If you are using the master branch, you can update, a huge refactoring have been made...
