### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by JMetai** [fguillot/kanboard#1524]
I have a user with standard user role, user tried many times with incorrect password and later I reset his password still he is not able to login with new password, he is getting bad user or password error and captcha. I removed the user and re-added him (ofcourse all associated tasks were removed) to fix the login issue.

Is there a better way to fix such kind of login issue?

Thanks for your help.

**Comment by fguillot** [comment]
As described here http://kanboard.net/documentation/bruteforce-protection, after 6 failures the account is locked down for a period of 15 minutes, you just need to wait.

At the moment there is no user interface to reset the failed login counter but that can be done manually in the database.

**Comment by n0va1s** [comment]
A user after 6 attempts is blocking access and is not releasing after 15 minutes. What to do? I need to set up some task in crontab? Something like ./kanboard -XXX unlock.

The current solution is to delete the user and grant all access again. But it loses all tasks already allocated.
