### ISSUE TITLE
Master: MySQL DB schema not updated on MariaDB 10

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#1526]
### Env

* FreeBSD 9
* MariaDB 10
* PHP 5.6

### Description

The MySQL schema is not properly updated when updating Kanboard via `git pull`
A custom script re-using Kanboard methods does update the schema, so it's not a permission issue.

### Old description

Just pulled in the latest changes, restarted PHP and I get this message when loading Kanboard:

> Internal Error: Identifier "acl" is not defined.

I'm using 2FA.

**Comment by oparoz** [comment]
I'm also using plugins, so it may be that those have not been updated yet to support the new ACL feature.

**Comment by fguillot** [comment]
Plugins are not yet updated.

**Comment by oparoz** [comment]
:+1: Thanks for letting me know :)

**Comment by fguillot** [comment]
Should work now with the master branch of plugins.

**Comment by oparoz** [comment]
I get a different error now. "Access Forbidden" instead of the dialogue asking for the 2FA code.

I know it's WIP, but I'm just updating the status :)

**Comment by fguillot** [comment]
When you have upgraded, did you flush the sessions?

I'm also using the dev version with 2FA and I didn't have this issue.

**Comment by oparoz** [comment]
I've restarted both the web server and PHP-FPM and deleted the cookies.

I don't see anything useful in the debug.log.

The URL is: `?controller=twofactor&action=code`
and I see the header, but the 2FA dialogue itself is not accessible.

**Comment by oparoz** [comment]
Is there a way to manually flush a kanboard session?

**Comment by oparoz** [comment]
I've checked the users table and users who have not enabled 2FA are still redirected to the same twofactor controller.

**Comment by fguillot** [comment]
You can flush the sessions by asking people to logout from the application or by removing all php session files on the server. If you use the default file storage of PHP, the location of session files is visible in the parameter `session.save_path` from a phpinfo `php -i`. By example, on Ubuntu, the location is /var/lib/php5.

When you said "Access Forbidden", who is sending this error, the web-server (Apache/nginx) or the application?

**Comment by oparoz** [comment]
> You can flush the sessions by asking people to logout from the application

Nobody is logged in.

> by removing all php session files on the server

They're stored in Redis and I can't just flush everything. That's the reason I was wondering if there was a command which can be run to clear the Kanboard sessions specifically.

Here is a screenshot of what I see after logging in.

![forbidden](https://cloud.githubusercontent.com/assets/323220/11868528/c013caae-a4b8-11e5-9f42-bc3f123bebf3.png)

**Comment by oparoz** [comment]
Testing with a user without Looking at the network tab, I see a POST to `?controller=auth&action=check` which gives me a 302 to `dashboard`.

I have a KB_SID cookie when I reach the login page and I get a KB_RM cookie after logging in.

**Comment by fguillot** [comment]
I don't really understand what is going on, I still not able to reproduce your issue.

So what happen with this scenario:

- update Kanboard
- open a new incognito window (to start without any existing cookies and with a clean session)

1. try to login with a user without 2FA enabled
2. try to login with a user with 2FA enabled

Which case is working and which one does't work?

**Comment by reiner** [comment]
Hello Frederick,

I think there is an issue with the plugins. I have deleted all plugins and then I will not get this error any longer…

cheers,
Reiner

Am 18. Dezember 2015 bei 02:16:43, Frédéric Guillot (notifications@github.com) schrieb:

I don't really understand what is going on, I still not able to reproduce your issue.

So what happen with this scenario:

update Kanboard
open a new incognito window (to start without any existing cookies and with a clean session)

try to login with a user without 2FA enabled
try to login with a user with 2FA enabled
Which case is working and which one does't work?

—
Reply to this email directly or view it on GitHub.

-- 

# Bitte beachten Sie meine neuen E-Mail-Öffnungszeiten um 12 und um 16 Uhr: http://rgae.de/oeffnungszeiten #

Reiner Gärtner
Editorial Services

ph.: +49-7522-7019321
rg@reinergaertner.de
www.reinergaertner.de

**Comment by rverchere** [comment]
Hello,

same issue there.
Upgraded from 1.0.21 to 1.0.22. "acl" issue when I have a plugin installed, no issues when I delete them.

**Comment by oparoz** [comment]
I've moved the plugins folder out of the root and it doesn't change anything.
Using another browser or an incognito window doesn't change anything.

With the latest update:
* User with 2FA -> Redirect loop
* User without 2FA -> Access denied

Did permissions change recently. Maybe Kanboard can't access something and is throwing this error which has nothing to do with login?

**Comment by oparoz** [comment]
Plugins used:
* SubtaskForecast
* Timetable
* Budget

**Comment by oparoz** [comment]
Checked the DB tables for changes introduced by 1.0.22. This has not happened:

> SQL table changes:
    - "users" table: added new column "role" and removed columns "is_admin" and "is_project_admin"
    - "project_has_users" table: replaced column "is_owner" with column "role"
    - Sqlite does not support alter table, old columns still there but unused

**Comment by oparoz** [comment]
Checked the schema version and I'm on 98, but nothing was updated past 93.

**Comment by oparoz** [comment]
I've modified the version which triggered an update, but it silently fails. The version is updated to 98, but the queries are not run.

That's on MariaDB 10.

**Comment by oparoz** [comment]
@fguillot - This is still happening on master. All schema updates silently fail and Kanboard becomes unusable until they're manually run.

**Comment by sjlovell** [comment]
I had this problem upgrading to latest version . Got the access forbidden message posted on Dec 17th by oparoz.
Remembered that there were a few things I had to do initially to get the db working around table permissions so since there were new tables I ran those scripts and flushed privileges and it now works:
Mysql>grant all privileges on <databasename>.* to ’<username>’@’localhost’;

Mysql>grant all privileges on <databasename>.* to ’<username>’@’%’ identified by ‘<password>’;

Mysql>flush privileges;


May help someone else?

**Comment by oparoz** [comment]
I'm not sure this applies to what I'm seeing since the schema updates do work if I call them from a custom script reusing Kanboard methods and execute it from the cli. The online updater must be aborting for some other reason.

**Comment by fguillot** [comment]
I'm not able to reproduce your issue with MariaDB or Mysql. With the latest version the schema migrations have been improved to be more reliable. I hope that this fix this issue. Otherwise, if the schema still not up to date, unfortunately you will have to fix it manually.
