### ISSUE TITLE
config.php in docker installations

### ISSUE THREAD

**Issue by waja** [fguillot/kanboard#1530]
Hi there,

since the docker image only provides a volume for ```data/```, it is not possible to adjust values via ```config.php```. Is there any suggested way in doing this instead?

Thanks, Jan.

**Comment by waja** [comment]
As workaround I mounted the file as volume into the container. This requires to restart the container on each modification, which is not very handy.

**Comment by fguillot** [comment]
At the moment, I think people use their own DockerFile when they want to customize the config, for example: https://github.com/blufor/docker-kanboard

But, I can easily modify the code to load the config.php from /data if not present in the default location. In this way, you will be able to put everything in a single volume. Do you think that will improve your deployment process?

**Comment by waja** [comment]
> But, I can easily modify the code to load the config.php from /data if not present in the default location.

This would fit I think. Many thanks.

**Comment by fguillot** [comment]
It's now available in master, the next stable version will probably be released in the next couple of days.

**Comment by waja** [comment]
Works like a charm, many thanks!
