### ISSUE TITLE
On first try: Unable to load this plugin class \Kanboard\Plugin\@eaDir\Plugin

### ISSUE THREAD

**Issue by PatDeLux** [fguillot/kanboard#1532]
I extracted the zip file to the web folder of my synology NAS, browsed to the *kanboard* folder with chrome, and got this message:

`Internal Error: Unable to load this plugin class \Kanboard\Plugin\@eaDir\Plugin`

**Comment by fguillot** [comment]
What do you have in the plugins folder?

**Comment by PatDeLux** [comment]
Thanks for replying.
plugins folder only contains a ".gitignore" file...

Et bravo pour miniflux, que j'ai aussi installé, et qui va vite remplacé
feedly. C'est super !

Patrick Honorez

**Comment by fguillot** [comment]
The plugin system of Kanboard try to load all subdirectories in the plugins folder.

Apparently, your Synology NAS is creating folders `@eaDir`, see http://nerdlogger.com/2012/03/08/synology-nas-and-those-pesky-eadir-folders/

I think you just need to remove these folders manually and that will work.

**Comment by PatDeLux** [comment]
worked perfectly. A million thanks !

**Comment by eSkiSo** [comment]
If anyone has this problem when using OSX, using the terminal go to the plugins folder and do sudo rm ._* to remove the hidden osx files, this will cause the same error.

**Comment by ZeRico** [comment]
hello All, i've just faced the same problem after having klicked on metadata plugin install "link" in extension manager (I'm running kanboard in Docker ... (ubuntu) 
something special to do too/ clean ? 
thanks 

> Internal Error: Unable to load this plugin class \Kanboard\Plugin\kanboard_plugin_metadata-1.0.29.0\Plugin
