### ISSUE TITLE
mySQL error after upgrade when saving a task

### ISSUE THREAD

**Issue by entwisi** [fguillot/kanboard#1533]
Hi, I get the following error back to my browser after I updated my install that was working fine. I added remote access to MySQL to allow a 2 webserver load balanced solution and this apears to work fine in accessing the board. When I edit a task I get the following, ( teh task does update if I go back to the board ) error  taken from a local windows install running on XAMPP pointing at the main DB but is exactly the same error I received using my prod webserver instances. 

Fatal error: Uncaught exception 'PicoDb\SQLException' with message 'SQL error' in C:\xampp\htdocs\kanboard\vendor\fguillot\picodb\lib\PicoDb\Database.php:319 Stack trace: #0 C:\xampp\htdocs\kanboard\vendor\fguillot\picodb\lib\PicoDb\Database.php(276): PicoDb\Database->handleSqlError(Object(PDOException)) #1 C:\xampp\htdocs\kanboard\vendor\fguillot\picodb\lib\PicoDb\Table.php(355): PicoDb\Database->execute('SELECT 1 FROM `...', Array) #2 C:\xampp\htdocs\kanboard\app\Model\ProjectIntegration.php(64): PicoDb\Table->exists() #3 C:\xampp\htdocs\kanboard\app\Integration\SlackWebhook.php(22): Model\ProjectIntegration->hasValue('3', 'slack', 1) #4 C:\xampp\htdocs\kanboard\app\Integration\SlackWebhook.php(72): Integration\SlackWebhook->isActivated('3') #5 C:\xampp\htdocs\kanboard\app\Subscriber\ProjectActivitySubscriber.php(53): Integration\SlackWebhook->notify('3', '562', 'task.update', Array) #6 [internal function]: Subscriber\ProjectActivitySubscriber->execute(Object(Event\TaskEvent), 'task.update', Object(Symfony\Component\Eve in C:\xampp\htdocs\kanboard\vendor\fguillot\picodb\lib\PicoDb\Database.php on line 319

for now I have created a new DB and migrated the tasks to that and that works fine but teh original DB seems to be borked somehow.

**Comment by fguillot** [comment]
Which version of Kanboard are you using ? and from which version did you upgrade ?

The filenames that appears on the stack trace you have copy/pasted doesn't exits anymore. Slack have been moved to an external plugin.

**Comment by entwisi** [comment]
Both release packages seem to show Version 1.0.18. By pointing my dev machine( also on 1.0.18)  at each of the databases in turn by just altering the database name in config.php the original one throws the error on updating tasks, the new DB doesn't. No other changes in config.php, just the name of the DB. 

I see you are now at v1.0.23, I'll download and test against that but my logic suggests that its something in the DB itself seeing that the web side of stuff works against the new clean DB that was created and is broken against the old one. 

Ian
