### ISSUE TITLE
[feature request] Warn about missing PHP extensions

### ISSUE THREAD

**Issue by lathan** [fguillot/kanboard#1539]
Some people are not very smart ( #1538 ) and might install kanboard without checking that they have the right php extensions installed and loaded.

It would be helpful to warn them when one of the modules is missing. This is usually done during installation, but kanboard being minimalistic doesn't have any installation process. One other way would be when kanboard is trying to call a function but the function is missing.

**Comment by fguillot** [comment]
There is already a basic check: https://github.com/fguillot/kanboard/blob/master/app/check_setup.php

**Comment by lathan** [comment]
Oh, when is this called?

**Comment by fguillot** [comment]
For each request, I added recently the check for the gd extension.
