### ISSUE TITLE
Bug: re-opening one task makes all the open tasks closed

### ISSUE THREAD

**Issue by raphaelbastide** [fguillot/kanboard#1541]
I closed a task (by mistake), then opened it again. Now all my tasks (except 2) are located in a column I created to automatically close it. I really don’t understand what happen but it seams to be a bug. I am sorry I can’t really give much more details here. I use v.2.15

**Comment by fguillot** [comment]
I cannot really reproduce what you are saying.

**Comment by raphaelbastide** [comment]
I cannot neither, It was solved some times after the issue. Everything is now in order without any action from me. I suspect a lagg, server side but I am not sure. I think the issue can be closed!
