### ISSUE TITLE
Implement a settings section for custom styles

### ISSUE THREAD

**Issue by xavividal** [fguillot/kanboard#1542]
Althought now there's a textarea where we can inject some custom css styles, maybe could be useful to have something to define some basic styles:

* custom logo
* font size 
* links color
* font color
* header background color
* etc...

A good example could be the default theme customization setup of Drupal.

**Comment by fguillot** [comment]
Since Kanboard focus on simplicity, it will be better to have a plugin for that. It's also possible to develop themes with the plugin api.

**Comment by emmanuelbuah** [comment]
I'd like to create a theme for kanboard. Can you point me to the right resources to get started. What would I be able to do theme-wise via the plugin api? Change almost everything or certain aspects.

**Comment by BlueTeck** [comment]
look at https://github.com/kanboard/plugin-example-css
