### ISSUE TITLE
Project managers / Project members generate Error 500 

### ISSUE THREAD

**Issue by dromek** [fguillot/kanboard#1544]
Hi
When I click on **Project Managers \ Project Member** in **Project Management** I gets Error 500.
This problem occurs both in demo and my private installation.

![demo_kanboard_2](https://cloud.githubusercontent.com/assets/15367630/11776682/552e2a8e-a249-11e5-98f5-e9fbef639da3.PNG)

![demo_kanboard](https://cloud.githubusercontent.com/assets/15367630/11776642/047e2044-a249-11e5-9ca6-37625c6f017d.PNG)

Regards, Damian

**Comment by Busfreak** [comment]
It throws
**Fatal error:** Undefined class constant 'TABLE' in /www/htdocs/xxx/kanboard/app/Model/ProjectPermission.php on line 31
on URL: ?controller=projectuser&action=managers&user_id=1 and ?controller=projectuser&action=members&user_id=1

**Comment by dromek** [comment]
The same issue is in **User Overview** :-(

![demo_kan](https://cloud.githubusercontent.com/assets/15367630/11783130/ae715c0c-a275-11e5-9b61-12c9fd7e574b.PNG)

![demo_kan2](https://cloud.githubusercontent.com/assets/15367630/11783134/b3187326-a275-11e5-8f2d-039e1d79c19d.PNG)

**Comment by fguillot** [comment]
It's now fixed in the development branch. If you need the fix right now, you can use the nightly build.

Thanks to report this issue.

**Comment by johnleta** [comment]
what specific files should I copy over that fixed the issue?

**Comment by TabDambrine** [comment]
If i remember well i followed the modifications in this commit https://github.com/fguillot/kanboard/commit/f01e2f4b781651b2fbb9e1dc079c7eaaae14a4d2 about the file app/Model/ProjectPermission.php to make it work.

**Comment by fguillot** [comment]
I published a new version that includes the fix: http://kanboard.net/news/version-1.0.23
