### ISSUE TITLE
Sorting for Id/Username/etc results in "There is no user in this group."

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1545]
I tried out the new group feature and wanted to sort the table by Id

![image](https://cloud.githubusercontent.com/assets/13346344/11777036/e5892d2a-a24b-11e5-9b1b-79b7f3301752.png)

after clicking on Id the view is empty:

![image](https://cloud.githubusercontent.com/assets/13346344/11777071/2b2db378-a24c-11e5-8625-0067ee2128ec.png)

The link changes from `group_id=1` to `page=1`
and if i change the `page=1` to `group_id=1` it works.

seems to be a minor bug there.

greetings!

**Comment by fguillot** [comment]
It's now fixed in the dev branch.

Thanks.
