### ISSUE TITLE
Exception on start a subtask (with PostgreSQL-9.1).

### ISSUE THREAD

**Issue by vsadriano** [fguillot/kanboard#1546]
Uncaught exception 'PicoDb\\SQLException' with message 'SQL error' in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php:318\n
#0 /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php(276): PicoDb\\Database->handleSqlError(Object(PDOException))\n
#1 /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php(260): PicoDb\\Database->execute('SELECT subtasks...', Array)\n
#2 /var/www/html/kanboard/app/Model/Subtask.php(136): PicoDb\\Table->findAll()\n
#3 /var/www/html/kanboard/app/Controller/Task.php(58): Model\\Subtask->getAll(326)\n
#4 /var/www/html/kanboard/app/Core/Router.php(88): Controller\\Task->show()\n
#5 /var/www/html/kanboard/app/Core/Router.php(107): Core\\Router->load('/var/www/html/k...', '\\Controller\\tas...', 'show')\n
#6 /var/www/html/kanboard/index.php(8): Core\\Router->execute()\n#7 {main}\n  thrown in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 318

**Comment by fguillot** [comment]
As described in the documentation Kanboard is tested only with Postgres >= 9.3

You should enable the debug mode and look for the SQL error in `data/debug.log` or just check Postgres sql logs. Having the error message from Postgres will be really useful.
