### ISSUE TITLE
Plugins are not been loaded

### ISSUE THREAD

**Issue by luisriera** [fguillot/kanboard#1549]
Hi all,

I first installed Ver 1.0.20, and I could not make the plugins to load.  I followed the proposed fix in "Plugin activation #1464", but I could not make it work either.  I just updated to Ver 1.0.22, and still can get the plugins to work.  When I change the config.php in Ver. 1.0.22 as follow:
>// Plugins directory
>define('PLUGINS_DIR','plugins');

I get the following error:
>Internal Error: Identifier "acl" is not defined.

If I move the the plugins directory to the /data/plugins which it is the the default in the config.php I get the same error:
>Internal Error: Identifier "acl" is not defined.

Any help will be  appreciated.

**Comment by dromek** [comment]
Hi 
I had this error when I upgrade. Close all users session. 
You can try login to Kanboard in private card in browser ;-)

Regards, Damian

**Comment by luisriera** [comment]
Thanks for your replay Damian.

I do not know what you mean by "try login to Kanboard in private card in browser ".  

If I use my "Incognito Window" in the browser I still get the same error.

**Comment by fguillot** [comment]
Just update your plugins.

**Comment by luisriera** [comment]
Thanks! 

It is working.

**Comment by cyrildmoses** [comment]
Hi Luisriera, I ma also getting the same error? Can you please help me to resolve this error?

Internal Error: Identifier "applicationAccessMap" is not defined.
