### ISSUE TITLE
Kanboard installation postgres error -SQLSTATE[42601]: Syntax error: 7 ERROR

### ISSUE THREAD

**Issue by DevOps-Haze** [fguillot/kanboard#1551]
Hi All,
My first post in GitHub. I have installed Kanboard and trying to get the login page up but I am getting following error -
Internal Error: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "NOT" LINE 1: CREATE TABLE IF NOT EXISTS schema_version 

I have used postgres as recommened by team and this is my first time. Postgres sql server version installed is 8.4.20 
Could anyone point me in right direction as to what could be the cause of this issue ?

**Comment by fguillot** [comment]
Your Postgres server is too old, as described in the documentation only the version >= 9.3 are supported.

http://kanboard.net/documentation/postgresql-configuration

**Comment by DevOps-Haze** [comment]
Thanks I have updated my postgres to 9.4 and it works fine now. Unable to login with admin user. Gives error bad username password.
