### ISSUE TITLE
[FR] Drag-drop order of subtasks

### ISSUE THREAD

**Issue by neurocis** [fguillot/kanboard#1553]
pingback to [FR] order subtasks #672.

When working with large numbers of subtasks the move up/down is just not sufficient. The ability to drag and drop the order would be "exquisite".

I am finding our process is to launch the main task of a project, then we are having a meeting to finalize out the subtasks while someone is updating kanboard live based on group feedback.

**Comment by tkwells** [comment]
+1

**Comment by fguillot** [comment]
Drag and drop for subtasks is now available in the development version.
