### ISSUE TITLE
Running with https enabled does not work

### ISSUE THREAD

**Issue by lmdv** [fguillot/kanboard#1554]
Hi,

Just installed kanboard on a clean debian machine.
Afterwards I ran the "lets encrypt" application to easily set up https.
Kanboard seems to work but after (almost) every action I get the folowing error: "Internal Error: SQL error".

Before running lets encrypt, everything seemed to work.

Is this something wrong on my setup? Or is kanboard not ready for https yet?

**Comment by fguillot** [comment]
Your issue is not related to HTTPS at all, the error message indicate "SQL error" so it's related to the database.

You should enable the debug mode, watch the log file, and when the error occurs, copy and paste the exact SQL error message here, that will be helpful to understand the problem.

**Comment by lmdv** [comment]
You are completely right! 
The problem had nothing to do with https. It works just fine. :-)
The access rights to the data dir were incorrect.

Thanks for your help and for this great app!

Luis
