### ISSUE TITLE
enabling LDAP_GROUP_PROVIDER breaks Kanboard

### ISSUE THREAD

**Issue by mildis** [fguillot/kanboard#1557]
When setting LDAP_GROUP_PROVIDER to true, Kanboard displays a blank page.

Error logs says :
```[Wed Dec 16 12:11:28 2015] [error] [client 192.168.8.102] PHP Parse error:  syntax error, unexpected ')', expecting T_PAAMAYIM_NEKUDOTAYIM in /srv/kanboard/app/Group/LdapBackendGroupProvider.php on line 48```

LDAP server is ActiveDirectory.
User auth works.
LDAP_GROUP_ADMIN_DN and LDAP_GROUP_MANAGER_DN are left empty.
This is an upgrade from 1.0.17 to 1.0.22 with already registered users and existing projects.

**Comment by SchmilK** [comment]
Same here v 1.0.22 (not sure what the previous version was because I was just asked to get LDAP working, which I did, now I am stuck trying to get group permissions to work).

LDAP Server is ActiveDirectory.
User auth works.
LDAP_GROUP_ADMIN_DN and LDAP_GROUP_MANAGER_DN are filled out and working.

**Comment by fguillot** [comment]
This issue is now fixed in the development branch. It was happening only to people using PHP < 5.5 (5.3 and 5.4).

Thanks to report this bug.

**Comment by SchmilK** [comment]
Yes, running PHP 5.4, should I update to 5.5 or wait for update?


On Tue, Dec 22, 2015 at 12:51 PM, Frédéric Guillot <notifications@github.com

**Comment by mildis** [comment]
PHP 5.3.3 here

**Comment by fguillot** [comment]
If you cannot wait the next release you can apply the fix manually: https://github.com/fguillot/kanboard/commit/8ff2032ea3fa49972fe076166c831719131e829d (change the line 48)

It's better to have the most recent version of PHP but it's not always possible.

**Comment by SchmilK** [comment]
Awesome thank you!!
