### ISSUE TITLE
Export option for LibreOffice

### ISSUE THREAD

**Issue by Gusatomik** [fguillot/kanboard#1561]
I was surprised to see you propose to export the pads to word but not to LibreOffice.
Even if LibreOffice can open Word formated files...

**Comment by fguillot** [comment]
There is no Word exports in Kanboard. The exports use the CSV format which is compatible with any spreadsheet software.

**Comment by Gusatomik** [comment]
I'm sorry fguillot, i don't know what happened, I was supposed to submit this issue to another project, I don't understant why it came here...
