### ISSUE TITLE
Project Permissions with Groups leads to wrong permission

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#1562]
I tried permission management with groups.
One group with *project members*, one with *project managers*.
Combining both groups in one project, without declaring single user permissions.
If a user is member in both groups, only the *project member* permissions get active, not the *project manager*. Adding the specific user additionally as project manager leads to the correct permission *project manager*.

I think, combining permission with groups should lead to the "higher" permission.

**Comment by fguillot** [comment]
It's fixed now in the master branch. Thanks!

**Comment by Busfreak** [comment]
Great!
I thank You!!
