### ISSUE TITLE
mysql.sql missing "is_admin" column in 'users' table

### ISSUE THREAD

**Issue by leewiscovitch** [fguillot/kanboard#1565]
When I try and import the app/Schema/Sql/mysql.sql file into an empty database I'm getting this error:

ERROR 1054 (42S22) at line 613: Unknown column 'is_admin' in 'field list'

In the mysql.sql file, in section that creates the 'users' table it looks like this was removed:
```sql
`is_admin` tinyint(4) DEFAULT '0',
```
If I add that back to the file it imports correctly. This is in version 1.0.22

**Comment by leewiscovitch** [comment]
After looking at the release notes it looks like that column was removed on purpose:

"users" table: added new column "role" and removed columns "is_admin" and "is_project_admin"

Guess that means that this line needs to be edited:
```sql
+INSERT INTO users (username, password, is_admin) VALUES ('admin', '$2y$10$fe3.kkCOOiOxf21QW0tEUOCo5hsL19ct4YUumL.xxTnKKMbJCUb/y', '1');INSERT INTO schema_version VALUES ('97');
```

To maybe this:
```sql
+INSERT INTO users (username, password) VALUES ('admin', '$2y$10$fe3.kkCOOiOxf21QW0tEUOCo5hsL19ct4YUumL.xxTnKKMbJCUb/y');INSERT INTO schema_version VALUES ('97');
```

Although I'm honestly not sure, I'll leave that up to the devs ;)

**Comment by fguillot** [comment]
You are right, my bad, I forget to update that.

The SQL should like that:

```sql
INSERT INTO users (username, password, role) VALUES ('admin', '$2y$10$EIYcgiDba33chGTqlP4cYeXSF7WC5RJPr8eMGsx.8gVT1Q4OUgkay', 'app-admin');
```

It's now fixed in the development branch.

Thanks to report that.
