### ISSUE TITLE
Access denied for user

### ISSUE THREAD

**Issue by luisriera** [fguillot/kanboard#1569]
Hi all,

After experimenting a big with Ve1.0.22 in testing machine; however, when I intent to replicate the setup in a production environment I go the following error:
> Internal Error: SQLSTATE[HY000] [1045] Access denied for user 'kanbord'@'localhost' (using password: YES)

I have change and verify the user, database, and password in the config.php and they are ok.

The main different between the two computers is that the testing was run on PosgreSQL and the production is in MySQL.

Any help

**Comment by DevOps-Haze** [comment]
It looks like sql credentials are wrong in config.php of kanboard. Have you tried verifying database connections with your given username. Also you could substituting localhost with hostname where your db is hosted.

**Comment by luisriera** [comment]
Thanks, I was missing the an "a" in the user name and the BD name.
