### ISSUE TITLE
Bad username/password error when trying to login to kanboard

### ISSUE THREAD

**Issue by DevOps-Haze** [fguillot/kanboard#1570]
Hi,
I have installed kanboard on apache server on linux box. Running postgres 9.4 on php 5.3.3-46 When trying to login as admin I get bad username/password error on login page. Can anyone help me out why this could be due to ?

**Comment by BlueTeck** [comment]
You tried admin/admin?

**Comment by DevOps-Haze** [comment]
funny enough that worked. thanks a tonne !!!
