### ISSUE TITLE
Why is necessary to have an SSD when using Sqlite? 

### ISSUE THREAD

**Issue by SSDAM** [fguillot/kanboard#1576]
From the documentation:
«Use Sqlite database only when you have a disk with fast I/O (SSD disks) otherwise use Mysql or Postgresql»

Thanks.

**Comment by fguillot** [comment]
It's not mandatory but recommended especially if you plan to have several users. With slow disk access you may have locking issues when there is too much concurrency. 

When a process wants to write in the database, the entire database needs to be locked during the operation. Other processes have to wait... For example, do not use Sqlite on a shared NFS mount.

In summary:
- Sqlite = single user or small team
- Mysql/Postgres = multiple users with a lot of projects

**Comment by SSDAM** [comment]
Aha, now that's more appropiate, @fguillot 
From the single user/small team perspective, this information is a bit scary. Now I see, if you come from a big team, the documentation is more accurate.

Thank you!
