### ISSUE TITLE
Having sub-columns

### ISSUE THREAD

**Issue by rverchere** [fguillot/kanboard#1580]
Hello,

Is it possible to have sub-columns like this (doing/done)?
![kanban image](http://kanbanblog.com/explained/image/kanban-board-1.png)

Thanks!

**Comment by MorganGeek** [comment]
It would be wonderful :) ! At work we want to make a distinction between doing/done statuses but we're stuck

**Comment by BlueTeck** [comment]
duplicate of #530 and a lot of other issues

**Comment by rverchere** [comment]
Ok, so I close it.
