### ISSUE TITLE
Swimlane filters not working consistenly in (Board, List or Gantt Views)

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#1582]
Hello,  

I may have found a bug.  I have stood up kanboard on a Ubuntu 14.04 LTS box with postgres as my database backend.  While working on some tasks with my team I found that I was not able to isolate tasks by swimlanes in any of the views consistently.  Below our examples of the filters I used.  

Did Not Work
status:open swimlane:"Relocation and Consolidation Project"

Worked
status:open swimlane:"*Management Tasks" - Worked
status:open swimlane:default

After further review there appears to be some type of string limit on the length of the swimline filter.  Also, I currently have 9 Swimlanes and growing on the board this issue was discovered.  

Thank You

**Comment by GDmac** [comment]
maybe related. on a fresh install, created private project, created two tasks (with a start and other with due date). i closed one task. then to show it, filter by "closed tasks". then "clear filter". 

if i then navigate to list or gant, it somehow re-applies some filter. It took some time, and selecting other filters before it started showing task and working again.

ps. love the amazing software, kuddos.
