### ISSUE TITLE
there is no directory "vendor" in app - cannot run from Github directly

### ISSUE THREAD

**Issue by rmaddox** [fguillot/kanboard#1587]
in common.php:
```
require __DIR__.'/../vendor/autoload.php';
```
but there is no directory "vendor" in app.

**Comment by fguillot** [comment]
Just read the documentation: http://kanboard.net/documentation/installation

**Comment by rmaddox** [comment]
I have installed from "stable" and it works. Thank you much for Kanboard, it looks crazy simple and usable.
