### ISSUE TITLE
documentation installation incomplete

### ISSUE THREAD

**Issue by anathemes** [fguillot/kanboard#1588]
Bonjour,

il semble que la documentation pour l'installation sur Ubuntu 14.04 : http://kanboard.net/documentation/ubuntu-installation soit incomplète. En effet, il est indiqué :
  sudo apt-get install -y php5 php5-sqlite unzip

Ce qui au premier démarrage va entraîner l'erreur :
  Internal Error: PHP extension required: "gd"

Proposition d'amélioration de la doc. :
  sudo apt-get install -y php5 php5-sqlite php5-gd unzip

Super logiciel, merci pour le travail effectué et joyeux Noël ;-)

**Comment by fguillot** [comment]
La documentation a été mise à jour, merci !

**Comment by anathemes** [comment]
Merci :-)
