### ISSUE TITLE
PHP Fatal Error from Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'

### ISSUE THREAD

**Issue by Bellgrad** [fguillot/kanboard#1599]
Hello!

I want move on a mysql database and I have a problem after configure Kanboard files.

I have an 500 error and on the apache log file, I have this:=
[Fri Jan 01 23:38:27.642509 2016] [:error] [pid 1198] [client XXX.XXX.XXX.XXX:56969] PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /var/www/XXXX/kanboard/vendor/fguillot/picodb/lib/PicoDb/Driver/Mysql.php on line 52

In this file I have this in the public function createConnection:
        $options = array(
            PDO::MYSQL_ATTR_INIT_COMMAND => 'SET sql_mode = STRICT_ALL_TABLES',
        );
Lack there anything after the "," ? I have no idea to resolve this problem and I'm returned in a Sqlite Database. And I don't want that.

Thank you.

**Comment by fguillot** [comment]
Check if the extension `pro_mysql` is correctly enabled.

**Comment by Bellgrad** [comment]
It's fixed!
The extension pdo_mysql was not installed correctly. Now it works

Thank you for your support.
