### ISSUE TITLE
LDAP_GROUP_PROVIDER doesn't work if LDAP_BIND_TYPE is user

### ISSUE THREAD

**Issue by okelet** [fguillot/kanboard#1608]
When typing in the LDAP group search from the project permissions, the error shows:

    [2016-01-05 15:32:04] [error] LDAP authentication failure for "mydomain\%s"

With LDAP_BIND_TYPE=proxy, and setting LDAP_USERNAME and LDAP_PASSWORD, the autocomplete works fine. I think this is not really a bug, because to do searches after login, the password should be saved anywhere, considering the security problems. So, the documentation should notice that LDAP_GROUP_PROVIDER only works with anonymous binding or proxy.

**Comment by fguillot** [comment]
The documentation have been updated. Thanks.
