### ISSUE TITLE
Theme Request

### ISSUE THREAD

**Issue by SchmilK** [fguillot/kanboard#1611]
Is it possible to get the Logout and Username text to be the same class as the header h1?  Trying to get a clean header bar and it's difficult when those use visited and unvisited classes.  I know I can modify the source files (like I changed KB to our company name) but I'd like to keep source edits to a minimum so updates can be simple.

Picture example is attached.
![cssclassrequest](https://cloud.githubusercontent.com/assets/4335981/12127092/d8688886-b3ba-11e5-96ab-78ce3e68d38d.jpg)

**Comment by SchmilK** [comment]
So I changed the order of operations in my custom style sheet to this order and now the UserName is white.  Still trying to figure out how to change Logout to white.  But it's much better now.

a:link {...}
a:visited {...}
a:hover {...}
a:active {...}
.username a {...}

**Comment by fguillot** [comment]
The page header have modified in the development branch. Now there is a dropdown menu for the user and each different part of the header are using a different css class. So you can change the logo, the title and the rest more easily.
