### ISSUE TITLE
Creating task via mailgun: task not showing up

### ISSUE THREAD

**Issue by PatDeLux** [fguillot/kanboard#1621]
Hi, I have configurated a mailgun account, the DNS settings are all "green" there, and the `route` seems ok as well. 
Then I have installed the plugin and updated  config.php.
I assigned an identifier to the test project.
After some trials I now have mailgun logs saying the message is "delivered", but I don't see the task appearing in my kanboard.  
What can be wrong ?

Thanks !!

**Comment by jtourt** [comment]
How about user configuration?   You did not mention any details about user configuration.

Kanboard configuration
1.Be sure that your users have an email address in their profiles
2.Assign a project identifier to the desired projects: Project settings > Edit
3.Try to send an email to your project: something+myproject@mydomain.tld

*NOTE*: The sender email address must be same as the user profile email address in Kanboard and the user must be member of the project.

---
Another thing to check is that the sender address is the address that you expect.  Some automated systems may have a SENDER address that is different than the FROM address that email programs display.  For example, I discovered this when I configured Toodledo to send reminders to my Kanboard.  Toodledo is using Amazon Web Services to send emails, and each email is sent with a randomized sender address.   Check in the Mailgun logs and verify the sender address matches the email address for a user in your Kanboard, and the user is a member of the project.


Example of sender address not matching from address:
![mailgun-sender](https://cloud.githubusercontent.com/assets/14179005/12216585/dfbf24c6-b6b4-11e5-9a4f-3738326ff195.png)

**Comment by PatDeLux** [comment]
@jtourt Thanks for replying. here are my settings and results. I have tried several thinks, with no result. Note however that Mailgun logs says the delivery is completed.
Mailgun domain info:
![2016-01-12 11_04_29-mg idevlop com - mailgun](https://cloud.githubusercontent.com/assets/4831319/12260670/3926149c-b91d-11e5-8a38-d5c4e2833466.png)
Mailgun log:
![2016-01-12 11_06_17-logs - mailgun](https://cloud.githubusercontent.com/assets/4831319/12260674/4116c156-b91d-11e5-9e5d-e64bc0729fb1.png)
Kanboard settings:
![2016-01-12 11_08_40-idevlop](https://cloud.githubusercontent.com/assets/4831319/12260691/53361e54-b91d-11e5-8f56-29d5f18f7260.png)

**Comment by PatDeLux** [comment]
Just noticed that the problem might be in the routing:
  1. example for routing used to be action=task, has now become action=receiver
  2. my initial setting uses http, instead of https. perhaps kanboard does not "listen" to http ? Anyway I changed that but it seems I will have to change something to my firewall as well, because server not available using https

**Comment by jtourt** [comment]
It could be routing.  The config will vary depending on the version of Kanboard that you are running, as well as the version of Mailgun.

- What is the string that shows in Integrations for Mailgun?  Settings / Integrations.  This is the string to  enter into Mailgun for the route.  (If you reply back here, leave off the token, of course.)

- What is the version number of Kanboard?   Settings / About.
- What is the version number of the Mailgun plugin?   Settings / Plugins.

At this time, there is no need to bother with opening up https on your firewall.  That is not the issue.  Http is working fine.

The question still remains if the email address for your user account matches the sender address.
In User Management, the email address showing beside your account is the same address that is in the Mailgun screenshot above?    (Just checking.)

I think you are close.  Mailgun seems to be working.  Just need to get the route action right now.

**Comment by PatDeLux** [comment]
Version of Kanboard: 1.0.23-fix1​
Settings/integrations: nothing appears for Mailgun. Only
 Google/Github/Gitlab authentication and Gravatar
Mailgun Plugin version: 1.0.1

I am sending test emails from the same address that is defined for me as a
Kanboard user.
The emails are sent to the Mailgun defined domain: mg.idevlop.com, for
instance to kanboard+PROJ1@mg.idevlop.com, PROJ1 beeing an existing project
identifier.
That obviously matches the defined Mailgun route.
What is unclear to me is what to enter in config.php for the MAIL_FROM
parameter, and why in the world that has anything to do with receiving
tasks, since
1) reception is made by http hook
2) sender address should vary if several users are define in Kanboard.

**Comment by jtourt** [comment]
The config.php Mailgun variables are only used for sending mail.  They are not used for receiving.  If you are only using the Mailgun plugin for receiving, none of the Mailgun variables need to be defined in config.php.

It's curious that Mailgun is not showing in the Integrations screen.  It should be.

Delete the Mailgun folder under the plugins folder.  Download the latest release of the Mailgun plugin (v1.0.2) and extract into the plugins folder.

Check if that resolves Mailgun not showing in the Integrations screen.

In Mailgun, define your route action as follows:
http://nas.idevlop.com/kanboard/?controller=webhook&action=receiver&plugin=mailgun&token=

----------------
If that doesn't resolve the issue, turn on debugging in config.php.

// Enable/Disable debug
define('DEBUG', true);

Once debugging is set to true, send an email to the Mailgun address and wait about 6 minutes.  Then check in the data folder for a file named debug.log.  Debug.log is verbose.  Search for "mailgun."  

Reminder: set debug to false when done debugging.

**Comment by PatDeLux** [comment]
@jtourt Many thanks. I reinstalled the plugin and it all works now. 8-D
