### ISSUE TITLE
Bugs in v1.0.23 - automatic actions - only last defined action executes, and wrong events are triggering

### ISSUE THREAD

**Issue by jtourt** [fguillot/kanboard#1626]
If multiple actions of the same type are defined, only the last action defined will execute.

For example, say that "Assign a color when the task is moved to a specific column" is set on 3 columns: Backlog, Ready, and Work in Progress.

![auto1](https://cloud.githubusercontent.com/assets/14179005/12218704/9c5a012e-b6f5-11e5-8d65-fe0c5f1a68a0.png)

Only task moves to the "Work in progress" column will execute -- not the Backlog or Ready columns.   In previous versions, the color would update as expected when task was moved between the 3 columns.

Building on the same example.  Let's say the actions are now defined as shown in the following screenshot:

![auto2](https://cloud.githubusercontent.com/assets/14179005/12218744/671c5f2e-b6f6-11e5-8d6f-29bf7cf8464a.png)

Now the color will only update in the Done column.  
Tested and found the same behavior with the TaskAssignColorCategory action, as well as my own plugins.

In the screenshot above, only the last two actions defined execute.   

Another issue: Actions are triggering for wrong events.  With the actions defined above--assign the color dark grey on *task creation*--tasks are changed to dark grey when they are created or *moved* into the column. Either event triggers the action, although only task.create is defined.

**Comment by Bakkoda** [comment]
Same issue and this is not new. I recently redid my entire install and switched it over to MySQL because I had the same problem. When the events did trigger it was sometimes 10-15 seconds later as well (the reasoning for me to switch away from sqlite).

Now the events simply do not fire.

**Comment by fguillot** [comment]
I just pushed a fix for this issue.

Thanks for the detailed bug report.

@Bakkoda your issue is probably not related to this one.

**Comment by jtourt** [comment]
Frédéric, thank you for the prompt fix.  I have tested it, and it resolves the issues that I reported.

I did discover another couple bugs while testing.  

Bug(?):
With the automatic actions defined in the second screenshot I previously posted above, the task color does not change when the task is moved between columns when either category Test1 or Test2 is assigned to a task.  

TaskAssignColorCategory is triggering on column moves (Task::EVENT_MOVE_COLUMN) even though it is only supposed to be compatible with Task::EVENT_CREATE_UPDATE.

Is that the intended behavior?  

[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorColumn => false
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorColumn => false
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorColumn => false
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorCategory => false
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorCategory => false
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorCategory => true
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorColumn => true
[2016-01-10 15:43:04] [debug] AutomaticAction \Kanboard\Action\TaskAssignColorColumn => false


BUG:
Click on a category name in a task footer and an internal error message pops up. 

![internal error](https://cloud.githubusercontent.com/assets/14179005/12223777/19546418-b7ae-11e5-9c79-a44dc9c24316.PNG)

This error can be fixed by adjusting /kanboard/app/Template/board/task_footer.php:

```php
<div class="task-board-category-container">
    <span class="task-board-category">
        <?php if ($not_editable): ?>
            <?= $this->e($task['category_name']) ?>
        <?php else: ?>
            <?= $this->url->link(
                $this->e($task['category_name']),
                'board',
                'changeCategory',
                array('task_id' => $task['id'], 'project_id' => $task['project_id']),
                false,
                'popover' . (! empty($task['category_description']) ? ' tooltip' : ''),
                ! empty($task['category_description']) ? $this->text->markdown($task['category_description']) : t('Change category')
            ) ?>
        <?php endif ?>
    </span>
</div>
```
Change the 8th line above with   'board', to
```php
                'boardPopover',
 ```
[One day I'll learn git and how to submit proper pull requests...]

**Comment by Bakkoda** [comment]
This fix also corrected my issues.

*@fguillot* The issues I had discussed went away upon my switch to MySQL(most likely fixed during an update between installs.
