### ISSUE TITLE
Internal error when category is clicked in task footer

### ISSUE THREAD

**Issue by jtourt** [fguillot/kanboard#1630]
Steps to reproduce:
- Add a category to a task.
- In board view, click on the category name in the task footer.
- An internal error message pops up. 

![internal error](https://cloud.githubusercontent.com/assets/14179005/12223777/19546418-b7ae-11e5-9c79-a44dc9c24316.PNG)

This error can be fixed by adjusting /kanboard/app/Template/board/task_footer.php:

```php
<div class="task-board-category-container">
    <span class="task-board-category">
        <?php if ($not_editable): ?>
            <?= $this->e($task['category_name']) ?>
        <?php else: ?>
            <?= $this->url->link(
                $this->e($task['category_name']),
                'board',
                'changeCategory',
                array('task_id' => $task['id'], 'project_id' => $task['project_id']),
                false,
                'popover' . (! empty($task['category_description']) ? ' tooltip' : ''),
                ! empty($task['category_description']) ? $this->text->markdown($task['category_description']) : t('Change category')
            ) ?>
        <?php endif ?>
    </span>
</div>
```
Change the 8th line above with   'board', to
```php
                'boardPopover',
 ```
[One day I'll learn git and how to submit proper pull requests...]

**Comment by fguillot** [comment]
It's now fixed in the development branch.

Thanks!

**Comment by jtourt** [comment]
Thank you.  Closing issue.
