### ISSUE TITLE
Can't attach files to the project itself, only to tasks.

### ISSUE THREAD

**Issue by PIMJIM** [fguillot/kanboard#1631]
It would be great to be able to attach files to the project itself so that they appear on the project summary screen. Also, can the file size limit of the all files be made configurable as an application setting?

**Comment by mfgeo** [comment]
I also just found myself wanting to do this.  Some documents span the entire project scope and best serve to be available across all tasks.  (Could even reference with a link from within a task if need-be)

**Comment by Chaosmeister** [comment]
:+1:

**Comment by awatterott** [comment]
:+1:

**Comment by marifrahman** [comment]
Would be really awesome.

**Comment by fguillot** [comment]
With the last development version of Kanboard you can attach files directly to the projects.

**Comment by mfgeo** [comment]
Thank you!
