### ISSUE TITLE
Change the way Automatic Actions are created

### ISSUE THREAD

**Issue by PIMJIM** [fguillot/kanboard#1633]
Currently after you select an Action, the selected Action is hidden and you then see the Event. When you select the Event, the selected Event is hidden and you see the Parameters. You don't actually see everything until the Automatic Action is created.

I think it would be easier to leave the Action visible and display the Event beneath it. Then leave the Event visible and show the Parameters beneath it. This way you get to see all components at all times.

**Comment by fguillot** [comment]
Your suggestion has been taken into consideration and it's now part of the development branch of Kanboard.

Thanks.
