### ISSUE TITLE
PHP Compatibility issues

### ISSUE THREAD

**Issue by nedelenbos** [fguillot/kanboard#1634]
When upgrading to the latest trunk version, I got the following error:
```php
Kanboard\\Core\\Security\\random_bytes() in /app/Core/Security/Token.php on line 24
```

I'm not running PHP7, so that's probably the problem :)

**Comment by nedelenbos** [comment]
Possible solution is to use 
http://php.net/manual/en/function.openssl-random-pseudo-bytes.php

Instead of random_bytes

**Comment by fguillot** [comment]
There is a polyfill for older PHP, don't forget to do a `composer install` if you are using directly the repo.

**Comment by nedelenbos** [comment]
Ah ofcourse, thanks for that! Then this issue can be closed :+1:
