### ISSUE TITLE
Kanboard hangs when saving certain texts in descriptions or titles

### ISSUE THREAD

**Issue by huberv** [fguillot/kanboard#1638]
We are using Kanboard 1.0.22 and have the following problem: when I create a new task with the description text
```
Check out the current impl. of /HRFE/CL_SECTION_FE->IS_STRUCT_KEY_VALID. In this method it is checked whether the given AUC or CoB is still "contained" in the current section. The problem with this implementation is that whenever the user deleted a CoB, e.g, false is returned and the user is forced to execute the load batch. This, however, deletes the localized data for the CoB/AUC and the protocol entries CAU and DCB cannot be implemented (because the data does not exist anymore).
```
the preview does not work and when I save the task and the screen refreshes I get a connection timeout. I guess that the description text is not escaped properly when the data is written to the DB.

The only way to get the task back into a working state is to press the browser's back button to go back to the edit view or to remove the description text directly in the DB.

When I prefix all underscores with a backslash everything works fine.

**Comment by jtourt** [comment]
Hmm.  Using a fresh test installation of Kanboard 1.0.22, and I tested with the string provided and had no issue with preview, saving, or editing.   

Possible issue with your web browser or something unique to your installation/environment?   I tested in Edge and IE11.

![description](https://cloud.githubusercontent.com/assets/14179005/12234685/b05ea70e-b83c-11e5-9601-8addbf72033c.PNG)

**Comment by jtourt** [comment]
Which database are you using?   MySQL, SQLite, or Postgres.

**Comment by TabDambrine** [comment]
Tested it on our production installation with Chrome 47 on kanboard 1.0.22 install with MySQL/IIS and no problem here.

**Comment by huberv** [comment]
We have MySQL 5.7 and I get the problem with both Chrome 47 and Firefox 43

**Comment by fguillot** [comment]
I tested with Mysql 5.7, Chrome / Firefox / Safari... I'm not able to reproduce this issue. You should try to update Kanboard to the latest version.
