### ISSUE TITLE
[Q] user mentions (@mention)

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1641]
what exactly is it they're doing?

**Comment by BlueTeck** [comment]
https://github.com/fguillot/kanboard/issues/801

https://github.com/fguillot/kanboard/blob/master/doc/user-mentions.markdown

**Comment by thob** [comment]
Thanks - but it doesn't mean that once you're mentioned in a thread you get notified of follow ups, except you're mentioned again, right?

**Comment by fguillot** [comment]
As first iteration of this feature, you receive only one notification when you are mentioned, you are not subscribed to the thread (this feature doesn't exists yet).
