### ISSUE TITLE
Cumulative Flow Chart dates not ordered correct

### ISSUE THREAD

**Issue by tvriend** [fguillot/kanboard#1645]
When using the cumulative flow chart, it orders the dates wrong.
It seems to mix up some dates, not all. 

In the screenshot you can see 7, 8 and 12th of januari being out of place.

![screen shot 2016-01-12 at 14 22 46](https://cloud.githubusercontent.com/assets/13728151/12264623/5897ff32-b938-11e5-9b39-f8f8793313d0.png)

**Comment by tvriend** [comment]
Some information to add after playing around today..
If i press execute a couple of times without changing any settings it will change the order of the dates.
It seems to be a random order of some sorts..

**Comment by fguillot** [comment]
Just for my information, what type of database do you use? mysql or postgres or sqlite?

**Comment by tvriend** [comment]
Database driver: postgres

**Comment by fguillot** [comment]
This issue has been fixed in the development branch. Thanks!
