### ISSUE TITLE
[IMP] Subtask re-order drag n' drop

### ISSUE THREAD

**Issue by neurocis** [fguillot/kanboard#1650]
Same as one can do on the board presently to move tasks about, but applied to the subtasks (together with line numbering?).

I am finding our process is to launch the main task of a project, then we are having a meeting to finalize out the subtasks while someone is updating kanboard live based on group feedback.

**Comment by angystardust** [comment]
This would be a nice improvement but you have already requested this in #1553...so this should be marked as a duplicate issue

**Comment by neurocis** [comment]
Correct, duplicate of my #1553 . Closing as duplicate.
