### ISSUE TITLE
LDAP groups using "memberUid"

### ISSUE THREAD

**Issue by pallando** [fguillot/kanboard#1652]
Hello, 

Kanboard really is a nice program! I was wondering though: would it be possible to look for LDAP group memberships in groups (attribute memberUid) instead of users?

**Comment by kincl** [comment]
+1

**Comment by fguillot** [comment]
It's not implemented, can you explain why you need that?

**Comment by pallando** [comment]
Well... The "MemberOf" attribute requires an overlay for OpenLDAP, which means I should modify my LDAP structure (which follows RFC2307 - posixGroup with memberUid). Maybe it's doable though. 
But since the groups would have to be "groupOfNames" and "posixGroup", I'd have to maintain 2 attributes ("member" and "memberUid") to keep retro-compatibility with other programs. 

I was afraid of modifying my LDAP structure, but if it must come to this, I can try.

**Comment by kincl** [comment]
Yeah its a different LDAP schema structure that is fairly widely used when not interfacing with an AD LDAP implementation.

**Comment by fguillot** [comment]
Ok, I see. If I understand correctly, this is the default LDAP schema with a standard OpenLDAP installation.

I will see how hard is it to make it work.

**Comment by C-Duv** [comment]
I can confirm it's a different (opposite) way of describing membership.
I'm also using `posixGroup` with `memberUid` attributes (each groups nodes stores it's member list, referring to them using their `uid`).

Usually applications that supports both offers a configuration settings to use either one or the other way.

My 2¢.

**Comment by fguillot** [comment]
Latest Kanboard now supports ActiveDirectory, OpenLDAP with memberOf, groupOfNames and Posix Groups.

There are 4 different examples on the website to help you to configure that: https://kanboard.net/documentation/ldap-configuration-examples
