### ISSUE TITLE
Migrating Kanboard

### ISSUE THREAD

**Issue by lostvicking** [fguillot/kanboard#1653]
Hi there.

I've been running Kanboard on my laptop as a trial and have created a project that my team is working on. We now have a new instance of Kanboard on a separate server. How can I migrate all the content off my laptop to this new instance?

Regards and thanks
Victor

**Comment by BlueTeck** [comment]
Which database are you using?

**Comment by lostvicking** [comment]
Thanks BlueTeck, copying the data from the /var/www/html/kanboard directory worked perfectly.
