### ISSUE TITLE
User specific Color

### ISSUE THREAD

**Issue by mauriziodidomenico** [fguillot/kanboard#1654]
First of all, thank you for this great piece of software!

I would appreciate the possibility to allocate a color to a specific user. In the case i assign a task to a user, it adapt the task color to the user specific color.

**Comment by jtourt** [comment]
Click: Actions --> Settings
-- Click: Automatic Actions
-- From the dropdown list, select: Assign a color to a specific user
-- Click Next Step....

**Comment by mauriziodidomenico** [comment]
Yes it's a possibility, but the settings are project related and not global and a have to define 2 rules per user (one for task creation and another one for task assignee change)

**Comment by mauriziodidomenico** [comment]
Is there a possibility to copy the automatic actions to an other project?

**Comment by mauriziodidomenico** [comment]
Thanks for the improvement in the version 1.0.26
