### ISSUE TITLE
Fail to add remote and local users to project (v. 1.0.22)

### ISSUE THREAD

**Issue by felixaballi** [fguillot/kanboard#1661]
I'm trying to adopt Kanboard in my project group, Ldap ready and so. But when I needed to add other remote or local user ('Permissions' section) to a test project, it doesn't work for at all, the completion of the functionality fails.
Redirects to: /?controller=project&action=index, after supposed user addition to project with zero results.

Any help.

**Comment by fguillot** [comment]
Try the last kanboard.

**Comment by felixaballi** [comment]
Thanks a lot. Continue improving it!
I'll check on this.
