### ISSUE TITLE
Screenshot dosn't work with specific hoster

### ISSUE THREAD

**Issue by nreojb** [fguillot/kanboard#1662]
Hello there.

This post isn't really a bug report or something like that but since there is no forum I don't know an other way to solve this problem.

This is whats happening:
* I'm at the BOARD view (this information is importend I think)
* I add the task "Test screenshot" by clicking on the "+" sign in the first column
* I click on the task-ID and select "add a screenshot"
* The window "add a screenshot" opens and I add a screenshot (I can see it after hitting CRTL+V)
* Then I click on the "save" button (I'm getting no error message or something like that)
* After the "add a screenshot" window is closed automatically I'm not back at the BOARD! I'm "redirected" to DETAIL VIEW of the task and the section "Add a screenshot" is open:

![detail view after save button](https://cloud.githubusercontent.com/assets/16576868/12329271/d6bb1540-badf-11e5-8d9d-b866e01541bd.PNG)

The screenshot was NOT attached to the task and there is no error message or something like that.

I'm sure it must be "the fault" of my hoster because I have a copy of this exact kanboard running in XAMPP on a local maschine and an a raspberry pi with nginx with no problems regarding this issue.

So the question I have (I think) is:
Is there a specific PHP extension needed for this "add a screenshot" thing? Or what could be the problem here?

I should mention adding a file via "Attach a document" is working like a charm.

Any help would be greatly appreciated!

Thank you very much!

**Comment by fguillot** [comment]
The screenshot feature doesn't require anything on the server, everything is done in the browser with Javascript.
