### ISSUE TITLE
Toggl integration

### ISSUE THREAD

**Issue by Andiministrator** [fguillot/kanboard#1663]
Hi Frédéric, I wrote a Plugin to report done tasks to Toggl.com. Maybe it is interesting for you ...
[Toggl.zip](https://github.com/fguillot/kanboard/files/90648/Toggl.zip)

**Comment by fguillot** [comment]
I would be cool to publish the code of your plugin somewhere. By example, you can create a repository on Github. So, people can download and contribute/improve easily to your plugin.

**Comment by thob** [comment]
@Andiministrator how does it work? Can a user link it to his personal Toggl account? Or…

**Comment by SergiArias** [comment]
@Andiministrator I think this plugin would be amazing, as Toggl interface is quite flexible compared to built in Kanboard.
But I see you deleted it from github. Are you using a custom plugin now to track? In case you didn't, could you guide me a little bit to modify yours and make it work? (it doesn't work on my kanboard after setting everything up)
