### ISSUE TITLE
Cannot create a purely remote Google user account, needs the first authentication to be a local user

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1672]
Running the latest kanboard release 1.0.23, I created a "remote" user account, with no password, setting the Google account ID to match that person's gmail address. I asked that person to log into the system with google auth with that ID, and it didn't work, saying "remote authentication failed".

To make it work, I had to re-enable local password login for that user, set a temporary password, have that user log into kanboard, go to his user profile/prefs, _unlink_ the external google account and then re-link it. After that was done, Google auth started working correctly.

So maybe there needs to be some sort of real auth initiation handshake going on for the first time, when the user has not successfully logged into kanboard with Google before?

**Comment by fguillot** [comment]
This is now supported by the plugin (only in the dev branch): https://github.com/kanboard/plugin-google-auth#automatic-account-creation

**Comment by nekohayo** [comment]
Your approach is per-domain (assuming one is using Google Apps Enterprise). What about the whitelist approach I was describing, where you type in the email address of the google account you specifically want to whitelist for automatic creation?

**Comment by fguillot** [comment]
Can you describe with an example what you suggest here https://github.com/kanboard/plugin-google-auth/issues

The approach implemented at the moment is a whitelist based on the email domain name.

Thanks
