### ISSUE TITLE
Kanboard - Not recieving email notifications

### ISSUE THREAD

**Issue by shaunthomson2097** [fguillot/kanboard#1673]
Hi.

Thank you for helping me with the user passwords.

The last thing I have to do is get the email notifications to work.

I renamed the  config.default php file to config php and entered my smtp details but still getting the following message: There is no notification method registered.

could you kindle please assist me to get the email notifications to work?

Thanks

**Comment by antoineguilbert** [comment]
Hello, 

Same problem here on my installation. Can someone have an idea to repair email notification ?

Thanks.

**Comment by 85pando** [comment]
Did you set `MAIL_TRANSPORT` to `smtp`?

In the `config.default.php` its in line 23

```php
// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'mail');
```

**Comment by shaunthomson2097** [comment]
Hi. I did set it to smtp. Will try again and get back to you.

Thanks

**Comment by shaunthomson2097** [comment]
It was set up as smtp. The problem was that the 'MAIL_FROM' on line 20 in the config file was not set.

It is now working. For anyone who battles with the same problem here are all the steps to set it up:

1. Rename the "config.default.php" file to config.php (File located in the Kanboard main folder)

2. open the config.php file in a text editor (whichever one you preffer)

3. on line 20, change the: define('MAIL_FROM', 'notifications@kanboard.local');
    Replace 'notifications@kanboard.local' with your email address for example: admin@domain.com

4.  Go to line 22 and 23 and change the following:
// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'smtp');
Replace the 'MAIL_TRANSPORT' to smtp as above.

5. Go to lines 25-30 and change the following:
// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'mail.smtp.co.za');  // YOUR SMTP  HOST NAME
define('MAIL_SMTP_PORT', 25); // CHOOSE THE CORRECT SMTP PORT (DEFAULT 25)
define('MAIL_SMTP_USERNAME', 'admin@domain.com'); // YOUR EMAIL ADDRESS
define('MAIL_SMTP_PASSWORD', 'enterYourEmailPassword'); // YOUR EMAIL PASSWORD
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"

Setup done. (This worked for me and I hope this helps you as well.)

Special thanks to 85pando who took the effort to assist.

Happy Days :)
