### ISSUE TITLE
DB migration from versions

### ISSUE THREAD

**Issue by myuser1234** [fguillot/kanboard#1674]
Hi,

im using version 1.0.21, and I want to upgrade to newer version.
I saw that on version 1.0.22 there was a schema change.
I wonder if there is any script or ability to convert SQLITE DB to newer schema.

thanks.

**Comment by fguillot** [comment]
As described in the documentation, the schema migrations are executed automatically for you. Don't forget to backup your database.

http://kanboard.net/documentation/update
