### ISSUE TITLE
Error message call_user_func_array() expects parameter

### ISSUE THREAD

**Issue by AZimmerhofer** [fguillot/kanboard#1679]
Hi!

I moved a task on kanban. This error message appeared:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'PicoDb\Condition' does not have a method 'decrement' in /.../home/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php on line 665

I am using 1.0.23.-fix1 with Slack integration

Kind regards

**Comment by fguillot** [comment]
Don't forget to update the vendor directory with composer.

**Comment by AZimmerhofer** [comment]
Thanks! That means that you updated the source code in github and corrected this? And I should update my code? Or what? Normally I don't use the composer.

**Comment by fguillot** [comment]
I don't know which version of Kanboard you have installed (stable or dev). But if you use directly the repository, you need to run composer to update the vendor directory.

**Comment by AZimmerhofer** [comment]
Thanks for your fix. It's working with 1.0.24
