### ISSUE TITLE
Unable to hide columns when there are multiple swimlanes

### ISSUE THREAD

**Issue by nedelenbos** [fguillot/kanboard#1680]
As said in the title, when there are multiple swimlanes, it's impossible to hide different columns (occurs on master branch)

**Comment by BlueTeck** [comment]
I can't confirm this bug in 1.0.23, I have not tested the latest master.

**Comment by fguillot** [comment]
It's working for me, which browser do you have?

**Comment by nedelenbos** [comment]
Strange, right now it seems to be working again. I was using the latest Chrome version as we speak (47.0.2526.106). I will keep an eye on it and get back to you when it happens again.
