### ISSUE TITLE
No domain name in the callback URI of GitLab Oauth integration

### ISSUE THREAD

**Issue by jgoux** [fguillot/kanboard#1683]
Hi,

#### Description
I tried to set up the Oauth integration for GitLab, but it fails on the redirect URI.

The exact error displayed on GitLab is : 
```
An error has occurred
The redirect URI included is not valid.
```

The callback URI passed to GitLab seems wrong (no domain's name, there is a "\_" character instead) : 
`&redirect_uri=http%3A%2F%2F_%2F%3Fcontroller%3Doauth%26action%3Dgitlab`

I think I have an issue in the integration config page of kanboard, because my domain name isn't displayed for the callback links : 
![capture](https://cloud.githubusercontent.com/assets/1443499/12422113/912ebc86-bec5-11e5-998b-82bbcc174d2d.PNG)

#### Softwares installed
- Gitlab v8.3.2
- Kanboard v1.0.23

#### Gitlab setup
![capture2](https://cloud.githubusercontent.com/assets/1443499/12421738/efa2f93c-bec3-11e5-9d7a-1750d98d5cae.PNG)

#### Kanboard configuration for GitLab integration
```php
// Enable/disable Gitlab authentication
define('GITLAB_AUTH', true);

// Gitlab application id
define('GITLAB_CLIENT_ID', /*public key*/);

// Gitlab application secret
define('GITLAB_CLIENT_SECRET', /*secret key*/);

// Gitlab oauth2 authorize url
define('GITLAB_OAUTH_AUTHORIZE_URL', 'http://srv-git/oauth/authorize');

// Gitlab oauth2 token url
define('GITLAB_OAUTH_TOKEN_URL', 'http://srv-git/oauth/token');

// Gitlab API url endpoint (don't forget the trailing slash)
define('GITLAB_API_URL', 'http://srv-git/api/v3/');

```

Thanks for this really great project :+1:

**Comment by fguillot** [comment]
You can define the kanboard url in "Settings > application url" to avoid the underscore.

Which web server are you using for Kanboard? do you use docker or anything special?

**Comment by jgoux** [comment]
Sorry, I missed the obvious setting ! :)
It's better with the `application url` !

I was also surprised that we have to create a "remote account" first before being able to login with GitLab. Is there any reason why the account isn't create on the fly when login the first time with GitLab ?

**Comment by fguillot** [comment]
At the moment, this feature is not implemented yet for Gitlab/Github/Google auth. Someone have to develop the "registration/sign up" part. So there is only the minimum right now.

**Comment by jgoux** [comment]
Ok, thanks for the info. :+1:
