### ISSUE TITLE
Add support for subcolumns or shared WIP between columns

### ISSUE THREAD

**Issue by JohnBat26** [fguillot/kanboard#1684]
Hello.
Almost  all books about Kanban have boards with columns or sub-columns and each sub-column has itself WIP limit.

My proposal is:
1. or add support for subcolumns with separate WIP limits;
2. or add support for shared WIP limit between columns.

**Comment by thob** [comment]
:+1:

**Comment by BlueTeck** [comment]
duplicate #530

**Comment by fguillot** [comment]
Closing this duplicate.
