### ISSUE TITLE
[Confused] Create a new task with 'Reference' field from web?

### ISSUE THREAD

**Issue by SchmilK** [fguillot/kanboard#1685]
We just migrated 70+ tasks for our scripting team from our internal ticketing system to Kanboard for better team management and tracking.  One nice .CSV field we used was Reference, where we used our ticket number as the reference number.

For some reason I can't find anywhere when creating a new task, or editing a task, to enter a reference.  

Am I doing something wrong, or is 'Reference' strictly editable when importing from csv?

**Comment by fguillot** [comment]
This feature is clearly missing from the user interface.

At the origin, it was developed to synchronize ticket automatically with some external systems and nobody express the need to update this field from the ui until now.

**Comment by rgarrigue** [comment]
:+1: 

I wouldn't mind it displayed at least, since I'm working on the API, just for a double check.

By the way, I can't see any intel in the doc about it, except the `getTaskByReference` that gave me the hint I needed.

**Comment by fguillot** [comment]
The reference field is now exposed to the user interface (only in the current development branch).
