### ISSUE TITLE
400 Bad Request when drag and dropping a task under another when you have both scrollbars.

### ISSUE THREAD

**Issue by pituseligmann** [fguillot/kanboard#1688]
I've set up a project that has 15 columns and about 20 taks on each column. When trying to move on the same column, a task under the last task on that column I get a 400 Bad Request error and upon pressing F5 the task I wanted to move is back on it's place.

Doesn't happen if I move the last one to a higher position on the column though.

This is happening only when the both scrolls, vertical and horizontal, are 'scrolled' to an extent.

**Comment by fguillot** [comment]
This issue should be fixed with the latest version, do you still having the issue?

**Comment by pituseligmann** [comment]
Unfortunately I had to move on from Kanboard since work opted to switch to Trello, I no longer have it deployed to be able to try and reproduce the issue listed here
