### ISSUE TITLE
Please test upload a chinese name document

### ISSUE THREAD

**Issue by manboo** [fguillot/kanboard#1690]
1. upload a chinese name document, 

2. can't download the document
[新建 测试中文.docx](https://github.com/fguillot/kanboard/files/96878/default.docx)
[鏂板缓 娴嬭瘯涓枃.docx](https://github.com/fguillot/kanboard/files/96880/default.docx)

The filename will change.

**Comment by fguillot** [comment]
I can upload/download documents with filename in Chinese without any problem.

The issue may come from your os/browser. Did you see the correct filename in Kanboard? What browser/os do you use?

**Comment by manboo** [comment]
Yes,

This is the issue come from the ie and edge browser.

It is ok with  chrome and firefox.
