### ISSUE TITLE
pointing database to new version of kanboard

### ISSUE THREAD

**Issue by JMetai** [fguillot/kanboard#1691]
I installed latest version of kanboard. Copied my database which I used it for old version of kanboard to latest version of kanboard. I am getting following error

Internal Error: Unable to migrate database schema: \Schema\version_89 => SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

owner and group changed to apache on kanboard/data and also chmod 777 to db.sqlite file as well. Still I am getting this error. Please help

**Comment by fguillot** [comment]
Seems to be a permission issue, double check the permission/owner of the directory data and the db.

**Comment by tlflow** [comment]
I seem to be getting the same thing. As original post mentioned, chmod 777 for db.sqlite file hasn't helped.
