### ISSUE TITLE
[v1.0.23-fix2] Search mask of board selector not available in board overview

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#1694]
Hi,

when I open the board selector in the top right corner I noticed that the instant search is not available when I am in a project's board/calender/list/gantt view.
It seems however to be available in every other view (Edit task, edit project, dashboard etc.)

**Comment by fguillot** [comment]
If you are talking about the text field inside the top right dropdown, it's appearing only if you have at least 10 items in the dropdown.

**Comment by donpatzone** [comment]
Hah, there are exactly 10 projects I am member of. I removed one for testing and then the search mask was gone in all views. Having 11 projects shows the search mask in all views.
Seems there is an inconsistency at exactly 10 projects.

**Comment by fguillot** [comment]
I just changed the behaviour in the dev branch, now the search box is always appearing in the project selector.

It's more convenient to use especially if you use the keyboard shortcuts, by pressing the key "b" then start to type the first letter of your project and then press enter. So you can switch quickly between projects.

And, yes it was > 10 items to see the text field. On the board view, the project where you are currently is not part of the dropdown, so in your case you were seeing 9 items... Anyway, now the search box is always there.
