### ISSUE TITLE
error after ubgrate to new version 

### ISSUE THREAD

**Issue by flydurov** [fguillot/kanboard#1697]
Hello! 
i have Ubuntu server Apache2 and kanbord 1.0.17
 when i try update to a new version  by instruction i have some error
" Internal Error: PHP extension required: "gd" "

**Comment by BlueTeck** [comment]
So you have to install the php extension "gd" ?!

**Comment by flydurov** [comment]
thanx i instaled it now but start to have another error: Internal Error: Unable to migrate database schema: \Schema\version_82 => SQLSTATE[HY000]: General error: 1296 Got error 64 'Temp file write failure' from InnoDB
could you explain where i can look for  the problem? ihavw MS SQL on other server

**Comment by fguillot** [comment]
This issue is not related to Kanboard but to your Mysql server configuration.
