### ISSUE TITLE
Error Message when changing category on the board

### ISSUE THREAD

**Issue by pchauvier** [fguillot/kanboard#1699]
Hello,
I just upgrade kanboard on the last version.
I still have the same problems since i have installed the version 1.022.
When i want to change category of a task on the board, this error message appears "Internal Error : Controller or method not found for the given url!" and nothing change.
I have to open the task to change the category.
Is there a fix planned to solve this problem ?
Thanks

**Comment by fguillot** [comment]
This problem have already been reported. It's now fixed in the development version et that will be part of the next stable version.

**Comment by fguillot** [comment]
Fix available in 1.0.24

**Comment by pchauvier** [comment]
Thanks a lot.

Philippe


Philippe CHAUVIER
Responsable du Service Infrastructures
Direction Numérique et Logistique
02.40.67.08.99
06.73.74.75.02




>>> Frédéric Guillot<notifications@github.com> 25/01/2016 >>>

Fix available in 1.0.24
