### ISSUE TITLE
Setting owner_id=0 via php api access function updateTask fails

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#1700]
Hi,

I am trying to update the owner of a task from an assigned user back to nobody (owner_id=0) via php updateTask api call, however this api call fails. Updating a task to a different owner_id (!= 0) succeeds however.

**Comment by fguillot** [comment]
It was a bug, it's now fixed in the development branch. Thanks.

**Comment by lehrhardt** [comment]
Confirmed, works again. Great, thx for the quick fix.
