### ISSUE TITLE
api call moveTaskPosition does not work with moving a task to a different project

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#1702]
Hi,

I am trying to use the api call moveTaskPosition via php to move a task from one project to a different one, however this fails. Project id and column_id are right, moving the task via the webinterface succeeds. Is the api call designed for moving tasks between projects?

**Comment by fguillot** [comment]
This api call is used to move a task within the same board, not across projects.

I added 2 new api calls for that:

- [moveTaskToProject](https://github.com/fguillot/kanboard/blob/master/doc/api-task-procedures.markdown#movetasktoproject)
- [duplicateTaskToProject](https://github.com/fguillot/kanboard/blob/master/doc/api-task-procedures.markdown#duplicatetasktoproject)
