### ISSUE TITLE
category selection does not work with lots of categories

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#1703]
Hi,

I have a kanboard project with 39 categories. Using the latest git checkout I have a layout problem now. With Seamonkey and Chrome I can only see the last two categories above the category selection box. All other categories are not available for selection in the display. This used to work with older kanboard versions. Screen resolution is 1920x1080.

**Comment by fguillot** [comment]
Can you make a screenshot please?

**Comment by NinjaPewPew** [comment]
Problably connected with #1738. I assume the box should go down, but goes up instead. Thats why it appears above the selection box.

**Comment by Busfreak** [comment]
real duplicat from https://github.com/fguillot/kanboard/issues/1738
@fguillot @lehrhardt can be closed

**Comment by lehrhardt** [comment]
confirmed. latest git checkout has all categories available again.
