### ISSUE TITLE
Dual logon (sAMAccount  and mail account) in LDAP

### ISSUE THREAD

**Issue by felixaballi** [fguillot/kanboard#1706]
Authentication by sAMAccount and mail isn't working. 
I would like that the user in LDAP can logon with user and mail.
If I write this filter it simply doesn't work.

//Current filter
define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');

//Necessary filter
define('LDAP_USER_FILTER', '(|(&(objectClass=user)(mail=%s))(&(objectClass=user)(sAMAccountName=%s)))'); //I changed the %s for the real one in both cases, anyway it should work.

This filter was tested in LdapSoft LdapBrowser, if at least one of the criteria fits the response the user queried is returned succesfully.

Any help. Great initiative by the way. Thanks.

**Comment by fguillot** [comment]
The ldap filter doesn't support multiple placeholders, only one `%s` is supported.

**Comment by felixaballi** [comment]
Thanks for your attention. 
But you could handle this on code directly. 
I think a much better approach than global variables. 
I have some functions that solve this and you can adapt it.
Perhaps it could work for you. Give more flexibility to Kanboard, excellent tool!

**Comment by fguillot** [comment]
That can be improved very easily in the code, instead of using `sprintf()` I can use `str_replace()` to replace all occurrences.

**Comment by fguillot** [comment]
This feature is now supported in the development branch.
