### ISSUE TITLE
 The session id is too long or contains illegal characters

### ISSUE THREAD

**Issue by he3naika** [fguillot/kanboard#1713]
Ubuntu 13.10 -- 3.11.0-26-generic
php5 -- 5.5.3+dfsg-1ubuntu2.6
php5-sqlite -- 5.5.3+dfsg-1ubuntu2.6
php5-gd -- 5.5.3+dfsg-1ubuntu2.6
php5-json -- 1.3.1+dfsg-2
php5-mcrypt -- 5.4.6-0ubuntu3
data folder is writable

**Comment by fguillot** [comment]
Which version of kanboard are you using and where did you see this error?

**Comment by he3naika** [comment]
kanboard version is v1.0.24
saw error in apache2 error.log (/var/log/apache2/error.log)
Full error mesaage is --- PHP Warning:  session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /var/www/kanboard/app/Core/Session/SessionManager.php on line 48

**Comment by grapeisme** [comment]
@fguillot  @he3naika 
it happens to me, and i changed 'session.use_strict_mode', and it works

ini_set('session.use_strict_mode', '0');            // app/Core/Session/SessionManager.php
