### ISSUE TITLE
no installation doc for opensuse Leap 42.1

### ISSUE THREAD

**Issue by gbn7** [fguillot/kanboard#1714]
Installation instructions for opensuse Leap 42.1 are as follows:

In a terminal, type: 

sudo zypper install php5 php5-sqlite php5-gd php5-json php5-mcrypt php5-mbstring php5-openssl
cd /srv/www/htdocs
sudo wget http://kanboard.net/kanboard-latest.zip
sudo unzip kanboard-latest.zip
sudo chmod -R 777 kanboard
sudo rm kanboard-latest.zip

Now, start kanboard as usual by pointing a browser URL to 127.0.0.1/kanboard

P.S.  If apache will not start in a fresh install of suse Leap 42.1, and if apache startup fails with an error message involving "nagois", try removing the packages nogois and nagois-www.  (This is unrelated to kanboard.)

**Comment by fguillot** [comment]
I added that in the documentation, thanks.
