### ISSUE TITLE
Metrics/reporting feature request

### ISSUE THREAD

**Issue by ryebread157** [fguillot/kanboard#172]
Considering the data for this is already present in kanboard's DB, could some canned reports be created? In the kanban world, these would include visual diagrams for cumulative flow and lead/cycle times. Other useful report lists would be 'completed in the last week' or being able to select a date range of completed tasks. A smaller enhancement in this area would be allow sorting by any column in the completed tasks view, it is currently unable to do this.

**Comment by gmdesousa** [comment]
It would be nice to have a graph saying how many time the tickets are spending on each column.
By type... or by category? What do you think?

**Comment by semka** [comment]
Any news about metrics?

**Comment by BlueTeck** [comment]
There are some analytics since a few month:

http://kanboard.net/news/version-1.0.10

**Comment by semka** [comment]
I was not percise :)
I mean specifically lead and cycle time reports.

**Comment by semka** [comment]
Any news on this? I wrote an ugly scala script for calculating lead/cycle time based on task transitions csv, but I still wish to have it right inside Kanboard.

Dirty script is here: https://gist.github.com/semka/84d01e9c3e086a487572

**Comment by fguillot** [comment]
Lead and cycle time is now available in the development branch.

See https://github.com/fguillot/kanboard/blob/master/docs/analytics-tasks.markdown and https://github.com/fguillot/kanboard/blob/master/docs/analytics.markdown#average-lead-and-cycle-time

Note: It's under testing at the moment.

**Comment by semka** [comment]
Thanks a lot, Frédéric!
