### ISSUE TITLE
remote-login-icons

### ISSUE THREAD

**Issue by TheRojam** [fguillot/kanboard#1732]
how could we add an class of this style-sheets https://necolas.github.io/css3-social-signin-buttons/ in login form?
I've tried to implement it but, i don't know how to add an class (e.g. "btn-auth btn-github")  to the php-link-string.

**Comment by fguillot** [comment]
Just pass the class name to the argument `$class`: https://github.com/fguillot/kanboard/blob/master/app/Helper/Url.php#L45
