### ISSUE TITLE
Kanboard not receiving email via Sendgrid Plugin

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#1734]
Im pulling my hair out.  I have tried every thing I can to get kanboard working with inbound parsing from sendgrid.   Debug is enabled, and I do not see any entries in relation to the sendgrid plugin.  I do see it in the apache access log though.  

167.89.125.224 - - [25/Jan/2016:20:59:23 -0500] "POST /?controller=webhook&action=receiver&plugin=sendgrid&token=12515676e82751a21e9276891f68f4ecfab93777b2efb3dbb290bf380149 HTTP/1.1" 200 17966 "-" "SendGrid 1.0"

or 

167.89.125.248 - - [26/Jan/2016:04:53:01 -0500] "POST /?controller=webhook&action=receiver&plugin=sendgrid&token=12515676e82751a21e9276891f68f4ecfab93777b2efb3dbb290bf380149 HTTP/1.1" 301 7003 "-" "SendGrid 1.0"

So I know sendgrid is reaching my server. in neither situation di a card get created on the intended board.  I am also able to send out emails just fine with send grid.  Also, here are the messages im getting from sendgrid via its activity log.  

Email:test123+test123@mydomain.com
Reason: 301 Moved Permanently
Processed String: Jan 26 03:33
MSGID: 

I have created the ProjectID on different board and have used the format something+projectID@mydoman.com

Am I missing something.

**Comment by seancarson** [comment]
Also, here is my debug log after sending and email to my project

root@www:/var/www/html/kanboard/data# tail debug.log
[2016-01-26 03:56:27] [debug] QUERY_DURATION=0.00073885917663574 ALL_QUERIES_DUR                    ATION=0.0046787261962891
[2016-01-26 03:56:27] [debug] SELECT * FROM "action_has_params"   WHERE "action_                    id" IN (?, ?, ?, ?, ?, ?)
[2016-01-26 03:56:27] [debug] QUERY_DURATION=0.00064802169799805 ALL_QUERIES_DUR                    ATION=0.0053267478942871
[2016-01-26 03:56:27] [debug] SELECT 1 FROM "users"  WHERE "id" = ?
[2016-01-26 03:56:27] [debug] QUERY_DURATION=0.0006868839263916 ALL_QUERIES_DURA                    TION=0.0060136318206787
[2016-01-26 03:56:27] [debug] SQL_QUERIES=6
[2016-01-26 03:56:27] [debug] RENDERING=0.03521990776062
[2016-01-26 03:56:27] [debug] MEMORY=1.79M
[2016-01-26 03:56:27] [debug] URI=/kanboard/?controller=app&action=status&_=1453                    800806520

**Comment by jtourt** [comment]
Hello. My name is Jason. I will assist you with this issue. 

Are you saying that you searched the debug log for 'Sendgrid' and found no entries?

These are the three possible debug lines that are written by the Sendgrid plugin:
- SendgridWebhook: ignored => user not found
- SendgridWebhook: ignored => project not found
- SendgridWebhook: ignored => user is not member of the project

If you found none of the above, then there are other things to consider, such as the subject line is empty.

- Edit the EmailHandler.php file in the plugins/Sendgrid folder.
- Add the following line at the beginning of the receiveEmail function:

$this->logger->debug('SendgridWebhook: verification => in the receiveEmail function');

It should look like this:

```php
public function receiveEmail(array $payload) 
{ 
        $this->logger->debug('SendgridWebhook: verification => in the receiveEmail function');

         if (empty($payload['envelope']) || empty($payload['subject'])) { 
             return false; 
         } 
  
         $envelope = json_decode($payload['envelope'], true); 
         $sender = isset($envelope['to'][0]) ? $envelope['to'][0] : ''; 
```
Send an email in again and check the debug log.  Search for: SendgridWebhook.

Did you find a line now?  If not, we can be confident that the plugin is not being called. That would be a curious head scratcher. But try the steps suggested above and let me know what you find.

**Comment by seancarson** [comment]
So I did what you asked and I still did not see anything close to the Receive Email entries detailed in your previous message.  I ran several combination of grep -a 'SendgridWebhook:' debug.log  along with grep -a 'sendgrid' debug.log and so one and found not corresponding entries to times I sent emails.  I still do however see them in the apache  access log.  

I did notice one thing.  When I would go to Global Settings -> Plugins  I did not see any of my plugins listed intially.  I had to go and change my config file to fix.  I basically removed all of the paths which started like plugins or /data/files   and instead used the __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'debug.log'  terminology.  After I change the three entries. the plugins then appeared in the Settings -> Plugins section.    But even after this I am not receiving any entries in the debug.log nor are tasks being created on board from emails.  

SC

**Comment by seancarson** [comment]
// Enable/Disable debug
define('DEBUG', 'true');

// Debug file path
define('DEBUG_FILE', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'debug.log');

// Plugins directory
define('PLUGINS_DIR', __DIR__.DIRECTORY_SEPARATOR.'plugins');

// Folder for uploaded files
define('FILES_DIR', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'files');

**Comment by seancarson** [comment]
My sending out bound still work fine as well.  This entry comes from a grep of the debug.log looking for sendgrid.  

 8 => 'Access-Control-Allow-Origin: https://sendgrid.com',
  'uri' => 'https://api.sendgrid.com/api/mail.send.json',
[2016-01-29 01:11:11] [debug] Sending email to (My  Correct Email Address) (sendgrid)
[2016-01-29 01:11:11] [debug] HttpClient: url=https://api.sendgrid.com/api/mail.send.json
    8 => 'Access-Control-Allow-Origin: https://sendgrid.com',
  'uri' => 'https://api.sendgrid.com/api/mail.send.json',

**Comment by jtourt** [comment]
As a reference, check out config.default.php.  That file should be your guide on setting the config variables.  It is possible for changes to occur with each release, so it's valuable to compare config.php with config.default.php any time you upgrade.

The values from the current release config.default.php:
```php
// Debug file path 
define('DEBUG_FILE', __DIR__.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR.'debug.log'); 
// Plugins directory 
define('PLUGINS_DIR', 'plugins'); 
// Folder for uploaded files 
define('FILES_DIR', 'data'.DIRECTORY_SEPARATOR.'files'); 
```

- What version of Kanboard are you running?  (Settings / About)  1.0.24 is the latest version.
- What version of the Sendgrid plugin? (Settings / Plugins) 1.0.2 is the latest version.

The plugins API in Kanboard is young. It is considered to be in ALPHA status, and there have been significant changes over the last couple releases. As a general rule, any time there is a new Kanboard release, check the plugins that you are using to see if they have been updated.

In your case, we have confirmed that the Sendgrid receiveEmail function is not being called.  Something basic is not working, 

Double-check that the Kanboard webhook url displayed in Settings > Integrations > Sendgrid matches what you have entered in Sendgrid configuration page.   

And let us know about the version numbers.

**Comment by seancarson** [comment]
The links are correct between sendgrid and kanboard.  I'm currently running kanboard 1.0.23-fix.  And the plugins are Sendgrid 1.0.2 and Budget Planning 1.0.3

I will update to the must recent version of kanboard and see if that helps.

SC


Sent from my BlackBerry - the most secure mobile device - via the T-Mobile Network

**Comment by seancarson** [comment]
So, I created a brand new server and followed the Ubuntu install instructions exactly.  I also used Postmark this time instead.   And now I do see Webhook entries for plugin=postmark.  The problem is now as it was before, tasks are still not being created  on the board.  I have verified that messages are being received and sent off to Kanboard by postmark.  I also added the PostmakWebhook: verification => in the receiveEmail function  and this appears in the debug.log as well.  

But I went a step further.  I Added the Postmak line to other parts of the function to see how it progressed and I didnt see any other beyond the "in the receiveEmail".  See below.  

 public function receiveEmail(array $payload)
    {
       $this->logger->debug('PostmakWebhook: verification => in the receiveEmail function');
         if (empty($payload['From']) || empty($payload['Subject']) || empty($payload['MailboxHash'])) {
            return false;
        }

        // The user must exists in Kanboard
        $user = $this->user->getByEmail($payload['From']);
        $this->logger->debug('PostmakWebhook: verification => User Must Exist Check');
        if (empty($user)) {
            $this->logger->debug('Postmark: ignored => user not found');
            return false;
        }

        // The project must have a short name
        $project = $this->project->getByIdentifier($payload['MailboxHash']);
        $this->logger->debug('PostmakWebhook: verification => Project must have a name Check');

        if (empty($project)) {
            $this->logger->debug('Postmark: ignored => project not found');
            return false;
        }

        // The user must be member of the project
        $this->logger->debug('PostmakWebhook: verification => User must be a member of the project');
        if (! $this->projectPermission->isMember($project['id'], $user['id'])) {
            $this->logger->debug('Postmark: ignored => user is not member of the project');
            return false;
        }

        // Get the Markdown contents
        $this->logger->debug('PostmakWebhook: verification => Get Email Content');
        if (! empty($payload['HtmlBody'])) {
            $htmlConverter = new HtmlConverter(array('strip_tags' => true));
            $description = $htmlConverter->convert($payload['HtmlBody']);
        }
        else if (! empty($payload['TextBody'])) {
            $description = $payload['TextBody'];
        }
        else {
            $description = '';
        }

        // Finally, we create the task
       $this->logger->debug('PostmakWebhook: verification => Task Creation Began');
        return (bool) $this->taskCreation->create(array(
            'project_id' => $project['id'],
            'title' => $payload['Subject'],
            'description' => $description,
            'creator_id' => $user['id'],
        ));
        $this->logger->debug('PostmakWebhook: verification => Task Created');
    }


Here are the two lines in my debug.log after sending two emails properly formatted.  

[2016-02-02 04:54:02] [debug] PostmakWebhook: verification => in the receiveEmail function
[2016-02-02 04:58:39] [debug] PostmakWebhook: verification => in the receiveEmail function

I must Also note that I did get one proper response early

[2016-02-02 04:07:05] [debug] Postmark: ignored => user not found

email format: test+test123@mydomain.com 


Thank You for your time.

**Comment by jtourt** [comment]
Either the FROM is empty, SUBJECT is empty, or MailboxHash is empty.

Modify the beginning of the receiveEmail function to look like this, and then check the debug log after sending in another email:


```php
public function receiveEmail(array $payload) 
{ 
    if (empty($payload['From'])) { 
        $this->logger->debug('Postmark: ignored => From not found');
	return false; 
    } elseif (empty($payload['Subject'])) {
	$this->logger->debug('Postmark: ignored => Subject not found');
	return false; 
    } elseif (empty($payload['MailboxHash'])) {
	$this->logger->debug('Postmark: ignored => MailboxHash not found');
	return false; 
    }
 
    // The user must exists in Kanboard 
    $user = $this->user->getByEmail($payload['From']); 

```

**Comment by seancarson** [comment]
Ok, it now tells me that the 'Postmark: ignored => MailboxHash not found'

**Comment by seancarson** [comment]
After redoing my server and setting this up again I was able to get it working.  Not sure what I did wrong the first time but it is good now.  

Thanks

**Comment by seancarson** [comment]
This is now resolved.  It appears it was related to the Application URL not being set right.  Because I have an sub folder in apache I should have added /kanboard/  to the URL.
