### ISSUE TITLE
Filter drop-down in board view not accessible if longer than screen hight

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#1738]
Hi!

I have about 25 users assigned to one board. In the board view I had to scroll down to select the last few users in the users filter. In kanboard 1.0.24 the **drop-down filter** changed its behaviour to a **"drop-up filter"**. Now I can only reach the last two users.
I didn't find any explanation for this. Any suggestion?

Same server (localhost), same clone of database,
first view, original 1.0.23-fix1,
![1 0 23](https://cloud.githubusercontent.com/assets/12938119/12581616/2695eb74-c438-11e5-982f-579d5b4b1166.jpg)

second view, update to 1.0.24.
![1 0 24](https://cloud.githubusercontent.com/assets/12938119/12581623/307af666-c438-11e5-82f7-82e0acce518b.jpg)

**Comment by Busfreak** [comment]
Addendum:
testet in Firefox 38 and IE 11

**Comment by Busfreak** [comment]
Issue occurred in commit https://github.com/fguillot/kanboard/commit/713113d6c05e7a85d68ad096e25536a0553f5534 "Add dropdown menu for subtasks ".

The fault is in "assets/js/src/Dropdown.js"

@fguillot could you please check and correct? I would like to install 1.0.24 :smile:

**Comment by iaanus** [comment]
Problem also present with Firefox 43 and 44.

**Comment by iaanus** [comment]
I don't think the problem has anything to do with line 24 of file assets/js/src/Dropdown.js, but rather with the if-else block at line 29-34 of that file. That block checks if the dropdown extends down beyond the bottom of the canvas, in which case it displays the dropdown above and upward the anchor point. This behavior is incorrect when the dropdown is tall, since it makes the dropdown extend above the top of the canvas.

**Comment by Busfreak** [comment]
@fguillot 
I found a solution.
The condition, if the menu opens to the top or bottom should also check, if the submenuHeight fits into "ScrollTop + OffsetTop". If not, menu must open to the bottom.

In file assets/js/src/Dropdown.js, line 29, swap the condition "<" to ">" and swap the if and else branch. Then extend the condition "ScollTop + OffsetTop  < submenuHeight".

        if (offset.top + submenuHeight - $(window).scrollTop() < $(window).height() || $(window).scrollTop() + offset.top < submenuHeight) {
            clone.css('top', offset.top + $(this).height());
        }
        else {
            clone.css('top', offset.top - submenuHeight - 5);
        }

**Comment by julesverhaeren** [comment]
Is there a reason that no pull request has been submitted with this patch? just tested it and it seemed to fix the issue

**Comment by Busfreak** [comment]
Because I have no Linux with installed make and yuicompressor and @fguillot has to test my suggestion.

**Comment by julesverhaeren** [comment]
added a pull request with your fix so that fguillot can merge it in a single click

**Comment by Busfreak** [comment]
THX! :smile:

**Comment by fguillot** [comment]
PR merged. Thanks everybody!
