### ISSUE TITLE
task attribute "% finished"

### ISSUE THREAD

**Issue by poikilotherm** [fguillot/kanboard#174]
It would be nice to have a new attribute to a task to track some kind of percent finished.

Maybe on tasks with subtasks this could even be calculated, perhaps weighted with the time tracking values?

**Comment by levlaz** [comment]
I also think that this would be a great addition. :) :+1:

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
I merged the pull-request of @levlaz
