### ISSUE TITLE
Check only in SQLite DB

### ISSUE THREAD

**Issue by owenmica** [fguillot/kanboard#1744]
Is it possible to check for a user account in the SQLite DB instead of searching from the AD each time once all users are authenticated?

**Comment by fguillot** [comment]
The software doesn't synchronize LDAP passwords in the local database. If you would like to go this way, it's probably better to have only local users.

Which problem do you try to solve?

**Comment by owenmica** [comment]
Our AD is quite large and the users I want to make the Kanboard available to is split in two OUs which are a bit far from each other. For now I managed to go around it by making it available for the whole forest. However I cannot make it specifically for those OUs. I was thinking of making it for one OU, make them authenticate for the first time, automatically enter their credentials in the Database along with their hashed password, and then change it and repeat the process for the other OU. Quite a redundant and lame procedure but for User mode I can't think of another way.

**Comment by fguillot** [comment]
How do you handle this situation with other software?
