### ISSUE TITLE
Save LDAP Password

### ISSUE THREAD

**Issue by owenmica** [fguillot/kanboard#1746]
Is it possible to save the user's LDAP password and bcrypt it in the database?

**Comment by fguillot** [comment]
Why? the purpose of LDAP authentication is to avoid to duplicate user credentials everywhere.

**Comment by owenmica** [comment]
The idea is to the the database only once the password is stored.

**Comment by fguillot** [comment]
Sorry, there is no plan to save the LDAP password in the SQL database.
