### ISSUE TITLE
[PLUGIN] [BUG] Mailgun plugin does not well converted from html to markdown

### ISSUE THREAD

**Issue by bdrayer** [fguillot/kanboard#1750]
Hi,

when I send an email to Mailgun (from Outlook or EM Client) , I get something like this on the description : 
test

or

blockquote.cite { margin-left: 5px; margin-right: 0px; padding-left: 10px; padding-right:0px; border-left: 1px solid #cccccc }blockquote.cite2 {margin-left: 5px; margin-right: 0px; padding-left: 10px; padding-right:0px; border-left: 1px solid #cccccc; margin-top: 3px; padding-top: 0px; }.plain pre, .plain tt { font-family: monospace; font-size: 100%; font-weight: normal; font-style: normal;}a img { border: 0px; }body {font-family: Calibri;font-size: 11pt;}.plain pre, .plain tt {font-family: Calibri;font-size: 11pt;}BLOCKQUOTE.cite { PADDING-LEFT: 10px; MARGIN-LEFT: 5px; BORDER-LEFT: #cccccc 1px solid; PADDING-RIGHT: 0px; MARGIN-RIGHT: 0px}BLOCKQUOTE.cite2 { PADDING-TOP: 0px; PADDING-LEFT: 10px; MARGIN-LEFT: 5px; BORDER-LEFT: #cccccc 1px solid; MARGIN-TOP: 3px; PADDING-RIGHT: 0px; MARGIN-RIGHT: 0px}.plain PRE { FONT-SIZE: 100%; FONT-FAMILY: monospace; FONT-WEIGHT: normal; FONT-STYLE: normal}.plain TT { FONT-SIZE: 100%; FONT-FAMILY: monospace; FONT-WEIGHT: normal; FONT-STYLE: normal}A IMG { BORDER-TOP: 0px; BORDER-RIGHT: 0px; BORDER-BOTTOM: 0px; BORDER-LEFT: 0px}BODY { FONT-SIZE: 11pt; FONT-FAMILY: Calibri}.plain PRE { FONT-SIZE: 11pt; FONT-FAMILY: Calibri}.plain TT { FONT-SIZE: 11pt; FONT-FAMILY: Calibri}.shape { BEHAVIOR: url(#default#VML)}o\: { BEHAVIOR: url(#default#VML)}v\: { BEHAVIOR: url(#default#VML)}w\:* { BEHAVIOR: url(#default#VML)}DIV.MsoNormal { FONT-SIZE: 11pt; FONT-FAMILY: "Calibri","sans-serif"; MARGIN: 0cm 0cm 0pt; mso-bidi-font-family: "Times New Roman"; mso-bidi-theme-font: minor-bidi; mso-style-unhide: no; mso-style-qformat: yes; mso-style-parent: ""; mso-pagination: widow-orphan; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: "Times New Roman"; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin}LI.MsoNormal { FONT-SIZE: 11pt; FONT-FAMILY: "Calibri","sans-serif"; MARGIN: 0cm 0cm 0pt; mso-bidi-font-family: "Times New Roman"; mso-bidi-theme-font: minor-bidi; mso-style-unhide: no; mso-style-qformat: yes; mso-style-parent: ""; mso-pagination: widow-orphan; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: "Times New Roman"; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin}P.MsoNormal { FONT-SIZE: 11pt; FONT-FAMILY: "Calibri","sans-serif"; MARGIN: 0cm 0cm 0pt; mso-bidi-font-family: "Times New Roman"; mso-bidi-theme-font: minor-bidi; mso-style-unhide: no; mso-style-qformat: yes; mso-style-parent: ""; mso-pagination: widow-orphan; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: "Times New Roman"; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin}.MsoChpDefault { FONT-SIZE: 11pt; mso-bidi-font-family: "Times New Roman"; mso-bidi-theme-font: minor-bidi; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-fareast-font-family: "Times New Roman"; mso-fareast-theme-font: minor-fareast; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin; mso-style-type: export-only; mso-default-props: yes; mso-ansi-font-size: 11.0pt; mso-bidi-font-size: 11.0pt}DIV.WordSection1 { page: WordSection1}TABLE.MsoNormalTable { FONT-SIZE: 11pt; FONT-FAMILY: "Calibri","sans-serif"; mso-style-parent: ""; mso-pagination: widow-orphan; mso-ascii-font-family: Calibri; mso-ascii-theme-font: minor-latin; mso-hansi-font-family: Calibri; mso-hansi-theme-font: minor-latin; mso-style-name: "Table Normal"; mso-tstyle-rowband-size: 0; mso-tstyle-colband-size: 0; mso-style-noshow: yes; mso-style-priority: 99; mso-padding-alt: 0cm 5.4pt 0cm 5.4pt; mso-para-margin: 0cm; mso-para-margin-bottom: .0001pt}Test

Is there a way to remove the CSS?

The rest of the message (signature in my case) is OK

thanks in advance

**Comment by jtourt** [comment]
I ran into the same issue, and modified the EmailHandler receiveEmail function to make it more to my liking.  

While waiting for an official fix, if you are feeling adventurous, give this a try.  

- Edit /kanboard/plugins/Mailgun/EmailHandler.php
- Replace with the following.

```php
<?php

namespace Kanboard\Plugin\Mailgun;

require_once __DIR__.'/vendor/autoload.php';

use Kanboard\Core\Base;
use Kanboard\Core\Tool;
use Kanboard\Core\Mail\ClientInterface;
use League\HTMLToMarkdown\HtmlConverter;

defined('MAILGUN_API_TOKEN') or define('MAILGUN_API_TOKEN', '');
defined('MAILGUN_DOMAIN') or define('MAILGUN_DOMAIN', '');

/**
 * Mailgun Mail Handler
 *
 * @package  mailgun
 * @author   Frederic Guillot
 */
class EmailHandler extends Base implements ClientInterface
{
    /**
     * Send a HTML email
     *
     * @access public
     * @param  string  $email
     * @param  string  $name
     * @param  string  $subject
     * @param  string  $html
     * @param  string  $author
     */
    public function sendEmail($email, $name, $subject, $html, $author)
    {
        $headers = array(
            'Authorization: Basic '.base64_encode('api:'.MAILGUN_API_TOKEN)
        );

        $payload = array(
            'from' => sprintf('%s <%s>', $author, MAIL_FROM),
            'to' => sprintf('%s <%s>', $name, $email),
            'subject' => $subject,
            'html' => $html,
        );

        $this->httpClient->postForm('https://api.mailgun.net/v3/'.MAILGUN_DOMAIN.'/messages', $payload, $headers);
    }

    /**
     * Parse incoming email
     *
     * @access public
     * @param  array   $payload   Incoming email
     * @return boolean
     */
    public function receiveEmail(array $payload)
    {
        if (empty($payload['sender']) || empty($payload['subject']) || empty($payload['recipient'])) {
            return false;
        }

        // The user must exists in Kanboard
        $user = $this->user->getByEmail($payload['sender']);

        if (empty($user)) {
            $this->logger->debug('Mailgun: ignored => user not found');
            return false;
        }

        // The project must have a short name
        $project = $this->project->getByIdentifier(Tool::getMailboxHash($payload['recipient']));

        if (empty($project)) {
            $this->logger->debug('Mailgun: ignored => project not found');
            return false;
        }

        // The user must be member of the project
        if (! $this->projectPermission->isMember($project['id'], $user['id'])) {
            $this->logger->debug('Mailgun: ignored => user is not member of the project');
            return false;
        }

        // Get the Markdown contents
        // if (! empty($payload['stripped-html'])) {
        //    $htmlConverter = new HtmlConverter(array('strip_tags' => true));
        //    $description = $htmlConverter->convert($payload['stripped-html']);
        // }
        // else if (! empty($payload['stripped-text'])) {
        //    $description = $payload['stripped-text'];

        if (! empty($payload['body-plain'])) {
	        $description = $payload['body-plain'];
	        // JT 2015-10-30: Fix for a problem with mailto formatting.
	        // $description = preg_replace("/\<mailto:(.*?)\>/", "$1", $description);
	        $description = preg_replace("/\<mailto:(.*?)\>/", "", $description);

	        // JT 2015-10-28: Add linebreaks for better looking output in the browser
             // $description = nl2br($description);
        }
        else {
            $description = '';
        }

	   // JT 2015-10-28: Remove reply and forward prefixes from the subject line
	   $simplified_subject = str_replace('FW: ', '', $payload['subject']);
	   $simplified_subject = str_replace('RE: ', '', $simplified_subject);

        // Finally, we create the task
        return (bool) $this->taskCreation->create(array(
            'project_id' => $project['id'],
            'title' => $simplified_subject,
            'description' => $description,
            'creator_id' => $user['id'],
        ));
    }
}
```

**Comment by bdrayer** [comment]
Hi,

Thanks a lot I will try this next week.

An other concern is that it go to the default Swimlane (also if she is hided).

Best regards

**Comment by PatDeLux** [comment]
I tested the provided code: messages from Outlook/Exchange don't arrive at all now. Gmail is still OK.  
I can see the Exchange messages are  delivered in the Mailgun logs , but they don't show up.
I will revert to the original code.

**Comment by PatDeLux** [comment]
The code above works fine!  
At first I thought it was not working at all, but I found it was due to the fact I had deleted the "Exchange user" form the project, and so the tasks wre not showing up at all. I re-added the user, and the content show up ok.  
FYI, Gmail format is kept (bold text...) while Exchange formatting is now lost.

**Comment by bdrayer** [comment]
Duplicate of https://github.com/kanboard/plugin-mailgun/issues/4

**Comment by fguillot** [comment]
Closing this issue, discussion moved to the mailgun plugin bug tracker.

@jtourt I added the subject cleanup part in the master branch of the plugin.
