### ISSUE TITLE
Category label get broken if there's a url on it's description

### ISSUE THREAD

**Issue by Le-R** [fguillot/kanboard#1752]
First of all, thank you for this awesome work!
I just discovery it yesterday and I'm really liking it. :)

So, I noticed that if I put a url inside of the description field of a category, the category label in the board get broken due to the quotes generated by the hyperlink.

Playing around I managed to fix locally, by replacing those additional quotes with `&quot;`
On /app/Template/board/task_footer.php

```
! empty($task['category_description']) ? str_replace("\"", "&quot;", $this->text->markdown($task['category_description'])) : t('Change category')
```
Not sure if it's a proper workaround, but seemed to work. :stuck_out_tongue: 

Once again, thank you for your awesome software! :+1:

**Comment by fguillot** [comment]
It's now fixed in the development version.

Thanks.
