### ISSUE TITLE
remote users

### ISSUE THREAD

**Issue by djsensui** [fguillot/kanboard#1758]
Hi, 

I already setup the LDAP auth to the system and it is working but the user must login first on the system before it can appear on the users list (remote user). 
Is this normal? if not, how can i appear all the users in my LDAP/AD  directory all at once. 

Thanks.

**Comment by fguillot** [comment]
This is the expected behaviour, Kanboard do not synchronize all users at once, only when the user sign in. Otherwise it will take too much time for organization with a large number of users.

**Comment by djsensui** [comment]
How about enabling "Notification" on default?
