### ISSUE TITLE
API methode createLdapUser broken

### ISSUE THREAD

**Issue by elacour** [fguillot/kanboard#1759]
I just upgraded to 1.0.24 and this method no longer works, because:

API::createLdapUser does sptinft of LDAP_USER_FILTER and pass the result to LdapUser::getUser, but this last one do the same and pass again the arg to sprintf and LDAP_USER_FILTER which leads to invalid filter.
Attached patch fixes this.

[0001-Pass-username-only-to-LdapUser-getUser.patch.txt](https://github.com/fguillot/kanboard/files/112015/0001-Pass-username-only-to-LdapUser-getUser.patch.txt)

**Comment by mtruijen** [comment]
createLdapUser function no longer works for me in version 1.0.25. In a previous version (1.0.21) we could pass the default project ID. In the new version of the API this has been eliminated. I found that the documentation as a small type. In the description of the function. There is a comma "," after "my_ldap_user". Would be great if this issue with createLdapUser could be fixed quickly.

**Comment by mtruijen** [comment]
Any news on this? It is a little frustrating that this broke all the sudden in a new release and no updates are posted to fix this.

**Comment by fguillot** [comment]
@elacour I merged your patch in master. This issue is now fixed.

Thanks
