### ISSUE TITLE
Subtask should have a title and a more detailed description

### ISSUE THREAD

**Issue by poikilotherm** [fguillot/kanboard#176]
Sometimes I would like to describe stuff I need to do for a subtask. Writing this into the rather small title text field is not the optimal solution. A description text area which is rendered in a smaller font size and maybe italics but allows a markdown syntax would help with this.

**Comment by okraits** [comment]
For me, a maxlength of 50 for the title is too short, too. I think that doubling the value to 100 would be sufficient for most cases.

**Comment by mnemonicflow** [comment]
+1 for both requests

**Comment by okraits** [comment]
Thank you for referencing my PR :+1:

**Comment by fguillot** [comment]
I increased the max length to 255. If you need more, the database column must be changed for Mysql and Postgres. Otherwise a textarea for a long markdown description can be added.

**Comment by jknapp82** [comment]
>> "Otherwise a textarea for a long markdown description can be added."

+1 :thumbsup:

**Comment by fguillot** [comment]
I don't want to duplicate all feature of tasks to subtasks, so if you need a longer description than 255 characters, use the task description or link the task to multiple tasks.
