### ISSUE TITLE
Allow Language to be fetched or set in ldap mode

### ISSUE THREAD

**Issue by elacour** [fguillot/kanboard#1760]
Would be nice to be able to fetch the user language from an ldap attribute or set a static one. Could be done on config side with something like:

define('LDAP_USER_ATTRIBUTE_LANG', 'lang');

 -> would fetch language value from attribute "lang".

define('LDAP_USER_ATTRIBUTE_LANG', 'static:fr_FR');

-> would set "fr_FR" as language for all ldap users.

this "static:something" configuration style could be extended to other attributes maybe.

or maybe having a global variable to define language for all users?

**Comment by fguillot** [comment]
In the meantime, if everybody are using the same language, you can define the language at the application level in the application settings.

**Comment by fguillot** [comment]
Kanboard 1.0.28 supports the language attribute from LDAP.
