### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by djsensui** [fguillot/kanboard#1761]
It is possible to pull user picture via Active Directory? 
Photo attribute : thumbnailPhoto / jpegPhoto

Thanks.

**Comment by fguillot** [comment]
It's planned when avatar images will be implemented correctly.

**Comment by angystardust** [comment]
I think this can be marked as a duplicate of #126

**Comment by NinjaPewPew** [comment]
:+1:

**Comment by djsensui** [comment]
Hi, 
Loving the 1.0.27 specially that you can now upload profile pictures. 

Hoping for the future release that the avatar images can be pulled thru AD. 
(Photo attribute : thumbnailPhoto / jpegPhoto)

It is possible to disable editing profile by non-admin?

**Comment by rverchere** [comment]
+1, retrieving jpegPhoto from LDAP should be great!

**Comment by fguillot** [comment]
This feature is now available in the development branch: https://github.com/fguillot/kanboard/blob/master/doc/ldap-profile-picture.markdown
