### ISSUE TITLE
Can't inherit abstract function Kanboard\Core\User\UserProviderInterface::getExternalIdColumn() 

### ISSUE THREAD

**Issue by EmFl** [fguillot/kanboard#1763]
Hello,
With v1.0.24 i'm getting this when trying to either link an account to google or authenticate with an already linked account : 
` Fatal error: Can't inherit abstract function Kanboard\Core\User\UserProviderInterface::getExternalIdColumn() (previously declared abstract in Kanboard\User\OAuthUserProvider) in /admin/kanboard/app/User/OAuthUserProvider.php on line 14`

Anyone else seeing something like this ?

Some more info: 
Based on this : http://stackoverflow.com/questions/17525620/php-fatal-error-cant-inherit-abstract-function it could be linked to my php version which is : php53-5.3.3-26.el5_11.x86_64 on centos

See also this : https://3v4l.org/8niN7#v530

Last edit : By commenting out line 21 of file kanboard/app/User/OAuthUserProvider.php ie : 
`//    abstract public function getExternalIdColumn();`
The authentication starts working again.

**Comment by fguillot** [comment]
Github/Google/Gitlab have been pulled outside of the core few days ago and it's working only with the current master branch of Kanboard and the coming version 1.0.25.

It's not expected to work with 1.0.24.

**Comment by EmFl** [comment]
Hello,
I don't see anything in the changelog of v1.0.24 that mentions google authentication is not supported. It was working fine in previous releases. If it's not expected to work in 1.0.24 I guess it should be mentionned somewhere. I'm not using google auth plugin (I can see it will be required for 1.0.25) but standard release code of 1.0.24. Seems strange that this is tagged as "not a bug"

**Comment by fguillot** [comment]
Because this feature is already part of 1.0.24, you don't need a plugin. But with the next 1.0.25, this feature has been moved to a plugin.

**Comment by EmFl** [comment]
Exactly my point, so in 1.0.24 I'm reporting it as bug because it's not working with the php version mentionned in my first comment.

**Comment by fguillot** [comment]
you can now use KB 1.0.25 with auth plugins.

**Comment by jspaans91** [comment]
I've installed version 1.0.25 with auth plugin but I have exactly the same problem.

**Comment by froschdesign** [comment]
@jspaans91 
> with auth plugin

Which one?

It's all there:

- https://github.com/kanboard/plugin-gitlab-auth/blob/master/User/GitlabUserProvider.php#L21
- https://github.com/kanboard/plugin-google-auth/blob/master/User/GoogleUserProvider.php#L21
- https://github.com/kanboard/plugin-github-auth/blob/master/User/GithubUserProvider.php#L21

**Comment by jspaans91** [comment]
Hi, I use the Gitlab Auth plugin.
