### ISSUE TITLE
Plugin request: Rocket chat

### ISSUE THREAD

**Issue by ciroiriarte** [fguillot/kanboard#1766]
Not sure if this is the right channel, but would be nice to have integration for Rocket Chat. We evaluated Mattermost but the lack of LDAP support is a show stopper for us...

**Comment by fguillot** [comment]
I haven't seen any webhook system on their documentation, only a rest api that require 2 http requests to send a message (1 for authentication and another one to send the message).

**Comment by rodrigok** [comment]
@fguillot we have webhooks at Rocket.Chat exactly equals to the Slack webhooks, we don't have a public documentation for it yet, but you can follow the Slack's documentation.

If you want we can deploy an instance in our servers to you be able to test this integrations, or you can install in your machine as well.

Let me know if you have any questions.

Best.

**Comment by fguillot** [comment]
@rodrigok I will try with docker on my own machine. Thanks.

**Comment by fguillot** [comment]
@rodrigok @ciroiriarte I write a new plugin for RocketChat: http://kanboard.net/plugin/rocketchat

Mostly a copy and paste of the Slack plugin.

**Comment by rodrigok** [comment]
@fguillot awesome :)

**Comment by valessiobrito** [comment]
thanks a lot!  :D

**Comment by ciroiriarte** [comment]
That was quick 😊
