### ISSUE TITLE
German translation for colors

### ISSUE THREAD

**Issue by 85pando** [fguillot/kanboard#1767]
In #1725 I proposed some changes for different German translation for some of the colors.

Currently these are the colors from the German translations.php
![kanboard-colors](https://cloud.githubusercontent.com/assets/1187085/12776783/fa47cf7a-ca58-11e5-8eb5-08a2b3ac0d44.png)

The previous discussion was about the shades of green. In my opinion its actually more like:

Light Green -> Grün
Green -> Neon-Grün or Hellgrün
Lime -> Hellgrün or Gelbgrün

Shoutout to @Busfreak @froschdesign

**Comment by Busfreak** [comment]
Ich finde die Benennung der Farben nicht so schwierig, einzig für Lime gibt es verschiedene Möglichkeiten: Lindgrün, Limettengrün. Wie wäre es einfach mit "Limette"?

**Comment by BlueTeck** [comment]
Ich bin für eines dieser Optionen:
* Lindgrün
* Limette
* (Gelbgrün)

**Comment by thob** [comment]
Limmette :1

**Comment by fbartels** [comment]
I would be for "Limette" as well. The rest of the greens should remain as they are.

**Comment by froschdesign** [comment]
"Limette" or "Limettengrün" is good!

> The rest of the greens should remain as they are.

:+1:

**Comment by 85pando** [comment]
Limette(ngrün) would be a solution that tries to stay closer to lime. So that would probably be somewhat preferable.

One thing that still boggles me a little is that in my opinion light green is darker than green in the current setup:

![gruen](https://cloud.githubusercontent.com/assets/1187085/12817737/d7775a50-cb53-11e5-8ad7-eaea060fbc4b.png)

**Comment by froschdesign** [comment]
@85pando 
This is also problem in English.

**Comment by 85pando** [comment]
@froschdesign
Thats true of course. Maybe at some point one wants to revamp the colors again to fix this.

- - - -

So the consensus seems to be __Limette__ for Lime?

**Comment by Busfreak** [comment]
:+1: 
Limette!
Perfect!

**Comment by froschdesign** [comment]
@85pando 
Create a PR with "Limette" and all is fine.

**Comment by nickbe** [comment]
Nennt mich seltsam, aber wieso überhaupt Namen für Farben....?

**Comment by 85pando** [comment]
@nickbe Etwa beim Einrichten der automatischen Aktionen werden nur die Namen angezeigt…

**Comment by nickbe** [comment]
Ah ok. But then it would be better to see the color instead of the color name..
