### ISSUE TITLE
did you plan to add email smtp authorization for remote user? just like ldap

### ISSUE THREAD

**Issue by renothing** [fguillot/kanboard#1768]
did you plan to add email smtp authorization for remote user? just like ldap, I think it's very simple and usefull for most scenario

**Comment by fguillot** [comment]
what do you mean by smtp authorization?

**Comment by renothing** [comment]
remote users from email. just like remote users from ldap

**Comment by fguillot** [comment]
Can you give an example of implementation because I don't get it.

**Comment by renothing** [comment]
in gogs, you can add new authentication source from smtp, just like in attachments

![1](https://cloud.githubusercontent.com/assets/261274/13028557/5d1a293e-d2ad-11e5-9fe4-e542952fba6e.jpg)

![2](https://cloud.githubusercontent.com/assets/261274/13028607/ae2fab7c-d2ae-11e5-900a-6b23ef35821e.jpg)


ref: [https://en.wikipedia.org/wiki/SMTP_Authentication](https://en.wikipedia.org/wiki/SMTP_Authentication)

**Comment by fguillot** [comment]
You can already do that: http://kanboard.net/documentation/email-configuration

**Comment by renothing** [comment]
oh, You didn't understand what I said. **it's not for notification. it's for remote user**. it's a user source, just like ldap
usertype    authentication  source
remote       ldap                  ldap
remote       smtp                 email
local           local                  local
