### ISSUE TITLE
Feature request: exclude closed tasks in iCal-feed

### ISSUE THREAD

**Issue by patrickvanelk** [fguillot/kanboard#1771]
Been checking out Kanban-tools for some time now (Trello, Taiga, etc. etc.) and all of them are missing one or more essential things in my opinion. Last week I started using KanBoard and while I don't think it has the most beautiful UI I've seen, it definitely has the most features/is the most customizable tool. Thank you for KanBoard!

I've added the iCal-feed to Lightning in Fossamail so all my due tasks show up, really nice. Only thing that's missing is an option to exclude the tasks which have been closed. Would be great if you could implement this feature!

**Comment by fguillot** [comment]
With the last development version, only open tasks appear in the ical feed now.

Thanks.

**Comment by patrickvanelk** [comment]
Excellent, thank you!
