### ISSUE TITLE
PHP Notice when category list empty

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#1777]
Hi there,

I have received next error in logs when try to create new task (with checked "Create another task" checkbox) for the project that have not categories:
```text
PHP Notice:  Undefined index: category_id in /app/Controller/Taskcreation.php on line 74
```
Unfortunately I have not time right now to fix it and make pull request, so may be someone will add validation to this line with his pull request. It should be smth like:
```php
    private function afterSave(array $project, array &$values)
    {
        if (isset($values['another_task']) && $values['another_task'] == 1) {
...
            'category_id' => isset($values['category_id']) ? $values['category_id'] : 0,
...
        }
....
    }

```

Thanks! 

P.S.  If this ticket will not found his hero, I will make pull request in a couple of days :)

**Comment by fguillot** [comment]
It's fixed in master. Thanks.

**Comment by orlov0562** [comment]
Thank you for great product and fast feedback!
