### ISSUE TITLE
Add Tasks via List View

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#1778]
Hello,  and thank you for a wonderful kanboard system.  

If possible can you add the following abilities to kanboard.   

1. add New Task "+ Add task" via the List View.  
2. Add "Create another task" checkbox to proposed List View "+ Add task" feature.  

Basically Mirror the Board View "+ Add Task" feature onto the List View.  

Thanks

**Comment by nttict-nick-b** [comment]
This whole view could just be editable like a spreadsheet. It would let you do things like reassign a whole bunch of tasks to another team member. You could sort by team member, then mass reassign.

**Comment by seancarson** [comment]
Good point nttict-nick-b.

**Comment by fguillot** [comment]
Adding tasks via the list view is now available in the development branch.
