### ISSUE TITLE
Hid a column and can't show it anymore

### ISSUE THREAD

**Issue by victornoel** [fguillot/kanboard#1781]
Hi,

I hid one of the column in the board view and I can't get it to be shown anymore, isn't there a missing button or something like that?

Version 1.0.24 with php7 and firefox 44…

**Comment by victornoel** [comment]
I tried with Chromium, and I get it: there is a button to show it, but it doesn't appear in firefox...

**Comment by fguillot** [comment]
Just click on the column title.

**Comment by victornoel** [comment]
Of course I tried clicking everywhere, but there is clearly something wrong with the UI in FF, I will make a screenshot on Monday. Also it is generally much slower in FF than in Chromium...

**Comment by victornoel** [comment]
Well, no, I'm crazy, sorry :)
