### ISSUE TITLE
Access own class from within template

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#1782]
Hello,
I have a question.
In a template, I can access all classes from the directory Helper with calling $this->class->function.
My own classes I can call with $this->container['classxx']->function but not with $this->classxx->function.
Then comes PHP error:
Fatal error: Class '\Kanboard\Helper\Classxx' not found in ...\kanboard\app\Core\Helper.php on line 65.

Why is this so and am I on the right way?

THX!

**Comment by fguillot** [comment]
Without context, it's hard to help, provide an example of code, please.

**Comment by Busfreak** [comment]
Hello Frédéric,
thanks for your help!

Very simple example, using the hook 'template:analytic:sidebar' echoing 'Hello' inside the sidemenu by calling a function SayHello in own Model.
Using fresh KB 1.0.25.

Plugin.php:
```<?php
namespace Kanboard\Plugin\Hello;
use Kanboard\Core\Plugin\Base;
class Plugin extends Base
{
    public function initialize()
    {
        $this->template->hook->attach('template:analytic:sidebar', 'Hello:analytic/sidebar');
    }
    public function getClasses()
    {
        return array(
            'Plugin\Hello\Model' => array(
                'Hello'
            )
        );
    }
}
```

Hello.php (Model):
```
<?php
namespace Kanboard\Plugin\Hello\Model;
use Kanboard\Model\Base;
class Hello extends Base
{
    public function SayHello()
    {
        return 'Hello';
    }
}
```

Working template file with call of function 'SayHello'
sidebar.php:
```
<?php echo $this->container['hello']->SayHello(); ?>
```
![sayhello1](https://cloud.githubusercontent.com/assets/12938119/12894572/cd301496-ce97-11e5-9db7-2a0cabc7aece.jpg)


Template file throwing error calling function 'SayHello'. Here KB tries to find it in the Helper namespace.
sidebar.php:
```
<?php echo $this->hello->SayHello(); ?>
```
![sayhello2](https://cloud.githubusercontent.com/assets/12938119/12894579/d2b426b4-ce97-11e5-873a-ec5f5622a64a.jpg)

**Comment by Busfreak** [comment]
Hello @fguillot 
I have to ask again.
I need to call my own function from within a template. The template is injected with a hook, so I can't give values from my controller to the template.

Could it be a way to load a custom helper class?
How could I do this? With the function getClasses(), I only can load custom models, right?

**Comment by fguillot** [comment]
That won't works from a template. If you do `$this->something->method()` that will load a helper class (Kanboard\Helper). I need to improve this part to be able to load custom helpers.

However, you should be able to generate a link in the sidebar template: `'Hello:analytic/sidebar'`. Then this link can point to a controller in your plugin, from there you can use your model and render another template that generate the right part of the page.

Have a look to the plugin Budget, it's mostly the same approach.

**Comment by Busfreak** [comment]
Hello @fguillot 

Thank you for your help!
I don't know if it is a bug or a feature, but if I do something like
`$this->NameOfHelper->MyModel->MyFunction()`
from within a template, it will call MyFunction from MyModel without an error.
NameOfHelper is the name of any existing helper :eyes:

**Comment by fguillot** [comment]
Yes it works too but this part need to be improved.

**Comment by BlueTeck** [comment]
I have a similiar problem and can't get it work, maybe you could help me:

It says "Internal Error: Identifier "container" is not defined." and I can't find my error:
https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/Template/task_file/images.php#L4

Plugin.php: https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/Plugin.php
Model: https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/Model/Coverimage.php

**Comment by Busfreak** [comment]
Hi Timo,

the construct $this->container['MyModel']->MyFunction()
doesn't work anymore, I think since 1.0.26. But you can try
$this->AnyExistingHelper->MyModel->MyFunction()

I used it in my color-extension:
https://github.com/Busfreak/kanboard-color_filter/blob/master/Template/task/color_picker.php#L2

I thought about initiating my own container in the helpers, something like
https://github.com/fguillot/kanboard/blob/2e320ceeadf5e134352a9bb83efff93964a40f81/app/ServiceProvider/HelperProvider.php

but this is still only a thought...

Hope that helps :-)
Martin

**Comment by BlueTeck** [comment]
Thx that is working, but the doc needs a change then: https://github.com/fguillot/kanboard/blob/master/doc/plugin-registration.markdown#dependency-injection-container

**Comment by Busfreak** [comment]
You are perfectly right, @fguillot said, he has to change the helper system to load custom helpers.
I haven't found out why $this->container[] doesn't work anymore in the templates.
I think, we can change the documentation, when calling own classes/functions works in templates without this workaround.
