### ISSUE TITLE
Kanboard on hosted webspace

### ISSUE THREAD

**Issue by brandy000** [fguillot/kanboard#1784]
I want to install kanboard on an hosted webspace - is this possible?

**Comment by BlueTeck** [comment]
Should be possible, check this specs: https://github.com/fguillot/kanboard/blob/master/doc/requirements.markdown

**Comment by brandy000** [comment]
But I have installed it alread and I only get: Internal Error: PHP extension required: "pdo_sqlite"

What does it mean?

**Comment by BlueTeck** [comment]
What database is availiable? Mysql and/or sqlite? Is there an option to enable php extensions?

Or could you give us the link of your hoster?

**Comment by kiney** [comment]
The vast majority of webhosts offer MySQL, so you should probably go with that.
http://kanboard.net/documentation/mysql-configuration

**Comment by gzcarlos** [comment]
But if I just want to run Kanboard in default dbms, like SQLite, what should I Do.
For example the official Doc page says SQLite is the default database used in Kanboard, and the db file should be located on "../kanboard/data", but on source files, there is not such a file.

**Comment by rautamiekka** [comment]
^ Of course the SQLite db ain't in the source files cuz that'd be 100% pointless bloating, 1 reason being SQLite is 99% binary, it's auto-created according to the code shipped with Kanboard.

**Comment by gzcarlos** [comment]
but why does we get this error.
FIY: Followed the installation steps for Windows - Apache
https://kanboard.net/documentation/windows-apache-installation

**Comment by kiney** [comment]
which error exactly do you get?

**Comment by gzcarlos** [comment]
after lauching the app (localhost:port/kanboard) getting this error

> Internal Error: PHP extension required: "pdo_sqlite"

**Comment by rautamiekka** [comment]
^ SQLite PDO driver for your PHP version not installed. Talk to your support.

**Comment by kiney** [comment]
@gzcarlos to clarify: do you try to install on hosted webspace (the original question) _or_ on your own windows machine?
I ask because hosted webspace on windows is very uncommon.

If you try to install on hosted webspace i strongly recommend to use whatever database your provider offers and supports(!), probably MySQL.

**Comment by gzcarlos** [comment]
@kiney It's in my own machine. So I'm the one responsible for its installation right now.

**Comment by HourGlss** [comment]
if you have mysql server. change config.default.php to config.php change the DB_DRIVER to mysql, fill in the username, password. host name and db name. Make sure you make the db with that name.

Works. I literally just did it.

**Comment by kiney** [comment]
@HourGlss as i understand @gzcarlos does currently not have a MySQL Server.

@gzcarlos then you probably need to install sqlite and the pdo driver for sqlite. But I cant't help you with details on windows... If your setup is multi-user you should install a "real" database server.

Note that the original topic of this issue is installation on hosted webspace.

**Comment by HourGlss** [comment]
@kiney it's also top result on google for this issue, so i would suggest allowing the comments as ANYONE who has this problem, hosted or not, is going to get this result.

**Comment by rautamiekka** [comment]
@gzcarlos Go to your `php.ini`, find these lines
```
;extension=php_pdo.dll
;extension=php_pdo_sqlite.dll
```
and remove the leading semicolon. On my XAMPP installation the first line doesn't exist, so if that's not there don't worry.

**Comment by gzcarlos** [comment]
Well.. solved it with @rautamiekka. srry for causing such a trouble
Just added the , 'cause it was not there (even it is not in the dll dir of php)
> extension=php_pdo.dll

Just after that the error stopped appearing,  BUT, just got this
> Internal Error: PHP extension required: "openssl"

**Comment by rautamiekka** [comment]
^
>Internal Error: PHP extension required: "openssl"

Similar deal, but this time you're not told it's prefixed with `php_`:
`extension=php_openssl.dll`

**Comment by gzcarlos** [comment]
Ready. 
1. Kept this line as it follows:
> extension=php_openssl.dll
2. Downloaded the `php_pdo.dll` from the web
3. Restarted the Apache Lounge.
4. Enjoyin it

Ty guys!
