### ISSUE TITLE
No email notification of comment to commenter himself

### ISSUE THREAD

**Issue by d4rk5eed** [fguillot/kanboard#1787]
Steps:
1. Write comment to task with `@` sender`s login of myself 
2. Send this comment

Expected:
I expect to have an email notification with this comment

Actual:
No notification

Does it look like a bug?
Or should we do more subtle notification setting? E.g. "send notification of myself"

**Comment by fguillot** [comment]
You won't receive any notification for stuff done by yourself.

**Comment by d4rk5eed** [comment]
It makes me upset. I need to track my comments and the best for me is tracking via email
