### ISSUE TITLE
Update 1.0.18 -> 1.0.24 Duplicate Column with postgres

### ISSUE THREAD

**Issue by kiney** [fguillot/kanboard#1789]
after Updating 1.0.18 -> 1.0.24 I get:
`Internal Error: Unable to migrate database schema: \Schema\version 66 => SQLSTATE[42701]: Duplicate column: 7 FEHLER: Spalte „description“ von Relation ...`

there was something about "swimlane" after that, but my clipboard history only contains the error message so far.

(for some reason the error message partly german, partly english. "FEHLER"="ERROR", "Spalte"="Column", "von"="from")

After refreshing the page everything seems ok.
So my most important question here is: is it safe to continue using the system now? is there risk of data loss?
I still have a backup I made directly before the upgrade.

System:
php 5.6.17 (php-fpm)
nginx 1.6.2
postgresql 9.4.5

**Comment by kiney** [comment]
A short update: I just continued using the Kanboard instance without restoring the backup. No further problems so far.

**Comment by fguillot** [comment]
I cannot reproduce your issue but since the time you opened this ticket, the schema migration mechanism have been improved to more reliable.

If you still have the issue, unfortunately you will probably need to fix the SQL manually.
