### ISSUE TITLE
On Ubuntu 14.04 LTS -> no rewrite?

### ISSUE THREAD

**Issue by borgrat** [fguillot/kanboard#1790]
Hello,

on an VPS Ubuntu 14.04 some links doesn't work correctly:

Works:
        <a href="/?controller=analytic&amp;action=tasks&amp;project_id=1" class="" title="" >Analytics</a>    

Doesn't work:
        <a href="/export/tasks/1" class="" title="" >Exports</a>    </li>
        <a href="/project/1" class="" title="" >Settings</a>    </li>

Could you help me please? I'cant enter my Tasks 

thx

Heiko

**Comment by fguillot** [comment]
The routes was missing, just upgrade Kanboard.
