### ISSUE TITLE
adding start date and estimated time

### ISSUE THREAD

**Issue by sstecker** [fguillot/kanboard#1791]
I am using the api json to insert new tasks from our erp system (ms sql) with python 3.5  with kanboard on MySQL. I'm using pythons requests to add tasks.   currently have the tasks being created if they do not exist.  I would like to add in the tasks table date_started and time_estimated.  I am updating directly in the MySQL tasks table but having an issue with the date_started.  what format do you use in the tasks date_started column?

**Comment by fguillot** [comment]
unix timestamp

**Comment by sstecker** [comment]
thank you. got it working.
