### ISSUE TITLE
Plugin thumbnail wouldn't show

### ISSUE THREAD

**Issue by liladani** [fguillot/kanboard#1792]
There seems to be an error in generating the url. Perhaps is supposed to generate a absolute path but it there might be an issue when using it under a subdomain?
![kanboard_minor_bug](https://cloud.githubusercontent.com/assets/7465227/12873897/61dda916-cdc9-11e5-95fd-c56ecf2fc4af.jpg)

**Comment by fguillot** [comment]
I fixed the issue in the plugin. There was a typo in the url (extra useless slash): https://github.com/kanboard/plugin-gitlab-webhook/commit/fd174c46ea744151e0fc74fa76cd1c9fd76b5e90

Thanks.

**Comment by liladani** [comment]
Thanks!
