### ISSUE TITLE
Itsn't possible to move task to another project's custom swimlane

### ISSUE THREAD

**Issue by d4rk5eed** [fguillot/kanboard#1800]
Steps:
- Select task
- Select Actions -> Move to another project
- Select Project in drop-down list
- Select Swimlane in drop-down list

Expected: 
I can select Swimlane assigned to project from drop-down

Actual: 
I see only standard swimlane, though there is no such one in project.

Seems to be regress as it wasn't reproducible some time ago

![kanboard2](https://cloud.githubusercontent.com/assets/4236587/12883296/08324ec2-ce68-11e5-872f-452e11843b49.png)

**Comment by bdrayer** [comment]
I also get a problem there with the move to other project action. I have 4 Swimlane (3 custom + 1 default) and get only 3 of them (2 custom + 1 default).

**Comment by fguillot** [comment]
This issue is now fixed in the development version.

Thanks.

**Comment by d4rk5eed** [comment]
Thanx!
