### ISSUE TITLE
[Bug] Notice: Undefined variable

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#1801]
Hello,

I have found new one notice:
```
Notice: Undefined variable: redirect in /app/Template/subtask/table.php on line 61
```

It happens when I try to mark sub-task as checked with checkbox in "Title" column of "Sub-Tasks" table.

KB version: v1.0.25-8-g8e6251e

**Comment by fguillot** [comment]
Should be fixed in master. Thanks.

**Comment by orlov0562** [comment]
Thank you!

**Comment by robjurd** [comment]
Still an issue in v1.0.25
