### ISSUE TITLE
Can't create a task, wrong modal windows appear...

### ISSUE THREAD

**Issue by dantahoua** [fguillot/kanboard#1802]
Hello.
When clicking on the "+" for creating a new task the wrong modal windows appears. It's the modal show all my stuff ans search box...
When I press "n" on the keyboard the good modal appear BUT when I save the task, nothing save and it go to the "search/my task" modal windows...
I tried to enable debug but I don't see any revelant stuff in the debug.log, just regular Query. I do not have any error in the console also.
Here is my phpinfo: http://kanboard.lesaintdev.com/phpinfo-kan.php
I can create you an access if you want to see by yourself! :)

Here is the GET I gat when clicking on the '+'
http://kanboard.lesaintdev.com/?controller=taskcreation&action=create&project_id=1&column_id=1&swimlane_id=1

And here is the response:

`<div class="search">
    <form method="get" action="/" class="search">
        <input type="hidden" name="controller" id="form-controller" value="search"/>        <input type="hidden" name="action" id="form-action" value="index"/>        <input type="text" name="search" id="form-search"  class="form-input-large" placeholder="Rechercher">    </form>

    <div class="dropdown filters">
    <i class="fa fa-caret-down"></i> <a href="#" class="dropdown-menu">Filtres</a>
    <ul>
        <li><a href="#" class="filter-helper filter-reset" data-filter="" title="Raccourci clavier : « r »">Réinitialiser les filtres</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open assignee:me">Mes tâches</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open assignee:me due:tomorrow">Mes tâches qui arrivent à échéance demain</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open due:today">Tâches qui arrivent à échéance aujourd&#039;hui</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open due:tomorrow">Tâches qui arrivent à échéance demain</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open due:yesterday">Tâches qui sont arrivées à échéance hier</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:closed">Tâches fermées</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open">Tâches ouvertes</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open assignee:nobody">Non assignées</a></li>
        <li><a href="#" class="filter-helper" data-filter="status:open category:none">Aucune catégorie</a></li>
        <li>
            <a href="/documentation/search" class="" title='' target="_blank">Voir la syntaxe pour la recherche avancée</a>        </li>
    </ul>
</div>
</div>

<div class="page-header">
    <h2><a href="/dashboard/1/projects" class="" title='' >Mes projets</a> (1)</h2>
</div>
    <table class="table-fixed table-small">
        <tr>
            <th class="column-5"><a href="/?controller=app&amp;action=index&amp;pagination=projects&amp;user_id=1&amp;page=1&amp;order=id&amp;direction=ASC" class="" title='' >Id</a></th>
            <th class="column-3"><a href="/?controller=app&amp;action=index&amp;pagination=projects&amp;user_id=1&amp;page=1&amp;order=is_private&amp;direction=ASC" class="" title='' ><i class="fa fa-lock fa-fw" title="Projet privé"></i></a></th>
            <th class="column-25">&#9650; <a href="/?controller=app&amp;action=index&amp;pagination=projects&amp;user_id=1&amp;page=1&amp;order=name&amp;direction=DESC" class="" title='' >Projet</a></th>
            <th>Colonnes</th>
        </tr>
                <tr>
            <td>
                <a href="/board/1" class="dashboard-table-link" title='' >#1</a>            </td>
            <td>
                            </td>
            <td>
                                    <a href="/gantt/1" class="dashboard-table-link" title='Diagramme de Gantt' ><i class="fa fa-sliders fa-fw"></i></a>                
                <a href="/list/1" class="dashboard-table-link" title='Liste' ><i class="fa fa-list"></i></a>&nbsp;
                <a href="/calendar/1" class="dashboard-table-link" title='Agenda' ><i class="fa fa-calendar"></i></a>&nbsp;

                <a href="/board/1" class="" title='' >Projet test</a>                                    <span class="tooltip" title='&lt;p&gt;Ceci est un test&lt;/p&gt;'>
                        <i class="fa fa-info-circle"></i>
                    </span>
                            </td>
            <td class="dashboard-project-stats">
                                    <strong title="Nombre de tâches">0</strong>
                    <span>En attente</span>
                                    <strong title="Nombre de tâches">0</strong>
                    <span>Prêt</span>
                                    <strong title="Nombre de tâches">0</strong>
                    <span>En cours</span>
                                    <strong title="Nombre de tâches">0</strong>
                    <span>Terminé</span>
                            </td>
        </tr>
            </table>

    <div class="page-header">
    <h2><a href="/dashboard/1/tasks" class="" title='' >Mes tâches</a> (0)</h2>
</div>
    <p class="alert">Il n&#039;y a rien d&#039;assigné pour vous.</p>
<div class="page-header">
    <h2><a href="/dashboard/1/subtasks" class="" title='' >Mes sous-tâches</a> (0)</h2>
</div>
    <p class="alert">Il n&#039;y a rien d&#039;assigné pour vous.</p>
`
Thanks

**Comment by fguillot** [comment]
Just check if everything is installed correctly, should works. Otherwise post a bug report with all the information to reproduce the issue.

**Comment by dantahoua** [comment]
Ok I will because it's really weird... Works great on my local web server, tried different PHP version, no problem, so maybe the Apache version is the culprit...
