### ISSUE TITLE
Automatic color assignment by column (sometimes?) doesn't work

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1803]
I'm a bit puzzled by this as I've seen it sometimes work, sometimes not. As I kept adding two more rules, it pretty much stopped working. Could it have something to do with the column names?

Here's my current setup:

![automated column-based colors](https://cloud.githubusercontent.com/assets/479401/12892717/6f442868-ce5b-11e5-806f-670ad6486b64.png)

This is Kanboard 1.0.24

**Comment by fguillot** [comment]
Do you still having the issue with the latest version?

**Comment by nekohayo** [comment]
Interesting, with 1.0.27 it seems to work fine now. Might be just luck, unless you actually changed code related to this in recent times?

**Comment by SchmilK** [comment]
I believe I found the reason this is not working.

If you run this:
**sed 's/^\([^:]*\):.*$/crontab -u \1 -l 2>\&1/' /etc/passwd | grep -v "no crontab for" | sh**

The first thing listed should be 
# Kanboard Management Tasks
0 8 * * * /var/www/html/kanboard/cron-tasks.sh 0

Notice the 0 at the end, changing that to 1 and now my columns are changing color.
