### ISSUE TITLE
v1.0.25 feedback

### ISSUE THREAD

**Issue by jtourt** [fguillot/kanboard#1808]
I like many of the changes in v1.0.25, but I'm not a fan of others.

- Add task priority configurable by project
Can this be changed to: "Show priority on card only when priority is not the default (hide P0 text)."  P0 showing on all cards is distracting.  Thankfully there is a way to disable the priority feature.

- Change sidebar style
Seems non-elegant for the text to jump to another position when the cursor gets near.  I'll get used to it.

- Add dropdown menu with inline popup for all task actions
All of the things that I used to use frequently to make task adjustments have been moved to under the Actions menu. Each task adjustment now requires going back to the Actions menu again and again.  Actions --> Edit the task.  Actions --> Edit the description.  Actions --> Add a comment.  Actions --> Attach a document.
Previously it was easier to make multiple modifications to a task, without needing to click on Actions in between each change.  (Actions) Now my (Actions) day will (Actions) be like (Actions) this.  I guess (Actions) I'll get used (Actions) to it.

**Comment by tortue-geniale** [comment]
Hi,

I test the new release.
I 've one problem on Kanban.

I see the priority. But every task show theirs contents and definition. The kanban is loaded and illegible.
I restart apache2. I search configuration on Kanboard. Damned ! Snif :(

**Comment by Chaosmeister** [comment]
> Change sidebar style
Seems non-elegant for the text to jump to another position when the cursor gets near. I'll get used to it.

maybe you could keep the textposition constant and just blend in the " | " on mousehover.

> Add dropdown menu with inline popup for all task actions

This was a pretty big change for me too.

if you could extend the defaults with comments and attachments like
![image](https://cloud.githubusercontent.com/assets/13346344/13046974/3e3cc1a4-d3dc-11e5-91c4-8beaf0402142.png)

i would be satisfied though.

**Comment by fguillot** [comment]
v1.0.27 has a better user interface. Most of your comments have been taken into consideration.
