### ISSUE TITLE
[Q] rename 'Category' on a per project basis

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1812]
I want to use KB for managing sales pipelines. Since there's no easy way to introduce a DB of contacts I figured to use the categories for that matter. if would be helpful to rename **Category** to **Contact** while still keeping it for other projects. Any idea how to this on a per project basis.
Thanks

**Comment by Busfreak** [comment]
You can create a plugin (http://kanboard.net/documentation/plugins), using ProjectMetadata (http://kanboard.net/documentation/plugin-metadata).
Then you attach your own template to the hook 'template:project:sidebar' (http://kanboard.net/documentation/plugin-hooks) and with this you open your own form for editing the ProjectMetadata.
Overwrite the template 'Template\project\filters.php' with a copy, overwriting the original with setTemplateOverride (http://kanboard.net/documentation/plugin-overrides).
Change your copied template on line 94 and overwrite the t('Categories') with your own function reading the new Category name from the database.
That's it :smile:

**Comment by thob** [comment]
Thanks. It sounds cool but way over my head :-(

**Comment by Busfreak** [comment]
Wait a moment...

**Comment by Busfreak** [comment]
try this one https://github.com/Busfreak/Category_label

**Comment by thob** [comment]
Nice. checking out over there
