### ISSUE TITLE
Problem with Category filter

### ISSUE THREAD

**Issue by Thomas-CRf** [fguillot/kanboard#1813]
Hello,

I'm on the last version (1.0.25) since today and, when I click in a project on the category button in order to apply filter, the list is opened toward the up of the screen and not toward the bottom. Therefore, i cannot scroll (up) to see and click on them. I can only see the last two of them.

We have almost 100 category in our project.

Thank you in advance.

Thomas

**Comment by Busfreak** [comment]
Duplicate with https://github.com/fguillot/kanboard/issues/1738

**Comment by fguillot** [comment]
Closing duplicate.
