### ISSUE TITLE
[question] can a plugin php version differ?

### ISSUE THREAD

**Issue by liladani** [fguillot/kanboard#1816]
If I'd like to make a plugin (public) which would have it's own dependencies that require higher PHP version than 5.3 is that possible to make it so?

**Comment by froschdesign** [comment]
@liladani 
- PHP 5.3 and 5.4 are dead!
- 5.5 is outdated
- …

look at [PHP Supported Versions](http://php.net/supported-versions.php)

**Comment by liladani** [comment]
@froschdesign 
You are right, I personally wouldn't use anything below 5.6 for a new project.
Kanboard however offers backwards compatibility till 5.3.3+.
So I'd like to know if it is allowed for a plugin to increase the min PHP version (in this case to 5.5).

And if so where should such check occur? 
I saw that in the Plugin class there is the initialize method... should that throw an exception?
isn't that already too late for a plugin not to cause problems....

Or simply put the requirements into the plugins README and then you loose if you TL;DR; -t?

**Comment by BlueTeck** [comment]
I would think, that the readme should be enough.

**Comment by froschdesign** [comment]
@liladani 
> You are right, I personally wouldn't use anything below 5.6 for a new project.

:+1: 

> Or simply put the requirements into the plugins README…

I think, readme is good.

**Comment by liladani** [comment]
fine with me.
