### ISSUE TITLE
Keyboard Shortcuts on Task Page

### ISSUE THREAD

**Issue by jeffshieldsdev** [fguillot/kanboard#1818]
Is it possible to add some keyboard shortcuts to the Task page? For instance:

E = Edit the task
C = Add a comment
S = Add a subtask

Thank you.

**Comment by BlueTeck** [comment]
C and S are already used:

![image](https://cloud.githubusercontent.com/assets/1961634/12952259/295aa7b6-d016-11e5-9ff2-4f09cb71e083.png)

**Comment by jeffshieldsdev** [comment]
They have no function on the Task page though.

**Comment by nttict-nick-b** [comment]
Perhaps all those fields should just be in-place editable? How often would you come to the task view without the intention of editing something?

**Comment by fguillot** [comment]
Those keyboard shortcuts are now available on the task view page (master branch).
