### ISSUE TITLE
[UploadFile] custom size 

### ISSUE THREAD

**Issue by tortue-geniale** [fguillot/kanboard#1822]
Hello the team,

I've one question about this excellent kanban tool.
In my team's project, i use files which a size over 2M.

Have you a recipe to custom this value ?
possible to set a variable in config.php (on the app's root )

Best regards.

**Comment by fguillot** [comment]
The size is not limited by Kanboard but by your web server/php configuration.

**Comment by tortue-geniale** [comment]
Thanks a lot !
For others: I find it on /etc/php5/..../php.ini  on a Debian Dist :)
