### ISSUE TITLE
Filter removing shows empty notice block

### ISSUE THREAD

**Issue by tvriend** [fguillot/kanboard#1825]
Couldn't find an earlier report, but if double, please close this one.

Version: 1.0.25
Database: postgres
Tested browsers: Safari 9.0.3, Firefox 43.0.4, Chrome 48.0.2564.97

When i remove a custom filter the screen greys out and shows a white notification box without any text.
I need to refresh the browser to go back to the screen.
The custom filter does get removed.

**Comment by fguillot** [comment]
Can you make a screenshot?

**Comment by tvriend** [comment]
Sorry for the late reply
Here is the screenshot

I create a customer filter named "test" with filter "status=open" (without quotes)
Then i clicked the arrow down where you can remove or edit the filter and clicked remove.
The screenshot is what you see after clicking the "remove" button in Safari, Firefox and chrome

<img width="819" alt="screen shot 2016-02-12 at 14 34 37" src="https://cloud.githubusercontent.com/assets/13728151/13008298/cffe9e08-d195-11e5-82c1-14fb8afd8e0d.png">

**Comment by nttict-nick-b** [comment]
I can reproduce. Investigating.

**Comment by nttict-nick-b** [comment]
It's as if the confirmation thing isn't working. The filter actually gets deleted without confirmation.

**Comment by nttict-nick-b** [comment]
Fixed and created pull request - awaiting verification and merge by @fguillot

**Comment by fguillot** [comment]
I merged the PR of @nttict-nick-b in master.

Thanks everybody.

**Comment by tvriend** [comment]
Thanks for fixing guys, will test once in production release :)
