### ISSUE TITLE
[Task] tag

### ISSUE THREAD

**Issue by tortue-geniale** [fguillot/kanboard#1827]
Hi,

Question or issue.
I don't find item about this topic.
Is it possible to have tags on task ?

It is useful to research task about a special topic.
In my case with a team (20p), we have for example: a task category **SysAdmin **with tags **Linux** **kernel** **addmods**...
In then it's easy to find some tasks with tags. on the time, you can build a **knowledge database**.

Possible or not ? :)

**Comment by BlueTeck** [comment]
see https://github.com/fguillot/kanboard/issues/646

**Comment by fguillot** [comment]
Closing duplicate.
