### ISSUE TITLE
Attachment size limited by nginx configuration resulting in upload error

### ISSUE THREAD

**Issue by perburn** [fguillot/kanboard#1829]
The docker setup in v1.0.25 switched from Apache to Nginx.

Upload size in the PHP configuration is set to 30mb and also being shown in the Kanboard UI with 30mb.
 
However nginx configuration client_max_body_size is left at the default value, which is 1mb, (see http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).

Therefore all uploads with files larger then 1mb result in a nginx "413 Request Entity Too Large" error message.

**Comment by nttict-nick-b** [comment]
I made the change and submitted a pull request

**Comment by fguillot** [comment]
PR merged. Thanks!
