### ISSUE TITLE
1.0.25 - Issue with Duplicate/Move task to different project

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#1832]
Hi,

When I try to move or copy a task from one project to another and I get the menu, I cannot choose the swimlane of the destination project, where the task should be moved to. 
The name of the swimlane I see is ___Progress___, which I have not declared anywhere. And no matter, which project I would choose the name stays the same.
When I finish the task copy/move operation it will be put into the default swimlane of the destination project, even if it is disabled.

I would have to enable the swimlane and move it to the correct one.

Regards

**Comment by balatone** [comment]
I seem to have a similar problem. I can duplicate an item as long as I don't change the project in the "Move the task to another project" dialog. When I select another project in the dialog it doesn't seem to update the Swimlane, Column or Category in the selection for that corresponding project.

**Comment by fguillot** [comment]
This issue is now fixed in the development version.

Thanks.

**Comment by fguillot** [comment]
Duplicate with #1800
