### ISSUE TITLE
Sub-tasks on Gantt

### ISSUE THREAD

**Issue by eSkiSo** [fguillot/kanboard#1833]
Hello, can we have sub-tasks appearing on the Gantt chart?

**Comment by julesverhaeren** [comment]
I don't think it is currently possible since the sub-tasks cannot be given a due date. It would be a nice feature however, so if anyone would be willing to implement it that would be great.

**Comment by fguillot** [comment]
Sorry, I prefer to keep Kanboard simple so this feature won't be developed. There is no date defined for subtasks btw.

**Comment by juanluisbaptiste** [comment]
What about displaying a gantt chart for the subtasks of a task instead of displaying them on the main gantt chart ?
