### ISSUE TITLE
How can I use Google Fonts with Kanboard?

### ISSUE THREAD

**Issue by tangelvy** [fguillot/kanboard#1834]
Hello, 

First, many thanks to Frédéric Guillot for this great tool, it's very usefull. 

I installed the Css and Theme plugins, but unfortunately I'm unable to get Google Fonts to work :-/

It works if I place the html code in the head of the main index.php (<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'> for example), but then it provocs blank pages when I create or delete a task or a project...

I tried to put the code in many other files, including app/Template/layout.php, but the font doesn't load. However, the code appears in the page source code when I check it.

Could someone help me with that issue please?
Thanks!

**Comment by fguillot** [comment]
If you are loading the fonts from an external web server, you are probably blocked by Content Security Policy: https://github.com/fguillot/kanboard/blob/master/doc/plugin-overrides.markdown#override-http-content-security-policy

You probably need to add `font-src`.

**Comment by tangelvy** [comment]
Thank you for the answer, I succeeded to use Google Fonts.

The way to do it, for others facing the same issue...
- Download the google fonts package (https://github.com/google/fonts) and upload on your server the .ttf files of the polices you wish to use
- Call the police with the font-face rule (http://www.w3schools.com/cssref/css3_pr_font-face_rule.asp)
- Apply on elements within your CSS code.

Kind regards
