### ISSUE TITLE
Why kanboard jsonrpc-api returning response in html instead of json

### ISSUE THREAD

**Issue by Ankur1994a** [fguillot/kanboard#1844]
when i am trying to hit the api it not responding in json format its returning html.why its happening please guide me.i am using it like:
http://Mylocalhost/jsonrpc.php     its returning "parser error" and when adding parameter like:
{"jsonrpc": "2.0", "id": 1, "method": "getAllUsers"}
its returning html but it should return a json response,please suggest me what i need to do as soon as posible.

**Comment by abhit011** [comment]
Even I am facing the same issue, its returing me the HTML instead of JSON.

**Comment by fguillot** [comment]
Can you show an example of request or code you are using?

**Comment by Ankur1994a** [comment]
code:-

import java.io.UnsupportedEncodingException;
import java.util.Base64;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.web.client.RestTemplate;
import java.net.*;


public class ProjectService {

    public void getAllProjects() throws UnsupportedEncodingException {

        RestTemplate restTemplate = new RestTemplate();
        	try{
        String url = "http://localhost/task/jsonrpc.php";
        String requestJson = "{\"jsonrpc\": \"2.0\", \"method\": \"getAllUsers\", \"id\": 1}";
        String user = "jsonrpc";
        String apiToken = "437e13e7bb431ab5d42fb6aadf540f822124a4e01cb1fb8a8a096ff9e87b";

        // encode api token
        byte[] xApiAuthTokenBytes = String.join(":", user, apiToken).getBytes("utf-8");
        String xApiAuthToken = Base64.getEncoder().encodeToString(xApiAuthTokenBytes);

        // consume request
        HttpHeaders headers = new HttpHeaders();
        headers.add("X-API-Auth", xApiAuthToken);
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<String> entity = new HttpEntity<String>(requestJson, headers);
        String answer = restTemplate.postForObject(url, entity, String.class);
        System.out.println(answer);
        	}
        	catch(Exception e)
        	{
        		System.out.println("Hello Error "+e);
        	}
    }
    public static void main(String ar[])
    {
    	ProjectService pro=new ProjectService();
    	try{
    		pro.getAllProjects();
    	}
    	catch(Exception e)
    	{
    		System.out.print(e);
    	}
    }
}


output:-
![java-output](https://cloud.githubusercontent.com/assets/12482768/13101074/3991a6a4-d569-11e5-892c-d63c72470fb3.png)




and when i am hitting the API using postmaster plugin:-

![json-response](https://cloud.githubusercontent.com/assets/12482768/13100960/1fdd17b2-d568-11e5-96f7-40d2c7dcfd62.png)

**Comment by fguillot** [comment]
- The data sent to the API must be a valid JSON payload. From your screenshot of Postman, you seems to send data with "form-data" which is not correct.
- The response sent by your web server seems to be a 302 redirect to `/task/SiteLogin.aspx?...`, this part is not related to Kanboard but to way your have configured IIS (maybe an authentication is required?).

**Comment by Ankur1994a** [comment]
Thats fine , but then what about this ? When i am trying to connect from a java client 
e.g this
RestTemplate restTemplate = new RestTemplate();
        try{
    String url = "http://localhost/task/jsonrpc.php";
    String requestJson = "{\"jsonrpc\": \"2.0\", \"method\": \"getAllUsers\", \"id\": 1}";
    String user = "jsonrpc";
    String apiToken = "437e13e7bb431ab5d42fb6aadf540f822124a4e01cb1fb8a8a096ff9e87b";

    // encode api token
    byte[] xApiAuthTokenBytes = String.join(":", user, apiToken).getBytes("utf-8");
    String xApiAuthToken = Base64.getEncoder().encodeToString(xApiAuthTokenBytes);

    // consume request
    HttpHeaders headers = new HttpHeaders();
    headers.add("X-API-Auth", xApiAuthToken);
    headers.setContentType(MediaType.APPLICATION_JSON);
    HttpEntity<String> entity = new HttpEntity<String>(requestJson, headers);
    String answer = restTemplate.postForObject(url, entity, String.class);
    System.out.println(answer);
        }
        catch(Exception e)
        {
            System.out.println("Hello Error "+e);
        }
}

In that case. I might be missing some config. Do i need to enable something more for enabling JSONRPC at my end ?

**Comment by Ankur1994a** [comment]
Its little urgent please guide me what i need to do.

**Comment by Ankur1994a** [comment]
am i doing anything wrong please guide me
