### ISSUE TITLE
Instalation Issue with kanboard

### ISSUE THREAD

**Issue by donieardianto** [fguillot/kanboard#1845]
I tried installing kanbanboard in our website and it come up with error message below

============================================================
Warning: openlog() has been disabled for security reasons in /home/laiengi1/public_html/project/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php on line 24

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to connect to syslog.' in /home/laiengi1/public_html/project/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php:25 Stack trace: #0 /home/laiengi1/public_html/project/kanboard/app/ServiceProvider/LoggingProvider.php(16): SimpleLogger\Syslog->__construct('kanboard') #1 /home/laiengi1/public_html/project/kanboard/vendor/pimple/pimple/src/Pimple/Container.php(273): ServiceProvider\LoggingProvider->register(Object(Pimple\Container)) #2 /home/laiengi1/public_html/project/kanboard/app/common.php(25): Pimple\Container->register(Object(ServiceProvider\LoggingProvider)) #3 /home/laiengi1/public_html/project/kanboard/index.php(4): require('/home/laiengi1/...') #4 {main} thrown in /home/laiengi1/public_html/project/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php on line 25
=================================================================

The server conviguration is 
- PHP Version 5.4.45
- SQLlite 3.8

PHP Extensions instaled
- pdo_sqlite	
- pdo_mysql	
- gd	
- mbstring	
- openssl	
- json	
- hash	
- ctype	
- session

Please advice for this instalation issue. What should i do to solve these problem. 

Thanks,

Donie

**Comment by fguillot** [comment]
You can disable syslog in Kanboard, the procedure is described here: https://github.com/fguillot/kanboard/blob/master/doc/config.markdown#logging

**Comment by donieardianto** [comment]
already disable the syslog as sugested but get another error below

Warning: openlog() has been disabled for security reasons in /home/laiengi1/public_html/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php on line 24

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to connect to syslog.' in /home/laiengi1/public_html/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php:25 Stack trace: #0 /home/laiengi1/public_html/kanboard/app/ServiceProvider/LoggingProvider.php(16): SimpleLogger\Syslog->__construct('kanboard') #1 /home/laiengi1/public_html/kanboard/vendor/pimple/pimple/src/Pimple/Container.php(273): ServiceProvider\LoggingProvider->register(Object(Pimple\Container)) #2 /home/laiengi1/public_html/kanboard/app/common.php(25): Pimple\Container->register(Object(ServiceProvider\LoggingProvider)) #3 /home/laiengi1/public_html/kanboard/index.php(4): require('/home/laiengi1/...') #4 {main} thrown in /home/laiengi1/public_html/kanboard/vendor/fguillot/simpleLogger/src/SimpleLogger/Syslog.php on line 25

Please advice.

Regards,

Donie
