### ISSUE TITLE
Can't add file:/// URI as external links

### ISSUE THREAD

**Issue by mterron** [fguillot/kanboard#1852]
If you try to add a file:/// URI, kanboard doesn't let you proceed to the second page, see [http://postimg.org/image/kv2nz3nvn/](url)

Expected behaviour: Kanboard allows me to insert any kind of external link even if kanboard itself can't access it, as the links will be executed by the client and he might have the required access to the URI.

**Comment by fguillot** [comment]
With the last development version, you can add local links that starts with `file://`. However, your browser won't allows you to click on the link, you will have to copy the URL manually.
