### ISSUE TITLE
Timetable plugin not working

### ISSUE THREAD

**Issue by dino124** [fguillot/kanboard#1855]
Salut Frédéric,
and thanks for your great work, I have an issue with the timetable plugin. I placed the Timetable folder in /kanboard/plugins/ but for some reason it's not detected, I don't see anything in my proflle section.
I installed another plugin the "google authent" and I can see it in "external accounts", is there an issue with the timetable plugin?

// Plugins directory
define('PLUGINS_DIR', 'plugins');

**Comment by BlueTeck** [comment]
Is it displayed in Settings->Plugins ?

**Comment by dino124** [comment]
yes I can see it now Thanks.

**Comment by dino124** [comment]
Frédéric, is it possible for the next version of the timetable plugin to calculate the project tasks time according to the timetable? Thanks.

**Comment by froschdesign** [comment]
@dino124 
This is the wrong issue tracker! [Look here.](https://github.com/kanboard/plugin-timetable/issues)
