### ISSUE TITLE
1.0.25 is very slow

### ISSUE THREAD

**Issue by mdgeus** [fguillot/kanboard#1856]
I've just updated to the 1.0.25 and every action is taking a very long time.
for example creating a new task or moving it to another column.

It looks like the system hangs for a couple of minutes.

The spinner keeps spinning.

**Comment by BlueTeck** [comment]
You could log into the debug file, to find out wich step is ataking so long.

https://github.com/fguillot/kanboard/blob/master/doc/config.markdown#enabledisable-debug-mode

**Comment by mdgeus** [comment]
I've found out that the problem is in sending mail.
It takes 120 seconds to send mail to one user.

I have now disabled mail notifications and will try to reconfigure the mail settings untill it's working faster.

**Comment by BlueTeck** [comment]
Maybe this issue could help: https://github.com/fguillot/kanboard/issues/1202#issuecomment-139455748
