### ISSUE TITLE
Error subtask time 

### ISSUE THREAD

**Issue by cncgen** [fguillot/kanboard#1857]
Hallo,
i have just install the new version of kanboard ... very nice software :+1: 
but wenn i create a subtask and start the counter it shows me this error :-(.
hoppe there is a solution for that. (system : wind.8.1 , wamp serveur, mysql)

![error_time_sub_task](https://cloud.githubusercontent.com/assets/8451537/13129215/b303a466-d5db-11e5-969b-828893111dae.png)

**Comment by fguillot** [comment]
Yes, this bug have been already reported.

**Comment by TabDambrine** [comment]
#1801 for the original thread

**Comment by fguillot** [comment]
Fixed in 1.0.26
