### ISSUE TITLE
[Bug] [Master] Activity Stream PHP Warning Template/event/file_create.php failed to open.

### ISSUE THREAD

**Issue by David-Norris** [fguillot/kanboard#1858]
When viewing an activity stream that includes an event for a file that was added to a task before commit 8e25c87, a PHP warning is encountered.

Possible fix would be to run an "update project_activities set event_name= 'task.file.create' where event_name=‘file.create' " command on the database.

Sorry, unable to prepare a pull request at this time.

**Comment by fguillot** [comment]
Should be fixed now if you update master.

Thanks.
