### ISSUE TITLE
json auth Authentication failed error

### ISSUE THREAD

**Issue by esclkm** [fguillot/kanboard#1859]
### Configuration

- Kanboard version: 1.025
- Database type and version: sqlite

when I use kanbord application api - everything works fine. But when user api - there is an error.

So :
-userapi = base64(username:userpass)
-appapi = base64(jsonrpc:appcode)

curl -H 'X-API-Auth: -appapi' -d '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 3}' --verbose http://tasks.leximed.pl/jsonrpc.php

answer:

* timeout on name lookup is not supported
*   Trying 93.157.99.179...
* Connected to tasks.leximed.pl (93.157.99.179) port 80 (#0)
> POST /jsonrpc.php HTTP/1.1
> Host: tasks.leximed.pl
> User-Agent: curl/7.45.0
> Accept: */*
> X-API-Auth: XXXX
> Content-Length: 55
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 200 OK
< Date: Thu, 18 Feb 2016 06:53:31 GMT
< Server: Apache
< X-Powered-By: PHP/5.5.21-ogc0
< Transfer-Encoding: chunked
< Content-Type: application/json
<
{"jsonrpc":"2.0","id":3,"result":[{.....

**USER-api**
curl -H 'X-API-Auth: -userapi' -d '{"jsonrpc": "2.0", "method": "getAllProjects", "id": 3}' --verbose http://tasks.leximed.pl/jsonrpc.php

* timeout on name lookup is not supported
*   Trying 93.157.99.179...
* Connected to tasks.leximed.pl (93.157.99.179) port 80 (#0)
> POST /jsonrpc.php HTTP/1.1
> Host: tasks.leximed.pl
> User-Agent: curl/7.45.0
> Accept: */*
> X-API-Auth:ZXNjbGttOjE5ODYxMQ==
> Content-Length: 55
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 403 Forbidden
< Date: Thu, 18 Feb 2016 06:56:29 GMT
< Server: Apache
< X-Powered-By: PHP/5.5.21-ogc0
< Transfer-Encoding: chunked
< Content-Type: application/json
<
{"error": "Access Forbidden"}

what is wrong?

**Comment by fguillot** [comment]
The procedure `getAllProjects` is not allowed by the user API, you have to use the method `getMyProjects`.
