### ISSUE TITLE
actions in leftbar or comments form enabled by default

### ISSUE THREAD

**Issue by esclkm** [fguillot/kanboard#1860]
Kanboard version: 1.025
 When I updated my kanboard: a have a lot of questions - how to add new comment

-can you add ability:
comments form enabled in tasks form, even there is no comments
or move actions bar to the left - no in submenu ;

you can help me and give hooks names - and action names - and i wiil write a plugin
thx

**Comment by esclkm** [comment]
I wrote little plugin/ thx

**Comment by fbartels** [comment]
Hello @esclkm ,

would you mind sharing your plugin?
