### ISSUE TITLE
Notice: Sub-Task Status-Change

### ISSUE THREAD

**Issue by SebStaeubert** [fguillot/kanboard#1862]
### Expected behaviour

Status Change of a Sub-task without Notice

### Actual behaviour

Status Change of a Sub-task with Notice:
"Notice: Undefined variable: redirect in /var/www/kanboard/app/Template/subtask/table.php on line 61"

### Steps to reproduce

1. Click on a Task
2. Add a Sub-task
3. Change the Status of a Sub-task -> Notice appears in the right column

### Configuration

- Kanboard version: 1.0.25
- Database type and version: MySQL
- PHP version: 5.4.45-0+deb7u2
- OS: Debian 8
- Browser: Iceweasel 38.5 (Firefox)

**Comment by TabDambrine** [comment]
duplicate of #1801.

**Comment by fguillot** [comment]
Fixed in 1.0.26

**Comment by SebStaeubert** [comment]
Great, THX!
