### ISSUE TITLE
How to mark a task done

### ISSUE THREAD

**Issue by jaguarondi** [fguillot/kanboard#1863]
This is just a question, I can't find how to mark a task done as I would tick a subtask for example. If I move it to the "Done" column, the task is still count as running (calendar, analytics) and if I close it, then it disappears from the board. Anyway to mark it as done (end date) but not close it?

I'm new to Kanban so maybe I'm missing something fundamental here.

Thanks,
David

**Comment by a4ambrish** [comment]
Dear Kanboard team,

today i have also downloaded and set kanboard in my local network.
I am also facing the same issue. 

![image](https://cloud.githubusercontent.com/assets/16659736/13173502/d87d14b8-d723-11e5-932e-7fa2674ee077.png)

please help me to solve this issue.

**Comment by BlueTeck** [comment]
@a4ambrish  see #1801

**Comment by fguillot** [comment]
@jaguarondi when you close a task the completion date will be set automatically
@a4ambrish this bug have been fixed
