### ISSUE TITLE
Hooking in a custom CSS-file should include choice of media (screen/print)

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#1864]
### Expected behaviour

I want to load a new stylesheet within my plugin:
```$this->hook->on('template:layout:css', 'plugins/Css/skin.css');```
sets the usage to ***media="screen"***. I would like to choose which type of media the css is for.

Something like:
```$this->hook->on('template:layout:css', 'plugins/Css/skin.css', 'print');```
resulting in
```<link rel="stylesheet" href="/kanboard/plugins/css/style.css?1450287310" media="print">```

### Actual behaviour

media="screen" is set automatically.

**Comment by Busfreak** [comment]
I tried sending both, value for the hook and the media-type in an array in the Plugin.php:

`$this->hook->on('template:layout:css', array('value' => 'plugins/qm/css/style.css', 'media' => 'print'));`

In Helper/Asset::css I have to check if the $filename is an array an then split it into $filename and $media:

        if (is_array($filename))
        {
            $media = $filename['media'];
            $filename = $filename['value'];
        }

Could this be a way?

**Comment by fguillot** [comment]
You can also use the template hook `template:layout:head` to inject any html tag in the head section.

**Comment by Busfreak** [comment]
OK, THX!
