### ISSUE TITLE
Cron Job

### ISSUE THREAD

**Issue by kamov** [fguillot/kanboard#1876]
Hi

My cron job allow to send email with output of result.
However, this don't happen.

My hosting suggest to remove ">/dev/null 2>&1"
wh,  because this blocks the output.

Can I safetly remove this and use:

0 8 * * * cd /path/to/kanboard && ./kanboard cronjob

Thanks!

**Comment by fguillot** [comment]
`>/dev/null 2>&1` redirect stdout and stderr to /dev/null, that it's.
