### ISSUE TITLE
script for cron job

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#1880]
### Expected behaviour
from what I understand I need a script on my hosted webspace to run the cronjobs. Is there on? Sorry for being a rookie

### Configuration

- Kanboard version: 1.0.25
- Database type and version: mysql
- PHP version: 5.6
- OS: Debain Squeeze

**Comment by thob** [comment]
I created a .sh file with this content
` #!/bin/sh
cd /is/htdocs/…/www/…/kanboard  
./kanboard cronjob >/dev/null 2>&1`

it's not working though, at least I don't get an email for _rotten tasks_

**Comment by fguillot** [comment]
Which hosting provider do you use?

**Comment by thob** [comment]
[Hosteurope](https://www.hosteurope.de/en/), I have a virtual managed server there. I got some kind of shell access but not to crontabs. So to launch it I need the GUI from HE.

**Comment by fguillot** [comment]
I don't know, it's specific to the user interface of your hosting provider.
