### ISSUE TITLE
Kanboard is too great

### ISSUE THREAD

**Issue by connorbode** [fguillot/kanboard#1881]
### Expected behaviour

Software should have some flaws.  Should be lacking in features, or broken in some way.

### Actual behaviour

Software works perfectly.  Completely satisfies user.  Continues to impress user with newly found features.

### Steps to reproduce

1. Visit kanboard.net
2. Install
3. Profit

### Conclusion

Just wanted to say thank you for such great software.

**Comment by thob** [comment]
:+1:

**Comment by nerdoc** [comment]
Subscribe.

**Comment by bdrayer** [comment]
Me too

**Comment by moserensheng** [comment]
i am chinses，how to create a model? i create like taskCreation, but throw a exception: is not defined ,this is why

**Comment by nerdoc** [comment]
@moserensheng  Could you maybe [open a new question](https://github.com/fguillot/kanboard/issues/new)?

**Comment by moserensheng** [comment]
@nerdoc my question is submited    could you help me， thank you

**Comment by fguillot** [comment]
@connorbode Thanks :)

**Comment by 85pando** [comment]
@connorbode is totally right. The bugs seem to be too well hidden. 👻

😱 But this will probably be a wontfix bug.
