### ISSUE TITLE
How do you configure for a hosted web service provider?

### ISSUE THREAD

**Issue by CaptainPackers** [fguillot/kanboard#1884]
I tried to install on one.com, went to mydomain.com/kanboard, as per instructions, and I get a forbidden error. What do I have to change/configure to get this to work with a hosted service provider like one.com or dreamhost or take your pick???

**Comment by fguillot** [comment]
There is already plenty of documentation to install Kanboard in different environments. For a shared hosting provider, you just need to copy the files and configure the database.
