### ISSUE TITLE
Suggestion: Plugin manager 

### ISSUE THREAD

**Issue by emmanuelbuah** [fguillot/kanboard#1888]
This is more of a feature request. To grow the eco system and make it easy for people to use and contribute plugin, It would be nice to have a plugin manager where you can search, find, install plugin, change plugin settings with kanboard application. 

I think this will be the final icing on the cake for anyone (including non developers) to setup and manage kanboard.

**Comment by BlueTeck** [comment]
Nice idea.

By the way, a list of plugins could be found here: https://kanboard.net/plugins

**Comment by fguillot** [comment]
Available in KB 1.0.29
