### ISSUE TITLE
mkdir() permission denied

### ISSUE THREAD

**Issue by elbismanuel** [fguillot/kanboard#1889]
Hi i try to upload and take snapshot but i get an error,

![kanboard](https://cloud.githubusercontent.com/assets/6278027/13299871/0ca9aec8-db0b-11e5-915b-2811d55ed95a.png)

I put all permissions in the folder app (777), my question is? i need an specifically group in the app? 
I used apache group and root group but i cant upload files in the server.

Thank

**Comment by abanger** [comment]
chcon -R -h -u system_u -t httpd_sys_content_t
