### ISSUE TITLE
create a model

### ISSUE THREAD

**Issue by moserensheng** [fguillot/kanboard#1892]
//this is my controller Licensees.php
<?php 
namespace Kanboard\Controller;
class Licensees extends Base {
	public function create ($values = array(), $errors =array()) {
		$user  = $this->getUser();

		$this ->response->html($this->helper->layout->dashboard('license/create', array(
			'title' => t('bulid license'),
			'user'  => $user,
			)));
	}
	public function save() {
		$values = $this->request->getValues();
                //this is invoke a model
		$this->licensees->create();
	}
}

//this is my model
<?php
namespace Kanboard\Model;
use Kanboard\Event\LicenseesEvent;

/**
 * Lincense Creation
 *
 * @package  model
 * @author   Frederic Guillot
 */
class Licensees extends Base
{
    /**
     * Create a Lincense
     *
     * @access public
     * @param  array    $values   Form values
     * @return integer
     */
    public function create()
    {
        echo 545;
    }  
}

url: http://localhost/kanboard/?controller=licensees&action=save

when controller is runned   throw an exeception:    Internal Error: Identifier "licensees" is not defined.

**Comment by nerdoc** [comment]
@moserensheng Oh - I'm no kanboard dev - I don't have aclue how to use internals... ;-)

**Comment by fguillot** [comment]
Take a look to the file ClassProvider.php. Kanboard use Pimple for the dependency injection container.
