### ISSUE TITLE
Constant page refresh after install

### ISSUE THREAD

**Issue by oszelaar** [fguillot/kanboard#1900]
After installing Kanboard on Ubuntu 14.04.4 using docker, and connecting it to my Gitlab server I find myself unable to use it because after sign in any page I go to will constantly refresh. I noticed a few other people have flagged this issue, but no response so far.

I use the chrome plugin "redirect path" and it is showing a perpetual loop of javascript redirects.

I'm accessing my installation through chrome, however IE produces the same problem

**Comment by fguillot** [comment]
I cannot really reproduce this issue at least with the last Docker image.

Can you describe how you are running the Docker image and how you access it?
