### ISSUE TITLE
New tasks action menu not visible

### ISSUE THREAD

**Issue by mehdid** [fguillot/kanboard#1906]
### Expected behaviour

See Action menu for selected task and be able to select one of the proposed actions.

### Actual behaviour

Action menu is drawn outside page and only "Remove" is visible.
Action menu is shown okay in Chromium 48.0.2564.116.

### Steps to reproduce

1. Create a task
2. Click on the task
3. Click on "Actions" menu.

### Configuration

- Kanboard version: 1.0.25
- Database type and version: mysql/5.5.47
- PHP version: 5.16.17
- OS: Debian 8
- Browser: Iceweasel/Firefox 44.0.2

**Comment by fguillot** [comment]
Can you try again with the version 1.0.26? this issue should be fixed.

**Comment by mehdid** [comment]
I've just tested with 1.0.26 and it fixed the issue, indeed. Thanks!
