### ISSUE TITLE
Upgrade to V1.0.25: Unable to load this plugin class 

### ISSUE THREAD

**Issue by frankvanderheyden** [fguillot/kanboard#1907]
### Expected behaviour
After upgrade to V1.0.25 and opening Kanboard in Chrome I immediately get the errormessage:
"Internal Error: Unable to load this plugin class \Kanboard\Plugin\@eaDir\Plugin" 
No logon screen. 
V1.0.24 still works fine.
What is wrong? 

### Configuration

- Kanboard version: 1.0.25
- Database type and version: Mariadb 5.5.44
- PHP version: 5.5
- OS: Synology
- Browser: Chrome

**Comment by fguillot** [comment]
The answer is there: https://github.com/fguillot/kanboard/issues/1532

**Comment by frankvanderheyden** [comment]
It works. Thanks for the answer.
Regards
Frank
