### ISSUE TITLE
user filters

### ISSUE THREAD

**Issue by ariebarie** [fguillot/kanboard#1911]
# Expected behavior

When a user is being selected in the "user filter" drop down I expected that it's name will be the only one used to filter, for example: _status:open assignee:"Demo Admin"_

- There should be only one "assignee" filter in the filter string.

### Actual behavior

The "user filer" acts like "append filter" and result with filter like: _status:open assignee:nobody assignee:"Demo Admin" assignee:"user000"_

### Steps to reproduce

1. Create a project with multiple users 
2. Select a user from the user filter drop down.
3. Select again a user from the user filter drop down.

### Configuration

- Reproduce on the Demo site 
- Browser: up to date Firefox and Chrome

**Comment by BlueTeck** [comment]
refers to https://github.com/fguillot/kanboard/issues/1181#issuecomment-146573589

**Comment by ariebarie** [comment]
I understand the changes, but there is no use in duplicate assigneed fiters - it gives empty group.
The dropdown selection of user filter should add assigneed filter or replace the assigneed filter in the current filter string.

**Comment by SebStaeubert** [comment]
Bug confirmed. Same Issue with the "category filter" drop-down next to the "user filter".

**Comment by fguillot** [comment]
It's not a bug and it was the expected behaviour.

However, I changed that in the development branch. Now, for the category and users filters only the selected occurence will be visible in the search field. It doesn't append the value anymore.

If appending the value is necessary, the custom filters can be used instead.
