### ISSUE TITLE
Oauth2 bug

### ISSUE THREAD

**Issue by litvinenkow** [fguillot/kanboard#1923]
I tried to implement a copy of oauth2 plugin for my company on the base of Github plugin and figured that core oauth2 class don't send "state" parameter that's required by server based on [this one](https://github.com/bshaffer/oauth2-server-php). And server said that state parameter is required and produces endless loops and don't authorize either.

As written [here](http://www.twobotechnologies.com/blog/2014/02/importance-of-state-in-oauth2.html) and [here](http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html) it's really important thing to avoid the CSRF.

I think that one simple string on the 61 line at the attached file will fix that behavior.

[OAuth2.php.txt](https://github.com/fguillot/kanboard/files/154382/OAuth2.php.txt)

**Comment by fguillot** [comment]
The state parameter in now handled (in master branch).
