### ISSUE TITLE
Filters on date using strtotime don't work for every case

### ISSUE THREAD

**Issue by rverchere** [fguillot/kanboard#1925]
### Expected behaviour

Trying to filter tasks modified before yesterday.
When using the filter `modified:<=yesterday` I should see all tasks.

### Actual behaviour
It shows nothing.

`modified:yesterday`works and gives me only the tasks modified yesterday.

Same behaviour with all words like 'last month', etc.

### Steps to reproduce

1. Go to the list of tasks
2. Apply the filter `modified:yesterday` :  tasks modified yesterday (normal behaviour)
3. Apply the filter `modified:<=yesterday` : nothing, I should see all tasks, includind the yesterday ones

### Configuration

- Kanboard version: 1.0.26
- Database type and version:  sqlite
- PHP version: 5.4.45
- OS: Debian 7
- Browser: Firefox

**Comment by fguillot** [comment]
In the development branch the filters have been improved. Query like `status:open created:>="11 days ago"` are now supported.
