### ISSUE TITLE
Please write, where to put config.php

### ISSUE THREAD

**Issue by Maienfelder** [fguillot/kanboard#1927]
In http://kanboard.net/documentation/mysql-configuration there is no information, in which directory config.php should be created.

**Comment by skobeo** [comment]
hi, just put at the root, where config.default.php is already. Or you can rename config.default.php to config.php

**Comment by froschdesign** [comment]
> Or you can rename config.default.php to config.php

This is also included in the docs: 

> Note: You can also rename the template file config.default.php to config.php.

http://kanboard.net/documentation/mysql-configuration

**Comment by Maienfelder** [comment]
thank you for your prompt answers!
