### ISSUE TITLE
Cannot change password or create new users with plugins installed

### ISSUE THREAD

**Issue by jmealo** [fguillot/kanboard#1928]
### Expected behaviour

You should be able to create new users and/or change the admin password **with any/all plugins installed in /plugins but not yet configured**.

### Actual behaviour

You cannot change the admin password and you cannot create new users.

### Steps to reproduce

1. Install kanboard from #master
2. Try to change admin password (will fail validation on all fields)
3. Try to create a user (will fail validation)

### Screenshots
http://i.imgur.com/AFV7Kua.png
http://i.imgur.com/JmM46pn.png

### curl:
``curl 'http://<REDACTED>/kanboard/?controller=user&action=save' -H 'Origin: null' -H 'Accept-Encoding: gzip, deflate, lzma' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36 OPR/35.0.2066.82' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Cookie: <<<REDACTED>>>' -H 'Connection: keep-alive' --data 'csrf_token=<<<REDACTED>>>&username=newuser&name=New+User&email=new%40localhost&password=Password123&confirmation=Password123&project_id=0&timezone=&language=&role=app-user' --compressed``
```

### Configuration

- Kanboard version: 6ef83d0e058d653322a8f9eb1131e665fb9b2a70
- Database type and version: PostgreSQL 9.5
- PHP version: 5.5.9
- OS: Ubuntu 14.04
- Browser: Chrome, Opera and Safari on OSX

**Comment by jmealo** [comment]
It definitely seems password related. If I change the password to Password123 via SQL I can no longer login.

### Generate the pasword
```php
print password_hash('JKYWzn8#MEmeaxL$EGj6S!jkeBs4*x', PASSWORD_DEFAULT) . "\n";
// $2y$10$pDxDIK.ANW0Vs1mhvxHEd.BnvFJTFfWSZmK96/hZHeaPIpPZM55X6
```

### Update the password and verify that it was set
```sql
kanboard=# UPDATE users SET password='$2y$10$pDxDIK.ANW0Vs1mhvxHEd.BnvFJTFfWSZmK96/hZHeaPIpPZM55X6' WHERE username='admin';
UPDATE 1
kanboard=# SELECT * FROM users;
kanboard=# SELECT count(1) FROM users WHERE password='$2y$10$pDxDIK.ANW0Vs1mhvxHEd.BnvFJTFfWSZmK96/hZHeaPIpPZM55X6';
 count 
-------
     1
(1 row)
```

**Comment by jmealo** [comment]
We can see from the PostgreSQL log that issuing this query is returning the user:
```sql
SELECT "id", "password" FROM "users"   WHERE "username" = 'admin' AND "disable_login_form" = false AND "is_ldap_user" = false AND "is_active" = true    LIMIT 1
```

**Comment by fguillot** [comment]
You are using your curl request to do that? if yes that won't works, the crsf token won't be valid.

**Comment by jmealo** [comment]
I've provided a curl request to show you the failed request issued by my
browser so that you can easily reproduce the issue. The CSRF token is the
one sent by my browser.

**Comment by fguillot** [comment]
Some plugins like the reverse proxy or client certificate will invalidate your session if they are not configured.
