### ISSUE TITLE
Active Directory Authentication not working

### ISSUE THREAD

**Issue by atcasanova** [fguillot/kanboard#1929]
### Expected behaviour

User Mode should allow AD's users to log in to kanban

### Actual behaviour

When I try to log in with an existent user, the debug.log shows a message error saying "[info] User not found in LDAP server". 
If I try to log in with an nonexistentuser, it says "[error] LDAP authentication failure for "atcasanovaaaaaaa@local.domain""

It's wrong in both ways. The password is right, I can't log in and the message says the user doesn't exist. 
And when I try to log in with a nonexistent user, I get the wrong message.

Either way, the authentication is not working.

### Steps to reproduce
define('LDAP_BIND_TYPE', 'user')
define('LDAP_PASSWORD', null); 
define('LDAP_AUTH', true);
define('LDAP_SERVER', '10.40.0.64');
define('LDAP_PORT', 389);
define('LDAP_SSL_VERIFY', false);
define('LDAP_START_TLS', false);
define('LDAP_USERNAME_CASE_SENSITIVE', false);
define('LDAP_USERNAME', '%s@local.domain');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_BASE_DN', 'CN=IPS_Admins,CN=users,DC=local,DC=domain');
define('LDAP_USER_FILTER', '(&(objectClass=user)(sAMAccountName=%s))');
define('LDAP_USER_ATTRIBUTE_USERNAME', 'samaccountname');
define('LDAP_USER_ATTRIBUTE_FULLNAME', 'displayname');
define('LDAP_USER_ATTRIBUTE_EMAIL', 'mail');
define('LDAP_USER_ATTRIBUTE_GROUPS', 'memberof');
define('LDAP_USER_CREATION', true);

### Configuration

- Kanboard version: 1.0.25
- Database type and version: sqlite 3.6.20
- PHP version: 5.3.3 
- OS: CentOS release 6.7 (Final
- Browser: any

**Comment by mterron** [comment]
Try define('LDAP_USERNAME', 'DOMAIN\\%s');
Replace domain for your domain name

**Comment by juanfergc** [comment]
Hi. I'm having the same problem connecting to AD.

I try to use the define('LDAP_USERNAME', 'DOMAIN\\%s') format (obviously with my correct domain), but now i'm receiving this error:
Internal Error: Username not found in LDAP profile, check the parameter LDAP_USER_ATTRIBUTE_USERNAME.

Triple checked all my AD configuration and i'm pretty sure everything is ok.

Any thoughts?

**Comment by mterron** [comment]
You need to escape your \ so it reads DOMAIN\\\%s

**Comment by fguillot** [comment]
There are 4 different examples on the website to help you to configure LDAP: https://kanboard.net/documentation/ldap-configuration-examples

Make sure to update to the latest version of Kanboard, LDAP integration have been improved.
