### ISSUE TITLE
Page always redirects to dashboard after login (instead of the page originally requested)

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#1930]
Let's say you want to directly access a task or board from your bookmarks or history, but that Kanboard logged you out (due to session inactivity or whatnot). You get the login form, authenticate through it or though external auth (such as Google accounts) and then... you end up at the /dashboard page, so you then need to remember what you were trying to access in the first place and click a bunch of times to go to it.

It would be nicer if Kanboard took into account what page I was trying to access when it prompted me to login, and then redirect me to that page once I'm authentified.

**Comment by fguillot** [comment]
There is already a redirection to the original page. Need to validate if that works correctly with Google Auth.
