### ISSUE TITLE
Unexpected access to private tasks

### ISSUE THREAD

**Issue by bzminds** [fguillot/kanboard#1933]
### Expected behaviour

I have created a project with public access, once I get the public link I can see the public kanboard at:

**mydomain/kanboard/public/board/7947d8e1f44dd332d5fc88752558a7c96ad003850274c196faae92a0a776**

When I click on a task I get redirected to something like:

**mydomain/kanboard/public/task/19/7947d8e1f44dd332d5fc88752558a7c96ad003850274c196faae92a0a776**

### Actual behaviour

Now If I change the number '19' in the task link to something else, I can see tasks from other projects that are supposed to be private, and without public access.

All of this is happening without being logged in, of course.

### Configuration

- Kanboard version: 1.0.26
- Database type and version: SQlite
- PHP version: 5.6.17
- OS: Linux
- Browser: Chrome and IE

**Comment by fguillot** [comment]
This issue is now fixed in the branch master.

Thanks a lot for reporting that!
