### ISSUE TITLE
Adding task bug

### ISSUE THREAD

**Issue by dantahoua** [fguillot/kanboard#1936]
### Expected behaviour

Task modal window should open when clicking on the "+".
If modal window open when pressing "n" on keyboard, should save when clicking on save.

### Actual behaviour

Instead, the Project list modal window always appear.

### Steps to reproduce

1.Click on the "+" OR press "n" on keyboard, fill the form and click "save"

### Configuration

- Kanboard version: 1.0.26 AND 1.0.27
- Database type and version: SQLLite 3.8.10.2
- PHP version: 5.6.17 and Apache 2.4
- OS: Linux Cent-Os
- Browser: All

Note that everything works fine with local server on my Mac (Mamp Pro), tested with different PHP Version (5.5 to 7, even 5.6.10) BUT Apache 2.2.29.
Seems Apache is the problem, a problem with Apache 2.4 ?

**Comment by dantahoua** [comment]
I was enable to test localy with Apache 2.4 (with AMPPS) and it's working...
So maybe the subdomain is the culprit?

**Comment by dantahoua** [comment]
New update: ModSecurity seems to generate this bug. When I deactivate apache ModSecurity, the problem is gone! Just to let you know! :)

**Comment by AbadaLokman** [comment]
Hello,

Is there a way to fix it without disabling ModSecurity ?

**Comment by rautamiekka** [comment]
Open your Apache error log to a window and repro this.
