### ISSUE TITLE
Add a generic tag field to task 

### ISSUE THREAD

**Issue by matteosanguin** [fguillot/kanboard#1938]
New feature request -

I want to group task dinamically.

I'd like to have a new field tag in the task where i can write one or more classification of tasks .

I'd like also to filter tasks by this new field .

**Comment by BlueTeck** [comment]
see #646 or you could use the task metadata via plugin

**Comment by matteosanguin** [comment]
I think taskmetadata might be fine but I'm not a php programmer you might give me a simple example of plugin task metadata please.

**Comment by BlueTeck** [comment]
You could take a look/install at my work in progress metadata plugin https://github.com/BlueTeck/kanboard_plugin_metadata

**Comment by Busfreak** [comment]
@BlueTeck 
nice job ;-)

**Comment by BlueTeck** [comment]
@Busfreak thanks, still work in progress ;)

**Comment by matteosanguin** [comment]
I think your plugin is a good starting point.

I need to filter metadata value ... but i stay tuned for improvements ...


Thank you very much.
