### ISSUE TITLE
config.php outside docker conatiner is showing on webpage

### ISSUE THREAD

**Issue by Keulix** [fguillot/kanboard#1943]
What am I doing wrong? I added a `config.php`in the `data` path (outside the container), and now every page shows the content of the config file at the top.

### Expected behaviour

Adding a config.php at the recommended location outside the container (i.e. the external data path) should be interpreted instead of inserted in front of the "head" section and displayed in clear text on the web page. 

### Actual behaviour

A config.php file that is put in the same path like the sqlite db (host path, not in the container) and that has only the settings regarding smtp e-mail (including `MAIL_FROM`, `MAIL_TRANSPORT`and all ...`_SMTP`) is shown on any webpage at the top. Looking at the page source shows the lines from config.php have been inserted before the html/head section. Going through the repro steps below but removing the config file instead eliminates the problem again, but no config change, of course.

### Steps to reproduce

1. stop container
2. put config.php file in the data path (outside the container) right beside the sqlite db containing only the e-mail config params (for smtp)
3. re-start container
4. call login page

### Configuration

- Kanboard version: 1.0.26 (stable)
- Database type and version: sqlite as provided by the image
- PHP version: as provided by the image
- OS: Synology DSM 5.2-5644 w/Synology Docker Service
- Browser: Chrome 48.0.2564.116 on osx 10.11.3

**Comment by fguillot** [comment]
your config.php starts with the `<?php` tag?

**Comment by Keulix** [comment]
<facepalm /> Thanks for the hint, works perfect now.
