### ISSUE TITLE
shibboleth authentification

### ISSUE THREAD

**Issue by Maienfelder** [fguillot/kanboard#1944]
I want to use kanboard on an university server, to which users access via shibboleth.
Before getting access to kanboard, the user has to enter his shibboleth login, which is defined in the htaccess file within the kanboard folder.

After that, the process is similar to LDAP authentification, but not equal.

### Preconditions of Process:
1. The user, who has successfully logged in via shibboleth, is allowed to use kanboard.
2. All necessary user information is available from the $_SERVER Array. For Example his email address from $_SERVER["HTTP_SHIB_INETORGPERSON_MAIL"] .

### Process:
1. Look for user in kanbords database
2. If the user does not exist
     create user without password 
3. give him access to kanboard

Im not familiar with kanboard. Therefore my questions to the experts:
- Is it that simple as I stated above?
- Which already existing functions of kanboard would support the steps above?

**Comment by fguillot** [comment]
Seems to be very similar to the reverse proxy authentication of Kanboard or to this plugin: http://kanboard.net/plugin/reverse-proxy-ldap

**Comment by Maienfelder** [comment]
Yes, this is very similar. Thank you.
For this term, the students are authorized directly from Kanboard. I'll test reverse proxy in summer.

**Comment by smacz42** [comment]
Would love to know if this had been implemented in one form or another.

**Comment by olberger** [comment]
I may be wrong, but maybe this is related: https://github.com/trajche/SamlAuth
