### ISSUE TITLE
Problems with a several numbers of subtasks

### ISSUE THREAD

**Issue by Deuzinei** [fguillot/kanboard#1948]
### Expected behaviour

When i have many sub task i cant change any properties of a subtask

### Actual behaviour

Application just remain in processing

### Steps to reproduce
1.Save a several nunbers of sub tasks, 3000, for instance.
2.Try to chance any propertie of subtasks
3.Application cant finish the processe

### Configuration

- Kanboard version: v1.0.23
- Database type and version: Postgres 9.3
- PHP version: 5.3.2
- OS:Cent OS
- Browser:

**Comment by Chaosmeister** [comment]
3000 subtasks sounds insane...
maybe you should split the subtasks into multiple task with their respective category.

**Comment by fguillot** [comment]
3000 subtasks for one task or 3000 in total?

**Comment by fguillot** [comment]
I'm not sure how you can manage 3000 subtasks with the user interface...
