### ISSUE TITLE
Improve sidebar design

### ISSUE THREAD

**Issue by mcorteel** [fguillot/kanboard#1950]
I suggest to remove the top margin for the title and add a left padding to menu items. This way, they don't move on mouse over. I also think that the active menu item would look better with a normal font-weight:

![spectacle nb7304](https://cloud.githubusercontent.com/assets/6164603/13551139/001e8610-e330-11e5-81d7-94ae051821b4.png)

What do you think? I have a pull request ready if you want.

**Comment by fguillot** [comment]
You can send your PR :)

**Comment by fguillot** [comment]
I merged your PR, thanks.
