### ISSUE TITLE
JSON-RPC API : I always get "Authentication failed"

### ISSUE THREAD

**Issue by EpocDotFr** [fguillot/kanboard#1953]
May be related to #1210 and #1859.

### Expected behaviour

Calling the `getVersion` method of the JSON-RPC API should returns the current kanboard version, e.g: 

```json
{
    "jsonrpc": "2.0",
    "id": 1661135463,
    "result": "1.0.26"
}
```

### Actual behaviour

The JSON-RPC error "Authentication failed" is always throwed, even if credentials are corrects:

```json
{
  "error" : "Authentication failed"
}
```

### Steps to reproduce

Make a simple JSON-RPC request calling the method `getVersion` with the `jsonrpc` username and the appropriate API token.

### Configuration

- Kanboard version: 1.0.26
- Database type and version: SQLite
- PHP version: 5.4.45 via Apache
- OS: Linux
- Browser: N/A

### Additional informations

  - Please note that I regenerated my API token several times (I didn't ever regenerated this token before, and I think the API worked in the past), maybe there is a bug here
  - There is no HTTPS
  - Here are two HTTP requests crafted with two different HTTP clients:

#### WizTools GUI RESTClient (Java)

```http
POST http://{REDACTED}/jsonrpc.php HTTP/1.1
Content-Length: 60
Content-Type: application/json; charset=UTF-8
Host: {REDACTED}
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.3.1 (java 1.5)
Authorization: Basic {REDACTED, authentication string here}

{"jsonrpc": "2.0", "method": "getVersion", "id": 1661138292}
```

#### jsonrpc-requests (Python library backed by requests)

```http
POST http:/{REDACTED, same as above}/jsonrpc.php HTTP/1.1
Host: {REDACTED, same as above}
Content-Length: 59
Accept-Encoding: gzip, deflate
Accept: application/json-rpc
User-Agent: python-requests/2.9.1
Connection: keep-alive
Content-Type: application/json
Authorization: Basic {REDACTED, same string as above}

{"jsonrpc": "2.0", "method": "getVersion", "id": 903558524}
```

The result is exactly the same: Authentication failed.

**Comment by EpocDotFr** [comment]
Update : I also tested with [your own JSON-RPC PHP client](https://github.com/fguillot/JsonRPC). Exact same problem: `JsonRPC\AccessDeniedException`.

```
$client = new JsonRPC\Client('http://wherekanboardisinstalled.com/jsonrpc.php');
$client->authentication('jsonrpc', '{REDACTED, authentication string here}');

print_r($client->getAllProjects());
```

**Comment by BlueTeck** [comment]
Did you tried to make the same API call to the Kanboard Demo page?

**Comment by EpocDotFr** [comment]
thanks for you suggestion.

It works on the demo. The result of `getVersion` is `demo`. I don't get it.

**Comment by EpocDotFr** [comment]
I upgrade PHP to 5.6.20, nothing changed (I host Kanboard on an OVH shared hosting).

**Comment by EpocDotFr** [comment]
After investigations, it seems that with specific Apache PHP handlers some `$_SERVER` variables are not popularized, especially `PHP_AUTH_USER` and `PHP_AUTH_PW` (used by the Kanboard's JSON-RPC server).

[Here](http://stackoverflow.com/a/7792912/1252290) is a Stackoverflow anwser about this. [Here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L47) is a part of the Symfony source code which deals with HTTP authentication.

Both are suggesting to add specific Apache configuration to handle this case:

```apache
RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

I added this configuration in the Kanboard's .htaccess, and now I get a 200 OK response from the API without any body in the HTTP response.

#1210 and #1859 have serious chances to be affected by this issue as well.

(poke @fguillot)

**Comment by EpocDotFr** [comment]
After investigations, it seems that with specific Apache PHP handlers some `$_SERVER` variables are not popularized, especially `PHP_AUTH_USER` and `PHP_AUTH_PW` (used by the Kanboard's JSON-RPC server).

[Here](http://stackoverflow.com/a/7792912/1252290) is a Stackoverflow anwser about this. [Here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L47) is a part of the Symfony source code which deals with HTTP authentication.

Both are suggesting to add specific Apache configuration to handle this case:

```apache
RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

I added this configuration in the Kanboard's `.htaccess`, and now all is working! On `jsonrpc.php`, I'd `print_r($_SERVER)` after modifyng the aforementioned `.htaccess`, both `PHP_AUTH_USER` and `PHP_AUTH_PW` are popularized.

#1210 and #1859 have serious chances to be affected by this issue as well.

(poke @fguillot)

**Comment by fbartels** [comment]
Hi,

I just tested this on my system and the workaround suggested by @EpocDotFr solves it for me as well. I have closed my original issue in favour of this ticket.

**Comment by fguillot** [comment]
@EpocDotFr I created a new entry in the FAQ: https://github.com/fguillot/kanboard/blob/master/doc/faq.markdown#authentication-failure-with-the-api-and-apache--php-fpm Thanks!

**Comment by TheCloud** [comment]
Sorry for opening this again, but the .htaccess patch does work only on some configurations.
In my case I get REDIRECT_HTTP_AUTHENTICATION populated and not HTTP_AUTHENTICATION so the proposed because my hosting provider uses "PHP SAPI: cgi-fcgi"

I added these lines to config.php (at the end) as a "testing patch" and now works:

// PHP FastCGI doesn't support HTTP Basic Authentication out of the box so we
  // need this workaround. Requires a patch to .htaccess.
  // @see http://drupal.org/node/1864628.
  if (isset($_SERVER['HTTP_AUTHORIZATION']) AND !empty($_SERVER['HTTP_AUTHORIZATION'])) {
    list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'], 6)), 2);
  } elseif (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']) AND !empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
    list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr($_SERVER['REDIRECT_HTTP_AUTHORIZATION'], 6)), 2);
  }
