### ISSUE TITLE
Usability questions 

### ISSUE THREAD

**Issue by Duplex420** [fguillot/kanboard#1955]
Hello,

- Is there a way to see an overview on calendar of all tasks for future - including when tasks are meant/scheduled to be duplicated?

- Can you add two users / assignees to a task? For example, I want to add a user but also want to add manager so the manager can see the tasks on their calendar for all users. 

- How can a manager or user of a task be notified when a new comment is added?

**Comment by fguillot** [comment]
1) Feature not available
2) Only one assignee per task is possible
3) Enable the notifications
