### ISSUE TITLE
Rename "Back to the board" and "Back to calendar" label

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#1959]
### Improvement
Rename "Back to the board" and "Back to the calendar" label, because you don't have to come from there. 

Proposal:
- Show on board
- Show on calendar

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/1961634/13568784/0ba6de08-e464-11e5-9f44-27478bd2639d.png)

ref #1807

**Comment by Chaosmeister** [comment]
:+1:

**Comment by thob** [comment]
What about:

- To board
- To calendar

**Comment by fguillot** [comment]
The view switcher is now unified between pages, there is no "back to board" anymore.
