### ISSUE TITLE
view screenshot from board.

### ISSUE THREAD

**Issue by dacebdo** [fguillot/kanboard#1960]
### Expected behaviour

Should open image in a new window.

### Actual behaviour

Gives error, "INTERNAL ERROR. ACTION NON IMPLEMENTED"

### Steps to reproduce

1.Make a new card, insert an screenshot.
2.View that card in the board and click over the clip logo to download or open the screenshot.
3.Instead of opening the screenshot in an image viewer, gives the error.

### Configuration

- Kanboard version:1.0.26
- Database type and version:
- PHP version:
- OS: windows 10
- Browser: chrome

**Comment by BlueTeck** [comment]
Could confirm this bug.

**Comment by BlueTeck** [comment]
PR with fix #1962

**Comment by fguillot** [comment]
PR merged thanks everybody!
