### ISSUE TITLE
[FR] configuration copy&pastable from Settings > About window

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#1961]
Since you made the Github-Issue template:

>### Configuration
>
- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

It would be nice to have the configuration copy&pastable in the Settings > About window.

Applicationversion & Database driver are already there.
The PHP Version is missing but might be easy for you to add and display.

So you would not have to rely on the issue-creator's ~~educated~~ guessing but would get the exact information you need.
Best regards!

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
It's now available in the current master.
