### ISSUE TITLE
template:task:menu hook

### ISSUE THREAD

**Issue by Imbasaur** [fguillot/kanboard#1964]
I am trying to attach new link to task:menu, and i cant pass $task['id'] from my plugins/name/Template/task/menu.php

```php
        <li>
            <i class="fa fa-clock-o fa-fw"></i>
            <?= $this->app->getRouterController() === 'plugin' ? 'class="active"' : '' ?>
            <?= $this->url->link(t('Time tracking'), 'plugin', 'index', array('plugin' => 'plugin', 'task_id' => $task['id'], 'user_id' => $user['id']), false, 'popover') ?>
        </li>
```

When i put same code in app/template/task/menu, everything works

Any idea what i am doing wrong?

### Configuration

- Kanboard version: 1.0.25

**Comment by fguillot** [comment]
This template hook doesn't exists anymore but the issue was probably because $task was not passed in the original hook.
