### ISSUE TITLE
Automatic action to assign color based on priority

### ISSUE THREAD

**Issue by NomaMitch** [fguillot/kanboard#1965]
### Expected behaviour

Issue #99 requested task cards be color coded based on task priority, but the ticket was closed because priority was not being added at the time. Now that tasks can be assigned a priority, rather than priority being based on the position in the column, it would be great to have an automatic action to assign a color based on the assigned priority.

### Actual behaviour

Currently color coding, based on priority is unavailable.

### Steps to reproduce

none

**Comment by crabnky** [comment]
+1

**Comment by nerdoc** [comment]
Definitely worth an implementation. Priority is worthless without `colors` and `sorting by priority`!

**Comment by phillc73** [comment]
I'd also find this automatic action helpful, and searched the issues specifically to see if it had already been submitted.

**Comment by otterz** [comment]
+1

This feature would be awesome! :)

**Comment by fguillot** [comment]
This feature is now available in the development branch.
