### ISSUE TITLE
Add external links to Json-RPC API

### ISSUE THREAD

**Issue by mtruijen** [fguillot/kanboard#1968]
Kindly requesting to add external link create/update/remove functions to Json-RPC API.

**Comment by StanSiska** [comment]
Would be super-useful to handle external links via API due to linkage with internal systems tasks.

**Comment by fguillot** [comment]
This feature is now available in the development branch: https://github.com/fguillot/kanboard/blob/master/doc/api-external-task-link-procedures.markdown
