### ISSUE TITLE
Do not see users within project permissions

### ISSUE THREAD

**Issue by Maienfelder** [fguillot/kanboard#1978]
### Expected behaviour

I expect to see a list with all users of the board to add them to a project.

### Actual behaviour
The only user I see is myself.

btw. when I create a new group and try to add group members, I see a dropdown list with the users.
[kanboard add user to project.pdf](https://github.com/fguillot/kanboard/files/164063/kanboard.add.user.to.project.pdf)

### Steps to reproduce

1. within a new (not private) project click
2. Actions
3. Settings
4. Permissions

### Configuration

- Kanboard version: 1.0.26
- Database type and version: MySQL
- PHP version: 5.4.45
- OS: Linux
- Browser: Firefox and Chrome

**Comment by Maienfelder** [comment]
Simplified question: How do I add a user to a project?

**Comment by Maienfelder** [comment]
Is it a possible workaround to add users to projects by adding rows to the table project_has_users? Or alre there any side effects?

**Comment by fguillot** [comment]
![user_autocomplete](https://cloud.githubusercontent.com/assets/323546/13750580/802e0fbc-e9dc-11e5-8f06-54a8f3ecbd0e.png)


In the user section input field, if you type the first letter of the username, you should see an autocomplete box, is it the case?

**Comment by Maienfelder** [comment]
No, I don't see the autocomplete box. Only the mouseover hint to type the user name.
