### ISSUE TITLE
bug : task description in public view @firefox

### ISSUE THREAD

**Issue by DoumeDuSud** [fguillot/kanboard#1983]
### Actual behaviour

the description of a task in the public view is so tiny that it's absolutely cannot be read 

but it's working well on chronium

### Steps to reproduce

1. have a public access on one board
2. go to the description of one task

### Configuration

- Kanboard version: 1.26 &  1.25
- Database type and version: sqlite
- PHP version: 7 & 5.6
- OS: ubuntu serveur
- Browser: firefox 44.0.2

- sous firefox : 
![bug kanboard1 26 public view on firefox](https://cloud.githubusercontent.com/assets/8639236/13642871/87664338-e61e-11e5-8adf-d944243ef77d.png)
- sous chronium : 
![normal kanboard1 26 public view on chronium](https://cloud.githubusercontent.com/assets/8639236/13642912/b4a3bfc4-e61e-11e5-9697-832db1f54e3f.png)

**Comment by fguillot** [comment]
It's should be fixed in 1.0.27

**Comment by DoumeDuSud** [comment]
oui j'ai mise à jour vers la 1.27 et c'est tout bon !! :-)

merci pour tout ce travail et bonne continuation
