### ISSUE TITLE
notification settings should be clearer.

### ISSUE THREAD

**Issue by nerdoc** [fguillot/kanboard#1985]
ATM, in User profile > Actions > Notifications, the settings are a bit unclear for me.

What happens if I uncheck "Enable notifications", but leave "Email" as notification method? Does "I want to receive notifications for:" apply if I have them generally unchecked?

I played around a bit and found that the first one at the top: "Enable notifications", is the "main switch".

What I sould suggest is: if switched off (unchecked), disable all the other options dynamically per javascript.
Would look like this:

![bildschirmfoto](https://cloud.githubusercontent.com/assets/2955584/13651067/eee4cd8c-e645-11e5-95bc-3b13fcd64daa.png)

### Configuration
- Kanboard version: 1.0.26

**Comment by fguillot** [comment]
The form is now improved in 1.0.27, there is no "Enable notifications" checkbox anymore. Notifications will be enabled when at least one method is selected.
