### ISSUE TITLE
Just Installed Kanboard on my Yunohost home server, getting an error

### ISSUE THREAD

**Issue by dospunk** [fguillot/kanboard#1992]
I just did a fresh install of Kanboard through YunoHost and I'm getting this error:

Internal Error: Unable to migrate database schema: \Schema\version_1 => SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'config' already exists

using Firefox is that helps at all

**Comment by fguillot** [comment]
Did report the issue on the Yunohost bug tracker? it's probably related to the way they are provisioning the application.

**Comment by fguillot** [comment]
The issue is probably related to the way that yunohost install KB.
