### ISSUE TITLE
Minimum configuration for openldap authentification backend

### ISSUE THREAD

**Issue by jadjay** [fguillot/kanboard#1997]
### Expected behaviour

Minimum configuration should be suffisant 
LDAP_AUTH, LDAP_SERVER, LDAP_START_TLS, LDAP_BIND_TYPE, LDAP_USERNAME, LDAP_PASSWORD, LDAP_USER_BASE_DN, LDAP_USER_FILTER

### Actual behaviour

With that configuration and even more, can't connect, and debug log isn't helpfull, I see it can't connect but I don't know why. The ldap log isn't more helpfull.

### Steps to reproduce

1. Configure a openldap with memberof overlay
2. configure kanboard LDAP AUTH as explained in doc
3. try to connect a user

### Configuration

- Kanboard version: v1.0.26-57-g7d7b9f7
- Database type and version: sqlite  3.7.13
- PHP version: PHPv5.4
- OS: debian gnu/linux 8
- Browser: Firefox/Chromium

**Comment by fguillot** [comment]
There are more logs from Kanboard if you use enable the debug mode. Maybe that will help you to find the problem.

**Comment by jadjay** [comment]
;-) I told you in the question that i used debug log.

**Comment by fguillot** [comment]
There is now 4 configuration examples for LDAP on the website: https://kanboard.net/documentation/ldap-configuration-examples

I hope you will solve your issue.
