### ISSUE TITLE
Kanboard on Cloudron

### ISSUE THREAD

**Issue by gramakri** [fguillot/kanboard#2002]
Hey, we have packaged Kanboard for Cloudron - https://cloudron.io/appstore.html#net.kanboard.cloudronapp. The Cloudron is a smart server on which you can install web apps (like kanboard). You can add users on the Cloudron and the users can automatically use the installed apps (for kanboard, we use the LDAP integration to achieve this).

The source code of the app is here - https://github.com/cloudron-io/kanboard-app . We have quite a few selenium tests as well (https://github.com/cloudron-io/kanboard-app/tree/master/test) to make sure that kanboard updates go smoothly across versions.

Would you be open to adding Cloudron as part of the docs ? Essentially, as one of the installation options under http://kanboard.net/documentation/ . If so, I can provide a PR.

**Comment by gramakri** [comment]
Feel free to email me as well if you want to discuss anything about the app or Cloudron :-) My email is in my profile.

**Comment by fguillot** [comment]
Thanks for packaging Kanboard in Cloudron.

I have no problem to have Cloudron in the doc (section installation), you can send a PR if you would like.

**Comment by gramakri** [comment]
@fguillot thanks, i am on it.
