### ISSUE TITLE
New Private Project - Add "Columns" as one part to be copied

### ISSUE THREAD

**Issue by anandvshah** [fguillot/kanboard#2003]
### Expected behaviour

New Private Project - Add "Columns" as one part to be copied

### Actual behaviour

Currently when we try to create new private project, it shows "Which parts of the project do you want to duplicate?" containing existing parts. These parts does not list out "Columns". Can we add a feature to allow copying that as well?

### Steps to reproduce

1.
2.
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version:1.0.26
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by fguillot** [comment]
When you duplicate a project, you always duplicate the columns.

**Comment by anandvshah** [comment]
Sorry. My bad. This is working as you said.
