### ISSUE TITLE
please explain cron job to beginner

### ISSUE THREAD

**Issue by Maienfelder** [fguillot/kanboard#2004]
I'am not familiar with bash syntax and I would appreciate someone to explain the cron job.
I understand:
`0 8 * * *` execute the following commands every day at 8 am.
`cd /path/to/kanboard` change to the directory in which kanboard resides
`&&` execute the remainder of the command only if the part before was successfulI 

I don't unterstand
`./kanboard cronjob >/dev/null 2>&1`

**Comment by Ryuk87** [comment]
The command starts `kanboard` cli, executes the `cronjob` command discarding all the output generated. It basically executes the cronjob suppressing the output generated by the command.

**Comment by Maienfelder** [comment]
thank you!

**Comment by PatrickHonorez** [comment]
And on a synology NAS, where there is a graphical interface for this, what command should be entered in the "user defined script" ?
Thanks !

![cron](https://cloud.githubusercontent.com/assets/4831319/17328674/4b693dae-58bf-11e6-888c-f7d09274bc3c.png)

**Comment by toepi** [comment]
> ./kanboard cronjob >/dev/null 2>&1

> - redirect Standard-Output
2> - redirect Standard-Error

&1 - 'append' to Standard-Output

Hope that help to understand the command a little bit more. For cronjobs it is importent to redirect output. If it is not done cron will send (by default email to root) the outputs for every call.
