### ISSUE TITLE
Add comment in task overview only visible if comment already exists

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#2005]
### Expected behaviour

When opening a task you cannot directly add a comment in the task overview. This is only possible when a comment is already existing.

### Actual behaviour

__Add a comment__ segment not present.

### Steps to reproduce

1. Open task without comment
2. Check if __Add a comment__ is visible

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.26
- Database type and version: SQLite
- PHP version: 5.6
- OS: Windows 7
- Browser: Mozilla Firefox 45

**Comment by BlueTeck** [comment]
![image](https://cloud.githubusercontent.com/assets/1961634/13745609/508cf1ac-e9ef-11e5-8143-fcc66cf95e29.png)
![image](https://cloud.githubusercontent.com/assets/1961634/13745616/5ab32a3e-e9ef-11e5-922b-1606ccc25ccc.png)

**Comment by thob** [comment]
one of my users had a similar issue. I changed **Actions** to **Menu** - we'll see if it helps ;-)

**Comment by donpatzone** [comment]
I know it is possible to add via the dropdown. I meant the possibility to add a comment directly in the overview. I think the screenshots will explain it better:

![without_existing_comment](https://cloud.githubusercontent.com/assets/4871330/13781732/a79e19be-eac4-11e5-8c8a-f4f3a661663c.png)
![with_existing_comment](https://cloud.githubusercontent.com/assets/4871330/13781796/dbeed92e-eac4-11e5-9a75-d032845bb489.png)

As soon as a comment is present you have the option to directly add a comment in the overview.

**Comment by bonbonGuy** [comment]
I work around this 'feature' :) by adding an automatic action to add a comment log when moving into my WIP. However, i do agree this would be nice to have it always there regardless.

**Comment by BlueTeck** [comment]
Just a little note, you could add the comment box via a little plugin ;)

**Comment by donpatzone** [comment]
I am aware that it is possible to add via plugin. My thought was to report it as an issue because it is not a coherent experience in my opinion – one time it is here, another time not. It is a __minor__ inconvenience as it does not prevent me from using Kanboard in any way.

**Comment by oparoz** [comment]
I agree with @donpatzone . It feels like a bug. It's been there for a long time and users are now used to a certain way of doing things. In terms of UI it doesn't make much sense to remove comments, but to keep the rest.

**Comment by fguillot** [comment]
With v1.0.27, the comment form always appear at the bottom. You can also use the keyboard shortcut "c" or menu on the left.
