### ISSUE TITLE
[Q] There's a way to override specific controller actions?

### ISSUE THREAD

**Issue by Ryuk87** [fguillot/kanboard#2008]
Hi,
there's a quick way, in a plugin, to override specific controller actions? For example, if a plugin wants to override the `show()` action of the `Project` class, what is the correct way?

Overriding a route could be a possibile solution but the `addRoute` loads plugin's custom route at the end of the route service and the app routes comes always first.

**Comment by Ryuk87** [comment]
Resolved!

**Comment by alefaucheur** [comment]
Hello,
Do you have any idea to rewrite / override any other specific controller?
For instance:  BoardAjaxController (there is no route to it ...)

Thank you ahead of time.
