### ISSUE TITLE
Can we define sub-projects or releases or milestones?

### ISSUE THREAD

**Issue by anandvshah** [fguillot/kanboard#2009]
### Expected behaviour

Facility for defining sub-project or releases or milestones.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version:1.0.26
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by BlueTeck** [comment]
refers to #1009 and #971

**Comment by fguillot** [comment]
Kanboard doesn't supports sub-projects. To discuss about milestones, refer to the mentioned ticket above.
