### ISSUE TITLE
session reset due to consistency problem between ldap and kanboard's db

### ISSUE THREAD

**Issue by lrrb** [fguillot/kanboard#2011]
Hello,

Some of my users complain that they couldn't submit form => Error message : the project name can't be empty. In debug.log, we find : 
> Invalidate session for UserXXX

It's likely due to the fact that in my ldap, username are uppercase and in kanboard's database, they're lowercase. 
However, in **ReverseProxyAuth.php**, the **isValidSession** function is case sensitive :
```
 public function isValidSession()
    {
        return $this->request->getRemoteUser() === $this->userSession->getUsername();
    }
```

### Steps to reproduce

1. Enable the plugin **"Reverse-Proxy Authentication with LDAP user provider"**
2. create users in uppercase in ldap
3. keep **LDAP_USERNAME_CASE_SENSITIVE** to false (default setting)
4. Connect with this new user to kanboard and try to create a new private project

### Configuration

- Kanboard version: 1.0.26
- Database type and version: mysql 5.6
- PHP: 5.3.3

**Comment by fguillot** [comment]
This issue have been fixed in the plugin itself. You can download the version 1.0.1.

Thanks.
