### ISSUE TITLE
not possible to enable notifcation for multiple projects

### ISSUE THREAD

**Issue by mglaubitz** [fguillot/kanboard#2015]
### Expected behaviour

when I select more than one project in my personal profile settings, kanboard should save my choice of (2, 3. ...) projects and send me notifications for these projects

### Actual behaviour

regardless of how many checkboxes / projects I select, only one checkbox / project remains selected after I hit "Save" 

### Steps to reproduce

1. Create 3 Projects
2. Enable the Personal Notfications 
3. Try to active the notfications for ALL three projects

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.26
- Database type and version: MySQL 5.6 (mysql community edition)
- PHP version: 5.5
- OS: openSUSE
- Browser: Firefox 43 + Chrome 49

**Comment by fguillot** [comment]
It's now fixed in the master branch. The SQL constraint was not correct.

Thanks!
