### ISSUE TITLE
Activity stream design

### ISSUE THREAD

**Issue by mcorteel** [fguillot/kanboard#2018]
I have a design proposal for the activity stream. This is of course inspired by Github and issue #1995.
![spectacle tj3057](https://cloud.githubusercontent.com/assets/6164603/13809227/fe28c2b6-eb69-11e5-83fc-8f9f4562261f.png)
This is a partial implementation (it's functional though) but it shows how we could have a more compact activity stream. And with a more compact activity stream, it may be interesting to include it (as suggested in #1995) in the summary of the task. We could then integrate the other functions (sub-tasks/links/etc).

**Comment by mcorteel** [comment]
Here is my design updated:
![spectacle b17175](https://cloud.githubusercontent.com/assets/6164603/13816901/75020a66-eb90-11e5-911e-7d26894c26d6.png)

**Comment by BlueTeck** [comment]
The userimage should have the same size in every row.

**Comment by mcorteel** [comment]
Like in github, I wanted to take advantage of events that don't need to display a content and make them smaller. This saves a lot of vertical space, so that we can display more activity.
If other users feel like you, we can just as easily have a fixed avatar size.

**Comment by mcorteel** [comment]
It's not that bad with a 32px avatar for everything:
![spectacle c20622](https://cloud.githubusercontent.com/assets/6164603/13818601/d163b9f2-eb96-11e5-9552-518ba0df96f4.png)
It does look more natural.

**Comment by fguillot** [comment]
Closing, see comments in PR
