### ISSUE TITLE
description is very, very small

### ISSUE THREAD

**Issue by Maienfelder** [fguillot/kanboard#2023]
The description of a task is displayed extremely small.

![description](https://cloud.githubusercontent.com/assets/17196130/13841976/2a8639b6-ec2c-11e5-93ab-416faacf1829.PNG)

Tested with firefox, edge and chrome.

    Kanboard version: 1.0.26
    Database type and version: MySQL
    PHP version: 5.4.45
    OS: Linux
    Browser: Firefox and Chrome

**Comment by BlueTeck** [comment]
Could you please provide the information from the issue template.

Kanboard version:
Database type and version:
PHP version:
OS:
Browser:

And the text from the description?

**Comment by Maienfelder** [comment]
Thank you. I updated  my post.
the text from the description is "sample text"

**Comment by EpocDotFr** [comment]
This happens also for me in a random way on Firefox, regardless of the PHP and Kanboard version. A page refresh immediatly fix this issue.

Happens also on other websites, not only Kanboard.

**Comment by Maienfelder** [comment]
Page refresh doesn't help on my machines.

**Comment by froschdesign** [comment]
@Maienfelder 
Please check the font size with the developer tools of your browser.

For Firefox:

- [Open the Inspector](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector)
- [Select an element](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element)
- [Examine and edit CSS](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS)

**Comment by Maienfelder** [comment]
it seems to have inherited a font size=1 from article
![inherited](https://cloud.githubusercontent.com/assets/17196130/13849672/6ad60980-ec57-11e5-92cb-0ea474d7b3d7.PNG)

**Comment by EpocDotFr** [comment]
Seems that the browser randomly fails to apply [this CSS font-size style](https://github.com/fguillot/kanboard/blob/master/assets/css/src/markdown.css#L4).

**Comment by mcorteel** [comment]
What's really weird, is that the rule in Firefox is `font-size: 1.0` when it should be `font-size: 1.0em`.
Firefox obviously interprets it as 1px. But this rule does not exist...

**Comment by Maienfelder** [comment]
Thank you all for your comments. They helped me to find and solve the problem. The cause is somewhat embarrassing to me. I am running Kanboard on a webspace provided by my university. In the top directory, there was an index.html that pointed to a css (to make it easy for public sites to follow  the corporate design rules).
I deleted the index.html and descriptions are perfect now.

**Comment by Maienfelder** [comment]
Meanwhile, I tried once more and the descriptions are very small again.

**Comment by Maienfelder** [comment]
On my local XAMPP installation of kanboard, the description is ok. Any hints, where to search for errors?

**Comment by Maienfelder** [comment]
in assets/css/app.css there was
`markdown{line-height:1.4em;font-size:1.0}`
at position 21:16543.
After replacing with
`markdown{line-height:1.4em;font-size:1.0em}`
the descriptions look fine.

**Thank you all for your support.**

**Comment by EpocDotFr** [comment]
Can you please make a pull request?

**Comment by froschdesign** [comment]
@EpocDotFr 
[In the current version there is no value `1.0`.](https://github.com/fguillot/kanboard/blob/master/assets/css/src/markdown.css)

**Comment by Maienfelder** [comment]
The error is in the actual download version, but not in the master.
