### ISSUE TITLE
burndown chart shows wrong total for all columns

### ISSUE THREAD

**Issue by kwijk** [fguillot/kanboard#2025]
### Actual behaviour

The value for "Total for all columns" is wrong: The values '4', '0', '0', '0', '0' and '0' are concatinated instead of summed.

![picture1](https://cloud.githubusercontent.com/assets/12728041/13873526/577bef62-ecf2-11e5-8efd-581b942d7f4c.png)

### Steps to reproduce

1. add some tasks to board
2. add complexity values to each task
3. goto analytics and select burndown chart
4. hoover mouse over any datapoint

### Configuration

About

    Official website: http://kanboard.net/
    Application version: 1.0.26
    Author: Frédéric Guillot (contributors)
    License: MIT

Database

    Database driver: sqlite
    Database size: 689k
    Download the database  (Gzip compressed Sqlite file)
    Optimize the database  (VACUUM command)

**Comment by fguillot** [comment]
Thanks, it's now fixed in master.
