### ISSUE TITLE
Internal Error: The directory "data" must be writeable by your web server user

### ISSUE THREAD

**Issue by peasead** [fguillot/kanboard#2029]
### Expected behaviour

The Kanboard login page should be displayed after starting the Kanboard Docker container.

### Actual behaviour

I get the following error when running the Kanboard Docker container and trying to view the login page:
`Internal Error: The directory "data" must be writeable by your web server user`

### Steps to reproduce

1. Build the Docker container per the normal `docker build -t kanboard .` command
2. Start the container with the following syntax:  
`docker run -d -p 8080:80 --name kanboard -v /tmp/data/kanboard:/var/www/kanboard/data -v /tmp/data/kanboard/plugins:/var/www/kanboard/data/plugins kanboard`
3. Receive the error when browsing to `http://hostIP:8080`

### Configuration

- Kanboard version: Latest Dockerfile
- Database type and version: Latest Dockerfile
- PHP version: Latest Dockerfile
- OS: Atomic Host (Fedora)
- Browser: Chrome

### Troubleshooting

I tried to chmod -R /tmp/data to ensure that everything could write to the directory - no luck 
I tried `docker run -d -p 8080:80 --name kanboard kanboard` and the container runs as expected, but I have no persistent storage 
I ran `chmod -R 777 /tmp/data` in an attempt to allow access 
I (begrudgingly) tried `setenforce 0`

### Caveat

I'm no Docker expert, I assume that there is something I may need to add to the Dockerfile to define a user...or something I need to create a user to allow containers to write to the host OS?

**Comment by peasead** [comment]
I figured this out...it was a misunderstanding on how container volumes work.

The Dockerfile has `/var/www/kanboard/data` and `/var/www/kanboard/data/plugins` as `VOLUME` instructions, and those are stored at `/var/lib/docker/volumes/<id>/_data`.

I found this by running `docker inspect kanboard` (name of the container)
```
  "Mounts": [
        {
            "Name": "e07ab4a00ec8d723a2717530414ccfb2e0369ecb1c72d6be82b2b86a9ac6d131",
            "Source": "/var/lib/docker/volumes/e07ab4a00ec8d723a2717530414ccfb2e0369ecb1c72d6be82b2b86a9ac6d131/_data",
            "Destination": "/var/www/kanboard/plugins",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "fdd35246b0c124d97ebedc4e9b95621d985362582d0529e964f4fe4272d4855c",
           "Source": "/var/lib/docker/volumes/fdd35246b0c124d97ebedc4e9b95621d985362582d0529e964f4fe4272d4855c/_data",
            "Destination": "/var/www/kanboard/data",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
```

**Comment by allustin** [comment]
similar issue

1. if i mount in docker 1.11.3 volume drives from host, like this

```
 -v /home/ubuntu/kaboard/data:/var/www/kanboard/data \
 -v /home/ubuntu/kaboard/plugins:/var/www/kanboard/plugins \
```

2. and then logon into container and run `ls -al /var/www/kanboard/`

```
ubuntu@backstage:~/board$ docker exec -it my-kanboard bash
bash-4.3# ls -al /var/www/kanboard/ | grep data
drwxr-xr-x    2 root     root          4096 Jun 18 16:14 data
bash-4.3#
bash-4.3# ls -al /var/www/kanboard/ | grep plugins
drwxr-xr-x    2 root     root          4096 Jun 18 16:14 plugins
bash-4.3#
```

i have see - the `data` and `plugins` have owner `root`

if i run the container without mounting a volume we have

```
ubuntu@backstage:~/board$ docker exec -it my-kanboard bash
bash-4.3#
bash-4.3#  ls -al /var/www/kanboard/ | grep data
drwxrwxrwx    2 nginx    nginx         4096 Jun 18 16:42 data
bash-4.3#
bash-4.3#  ls -al /var/www/kanboard/ | grep plugins
drwxrwxrwx    2 nginx    nginx         4096 Jun 18 16:42 plugins
bash-4.3#

```

seem to be wthat we have a strange behavior of docker... but ;-) there is a fix for what

**kanboard NEED to be run with sudo** like this

```
sudo docker run -d --restart="on-failure:1" -p 80:80 --name my-kanboard kanboard/kanboard \
        -v /home/ubuntu/kaboard/data:/var/www/kanboard/data \
        -v /home/ubuntu/kaboard/plugins:/var/www/kanboard/plugins
```

and then you have see

```
ubuntu@backstage:~/board$ docker exec -it my-kanboard bash
bash-4.3#
bash-4.3#  ls -al /var/www/kanboard/ | grep data
drwxrwxrwx    2 nginx    nginx         4096 Jun 18 16:42 data
bash-4.3#
bash-4.3#  ls -al /var/www/kanboard/ | grep plugins
drwxrwxrwx    2 nginx    nginx         4096 Jun 18 16:42 plugins
bash-4.3#

```

this bug (or feature) will be reproduce, then you add your user to docker group, like its recomended in docker install.

**Comment by Simon-L** [comment]
I also had this error with the Docker image, you can simply `chown` the folders used for volumes:
`sudo chown -R 100:101 /mnt/data/kanboard/`

Change `/mnt/DATA/kanboard` to the folder where the /data and /plugins volumes are stored.
100 and 101 are user and group ids for nginx inside the container, respectively. You can check these using:
`docker exec -ti kanboard id nginx`.
