### ISSUE TITLE
[compliment] I like the new task details design

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#2030]
Hi @fguillot,

I just pulled the latest master and just want to say, that I like the new task details design!!!

Keep it up,
Timo

**Comment by BlueTeck** [comment]
But the task in board looks strange, too much space.

![image](https://cloud.githubusercontent.com/assets/1961634/13904190/7b14e152-ee98-11e5-9dde-72fd7b5baafc.png)

**Comment by jtourt** [comment]
@fguillot,

Yes, compliments on the new design are deserved.  Thank you for putting the action sidebar back in task view and improving the sidebar design.  Thank you. Thank you. The change to the actions menu in v1.0.25 rattled me (#1808), and it seems other people were confused by the new design (#1919), too.  But that's in the past.  The new design looks great!

(As an aside, it's probably still being worked on, but clicking on "change sorting" in the comments section causes an  "Internal Error: Action not implemented" message.)

Echoing BlueTeck's comment above, the letter avatar placement could benefit from fine tuning to conserve space.

**Comment by fguillot** [comment]
Thanks guys. The avatar is now on the top right corner.
