### ISSUE TITLE
[new Plugin] Metadate Manager

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#2032]
Hi,

I just want to let you know about my new little plugin to manage [metadata](https://github.com/fguillot/kanboard/blob/master/doc/plugin-metadata.markdown) via GUI:

![image](https://cloud.githubusercontent.com/assets/1961634/13904924/2cc1c02e-eeb1-11e5-9ec3-90fac668bce3.png)

Manage Metadata for:
* task
* user
* project

This is only the first release, I have some ideas for the next version. PR and ideas are welcome.

Plugin: https://github.com/BlueTeck/kanboard_plugin_metadata/releases/tag/1.0.0

**Comment by jtourt** [comment]
Thumbs up.   I'm not currently using metadata, but this might help get me started.

One suggestion that springs to mind immediately, the ability to edit existing metadata. Not just remove/add.

**Comment by BlueTeck** [comment]
If you enter metadata with the same key it will "edit" the value, but you are right, an edit button might be usefull. -> https://github.com/BlueTeck/kanboard_plugin_metadata/issues/6

**Comment by BlueTeck** [comment]
> One suggestion that springs to mind immediately, the ability to edit existing metadata. Not just remove/add.

There is an edit button now ;)

![image](https://cloud.githubusercontent.com/assets/1961634/13924808/ffdb8736-ef85-11e5-9868-104abdf52ce1.png)

**Comment by fguillot** [comment]
If you want to publish your plugin on the website, you can send a PR here https://github.com/kanboard/website
