### ISSUE TITLE
[Plugin] Metadata Toolkit

### ISSUE THREAD

**Issue by Ryuk87** [fguillot/kanboard#2033]
Hey! :)
I'm working on a plugin to use the simplify and enhance Metadata use.

Briefly, the plugin does as follow:

- In the Kanboard settings page there is a view to create Metadata types. You can specify a friendly name, if it's required, the entity to attach it and the type (text, integer, boolean...)
- When a user creates a new entity (project, user or task), he will see  the additional metadata created by the admin as new form field. (The code then validates the user input based on the metadata type declared)
- This new data will be shown in the project/user/task base as additional info.

https://github.com/Ryuk87/kanboard-metadata-toolkit/tree/develop
Currently I'm working in the "develop" tree so master is pretty empty :) 

I think I will be able to release a first "beta" version during the week.

If you think you could need additional feature, feel free to open an issue directly in the repo.

Every idea is really appreciated :)

**Comment by BlueTeck** [comment]
Hmmm thats what I wanted with https://github.com/BlueTeck/kanboard_plugin_metadata too. Maybe we should work on one plugin instead of two ;)

**Comment by Ryuk87** [comment]
@BlueTeck sorry, I did not saw your plugin :) Sure, I can integrate my logic in you code if that's ok!

**Comment by BlueTeck** [comment]
@Ryuk87 sounds good, the modell controller etc could coexists at the moment, only the Plugin.php has to be merged.

**Comment by Ryuk87** [comment]
@BlueTeck Thanks! :)

**Comment by Ryuk87** [comment]
Merging into #2032
