### ISSUE TITLE
Commit: "Added Markdown editor and Javascript code refactoring" enter bug with select text ..

### ISSUE THREAD

**Issue by JohnBat26** [fguillot/kanboard#2036]
### Expected behaviour
When I add new task in taskboard and select description then  new-task-popup  hasn't close

### Actual behaviour
When I add new task in taskboard and select description then  new-task-popup closed suddenly without save of data :(

Tell us what should happen

This commit:
~~~
commit f77d6c590bf683377986064113ddddae9ed443c2
Author: Frederic Guillot <fred@kanboard.net>
Date:   Sun Mar 20 15:45:02 2016 -0400

    Added Markdown editor and Javascript code refactoring
~~~
 add this bug

### Steps to reproduce

1. Click "+" on taskboard for add new task
2. Type any text to task description
3. Select typed text
4. New-task popup closed suddenly

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: master (last commit 45f21e1cd8e09e39d5f74d8826b27fc202428b3c)
- Database type and version: PostgreSQL 9.5
- PHP version: 5.6.19
- OS: CentOS 7.2
- Browser: Chrome  49.0.2623.87

**Comment by fguillot** [comment]
Do you still have the issue because I'm not able to reproduce with the same browser version?

Do you have Javascript errors in the console or anything else? Did you flush the browser cache, just in case?

**Comment by NioFBI** [comment]
Played when the mouseup event on #Popover-container.
(example: text selection).
I propose to make the box "Close without saving?" @Close@ @No@
