### ISSUE TITLE
Link to Task in Comments

### ISSUE THREAD

**Issue by Kolesar** [fguillot/kanboard#2056]
### Expected behaviour

When click on link task (created by #) open task

### Actual behaviour

Get permission denied

### Steps to reproduce

1. Create project one
2. Create task inside project one
3. Create another project
4. Create task inside second project
5. Add comment inside task from first project with relation/link to second task from second project (with #)
6. Try to click on generated link

### Configuration

    Application version: master
    PHP version: 5.6.11-1ubuntu3.1
    PHP SAPI: apache2handler
    OS version: Linux 4.2.0-34-generic
    Database driver: mysql
    Database version: 5.6.28-0ubuntu0.15.10.1
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

For fix this issue, use follow code inside ``Markdown`` class:
```
    protected function inlineTaskLink(array $Excerpt)
    {
        if (! empty($this->link) && preg_match('!#(\d+)!i', $Excerpt['text'], $matches)) {
            if(array_key_exists('project_id', $this->link['params'])) {
                $this->link['params']['project_id'] = $this->container['taskFinder']->getById($matches[1])['project_id'];
            }
```

**Comment by fguillot** [comment]
Thanks to report this issue. It's now fixed in master.
