### ISSUE TITLE
 Multi board project (Feature request)

### ISSUE THREAD

**Issue by homayouni** [fguillot/kanboard#2058]
### Expected behavior

When a project size is a little big and several contributes involve, multi board project is required with access right of project members to specific boards in a project.

**Comment by fguillot** [comment]
Probably a duplicate with #6.

**Comment by homayouni** [comment]
I could not find the requested feature in your great work which you have commented as Duplicate
Is that really a project can have several boards and some member can access some and others can access others and the supervisor can see all boards in one dashboard? please advise.

**Comment by gabimem** [comment]
+1
