### ISSUE TITLE
There is no suitable CSPRNG installed on your system

### ISSUE THREAD

**Issue by SiriusPrime** [fguillot/kanboard#2060]
### Expected behaviour

Starting kanboard in web browser after copying new version 1.0.27 to web server.

I have older version (1.0.26) running on my server already.

### Actual behaviour

only this error message: 

Internal Error: There is no suitable CSPRNG installed on your system

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version: mysql 5.0.11
- PHP version:5.6.19
- OS: Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u5 x86_64
- Browser: Mozilla Firefox 45.0.01

**Comment by rylangrant** [comment]
Same issue, similar setup but fresh install.

**Comment by PatDeLux** [comment]
Same issue with my Synology NAS. Version 1.0.26 works like a charm.

**Comment by ocean123** [comment]
Same issue overhere. How can I solve the problem

**Comment by frankvanderheyden** [comment]
Same problem on my Synology NAS. Version 1.0.26 works OK.

**Comment by szawadski** [comment]
Hello, I confirm the problem with version 1.0.27 on my Synology NAS

**Comment by eagle243** [comment]
Yup, I noticed the same issue when upgrading from 1.0.25 on my Synology.

**Comment by fguillot** [comment]
This is coming from the library https://github.com/paragonie/random_compat, do you have at least openssl or mcrypt and /dev/urandom?

**Comment by eagle243** [comment]
Hi Fréderic.

The Synology does have /lib/libmcrypt.so.4, as well as openssl, and /dev/urandom.

Version 1.0.25 works fine on Synology, but 1.0.27 does not.

Daniel

**Comment by kero242** [comment]
"Internal Error: There is no suitable CSPRNG installed on your system"
same here with ubuntu 14.04 and kanboard 1.0.27

**Comment by oliviermaridat** [comment]
It seems to be related to this issue on the random_compat component: https://github.com/paragonie/random_compat/issues/99

**Comment by kero242** [comment]
adding 
/dev/urandom to the open_basedir directive fixes my problem.

**Comment by erok997** [comment]
Confirmed that adding /dev/urandom to the open_basedir directive, specifically within the Synology NAS Web Services Control Panel Pane, PHP Settings, "Customize PHP open_basedir" field fixed this issue.

**Comment by PatDeLux** [comment]
confirmed as well that adding /dev/urandom to the open_basedir directive
on my Syno 710+ fixed the issue.

**Comment by frankvanderheyden** [comment]
confirmed also adding /dev/urandom to the open_basedir directive
on my Syno 211+ fixed the issue.

**Comment by szawadski** [comment]
I also confirm adding /dev/urandom has solved my issue
Thanks to all of you.
Regards,
Sébastien

Le mar. 5 avr. 2016 à 17:10, frankvanderheyden <notifications@github.com> a
écrit :

**Comment by fguillot** [comment]
I updated the FAQ.

**Comment by sleepywitti** [comment]
It's also possible to downgrade random_compat to [1.4](https://github.com/paragonie/random_compat/releases/tag/v1.4.0), which still supports OpenSSL instead of /dev/urandom. Just replace the files in `kanboard/vendor/paragonie/random_compat`.

**Comment by amiceli** [comment]
I had the same problem, i found this [article](https://forum.synology.com/enu/viewtopic.php?t=87176).
To fix **CSPRNG ** error, I added /dev path to open_basedir options.

Maybe this fix can be added on FAQ ?

**Comment by luchothoma** [comment]
Sorry, I'm installing Kanboard.net in a free hosting account and I get in troubel cause it run on error message (In local XAMPP it run well) going with this "_Internal Error: There is no suitable CSPRNG installed on your system_"

Can some one give me a solution?

**Comment by hauserulrich** [comment]
I upgrade from 1.0.25 on a hosted account. The solution of  amiceli worked for me.

**Comment by skreisel** [comment]
Any idea how to get past this if one is using a hosted system where changes to open_basedir settings are blocked?
Cheers!

**Comment by skreisel** [comment]
Answering myself: sleepwitty's instructions are how to do it. To clarify for those of us without computing intuition: on the site of the [link](https://github.com/paragonie/random_compat/releases/tag/v1.4.0) one has to download the zip, delete the contents of the  `kanboard/vendor/paragonie/random_compat` directory on your installtation and unpack the zip there - adding the downgraded version. Voilà...

**Comment by z-works** [comment]
sleepwitty & skreisel: yes it worked out. Now 1041 runs instead of 1023. Thanks!

**Comment by luchothoma** [comment]
I read in PHP manual, and this CSPRNG does not come with versions before 7.X, also you can download and install the library standalone but for my case I use a shared free hosting so I can't install anything but happily I have permision to switch between some versions of PHP and 7.0 was in that list !

I hope this help someone later.

**Comment by marcosaccioly** [comment]
@skreisel thank's for the clarification on @sleepywitti 's solution. Nailed it.
