### ISSUE TITLE
[API] Search tasks by critera

### ISSUE THREAD

**Issue by abouquet** [fguillot/kanboard#2064]
Hi,

I would like to be able to browse for task with a more complex API with a method like
`getTaskByCritera` to be able to filter only by columns and/or swimlanes

Where the post method should contain one or more criterias with the same params contained in the createTask method

```
{
    "jsonrpc": "2.0",
    "method": "getTaskByCriteria",
    "id": 133280317,
    "params": {
        "project_id": 1,
        "status_id": 1,
         //Added
        "column_id":1,
        "swimlane_id:1"
        etc..
    }
}
```

would it be possible to update the API for this purpose ? 

Thanks

**Comment by fguillot** [comment]
You can now use the method `searchTasks($project_id, $query)` in master.
