### ISSUE TITLE
Release "Kanboard Milestone Plugin"

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#2065]
I have created a first release for the [Milestone plugin](https://github.com/oliviermaridat/kanboard-milestone-plugin). It targets the last (and fresh!) version of Kanboard (1.0.27). I plan to make a new release at least for each new release of Kanboard in order to keep compatibility.

@fguillot, is it possible to add it in the list of plugins for Kanboard? Thank you!

**Comment by fguillot** [comment]
Hi Olivier,

The source code of the website is available on Github now. If you want to publish your plugin on the website, you can send a pull-request. In this way, you can choose the description and the text you would like to have.

https://github.com/kanboard/website#how-to-add-a-new-plugin-to-the-list

Thanks
