### ISSUE TITLE
Privacy break with public link to a project

### ISSUE THREAD

**Issue by seynaeve** [fguillot/kanboard#2067]
When creating a public link to a project, and that our customer clicks on a spot he obtien the unique link and to a public spot Ex: kanboard / public / task / 2473 / b8a4eba508b8ebf2768e5acfc0e8d6194393d511ebba93dd7471a7b688d6
If it changes by 2473 any lower number, he can see any spots, including outside its project :-(

- Kanboard version: 1.0.22

**Comment by fguillot** [comment]
It was already reported and fixed, you should update your Kanboard instance.

**Comment by seynaeve** [comment]
Thx a lot

Merci

<http://wepika.com/> Edouard Seynaeve <http://wepika.com/> Technico-strategist
(e-commerce / prestashop) <http://wepika.com/>
[image: Email icon] <cgillard@wepika.com> edouard@wepika.com [image: Phone
icon] (+32)498.17.73.19 [image: Twitter icon] <http://twitter.com/seynaeve>
@seynaeve <http://twitter.com/seynaeve>



RueDuWeb <http://www.rueduweb.be/> (3e étage) 6 rue Emile Francqui, 1435
Mont-Saint-Guibert, Belgium
<https://maps.google.com/maps?q=Wepika+%7C+e-commerce+agency,+1+rue+Emile+Francqui,+1435+Mont-Saint-Guibert,+Belgium&hl=en&ie=UTF8&sll=50.656902,4.623878&sspn=0.062793,0.169086&hq=Wepika+%7C+e-commerce+agency,&hnear=Rue+Emile+Francqui,+Mont-Saint-Guibert+1435+Mont-Saint-Guibert,+Brabant+Wallon,+R%C3%A9gion+wallonne,+Belgium&t=m&z=16>
[image:
Facebook icon] <http://www.facebook.com/wepika> [image: Twitter icon]
<http://twitter.com/wepika> @wepika <http://twitter.com/wepika>

On Tue, Mar 29, 2016 at 11:16 PM, Frédéric Guillot <notifications@github.com
