### ISSUE TITLE
Undefined index on trying to remove a comment

### ISSUE THREAD

**Issue by gene-pavlovsky** [fguillot/kanboard#2069]
After upgrading to 1.0.27, I get the following notice messages when trying to remove a comment from a task:
```
Do you really want to remove this comment?

Notice: Undefined index: email in C:\project\www\kanboard\app\Template\comment\show.php on line 3

Notice: Undefined index: avatar_path in C:\project\www\kanboard\app\Template\comment\show.php on line 3
```

**Comment by fguillot** [comment]
It's fixed in master, Thanks.

**Comment by gene-pavlovsky** [comment]
For testing, is it safe to clone the repo and just copy over my current installation?

**Comment by fguillot** [comment]
No, removed and renamed files will stay there. You are better to clone the repo, then copy your data folder inside (see install/update doc).

**Comment by gene-pavlovsky** [comment]
Ok, there are no more `Notice` messages. Thanks for the fix.
