### ISSUE TITLE
Don't highlight task changes done by myself

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#207]
Updating my kanboard install to latest git master, I see that items now get a light blue glow around them after you edit them or even just move them... what's that glow meant to represent? The documentation doesn't tell me and I find it confusing because it never seems to go away.

**Comment by fguillot** [comment]
The behavior of this feature have changed, now that just display a shadow around the card for recently modified tasks. That maybe removed later since it's not really useful.
