### ISSUE TITLE
Contrib: git hooks to comment/close issues in kanboard

### ISSUE THREAD

**Issue by gene-pavlovsky** [fguillot/kanboard#2070]
I've made a simple PHP script that uses regexps to detect issue ids mentioned in a comment. The script then contacts Kanboard using JSON-RPC and either validates that issues exist and belong to the specified project, or adds comment to the issues, and optionally moves them to the specified column.

There are also two git hooks: 
- `commit-msg` detects and validates issue ids in the commit message. If validation fails, the commit is aborted. Optionally, if no issue ids are mentioned, commit is also aborted.
- `post-commit` runs after commit is made, and: adds comments, optionally moves issues to the specified column (e.g. `Done`).

Wherever I mentioned `issues` I mean Kanboard `tasks`.

I hope these hooks can be useful, maybe you can add them in `contrib` folder, or do you think I should create a separate repository myself and put them there?

https://dl.dropboxusercontent.com/u/49471027/kanboard-hooks.7z

Example of what the RegExps can detect: all of the issues mentioned here in there:
```
Sample log message to test the regex strings.

Testing mentions of issues inside a text: Mention single issue #55. Mention issues #77, #78 and #79. Mention more issues #123, #124 and #125 and some more separate ones: Issue #45, issue #46 and issue #47.

Related issues: #10, #11 and #13.

All of the following will be moved to Done:
Implements issue #101
Fixes bug #202
Fixed #123
Closes #99.
Closed #333, #334 and #335.
Closed: #10, #20.
```

**Comment by gene-pavlovsky** [comment]
I've somewhat improved the hooks since then.
When amending a commit, the script attempts to amend the Kanboard task comments.
I've uploaded the hooks to a new repo on github.
https://github.com/gene-pavlovsky/kanboard-git-hooks

**Comment by fguillot** [comment]
I added your project to the list of related projects: https://github.com/fguillot/kanboard/blob/master/doc/faq.markdown#where-can-i-find-a-list-of-related-projects

Thanks!

**Comment by gene-pavlovsky** [comment]
Thanks!
