### ISSUE TITLE
[FR] Auto-update hosted application

### ISSUE THREAD

**Issue by thob** [fguillot/kanboard#2073]
### Expected behaviour

easily update your install if a new version (or a fix) of KB is out. Like we have it for WordPress, see
http://maxmorgandesign.com/simple_php_auto_update_system/

**Comment by fguillot** [comment]
It was already asked in #896

**Comment by BlueTeck** [comment]
@fguillot wrong issue?

**Comment by fguillot** [comment]
Sorry it was #894
