### ISSUE TITLE
Advanced Search Syntax: "created:-100 days" not working

### ISSUE THREAD

**Issue by jniggemann** [fguillot/kanboard#2075]
### Expected behaviour

I put "status:open created:<-100 days" as a search.
I expect to see all tasks that I created more than 100 days ago.

### Actual behaviour

No tasks are found.
The syntax "status:open created:<2015-07-01" works though.

### Steps to reproduce

see above

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.26
- Database type and version: sqlite3 3.6.20
- PHP version: 5.6.32.0
- OS: CentOS 6.7
- Browser: Firefox 45.0.1

**Comment by fguillot** [comment]
With the current development version, the syntax `status:open created:<"-100 days"` is now supported. The double quotes are required.
