### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by mcorteel** [fguillot/kanboard#2076]
I wonder if there is a reason why kanboard doesn't have a dedicated IRC channel. Most free software communities do, and I think kanboard could benefit from this direct communication channel.
What do you think? Is there already such a chan maybe?

**Comment by fguillot** [comment]
Probably because I prefer async communications.

Just to try, I created a room on Gitter a couple of weeks ago. Maybe I should create a channel on Freenode.

**Comment by mcorteel** [comment]
Yes, I think that would make sense. You could put a link on the website. It
would help users get help without overcrowding the bug tracker.

2016-03-31 18:48 GMT+02:00 Frédéric Guillot <notifications@github.com>:

**Comment by fguillot** [comment]
I created a new IRC channel on Freenode `#kanboard` or  `ircs://chat.freenode.net:6697/#kanboard`

I don't necessary answer right way even if my user is connected all the time.
