### ISSUE TITLE
'Set start date' disregards international date setting

### ISSUE THREAD

**Issue by jvlekken** [fguillot/kanboard#2082]
The start_task function (available trough the 'Set start date' in the task view) assumes a different date format than the 'edit task' view

For example:
- Today is 1 april 2016 (Kanboard setting for date notation in my region = 01/04/2016)
- Push 'Set start date' button
- Click 'Edit the task'
- The start date seems filled in as '01/04/2016'
- I select a due date trough the calendar/date-picker, notice how the notation is 2016-04-06, I guess the bug happens somewhere around here.
- save the task

When I look for example in the Gant chart, Kanboard seems confused and changed the startdate to January 4th 2016.

Can somebody reproduce this error?
Thank you!

**Comment by fguillot** [comment]
At the moment, the date picker will always show the date in iso8601 format. However, when the date is displayed somewhere, you local format should be used.

**Comment by angystardust** [comment]
Same issue here (italian timezone) :cry:

**Comment by jvlekken** [comment]
It seems to swap dd/mm/yy with mm/dd/yy on start date and due date when updating a task. But only in case you did not touch the start and due date fields.

I believe this only occurs when the date format is not set to mm/dd/yy.

**Comment by milankni** [comment]
Same here. English lang, manually set date format to MM/DD/YYY.

**Comment by angystardust** [comment]
@milankni thanks for your detailed report.
I agree with you that this issue should be marked as a bug.

**Comment by damo2015** [comment]
Same issue here, I'll be glad when its fixed. Everytime I edit a task my calendar gets all messed up.
