### ISSUE TITLE
1.0.27 doesn't run on Synology

### ISSUE THREAD

**Issue by eagle243** [fguillot/kanboard#2083]
### Expected behaviour

1.0.25 runs fine on Synology DSM 6.0.  1.0.27 presents an error about CSPRNG.

### Actual behaviour

When I load https://SERVERNAME/kanboard, it tells me "Internal Error: There is no suitable CSPRNG installed on your system"

### Steps to reproduce

1. Install Kanboard 1.0.27 on Synology
2. Ensure that data directory is writeable by Apache user
3. Load the main kanboard URL

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version: SQLite 3.10.12
- PHP version: 5.6.11
- OS: Synology DSM 6.0 (Linux)
- Browser: Safari 9.1

### Other comments
I grepped for CSPRNG and found the error message in the source (kanboard/vendor/paragonie/random_compat/lib/random.php) and then diffed that file from 1.0.25 to 1.0.27 and didn't see why that CSPRNG error message would be showing up in 1.0.27.

**Comment by eagle243** [comment]
This issue is a duplicate of another one.  Not sure why I didn't see the other one before opening this one.  Sorry about that.

**Comment by BlueTeck** [comment]
#2060
