### ISSUE TITLE
Unable to add comments to tasks

### ISSUE THREAD

**Issue by golharam** [fguillot/kanboard#2085]
### Expected behaviour

I'm using version 1.0.26.  I create a task, then clicked on the task to view it.  When viewing the task, there is no button to add comments anymore.  This used to be available in previous versions.

### Actual behaviour

When viewing a task, there should be a button to add comments.  It appears I have to click on the tasks id, then I can add a comment.  Once a comment exists, I can then view the task, scroll to the bottom and add additional comments.

### Steps to reproduce

1.  Create a task.
2.  Click on the title of the task to view the task.
3.  Scroll down to add a comment, and there is not way to do this.
4.  Go back to viewing the board.
5.  Click the task's id, then select Add Comment.
6.  Add comment.
7.  Click the tasks title to view the task
8.  Scroll down the bottom to add a comment, and now you can add comments.

### Configuration

- Kanboard version: 1.0.26
- Database type and version: MySQL
- PHP version: 5.3.3
- OS: Windows 7 (Client), Server is CentOS 6.5
- Browser: Chrome

**Comment by jtourt** [comment]
Starting with version 1.0.25 most of the sidebar items were moved to the Actions menu.
In version 1.0.27 the side bar action items were brought back.

- In v1.0.26, click the Actions menu --> Add a comment.  (#1919)

or

- Upgrade to v1.0.27 and the sidebar items will be back to where you expect them.

**Comment by fguillot** [comment]
You should upgrade to 1.0.27, there are 3 ways now to create comments on the task summary page:

- Use the link on the left sidebar
- Use the keyboard shortcut "c"
- Expand the comments section and write your comment
