### ISSUE TITLE
LDAP Group Synchronization is not working

### ISSUE THREAD

**Issue by ibirisol** [fguillot/kanboard#2094]
Hi there,

Follow below a issue about LDAP Group Sync in kanboard setup.

I'm using OpenLDAP and kanboard's configuration is working fine for auth and group search process.
However I was expected the users were in the LDAP group member page, but anyone is there. Every LDAP Group are empty.

How can verify if the group members are taking properly? My OpenLDAP setup is as groupOfNames and I'm using member attribute with full user DN. 
I not found in the code of LDAP backend a segment with Group Member Sync, and I did'nt see a parameter to define something like LDAP_GROUP_ATTRIBUTE_USERS to take member by custom attribute.

### Configuration

- Kanboard version: 1.0.26
- Database type and version: postgres
- PHP version: 5.6.19
- OS: Debian GNU/Linux 8.4 (jessie)
- Browser: chromium / iceweasel

**Comment by frederikheld** [comment]
+1. I am very interested in LDAP Group Sync as well.

**Comment by fguillot** [comment]
At the moment, groups sync is only supported with the overlay "memberOf" or the default settings of ActiveDirectory.

I plan to improve this feature to support more LDAP configurations.

Can you provide an example of how your users and groups are configured in your LDAP directory? (LDIF entries with groupOfNames)

**Comment by fguillot** [comment]
Latest Kanboard now supports ActiveDirectory, OpenLDAP with memberOf, groupOfNames and Posix Groups.

There are 4 different examples on the website to help you to configure that: https://kanboard.net/documentation/ldap-configuration-examples
