### ISSUE TITLE
Blank page in public link for a empty board

### ISSUE THREAD

**Issue by IxeYgrek** [fguillot/kanboard#2100]
### Expected behaviour

Tell us what should happen

Blank page in public link for a empty board

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.create new empty board
2.active public link
3.click to public link

Page are blank

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

 Application version: 1.0.26 
 Database driver: sqlite 
- PHP version: 5.6
- OS: Windows 7
- Browser: Firefox

**Comment by levlaz** [comment]
I ran into the same issue today, it took me a few minutes to realize that the functionality was not broken. @fguillot I would like to take a stab at this issue, do you have anything in mind for what the page should look like if the board is empty?

I was thinking of something like this: 

![kanboardemptyboardpublic](https://cloud.githubusercontent.com/assets/7981032/15836281/e435ad14-2be8-11e6-81ff-35d823f3a82a.png)

**Comment by fguillot** [comment]
@levlaz The most simple way is probably to display an alert message that says "There is no tasks yet..".

**Comment by fguillot** [comment]
This now fixed fixed in dev. Now that display an empty board instead.
