### ISSUE TITLE
feature request: edit without authenticification

### ISSUE THREAD

**Issue by wrkb** [fguillot/kanboard#2101]
### Expected behaviour

like open wikis: for our tiny intranet purposes (kanboard is not reachable from internet) it would be great, when my colleagues and me could use the boards without authentification. i'm not sure, if this is possible, but it would be big help...
...when others only should see the contents, without edit intention
...it would be okay for our little working circle, if you edit board contents without a special user (IP based, like in wikis?). no risk of vandalism.
...i could get them away from trello, without forcing them to another login (acceptance)

applying SSO ist not possible here, no developers around...

Thx and: kanboard is a great piece of software!

karsten

**Comment by fguillot** [comment]
You need to be authenticated to use the software. If you want to avoid another credentials, there are some plugins to use other authentication backends like Google or whatever, that require some configuration but you don't need to have a in-house developer.

**Comment by wrkb** [comment]
too sad, but i know, this is a very rare scenario. i will browse through the plugins or we have to change our behaviour. thx and greetings
