### ISSUE TITLE
Data migration from one instance to another

### ISSUE THREAD

**Issue by nebulade** [fguillot/kanboard#2102]
Hi, I might have missed something obvious, but is there a way to export all data from one kanboard instance and then import to another kanboad using a different storage backend? 
SQL dumps might probably work, but I am wondering if there is some other way, especially with regards to user mapping. In my case the new instance would use LDAP and the old instance is not.

I do see a couple of other plugins, which allow importing from 3rd party services but haven't seen plugins related to kanboard -> kanboard data migration.

Thanks a lot,
Johannes

**Comment by fguillot** [comment]
If you want to migrate from Sqlite to Mysql or Postgres there are probably some command line tools, but the reliability of this operation is not guaranteed to work correctly. (search in the closed issues, some people already tried that).

**Comment by oliviermaridat** [comment]
The most relevant related to this issue is #1740

**Comment by oliviermaridat** [comment]
I have disclosed a script for migrating SQLite database to MySQL: https://github.com/oliviermaridat/kanboard-sqlite2mysql 

It generates a SQL dump of Kanboard data. It can be used for export / import.

**Comment by thob** [comment]
How would I migrate from one server to another, both having mysql. Is it just a matter of export/import to the db?

**Comment by fguillot** [comment]
@thob Yes, you can use mysqldump for example
