### ISSUE TITLE
Gender equality bug in french version. (otherwise thanks for this very useful app...)

### ISSUE THREAD

**Issue by Krishnou** [fguillot/kanboard#2104]
### Expected behaviour

Tell us what should happen
In french version administrator is translate as. Administrateur.

### Actual behaviour

Tell us what happens instead
Administrateur-trice should be a more accurate translation about the diversity of users.

### Steps to reproduce
I can change the translation myself if somebodu explain me how to do.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:

**Comment by mcorteel** [comment]
La langue française est certes assez mal faite à cet égard, mais je ne crois pas avoir déjà vu de logiciel faire cette distinction. Par ailleurs, il faudrait également changer "utilisateur".
Je suis tout à fait pour un débat sur l'inclusion de la règle de proximité dans la grammaire française, mais je ne crois pas que cette distinction soit la manière la plus efficace de représenter la diversité.
Je serais intéressé par les avis des francophones à ce sujet ceci dit !

**Comment by fguillot** [comment]
The current translation system is so basic that it doesn't take into consideration the gender or the plurals. For me, changing the localization system it's not a priority right now. I don't know if gettext is able to that...

If you change the text to have "Administrateur-trice" everywhere, that will also increase the string length, French sentences are already too long IMHO.

**Comment by DoumeDuSud** [comment]
A mon sens il n'y a pas nécéssité à mettre de l'idéologie politique dans la traduction d'un logiciel, même si cela est à la mode dans certain milieu libriste.

Pour rappel le masculin est aussi un neutre en français, notament concernant les fonctions des personnes. Il me semble donc qu'il est tout à faire normal d'appliquer les règles de l'académie française. 
Il a bien entendus quantité d'endroits bien plus pertinant pour promouvoir l'égalité entre être humain :-) et réfléchir à la question.
