### ISSUE TITLE
Question: Cron Job in Cpanel

### ISSUE THREAD

**Issue by cbrokaw** [fguillot/kanboard#2106]
I'm a complete beginner with trying to schedule a cron job. I'm trying to set this up in cPanel. What file do I reference when trying to initiate the cron job?

### Configuration

Application version: 1.0.27
PHP version: 5.4.44
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.30.3.lve1.3.63.el6.x86_64
Database driver: sqlite
Database version: 3.8.10.2
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by fguillot** [comment]
I don't know anything about cPanel but maybe this link will help you: https://documentation.cpanel.net/display/ALD/Cron+Jobs

Just put this command in the text field: http://kanboard.net/documentation/cronjob

**Comment by khigashi** [comment]
Hi @cbrokaw 

If you are using a shared host, you can setup a New Cron Job in CPANEL using the following command:

**php-cli `/path/to/kanboard/`cli cronjob**

![cron-job](https://cloud.githubusercontent.com/assets/1253063/21966813/058bfc10-db62-11e6-8a5b-e747948ba293.png)

PS: I spent a few hours to solve this puzzle =).

**Comment by cbrokaw** [comment]
Thank you @khigashi for your help on this!
