### ISSUE TITLE
Change buttons layout

### ISSUE THREAD

**Issue by mcorteel** [fguillot/kanboard#2107]
I really love some of the recent design changes to Kanboard and the addition of a theme manager plugin is awesome!
But there is one very important limitation to theming right now, which is the fact that the icons are not included in links. I proposed a PR some time ago to change the UrlHelper::link() function in order to include the icon when necessary. My proposal is the following:

- Use the normal UrlHelper::link() for actual links (the blue ones without icons)
- Create another helper function UrlHelper::button() that includes an optional icon parameter for buttons

This requires important changes throughout the whole code base, but I think it would be worth it to improve theming. I'm willing to provide a pull request implementing this change for all buttons if you want. @fguillot what do you think?

**Comment by fguillot** [comment]
Actually, I merged and modified your helper from your PR, `UrlHelper::button()` is available: https://github.com/fguillot/kanboard/blob/master/app/Helper/UrlHelper.php#L43

However, only few links use this helper at the moment.

**Comment by mcorteel** [comment]
Oh, I didn't notice... Great!
I will try to submit a PR to change the remaining icon links next week-end or so.
