### ISSUE TITLE
Reset "nb_failed_login" counter in database after password modification

### ISSUE THREAD

**Issue by mrfyx** [fguillot/kanboard#2117]
### Expected behaviour

Our kanboard doesn't have access to internet. The captcha doesn't work. So if a user is blocked to the login page, we use administrator to "reset" is password. However the ``nb_failed_login`` counter is not reset so the user can't login.

Currently, we edit the database with an external editor to set the ``nb_failed_login`` to 0.

### Actual behaviour

It should be great to reset the counter when an administrator change a password.

### Steps to reproduce

1.WIth the User1, enter a bad password 3 times
2.Modify the password of User1, with the administrator
3.Try to login with User1 and its new password

### Configuration

* Application version: 1.0.27
* PHP version: 7.0.5
* PHP SAPI: cgi-fcgi
* OS version: Linux 3.10.0-327.el7.x86_64
* Database driver: sqlite
* Database version: 3.8.10.2
* Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by fguillot** [comment]
This now implemented in the development branch. Thanks.
