### ISSUE TITLE
1.0.27 - Issue with "submit form" shortcut comment window pop-out using FF or IE

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#2118]
### Expected behaviour

When using the pop-out comment window in a task (invoked by pressing __C__) and submit form by using CTRL+Enter the comment should be added to the task. This is working as expected with Chrome.

### Actual behaviour

By using Firefox or Internet Explorer the submit form shortcut in the pop-out comment window forwards you to another page with plain HTML view and where the comment has to be entered again.

![comment_submit_form_issue](https://cloud.githubusercontent.com/assets/4871330/14467114/1ac75a1a-00da-11e6-95c1-b3607551395b.png)

### Steps to reproduce

1. Open Kanboard with either Firefox or Internet Explorer
2. Create task
3. Invoke pop-out commenting window by pressing __C__
4. Use CTRL+Enter shortcut

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27
- Database type and version: SQLite
- PHP version: 5.4
- OS: Win2k8
- Browser: Firefox 45

**Comment by donpatzone** [comment]
Another thing that I noticed is that when I try to create a new task on the board using CTRL+Enter it will not finish it correctly. I see this problem only in Firefox. IE and Chrome are working fine.

**Comment by fguillot** [comment]
It's fixed in master. Thanks.

**Comment by donpatzone** [comment]
Thanks :)
