### ISSUE TITLE
Once a project is made public, it cannot be undone

### ISSUE THREAD

**Issue by mehdid** [fguillot/kanboard#2120]
In the "Permissions" page, for each project, an admin can choose to make the project accessible to everyone. Unfortunately, this decision cannot be undone. The "Preferences" page for the project is not shown anymore and any try to show it results in an error message (red block) which says "Accès interdit" (forbidden access). A project admin should be able to untick the "Allow everybody to access to this project" option.

In fact, the problem is that a project owner doesn't see the "Preferences" menu item anymore... Only a kanboard admin can.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.27

**Comment by fguillot** [comment]
This issue is now solved in master. Thanks.
