### ISSUE TITLE
What happened with autocomplete?

### ISSUE THREAD

**Issue by Kolesar** [fguillot/kanboard#2128]
### Expected behaviour

When use @ sign expect drop down list with all users in current project

### Actual behavior

Auto-complete drop-down missing

### Steps to reproduce

1. Try do add comment in task with sign @

### Configuration

    Application version: master
    PHP version: 5.5.14
    PHP SAPI: apache2handler
    OS version: Linux 4.1.20-11-default
    Database driver: mysql
    Database version: 10.0.22-MariaDB
    Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**P.S.
Can we get drop-down list in description field too?**

**Comment by fguillot** [comment]
See #2045
