### ISSUE TITLE
Error when deleting User

### ISSUE THREAD

**Issue by justice777** [fguillot/kanboard#2143]
### Expected behaviour

When deleting a user I expect to be redirected back to the user management screen.

### Actual behaviour

After confirming deletion I receive the following error screen:

**Warning: unlink(data/files/) [function.unlink]: Is a directory in /home/content/37/4265637/html/kanboard/app/Core/ObjectStorage/FileStorage.php on line 133
**
**Warning: Cannot modify header information - headers already sent by (output started at /home/content/37/4265637/html/kanboard/app/Core/ObjectStorage/FileStorage.php:133) in /home/content/37/4265637/html/kanboard/app/Core/Http/Response.php on line 96
**
### Steps to reproduce

1. Navigate to User Management
2. Click Actions gear and select Remove
3. Click Yes on the confirmation prompt.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Kanboard version: 1.0.28
Database type and version: mysql\5.5.43-37.2-log
PHP version: 5.3.24
OS: Linux 2.6.32-604.30.3.lve1.3.63.el6.nfsfixes.x86_64
Browser: Chrome\49.0.2623.112 m, Firefox\33.1.1
Sign up for free

**Comment by justice777** [comment]
I tracked this down to app/Core/ObjectStorage/FileStorage.php

It looks like when avatar deletion is being called instead of passing in data/files/avatars/user_id it's only getting data/files. Unlink then fails because it's a directory.

**Comment by fguillot** [comment]
This issue is now solved in master. Thanks.
