### ISSUE TITLE
[plugin] openid-auth

### ISSUE THREAD

**Issue by agentcobra** [fguillot/kanboard#2152]
![OpenID_logo](https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/OpenID_logo_2.svg/320px-OpenID_logo_2.svg.png)
Hello,
I'm starting a plugin for kanboard called [openid-auth](https://github.com/agentcobra/kanboard-plugin-openid-auth)
it's my first plugin, it's for [OpenID](https://en.wikipedia.org/wiki/OpenID) authentification 
if you would like to help, fork it ;)
agentcobra

**Comment by agentcobra** [comment]
@fguillot,
have you got a documentation for making plugins ?
agentcobra

**Comment by fguillot** [comment]
https://kanboard.net/documentation/plugins
