### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by Asshad** [fguillot/kanboard#2154]
### Expected behaviour
User Add - Is there any email notification when adding a new user?

Tell us what should happen
Receive email notification

### Actual behaviour
There's no trace that email has been sent out or queue somewhere.

Tell us what happens instead

### Steps to reproduce

1. Telnet localhost 25
2. Send email via telnet, it works.

### Configuration
Config 
// Mail transport available: "smtp", "sendmail", "mail" (PHP mail function), "postmark", "mailgun", "sendgrid"
define('MAIL_TRANSPORT', 'mail');

// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'smtp.server.com');
define('MAIL_SMTP_PORT', 25);
define('MAIL_SMTP_USERNAME', 'classified@server.com');
define('MAIL_SMTP_PASSWORD', 'xxxxxxx');
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Latest
- Database type and version: MongoDB Latest
- PHP version: 5.3.3
- OS: Centos 6.7
- Browser: Safari

**Comment by fguillot** [comment]
If you use SMTP, maybe you should set the transport to "smtp" (first config parameter).

> Database type and version: MongoDB Latest

Kanboard doesn't use MongoDB by the way.

**Comment by Asshad** [comment]
Hi, Thanks for your reply. 

However, I have tried to use smtp and changed the db to sqlite3. I managed to login and add user but notification don't work.  I have enabled the debug mode, I couldn't see anything related to mailing error.

**Comment by Asshad** [comment]
Hi sir,

I managed to get it work. Instead of using smtp, I need to use sendmail. 

Thanks for the great software.
