### ISSUE TITLE
make break on Bootstrap.js

### ISSUE THREAD

**Issue by svenn71** [fguillot/kanboard#2157]
When building from clone master, I get the following error message:
cat: assets/js/src/Bootstrap.js: No such file or directory
Makefile:38: recipe for target 'app.js' failed
make: *** [app.js] Error 1

What package am I missing on my Debian unstable to make this go away?

**Comment by svenn71** [comment]
I found myself:
Go to assets/js/src and copy bootstrap.js to Bootstrap.js

**Comment by svenn71** [comment]
also find that yuicompressor is called yui-compressor in Debian.

**Comment by fguillot** [comment]
Thanks, the file have been renamed.
