### ISSUE TITLE
[Bug] Notice: Undefined index: avatar_path

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#2158]
Hi there, I have found php notice error after I made update

### Expected behaviour

No errors or notices

### Actual behaviour

After I updated kanboard to latest version and opened project task, ex: http://kanboard/project/1/task/2

I got next notice

```Notice: Undefined index: avatar_path in /public_html/app/Helper/AvatarHelper.php on line 66```

### Steps to reproduce

1. Update kanboard from old version to new
2. Open any Task page

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

```
    Версия приложения: master
    Версия PHP: 5.5.9-1ubuntu4.14
    PHP SAPI: apache2handler
    Версия ОС: Linux 3.16.0-30-generic
    Драйвер базы данных sqlite
    Версия БД: 3.8.2
    Браузер: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

**Comment by fguillot** [comment]
Do you still having the issue because I'm not able to reproduce?

**Comment by orlov0562** [comment]
Hello,

I have just updated and checked - everything works perfectly without any notices. Thank you again for your time and great product!

**Comment by edwigemorin** [comment]
Hello,
Just to let you know that I had the same notice and it disappears when I added my family name in the name field (I just had my first name before). As soon as I added it, the notice went off.
Great app thank you very much for your work.
