### ISSUE TITLE
[Feature Request] Append "Task title" to the page title

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#2159]
Hello!

I have found that when we open any task page we have only project name in page title. 
I mean: ```<title>prj name</title>```

It's leads to inability to use "browser history" and "restore closed tab list", because all pages have the same title.

I suggest append "task id" and "task title" to the page title. Something like this:
```<title> [prj name] [task number] [task title] </title>```
example:
```<title> My project, #136 - Change box shadow to red in one step chackout page</title>```

**Comment by fguillot** [comment]
This improvement is available in master. Thanks.
