### ISSUE TITLE
Missing code/config for app/Core/Http/Client SSL options

### ISSUE THREAD

**Issue by digitician** [fguillot/kanboard#2162]
The Gitlab auth plugin uses the HTTP client in core. When Gitlab is using a self-signed cert for HTTPS and Kanboard is running on PHP 5.6+, authentication fails. With PHP 5.6+ the default behaviour of the SSL streams changed to verify certs. I patched the code on my setup, but it would be nice if the SSL options could be set via the config.

### Steps to reproduce

1. Host Kanboard on PHP 5.6+ with Gitlab authentication
2. Host Gitlab on HTTPS with self-signed cert
3. Try to authenticate

### Configuration

- Kanboard version: 1.0.27
- Database type and version: mysql 5.5.46
- PHP version: 5.6.19
- OS: Linux
- Browser: Firefox

**Comment by fguillot** [comment]
A new config option is now available in the dev branch.
