### ISSUE TITLE
Help is an emergency

### ISSUE THREAD

**Issue by decost96** [fguillot/kanboard#2168]
Hello
My question was to know where the function to add a new column
Example:
+ Backlog
+ Ready
+ Work in progress
+ Done
+ Repeat
And as the percentage that is done by moving a task from the task Ready Done works.
If anyone knows please feel free to let me know.
First of all, Thanks

**Comment by fbartels** [comment]
Hi,

when editing a project, there is also a section to add/edit/remove columns. See http://kanboard.net/documentation/editing-projects

I am not sure what you mean with percentage and tasks. Are you maybe searching for an "automatic action" to close a task once it has been moved to done?
