### ISSUE TITLE
LDAP groups are not synchronized

### ISSUE THREAD

**Issue by didierm** [fguillot/kanboard#2173]
### Expected behaviour

According to http://kanboard.net/documentation/ldap-group-sync, one would expect that LDAP groups allow for access control to the different projects.

### Actual behaviour

After defining all relevant LDAP parameters in config.php, both LDAP users and groups are recognized in KB, and the Admin / Manager roles are assigned accordingly.

Unfortunately, assigning an LDAP group to a project (in project permissions) adds the group to SQL table "groups", but the SQL table "group_has_users" is not updated.

It is unfeasible to manually add & update LDAP members the KB groups.

### Steps to reproduce

1. LDAP user "user01" is memberOf LDAP group "group01"
2. Assign the LDAP group "group01" to KB-project "project01"
3. When "user01" logs in, he has no access to "project01", as "group01" has an empty member list.

One would expect the following program flow : 
1. "user01" logins in ;
2. the memberOf values are enumerated ;
3. these are compared against the groups in table "groups" ;
4. if a memberOf value matches a group, the entry is added to table "group_has_users" if not already present ;
5. missing user_id/grou_id memberOf values are deleted from table "group_has_users" (to catter from users which are deleted fro an LDAP group).

### Configuration

- Kanboard version: 1.0.27
- Database type and version:  postgres 9.4.4
- PHP version: 5.4.16
- OS: Linux 3.10.0-327.13.1.el7.x86_64
- Browser: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by fguillot** [comment]
This issue is now solved in Kanboard 1.0.28.

Reopen this ticket if that doesn't works as expected.

Thanks.

**Comment by felixkretschmer** [comment]
Reopened. See: #3182

**Comment by felixkretschmer** [comment]
Groups are even not updated, if admins change them and the user re-login.

Example:
User A has the role "User".
Admin upgrades User A to "Manager". This is visible in the users profile.
As soon as User logs out and in again the role is switched back to "User" altough LDAP is updated as well.
