### ISSUE TITLE
[Feature Request] Possibility add comment on sub task

### ISSUE THREAD

**Issue by Portekoi** [fguillot/kanboard#2174]
Hello,

Is it possible add a comment on a sub task? Purpose is give more instruction for the user in charge on this task

Thanks,

**Comment by fguillot** [comment]
No, it's not possible. This feature have been already asked in the past. But to keep the software simple, the number of features are voluntary limited. I'm sorry but at the moment there is no plan to add comments/description/files to subtasks.
