### ISSUE TITLE
Close all tasks by column is closing all open and closed items, thus, completed times updating. 

### ISSUE THREAD

**Issue by bonbonGuy** [fguillot/kanboard#2175]
### Expected behaviour
Close all tasks by column 
all OPEN tasks are closed and completed time updated

### Actual behaviour

Close all tasks by column
All OPEN and CLOSED tasks are closed and completed time updated

### Steps to reproduce

1. Have a closed task in a column
2. Have an open task or tasks in a column
3. Close all tasks by column

This is affecting our analytics and changed it here on my end:
 
I've looked at the code and here is the fix in the TaskStatus.php file in app/Model

Just need to add eq(Task::TABLE.'.is_active',Task::STATUS_OPEN) when getting applicable tasks

    public function closeTasksBySwimlaneAndColumn($swimlane_id, $column_id)
    {
        $task_ids = $this->db->table(Task::TABLE)->eq('swimlane_id', $swimlane_id)->eq('column_id',    $column_id)->eq(Task::TABLE.'.is_active',Task::STATUS_OPEN)->findAllByColumn('id');
        $this->closeMultipleTasks($task_ids);
    }

**Comment by fguillot** [comment]
Thanks to report this issue. It's now fixed in master.
