### ISSUE TITLE
Tags & User in the description field 

### ISSUE THREAD

**Issue by connered** [fguillot/kanboard#2180]
hey 

I use the Kanboard and like it much but miss a feature that i can add tags (start with #) and user (with a @) direct in the description field - with the use of that Token in the description field the interface could more focused

**Comment by thob** [comment]
@ works, just the autocomplete is gone for the moment

**Comment by connered** [comment]
thanks - how do you like this for tags ?

**Comment by thob** [comment]
would be great, I think there's a feature request out there already

**Comment by ptman** [comment]
So if @ works and tags are a duplicate, shouldn't this be closed?

**Comment by fguillot** [comment]
FR for tags is #262
