### ISSUE TITLE
Why the easy way to edit subtask was removed in the last version (1.0.27) ?

### ISSUE THREAD

**Issue by mrbidon** [fguillot/kanboard#2181]
First, I thank you for work, you application Kanboard increase the way I organize my life.

I just upgraded to the 1.0.27 and I discover that the easy way to write new subtask after a current one already created, was removed. It was very usefull for quickly add subtask, we just had to fill the text input. 

I guess we should use the checkbox "add a other sub-task" when creating lot of sub-task. 

But, I'm very interested by the aim that made you delete this quick and efficient way to create subtasks.

**Comment by fguillot** [comment]
Yes it was removed to simplify the ui but you can still add subtasks quickly by using the keyboard shortcut "s" or by clicking on the link on the left.

**Comment by mrbidon** [comment]
Ok, with, the s shortcut will be ok for me. 

(but I still prefer the last input :-))

Thanks a lot for your answer
