### ISSUE TITLE
Error when saving an uploaded avatar doesn't tell what to do to fix it

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#2183]
This happened when uploading and then clicking Save:

![upload fail](https://cloud.githubusercontent.com/assets/479401/14895540/33c5b934-0d47-11e6-9984-995121966843.png)

If it's a permissions problem, it should tell me which folder is problematic, and ideally how to fix it exactly (or a link to the docs about required file/folder permissions for kanboard).

But then, in this case it was not even a permissions problem; it showed me that error but had actually uploaded and saved the avatar without problems. Reloading the page showed the uploaded avatar, so I'm not sure what would trigger this error message on the "first upload".

**Comment by nekohayo** [comment]
Oh, I think I just realized what this is about... the "Save" button actually means "Upload", not "save the changes". So it should be named accordingly, or that button should disappear once the image has been successfully uploaded already (unless the user picked a new local file from the file browser).

**Comment by fguillot** [comment]
The avatar upload form have been improved.

**Comment by toddlyons** [comment]
I had an error like this because files/* and files/thumbnails/* did not exist, and I didn't realize I needed to manually create them.

**Comment by mickusmaximus** [comment]
I have the same problem to and can't find a solution. If it helps I also have problem displaying avatars downloaded over ldap. (no error in debuglog) thumbnail picture is downloaded successfully and can be viewed in avatar folder but kanboard shows (broken picture) icon. Please tell if you need more information. I'm grateful for answers.
