### ISSUE TITLE
Assign user to a task

### ISSUE THREAD

**Issue by Thatoo** [fguillot/kanboard#2189]
### Expected behaviour

When I create a task, I'd like to assign it to an other user than myself.

### Actual behaviour

However, even though I have two local users, the list contain only myself. I didn't find how to add a user to a project by the wy whioch might be linked to the problem, but then, it's very not intuitive cause I spent 5 minutes just looking for it.

### Steps to reproduce

1. Create a task
2. In Assignee, no other choice than me.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Official website: http://kanboard.net/
    Application version: 1.0.25-framaboard
    Author: Frédéric Guillot (contributors)
    License: MIT
- Database type and version:  sqlite

- Kanboard version:

- PHP version:
- OS:
- Browser:

**Comment by AgatonSax** [comment]
It sounds like you have a private project. In order to assign a task to some user (other than your self) you need to make it a normal project. Go: menu > settings > edit project > uncheck private project.

**Comment by Thatoo** [comment]
Thank you for your answer but unfortunately it doesn't solve it. My project was not checked as private project.
I had the idea to log in with an other member, an other admin, and he cannot assign task to anyone except the founder of the project, not even himself...

**Comment by fguillot** [comment]
https://kanboard.net/documentation/project-permissions

**Comment by Thatoo** [comment]
Thank you, that was it.

**Comment by godspeedyou** [comment]
A refresh (of the server) may be necessary, if you just added new users or else there won't be any suggestions for user names and the "Add" button will be disabled.
