### ISSUE TITLE
User Label aka avatar-letter and Cyryllic encoding

### ISSUE THREAD

**Issue by Folcky** [fguillot/kanboard#2195]
### Expected behaviour
avatar-letter should include first letters of username parts.

### Actual behaviour
There are avatar-letters now include two "?" for all users with the same color in all tasks.
Screenshot is attached.

### Steps to reproduce
Cyryllic usernames work wrong.
Latinic usernames work perfectly.

### Configuration
- Kanboard version:1.0.27
- Database type and version:3.6.20  sqlite
- PHP version:5.5.30
- OS:Linux 2.6.32-431.11.2.el6.x86_64
- Browser:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
![avatar-letter](https://cloud.githubusercontent.com/assets/758787/15011120/b83b4fde-11f8-11e6-89ba-c1b05800fe83.png)

**Comment by fguillot** [comment]
I tested with several Russian names and it's working fine for me. Which operating system do you have on the server?

**Comment by Folcky** [comment]
Hi,

-bash-4.1$ uname -a
Linux saswiki 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Lood** [comment]
method Kanboard\Helper\UserHelper:getInitials() is used `mb_substr`.
you must add 
`mb_internal_encoding ( "UTF-8");`

**Comment by fguillot** [comment]
That should be fixed in the development branch. Thanks.

**Comment by fguillot** [comment]
You can now use Kanboard 1.0.29, reopen this issue if necessary.
