### ISSUE TITLE
Bug: Plugins broken

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#2199]
### Expected behaviour

Plugins should work as expected

### Actual behaviour

On upgrade, the Slack plugin and Gogs plugin throw out similar error messages

`Fatal error: Uncaught Error: Call to undefined method Kanboard\Model\Config::getCurrentLanguage() in {location}\plugins\GogsWebhook\Plugin.php:13 Stack trace: #0 [internal function]: Kanboard\Plugin\GogsWebhook\Plugin->Kanboard\Plugin\GogsWebhook\{closure}(Object(Pimple\Container)) #1 {location}\app\Core\Plugin\Base.php(66): call_user_func(Object(Closure), Object(Pimple\Container)) #2 [internal function]: Kanboard\Core\Plugin\Base->Kanboard\Core\Plugin\{closure}(Object(Symfony\Component\EventDispatcher\Event), 'app.bootstrap', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 {location}\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\Event), 'app.bootstrap', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #4 {location}\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Arr in {location}\plugins\GogsWebhook\Plugin.php on line 13`

### Configuration

- Kanboard version: 1.0.28
- Database type and version: Postgres 9.4
- PHP version: 5.5
- OS: Windows
- Browser: Vivaldi 1.1

**Comment by CoMPaTech** [comment]
Just curious, did you update the plugins (as mentioned by fguillot in the update documents)? I don't have much running but my theme plugin was still alive ... both gogs and slack show crritical code updates and although I have gogs running I'm not able to test it's integration over here

**Comment by fguillot** [comment]
All plugins must be updated.
