### ISSUE TITLE
How to search for specific links?

### ISSUE THREAD

**Issue by Dirk-Herrmann** [fguillot/kanboard#2200]
### Expected behaviour

In my database, there exist items which are parents of others (using links).
According to the documentation, it shall be possible to search for links with search expressions like:
link:"is a parent of"
To my understanding, then all the items which are a parent of some other task should be shown.

Moreover, I couldn't get the following information from the manual:
* Is there a way to search for parents of some dedicated item?
* Is there a way to search for items that are not a child of another item?

### Actual behaviour

No task is found.  I also tried variations like 'Is a parent of' "is parent of".

### Steps to reproduce

1. create links (is parent of)
2. search as documented

### Configuration

- Kanboard version: No idea - I'm only a user - how can I figure it out?
- Database type and version: No idea - I'm only a user - how can I figure it out?
- PHP version: No idea - I'm only a user - how can I figure it out?
- OS: my OS is Windows 7, don't know about the server OS
- Browser: Firefox 45.0.1

**Comment by fguillot** [comment]
The string between quote have to be the exactly the same as the link label (lower or uppercase doesn't matter), for example this query should work: `status:open link:"is a child of"` or `status:open link:"is a parent of"`?

**Comment by Dirk-Herrmann** [comment]
Sorry for the late reply.  I tried both queries.  Result: "Nothing found."  Maybe we are not using the latest version, but how could I figure it out as a user?
