### ISSUE TITLE
No redirection to board view after deleting task

### ISSUE THREAD

**Issue by donpatzone** [fguillot/kanboard#2201]
### Expected behaviour

After task is deleted one should be redirected back to the board view

### Actual behaviour

After task is deleted the browser still references to this particular task and shows the error _Sorry, I didn't find this information in my database!_

### Steps to reproduce

1. Create task
2. Remove it and confirm the task deletion
3. You will be shown the error as no redirection happens to the board view.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.28
- Database type and version: SQlite
- PHP version: 5.6
- OS: Win2k8
- Browser: Firefox 46, Chrome 50, IE 11

**Comment by fguillot** [comment]
This issue is now fix in the development branch. Thanks.

**Comment by fguillot** [comment]
You can now use Kanboard 1.0.29, reopen this issue if necessary.
