### ISSUE TITLE
Mail notification for overdue tasks no more working

### ISSUE THREAD

**Issue by nob900** [fguillot/kanboard#2202]
(PR coming soon)

### Expected behaviour

Get mail notification as in previous releases.

### Actual behaviour

PHP error:
```
PHP Fatal error:  Call to undefined method Kanboard\Core\Template::e() in /var/www/alixen/app/Template/notification/task_overdue.php on line 26
```

### Steps to reproduce

1. cd to kanboard install directory
2. run ```./kanboard notification:overdue-tasks```

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.28
- Database type and version:  3.8.7.1
- PHP version:  5.6.20-0+deb8u1
- OS: Debian Jessie
- Browser:  Mozilla/5.0 (X11; Linux i686 on x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.8.0

**Comment by nob900** [comment]
see #2203

**Comment by fguillot** [comment]
You can now use Kanboard 1.0.29, reopen this issue if necessary.
