### ISSUE TITLE
Board locking and persistent conections for LDAP users

### ISSUE THREAD

**Issue by n0va1s** [fguillot/kanboard#2209]
### Expected behaviour

Tell us what should happen
Save the task

### Actual behaviour

Tell us what happens instead
Some boards are locking when the user save or edit a task. Its necessary close the board and open the board again. I saw that are getting persistent sessions. Users are remote and use LDAP.

### Steps to reproduce

1. Open the board
2. Create a task
3. Save the task

When I duplicate board the problem is temporarily resolved. When I create a new board solves so far.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.23-fix1
- Database type and version: PostgresSQL 9.4
- PHP version: 5.4
- OS: RedHat 6
- Browser: Firefox 38.5.0

**Comment by fguillot** [comment]
This version of Kanboard is very old. You should upgrade.

**Comment by fguillot** [comment]
I suggest that you update to a more recent version of Kanboard or read https://kanboard.net/documentation/performances

If you find a bug, don't hesitate to open a new issue. Thank you.
