### ISSUE TITLE
Question - How to change date format?

### ISSUE THREAD

**Issue by johnhanby** [fguillot/kanboard#2211]
We love Kanboard, but we would love it even more if it had a UK time format DD/MM/YYYY.

My PHP.ini correctly has my timezone of Europe/London, but this hasn't helped and I've had a look in the config file and can't find anything related.

- Kanboard version: 1.0.26
- Database type and version: SQLLite
- PHP version:5.3
- OS: Windows Server 2008 R2
- Browser: Chrome

**Comment by fguillot** [comment]
You can change the date format in the application settings.

**Comment by johnhanby** [comment]
Ah, completely missed that bit. Feel like a bit of a fool now.

Thanks Frédéric.
