### ISSUE TITLE
Ability to Reorder Automatic Actions

### ISSUE THREAD

**Issue by badmojo76** [fguillot/kanboard#2216]
Feature Request:  Ability to sort the Automatic Actions so that they process in the desired order.  For example, if I have the following actions setup:

Move Task to Column "Done" -> Duplicate Task to another Project
Move Task to Column "Done" -> Close Task

and I want to add a color change before duplicating the task, e.g.:

Move Task to Column "Done" -> Change Task Color to Red
Move Task to Column "Done" -> Duplicate Task to another Project
Move Task to Column "Done" -> Close Task

Currently, I need to delete the original Automatic Actions, then add the Color Change, then re-add the original actions.  If I don't, the color change is processed after the duplicate, and does not show as desired in the destination project.  

Rules are processing in the correct and anticipated order - there's just no easy way to "insert" a rule further up the chain when multiple rules may be triggered by the same action.

**Comment by jtourt** [comment]
+1.  I would like this feature, too.

**Comment by fguillot** [comment]
Duplicate with #304
