### ISSUE TITLE
Create and Update Tasks via Email

### ISSUE THREAD

**Issue by timjcraig** [fguillot/kanboard#222]
Ability to create and update tasks via email, using POP3 or IMAP. Creating tasks via would very useful to integrate KanBoard with other systems and also allow users to easily create and update tasks via email.

**Comment by Protoneer** [comment]
@oparoz I agree.... My current needs would be to only create new items but to have an email address for each project.

Doing this in Python and using the API would be quick to do but I am not sure how this would be structured in Kanboard. (I am sure what the best way would be to pole an email address without using some kind of cron-job in background. Maybe an interval based ajax call to an URL that does the processing?)

**Comment by fguillot** [comment]
Many possibilities are available to implement that:

1. If you already have a STMP server like postfix, pipe everything to a script that use the Kanboard API.
2. That can be a cronjob that check an IMAP/POP mailbox.
3. That can be a third-party service like Mailgun that relay incoming emails to a Webhook: http://documentation.mailgun.com/quickstart-receiving.html

The last solution is very easy to implement but you have to use an external provider.

For creating task, the email subject can be the task title and the email body the task description...

**Comment by BlueTeck** [comment]
If have tested 2) recently, works fine, until there is the first HTML Mail, that have to be transferred to markdown.

**Comment by fguillot** [comment]
I implemented the easiest solution in the master branch: integration with third-party services. You have the choice between 3 SMTP providers: Sendgrid, Mailgun and Postmark.

More information here:

- http://kanboard.net/documentation/create-tasks-by-email
- http://kanboard.net/documentation/mailgun
- http://kanboard.net/documentation/sendgrid
- http://kanboard.net/documentation/postmark

If you want to implement the solution 1) or 2) mentioned above, you can do that with an external script that use the API or the webhooks.

At the moment, this system works only for task creation. I will see later if I need to implement notifications reply or update tasks by email.

@BlueTeck there is a library in the vendor folder to convert HTML to Markdown if you need it.

**Comment by timjcraig** [comment]
Testing task creation using Postmark integration get the following in debug log and no task created?

>[2015-04-20 11:18:18] [debug] SELECT  * FROM "actions"      
[2015-04-20 11:18:18] [debug] DURATION=0.0014398097991943
[2015-04-20 11:18:18] [debug] SELECT  * FROM "action_has_params"      
[2015-04-20 11:18:18] [debug] DURATION=0.00012922286987305
[2015-04-20 11:18:18] [debug] SELECT COUNT(*) FROM "users"  WHERE "id" = ?
[2015-04-20 11:18:18] [debug] DURATION=0.00015807151794434
[2015-04-20 11:18:18] [debug] SQL_QUERIES=3
[2015-04-20 11:18:18] [debug] RENDERING=0.093764066696167
[2015-04-20 11:18:20] [debug] SELECT  * FROM "actions"      
[2015-04-20 11:18:20] [debug] DURATION=0.0014429092407227
[2015-04-20 11:18:20] [debug] SELECT  * FROM "action_has_params"      
[2015-04-20 11:18:20] [debug] DURATION=0.00012898445129395
[2015-04-20 11:18:20] [debug] SELECT  "settings"."option", "settings"."value" FROM "settings"      
[2015-04-20 11:18:20] [debug] DURATION=0.00014495849609375
[2015-04-20 11:18:20] [debug] SQL_QUERIES=3
[2015-04-20 11:18:20] [debug] RENDERING=0.091457843780518

Checked From, Subject, MailboxHash and HtmlBody within Postmark -> Inbound -> Activity -> JSON and looks correct.

**Comment by fguillot** [comment]
I just tested again with my own installation and that works for me.

- Be sure to have the last version of master + composer install
- Be sure the from address match the kanboard user email address
- Be sure the recipient address match the project identifier, foobar+myproject@mypostmark.domain.tld
- Be sure the webhook url is correct in postmark settings
- The wehbook should send back a status code 200 OK and the body "PARSED"
- In the debug log file, you should see those debug messages if the message is ignored: https://github.com/fguillot/kanboard/blob/master/app/Integration/PostmarkWebhook.php#L32-L46
- You can check the webhook response code in your webserver logs

**Comment by divansantana** [comment]
This email integration looks awesome.
Would love to use it, though AFAIK this only support "public" email providers.

We, like many corporations, are not allowed to use external IT services and require to use an inhouse email system.

Therefore I'd like to request support for standard pop3/imap support.

Your thoughts on this?
Should I open a separate issue for this?

Just a note again, that this project really rocks.
