### ISSUE TITLE
Task Report not showing sub tasks

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#223]
Hi

It will be great if the exported task report show details of the sub tasks too. Currently it show details of the tasks only. Also the tasks should have option to add estimation time as well as the spend time similar to that of sub task. 

![kanboard](https://cloud.githubusercontent.com/assets/7837070/4056244/6bb1af22-2db7-11e4-8eea-4e677146a23c.png)

**Comment by fguillot** [comment]
I implemented a separate subtasks export in the development version.
