### ISSUE TITLE
several assignees

### ISSUE THREAD

**Issue by vova-deep** [fguillot/kanboard#2230]
After upgrading to 1.0.28 search engine stopped work with several assignees.

**Comment by kerro** [comment]
Problem in _Kanboard\Filter\TaskAssigneeFilter::apply()_
_PicoDb\Builder\ConditionBuilder::beginOr()_ is called but was previously called in _Kanboard\Core\Filter\OrCriteria::apply()_ leading to an unexpected behavior.

beginOr()/closeOr() should not be called in TaskAssigneeFilter::apply() when there is already a 'or' condition going on.
But there is actually no way to know if a 'or' condition is currently applied in ConditionBuilder.

**Comment by fguillot** [comment]
This issue is now fixed in the development branch.

Thanks!
