### ISSUE TITLE
[Bug] Task description new lines is not the same as in editor

### ISSUE THREAD

**Issue by orlov0562** [fguillot/kanboard#2236]
### Steps to reproduce

* Create any task
* Add description with new lines, ex:

> line 1
> line 2
> 

* Save description
* Pay attention to "Description" block at task overview page

### Expected behaviour

Task description is the same as in editor
>line1
>line2

### Actual behaviour

Task description do not show line breaks.
>line1 line2

### Note
Works as expected when we add two line breaks, ex:
>line 1
>
>line 2

show:

> line 1
>
> line 2

### Configuration
Application version: master
PHP version: 5.5.9-1ubuntu4.14
PHP SAPI: apache2handler
OS version: Linux 3.16.0-30-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36

**Comment by orlov0562** [comment]
Description in editor:

![description in editor](https://cloud.githubusercontent.com/assets/1763904/15360014/92eb712e-1d14-11e6-9a78-449013e2046a.png)

Description in task overview:

![description-task-overview](https://cloud.githubusercontent.com/assets/1763904/15360019/98b5f21e-1d14-11e6-9024-7252c4167af9.png)

**Comment by fguillot** [comment]
The Markdown syntax impose to have one blank line between line, otherwise it will be the same paragraph. The Markdown rendering in the textarea is just a simple preview, it's apply only some styles.

The description field is rendered by the Javascript library SimpleMDE and the rendering in the task view is made by the PHP library Parsedown.

**Comment by orlov0562** [comment]
Got it now. Thanks for explanation!
