### ISSUE TITLE
[Solved] Changing App Labels (buttons, etc.)

### ISSUE THREAD

**Issue by servicefly** [fguillot/kanboard#2239]
I hope this is a simple questions to answer:

I can't seem to find the native language file to make a change. Basically lets say I want to change the "Category" label throughout the app to display "Status" and change the "Sub-Tasks" label to "CHild Tasks" throughout the app. Where would I find the file(s) to accomplish this?

Thanks for any help in advance.

**Comment by BlueTeck** [comment]
You could use this plugin to overwrite texts without touching the core files:

https://github.com/BlueTeck/kanboard_plugin_overwrite_translation

**Comment by servicefly** [comment]
Thank you Blue Teck. I will check out the plugin. What kinda baffled me was there is no en_En or similar for the english language in the translation director, at least on my install.

**Comment by BlueTeck** [comment]
EN is the default language  in which the apllication is developed, therefore you have to change the php code in the templates to change english texts.

Example:
https://github.com/fguillot/kanboard/blob/master/app/Template/header.php#L5

```t('Dashboard')``` is the english translation inside the code, and if you change that, the other languages doesn't work anymore.

-> the plugin helps ;)

**Comment by servicefly** [comment]
I was one of the original volunteer Developers for EyeOS where we usedlanguage files for every language in an xml format very similar to Joomla! I guess I assumed the same format would be used with Kanboard. My bad. Thanks again for your response.

**Comment by servicefly** [comment]
Uploaded your plugin. It seems my next step is to create an entire translation file (or fill in the en_US file). Is that correct? Forgive my denseness if I missed something.

**Comment by servicefly** [comment]
I just added some changes to see if it would work. I double checked I was using the right syntax. The plugin has not overwritten anything. All I did was add lines to the en_US file. Did I miss a step? If I didn't and there is a solution I will add it to the bug tracker if you want?

**Comment by BlueTeck** [comment]
You just have to put in the translations that you want to overwrite

**Comment by servicefly** [comment]
I caught that & did. They are not showing. My version is 1.0.27.

**Comment by BlueTeck** [comment]
If you are not on 1.0.28 you have to use an older version:

https://github.com/BlueTeck/kanboard_plugin_overwrite_translation/releases/tag/1.0.22

**Comment by servicefly** [comment]
Now I get it. Totally works thank you!! If I had the time I would build a en_US file with all of the phrases to help others. I might still do it. Would be great for template (theme).
