### ISSUE TITLE
Application URL Issue

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#2242]
### Expected behaviour

**Tell us what should happen
When I set the application url all subsequent generated links should work.**   

### Actual behaviour

**When , I set the Settings>Application URL the corrsponding Intergrations links and email links appear to not work properly.   For instance when I set the Application URL to kb.mydomain.com  all the links generated are missing the /kanboard.**  

**Settings>Application URL = https://kb.mydomain.com
Links in emails is https://kb.mydomain.com/?controller=task&action=show&task_id=171&project_id=13**

When I click on that link it takes me to the apache page.  

### Steps to reproduce

**Settings>Application URL = https://kb.mydomain.com
Links in emails is https://kb.mydomain.com/?controller=task&action=show&task_id=171&project_id=13**

When I click on that link it takes me to the apache page.  

### Configuration

**Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: apache2handler
OS version: Linux 3.13.0-86-generic
Database driver: postgres
Database version: 9.3.12
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36**

**Comment by seancarson** [comment]
Maybe related to #2233 and  #1734

**Comment by mordentware** [comment]
Possibly related, but I'm seeing the above on the actual boards themselves. Fresh install of Kanboard with the application URL set:

[Screenshots](http://imgur.com/a/KYAQJ)

The "+" next to "Backlog" links to

`/?controller=taskcreation&action=create&project_id=1&column_id=1&swimlane_id=0`

which, when clicked shows the second image (resolved link is `http://kanboard.mydomain.com/?controller=taskcreation...`). This may well be something to do with my configuration, of course, so happy to take to a separate issue if so.

**Comment by fguillot** [comment]
You have to put the absolute URL to your Kanboard folder: `https://kb.mydomain.com/kanboard/` or if you  don't have a sub-folder put: `https://kb.mydomain.com/`

**Comment by mordentware** [comment]
@fguillot: if the above was in reference to my point, I don't have a sub-folder and the application URL is set, as far as I can tell, to the right URL (i.e. `http://kanboard.mydomain.com/`). Accessing the rest of the site seems to work, but any real actions try to go via `http://kanboard.mydomain.com/?controller=...`, which gives the form submission a problem.

**Comment by seancarson** [comment]
Ok, thank you @fguillot .  And yes I do have the sub folder kanboard in my setup.  So when I add /kanboard to the application url links in emails work, but all my api/webhook calls fail with timeouts and such as @mordentware mentions above.  I noticed this when setting up email to task creation with Sendgrid and Postmark plugins.

**Comment by seancarson** [comment]
and Example of an Failed API call is below.  

https://www.myurl.com/kanboard/?controller=webhook&action=receiver&plugin=sendgrid&token=67545fef6a0a3f43d60c7d57632d6e4af9930f064c12e72266b1c9b42381

When I open this link in a Web browser I get an message that just says IGNORED.

**Comment by seancarson** [comment]
Well, the issue is now resolved.  After adding /kanboard/ to my application URL Emails now have  a working link and Sendgrid create tasks via email is now working properly.  Thank You for all your help.  

Sean Carson
