### ISSUE TITLE
Provide the ability to add labels, tags or icons in Tasks

### ISSUE THREAD

**Issue by menegrete** [fguillot/kanboard#2245]
### Expected behaviour

Option to add labels, tags or icons in Tasks to identify or categorize.

### Actual behaviour

Currently there is no such option in Tasks.

### Configuration

- Kanboard version: 1.0.26

**Comment by BlueTeck** [comment]
duplicate of #262 and see #646

**Comment by menegrete** [comment]
+1 for this
