### ISSUE TITLE
User label / letter-avatar with PHP 5.3.28

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#2250]
### Expected behaviour

Showing initials with different background-colors when no avatar is uploaded.
Specs say: working with PHP >= 5.3.3

### Actual behaviour

All user labels show the same background-color (rgb(58, 120, 58)).
Having umlauts in the name, like Müller, PHP throws an error:
Warning: unpack() [function.unpack]: Type N: not enough input, need 4, have 0 in /www/htdocs/kanboard/app/User/Avatar/LetterAvatarProvider.php on line 167

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

    Version: 1.0.28
    PHP Version: 5.3.28-nmm5
    PHP SAPI: fpm-fcgi
    OS Version: Linux 3.13.0-85-generic
    Datenbanktreiber mysql
    Datenbank Version: 5.6.30-nmm1-log
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by Busfreak** [comment]
I don't know if it really has something to do with PHP 5.3.

Even though the database and server are set to UTF-8, the umlauts are recognized as ISO-8859-1.
So I added mb_detect_encoding to the function getCharCode() in LetterAvatarProvider, see https://github.com/fguillot/kanboard/pull/2256.

What do you think?

**Comment by Busfreak** [comment]
I have tested it on a shared web server, where I can change PHP version, everything else remains the same:
PHP 5.3
![5 3](https://cloud.githubusercontent.com/assets/12938119/15655075/fb494370-2699-11e6-8c89-18f28d8cb236.jpg)


PHP 5.5
![5 5](https://cloud.githubusercontent.com/assets/12938119/15655078/ff1d4672-2699-11e6-88e0-1a7ad753a775.jpg)

**Comment by Busfreak** [comment]
see https://github.com/fguillot/kanboard/pull/2267

**Comment by fguillot** [comment]
This is now fixed in the master branch. Thanks.
