### ISSUE TITLE
Start date incorrectly parsed

### ISSUE THREAD

**Issue by nob900** [fguillot/kanboard#2251]
### Expected behaviour

Have start date correctly parsed

### Actual behaviour

Tasks with a "french" start date are interpreted as an "US" date.

### Steps to reproduce

1. create a task
2. give it a start date on 2th september
3. task start date is set to 9th february

### Configuration

Don't know if this is really useful, but here's my locale configuration : 
```
$ locale -a
C
C.UTF-8
fr_FR.utf8
POSIX

$ cat /etc/default/locale
LANG=fr_FR.UTF-8
```

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version:  1.0.28
- Database type and version:   sqlite 3.8.7.1
- PHP version:  5.6.20-0+deb8u1
- OS: Debian Jessie
- Browser:  Mozilla/5.0 (X11; Linux i686; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.7.1

**Comment by nob900** [comment]
This issue appears when date/time format is set to "mm/dd/yyyy hh:mm" (first element in dropdown) in application settings.

Everything works fine if date/time format is set to "dd/mm/yyyy hh:mm"

**Comment by fguillot** [comment]
Do you use the date picker or do you enter the date manually?

**Comment by nob900** [comment]
Yes, datepicker. Once date has been selected its ISO value is set into input field.

It seems to be an upgrade issue… After having reconfigured date format to "dd/mm/yyyy", if I change it back to "mm/dd/yyyy", I’m also unable to reproduce this behavior.

**Comment by oparoz** [comment]
Same problem with end date on 1.0.28.

Steps to reproduce for @fguillot 

1. Set date format to dd/mm/yyyy
1. Set the end date to 5th of June. Field shows: 2016-06-05
1. Save. Task shows 05/06/2016 as it should
1. Edit the task. Field shows 05/06/2016 as it should
1. Save. Task shows **wrong date**: 06/05/2016

Playing with the date settings has no impact, the bug stays.

**Comment by fguillot** [comment]
This is now fixed in master. Thanks.

**Comment by fguillot** [comment]
You can now use Kanboard 1.0.29, reopen this issue if necessary.

**Comment by marcosaccioly** [comment]
After an upgrade to version 1.0.30, it is mandatory to go to Configuration > Aplication and set the corresponding datetime format for the functionality to work, as it is not present in older versions.
