### ISSUE TITLE
Forbiden error after install kanboard on localhost

### ISSUE THREAD

**Issue by edgram** [fguillot/kanboard#2252]
### Expected behaviour

After download kanboard zip file, I put it on my local webserver instalation but when I try to enter to localhost/kanboard site, I get an 403 forbidden access error.  

### Actual behaviour

When I go to my site localhost/kanboard, I get an 403 forbiden acces error.

### Steps to reproduce

1. Download Kaboard stable versión from https://kanboard.net/kanboard-latest.zip
2. unzip to html apache directory.
3. go to localhost/kanboard

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: v1.0.28
- Database type and version:  sqlite, PDO Driver for SQLite 3.x
- PHP version: 5.5.31 
- OS: Darwin MacBook-Pro.local 15.4.0 Darwin Kernel Version 15.4.0: root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
- Browser: google chrome Versión 50.0.2661.102 (64-bit)

<img width="518" alt="captura de pantalla 2016-05-19 a la s 10 36 58 p m" src="https://cloud.githubusercontent.com/assets/16267007/15416592/b655211a-1e12-11e6-86c8-1aa62f083aa2.png">

**Comment by edgram** [comment]
I've tried to install in my domain with equal result. My server log error say next:

[Fri May 20 01:55:30.020389 2016] [access_compat:error] [pid 28026:tid 140019524105984] [client 189.215.229.67:42053] AH01797: client denied by server configuration: /home/domain/public_html/kanboard

**Comment by kaysiz** [comment]
i am getting the same error too...Error 403

**Comment by fguillot** [comment]
This problem have nothing to do with Kanboard. The issue is related to the way that Apache is configured on your own machine.

Google the error message and you will find the answer to your problem (https://wiki.apache.org/httpd/ClientDeniedByServerConfiguration).

**Comment by kaysiz** [comment]
thank you will have a look at the link

**Comment by mrks11** [comment]
This is my take on this issue and how I fixed it:

Starting point: I wanted to install kanboard in a folder named "kanboard" below the document root, e.g. www.mydomain.ltd/kanboard. I changed the rewrite rule in kanboard's htaccess file from `RewriteRule ^ /index.php [QSA,L]` to `RewriteRule ^ /kanboard/index.php [QSA,L]`

Result: 403 error - Forbidden

Fix: I renamed the kanboard folder to 'kanban' (actually, anything different from 'kanboard' will do) and changed the above rewrite rule, in my case, to `RewriteRule ^ /kanban/index.php [QSA,L]` to match the new folder name.

Result: It works :)

Apparently, the rule `<FilesMatch "(kanboard|config.php|config.default.php)">` in kanboard's htaccess file also matches the folder (!) name 'kanboard', resulting in the 403 error. 

Markus

**Comment by nickbe** [comment]
I think it might be actually simpler than this.

I solved the problem by adding a RewriteBase command like this:
```

RewriteEngine On
RewriteBase /kanboard
```

**Comment by moicarballo** [comment]
Buen día a mi el error me daba porque estaba activo el modulo de seguridad, para resolverlo, hacemos lo siguiente: 
evasive.conf o evasive.load

LoadModule evasive20_module /usr/lib/apache2/modules/mod_evasive20.so
<IfModule mod_evasive20.c>
DOSHashTableSize 3072
DOSPageCount 10
DOSSiteCount 150
DOSPageInterval 1
DOSSiteInterval 1
DOSBlockingPeriod 300
DOSLogDir "/var/log/apache2/evasive"
DOSWhitelist    127.0.0.1
DOSWhitelist    192.168.*.*
</IfModule>

con eso queda solucionado.
