### ISSUE TITLE
Task priorities not cloned when duplicating a project

### ISSUE THREAD

**Issue by carlosabalde** [fguillot/kanboard#2254]
### Expected behaviour

Task priorities in 'Settings  > Edit project > Task priority' are not cloned when duplicating a project.

### Actual behaviour

Default values are used.

### Steps to reproduce

Clone a project with some custom priorities (default, lowest, highest).

### Configuration

Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: fpm-fcgi
OS version: Linux 3.13.0-79-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by fguillot** [comment]
This feature is now supported in the development branch.

Thanks
