### ISSUE TITLE
Task priority not cloned when duplicating a task to another project

### ISSUE THREAD

**Issue by carlosabalde** [fguillot/kanboard#2255]
### Expected behaviour

Task priority is not copies when duplicating a task to another project.

### Actual behaviour

Task is cloned in the target project but the priority is always set to 0.

### Steps to reproduce

Create a task with some priority greater than zero and the duplicate it in another project.

### Configuration

Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.16
PHP SAPI: fpm-fcgi
OS version: Linux 3.13.0-79-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by levlaz** [comment]
Can you confirm that this is still happening? I just tried this on a fresh dev environment and it works for me.

**Comment by carlosabalde** [comment]
I'm sorry but we stopped using kanboard a few weeks ago. Thanks!

**Comment by fguillot** [comment]
This feature is now supported in the development branch.
