### ISSUE TITLE
1.0.28 - Remove task: Page not found -- Sorry, I didn't find this information in my database! 

### ISSUE THREAD

**Issue by jtourt** [fguillot/kanboard#2258]
### Expected behaviour

After removing a task, browser should redirect to board view.

### Actual behaviour

Page not found 
Sorry, I didn't find this information in my database! 

![image](https://cloud.githubusercontent.com/assets/14179005/15454251/35327254-2001-11e6-9b21-e1e84a15bf3e.png)

### Steps to reproduce

1. Open any task.
2. Click Remove.
3. Click Yes to confirm that you really want to remove this task.

### Configuration

Application version: 1.0.28 
◾ PHP version: 5.6.20-0+deb8u1 
◾ PHP SAPI: fpm-fcgi 
◾ OS version: Linux 4.1.19-v7+ 
◾ Database driver: mysql 
◾ Database version: 5.5.44-0+deb8u1 
◾ Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Comment by fguillot** [comment]
This issue is now fixed in the development branch. Thanks.

Duplicate with #2201
