### ISSUE TITLE
DB migration conflicts

### ISSUE THREAD

**Issue by d4rk5eed** [fguillot/kanboard#2268]
Hi guys,
have question.

For example, I need to add migration for custom field in existing table.
I've made some coding in schema/*.php and added function version_102.
But time passed and new kanboard version released with new migrations.
Thus I have got confilct between my version_102 and "native" version_102.

Do you have any ideas about resolving this issue?

**Comment by fguillot** [comment]
You should use a plugin that run custom migrations: https://kanboard.net/documentation/plugin-schema-migrations

**Comment by d4rk5eed** [comment]
@fguillot thanx
