### ISSUE TITLE
overdue notifications fails (Slack Integration)

### ISSUE THREAD

**Issue by dfpena** [fguillot/kanboard#2270]
### Expected behaviour

Send overdue notifications

### Actual behaviour

PHP Notice:  Undefined index: task in /var/www/kanboard/plugins/Slack/Notification/Slack.php on line 30
PHP Catchable fatal error:  Argument 3 passed to Kanboard\Plugin\Slack\Notification\Slack::sendMessage() must be of the type array, null given, called in /var/www/kanboard/plugins/Slack/Notification/Slack.php on line 31 and defined in /var/www/kanboard/plugins/Slack/Notification/Slack.php on line 98

### Steps to reproduce

1.  open terminal on server
2. cd into kanboard directory
3. ./kanboard notification:overdue-tasks

### Configuration

Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.16.0-45-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36

**Comment by levlaz** [comment]
I think this issue should be filed under the plugin itself https://github.com/kanboard/plugin-slack/issues

**Comment by fguillot** [comment]
This is issue won't be fixed because it doesn't happens with Kanboard > 1.0.28. The task overdue event is not handled by the notification subscriber. You just need to upgrade to the latest version and that should solve your issue.
