### ISSUE TITLE
Add zip to the PHP Extensions Required page

### ISSUE THREAD

**Issue by nitr8** [fguillot/kanboard#2272]
### Expected behavior
When viewing the requirements page php-zip should be listed under the "PHP Extensions Required" section https://kanboard.net/documentation/requirements. As it is now a requirement for the new plugin changes happening.

### Actual behavior
N/A

### Steps to reproduce
N/A

### Configuration
N/A

**Comment by oparoz** [comment]
@nitr8 - Maybe you could provide a PR straight from Github?
https://github.com/fguillot/kanboard/blob/master/doc/requirements.markdown

**Comment by nitr8** [comment]
will do from now on :)

**Comment by fguillot** [comment]
It's already done. Thanks.
