### ISSUE TITLE
Usability-Improvement: Project name with link

### ISSUE THREAD

**Issue by wrkb** [fguillot/kanboard#2276]
### Expected behaviour

Project name on top left should be clickable

### Actual behaviour

After clicking on a task it's uncomfortable to navigate back to the project. Yes, the board menu does it, but it is very unintuitive.

### Steps to reproduce

1. Open a task
2. Try to navigate back to the project immediately

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 0.27

**Comment by wrkb** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/9445370/15674241/00172f78-273c-11e6-80ea-c11dc72ff958.JPG)

**Comment by fguillot** [comment]
It's now available in master. Thanks.

Merged PR #2288
