### ISSUE TITLE
Notification:Overdue-tasks is not working in KB 1.0.28

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#2284]
### Expected behaviour

Tell us what should happen
when in shell as su running executable ./kanboard notification:overdue-tasks throws an PHP fatal exception. 

### Actual behaviour

Tell us what happens instead

PHP Fatal error:  Call to undefined method Kanboard\Core\Template::e() in /var/w                                                             ww/html/kanboard/app/Template/notification/task_overdue.php on line 26
<h2>Overdue tasks for the project(s) &quot;Project_IS_FY15-16 Security Remediati                                                             on&quot;</h2>

<table style="font-size: .8em; table-layout: fixed; width: 100%; border-collapse                                                             : collapse; border-spacing: 0; margin-bottom: 20px;" cellpadding=5 cellspacing=1                                                             >
    <tr style="background: #fbfbfb; text-align: left; padding-top: .5em; padding                                                             -bottom: .5em; padding-left: 3px; padding-right: 3px;">
        <th style="border: 1px solid #eee;">Id</th>
        <th style="border: 1px solid #eee;">Title</th>
        <th style="border: 1px solid #eee;">Due date</th>
        <th style="border: 1px solid #eee;">Project</th>
        <th style="border: 1px solid #eee;">Assignee</th>
    </tr>

            <tr style="overflow: hidden; background: #fff; text-align: left; pad                                                             ding-top: .5em; padding-bottom: .5em; padding-left: 3px; padding-right: 3px;">
            <td style="border: 1px solid #eee;">#24</td>
            <td style="border: 1px solid #eee;">
                                    <a href="https://myurl/kanboard/?contr                                                             oller=task&amp;action=show&amp;task_id=24&amp;project_id=8">Implement AD Managem                                                             ent System</a>
                            </td>
            <td style="border: 1px solid #eee;">04/14/2016</td>
            <td style="border: 1px solid #eee;">Project_IS_FY15-16 Security Reme                                                             diation</td>
            <td style="border: 1px solid #eee;">

### Steps to reproduce

1. ssh to box
2. sudo ./kanboard notification:overdue-tasks
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.28
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.13.0-87-generic
Database driver: postgres
Database version: 9.3.13
Browser: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by fguillot** [comment]
Upgrade to 1.0.30, this issue should be fixed: https://kanboard.net/news/version-1.0.30
