### ISSUE TITLE
Board view: Show due dates for today in another colour

### ISSUE THREAD

**Issue by akien-mga** [fguillot/kanboard#2285]
### Expected behaviour

I'd like to have the due date of the tasks due for today shown in a colour that is different from the one of past-deadline tasks. Green or blue could be a good choice.

### Actual behaviour

Current tasks that are due today have their due date coloured in red, just like tasks that are already in the backlog.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.25-framaboard
- Database type and version: sqlite, version unknown
- PHP version: Unknown
- OS: Windows 7 x86_64
- Browser: Google Chrome 50.0.2661.102 m

**Comment by fguillot** [comment]
This is now part of master.
