### ISSUE TITLE
Unable to correctly display attachments

### ISSUE THREAD

**Issue by Issam2204** [fguillot/kanboard#2291]
### Expected behaviour
I'd expect to correctly see attachments after uploading them.

### Actual behaviour
It is not possible to open attachments. An error is displayed when I try to open an image just uploaded.

After uploading:
![1](https://cloud.githubusercontent.com/assets/8282518/15807212/0710311a-2b58-11e6-861c-2f951f879014.png)

When I try to open the attachment (a .png image):
![2](https://cloud.githubusercontent.com/assets/8282518/15807193/9cca976e-2b57-11e6-911b-807f544957ec.png)

### Steps to reproduce

1. Go to the overview page of the project
2. Click on the attachment section and start uploading a file (e.g. an image)
3. Open the recently upload image from the attachment section: an error appears.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: fpm-fcgi
OS version: Linux 4.2.0-36-generic
Database driver: sqlite
Database version: 3.8.2
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by fguillot** [comment]
This is fixed in master, you can do a `git pull`. Thanks

**Comment by Issam2204** [comment]
It works perfectly now. Thanks!
