### ISSUE TITLE
kanboard 1.0.29 - Internal Error: Identifier "language" is not defined

### ISSUE THREAD

**Issue by radimoto** [fguillot/kanboard#2292]
### Expected behaviour

Tell us what should happen

I am trying to upgrade from Kanboard 1.0.28 to 1.0.29.
My only installed plugin is Color_filter

### Actual behaviour

Tell us what happens instead

I tried to upgrade as per usual but am now getting an error:

Internal Error: Identifier "language" is not defined

It looks like this may be due to a missing Metadata plugin. I have found the Metadata plugin 1.0.3 which is for 1.0.28 (is this compatible with 1.0.29?) I have tried to install this plugin but I still have the error occurring and cannot use Kanboard.

### Steps to reproduce

1. Upgrade Kanboard from 1.0.28 to 1.0.29  
2.  
3.  

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Upgrading from 1.0.28 to 1.0.29
- Database type and version: 5.5.47-MariaDB - MariaDB Server
- PHP version: 5.6.22
- OS: CentOS 7
- Browser: Chrome

**Comment by radimoto** [comment]
This issue is actually caused by the plugin Color_filter. If I move the plugin out of the way to /tmp/ Kanboard runs OK.

**Comment by fguillot** [comment]
All plugins must be updated to work with Kanboard 1.0.29. External contributors have to update their plugins. You should report the issue to the author of Color_filter.

**Comment by Busfreak** [comment]
Plugin updated, please close this issue.

**Comment by levlaz** [comment]
I had the same issue using the GitHub webhooks plugin (that was installed in the old way) removing the plugin fixed it.

**Comment by agentcobra** [comment]
Same for me, 
but I've delete old plugins and it's works again
agentcobra

**Comment by levlaz** [comment]
@fguillot since it seems that having _most_ plugins installed will cause the update to fail, would it make sense to just have a step in the upgrade process to automatically either: 

1. Try to upgrade all plugins and disable the ones that still don't work 
2. Just disable all plugins and tell the user to install them via the new plugin system

**Comment by agentcobra** [comment]
@levlaz or change update to a major one

**Comment by fguillot** [comment]
I close this issue, you can propose any improvements on the release process on this thread #2301
