### ISSUE TITLE
Search in DashboardController not working

### ISSUE THREAD

**Issue by eSkiSo** [fguillot/kanboard#2298]
### Expected behaviour
Search for task or project

Tell us what should happen
List search results

### Actual behaviour
When you try to search something on Dashboard it gives you an Controller not found error

Tell us what happens instead
Error: Controller search not found

**Url badly formed?** - ?controller=**search**&action=index&**SearchController**=test

### Steps to reproduce

1. Go to Dashboard
2. Type something on search
3. Press Enter

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.29
- Database type and version: mysql
- PHP version: 5.5.9-1ubuntu4.17
- OS: Linux 3.13.0-87-generic
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by radimoto** [comment]
I just noticed this as well. The search directly on the dashboard returns the controller not found error. But the search link works OK.  
  
From the dashboard, this fails:

www.example.com/kanboard/?controller=search&action=index&search=status%3Aopen

But using the search link on the dashboard (to it's own search page) works:

www.example.com/kanboard/?controller=SearchController&action=index&search=status%3Aopen

**Comment by Busfreak** [comment]
PR to fix this: https://github.com/fguillot/kanboard/pull/2299

**Comment by fguillot** [comment]
Fix is available in the latest tag (v1.0.30). Thanks.
