### ISSUE TITLE
pre-release?

### ISSUE THREAD

**Issue by Busfreak** [fguillot/kanboard#2301]
Hello,

what about a pre-release, or an announcement of a new release, so we can test the application, change plugins and update translation befor final release?

**Comment by REJack** [comment]
@fguillot it seems you use [SemVer](http://semver.org/), if yes you could create a release like `1.0.30-alpha` or `1.0.30-beta` 

see [SemVer's pre-release Info's](http://semver.org/#spec-item-9) for more details

**Comment by levlaz** [comment]
@fguillot I really like the approach that atom takes, they talk about it in depth in their blog: http://blog.atom.io/2015/10/21/introducing-the-atom-beta-channel.html

**Comment by Busfreak** [comment]
I agree with levlaz.
The way you released in the past would best fit to the "release train model" with three rails, master, beta, stable. You work on master like you do right now. We do the testing and language work on beta, until it is stable and the "end user" gets the build from stable. New features have to be introduced to master. This leads to a time gap in releasing new fetures, but right now it's the same. 1.0.28 is stable, 1.0.29 is beta...

**Comment by fguillot** [comment]
Your suggestions have been taken into consideration: https://kanboard.net/news/release-cycle

We will try like that and adjust if necessary.
