### ISSUE TITLE
Browser Tests

### ISSUE THREAD

**Issue by levlaz** [fguillot/kanboard#2304]
I submitted a [minor UI bugfix](https://github.com/fguillot/kanboard/pull/2303) and as much as I wanted to write a test for it, I noticed that there are no "end to end" or browser tests for Kanboard. @fguillot do you have any plans for this, I would be glad to get us started using Selenium or something, but do not want to write a bunch of browser tests (because its kind of a PITA) if you have something else in mind.

**Comment by fguillot** [comment]
Of course I'm ok to have automated tests with Selenium. They can be written in Python or PHP.

Don't need to test everything because maintaining that is very time consuming. Testing the most important flow should be enough. If you would like to start the first baby step, go for it :)

**Comment by levlaz** [comment]
I had a heck of a time trying to get this working with phpunit, selenium, and firefox. Since I have done this extensively with python I will opt for that approach. Thanks!
