### ISSUE TITLE
Fresh `vagrant up` Not Working

### ISSUE THREAD

**Issue by levlaz** [fguillot/kanboard#2305]
### Expected behaviour

I should be able to go to `localhost:8001` and see the kanboard site once vagrant finishes provisioning the box with `vagrant up`

### Actual behaviour

Going to `localhost:8001` shows that the server is not reachable. If I `vagrant ssh` into the machine and try to `curl localhost` it results in a 500 error. The apache logs show: 

```
[Tue Jun 07 01:49:50.864089 2016] [:error] [pid 6010] [client 127.0.0.1:54445] PHP Fatal error:  
require(): Failed opening required '/var/www/html/app/../vendor/autoload.php' 
(include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/app/common.php on line 3
```

### Steps to reproduce

1. clone this repo 
2. execute `vagrant up`

### Configuration

Unable to do this, since the site is not loading. However, this is from a fresh clone of master running `vagrant up`.

**Comment by levlaz** [comment]
Per the error: 

`/var/www/html/app/common.php on line 3` 

this is what is included on line 3 of `common.php`

```
require __DIR__.'/../vendor/autoload.php';
```

**Comment by levlaz** [comment]
This is happening because composer is not being installed or called by default. Sending a PR to fix this now.

**Comment by fguillot** [comment]
Merged your PR. Thanks.
