### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by mauriziodidomenico** [fguillot/kanboard#2311]
### Expected behaviour
Different user icon background colors.

### Actual behaviour
they are all green with white initials.

### Configuration

Application version: master
PHP version: 7.0.7
PHP SAPI: apache2handler
OS version: Linux 4.4.11-1-ARCH
Database driver: sqlite
Database version: 3.13.0
Browser: Mozilla/5.0 (X11; CrOS x86_64 7978.74.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.103 Safari/537.36

![pild 1](https://cloud.githubusercontent.com/assets/16655789/15862899/742ea1a8-2cd1-11e6-85df-6f32e7edd6f9.png)

**Comment by TabDambrine** [comment]
Hi

I ran into the same problem with #2163. I'm not sure but I think it's because of 64bits and 32bits differences in PHP.
Could you try the solution I used in the mentioned thread and see if this works for you ?

**Comment by mauriziodidomenico** [comment]
Yes it Works.

Just edit app/User/Avatar/LetterAvatarProvider.php (line 145) :
`$max = intval(9007199254740991 / $seed2);`
into (per example)
`$max = intval(90071992547409 / $seed2);`

**Comment by fguillot** [comment]
This issue is now solved in the dev branch.
