### ISSUE TITLE
Plugin Directory install

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#2313]
Hi @fguillot,

I have a question regarding the new plugin directory install.
What should I change that the Github-Release-Zip is extracted correct?

https://github.com/BlueTeck/kanboard_plugin_coverimage/archive/1.0.29.0.zip is extracted to 
kanboard_plugin_coverimage-1.0.29.0 (instead of Coverimage) and so the plugin is not working?

Related https://github.com/BlueTeck/kanboard_plugin_coverimage/issues/4

Regards,
Timo

**Comment by levlaz** [comment]
@BlueTeck I think this may have to do with the name of the file. If you look at the makefile for plugin-budget https://github.com/kanboard/plugin-budget/blob/master/Makefile it has a specified archiving step. 

Can you try to add this Makefile to your repo and then: 

```
export plugin=Coverimage
export version=1.0.29
make
```

Best, 
Lev

**Comment by BlueTeck** [comment]
Ah my mistake, I thought that my Github generated Source Archive is wrong, but I have to upload a release build. Thanks ;)
