### ISSUE TITLE
Internal Error: Identifier "language" is not defined.

### ISSUE THREAD

**Issue by SoftBrok** [fguillot/kanboard#2318]
### Expected behaviour

Kanboard should work

### Actual behaviour

It displays this message:

Internal Error: Identifier "language" is not defined.

and does not work. Debug mode shows nothing else.

### Steps to reproduce

1. Load Kanboard

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: Latest from ZiP. Installed Today.
- Database type and version: Default
- PHP version: PHP 5.4.16 (cli) (built: May 12 2016 13:45:17) 
- OS: CentOS7
- Browser: Latest Firefox

Plugins are configured as follows:

Jabber	Metadata  Milestone  Registration  Sendgrid  SubtaskForecast  Timetable

**Comment by fguillot** [comment]
Don't forget to update all your plugins.

**Comment by SoftBrok** [comment]
I just pulled them down from the ZIP files linked to from the home page.

Is the home page out of date?

**Comment by SoftBrok** [comment]
Yes, it looks like they are. If you install everything from official website zips, it will be broken.

**Comment by fguillot** [comment]
Some plugins are not compatible with the latest version of Kanboard, for example Milestone is only compatible with v1.0.28: https://kanboard.net/plugin/milestone You may want to ask to the author to update his plugin: https://github.com/oliviermaridat/kanboard-milestone-plugin
