### ISSUE TITLE
[Bug] My dashboard (overview) -> filter to "open tasks" results in "Internal Error: Controller not found" error

### ISSUE THREAD

**Issue by GeorgeFischhof** [fguillot/kanboard#2323]
### Expected behaviour

Menu item should display my open tasks

### Actual behaviour

There is an error message "Internal Error: Controller not found"

### Steps to reproduce

1. login to kanboard
2. select my dashboard from top-right corner menu
3. set filter on top-lef to "open tasks"

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.29
- Database type and version: sqlite 3.8.10.2 (kanboard's installed db)
- PHP version: 7.0.7 (latest I found)
- OS:Win 8.1 (fulli patched, updated)
- Browser:Firefox latest (46.0.1)

**Comment by fguillot** [comment]
I new version have been published to fix this issue, you can download the version 1.0.30: https://kanboard.net/news/version-1.0.30
