### ISSUE TITLE
What do you prefer: tags or hashtags?

### ISSUE THREAD

**Issue by fguillot** [fguillot/kanboard#2331]
Having tags in Kanboard seems to be a popular request, which method do you prefer?

1. Tags (list of keywords) similar to the proposed solution in the issue #646 
2. Hashtags in task description similar to Twitter #my-keyword
3. Both?

Thanks

**Comment by ptman** [comment]
I would expect tags to work without having to write them using #syntax in the description, but can live with that. Worst case I'd just put them in the end of the description. Does # clash with some formatting syntax currently in use in descriptions (I'm guessing descriptions _aren't_ markdown)? Does it clash with something that people would want to write in the description? Should it be possible to escape it?

**Comment by oparoz** [comment]
I vote for true tags ("3 tables: "tasks", "tags" and "tasks_tags" as a junction table").
Hashtags in descriptions are going to be problematic when someone references an issue using #1234566, but tags could be added to the description when exporting to some text formats.

**Comment by fguillot** [comment]
Task description is using Markdown. There is already a custom extension to parse `#123` and generate a link that to this task.

On the technical perspective having tags outside of the task description seems to be easier to implement. I don't need to parse anything and I can display an autocomplete field.

**Comment by jtourt** [comment]
Tags.   Thank you.

**Comment by ptman** [comment]
Yes, autocomplete is a good point. It's really useful in order to not have slight variations of tags. Maybe some way to list all tags is needed as well?

**Comment by menegrete** [comment]
true tags +1

**Comment by thob** [comment]
tags outside of description, treated like categories

**Comment by BlueTeck** [comment]
Real tags!

Example Libary that I am using for Laravel: https://github.com/cviebrock/eloquent-taggable
together with http://selectize.github.io/selectize.js/ tags to enter them

**Comment by nidico** [comment]
I'd go for real tags (though I'd rather pre-define the tags, same as github labels, but on-the-fly tag creation is also okay).

**Comment by joeaston** [comment]
First priority: Real / True tags
Nice to have: #hashtags

**Comment by szawadski** [comment]
I agree with @joeaston. First priority are (real/searchable/filterable) tags.
Hashtags with auto-complete would be a great nice-to-have oriented on productivity if they are creating/affecting tags while typing the title or description of a task.
Auto-complete (and auto-colouring of tags if their number is limited) would be nice for tags but necessary for in-text hashtags.
Looking forward to testing the version 1.0.31 !

**Comment by GeorgeFischhof** [comment]
Hi, tags would be better for me. :-)

**Comment by virtualtam** [comment]
+1 for plain tags, they could be used to mirror a web-hooked issue tracker's tags/labels (e.g. GitHub issues)

**Comment by Chaosmeister** [comment]
:+1: plain tags for me. should be filterable though.

**Comment by fguillot** [comment]
The first iteration of the "tags feature" is now available in the development branch. Many improvements will come up in next versions.

https://github.com/fguillot/kanboard/blob/master/doc/tags.markdown
