### ISSUE TITLE
Problem with layout  issue left menu

### ISSUE THREAD

**Issue by JohnBat26** [fguillot/kanboard#2336]
### Expected behaviour

Normal layout of issue left menu

### Actual behaviour

Broken layout of issue left menu

### Steps to reproduce

1. Go to issue details

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: last master(  0e35f818)
- Database type and version: postgres (9.5)
- PHP version: 5.6.21
- OS:  Linux 3.10.0-327.el7.x86_64
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by JohnBat26** [comment]
![screenshot_20160611_002612](https://cloud.githubusercontent.com/assets/732942/15979263/b594c93c-2f6b-11e6-8fe6-d315f0b1280f.png)

**Comment by fguillot** [comment]
I reverted the pull-request that introduced this bug.
