### ISSUE TITLE
Internal link lists all tasks from all projects

### ISSUE THREAD

**Issue by Olliiee** [fguillot/kanboard#2340]
### Expected behaviour

Set an internal link to an existing task within the project. Typing the name of the tasks, getting a list of all possible tasks within the project.

### Actual behaviour

Getting a list of all possible tasks of all existing projects. I don't think this is the right behavior.

### Steps to reproduce

1. Create at minimum 2 projects.
2. Create some tasks in project 1.
3. Create some tasks in project 2.
4. Set an internal link for a task in project 2 by typing the name of a task in project 1.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Version: 1.0.30
PHP Version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS Version: Linux 3.13.0-32-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.49-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by fguillot** [comment]
Actually, this is a feature :) You can link tasks between different projects.

**Comment by Olliiee** [comment]
Would be nice to have the name of the project in front of the task. "ProjectName/TaskName" makes it easier to find the right task.

**Comment by fguillot** [comment]
The project name is now displayed (only in development branch).
