### ISSUE TITLE
Feature request - week starting on Monday

### ISSUE THREAD

**Issue by adgu** [fguillot/kanboard#2341]
Can we please add ability to display weeks in the calendar with Monday as the first day?

Thanks.

**Comment by cmmata** [comment]
My calendar starts on monday, but I don't see any option to choose that. Maybe it's because I have it in spanish.

**Comment by adgu** [comment]
Mine starts on Sunday so I guess it is pulling this setting from the server?

**Comment by adgu** [comment]
I noticed this issue/feature was mentioned before (#1537).
Closing the issue.
