### ISSUE TITLE
How to use API with PHP

### ISSUE THREAD

**Issue by bdrayer** [fguillot/kanboard#2342]
Hi,

I tried to use the API using the examples but without success, I always get an error :+1: 
PHP Fatal error:  Class 'Client' not found in /var/www/kanboard/test.php on line 5
 
Here is my code : 

<?php

$client = new JsonRPC\Client('https://www.example.com/kanboard/jsonrpc.php');
$client->authentication('jsonrpc', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
$client->getHttpClient()->withDebug();
print_r($client->getAllProjects());

?>

It work with the same informations (the URL, the method and the auth key) using curl

What did I do wrong?

**Comment by euneuber** [comment]
Hi,

Did you install https://github.com/fguillot/JsonRPC ?
I did install this library via composer and added this line at the beginning of your code:

`
include_once __DIR__ . '/vendor/autoload.php';
`

**Comment by bdrayer** [comment]
Hi,

No need to install them, it's already installed but your Include line does the work. Thank you.
