### ISSUE TITLE
How can I increase the attachment size restriction

### ISSUE THREAD

**Issue by seancarson** [fguillot/kanboard#2353]
Hello, How do I go about increasing the attachment size restriction from 2M to something bigger.  Can this be done by modifying php.ini values? Also, what is the recommended Max

Thanks

### Configuration

Application version: 1.0.30
PHP version: 5.5.9-1ubuntu4.17
PHP SAPI: apache2handler
OS version: Linux 3.13.0-87-generic
Database driver: postgres
Database version: 9.3.13
Browser: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by fguillot** [comment]
This is defined by your `php.ini`, you have to change those values and restart your web server:

```
; Maximum allowed size for uploaded files.
upload_max_filesize = 40M

; Must be greater than or equal to upload_max_filesize
post_max_size = 40M
```

**Comment by seancarson** [comment]
Got it, Thank you.

**Comment by shadson** [comment]
Hello,
As I understand, attachments is stored as files (not BLOBs), so they will be not downloaded together with database when I do 'Download database' as Admin. 
Is it any way make a backup of all my data (DB + attachments + avatars + what else...) with single click or script?
Thank you, we are trying to implement Kanboard in our team (not SW development, mostly marketing and promotion) - I am really impressed with the features it has already even comparing with commercial software.
