### ISSUE TITLE
Question/Feature Request: A global board

### ISSUE THREAD

**Issue by flow7** [fguillot/kanboard#2357]
_(Sorry, not sure if this is the right place to ask)_

**Question**: Is there a way to have a view of all projects on one board?
**Longer**: There is a dashboard, which sums up all projects, tasks etc in one view, but doesn't provide a clear or easy digestible view of important and urgent issues, tasks.
I'd appreciate a brief graphic overview of all projects, that depicts the overall level of progress and provides a good point for starting to tackle the tasks... 

One possible example could be the Dashboard at Restyaboard: http://board.demo.restya.com/#/boards

_Maybe Kanban is not intended to provide an overview over various projects?_

**Comment by fguillot** [comment]
This feature doesn't exists at the moment. There is already a discussion open for this topic, see #426.
