### ISSUE TITLE
Question: Move icon

### ISSUE THREAD

**Issue by dmcnaughtan** [fguillot/kanboard#2358]
Question:  I have two instances running (v1.0.28 and v1.0.30).  I seem to be the only user that sees the move icon on v1.0.28.  I don't see the icon on v1.0.30.

![image](https://cloud.githubusercontent.com/assets/12763080/16120270/e0fde622-33ac-11e6-9289-288e79192b8c.png)

Is there a way to enable that globally?

**Comment by BlueTeck** [comment]
Normally this Icon to drag and drop appears if you are on a touch device, otherwise you could drag the whole task.

**Comment by dmcnaughtan** [comment]
I confirm that it's appearing using Chrome on Windows 8.1, but now using Firefox.
No worries - just a bit weird.
