### ISSUE TITLE
#UI - sort comment order

### ISSUE THREAD

**Issue by DoumeDuSud** [fguillot/kanboard#236]
It just a little improvement : 
is ti possible to invert the order of comment in order to have the newest on top ? 
if it's just a value to modify in one config file witch one it is ?
Thanks in advance

Personnaly we use a lot the comment to precise the advancement of task, so after some comment we lose so time to scroll to the end.
And maybe later on devellopement, one usefull function (when we are 3-4 to work on one task) will be the able to answer to one particular comment. But sorry, I don't know how to code, so I cannot give help for this

**Comment by fguillot** [comment]
With the last development version, it's possible to choose the sorting direction for comments.

**Comment by Cathryne** [comment]
Merci :-)
