### ISSUE TITLE
Budget Plugin

### ISSUE THREAD

**Issue by OWENCRUZ** [fguillot/kanboard#2364]
Feature Request: 

Hi, this is a very useful piece of Software. In fact, even if it's designed as IT / programming project management board, we're able to use it in our construction company. It'll be good if you can improve the budget plugin such it it'll allow to create projected budget and actual budget used. Based on both materials and labor.

If this can be accomodated, I'm very much willing to send details of how it can be implemented.

**Comment by REJack** [comment]
A Budget Plugin is already available. https://kanboard.net/plugin/budget

**Comment by OWENCRUZ** [comment]
Thanks @REJack . I actually got that installed. However, budget is designed for hourly rate. I'm thinking if it can be enhanced to include, labor, materials and other cost category. I've already submitted a request for a quote to see if I can afford to sponsor enhancement.

**Comment by fguillot** [comment]
For the budget plugin, you should open your feature requests here https://github.com/kanboard/plugin-budget/issues

That will be useful to see if other people are interested by your suggestions.

Thanks
