### ISSUE TITLE
Possibility to chose the Creator when creating a new task

### ISSUE THREAD

**Issue by bdrayer** [fguillot/kanboard#2366]
### Expected behaviour

When crating a task it will be great to add the possibility to change who is the creator of a task, because sometimes people are to lazy to do it, ...

### Actual behaviour

The person who create the task is the creator

### Configuration

Not relevant in this case, ...

### Comments

I will be very happy to create a plugin if I have the necessary knowledge to do it but it's not the case, ...

**Comment by angystardust** [comment]
Hi @bdrayer , this feature was already requested in #2293
