### ISSUE TITLE
no new task created when Use Mailgun to create tasks from emails

### ISSUE THREAD

**Issue by inuvalogic** [fguillot/kanboard#2373]
### Expected behaviour

I'm following your docs to "Use Mailgun to create tasks from emails" at Mailgun plugin

use Mailgun for mydomain.com and installing kanboard on myotherdomain.com

have add this on Mailgun Routes

match_recipient("^kanboard\+(.*)@mydomain.com$")
forward("http://www.myotherdomain.com/kanboard/?controller=WebhookController&action=receiver&plugin=mailgun&token=my_token") -> the URL from Settings > Integrations

if I send an email from the email registered as project member to kanboard+PROJECTNAME@mydomain.com, new task should be created
on the project

### Actual behaviour

but when trying to send an email to kanboard+PROJECTNAME@mydomain.com, no new task created, even in Mailgun Logs my email not there

is it installing kanboard on different domain take an effect? or it just a problem with Mailgun

### Steps to reproduce

1. setting Routes on Mailgun dashboard
2. send email to kanboard+PROJECTNAME@mydomain.com
3. new task should be created, but this is not

### Configuration

Application version: 1.0.30
PHP version: 5.4.45
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-604.16.2.lve1.3.54.el6.x86_64
Database driver: mysql
Database version: 5.5.50-cll
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by jtourt** [comment]
It's a problem with Mailgun.  Concentrate on getting your Mailgun configuration working.  "Even in Mailgun logs my email not there."   If your emails are not arriving at Mailgun, then you have a Mailgun configuration issue.  Review the Mailgun documentation for setting up DNS and MX records.  Check that your domain is verified in Mailgun.

Installing Kanboard on a different domain than the domain used for Mailgun is not an issue.

**Comment by inuvalogic** [comment]
thank you very much, I'm not setting up the MX records for receiving email at Mailgun
now the new task created successfully :)
