### ISSUE TITLE
CSV export of tasks contains warnings and HTML content

### ISSUE THREAD

**Issue by Sp0oky** [fguillot/kanboard#2374]
### Expected behaviour

Exporting a CSV file should only contain the list of tasks that match the date range specified.

### Actual behaviour

The CSV export file contains the list of tasks but also, immediately after the last task, the following output (note: I have truncated the HTML output rather than list all of it):

<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\Apache24\htdocs\kanboard\app\Core\Csv.php:171) in <b>C:\Apache24\htdocs\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="robots" content="noindex
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="referrer" content="no-referrer">
 *** truncated ***

### Steps to reproduce

1. Select a Project
2. Select "Menu" and then "Exports"
3. Select the date range for the tasks and then click "Execute"
4. Open the CSV and scroll down through the file to the end of the task list to see the first warning as above

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.30
- Database type and version: 10.0.21-MariaDB
- PHP version: 7.07
- OS: Windows NT 10.0
- Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
This issue have been fixed in the development branch. Thanks!
