### ISSUE TITLE
User mention suggestion not working

### ISSUE THREAD

**Issue by OWENCRUZ** [fguillot/kanboard#2375]
### Expected behaviour

When typing @userid, Kanboard should show / suggest list of users.

### Actual behaviour

Drop down list of users do not show up.

### Steps to reproduce

as explained

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.27
PHP version: 5.5.35
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-431.29.2.el6.x86_64
Database driver: mysql
Database version: 5.5.50-cll
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
Yes, It's known issue, duplicate with #2045
