### ISSUE TITLE
reverse proxy user role always changed to 'app-user' at login

### ISSUE THREAD

**Issue by schtritoff** [fguillot/kanboard#2380]
### Expected behaviour

User roles should be preserved on user login

### Actual behaviour

User role is always changed to app-user on login when using reverse proxy (can't test another login provider). REVERSE_PROXY_DEFAULT_ADMIN is working as expected.

### Steps to reproduce
Configure kanboard with:
REVERSE_PROXY_AUTH=true
REVERSE_PROXY_USER_HEADER=REMOTE_USER
REVERSE_PROXY_DEFAULT_ADMIN=administrator  (<- this is the only admin user working right now)

### Configuration

Application version: 1.0.30 
◾ PHP version: 5.6.20 
◾ PHP SAPI: fpm-fcgi 
◾ OS version: Linux 3.10.0-327.13.1.el7.x86_64 
◾ Database driver: mysql 
◾ Database version: 5.5.47-MariaDB 
◾ Browser: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)

**Comment by phoen1x** [comment]
After an update I faced a similar issue and can provide a Docker-Container with a HAProxy to reproduce the reverse proxy.

## Details

I updated a old Kanboard to Docker 1.0.31

* Application version: master.fc93203e4db044d37c1686fef0efb1ac1d6ac4b8
* PHP version: 5.6.21
* PHP SAPI: fpm-fcgi
* OS version: Linux 4.4.0-24-generic
* Database driver: sqlite
* Database version: 3.13.0

and set my role in the database manually. But this had no effect.

`update users set role='app-admin' where username='MY_USER';`

@schtritoff: Thanks for the "steps to reproduce" setting REVERSE_PROXY_DEFAULT_ADMIN=MY_USER worked for me as a hotfix.

**Comment by fguillot** [comment]
Actually it was the expected behaviour. Anyway, now the role is preserved if the user already exists. This change is available only in the development branch at the moment.

Thanks
