### ISSUE TITLE
Problem in calling procedures online

### ISSUE THREAD

**Issue by nipasoni** [fguillot/kanboard#2386]
### I configured josonRPC using php

All procedures call perfectly in my local server but when i upload same file on server then it will display HTTP Error 500

### All procedure work perfect in local but problem arise when used online

Tell me how can i solve this problem

### Steps to reproduce

1. give proper detail about where we have to give base64(user:password)  
2. 
3.

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: 1.0.30
- Database type and version:  Sqlite 3.x
- PHP version: 5.3
- OS: linux server 
- Browser: crome , firefox

**Comment by fguillot** [comment]
You should provide some details and context, it's impossible to say what is wrong based on your message. Your issue is probably only a configuration problem.

**Comment by nipasoni** [comment]
yes fguillot you are right its just configuration problem i have solved that error.
thank you so much
