### ISSUE TITLE
Identifier "userNotificationType" is not defined. / Upgrade to 1.0.30 fails

### ISSUE THREAD

**Issue by mdawart** [fguillot/kanboard#2387]
While upgrading from 1.0.26 to latest/1.0.30 I got the Schema error: 

> Internal Error: Unable to run SQL migrations: Running migration \Schema\version_108, Running migration \Schema\version_109, Running migration \Schema\version_110, SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'user_has_notifications_ibfk_2'; check that column/key exists (You may have to fix it manually)

after fixing this manually and setting the scheme version to 110 / 111

i always get the error

> Internal Error: Identifier "userNotificationType" is not defined.

I also tried to just upgrade to 1.0.27 / 1.0.29 but always got the same error

### Configuration
- Database type and version: MySQL 5.6.28-log - Source distribution
- PHP version: 5.6.22-pl0-gentoo
- Browser: Chrome / Firefox

**Comment by fguillot** [comment]
The class `UserNotificationType` have been renamed `UserNotificationTypeModel` in v1.0.29. Maybe, you are using plugins that send notifications, you have to update all plugins to make it work with v1.0.30.

**Comment by mdawart** [comment]
Yes this solved my problem, thank you!
