### ISSUE TITLE
New Language ?

### ISSUE THREAD

**Issue by bluegroper** [fguillot/kanboard#2390]
I searched the documentation for any instructions to add/create a new language.
Sorry if I missed something.

Please, what are the steps to add language to locale directory.
I was hoping to start with en_GB file and make a few small changes before saving as en_AU or en_US.
Seems there's no en_GB file/s in locale.
TIA's for any tips or clues.

Edit.  It looks like the following steps might be working ;
1.  Create directory .../Locale/en_US
2.  Create the file translations.php, containing ONLY the words/labels desired to be changed.  Omit all other words that can use defaults.

Am I doing this "the-right-way" (tm) ?

**Comment by BlueTeck** [comment]
https://kanboard.net/documentation/translations

**Comment by bluegroper** [comment]
I had searched the official documentation for the string "language".  Sorry I missed the "translation" page.
Looking at "the-right-way" per documentation, I'm thinking my method my work better since it will likely survive any update to the file app/Model/Language.php (or its later equivalent).
Thx for helps.
