### ISSUE TITLE
Howto Delete or Remove a Project ?

### ISSUE THREAD

**Issue by bluegroper** [fguillot/kanboard#2392]
Sorry for newbie question.
I search the documentation but cannot find the step/s to delete or remove a finished (or unwanted) project.
Please for any directions to achieve this important feature.

Edit #1.  Found it.
Login, Project management, click at Users overview to show Projects list, click at the settings gear-wheel for the unwanted project, Remove.

Edit #2.  Any forum ?
Is there a web forum where newbies can post questions and help requests ?
Maybe better than cluttering up the github issues register.

**Comment by Chaosmeister** [comment]
Nice that you were able to find it yourself!
I'm unaware of a forum hower there is a gitter-chatroom: https://gitter.im/kanboard/kanboard you could ask your questions there.
