### ISSUE TITLE
Login inpossible while already logged in. 

### ISSUE THREAD

**Issue by Chaosmeister** [fguillot/kanboard#2403]
### Expected behaviour

When I call the root directory of our Kanboard installation while being logged in, I would expect to reach **[url]/kanboard/?controller=app&action=index** or the dashboard

### Actual behaviour

Instead I'm directed to
[url]/kanboard/?controller=auth&action=login

When pressing the _Sign in_ Button, the page just reloads.

### Steps to reproduce

1. Log into Kanboard
2. Remove anything after the last "/" including the "/" from the url - in my case [url]/kanboard
3. The login form appears but I'm unable to login.

### Additional Information

Nearly every url with [url]/kanboard/ works.
Some output an "Internal Error: Action not implemented" like [url]/kanboard/?controller=task.

This is possibly a misconfiguration on our server side.

### Configuration

Application version: 1.0.28
PHP version: 5.3.28
PHP SAPI: cgi-fcgi
OS version: Windows NT 6.2
Database driver: sqlite
Database version: 3.7.7.1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by Chaosmeister** [comment]
This also happens with the latest stable kanboard (1.0.30).

**Comment by seancarson** [comment]
This may help.  

Under KB Settings > Application settings
make sure your Application URL matches your hosting path. In my case I use apache  so my root is /var/www/html/kanboard  so my application URL is https://myurl/kanboard/ .  

second check your apache configuration and make sure your permanent redirect are setup properly. If they are set it should be the same as your Application URL.    

SC

**Comment by Chaosmeister** [comment]
Hi!
our internal url is http://vm-vsissues/kanboard/ which is also set in the application settings.
we're using IIS though.

**Comment by jtourt** [comment]
#2243 - same issue has been reported previously.  Common denominator is IIS.

**Comment by Chaosmeister** [comment]
this does not happen with version 1.0.31 anymore.
also /controller=auth&action=login now correctly redirects to the dashboard :+1:
