### ISSUE TITLE
Publish a plugin in the plugin directory

### ISSUE THREAD

**Issue by xavividal** [fguillot/kanboard#2408]
Hi @fguillot 

The Relationgraph plugin is available for all users and working in the latest kanboard version.

What I need to do to publish this plugin in the plugin directory? 

The URL is: https://github.com/xavividal/kanboard-plugin-relationgraph

Thanks !

**Comment by macman31** [comment]
@xavividal please read the bottom of the plugins page:
"To publish your own plugin on this page, [send a pull-request to this repository](https://github.com/kanboard/website)."

**Comment by xavividal** [comment]
Thanks
