### ISSUE TITLE
Unexpected result at search with "-"

### ISSUE THREAD

**Issue by Vertumnus** [fguillot/kanboard#2416]
### Actual behaviour

We have tasks, which contain a "-" inside the title. If I try to search for one of this, e.g. "TO-123" (which is content of several titles), the search string is ignored and I get all tasks in my result. If I use only a part of it without "-", e.g. 123, then I get the correct result (all tasks with 123 in title).

### Expected behaviour

The search functionality shall consider also the "-". In my example: If I search for TO-123 the result list should show only tasks containing TO-123 in the title.

### Steps to reproduce

1. Go to Board or List view
2. Specify a filter with "-", e.g. TO-123
3. Apply filter

### Configuration

- Kanboard version: 1.0.30
- Database type and version: mysql 5.7.9-log
- PHP version: 5.6.16

**Comment by fguillot** [comment]
Thanks to report this issue, it's now fixed in the development branch.
