### ISSUE TITLE
Internal Error: SQL error  - Heroku

### ISSUE THREAD

**Issue by dancomanlive** [fguillot/kanboard#2419]
### Expected behaviour
 add new task
Tell us what should happen
 new task should be added to project

### Actual behaviour
 pop up error message
Tell us what happens instead
 Internal Error: SQL error

### Steps to reproduce

1. One click deploy to Heroku
2. Create new project
3. Create new task

**Comment by fguillot** [comment]
You should try to deploy agin, this issue have been already fixed. Thanks.

**Comment by dancomanlive** [comment]
Merci beaucoup! [😊]


________________________________
