### ISSUE TITLE
Default Plugin Settings not working

### ISSUE THREAD

**Issue by SDTipps** [fguillot/kanboard#2420]
### Expected behaviour

If I understand the documentation, the default settings should allow me to install plugins either from the command line interface or from the Kanboard when logged in as administrator. 

### Actual behaviour

Right now I'm getting a message saying "Your Kanboard instance is not configured to install plugins from the user interface" or (in terminal) a big red box that says"[LogicException] Kanboard is not configured to install plugins itself"

### Steps to reproduce

Just installed on an Azure instance running Ubuntu 16.04 as a VM

### Config Files

Having checked the default.config.php settings, it appears they differ from those shown in the documentation.

First off, this is missing entirely, so I added it to config.php:
//Enable/disable plugin installation from the user interface:
define('PLUGIN_INSTALLER', true); // Default is true

Second, this is a bit different from the docs, but I assume it doesn't actually affect performance other than the fact that I had to do a CHOWN to make it writable since the installation instructions won't reach this directory:
// Plugins directory
define('PLUGINS_DIR', 'plugins');

The last difference is probably just a matter of syntax, but I figured I'd check and make sure that the standard "data/files" would work here as well:
// Folder for uploaded files
define('FILES_DIR', 'data'.DIRECTORY_SEPARATOR.'files');

### System Configuration

Application version: 1.0.30
PHP version: 7.0.4-7ubuntu2.1
PHP SAPI: apache2handler
OS version: Linux 4.4.0-28-generic
Database driver: sqlite
Database version: 3.11.0
Browser: Mozilla/5.0 (X11; CrOS x86_64 8172.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by fguillot** [comment]
Do you have configured everything like described on this page: https://kanboard.net/documentation/plugin-directory ?

**Comment by SDTipps** [comment]
Yep. Here's the relevant stuff from config.php:

//enable/disable plugin installer
define('PLUGIN_INSTALLER', true);

// Plugins directory
define('PLUGINS_DIR', 'data/plugins');

Which of course means that I've moved plugins back into the data directory and set everything in it to be owned by www-data (chmod is at 755).
I also installed Zip before starting the ticket.

Is there anything relevant I should check in the log?

**Comment by fguillot** [comment]
The Zip PHP extension or the zip command line utility?

**Comment by SDTipps** [comment]
Looks like there was an error installing the extension the first time. I removed it, reinstalled, and everything's working great. Sorry I didn't think of this one myself, and thanks for your time!

**Comment by ekariz** [comment]
for my case i had to #sudo chmod -R 777 /var/www/html/kanboard/plugins and 
seeing 
public static function isConfigured()
    {
        return PLUGIN_INSTALLER && is_writable(PLUGINS_DIR) && extension_loaded('zip');
    }
