### ISSUE TITLE
Typo on french translation : "Votre compte est vérouillé pour 15 minutes"

### ISSUE THREAD

**Issue by Biniou180** [fguillot/kanboard#2445]
I open this ticket as a contributor of Framasoft projects, and particularly Framaboard which is based on Kanboard.

### Expected behaviour

When unsuccessfully login, Kanboard blocks the user, and the message "Votre compte est verrouillé pour 15 minutes" (Account locked for 15 minutes in french) is displayed.

### Actual behaviour

There is a typo in the message:
"Votre compte est **vérouillé** pour 15 minutes" => should be **verrouillé**

![screenshot framaboard](https://framapic.org/G3WX1NDacz6f/Ky0Wigraj3tD.jpg)

### Steps to reproduce

1. Try to login a lot of times (around 10 times) with correct username/captcha, but wrong password

### Configuration

- Kanboard version: 1.0.25 (but typo appears also with 1.0.31)

Cheers!

**Comment by 85pando** [comment]
Would be an easy fix, just create a pull request for this file: https://github.com/fguillot/kanboard/blob/master/app/Locale/fr_FR/translations.php

(Not able to speak french myself.)

**Comment by Biniou180** [comment]
You're right @85pando , I didn't take the time to search for source files. My bad!
Thanks for the link anyway :)

[Pull request created](https://github.com/fguillot/kanboard/pull/2448).

**Comment by 85pando** [comment]
Never mind (-:

**Comment by fguillot** [comment]
PR merged, thanks!
