### ISSUE TITLE
Problem with UI Design -

### ISSUE THREAD

**Issue by sensei412001** [fguillot/kanboard#2454]
### Expected behaviour

Should have the proper interface in login and its pages

### Actual behaviour

no ui design, swimlanes

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

About

    Official website: https://kanboard.net/
    Author: Frédéric Guillot (contributors)
    License: MIT

Configuration

    Application version: 1.0.30
    PHP version: 7.0.7
    PHP SAPI: cgi-fcgi
    OS version: Windows NT 6.1
    Database driver: sqlite
    Database version: 3.8.10.2
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by sensei412001** [comment]
Please see attached

![1](https://cloud.githubusercontent.com/assets/14103169/16647175/8d971282-4460-11e6-86ae-20ffb4b001aa.PNG)

**Comment by volodymyr-kushnir** [comment]
Hey, @sensei412001, I've had similar issues recently. Take a look at this [comment](https://github.com/fguillot/kanboard/issues/2369#issue-161074297) please. I think you can get it to work if you just remove ```fastcgi_param PATH_INFO``` from your nginx configuration.

**Comment by volodymyr-kushnir** [comment]
@sensei412001, can you attach your **c:\php.ini** and **c:\inetpub\wwwroot\kanboard\web.config** please? I'm on Windows 10 with IIS 10 and PHP 7.0.8, but I can't reproduce your problem with default configurations.

**Comment by sensei412001** [comment]
it's working now. i moved the kanboard to Window Server and use php 5 and url rewriter.

thank you volodymyr-kushnir. appreciate it
