### ISSUE TITLE
Getting LDAP Working

### ISSUE THREAD

**Issue by ohlookemus** [fguillot/kanboard#2460]
### Expected behaviour

LDAP should work or have better logging? Mainly I can't get enough debug information to figure out why my LDAP setup is not working.

### Actual behaviour

kanboard_1  | 2016/07/08 21:18:17 [error] 11#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  ldap_search(): Search: Operations error in /var/www/app/app/Core/Ldap/Query.php on line 57" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "POST /?controller=AuthController&action=check HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "kanboard.heylookemus.local"

### Steps to reproduce

1. Running docker kanboard
2. Use below config.php

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: master
PHP version: 7.0.7
PHP SAPI: fpm-fcgi
OS version: Linux 3.10.0-327.18.2.el7.x86_64
Database driver: postgres
Database version: 9.4.8
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

Config.php
`<?php

define('DEBUG', true);

// We choose to use Postgresql instead of Sqlite
define('DB_DRIVER', 'postgres');

// Mysql parameters
define('DB_USERNAME', 'kanboard');
define('DB_PASSWORD', 'kanboard_password');
define('DB_HOSTNAME', 'localhost');
define('DB_NAME', 'kanboard');

define('LDAP_AUTH', true);
define('LDAP_BIND_TYPE', 'user');
// LDAP server hostname
define('LDAP_SERVER', 'ldap://myldap.local');

// LDAP properties
define('LDAP_USER_BASE_DN', 'OU=My Users,OU=My,DC=User,DC=local');
define('LDAP_USER_FILTER', 'uid=%s');

define('ENABLE_URL_REWRITE', true);
define('LOG_DRIVER', 'stderr');`

**Comment by gramakri** [comment]
FWIW, We use LDAP and in the Cloudron.io app. You can see how we configure it here - https://github.com/cloudron-io/kanboard-app/blob/master/config.php.template

**Comment by fguillot** [comment]
Use the log driver "file", and watch the application logs with `docker exec -ti my-container tail -f /var/www/app/data/debug.log`.

PHP-FPM doesn't seems to output to stderr the application logs, only the PHP errors are outputted correctly.

**Comment by ohlookemus** [comment]
Looks like that helped once I saw the debug log. Thanks!
