### ISSUE TITLE
Who can use my Kanboard?

### ISSUE THREAD

**Issue by primantok** [fguillot/kanboard#2465]
Hello,

I am new here and I am sorry if this question has been asked before.

When I install Kanboard, who can use it?
- me & my team only, where my team must ask me to get permission tu use this software
- everyone who knows my Kanbord site can use use (they can register as new user, similar to Trello)

Thanks.

**Comment by andyhoyland** [comment]
Hi there.

By default the setup allows you to assign access and share that with the rest of your team. So your permission is required.

There is a plugin available to allow self registration.

https://kanboard.net/plugin/registration

**Comment by primantok** [comment]
Thank you @andyhoyland for your help.

Your recommended plugin seems what I'm looking for. I want my team use Kanboard with self registration.
