### ISSUE TITLE
Issues with task start date/time

### ISSUE THREAD

**Issue by entwisi** [fguillot/kanboard#2467]
### Expected behaviour

Tell us what should happen
using date picker to seletc a date gives no errors on saving task

### Actual behaviour

Tell us what happens instead
Selecting any date other than today I get "Invalid date" error on saving task

### Steps to reproduce

1. edit or create a new task
2. click in start date field and select a date in future from the date picker
3.click done 
4. click save on task

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

Application version: 1.0.31
PHP version: 5.6.14
PHP SAPI: apache2handler
OS version: Linux 3.10.0-229.20.1.el7.x86_64
Database driver: mysql
Database version: 10.0.17-MariaDB-log
Browser: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
![dateissue](https://cloud.githubusercontent.com/assets/5046093/16757766/f0451f5c-4805-11e6-9289-73cbac71ca37.png)

**Comment by NinjaPewPew** [comment]
I had this issue to. Go to application settings and set the date format accordingly and it will work again without error.

**Comment by entwisi** [comment]
Thanks, as said, works fine now. Will close the issue.
