### ISSUE TITLE
Ignorecase for SearchKeys

### ISSUE THREAD

**Issue by toepi** [fguillot/kanboard#2469]
### Expected behaviour

Key with wrong case (e.g. starts with capital letter) should found same as with right case (all lowercase). Nice to have ignore case for values also (allow searches with same result: 'category:test' and 'category:Test')

### Actual behaviour

Found all task if key doesn't match case, e.g. search after 'Color:orange' founds all Task and 'color:orange' found expected tasks.

### Steps to reproduce

1. Type 'Color:orange' or 'Category:Work' into search

### Configuration

- Kanboard version: 1.0.30

More not available, because no admin over ldap :(.

**Comment by fguillot** [comment]
In the development branch, the search attribute ignore the case now. Some filters have to modified to ignore the case for the value.

**Comment by toepi** [comment]
Great, works like expected now.
