### ISSUE TITLE
Jabber Plugin

### ISSUE THREAD

**Issue by stf675** [fguillot/kanboard#2479]
### Expected behaviour

Use private installation of Openfire (XMPP clone)
Since it is internal only, we are using self signed certificate

### Actual behaviour

On the 1st use, I am getting

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in <my root>\kanboard\plugins\Jabber\vendor\fabiang\xmpp\src\Stream\SocketClient.php on line 192

### Steps to reproduce

1. Create /Update task with Jabber as notification channel

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

running on 4 month old XAMPP
    Application version: 1.0.31
    PHP version: 5.6.15
    PHP SAPI: apache2handler
    OS version: Windows NT 6.1
    Database driver: sqlite
    Database version: 3.8.10.2
    Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

So is there config settings/option to disable SSL validation?

**Comment by fguillot** [comment]
The upstream XMPP library have to be patched, see https://github.com/fabiang/xmpp/issues/19

**Comment by stf675** [comment]
great, that fixed it.

**Comment by kierun** [comment]
I appear to have hit this bug as well when using the (stable) docker container. Would that make any difference?

**Comment by fguillot** [comment]
@kierun that's nothing to do with Docker, the library that handle the XMPP protocol do not support self-signed certificates. See the link posted above.

**Comment by kierun** [comment]
AH! I did not notice that it was still open. The "closed" tags are for related issues.  My bad. Apologies.
