### ISSUE TITLE
Exporting tasks: csv data is followed by warnings and the html page!

### ISSUE THREAD

**Issue by gene-pavlovsky** [fguillot/kanboard#2501]
I've just tried to export all projects' tasks, a .csv file was successfully saved, it contains expected header comment and task data as csv, but after the last task there are around 10 identical warnings
```html
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at C:\project\www\kanboard\app\Core\Csv.php:171) in <b>C:\project\www\kanboard\app\Core\Http\Response.php</b> on line <b>210</b><br />
```
The warnings are followed by an html page, which is basically the `Tasks exportation for "PROJECT_NAME"` page.

PS. Is there a way to export entire project's data in a form that could be imported into a fresh install of Kanboard on another machine? E.g. I'm working on a project for a client and track it using Kanboard on my local machine. After I'm done I give the client the source code (with the git repository) and would also like to give him a complete dump of Kanboard task data, so that they would be able to install Kanboard and import the data and review the tasks.

**Comment by fguillot** [comment]
What version are you using? this issue have already been fixed in 1.0.31

**Comment by gene-pavlovsky** [comment]
1.0.30. Didn't see that is 1.0.31 already out. Will upgrade and report back.

**Comment by gene-pavlovsky** [comment]
Ok, in 1.0.31 it's fixed indeed.
