### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by 85pando** [fguillot/kanboard#262]
Categories are nice, but you can only have one category per item. Multiple tags could be added to one task enabling combinations like "important" and "ui"  or just anything...

**Comment by filipesaraiva** [comment]
Add multiple categories or tags would be very usual to Kanboard. +1.

**Comment by oparoz** [comment]
Call them categories or tasks, but more than one is needed, especially when linking projects with systems like Github.

**Comment by ashbike** [comment]
May be we can differentiate in this way:

* Category : Just the way it is. System defined values. One can only select from what is available.
* Tags/Labels : User defined. Somewhat Free form. Multiple values.

**Comment by mtruijen** [comment]
This discussion is really about being able to categorize or classify.
Tag and category in this discussion are one and the same thing.
I don't think it helps the phylosofy that is behind kanboard (simplicity) if tags are introduced. My recommendation is that we expand on categories. A card can be tagged with one or more categories.

**Comment by abouquet** [comment]
+1 !

**Comment by binitprads** [comment]
+1

**Comment by ptman** [comment]
what's the relation of this to #646 ?

**Comment by 85pando** [comment]
In my opinion this would be a dupllicate, but as there is some implementation already present and the discussion seems more lively, i'd rather close #262.

**Comment by fguillot** [comment]
There are many ways to implement tags, I opened a new issue concerning the implementation in the user interface #2331

**Comment by fguillot** [comment]
Tags are now available in the development branch.
