### ISSUE TITLE
[feature request] Synthèse de progression / progression report

### ISSUE THREAD

**Issue by bizulk** [fguillot/kanboard#29]
English traduction :
The board state is a good snapshot of the project current state.
But very often we need to have an overview of the project progress, to see if some task need more people to achieve, or if the project is more complicated as there are a lot of new tasks created.
The Idea is to export a CSV file with all board changes beetween two dates.
* Record board states : we ask to record the current state using à button (date is recorded).
* Make report : We ask to make and export a report py pushing another button, the CVS file format would be :
"Date Created" "Task Name" "Column before" "Column now"

Rows are ordered by "date creation" : from oldest to newest.
Other filters are to be done with excel/libreOffice.

Others tips :
Record board states : only one record may exist. A save overwrite existing record. This avoids to manage a record list.
Task list : deleted task appears in the list (Column now = deleted).

French  :
L'état du tableau constitue un bon snapshot de l'état en cours du projet.
Ca serait bien également de pouvoir synthétiser un rapport d'avancement.
On pourrait soit historiser toutes les actions et ensuite demander un historique entre deux dates. Mais ça peut-être couteux en terme de place.
Soit on gère manuellement l'historique, en demandant via un bouton l'enregistrement de l'état en cours, et par un autre bouton de générer le rapport. Le rapport listerait toutes les tâches avec la différence d'état, les nouvelles tâches, les tâches supprimées. La différence serait indiqué entre la date du snapshot (et d'un commentaire) et la date de la demande.
Cela exporté dans un format type CVS.
Dans une partie admin on gèrerait les snapshot du tableau (effacer, voir le tableau dans cet état, etc...)

**Comment by fguillot** [comment]
In the current development branch the task transitions are recorded in the database, you can export this data in CSV.

Basically you got:

- Task id
- Task title
- Source column
- Destination column
- Executer, the person that move the task
- Date
- Time spent in the origin column

It's also available in the task view. I think that fits your needs.
