### ISSUE TITLE
Generic module, ready to be integrated into other projects

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#296]
I keep pointing Project Management software developers to this project for potential integration, but I think it would make things easier if some components (GUI+API) could be bundled in an independent module which can easily be plugged into another project, similar to what's already available for Gantt charts per example.

Here is one example of what I'm talking about:
http://dhtmlx.com/docs/products/dhtmlxGantt/

>Initialize a Gantt chart on a page using JavaScript API and load data from server in XML or JSON format. You can also generate data for the Gantt chart with the client-side API.
>dhtmlxGantt provides a simple integration with jQuery and ready-to-use server-side connectors (now connectors for PHP and Java are available, ASP.NET integration is on the way).

**Comment by fguillot** [comment]
Gantt chart is now available in the dev version.

**Comment by oparoz** [comment]
That's great news, but this is not what this ticket is about. I was asking about packaging the frontend (bower?) so that the board itself can be used within different projects.
