### ISSUE TITLE
Include author of task move in notification mail

### ISSUE THREAD

**Issue by eikehein** [fguillot/kanboard#297]
It would be really great if the notification mails sent when a task is moved would include who moved the task. Often I find myself wanting to ask a follow-up question or congratulate someone or so, but can't see who did it.

**Comment by fguillot** [comment]
It's now available in the development branch.

The author will be displayed in the From field, by example "Bob via Kanboard".

**Comment by eikehein** [comment]
Brilliant, thanks!
