### ISSUE TITLE
opacity 0.2 vs display = none for "filter"

### ISSUE THREAD

**Issue by borgrat** [fguillot/kanboard#298]
May be configurable by Project oder mybe better by user. If you have a lot of Tasks the overview would be better ;-)

in Version 1.0.8 in the function at line 186 i wrote:
filtered: "item.style.display = "none";"  
or nonfiltered: "item.style.display = "block";" 

    // Apply user or date filter (change tasks opacity)
    function filter_apply()
    {
        var selectedUserId = $("#form-user_id").val();
        var selectedCategoryId = $("#form-category_id").val();
        var filterDueDate = $("#filter-due-date").hasClass("filter-on");

        $("[data-task-id]").each(function(index, item) {

            var ownerId = item.getAttribute("data-owner-id");
            var dueDate = item.getAttribute("data-due-date");
            var categoryId = item.getAttribute("data-category-id");

            if (ownerId != selectedUserId && selectedUserId != -1) {
                item.style.opacity = "0.2";
				item.style.display = "none";
            }
            else {
                item.style.opacity = "1.0";
				item.style.display = "block";
            }

            if (filterDueDate && (dueDate == "" || dueDate == "0")) {
                item.style.opacity = "0.2";
				item.style.display = "none";
            }

            if (categoryId != selectedCategoryId && selectedCategoryId != -1) {
                item.style.opacity = "0.2";
				item.style.display = "none";
            }
        });
    }

**Comment by fguillot** [comment]
The board handle the display at none now.
