### ISSUE TITLE
Color picker for tasks

### ISSUE THREAD

**Issue by essembeh** [fguillot/kanboard#3]
The ticket color could be editable with a simple color picker.
It would be easier than the combobox.
It would also be useful if the color could be changed directly in the Project view (with a small color picker).

**Comment by nekohayo** [comment]
@poikilotherm any progress on that patch of yours? Would be great to have a color picker palette widget. Lately the combobx list has grown to way more colors and they're all textual, and not sorted logically, which makes the thing hard to use consistently.
