### ISSUE TITLE
Moving tasks between projects

### ISSUE THREAD

**Issue by frankdlt** [fguillot/kanboard#306]
Hi. When i move a task to another project it always shows up on the first column. its there a way to change that. ex: pick which column you want it to go to.

Thanks

**Comment by dlocke** [comment]
Until this improvement is implemented, can this behavior be documented?  This is the only place I've found that describes what will happen to the moved task.

**Comment by fguillot** [comment]
It's now possible with the development branch, see http://kanboard.net/documentation/duplicate-move-tasks for more information.
