### ISSUE TITLE
Milestones, tasks lists or sub-projects to organise tasks

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#317]
### The problem
Any project with more than a few issues is going to run into a clutter problem at some point, unless Kanboard is only used to manage tasks stored elsewhere.
Let's say you have something like 30 US, tasks, FR, ideas, etc. You can organise them into categories and grey out the ones you're not interested in at the moment, but that's still 30 tasks on a board at the beginning of the project.
You can also split the tasks into 4-5 projects, but you're going to end up with a long list of projects.

### Solution
Introduce
* milestones or tasks-lists or
* sub-projects or
* components
* all of the above

**Comment by fguillot** [comment]
We swimlanes now...
