### ISSUE TITLE
Custom fields on the summary page

### ISSUE THREAD

**Issue by hicter00** [fguillot/kanboard#323]
It would be good to have the ability to add custom fields for each project.  You could create a similar panel like the one used for categories to enter them.  Users could create their own fields (for whatever purposes they want to track) to a max of x.  Each field could be given a type - text, date, list (with the options provided comma separated (like the default values for the columns).  A use of this might allow a user to create linked dependencies between tasks (ie., Predecessor=#4 or Next Action=#7" or it might allow them to track the end date of a process vs. the date for each column.

**Comment by fguillot** [comment]
Custom fields are available through the plugin api (not the user interface). Anybody can create plugins that expose new fields in the user interface.
