### ISSUE TITLE
Recurring Tasks

### ISSUE THREAD

**Issue by aaronrobertson** [fguillot/kanboard#340]
Could you add a feature to add new tasks to a project on a specific schedule?

**Comment by majewsky** [comment]
This would interest me as well. I would like to use the board for recurring household tasks, such as:
* vacuum living room every week
* clean bath every three weeks

**Comment by shimza** [comment]
Me too. Recurring tasks and location would be ideal

Cheers,

Shimon Friedman 
Mob: 0403067613

**Comment by fguillot** [comment]
@majewsky did you already forgot to vacuum the living room? :)

**Comment by hamzasheikh** [comment]
Another vote for this feature. I'm OK with creating n number of additional tasks when the task is first created. I can then edit their due dates to manage their order.

**Comment by David-Norris** [comment]
Proposed concept: #847

**Comment by fguillot** [comment]
I merged/improved the pull-request of @David-Norris in master.

The idea behind is described here: https://github.com/fguillot/kanboard/blob/master/docs/recurring-tasks.markdown

We will see later if that need some modifications or improvements.
