### ISSUE TITLE
Duplicate all tasks in board when duplicating board?

### ISSUE THREAD

**Issue by selenium9k** [fguillot/kanboard#344]
[Feature Request]
It would be awesome if, when duplicating a project, it is possible to have an option to duplicate all or some tasks of the source project to the new project as well. 

We use Kanboard to track web development jobs and there are some tasks that occur in every project.

**Comment by fguillot** [comment]
It's possible since January.

**Comment by selenium9k** [comment]
Thank you! I actually forgot about this request and we updated to the latest version a while ago and I saw it had been implemented. 
For what we use it for, Kanboard is now just about PERFECT!!
