### ISSUE TITLE
[bug] Persistant connection fails to persist

### ISSUE THREAD

**Issue by theonlydoo** [fguillot/kanboard#346]
Hello, 
I noticed that even if I ticked the "autoconnect" box on the login screen, I was disconnected after a while (about 1/2 work day), it's quite annoying since I may be disconnected right after validating a new comment on an existing task.

**Comment by fguillot** [comment]
Should be fixed now?

**Comment by theonlydoo** [comment]
Indeed :)
:+1: 
welldone !

**Comment by mluepkes** [comment]
Hooray :+1:  Please remember to close the issue :smile:
