### ISSUE TITLE
Control task notification

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#351]
I would like to control the task creation email notification so that, no email notification is sent to anyone when a task is created, but only when a task is assigned to an individual, that individual will get the email notification. 

Also whenever someone updates a task, the task creator will get an email notification of that change. 

Could you show me where to control this?

**Comment by jtrebschuh** [comment]
Me too.
Everybody recieves notification for tasks where they are not involved.

**Comment by felipestanham** [comment]
Everyone at work has turned off notifications because of this missing feature!

Please include these feature

**Comment by BlueTeck** [comment]
It should be a little bit like github:
- new table participants with task_id and user_id
- if a user changes something on a task (rename, move etc) the user and taskid should be stored in this table
- if a user is assigned, his user_id is also added
- notifications should be sent to matching users is this table
- in the frontend, there should be a button to remove and add yourself as participant

Agree with it?

**Comment by Guybrush333** [comment]
+1

**Comment by valessiobrito** [comment]
:+1:

**Comment by fguillot** [comment]
It's now implemented in the development branch, I choose to adopt a simple method but there are several options available:

- Receive notifications for all tasks (same as before)
- Only for tasks created by me
- Only for tasks assigned to me
- Only for tasks assigned to me and tasks created by myself (the new default)

And it's also possible to filter by projects.

Note: it's under testing at the moment, if you spot any issue let me know.
