### ISSUE TITLE
Issue at first connection

### ISSUE THREAD

**Issue by zemadmat** [fguillot/kanboard#354]
Hi,
i'm using zwamp on windows and have try to install Kanboard after having enabled both mbstring and pdo_sqlite.
I then try to connect to http://127.0.0.1/kanboard and i receive this error message:
 Fatal error: require(): Cannot redeclare class core\loader in Z:\web\kanboard\app\common.php on line 22

how can i avoid this ?

Cheers

**Comment by fguillot** [comment]
This ticket is too old, the mentioned code doesn't exists anymore, I close it.

Try to install the last version from the zip file, open a new issue if there is a problem.
