### ISSUE TITLE
Email automated action

### ISSUE THREAD

**Issue by hicter00** [fguillot/kanboard#361]
Since you have email already enabled on the system, is it possible to create an automated action that when a task is moved into a particular column or is closed, that you can send an email.  The text of the email to be provided as part of the action (could be dependant on the column etc).  An example of this is, we completed development and SIT testing, but before we can move into UAT testing, we need to ensure a specific form is filled in.  So, when we move task into UAT column we can email (someone - either the action owner, or a specific email) with text that we provide.

**Comment by fguillot** [comment]
With the current development version, a new automatic action allow you can send a task by email when a task is moved to another column or closed.

**Comment by ornic** [comment]
Is it possible to send email to task owner? I can't find this option. Only user list or Unassigned.
(gitcloned project several hours ago)
