### ISSUE TITLE
Cite things (commens / description / ...)

### ISSUE THREAD

**Issue by poikilotherm** [fguillot/kanboard#365]
One thing I always miss on editing GitHub Issues or Comments: there is no easy way to cite one's comment. 

I would like to implement a cite-function within the UI, maybe based on jQuery. That would not only allow to cite a complete comment / ..., but marked parts of it, too.

**Comment by fguillot** [comment]
To keep Kanboard simple, I won't implement this feature. You can still use the Markdown syntax to cite someone.
