### ISSUE TITLE
Markdown Toolbar

### ISSUE THREAD

**Issue by poikilotherm** [fguillot/kanboard#367]
Many people are not that familiar with Markdown. This may be a cause of frustration to new or non-IT users. A little toolbar above the textareas may be of great help here.

(As always, willing to actually do stuff...)

**Comment by fguillot** [comment]
Someone has developed a plugin for that: http://kanboard.net/plugin/wysiwyg

**Comment by OWENCRUZ** [comment]
Hi Guys, I'm having an issue on the markdown toolbar. @fguillot , looks like this one is no longer available http://kanboard.net/plugin/wysiwyg

I'm not sure if it's just my settings, but in I don't have a markdown toolbar on my comment area. See screenshot http://prntscr.com/bllmoq

But it's funny that the toolbar shows up when editing a comment, http://prntscr.com/blln2k . Isn't it supposed to be available when adding new comment?
