### ISSUE TITLE
champ de recherche dans «Afficher un autre projet»

### ISSUE THREAD

**Issue by phardouin** [fguillot/kanboard#372]
Bonjour,

étant donné mon anglais désastreux…
juste une petite remarque pour signaler que tout semble fonctionner nickel sous FirefoxOS 1.3 (sur Open C ZTE) et Firefox comme navigateur.

Un petit point embêtant : lorsqu'on clique (avec le doigt) sur «Afficher un autre projet» cela affiche par dessus le clavier virtuel car c'est le champ de recherche qui est activé par défaut. Cela serait plus pratique si ce champ de recherche ne provoquait pas l'affichage automatique du clavier virtuel.

à bientôt,

NB : superbe application soit dit en passant :+1:

**Comment by fguillot** [comment]
@phardouin cela vient de l'autofocus qui déclenche le clavier virtuel automatiquement sur firefox mobile. Pour le moment je peux pas changer ce comportement, je verrais par la suite sur comment améliorer la version mobile.
