### ISSUE TITLE
Display my tasks (globally, not by project)

### ISSUE THREAD

**Issue by porelli** [fguillot/kanboard#381]
An option to see all tasks assigned to an user would be really useful, especially with a kanboard installation containing many projects.
It will be awesome if the summary will be shown like a project with columns corresponding to assigned assigned task.

PROJECT A
Backlog -> no tasks
Sprint -> no tasks
WIP -> fix bgp routing (john)
Feedback -> no tasks
Done -> no tasks

PROJECT B
Backlog -> prepare backup strategy (john)
Sprint -> no tasks
WIP -> no tasks
Feedback -> new nginx rules (john)
Done -> no tasks

PROJECT C
Backlog -> read and validate wiki pages (john)
Sprint -> no tasks
WIP -> no tasks
Feedback -> check rf parameters (john)
Done -> no tasks
done -> no tasks

EXPECTED SUMMARY (as john user)
Backlog -> prepare backup strategy (project b), read and validate wiki pages (project c)
WIP -> fix bgp routing (project a)
Feedback ->  new nginx rules (project b), check rf parameters (project c)

**Comment by fguillot** [comment]
Duplicate with #426
