### ISSUE TITLE
Adding Mulitple Tasks

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#392]
Hi 

It would be great if we can have an option to add multiple tasks in a go. Please find the attached screenshot. We will have another list icon apart from add button on the board. Once you click on the list icon you can add the tasks line by line. Once you are done you can click save and all the tasks will be available on the board.  
![kandboard](https://cloud.githubusercontent.com/assets/7837070/5007903/d1b974f6-6a7c-11e4-95b3-2abb464c19a6.png)

**Comment by fguillot** [comment]
This feature is now available in the development branch. Click on the column title and choose "create tasks in bulk".
