### ISSUE TITLE
Break more gracefully in vertical mobile screens?

### ISSUE THREAD

**Issue by poVoq** [fguillot/kanboard#397]
The Kanboard already works surprisingly well in landscape mode on my phone, but when I turn the screen vertically it breaks quite horribly with lots of text overlapping etc. would be nice if it was at least somewhat useable in vertical mode also (by stacking things below instead of on top).

**Comment by fguillot** [comment]
I improved the mobile layout in the current development version. The application is more "responsive". It's not perfect but I can at least navigate without any problem with my smartphone.
