### ISSUE TITLE
Coloured Cards

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#404]
Hi

Instead of using colorful cards, is it good to have white cards and color only on sides of the cards. Please find the attached screenshot.

![1](https://cloud.githubusercontent.com/assets/7837070/5082129/cedbca80-6f00-11e4-974a-7aef8408aad3.png)

**Comment by daddykom** [comment]
In Definition > Application configuration > user defined stylesheet
insert this:

td.color-yellow, div.color-yellow {
    border-color: rgb(223, 227, 45);
    border-left-width: 15px;
    background-color: white;
}

td.color-blue, div.color-blue {
    border-color: rgb(168, 207, 255);
    border-left-width: 15px;
    background-color: white;
}
td.color-green, div.color-green {
    border-color: rgb(74, 227, 113);
    border-left-width: 15px;
    background-color: white;
}
td.color-purple, div.color-purple {
    border-color: rgb(205, 133, 254);
    border-left-width: 15px;
    background-color: white;
}
td.color-red, div.color-red {
    border-color: rgb(255, 151, 151);
    border-left-width: 15px;
    background-color: white;
}
td.color-orange, div.color-orange {
    border-color: rgb(255, 172, 98);
    border-left-width: 15px;
    background-color: white;
}
td.color-grey, div.color-grey {
    border-color: rgb(204, 204, 204);
    border-left-width: 15px;
    background-color: white;
}

**Comment by lathan** [comment]
Where is this?
"Definition > Application configuration > user defined stylesheet"

**Comment by daddykom** [comment]
Have a nice day..

Charley

__________________________________________________

Email verschlüsseln? Hier wird geholfen: http://t3n.de/news/mails-verschlusseln-eigentlich-482381/

collins.ch
flühbergweg 2B
ch-4107 ettingen

t: 061 722 01 10

http://www.collins.ch

**Comment by radicaledward68** [comment]
I don't know if this thread is dead or not - but for those of you running Kanboard on a host that supports MySQL v > 5.0.3 - the 255 character limitation for the CSS field can increased with a mysql command or by using a web interface like PHPMyAdmin.  I increased mine to 5,000 and was able to edit the CSS very easily. 

Blue Skies.
