### ISSUE TITLE
To have the possibility to transform private project into normal project and add some people to the project

### ISSUE THREAD

**Issue by riantsoa** [fguillot/kanboard#417]
I cant add people in private project, and i dont have the option to turn this into normal project.

**Comment by oliviermaridat** [comment]
The possibility to turn a private project to a normal could be more than useful.
It is common to create a private project by mistake, to create numerous of tasks in it, and then to be stuck when it is time to add users in it "frack, this is a private project!".

**Comment by fguillot** [comment]
It's now possible in the current development version. However, only admins can convert a private project to a normal project. Just uncheck the box "Private project" on the project edit page.

**Comment by oliviermaridat** [comment]
Great! Thanks!

**Comment by nerdoc** [comment]
Hm. I think this should not only be able to do by Admins. I don't want to make some people in my group administrators of the whole kanban, but they are like "managers" who should be able to start projects.
Why ist it not possible to make something like a permission to create public projects that can be assigned to users (or roles)?
I think it should be easily possible for admins to give a person the ability to create projects, like "managers" that could start their own ones.
In this case you don't need to always bother the "system" admin to start a new project.

**Comment by fguillot** [comment]
At the moment, the permission system is very simple. I will see how to add new role "manager" for the next versions, but since the beginning I try to keep Kanboard very simple.
