### ISSUE TITLE
Apply actions when commenting a task

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#423]
Using Kanboard, I noticed that when I comment a task, I oftently need to move this task just before, or just after. Or I need to attach a file, and I describe this file in a comment. Or I change the assignee, and I explain why in the comment.

That is why I would like to propose, to add the possibility to apply actions (delete / close / move the task, update category, update assignee, join a document, change color, change date, change estimation, ...) when adding a comment to a task. A summary of actions applied on the task may then be displayed at the end of the comment as depicted below (this information is already available in the activity feed, though, so it doesn't seem necessary).
![comment](https://cloud.githubusercontent.com/assets/953989/5165422/80fbbfee-73e4-11e4-9a4e-26a5032a1823.png)

In fine, almost all actions that can be selected at the creation of a task, may be useful when writing a comment. For clarity, it may be useful to show/hide this "actions sidebar".
![add-comment](https://cloud.githubusercontent.com/assets/953989/5165579/ac410ae0-73e6-11e4-86c9-50fff21e78a0.png)

Of course, it has to be refined, but it may be a usability gain for Kanboard.

**Comment by myrdd** [comment]
I like the idea that any change to a task can be displayed. However, IMHO it's not necessary to be able to edit the task's attributes *when commenting*. It would be OK for me if those task-altering fields were *hidden* by default.

> Or I need to join a document, and I describe this document in a comment.

What do you mean by a *document* and by *joining*?

**Comment by oliviermaridat** [comment]
"Or I need to attach a file, and I describe this file in a comment."
Is it better?

**Comment by myrdd** [comment]
Ah! So by »to join a document« you meant »to attach a file«`, no? Yes, imho that's *way* more understandable.

**Comment by oliviermaridat** [comment]
Ok thanks! (In French there is this notion of "pièce-jointe" for "attachment file", so "join" seemed a good candidate ;-D)

**Comment by gmichard** [comment]
👍

**Comment by fguillot** [comment]
Sorry, I'm closing this FR, try to keep it very simple for now.
