### ISSUE TITLE
[improvement] when there is only one board, hide dropdown menu on 'dashboard'

### ISSUE THREAD

**Issue by lathan** [fguillot/kanboard#427]
There is a "Display another project" dropdown menu on "boards" and "dashboard". When there is only one project, the menu is hidden on boards, but not on dashboard.

**Comment by fguillot** [comment]
It's hidden on the board because there is no other boards to display. It's not hidden on the dashboard because you can go to the board through the dropdown.

**Comment by lathan** [comment]
ok. It seemed inconsistent and I assumed it wasn't intentional.
