### ISSUE TITLE
[UX] clicking 'cancel' on popover reloads page

### ISSUE THREAD

**Issue by lathan** [fguillot/kanboard#431]
In a popover like the one below, if I click the dark background, the popover gets hidden. But if I click "cancel" the entire page reloads. "Cancel" should not reload, since it is already possible.

![2014-11-28-155638_1520x351_scrot](https://cloud.githubusercontent.com/assets/1893345/5228761/57dad628-7717-11e4-8cad-de9fb0e32ab0.png)

**Comment by fguillot** [comment]
It's now changed in master.
