### ISSUE TITLE
Shortcut Key to Save

### ISSUE THREAD

**Issue by jeffshieldsdev** [fguillot/kanboard#434]
Would it be possible to add a shortcut key to the Save button for Descriptions, Comments, etc. for when typing in the multiline text box?  Gmail has Ctrl+Enter and Mediawiki has Alt+Shift+S .  For me, this would improve efficiency.  Thank you.

**Comment by fguillot** [comment]
There some keyboard shortcuts implemented in the development version. You can save a form with Ctrl+Enter or Command+Enter (with OS X).
