### ISSUE TITLE
[FR] Per project or per user language setting

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#451]
Let's say you work both with local businesses in French and have international business partners with whom you communicate in English.
Having just one global language setting doesn't cut it, so you would need to install Kanboard twice.
Setting one language per project would be ideal as it would make sure that both the software and the content are in the same language, but would it be a problem to switch language on the fly, when switching project?
The alternative would be a per user setting.

**Comment by fguillot** [comment]
With the last development version, users can choose their own timezone and language.
