### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by ameeriqbal** [fguillot/kanboard#453]
Hi 

Currently the Analytics is limited to each project only. I would like to suggest a split in user roles, we will be having three roles - user, manager and admin. So it will be easy to implement a report structure that will help the admin to get an overview of all the projects in an organization. Manager will be having the current reportings structure, that is he can view the analytics on each projects. The normal user will not be having any reporting.

**Comment by fguillot** [comment]
There is now a new role "project admins", global reports can be added later easily.
