### ISSUE TITLE
API for User Tasks

### ISSUE THREAD

**Issue by hussam789** [fguillot/kanboard#455]
Hi, 
I'm trying to implement some Android Client App for KanBoard, and i'm looking at the API documentation, how i can log-in through the API as a user and to get User's Tasks, User's Projects for the specific user i'm logged in with.  is there a Log-in API call with User/Password and then every API Call will be related to this user?

**Comment by fguillot** [comment]
@hussam789 probably for the next version, I want to test master and release a new stable version before making any important changes.

**Comment by shimza** [comment]
Any news on user-authenticated access via the API?

**Comment by fguillot** [comment]
I started to implement the user api access in the development branch. At the moment, it's pretty basic, more procedures will be available later.

- Differences between the application and user api: https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#user-and-application-api
- List of methods available through the user api: https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#authorized-user-api-procedures

It's a work in progress...

**Comment by BlueTeck** [comment]
Thank you very much, i will play around with it alter :)
