### ISSUE TITLE
new PHP version enforcement?

### ISSUE THREAD

**Issue by scootersmk** [fguillot/kanboard#456]
I was successfully using kanboard version 1.0.9 on a vanilla Centos 6 server(w/ EPEL), despite centos 6 only having PHP 5.3.3. But a fresh install of 1.0.10 fails due to an error complaining I don't have the minimum PHP version. If this is intended, I recommend you change the installation instructions for centos 6 to note this.

**Comment by fguillot** [comment]
I reverted back the changes, so the next version of Kanboard will be compatible with PHP 5.3.3 (Centos 6.x and Debian 6).
