### ISSUE TITLE
Fast closing button

### ISSUE THREAD

**Issue by lmbss** [fguillot/kanboard#459]
Hello I would suggest that incluise a button to quickly close a task, for example the description of side button on the board put a cross to thereby close a task quickly

grateful for his work and his staff as looking something like this a long time

**Comment by fguillot** [comment]
It's done in the development version with a dropdown menu on the task.

**Comment by ashbike** [comment]
:+1:  I was not able to find it at first glance. Actually, I saw this menu for the first time. It's handy. Just to help others:
![image](https://cloud.githubusercontent.com/assets/7455931/5995984/43cf308e-aac5-11e4-8772-92cb6171f835.png)
