### ISSUE TITLE
[API] result getMembers

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#461]
I think the result of the call getMembers is not the best.

-> Result on success: Key/value pair of user_id and username

```json
{
    "jsonrpc": "2.0",
    "id": 1944388643,
    "result": {
        "1": "user1",
        "2": "user2",
        "3": "user3"
    }
}
```
in my opinion this would be better:

```json
{
    "jsonrpc": "2.0",
    "id": 1944388643,
    "result": [{
        "id": "1",
        "name": "user1"
        },
        {
        "id": "2",
        "name": "user2"
        }
}
```

What do you think?

**Comment by fguillot** [comment]
Why?

**Comment by BlueTeck** [comment]
I think its clearer ;)
And if you want enhance it, for example add a project owner flag, it isn't possible at the moment.
