### ISSUE TITLE
Collecting new automatic action

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#463]
Hi,
i think the "automatic actions" are really nice, but i have some ideas for more action. 

actual actions:
![actions](https://cloud.githubusercontent.com/assets/1961634/5393366/5c677aec-8131-11e4-9cef-994b447d7963.png)

Ideas:
- assign color to a column
- change color if due date reached

Waiting for more ideas ;)

**Comment by mluepkes** [comment]
This one is a little more tricky: repeating tasks

Every x days/weeks/months add task y
which could be modified/expanded with
...to column z
...with due date = current date + x
...to swimlane a
etc

**Comment by ZegalPL** [comment]
repeating tasks would be great thing to have

**Comment by oparoz** [comment]
[Swimlanes automatic actions](https://github.com/fguillot/kanboard/issues/633)

**Comment by dbtek** [comment]
Moving tasks between columns with Github commits would be nice to have.
For example:
Moving task from **ready** to **work in progress** with a commit.
