### ISSUE TITLE
[FR] Stack cards on demand

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#465]
Would be nice if we could stack all the cards belonging to the same column, showing only the task name.
Would make for less tall columns and could also be useful if swimlanes are ever implemented.

**Comment by oparoz** [comment]
With swimlanes this is even more crucial. Dragging a task from the default swimlane to one which is a couple of rows belows is a pain as we have to scroll down while holding it or do it in at least 2 steps.

**Comment by fguillot** [comment]
It's now available in master. For each board, you can collapse/expand tasks.

**Comment by oparoz** [comment]
Good job! :+1:

**Comment by oparoz** [comment]
Would it be possible to get a keyboard shortcut like "e" ?

**Comment by ashbike** [comment]
Shortcut is already there. 's'

**Comment by oparoz** [comment]
Excellent, thanks!
