### ISSUE TITLE
Owncloud

### ISSUE THREAD

**Issue by mrbreil** [fguillot/kanboard#466]
Hello, i want to integrate kanboard in to my owncloud Website. I used the owncloud external site APP. I want to See the owncloud header. But if i open the kanboard site in owncloud i getting a blank page. Do i habe to change some security settings in kanboard?

Sorry for my Bad english.

**Comment by euneuber** [comment]
Tried to integrate kanboard (today's master) in owncloud 8.0.0 and I get the "white page of death"..
I enabled debugging in PHP.ini but I get no message.
Can you please give a hint where to look?

**Comment by fguillot** [comment]
I added a new config option in the development branch:

You can disable the "X-Frame-Options: DENY" HTTP header like that (in your `config.php`):

```php
define('ENABLE_XFRAME', false);
```
This why you got a blank page and no error message, it's a security header used by web browsers to prevent this behavior. Just disable that with the option parameter, that should work with Owncloud.
