### ISSUE TITLE
Allow admin to select layout of Dashboard - choose to keep Activity stream at bottom of Dashboard to allow sufficient width "My projects", "My tasks", "My substasks" (ref v 1 0 10, rel Dec 6th, 14)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#471]
* Great job, fguillot - KB is great.
* Appreciated that subtasks were included in dashboard in latest release.

However;
we operate with "long titles" for the lanes, but they are < 50 characters (as is required), a total of 5-7 lanes/columns.

In the latest release - we see some issues in the Dashboard layout.

The activity stream is nice feature, but due to alot of activity on the board in each project (by many users) - the activity stream in the dashboard itself is a space hugger in the dashboard - of lower importance for the individual user. (NOTE: we also use public boards and RSS to keep people up-to-speed on activity on their projects, a great feature)

**A good summary of assigned tasks and subtasks is the most important feature of the dashboard, IOHO.**

Hence, 
**Would it be possible to allow the admins an option in the settings so that activity stream is shown at the bottom, and that all the screen width in Dashboard can be used for showing tasks and subtasks?**

**Also, if member of several projects, now you have to click icon for "Next" to view your "other projects" that don't fit in the list. A longer list, with scrolling down would be of preference.**

Suggested placement of activity stream illustrated below:
![dashboard](https://cloud.githubusercontent.com/assets/10092252/5427684/a684762e-83a8-11e4-9d54-ebb0b19c514b.jpg)

**Comment by fguillot** [comment]
With the last development version, you can choose to hide or show any section of the dashboard. Just hide the activity stream section to have a single column view.
