### ISSUE TITLE
Board Tasks - Same due date - multiple timestamps

### ISSUE THREAD

**Issue by TabDambrine** [fguillot/kanboard#477]
Hi,

We've come through a strange thing on the board one morning : Not all tasks with due date at the same date were red, only a few of them. By the day passing more and more of them went red.

It seems that even with the same due date the timestamp of the due date in the task is not the same : i made an example by creating a project and put in it 3 tasks with the same due date.

![kanboardtasks](https://cloud.githubusercontent.com/assets/4599948/5486801/fb414b42-86aa-11e4-8296-519e3ced7540.PNG)
 I modified the board\task.php to see the timestamp next to the due date.

the first one is on 31/12/2014 at 11:36:21	
the second on 31/12/2014 at 11:36:28	
the third on 31/12/2014 at 11:36:34

maybe it would be a good thing to initialize the date to 31/12/2014 00:00:00 (timestamp 1419980400) in order to have all of them red at the same time beginning the 31/12/2014 or initialize them to 31/12/2014 23:59:59 (timestamp 1420066799) to have all of them red on 01/01/2015.

Don't know yet if the due date should be a day over to be red or the specified day itself but it would be nice to have the same timestamp for the same due date.

What do you think of it ?

**Comment by fguillot** [comment]
With the last version of master, due date don't contains the time anymore (reseted to 00:00:00).
