### ISSUE TITLE
Keyboard shortcut for accepting input

### ISSUE THREAD

**Issue by aleixpol** [fguillot/kanboard#480]
It's quite standard nowadays to use "Control+Enter" for accepting the current input. It could be used to save comments, create new tasks etc.

**Comment by fguillot** [comment]
It's on the roadmap.

**Comment by fguillot** [comment]
I started to implement some keyboard shortcuts in master:

- Ctrl+Enter or Cmd+Enter to save a form
- b to open the board selector
- n to create a new task from the board
- s to collapse/expand tasks on a board
