### ISSUE TITLE
Some tasks are now invisible?

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#483]
I updated my git checkout of master to try out the new swimlanes feature, and now I see that the last of my 6 columns always shows as empty even though there are items in it!

I thought the tasks had been deleted in a terrible accident, but:

* Creating a new task in that column results in the task not showing up
* Using the "Search" feature, I can find the tasks that were in that column... and their status is still Open (not Closed), so there's no reason why they shouldn't show up there. How can I troubleshoot this?

**Comment by nekohayo** [comment]
Hmmm... When I click on a task's title inside the board, I get an error message: "Sorry, I didn't found this information in my database!" — I haven't bisected or anything, but could your latest fixes have caused this?

P.s.: there's a typo in there... it should be "I didn't find", not "I didn't found"...

**Comment by euneuber** [comment]
I have to confirm nekohayo error. My version is ee8ec7685f95125c385d17dad41369a549ce9bbf.
If I go back to 66f150d887a34d2b51ff14f22d0fd41a34f8cc77 everything is OK.

**Comment by nekohayo** [comment]
Lol j'ai trouvé. The bug is that &project_id=123 is missing in the URL when you do that...

**Comment by fguillot** [comment]
Yes, I fixed that yesterday, you should update the code again and also the dependencies with composer.

I'm currently testing with my own instance to find other bugs after my different refactorings... unit tests can't catch user interface problems.

I close this ticket, if you find something else just open a new one :)
