### ISSUE TITLE
adding file attachments to comments

### ISSUE THREAD

**Issue by myrdd** [fguillot/kanboard#484]
Thank you for this great task manager! I'd like to add a feature request I couldn't find.

It would be great if adding file attachments to *comments* would be possible.

**Comment by oliviermaridat** [comment]
Hi,

It seems similar to #423.

**Comment by myrdd** [comment]
> It seems similar to #423.

Not exactly. As far as I understand #423 it's about adding attachments *to the task* when commenting. What I'm suggesting is the possibility to add attachments **to a comment** instead.

By the way, I think that any new feature – like this one – should be *optional*, i.e. it should be possible to disable that feature.

**Comment by fguillot** [comment]
To keep Kanboard simple, I think attachments to tasks are good enough.
