### ISSUE TITLE
Github action to set category does not work

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#485]
Using master, add an action to set the category based on the Github label.
Now create a Github issue and assign a label to it
The issue is created in Kanboard, but the category has not been set.

On the Github side, everything seems to be OK. It got a 200 status from Kanboard.

**Comment by fguillot** [comment]
It's weird? I use this feature everyday with Kanboard itself.

Do you use the last version of master?

**Comment by oparoz** [comment]
I'll try again when the chained actions are implemented. It could be that there is a conflict between various actions.

**Comment by oparoz** [comment]
It only works if I assign the label after I've created the issue. If I add it before submitting the issue, then the category is not assigned in Kanboard. I'm also assigning a colour at the same time, so maybe that's getting in the way.

**Comment by fguillot** [comment]
Can you tell me which automatic actions you are using with the parameters and the order?

Because I do exactly the same thing with this bug tracker...

**Comment by oparoz** [comment]
![kb_actions](https://cloud.githubusercontent.com/assets/323220/5989282/6b962cec-a982-11e4-8c2e-5a68d0adacd2.png)
