### ISSUE TITLE
[bug]Chinese translations missing creator

### ISSUE THREAD

**Issue by sam7200** [fguillot/kanboard#492]
if Chinese choosed for language displayed

app/Locale/zh_CN/translations.php

>'Created by %s' => '创建者：',

should be changed to

>'Created by %s' => '创建者：%s',

- Otherwise,you will not see the creator in task;

BTW,this Kanban is the best one i used,thank you;

**Comment by fguillot** [comment]
Thanks, it's fixed in master.
