### ISSUE TITLE
[BUG?] [current dev version] - link to task from activity stream results in error page not found

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#495]
**Used composer and got the lastest dev version.**
-Thumbs up, like it....

Bug, or is it just me(?)
When clicking the task ID (# xx) in Activity stream, the following appears.
When accessing the "ticket" from the board, everything is fine...

SCREENSHOT:
![screen](https://cloud.githubusercontent.com/assets/10092252/5636015/7b716584-95ee-11e4-934f-4c8f9968aa5b.jpg)

**Comment by fguillot** [comment]
It should be fixed now in master.

**Comment by timjcraig** [comment]
@fguillot issue resolved after updating to latest master.
