### ISSUE TITLE
[FR] collapse swimlane

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#496]
It would be nice, if you could collapse/hide a swimlane. (like filters)

- - Swimlane 1
  + Row1
  + Row2
+   collapsed Swimlane 2
- - Swimlane 3
  + Row 1
  + Row 2

I hope you can understand it ;) 

reference #465

**Comment by adilbo** [comment]
Could be done with CSS: http://jsfiddle.net/thurstanh/emtAm/2/

**Comment by BlueTeck** [comment]
#542

**Comment by fguillot** [comment]
A patch have been merged for that.
