### ISSUE TITLE
Problem updating date related fields through api

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#497]
Hi,

with the latest kanboard version from December 6th I have a problem updating tasks through php with the json api. The following fields seem to be problematic:
date_modification, time_estimated, date_started, date_due, time_spent, time_estimated
When I set those fields to a new value or just reuse the original value updating the task fails.

OS is Debian Wheezy with PHP 5.4.4.

Is there a way to get a detailed error message?

**Comment by fguillot** [comment]
The due date a have to be a ISO-8601 format for task creation and task modification. However, when you get a task the date is shown as a unix timestamp.

```php
$client = new JsonRPC\Client('http://localhost/kanboard/jsonrpc.php');
$client->authentication('jsonrpc', 'token');

// Create a task with due date
$task_id = $client->createTask(['title' => 'My new task', 'project_id' => 2, 'date_due' => '2015-01-20']);

$task = $client->getTask($task_id);
print_r($task); // Display unix timestamp

// Same thing here, the date must use the iso format
$client->updateTask(['id' => $task_id, 'date_due' => '2015-01-14']);
```

- date_modification can't be set, it's done internally by the application
- Other fields time_estimated, date_started, time_spent and time_estimated are not yet available through the api.

Only fields described in the documentation are available.

The API will be improved in the next version.
