### ISSUE TITLE
createTask api call does not work anymore

### ISSUE THREAD

**Issue by lehrhardt** [fguillot/kanboard#498]
Hi,

with the Kanboard release from December 6th the following json api call does not work with php anymore :

$client->createTask(['title' => 'Super task', 'project_id' => 1]);

while the following calls do:

$client->createTask('My new task', 1);
$client->execute('createTask', ['title' => 'My new task title', 'project_id' => 1]);

OS is Debian Wheezy, PHP 5.4.4.

**Comment by fguillot** [comment]
Those calls are exactly the same, I just tested with the version 1.0.10 and that seems ok for me.

Do you have any errors?

**Comment by fguillot** [comment]
No answer, ticket closed.
