### ISSUE TITLE
Compress change notifications and activity logs

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#499]
If you look at the "activities" page of a board where someone made incremental changes to an item, you get stuff like:

```
January 8, 2015 at 2:27 AM
Bob updated the task #20
Review the FOOBAR branding and trademark guidelines for ® vs ™ confusion

January 8, 2015 at 2:27 AM
Bob updated the task #20
Review the FOOBAR branding & trademark guidelines for ® vs ™confusion

January 8, 2015 at 2:27 AM
Bob updated the task #20
Review the FOOBAR trademark guidelines for ® vs ™confusion

January 8, 2015 at 2:06 AM
Bob created the task #20
Review the FOOBAR trademark guidelines for ® vs ™confusion
```

I'd rather skip all the intermediate steps (done by a single person onto a task in a short period of time [less than an hour?] with no other people involved). Either that or make it a combined view (bulleted/indented changes for an item?) or something...

The goal would be to have something that is less like an information-overloading robotic "change log" and more like a human "exec summary". I reckon this is maybe not trivial to achieve, but it would be pretty nice (example usecase: someone using the activity log to write a report).

**Comment by fguillot** [comment]
I took another approach, the "task update" event describe the changes made in the task now.
