### ISSUE TITLE
[UI] make task menu more clearly

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#500]
Simple improvement, add a space between the menu.
Part 1: Actions regardings this task
Part 2: Action regarding task in context
![menu](https://cloud.githubusercontent.com/assets/1961634/5664402/834f52e4-9750-11e4-862c-740ce48c49ae.PNG)

**Comment by fguillot** [comment]
I splitted the sidebar with 2 menus. I will see after a while if it's better to use...
