### ISSUE TITLE
Syncing kanboard/data/ between two computers

### ISSUE THREAD

**Issue by jibe-b** [fguillot/kanboard#503]
Hi,

If the kanboard/data/ folder is shared between two computers (via [bittorrentsync](http://getsync.com) or [syncthing](https://github.com/syncthing/syncthing)), will the two boards behave in a synchronised way? (excepting the possible delay due to syncing)

Best regards,

jibe-b

**Comment by mluepkes** [comment]
If you're running sqlite and the configs don't differ, they should. BUT: You'll run into sync conflicts if you're using both systems simultaneously. Using this system you'll have to wait for a sync after making edits - so it's a system only to be used by a single user.

**Comment by jibe-b** [comment]
Thanks for the answer. I will try

**Comment by mluepkes** [comment]
Why exactly do you want to sync the data folder and just put kanboard on a webhost or host it locally on one of the two computers?

**Comment by fguillot** [comment]
I never tested, but if you are the only user it should work.

**Comment by jibe-b** [comment]
What I would like is having:

- data shared between users via p2p sharing system (syncing done by an external software, like [syncthing]() or [bittorrentsync]())
- software (kanboard) running on your computer.

This way, kanboard could be used as an indie web software: 
you can run it on your own computer with personal data, and share data when collaborating on a project.

Anyhow, sqlite database is not intended for p2p syncing, as it requires a master.

**Comment by TheRojam** [comment]
@fguillot is this _now_ working in some kind??
