### ISSUE TITLE
Project Duplication: Wishes & Implementation

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#505]
After yesterdays hacky implementation I'm thinking about doing a proper implementation of the project duplication feature including categories, swimlanes and tasks. Any wishes on where to put it? I was thinking about writing a Model\ProjectDuplication which handles the whole duplication apart from the barebones project duplication. I feel like leaving that in the Project model. Wishes/Input?

**Comment by fguillot** [comment]
Concerning the pull-request, the task duplication itself should not happen in the controller but in the model:

https://github.com/fguillot/kanboard/blob/master/app/Model/Project.php#L244

- Actually, the board, automatic actions, categories and users are duplicated.
- Coping tasks should be optional by example with a checkbox visible in the template.
- Moving that logic in class ProjectDuplication is a good idea

**Comment by mluepkes** [comment]
In that case I would make every part apart from the project board optional -> checkbox. Will get working on an appropriate ProjectDuplication model.

To streamline the issue, should duplication cascade model-wise, e.g. ProjectDuplication->duplicate() -> ModelDuplication->duplicate() -> Subtask->duplicate. I think that makes the most sense. This way every base model (Project, Swimlane, Task, Subtask etc) only handles their own duplication. The handling of finding e.g. each subtask for a task and starting Subtask->duplicate() is then done by TaskDuplication.
