### ISSUE TITLE
Fatal error when reading tasks

### ISSUE THREAD

**Issue by Torsten-K** [fguillot/kanboard#507]
Hello,

I get a fatal error in case I try to read a task (no matter if clicking on task description or symbol in the corner right below). This happens when running on MySQL, PHP 5.6.3 and installation in a subdomain, I haven’t seen this under SQLite, PHP 5.3.29 and installation in a subdirectory. The error reads:

Fatal error: Uncaught exception 'LogicException' with message 'Unable to load the template: "task/comments"' in /var/www/ud04_82/html/kanboard/app/Core/Template.php:39 Stack trace: #0 /var/www/ud04_82/html/kanboard/app/Template/task/show.php(7): Core\Template->render('task/comments', Array) #1 /var/www/ud04_82/html/kanboard/app/Core/Template.php(45): include('/var/www/ud04_8...') #2 /var/www/ud04_82/html/kanboard/app/Controller/Base.php(247): Core\Template->render('task/show', Array) #3 /var/www/ud04_82/html/kanboard/app/Controller/Task.php(81): Controller\Base->taskLayout('task/show', Array) #4 /var/www/ud04_82/html/kanboard/app/Core/Router.php(88): Controller\Task->show() #5 /var/www/ud04_82/html/kanboard/app/Core/Router.php(107): Core\Router->load('/var/www/ud04_8...', '\\Controller\\tas...', 'show') #6 /var/www/ud04_82/html/kanboard/index.php(9): Core\Router->execute() #7 {main} thrown in /var/www/ud04_82/html/kanboard/app/Core/Template.php on line 39

**Comment by Torsten-K** [comment]
After some more testing, I can say that MySQL is not the problem. Might be the PHP version.

**Comment by mluepkes** [comment]
Moin! Did the error occur right after installation? Maybe it's an install error and the template is really not there. I guess you checked that first?

**Comment by Torsten-K** [comment]
Schönen guten Tag,

thank you, mluepkes – that did the trick. I uploaded all files again, and now it works. This was such a simple solution that it would never have occured to me. (._.);

Bug report can be closed,

**Comment by mluepkes** [comment]
When in doubt, try turning it off and on again ;)
