### ISSUE TITLE
Inactive Project: Don't show (sub-)tasks in dashboard

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#508]
I'd like some filter mechanism to be implemented so that tasks from deactivated projects are not displayed in the dashboard under "My Tasks". Apart from logical reasons this would enable users to create projects as templates purely for cloning purposes.

**Comment by fguillot** [comment]
I'm ok with the fact of not showing tasks for inactive projects.

But I don't get the use case you describe about cloning the project for users?

**Comment by mluepkes** [comment]
User has many projects with same workflow and board board setup. User creates a board he calls e.g. "Template". This board has the setup (Columns, Tasks, Subtasks etc) needed for each of these similar projects and is set inactive. User then clones "Template" and renames "Template (Clone)" to "Project 1".

Current behaviour: All tasks from "Template" and "Project 1" which are assigned to User are displayed in the dashboard as assigned tasks.

Expected behaviour: Only tasks from active "Project 1" are displayed in dashboard.

Solution: Filter out Tasks from Projects which are set as inactive.

**Comment by fguillot** [comment]
I merged your patch, so I close this ticket now.
