### ISSUE TITLE
File Upload with "Screenshot from Clipboard" option

### ISSUE THREAD

**Issue by adilbo** [fguillot/kanboard#511]
If i add a Ttask ist would be great and helpfull if i could paste a screenshot from the clipboard and upload it as a attached file - like http://supa.sourceforge.net/ see Demo http://supa.sourceforge.net/demo.php

**Comment by fguillot** [comment]
I like the idea but we should find another library to do that, "supa" is a Java applet and I got many security warnings. There is probably something similar in Flash.

Jira also have a feature like that, I should take look.

**Comment by Gaffling** [comment]
Maybe only JavaScript (but only for Firefox and Chrome): http://joelb.me/blog/2011/code-snippet-accessing-clipboard-images-with-javascript/

**Comment by Gaffling** [comment]
This is how Jira and Redmine do it: http://www.redmine.org/issues/3816

**Comment by lawre** [comment]
Trello, pasteboard and imgur all have this feature.  I know all the browsers access the clipboard for images differently, thus they only seem to work in Opera and Chrome now.  I'm ok with a "only works in chrome/opera" alpha feature just to get the ball rolling on this.  I'm currently on Trello and worry every day that I don't own my own boards and cards...  Can't wait to switch to kanboard when this critical feature is implemented.

**Comment by adilbo** [comment]
![image](https://cloud.githubusercontent.com/assets/10500034/5940144/27a40494-a709-11e4-9cd6-ecac0720404a.png)

Maybe ist should work like her on github

**Comment by fguillot** [comment]
I have a working prototype in pure Javascript based on the mentioned links above. That works only with Firefox and Chrome. I will release that soon if that work well.

**Comment by fguillot** [comment]
Finally it's pushed into master. You can add a screenshot directly from the dropdown menu in the board:

![Dropdown screenshot menu](http://kanboard.net/screenshots/documentation/dropdown-screenshot.png)

And after you just have to press CTRL+V:

![Screenshot page](http://kanboard.net/screenshots/documentation/task-screenshot.png)

At the moment, it's works only with Chrome and Firefox (tested with Mac OS X).

**Comment by BlueTeck** [comment]
Works fine, but is it needed in the dropdown menu?

**Comment by ashbike** [comment]
+ Works on Windows 7 + Chrome Version 41.0.2272.118 m. 
- Does not work on Windows 7 + Firefox 37.0.1

**Comment by fguillot** [comment]
I tested on Windows 7, IE11, last Chrome and last Firefox, seems to work.
