### ISSUE TITLE
BUG? If i want to dublicate a project i get an Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by adilbo** [fguillot/kanboard#512]
Fatal error: Uncaught exception 'RuntimeException' with message 'SQL error' in /var/www/virtual/example.com/domain.de/htdocs/vendor/fguillot/picodb/lib/PicoDb/Database.php:246 Stack trace: #0 /var/www/virtual/example.com/domain.de/htdocs/vendor/fguillot/picodb/lib/PicoDb/Table.php(164): PicoDb\Database->execute('SELECT * FROM ...', Array) #1 /var/www/virtual/example.com/domain.de/htdocs/vendor/fguillot/picodb/lib/PicoDb/Table.php(193): PicoDb\Table->findAll() #2 /var/www/virtual/example.com/domain.de/htdocs/app/Model/Action.php(344): PicoDb\Table->findOne() #3 /var/www/virtual/example.com/domain.de/htdocs/app/Model/Action.php(315): Model\Action->resolveDuplicatedParameters(Array, '51') #4 /var/www/virtual/example.com/domain.de/htdocs/app/Model/Project.php(258): Model\Action->duplicate('11', '51') #5 /var/www/virtual/example.com/domain.de/htdocs/app/Controller/Project.php(310): Model\Project->duplicate('11') #6 /var/www/virtual/example.com/domain.de/htdocs/app/Core/Router.php(88): Controller\Projec in /var/www/virtual/example.com/domain.de/htdocs/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 246

**i use mysql**

**Comment by Gaffling** [comment]
i use mysql

**Comment by fguillot** [comment]
I cannot reproduce the issue, can you provide more information? Do you have automatic actions, categories or users in the source project?

Apparently the bug happens during the execution of the method `resolveDuplicatedParameters()`, that mean an automatic action cannot be duplicated. Can you describe which automatic actions are configured in your project?

**Comment by Gaffling** [comment]
Yes, i have all: users, categories and actions like this:

TaskAssignColorCategory
TaskAssignColorCategory
TaskAssignColorCategory
TaskAssignColorCategory
TaskAssignColorCategory
TaskAssignColorCategory
TaskAssignColorCategory
**TaskAssignCurrentUser**
TaskAssignColorCategory

**Comment by Gaffling** [comment]
I try this: Delete all Actions - and it works! ;) But it would be great if i can dublicate the acions too! ;)

**Comment by fguillot** [comment]
Should not happen anymore with the last development version.
