### ISSUE TITLE
How to style CSS for Markdown?

### ISSUE THREAD

**Issue by Torsten-K** [fguillot/kanboard#514]
Dear Kanboarders,

I don’t like the underlined headings in the task descriptions and comments. I changed the file _assets/css/markdown.css_ (deleted _text-decoration: underline_), but that has no effect. I cleared the browser cache and even tried with another browser, without success.

Anyway, I find the lot of CSS files a bit confusing, so maybe I touched the wrong file? 

Can anybody help me finding a solution? 
Thanks in advance,
Torsten

**Comment by oliviermaridat** [comment]
Hi Torsten-K,

I don't know how it works exactly (and I will be glad to have some hints there ;-D), but a quick answer to "make it work now" is: update app.css.
Apparently, all CSS files are merged (but I don't know when nor how) in app.css.

**Comment by mluepkes** [comment]
The single CSS files seem to all be merged into app.css. 

Removing *text-decoration: underline* from *.markdown h1* should lead to the desired results.

**Comment by Torsten-K** [comment]
Okay, thank you, guys, I will change app.css and tell you how it worked.

**Comment by adilbo** [comment]
Maybe you use:

/* markdown content */
.markdown {
    line-height: 1.4em;
    font-size: 1.0em;
}

.markdown h1 {
    margin-top: 5px;
    margin-bottom: 10px;
    font-size: 1.5em;
    font-weight: bold;
    /* text-decoration: underline; *//* adilbo */
}

.markdown h2 {
    font-size: 1.2em;
    font-weight: bold;
    /* text-decoration: underline; *//* adilbo */
}

.markdown h3 {
    font-size: 1.1em;
    /* text-decoration: underline; *//* adilbo */
}

.markdown h4 {
    font-size: 1.1em;
    /* text-decoration: underline; *//* adilbo */
}

.markdown p {
    margin-bottom: 10px;
}

.markdown ol,
.markdown ul {
    margin-left: 25px;
    margin-top: 10px;
    margin-bottom: 10px;
}

.markdown pre {
    background: #fdfdfd;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ddd;
    overflow: auto;
    color: #444;
}

.markdown blockquote {
    font-style: italic;
    border-left: 3px solid #ddd;
    padding-left: 10px;
    margin-bottom: 10px;
    margin-left: 20px;
}
.markdown p code{ /* adilbo */
	color: #dcdcdc;
	font-family: monospace;
	border-radius: 5px;
	background: #3f3f3f;
	padding: 3px;
	font-size: 1.0em;
}

**Comment by fguillot** [comment]
- Edit the file markdown.css
- Execute the script `./scripts/make-assets.sh` to generate css/js files

**Comment by Torsten-K** [comment]
@mluepkes and @adilbo:
Changing CSS files is not the problem, as I am a web designer. You could not know that, so thank you for your help. The issue is, that all those tiny little CSS files have to be merged into the one big app.css. You could change that file directly, but there is a warning in the file that you should keep your hands off  it.

@fguillot: 
Hm … I cannot find such a script, and I can’t run shell scripts anyway (standard web hosting account). Anyway, I will change app.css, although I know I should not do it – or do you think that would be a very bad idea?

**Comment by mluepkes** [comment]
`./scripts/make-assets.sh` is only contained in the github release. The kanboard.net *stable version* does not contain development scripts and comes bundled with composer dependencies. If you want do use development scripts, download the master or e.g. https://github.com/fguillot/kanboard/archive/v1.0.11.zip

Be advised that in order to run kanboard itself from that download, you'll need to run `composer install` or copy the vendor directory from the *stable release*

**Comment by Torsten-K** [comment]
@mluepkes Danke / Thank you!
