### ISSUE TITLE
[bug] Private projects created by non administrators can not have their user lists changed

### ISSUE THREAD

**Issue by stile1987** [fguillot/kanboard#517]
Kanboard v 1.0.11

When a NON administrator creates a new private project, the resulting project can not have the users modified by anyone(project manager/creator/admin's) the only "fix" that I have been able to identify is deleting the project and having an administrator re-create the project and set the user as the project manager.

This is with both remote and local users.

**Comment by David-Norris** [comment]
Similar to #417

**Comment by fguillot** [comment]
It's not a bug, it's described in the documentation: http://kanboard.net/documentation/creating-projects

There is no user management with private projects.

**Comment by stile1987** [comment]
May I then suggest one of two things.

A) Rename the type of project as there are "private projects" created by administrators that are fully functional

B) Allow private projects by non administrators to be converted to a full project so that user management can be done

Apologies for the initial misunderstanding, I had tried looking on the documentation and with multiple searches online but was not able to find anything about the limitations of those projects.
