### ISSUE TITLE
Project due date

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#519]
I would like to have the ability to assign due dates to projects.

**Comment by oliviermaridat** [comment]
Assigning a due date to a project seems very useful, but generally, one project can have several due dates (e.g. to target v1, v2, ...). So, a roadmap feature (#424) seems to fit better this objective.

**Comment by mluepkes** [comment]
Project / Milestone / Task due dates are of increasing specificity, so they all have their own merits.

**Comment by fguillot** [comment]
There is now a start and end date for projects in the development version.
