### ISSUE TITLE
[Idea | UI] Quick dropdown Menu 

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#520]
Hi all,

i was playing around with a right click context menu for desktop (not nice on device without mouse).

Just a little fiddle about that, what do you think? Just a concept, not implemented nice.
This menu could be also accessable via a little button.

http://jsfiddle.net/blueteck/wbcwkzev/5/

Update: No right click -> new button or click on task id. I am currently designin a new prototype.

**Comment by mluepkes** [comment]
+1! Would make life easier at least for color/category assignment. I'd drop user and just maybe status, which can be set directly from the board or achieved with an auto action for a column. Instead of those, add quick links to adding subtasks, comments and documents.

**Comment by fguillot** [comment]
The problem with that is you override the default browser behaviour.

http://stackoverflow.com/questions/779689/right-mouse-click-in-web-applications-good-or-bad-idea
http://stackoverflow.com/questions/2055065/why-isnt-right-click-more-used-in-web-applications?rq=1

However a dropdown menu that appears with a left click on the task id is maybe better (works on tablets). The context menu can display shortcut methods to update the task quickly.

**Comment by BlueTeck** [comment]
Right click or left click on the id or a little button is not important. Important is a way to archive your goal faster. Should i implement a menu like that (click on id or button) or do you want to do it by yourself?

**Comment by fguillot** [comment]
If you know how to implements a simple dropdown menu that works on major browsers/tablets and that don't use too many external libraries, feel free to propose something.

There is also too many items now for the menu above the board, a dropdown menu is maybe a good idea.

**Comment by BlueTeck** [comment]
If I use Jquery and not just CSS3 it should be working on all devices. I will make a prototype.

**Comment by elnicko** [comment]
This would be a great improvement, keep in mind the fguillot's comments above: left click and no JS/library bloating :+1: 

Let men know if you need a tester.

**Comment by BlueTeck** [comment]
I am not sure if i should append the dropdown to every task due rendering (https://github.com/fguillot/kanboard/blob/master/app/Template/board/task.php) or if i should load the dropdown via Ajax if it is needed. Any suggestions?

**Comment by oliviermaridat** [comment]
Yes, using an asynchronous method seems to be a better solution.
If I understand well, you could use the popover "method" that is used to display Subtasks, descriptions, comments, etc, for each task on the board view.

**Comment by elnicko** [comment]
After a careful consideration, such a pop-up will provide a second click-path to doing the same stuff which is available when clicking on the task ID. At the time I was "voting" this feature up, I thought that the modal dialog was removed (I always clicked on the small icon on the bottom right instead of the task ID). Now that I know that the functionality is there wouldn't it be better to increase the usability of the modal dialog instead of introducing a second way of doing the same thing?

By increasing the usability I mean that it appears when one clicks anywhere on the task so that one does not have to target precisely the small task ID.

**Comment by BlueTeck** [comment]
Click anywhere is also a possibility. Or it could be changed, click on the Id is the actual left click on the task, and left click anywhere on the task is the new menu. We habe also to define the functionsof the new menu (i.e. color, member, categorie).

I have taken distance from my idea, to do it with jquery by myself. Jquery UI which is already used in Kanboard has a menu funktion, which is also usable via keyboad. http://jqueryui.com/menu/

**Comment by fguillot** [comment]
I added a dropdown menu for tasks on the board in the master version. I'm testing that on my own installation...
