### ISSUE TITLE
Rights to create projects

### ISSUE THREAD

**Issue by AoHans** [fguillot/kanboard#521]
Right now users only can create a private projects and administrators can create projects for teams. Administrators can also set all application setttings. Is it possible to either give users the possibility to create projects for teams or create a special user who can create projects like an administrator, but can't edit the application settings?

**Comment by jdittrich** [comment]
related for enabling the system to run without the admin setting up everything:
#570 (Add registration feature)

**Comment by Zorin95670** [comment]
It would be nice, if we are three type of user :
- administrator : can do anything
- "manager" : can create multi user project and private project
- user : can create private project

**Comment by fguillot** [comment]
Now there is a new type of users call "Project administrator" to create multi-users projects.

**Comment by DoumeDuSud** [comment]
perfect :+1:  thanks you @fguillot

**Comment by Zorin95670** [comment]
Yep you awesome ^^

perfect [image: :+1:] thanks you @fguillot <https://github.com/fguillot>

—
Reply to this email directly or view it on GitHub
<https://github.com/fguillot/kanboard/issues/521#issuecomment-131637682>.
