### ISSUE TITLE
[Idea] Implement Teams

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#522]
Include Teams/Groups into Kanboard. As you could do it here on Github for Example.

To there could be a Projectowner or Team. Also you could assign Cards to Teams or Users.

Reference #521 #347 #85

**Comment by valessiobrito** [comment]
Other reference: #756

**Comment by DoumeDuSud** [comment]
:+1:

**Comment by BlueTeck** [comment]
Now work in progress :smile: 

https://github.com/fguillot/kanboard/commit/e582d4047b061f0c17e6366fed2bf1cabd624c10

**Comment by fguillot** [comment]
Teams have been implemented in the development branch. You could test this feature and report potential bugs if you would like to.

**Comment by nekohayo** [comment]
Thanks for your work for that folks :) I can see a use for this feature. On the other hand, I still have a need for the ability to assign multiple users (not a team) to a task, as per issue #85 (+ issue #126 for the avatar representation). Loosely quoting from my last comment in 85:

> There are cases where projects are assigned with "equal responsibility" to two people. In the environment I'm dealing with, the notion of "teams" won't work for that, because it's only 4-5 people—they are essentially working in a cross-teams fashion.

**Comment by awatterott** [comment]
:+1: Both assigning more than one person and also a group to a task would be nice feature.
