### ISSUE TITLE
Download link not working on board view

### ISSUE THREAD

**Issue by marcosaccioly** [fguillot/kanboard#523]
Hi all, 

The link to download files does not work on the preview box of the board view because it is missing the project_id parameter. 

Link on board view (i.e.: ?controller=board&action=show&project_id=8): 
http://172.17.159.150/kanboard/?controller=file&action=download&file_id=11&task_id=100

Link inside task details page (i.e.: /?controller=task&action=show&task_id=100&project_id=8): 
http://172.17.159.150/kanboard/?controller=file&action=download&task_id=100&project_id=8&file_id=11

**Kanboard version:  1.0.11**

**Comment by fguillot** [comment]
Thanks it's fixed in the dev version.

**Comment by BlueTeck** [comment]
Could be closed.
