### ISSUE TITLE
[FYI] FreeBSD Port

### ISSUE THREAD

**Issue by freebsd-kanboard** [fguillot/kanboard#525]
Hi,

just FYI:

I have created a FreeBSD port for Kanboard.
Repository: https://bitbucket.org/if0/freebsd-kanboard
FreeBSD bug/request to add to ports tree: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196810

Have fun!
if0

**Comment by fguillot** [comment]
Awesome, can you explain quickly how to install the port? I would like to update the documentation https://github.com/fguillot/kanboard/blob/master/docs/freebsd-installation.markdown

Thanks

**Comment by freebsd-kanboard** [comment]
Pull request created. Please let me know it anything needs to be updated or feel free do update it yourself (spelling, language correctness, etc.)

**Comment by fguillot** [comment]
Thanks, I merged your pull-request: http://kanboard.net/documentation/freebsd-installation

I will update the doc when the port will be available in the official Freebsd port tree.

**Comment by fguillot** [comment]
According to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196810 Kanboard have been integrated into the port tree of FreeBSD.

I tested the package on FreeBSD 10.1 and I have one question: is it the responsibility of the user or the packager to make the directory /usr/local/www/kanboard/data writable by the user www?

Thanks again to maintain a FreeBSD port :)

**Comment by fguillot** [comment]
For your information the dependencies php56-gd and php56-hash seems missing.

**Comment by freebsd-kanboard** [comment]
The port has been added to port tree, indeed. :)

##### Regarding access rights:
In fact the user does not have to give the access rights to `www`. It is done automatically by a port or package (if you install it with pkg).

**Comment by freebsd-kanboard** [comment]
##### Regarding dependencies:
Is there a list of required and recommended dependencies? I have found only this: `mbstring`, `gd` and `pdo_sqlite` in docs/installation.markdown. `hash` is not mentioned.

I will anyway update the documentation for FreeBSD once it is clarified. Thanks!

**Comment by fguillot** [comment]
I didn't mentioned `hash` in the doc because with php packages on linux distros it's always included by default, so I don't even think about that. In FreeBSD, php extensions seems to be separated into more packages.

From this list https://www.freebsd.org/cgi/ports.cgi?query=php56&stype=all&sektion=all, those packages can also be added:

- php56-json
- php56-ldap (optional only if people want to use ldap authentication)
- php56-opcache (optional but recommended to improve performances)

Thanks

**Comment by freebsd-kanboard** [comment]
I have submitted the patch for the port with update of the license and some Makefile changes: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=202032

**Comment by fguillot** [comment]
Thanks again for creating the package! I posted a news about that: http://kanboard.net/news/freebsd-port-kanboard
