### ISSUE TITLE
Page containing all activity (including recent)

### ISSUE THREAD

**Issue by marcosaccioly** [fguillot/kanboard#528]
Hey Guillot, 

Could there be a link on the home panel to a page containing all recent activity from all projects? As of version 1.0.11 we can only see the latest 10 activities on the right column. It would be great to have a page or a pager allowing us to see all recent activity. 

P.S.: Your Kanboard is more and more excellent every day. We've been using it in our production department (we are a public education institution in Brazil, specialized in distance education) and the number of tasks and everyday actions is growing fast. As a designer, I look forward to helping you improve your software.

**Comment by tscofield** [comment]
Adding the ability to filter the contents of this page would be helpful as well.  For example, being able to pull all of the comments on a select group of projects over a specified date range could be used to create status reports for management.

**Comment by frederikheld** [comment]
Push!

Having a view that shows all acitivites would be really helpful. Expecially since each action (move, rename, comment, change category, etc.) creates it's own activity, the recent 10 activities do not cover all activities since my users' last logins.

**Comment by frederikheld** [comment]
Okay, I found it in the project view's menu. But it would be nice to have an overview for all projects as well.

**Comment by fguillot** [comment]
From the dashboard, you can see the activity stream of all projects where you are member.
