### ISSUE TITLE
Quick editing of a task description

### ISSUE THREAD

**Issue by elnicko** [fguillot/kanboard#529]
As of version 1.0.11, we are unable to edit the description of the task by hovering over the document icon on the bottom right. In 1.0.4 a click on this icon brought up a "pop-up", in which we were able to edit the task's description - just as the pop-up containing the drop-down for category selection. 

Now clicking on the icon brings up the Task detail view, which requires an additional click on "Edit the task" to be able to edit the description. This slows things down, especially when using kanboard over the internet. We were using this feature to quickly add notes or comments on the tasks, which then increased our productivity. 

Is there the possibility to add this feature back into kanboard?

Kind regards and thank you in advance for your time in considering an answer to this issue.

**Comment by BlueTeck** [comment]
Do you mean the popup, if you click on the task id?

**Comment by elnicko** [comment]
Yepp, the link on the task id works just as the link that is now gone from the document icon on the bottom right. I expected the link on the task id to actually open the task detail view, instead of the quick edit popup, which is probably why I never paid any attention to it. Thank you for your remark.

What is the rationale behind the removal/replacement of the link from the icon?

**Comment by BlueTeck** [comment]
I don't know the reason behind, but i am currently developing a new quick access dropdown menu -> #520

**Comment by elnicko** [comment]
Nice, that will improve usability. Thank you.
