### ISSUE TITLE
[Bug] Calendar Filter

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#531]
Hi @fguillot,

in your merger of my calendar view, you changes the filter logic. I was using the same filter as the board, and the filter was saved per project. You changes it, so that there is an own calendar filter (matter of decisions, i like my idea, that the filters are the same).
But this calendar filter has no project id, so it is wrong after switching the project, because column id is not availiable for that project. See screenshots:
![1](https://cloud.githubusercontent.com/assets/1961634/5816236/6a6b995c-a09e-11e4-97f9-8f9120f87623.PNG)
![2](https://cloud.githubusercontent.com/assets/1961634/5816237/6a706b62-a09e-11e4-9083-1107c269a3ab.PNG)
![3](https://cloud.githubusercontent.com/assets/1961634/5816235/6a6a3ae4-a09e-11e4-82ff-63f7bbda3aea.PNG)

**Comment by fguillot** [comment]
The calendar filters are now prefixed with the project_id in local storage.

**Comment by BlueTeck** [comment]
working
