### ISSUE TITLE
email notification show only php-code in the mailbody

### ISSUE THREAD

**Issue by ukedk** [fguillot/kanboard#532]
Hello! 
first: thank you very much for this really good tool !!!
2nd ;) With 1.0.11 I´ve got e-mail notification with shows only php-code in the body:
e.g.
(#) e($task['title']) ?> () () 
render('notification/footer', array('task' => $task)) ?> 
(it doesnt matter if I set to smtp/sendmail/mail) 
(unzipping the github-repository over the "original" zip didnt solve it)

**Comment by fguillot** [comment]
Something is probably wrong with your installation, that means php didn't parse your files.

It's hard to guess what is wrong, you should give us more details to find the issue. How did you install Kanboard? Where? What is the environment? Do you have any PHP errors?

**Comment by ukedk** [comment]
Helo Frederic,
thanks for reply. Sorry! I analyzed litte deeper. on opensuse where we have kanboard running, there is a /etc/php5/apache2 folder and a /etc/php5/cli (both with php.ini). Because we used php on cli not yet on other programs I copied the apache2 php.ini to the cli-folder...and ... it works.
Sorry for wasting your time!
Have a good time! regards ulli
