### ISSUE TITLE
[Low priority FR] Automatic action --> assign color when task moved to another column

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#535]
Know this probably might be kinda silly for **most users**, so I deem it low priority, but the use case is described as follows:

Public board, where "viewing user" (emergency management) has clicked into the public link to view **one specific ticket**.

The issue is being handled by others. 

The users that are on "it" (the task/issue), are in real time commenting and updating ticket, and the "viewing user" (manager) gets (almost) live updates because the browser is set to automatically refresh each XXX second. 

(the refresh function of the browser is external to KB).

Since the ticket is colored RED while on the board, the colored square surrounding the summary is also red.

When the issue is handled / completed, the ticket is dragged (by the people handling it) to the final column (Completed) and the color changes to e.g. GREEN. 

The effect for the "viewing user" (manager) (who is keeping close tabs on this single, priority issue) is then visually alerted by the colored square changing from RED to GREEN.

EXAMPLE OF USE CASE AS SCREENSHOT

![2](https://cloud.githubusercontent.com/assets/10092252/5827844/5a2ab66c-a0fe-11e4-83d9-e1701e944019.jpg)

**Comment by mluepkes** [comment]
This! I've been looking for this! :D

**Comment by BlueTeck** [comment]
-> #463

**Comment by tconstans** [comment]
It used to be possible in previous version, i was really fond of this feature and would love to have it back

keep up this nice work !

**Comment by sparkles645** [comment]
With 1 0 1 3 - the "Assign a color when the task is moved to a specific column" complies with this FR. 
With all the FR's currently on the board - I'll assist FG cleaning up by closing this one.
Tnx for implementing.
