### ISSUE TITLE
nginx cannot login unless manually append of index.php

### ISSUE THREAD

**Issue by linkyone** [fguillot/kanboard#537]
I'm running version kanboard 1.0.11 on Arch with nginx 1.6.2 and php 5.6.0. When I open the vhost in a browser (firefox) I get the kanboard login page. When I enter my credentials, I get redirected to the login page with "The username is required" and "The password is required" errors. I have to manually put index.php after the domain name and before the php variables to get it to work:

before:
https://subdomain.domain.net/?controller=user&action=check&redirect_query=
after:
https://subdomain.domain.net/index.php?controller=user&action=check&redirect_query=

I've temporarily fixed it with a 302 redirect statement in my vhost config file but wanted to bring this to your attention. My nginx config file is identical to your example except I have SSL statements.

**Comment by fguillot** [comment]
Probably a nginx configuration problem. It's pretty hard to guess what is wrong in your setup.

I use Kanboard everyday with nginx/php-fpm... Do you have any errors in your logs?

**Comment by linkyone** [comment]
No errors in nginx logs, no errors in php-fpm log. Access logs show normal traffic. Php-fpm config file is factory default except for listening via socket and not loopback IP.

I think my php config's <code>cgi.fix_pathinfo=0</code> was the culprit. I missed that part of the install instructions. Thanks for your help guiding me in the right direction.
