### ISSUE TITLE
SSL Certificate Authentication

### ISSUE THREAD

**Issue by vbachvarov** [fguillot/kanboard#538]
Hi,
Is it possible to use an SSL client certificate for authentication in Kanboard instead of username/password?
Other web applications like MediaWiki and Wordpress support it through plugins.
Basically one has to use the environment variables SSL_CLIENT_S_DN_Email and SSL_CLIENT_S_DN_CN for username and execute a login without requiring the password, when SSL is enabled.
Best Regards,
v_bachvarov

**Comment by fguillot** [comment]
Actually it's not implemented, but that should not be very hard to add.

The ReverseProxy authentication is similar to that. https://github.com/fguillot/kanboard/blob/master/app/Auth/ReverseProxy.php

**Comment by CoMPaTech** [comment]
Actually it's something like below, but how to incorporate that into a plugin;
  - The below worked to capture the USER@example.org and using USER wrt to existing username in kanboard.
  - Kanboard 24 was patched using the below with a reverse proxy (doing the SSL-stuff) having 
```                RequestHeader set X-Authenticated-User "%{SSL_CLIENT_S_DN}s"``` set
  - And the appropriate reverse-proxy in the config.php

```
--- kb.old/app/Core/Http/Request.php    2016-01-07 23:32:21.000000000 +0100
+++ kb/app/Core/Http/Request.php        2016-01-09 17:18:50.000000000 +0100
@@ -214,5 +235,10 @@
      */
     public function getRemoteUser()
     {
+
+       if ( isset($this->server[REVERSE_PROXY_USER_HEADER]) )
+       {
+               $this->server[REVERSE_PROXY_USER_HEADER]=preg_replace("/^CN=(.*)\.example\.org,OU=.*$/","$1",$this->server[REVERSE_PROXY_USER_HEADER]);
+       }
```

My 2 cts ...

**Comment by fguillot** [comment]
I made a plugin for SSL Client certificate authentication: https://github.com/kanboard/plugin-client-certificate

Don't hesitate to improve this plugin.

Thanks

**Comment by vbachvarov** [comment]
Thank you fguillot. I will try it out.
Great response time, by the way.
^^

**Comment by vbachvarov** [comment]
Tested it. It works perfectly.
I added a small patch - making the username "strtolower", because in my certificate the username is capitalized, but otherwise - tip top!
