### ISSUE TITLE
[BUG] Duplicating projects may make project name exceed column length

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#541]
Column name of table project is varchar(50). Entering a project with a name which is close to the 50 char maximum and then trying to duplicate said project will result in a:

`[2015-01-23 08:37:14] [debug] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1`

and a white screen to boot.

Name length should be validated after ` (clone)` is appended in order to notify the user of the exeeded char limit.

**Comment by fguillot** [comment]
It's fixed in the last master version.

Thanks.

**Comment by mluepkes** [comment]
Thanks for fixing
