### ISSUE TITLE
Collapsible columns/swimlanes

### ISSUE THREAD

**Issue by krpandrei** [fguillot/kanboard#542]
Hi,
I think was at some extent already discussed the feature request for collapsible columns/swim-lanes. To better exemplify the request at least for columns I attached some screenshots. This will greatly improve productivity together with filters and of course the visual aspect.
Thanks,

![2015-01-23 10_26_09-sametime appshare highlighter](https://cloud.githubusercontent.com/assets/9028153/5871786/5a7d3056-a2eb-11e4-8f04-19fa0b264382.png)
![2015-01-23 10_27_00-sametime appshare highlighter](https://cloud.githubusercontent.com/assets/9028153/5871787/5a7ec8ee-a2eb-11e4-844e-08f408e7dea2.png)
![2015-01-23 10_36_12-sametime appshare highlighter](https://cloud.githubusercontent.com/assets/9028153/5871817/c96b7e0a-a2eb-11e4-9521-11b104176f8b.png)

**Comment by adilbo** [comment]
Looks nice

**Comment by fguillot** [comment]
That will be very nice, just need to figure out how to make that in css/js...

**Comment by krpandrei** [comment]
I don't want to be rude something else but my inspiration comes from a similar project, please see : http://taskboard.matthewross.me/ [Open-Source (MIT License)]

**Comment by mluepkes** [comment]
```Imitation is the sincerest form of flattery```

**Comment by ashbike** [comment]
Can this be achieved in this way? http://codepen.io/ashbike/pen/gbxwvz . 
Clicking on the Swimlane name toggles all items under it. This just hides/shows items, no fancy stuff like ajax loading etc. Just JQuery.

**Comment by BlueTeck** [comment]
:+1: and the same with columns. That would be the first version. Later you could change the Ajax call, so that hidden task aren't updated.

**Comment by BlueTeck** [comment]
And it should be visible that the swimlane is empty and not hidden. +/- Icon for example

**Comment by ashbike** [comment]
The +/- icon part is simple. http://codepen.io/ashbike/pen/JoyRQy. Also, those icons can be absent for an empty swimlane. I will try the column part. That is bit complicated I think.

**Comment by BlueTeck** [comment]
Yes, the icon and also rest is simple, you just need some time ;).

Icons should be from font awesome (http://fortawesome.github.io/Font-Awesome/icons/).

For the columns and swimlane, the task could get a data attribute with the swimlane or column id.

**Comment by adilbo** [comment]
plus
 plus-circle
 plus-square
 plus-square-o

**Comment by ashbike** [comment]
Created a quick prototype on my 'swimlane' branch https://github.com/ashbike/kanboard/commits/swimlane . Also, set up a demo server to try out at http://goo.gl/Y5PrgO .
One can show/hide swimlanes and hidden states are maintained across logins. If a swimlane does not have any task under it, then show/hide icons are not shown. 

I tried to create a quick prototype and majority of it is in JS which I'm not very familiar with. For now, i put the whole JS code in app.js (just to make my life easy). However, it should be organized.

Any help towards organizing this JS code will be appreciated. It has some utility functions and two events (Ready & Ajaxcomplete). Take a look towards the end of app.js.

Column show/hide is bit complicated as it appears, so not focusing on it right now.

**Comment by BlueTeck** [comment]
I tried it, and it is working fine (just the +/- button is a little big and blue :smirk: )

The js code should be in /assets/js/src/board.js the app.js is compiled for release from the files in src.

**Comment by BlueTeck** [comment]
Maybe we can get more space, compare 1 and 2 on my screenshot (quick and dirty):
![collapse2](https://cloud.githubusercontent.com/assets/1961634/5958516/839c2580-a7c5-11e4-9fc7-d27e9e65bfe5.PNG)

**Comment by ashbike** [comment]
@BlueTeck Basically you moved the swimlane name to the same row as column names in case of hidden. What I did is, moved the swimlane name to the columns row. Now the row is much thinner if hidden. Also reduced icon sizes to normal font size and made them circular. I updated the demo. http://goo.gl/Y5PrgO 

I already figured out that the css/js sources reside in their corresponding src folders. What I wanted to know, how do I put the JS inside, say board.js. I'm sorry, but I'm just a beginer in JS and not sure where to put that code in. Just putting right under Kanboard.Board = (function()... would work?

**Comment by BlueTeck** [comment]
Very nice! 

Would work,  but i wouldn't set it in the beginning. @fguillot could give you the right place/order he did a lot of refactoring wuth my js code ;-)

**Comment by David-Norris** [comment]
@ashbike Very nice!

**Comment by ashbike** [comment]
Collapsible swimlane has been merged.

**Comment by oparoz** [comment]
Thanks!

**Comment by fguillot** [comment]
Closing this ticket, hide column are already asked in #101 and swimlanes are implemented in master.
