### ISSUE TITLE
formatting fails for URLs with numeric fragment identifiers

### ISSUE THREAD

**Issue by norcnorc** [fguillot/kanboard#544]
If I write a URL like

http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

Into a kanboard task description, the resulting HTML is invalid, because kanboard is trying to format it as two kinds of links at once: A link to stackoverflow, and a link to task number 1732454

**Comment by fguillot** [comment]
Fix merged.
