### ISSUE TITLE
[FR] Calendar View: Global Calendar

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#547]
I would like to have a global calendar view. Right now it seems to be restricted to displaying the tasks of single projects only. (Nice work btw, @BlueTeck)

**Comment by svenn71** [comment]
I would like to give this feature a :+1:  as I work in a matrix structure on many different projects where all tasks assigned to me are very important. I struggle to keep overview of which product owner to please first.

**Comment by BlueTeck** [comment]
In the current dev, you could see all your tasks in the dashboard, bt you mean all tasks right?

**Comment by svenn71** [comment]
I have 6f94ce6af installed, and that one includes the commit 'Add user calendar view on the dashboard....', and I can now see all tasks in all projects assigned to me with a due date in the calendar on the dashboard. To me, this concludes the wish to see all assigned tasks in all projects. Thank you for your efforts.

I have a followup wish to see all tasks which have passed their due dates pulled in on todays date but with a thick red boundary to indicate that they need immediate action. That is probably best described in a new feature request?

**Comment by fguillot** [comment]
Now, there is a calendar for each user that display tasks for all projects where your are member.
