### ISSUE TITLE
subtask are not deleted when the main task is remove

### ISSUE THREAD

**Issue by alimouzin** [fguillot/kanboard#554]
Hello again
Apparently subtask are not deleted when the main task is remove.

I create a New task 'test' (it is task #1)
I add a subtask 'toto' to 'test'
I remove 'test'
I create a new task 'test2'  (it is also task #1)
subtask 'toto' is attached to 'test2'

It doesn't seem logical to me.

Arnaud

**Comment by mluepkes** [comment]
[Model/Task->remove()](https://github.com/fguillot/kanboard/blob/c1173765ae7b2ba116d8a263f2d3f3cde0438362/app/Model/Task.php#L51-60) only removes the task and corresponding files. Subtasks need to be added.

**Comment by alimouzin** [comment]
I must admit I didn't check if the subtask was in the UI or database after deletion. But as it appears again when I create a new task I supposed so.
It could be my installation but I didn't do anything special...

**Comment by mluepkes** [comment]
I couldn't reproduce your error, but as #553 shows you're also having other problems, I assume that it has to do with your installation of kanboard. I suggest you check the debug log and report back here with your findings.

**Comment by alimouzin** [comment]
Yeah I would think so also

**Comment by fguillot** [comment]
Subtasks are removed with a foreign key constraints.

**Comment by mluepkes** [comment]
Thank you
