### ISSUE TITLE
"Return to the board" can focus snap back to active swimlane?

### ISSUE THREAD

**Issue by jeffshieldsdev** [fguillot/kanboard#556]
1. I'm working in a swimlane further down on my Board and click on a task to edit it.
2. I edit my task, click save, and on the Task page click "Back to the Board".
3. I'm brought back to the board, but at the top of the page.  It'd be nice if focus went back to the swimlane I was working in.

Thank you.

**Comment by sparkles645** [comment]
+ 1 (not a huge issue the way it is, but would be alot less scrolling with the suggestion) - we have 37 swimlanes in one board - and some boards might end up having even more. :)

**Comment by sparkles645** [comment]
Found a decent workaround for this one by changing my work-flow a tiny bit - I click the scroll button on the mouse to **open a new tab** with the ticket/task I want to edit - that way, the tab with my whole board and all the swimlanes does not reload. =)

**Comment by fguillot** [comment]
@jeffshieldsdev It's now implemented in the last development version.
