### ISSUE TITLE
debug mode breaks kanboard via invalid logfile path

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#558]
After trying to find out for half the day why my dev installation is neither working in vagrant nor on an external server, I finally checked the php error log after ruling out all browser and code errors (duh). All js requests got blocked with 500 error responses, although the content was delivered. No 500 header was set in the code.

Error Log: http://pastebin.com/raw.php?i=vegvgpui

Modifying the logfile path in my config.php by prepending ```__DIR__``` like this ```define('DEBUG_FILE', __DIR__.'/data/debug.log')``` finally did the trick. If anyone else is having this problem, this should probably be changed in the config.default.php too.

Good night!

**Comment by fguillot** [comment]
I changed that in master. Thanks!
