### ISSUE TITLE
Older tasks not showing up in the calendar

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#563]
I had a bunch of tasks in Kanboard
I did a `git pull` and got the new calendar
It's empty despite the fact that some of my tasks have end dates.

**Comment by fguillot** [comment]
The current version of the calendar show only tasks with due date for the moment.

**Comment by oparoz** [comment]
Maybe it's a format thing? I'm using `31/03/2015`
![due_date](https://cloud.githubusercontent.com/assets/323220/5989293/25c50570-a983-11e4-9649-90168127f6b8.png)

**Comment by BlueTeck** [comment]
Its not a formatting thing, in the databease there are all unix timestamps. This one should appear in the calender. Do you see other tasks in the calendar?

**Comment by oparoz** [comment]
The calendar is completely empty. I've checked the database and I can see the timestamps in the `date_due` column.

**Comment by oparoz** [comment]
If I use a filter to only show tasks assigned to me, then I can see the tasks and when I put the filter back to "Everybody" then it stays, but as soon as I move away and come back then the calendar gets reset again.

**Comment by BlueTeck** [comment]
I could reproduce it, i will debug tomorrow.

**Comment by BlueTeck** [comment]
The problem is, that the calendar is not refreshing when switching the month. It is only pulling new data, if the filter is changing. So there is a bug in the merge of the calendar.
