### ISSUE TITLE
Sub-taks of closed tasks should not appear on the dashboard

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#566]
The parent tasks have been closed and don't appear on the dashboard, so the sub tasks should not either.

**Comment by fguillot** [comment]
Or close all subtasks when a task is closed.

**Comment by ashbike** [comment]
I think closing subtasks is better option. An warning message can be displayed saying all subtasks will be closed while parent task is closed.

**Comment by mluepkes** [comment]
:+1:

**Comment by oparoz** [comment]
I like @ashbike's suggestion. Gives people an opportunity to review the sub-tasks

**Comment by fguillot** [comment]
With the last development version, all subtasks will be closed when you close a tasks.

**Comment by oparoz** [comment]
Thank you.
