### ISSUE TITLE
Add Registration Feature 

### ISSUE THREAD

**Issue by levlaz** [fguillot/kanboard#570]
It would be cool if users were able to register. This should be a customizable setting but the use case that I am thinking of is when this is used in a large organization. It can be a pain to set up users, but it would be really nice to ask a new employee to go and register on this page. 

Slack allows anyone with an organizational email to register for an account, perhaps we could implement a similar feature. This will prevent random or unwanted people from signing up. 

Another option could be to simply have the administrator approve all registered accounts.

**Comment by vfarcy** [comment]
Sure !

**Comment by jdittrich** [comment]
1+

**Comment by jdittrich** [comment]
related for enabling the system to run without the admin setting up everything: 
#521 (Rights to create projects)

**Comment by sah-anshu** [comment]
+1

**Comment by pyg77** [comment]
Is this plugin still on the roadmap? 
We have a lot of requests for that feature :)

**Comment by fguillot** [comment]
FYI, I started the development of this plugin. An email confirmation will be necessary to create the account and optionally a domain restriction.

**Comment by jdittrich** [comment]
This is great to hear! Looking forward.

**Comment by fguillot** [comment]
The plugin is available here: https://github.com/kanboard/plugin-registration (works only with the dev branch of Kanboard at the moment).
