### ISSUE TITLE
CLI for Kanboard

### ISSUE THREAD

**Issue by ashbike** [fguillot/kanboard#571]
I was thinking of prototyping a command line client application for Kanboard. There is one available right now but that is server side and more suited for running heavy duty jobs or cron.

This proposed CLI will be client side, installed on user's own machine, will use existing JSON-RPC. The idea came from Jira CLI (http://goo.gl/vNX8y). This can be used for example:

- Adding tasks in bulk
- Updating multiple tasks at once
- Automation, integrating with other applications
- Create projects with set of predefined swimlanes, categories etc.

Do you think such a thing will be useful?

**Comment by mgro** [comment]
I do :)

**Comment by euneuber** [comment]
me too

**Comment by fguillot** [comment]
Yes, it's a good idea.

What programming language do you want to use for that?

**Comment by ashbike** [comment]
Not sure. But, it got to be platform agnostic. I was thinking about php only, may be Java? Other option could be python but I'm not very familiar with it.

**Comment by mluepkes** [comment]
As nearly everything else is PHP, I'd opt for a PHP CLI. :+1:

**Comment by euneuber** [comment]
It might not be the best choice for all, but **I also prefer PHP** (at least for a reference implementation, others might port it to a different language).

**Comment by ashbike** [comment]
Let's start with PHP and then we will see. I will try to prototype 2-3 commands to start with.

**Comment by AlgyTaylor** [comment]
:+1:  for CLI and PHP

It would be very useful for me

**Comment by fguillot** [comment]
Don't hesitate to post a link to your project when you will be ready.
