### ISSUE TITLE
Login loop in IE, works in other browsers.

### ISSUE THREAD

**Issue by ZegalPL** [fguillot/kanboard#572]
Hello. 
Im having problems with kanboard 1.0.11 on IE (tested on 11, 10 and 9). When i try to login i get  "username required" and "password required" messages, works on chrome, FF, android browser, it seems only IE is affected. Demo on kanboard.net works fine, so it has to be something with my setup. Kanboard is hosted on iis 8.5, php 5.5, windows server 2012R2. Web server is in DMZ behind TMG. 

could anyone here provide me with some insights on this matter? 

thanks in advance, 
Piotr Zęgota

**Comment by ashbike** [comment]
Just noticed an odd behaviour. I am running under XAMPP. When Kanboard resides right under webroot, IE shows this error. Else it works fine. For example:

http://localhost/ shows this error on IE 
http://localhost/kanboard works fine on IE 

FF & Chrome do not have this problem.

**Comment by ZegalPL** [comment]
That solved my issue. Added folder in directory i published from and put redirection on root. Peculiar.
