### ISSUE TITLE
Can't move task for other projects with lower ID

### ISSUE THREAD

**Issue by willianwrm** [fguillot/kanboard#573]
Hello,

I'm having trouble to move some tasks to another project: I have two projects, one with ID 1 and another with ID 2. I can move tasks from project ID 1 to project ID 2, but there is no way I can move from project ID 2 to project ID 1 - none exception is throw, but there is no projects to move to when I click in "move to another project".

Thanks in advance and thanks for the good work ;)

**Comment by willianwrm** [comment]
I found out what it was: the table 'project_has_users' has no entry for the project ID 1, so what I did to fix it is manually add something and voala, I can now move tasks to project ID 1 :)

**Comment by fguillot** [comment]
The dropdown on the page "move to another project" show projects where you are member. You have to be member of the project event if you are admin.
