### ISSUE TITLE
Inconsistencies in duplicate functions / transaction handling

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#575]
While working on expanding project duplication to contain swimlanes and tasks, I've run into differences between how duplicate functions handle transactions. 

For some models (e.g. tasks) the duplicate functions also duplicate their sub-models. This means they're starting transactions of themselves. Others only handle their own duplication and call on db->save directly.

My question now is, do I:
* refactor all models to only handle their own duplication and superset the submodel and transaction handling.
* work in some sort of improved transaction handling?

The latter would also include changes to PicoDB to include an inTransaction function and returns for startTransaction and closeTransaction.

I think a combination of both would probably be of most benefit for the project in the long run.

**Comment by fguillot** [comment]
For the Swimlane, just add a method `duplicate()` like other stuff (categories...)

The task duplication should be optional during project duplication, the user should be able to choose or not to duplicate tasks with a checkbox by example. So you can do it in two pass without modifying too much the current code:

1. Duplicate the project with all properties (one transaction: `ProjectDuplication::duplicate()`)
2. If the project is duplicated successfully, duplicate all task (`TaskDuplication::duplicateToProject()`)

**Comment by mluepkes** [comment]
I didn't get the idea of doing it in 2 passes, the rest was already implemented. I guess that's workable, although ultimatively I'd prefer the ability of doing it in one pass and do a rollback if task duplication fails. I'll implement it this way for now. Just need to include the checkboxes for selecting which parts are to be duplicated and I'll post a pull request.

**Comment by mluepkes** [comment]
Everything implemented, writing the unit test
