### ISSUE TITLE
Independent scroll for every column

### ISSUE THREAD

**Issue by felipestanham** [fguillot/kanboard#576]
When you scroll down you loose track of the columns' titles and if one column has many tiles it complicates ordering.

Please add a scroll for every column and keep the title fixed at the top (see trello.com for an example)

**Comment by sparkles645** [comment]
IMHO, this would make KB less user friendly.

**Comment by felipestanham** [comment]
I thought so the first time I saw this in trello.com but it really helps to see the column titles fixed at the top.

Also with individual scroll you are able to grab the last tile from a column while keeping the first tiles (or any desired range of tiles) of any other column. 
Example: try to move the first tile of one column to the one-before-last position of another column that has a scroll.

If this is not good for everyone, at least make the column titles stick at the top of the screen.

**Comment by euneuber** [comment]
is this compatible with swimlanes?

**Comment by sparkles645** [comment]
Haven't checked the Trello-functionality. Since the the titles of the columns are repeated with swimlanes --> If I can't see the titles above, I'll just scroll down to see the next repeat below. **How many tasks do you gave stacked in a single column in your board?** Is this board swimlaned or not?

**Comment by fguillot** [comment]
This feature is now implemented in the development version, each column can scroll independently. The board height is now the same height as the window.
