### ISSUE TITLE
LDAP is case-sensitive, creates new user if not consistent with prior login

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#578]
**Minor issue:**

Discovered that logging in as:

**m**y.**u**ser
and 
**M**y.**U**ser

both give access, but establishes different users within Kanboard.
LDAP with no proxy.

**Consequence:**
* New user has no rights
* If given rights, the user shows up twice (or more) in all lists - depending on *cAsE.VariAtIoNs* of user name.

I have expressed to our users that they need to be consisent when they type in their user-name.

**Comment by fguillot** [comment]
One solution can be to lowercase the username for ldap authentication through Kanboard.

What database type do you use? Sqlite, Mysql or Postgresql?

**Comment by sparkles645** [comment]
Sqlite

**Comment by fguillot** [comment]
I modified the code in the dev branch:

- By default all ldap username will be lowercase in the database to avoid duplicates.
- To enable the previous behaviour, set the constant `LDAP_USERNAME_CASE_SENSITIVE` at `true`.

I tested with ActiveDirectory and that seems ok, no more duplicates.
