### ISSUE TITLE
[BUG?] - RSS link to issue results in error "could not find in my database"

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#579]
**From version 1.0.11 January 10th, 2015** (perhaps already corrected, if so - sorry for duplicate)

**When accessing inside KB:**

http://**SERVER**/kanboard/?controller=task&action=show&task_id=61**&project_id=12**
 
**When accessing link found in RSS feed:**

http://**SERVER**/kanboard/?controller=task&action=show&task_id=61

**RESULT when accessing link found in RSS feed:**
 "could not find in my database"

**Comment by BlueTeck** [comment]
it was a bug should be fixed in the dev version  #543 #523

**Comment by sparkles645** [comment]
Closing (duplicate)
