### ISSUE TITLE
Can´t move tasks through columns.

### ISSUE THREAD

**Issue by mrender** [fguillot/kanboard#582]
I just installed KANBOARD but I can't move tasks. When I try to drag it, it just selects the content of the screen and does not understand it as something "draggable".
Was it a problem of installation of mine?
My website is hosted at Dreamhost, with PHP support.

**Comment by BlueTeck** [comment]
which Browser are you using?

**Comment by mrender** [comment]
Hi!!
Cynthia Pereira just helped me!
It was the App.js file that was corrupted. I uploaded it again and now everything seems to be fine!!
Thank you for your attention, BlueTrack!

**Comment by pythagorean** [comment]
I have the same problem.  Can you point me to where the app.js file is at?
