### ISSUE TITLE
Dropbox problem / internal error 1060, 500 internal error

### ISSUE THREAD

**Issue by gdumanoir** [fguillot/kanboard#583]
I have a problem with a dropbox storage.

When I first configured it, it worked well.
Then I did some tidying, moving file and directory inside the dropbox share using the linux owncloud sync client.

The client was unable to execute the changes it seems, and started to get errors : internal error 1060, 500 internal error.
Each time it scans the dropbox directory, it ends up with this error and stops the scan.

In the owncloud.log there are lots of this errors :

Debug	OC\Files\Cache\Scanner	!!! No reuse of etag for '' !!! cache: Array ( [fileid] => 7 [storage] => dropbox::0ef0t2zo64sum0jzb0qr1zjybgd7tbz/ [path] => [parent] => -1 [name] => [mimetype] => httpd/unix-directory [mimepart] => httpd [size] => -1 [mtime] => 1422810150 [storage_mtime] => 1422810150 [encrypted] => [unencrypted_size] => 0 [etag] => 54ce5c26e03de [permissions] => 31 ) data: Array ( [mimetype] => httpd/unix-directory [mtime] => 1422810188 [size] => -1 [etag] => 54ce5c4cebea4 [storage_mtime] => 1422810188 [permissions] => 31 ) 

What seems weird to me is the fact no file name is filled : No reuse of etag for ''

I have another dropbox share configured, and it is working well.
                    
Also, when I  check the dropbox share on the dropbox interface, the changes done with owncloud were correctly done.

I tried several things :
- erase content of oc_filecache table : no improvement
- configure a new dropbox application : no improvement
- erase completely the content of the dropbox share (using the dropbox website) : then the sync worked correctly. I then started to add my files again using owncloud, the problem reappeared....
Each file uploaded though the sync client had a 500 error, even if the file arrived correctly on the dropbox share...

When I try to click on the dropbox share using owncloud web interface, after a few second  I get the root of owncloud...

Would you have an idea of what is going wrong ?

Version : ownCloud 7.0.4 (stable)
I tried the client under windows and linux.

Thanks

**Comment by mluepkes** [comment]
Wait, what? I guess you posted to the wrong repository?!

**Comment by gdumanoir** [comment]
Oups, yes... sorry. I begin with github and I posted in the wrong repository....
