### ISSUE TITLE
LDAP Authentication (AD) not working

### ISSUE THREAD

**Issue by secZero** [fguillot/kanboard#584]
Hi guys, maybe I do something wrong, but I've followed the instructions at [LDAP Auth](http://kanboard.net/documentation/ldap-authentication), but kanboard doesn't authenticate against my domain controller.

Here is my config.php
```
<?php

// Enable/disable debug
define('DEBUG', true);
define('DEBUG_FILE', __DIR__.'/../data/debug.log');

// Enable LDAP authentication (false by default)
define('LDAP_AUTH', true);

// Credentials to be allowed to browse the LDAP directory
define('LDAP_BIND_TYPE', 'user');
define('LDAP_USERNAME', '%s@sub.domain.local'); // or 'KANBOARD\\%s'
define('LDAP_PASSWORD', null);

// LDAP server hostname
define('LDAP_SERVER', 'dc.sub.domain.local');

// LDAP properties
define('LDAP_ACCOUNT_BASE', 'CN=Users,DC=sub,DC=domain,DC=local');
define('LDAP_USER_PATTERN', '(&(objectClass=user)(sAMAccountName=%s))');
define('LDAP_ACCOUNT_FULLNAME', 'displayname');
define('LDAP_ACCOUNT_EMAIL', 'mail');

```
The debug.log tells me:
```
[debug] SELECT  * FROM "users"   WHERE "username" = ? AND "is_ldap_user" = ?    LIMIT 1
```

The file config.default.php is untouched, but there is no request at the DC and authentication on kanboard fails.

Any hints for me?

**Comment by mluepkes** [comment]
AD <-> LDAP is tricky in general. I suppose you put in the actual values for your subdomains in LDAP_USERNAME and LDAP_SERVER, right? If not, do so. 

Next is the account base. We are using Windows SBS 2011 and our account base looks like this: 

```define('LDAP_ACCOUNT_BASE', 'OU=SBSUsers,OU=Users,OU=MyBusiness,DC=[redacted],DC=local');```

From what I read it differs depending on your setup.

To find the correct BaseDN: http://bluecoat.force.com/knowledgebase/articles/Solution/HowdoIfindLDAPUserandGroupBaseDNforMicrosoftActiveDirectory

Hint: Use wildcards (*) on the user name.

**Comment by secZero** [comment]
That was a good hint ==> solved. :+1: 

Thank you!

**Comment by mluepkes** [comment]
The BaseDN? I've been fighting with that one for a while. Bookmark the link I posted!
