### ISSUE TITLE
Bitbucket Integration

### ISSUE THREAD

**Issue by revnode** [fguillot/kanboard#586]
I do most of my work on Bitbucket ( https://bitbucket.org/ ), it would be great to have the same integration as Github and Gitlab.

Thanks!

**Comment by fguillot** [comment]
I added the Bitbucket web hook in the current development branch based on Gitlab and Github hooks.

However, only commits message seems to be supported by their webhook, I didn't find anything about the issue tracker.

At the moment, only closing a task from a commit message is supported (tested only with git, should work with mercurial too).

The documentation: https://github.com/fguillot/kanboard/blob/master/docs/bitbucket-webhooks.markdown

**Comment by bastiao** [comment]
https://confluence.atlassian.com/display/BITBUCKET/Set+up+the+Issues+hook

How could this be integrated as well? Any ideias?

**Comment by fguillot** [comment]
@bastiao issues hooks are for bitbucket internal issues tracker, not for external software.

**Comment by bastiao** [comment]
you're right. I checked it later.

**Comment by bastiao** [comment]
maybe, if we can include a external applications to polls the issues by RESTful API. Anyway, this is not related with the issue. Thanks for the help.
