### ISSUE TITLE
Put branch and version or date in name of downloadable files.

### ISSUE THREAD

**Issue by tranquility-base** [fguillot/kanboard#587]
It would be helpful if the name of the download file included the branch, and either the version or date. For example, "kanboard-stable-2015-01-10" instead of kanboard-latest. This way, I can easily compare the filename on the download page with the filename in my download folder to see if my version is out of date.

**Comment by fguillot** [comment]
There is also packages for specific versions instead of latest http://kanboard.net/kanboard-1.0.11.zip etc...

**Comment by fguillot** [comment]
You can also call this url from a script with curl to know the last stable version `curl http://kanboard.net/version`.
