### ISSUE TITLE
[Info] Chrome Extension

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#588]
Hi all,

i wrote a little Chrome Extension to quick access boards for myself, maybe someone else is interested:

https://chrome.google.com/webstore/detail/kanboard-quickmenu/akjbeplnnihghabpgcfmfhfmifjljneh?utm_source=chrome-ntp-icon

Regards,
Timo

**Comment by fguillot** [comment]
Awesome, I added a new section "Related projects" in the readme: https://github.com/fguillot/kanboard#related-projects
