### ISSUE TITLE
[Q] Release Schedule

### ISSUE THREAD

**Issue by mluepkes** [fguillot/kanboard#594]
Quick question: Do you have a set release schedule? I'm just wondering when we can expect a new stable release. There are some changes in the current master that I'd very much like to get to our production environment.

**Comment by fguillot** [comment]
There is no release date yet.

I want to add a couple of feature, fix all remaining bugs and test again.

**Comment by fguillot** [comment]
I released the version 1.0.12 today.

**Comment by ashbike** [comment]
:+1:  :+1:

**Comment by BlueTeck** [comment]
:+1:
