### ISSUE TITLE
[Bug] add new Column to board

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#595]
Add a new colum:
![kb1](https://cloud.githubusercontent.com/assets/1961634/6103589/4b22dfee-b046-11e4-9444-d40c188b3dfa.PNG)
Will add the description as task limit:
![kb2](https://cloud.githubusercontent.com/assets/1961634/6103597/5ac40eb4-b046-11e4-95f0-90f4698aac7b.PNG)
![kb3](https://cloud.githubusercontent.com/assets/1961634/6103598/5ac42fd4-b046-11e4-8ba7-7607473f2787.PNG)
Editing the column does not show tasklimit or description:
![kb4](https://cloud.githubusercontent.com/assets/1961634/6103615/7f742708-b046-11e4-96d3-79c17c995d83.PNG)

**Comment by fguillot** [comment]
Fixed. Thanks.
