### ISSUE TITLE
[Bug] subtask text in board

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#596]
The  popup in the board shows status instead of title:
![kb5](https://cloud.githubusercontent.com/assets/1961634/6105495/00527a4e-b058-11e4-9bbf-1f98ab59d62e.PNG)
![kb6](https://cloud.githubusercontent.com/assets/1961634/6105496/0052cdf0-b058-11e4-8b1e-8f238832be77.PNG)

**Comment by fguillot** [comment]
Fixed. Thanks.
