### ISSUE TITLE
[Q] Day/Week Calendar View needed?

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#599]
Is the Day/Week View in both calendars needed? It displays only fullday entries for tasks?

Or month view should be default.

**Comment by BlueTeck** [comment]
Or we could leave it and the user could display an own web-ical in there.

**Comment by BlueTeck** [comment]
But I think only the month view should be other, or the month view should be default.

**Comment by fguillot** [comment]
I plan to add to add more stuff in the calendar. So I try different configs...

By example, I need to have the subtasks time tracking in the calendar and for that I need a day view. And maybe also the closed tasks with the start date/completed date. The user should have the choice to display different things.

The development branch is a constant working in progress, it's not definitive.

**Comment by BlueTeck** [comment]
:+1:
