### ISSUE TITLE
What does the id parameter refer to in a request

### ISSUE THREAD

**Issue by createS0ftware** [fguillot/kanboard#603]
What does the id parameter in this example refer to 
Request :
{
    "jsonrpc": "2.0",
    "method": "getTimezone",
    "id": 1661138292
}

?

Thanks

**Comment by BlueTeck** [comment]
it is a "random" number.

Wiki: id - A value of any type, which is used to match the response with the request that it is replying to.

http://en.wikipedia.org/wiki/JSON-RPC

**Comment by createS0ftware** [comment]
Thanks
