### ISSUE TITLE
Theme system

### ISSUE THREAD

**Issue by Zakarisz** [fguillot/kanboard#604]
Hello.
Is there any plan to add a theme system ?

**Comment by fguillot** [comment]
Not yet, it's not a priority right now.

**Comment by fguillot** [comment]
You have custom stylesheet now.

I don't plan to add a theme system right now. I already do that with another open software and people don't maintain their themes over the time.

**Comment by Zakarisz** [comment]
A custom stylesheet will probably be enough.
Thank you

**Comment by thob** [comment]
:+1:
