### ISSUE TITLE
getMembers doesnt Work 

### ISSUE THREAD

**Issue by IssaGithub** [fguillot/kanboard#606]
Hi, 
i try to use the Method getMembers.
Thats my json:
Str_Send_getMembers = "{"jsonrpc":"2.0","method":"getAllowedUsers","id":"1","params":[2]}"
 
in my resposne i receive an error Message: Method not found. 

Is "getAllowedUsers" still up to date?

thanks

**Comment by BlueTeck** [comment]
In the current dev Version this method does not exists, but there is getMembers Method. Please take a look into your jsonrpc.php file which method exists.

Doc:
https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getmembers

Api-Methods:
https://github.com/fguillot/kanboard/blob/master/jsonrpc.php

**Comment by IssaGithub** [comment]
ok,
im new with json/php. im using RPC  wit VB.net. 
So you said"In the current dev Version this method does not exists, but there is getMembers Method"
what do you mean by  "there is getMembers"?
Where is it? :-)

**Comment by IssaGithub** [comment]
how can i use it?

**Comment by BlueTeck** [comment]
In your Kanboard installation, you have an Endpoint, which is the jsonrpc.php. In this file are the methods specified, that could be used. (should be easy to read, even if you are not familiar with php).

I don't know which kanboard version you have. But in the development version here on github there is not getAllowedUsers Method, but there is a method that seems to be similiar called getMembers.

Which knaboard version are you using? The newest release 1.0.11?

**Comment by IssaGithub** [comment]
hi, 
look to the link you send me:
https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getmembers
there it says you Need to write:
"jsonrpc": "2.0", "method": "getAllowedUsers", "id": 1944388643, "params": [1]}

**Comment by IssaGithub** [comment]
ok, 
now i used: "get_Members"
and it works :-)

So you Guys Need to correct the Documentation!
thanks!

**Comment by BlueTeck** [comment]
Yes the documentation is wrong here...

**Comment by IssaGithub** [comment]
thanks for you help!

**Comment by fguillot** [comment]
I updated the example in the doc.

**Comment by IssaGithub** [comment]
Hi,
i have a question about the table Project_avtivites.
i have an more than less old database-backup.
if i look to the table "Project_activites" i see the colum "date_creation".
It seem for me, that the "date_creation" value only gives me the day of the
month.

how can i select the colums today.

Thanks
Issa Zaytoun



2015-02-11 2:19 GMT+01:00 Frédéric Guillot <notifications@github.com>:

**Comment by IssaGithub** [comment]
Hi,
i have a question about the table Project_avtivites.
i have an more than less old database-backup.
if i look to the table "Project_activites" i see the colum "date_creation".
It seem for me, that the "date_creation" value only gives me the day of the
month.

how can i select the colums for today?

Thanks

2015-02-10 11:00 GMT+01:00 Timo <notifications@github.com>:
