### ISSUE TITLE
Get_Members

### ISSUE THREAD

**Issue by IssaGithub** [fguillot/kanboard#607]
Hi,
i have a generall question.
Is it posible to have members withoud an "User_iD"(integer).

When i using get_Members, i dont receive any id of the members. 
thanks

**Comment by IssaGithub** [comment]
i can only read the names, but no id's(i Need the id in order to create an comment)

**Comment by BlueTeck** [comment]
The Key is the userid.

I already proposed a change #461, but @fguillot doesn't want it.

**Comment by BlueTeck** [comment]
But also this is written in the docs:

- Result on success: Key/value pair of user_id and username

https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getmembers
