### ISSUE TITLE
Task age and time spent in one column

### ISSUE THREAD

**Issue by ashbike** [fguillot/kanboard#608]
In our internal implementation, two things we needed to track: 1. How long a task is open 2. How much time a task spent in a column (both in days).

I did a prototype which can be seen at: http://goo.gl/Y5PrgO. Screenshot below. There are tooltips on those little boxes next to the "Assigned to XXX" text on task board. The time spent in a column resets if the task is moved to another column.

Similar feature is available in other software, http://goo.gl/kptUdK . Also, I was referring to the slides at http://goo.gl/j6fTk9. They also propose something like this.
Kanboard code is so nicely organized, I had to add just 10-12 lines to have this feature. Let me know if you think this is useful. Then I can clean up the code and request for a pull. 

![image](https://cloud.githubusercontent.com/assets/7455931/6134734/75ff21c0-b189-11e4-9a52-773b842c18d5.png)

**Comment by sparkles645** [comment]
That's cool!

**Comment by fguillot** [comment]
It's definitively useful, you can send a pull-request :)

**Comment by BlueTeck** [comment]
Idea: display hours, if the number of days is lower then 0.

**Comment by ashbike** [comment]
Was thinking about that. How about <1h, NNh if less than <24, and finally days?

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
I merged your pull-request.

If you want to display the hours, just send another pull-request :)
