### ISSUE TITLE
createComment

### ISSUE THREAD

**Issue by IssaGithub** [fguillot/kanboard#609]
Is there something wrong with this:

{"jsonrpc":"2.0" , "method" : "createComment" , "id" : "1" , "params" :{"taskid" : "1" , "userid" : "1" , "content" : "Hohenwart_Schule_Schneider #1"}}

Because i get this Response:
{"jsonrpc":"2.0","id":"144","error":{"code":-32602,"message":"Invalid params"}}

**Comment by BlueTeck** [comment]
Hi,
your parameters are wrong, try

```
{"jsonrpc":"2.0" , "method" : "createComment" , "id" : "1" , "params" :{"task_id" : "4" , "user_id" : "1" , "content" : "Test"}}
´´´

**Comment by IssaGithub** [comment]
oh,
what a shame :-)
thanks a lot!
