### ISSUE TITLE
Add closed task in the Cumulative flow diagram

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#611]
It could be great to add closed tasks in the "Cumulative flow diagram". Let me explain why.

In several use cases, the last column is called "Done" or "Finished". Once a task is put in this column, it is (automatically or not) closed. Therefore, in the "Cumulative flow diagram", it seems that not much tasks have been done, but a lot of them are still to be done. In reality, a lot of tasks are already closed and finished, but doesn't appear in the diagram.

**Comment by fguillot** [comment]
The CFD include all tasks now (in master).
