### ISSUE TITLE
Getting notification/events from Kanboard Server 

### ISSUE THREAD

**Issue by IssaGithub** [fguillot/kanboard#613]
Hi,
is it possible to get notifications by the Server, in the case that a Task has been changed?
For example the title has been changed?

thanks

**Comment by IssaGithub** [comment]
P.s. i dont mean email notification, but something like an RPC Response!

**Comment by BlueTeck** [comment]
A few days ago I implemented the API method getProjectActivity with the paramter start and end. With this you could get the activitys for example title has changed. (like the Activity Stream in Dashbard).

**Comment by BlueTeck** [comment]
-> it is not pushed by the server, you have to pull it

**Comment by IssaGithub** [comment]
Thats nice : )
Am 12.02.2015 11:17 schrieb "Timo" <notifications@github.com>:

**Comment by fguillot** [comment]
You can also use the webhooks: http://kanboard.net/documentation/webhooks

When a task is modified or created the application call an url on your server.
