### ISSUE TITLE
Unique identifier / ability to use some tasks across multiple projects

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#62]
I'm considering using kanboard to manage student research projects in a university, and I'm thinking I could use multiple kanboard "projects" to represent the various aspects of a student's research project (ethics application process, funding process, thesis writing process, etc.).

As such I think it would be great to be able to create tasks that are "global" or "shared" within multiple kanboard projects. Basically like a soft symlink, not an independent "duplicate" like issue #54.

Maybe we could imagine something like a serie of checkboxes in the task's properties:

```
Visible in the following projects:
  [x] Foo (current project)
  [ ] Bar
  [x] Baz
  [x] Ponies
```

**Comment by levlaz** [comment]
This is an interesting idea, I am curious what the implications are for the task status. If they are not full clones and instead referencing the same card, does moving the card from work in progress to done move it on all of the boards? What about the case where the boards do not have the same column names?

**Comment by fguillot** [comment]
I don't see how it can be implemented without changing the data model. The column_id, position, swimlane_id of tasks are unique to each project.

**Comment by fguillot** [comment]
Closing this ticket because that will require too much changes.
