### ISSUE TITLE
Change data path from config file

### ISSUE THREAD

**Issue by crash5** [fguillot/kanboard#620]
Hi,

please add a variable to the config file to change the default "data/" path to another.

Now the path is only changed with edit all of these files:
- \app\constants.php
- \app\Core\FileCache.php
- \app\Model\File.php
- \app\ServiceProvider\LoggingProvider.php

PS: \app\constants.php is bypassed if the "DB_FILENAME" defeined in config.php

**Comment by fguillot** [comment]
You can already change the location of data stored in `data` by using those constants:

- `DEBUG_FILE`
- `FILES_DIR`
- `DB_FILENAME`

The class FileCache is not used actually.

I could also add another constant like `DATA_DIR`...
