### ISSUE TITLE
[Q] Has "task age & time spent in column" replaced view of "Complexity" on the Task?

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#621]
**Current development version:**

* We use a decided range of numbers and the Complexity-field as an indication of priority. 
* 1' are most important, 4's are of lesser importance and so on.

With implementation of #608 - it appears that the Complexity number no longer views on the task itself. There is no way of filtering based on Complexity either.

This makes this dimension very hidden - you have to visit each task to reveal the value set in the complexity field.

We will have to revise our system - and that's fine - but just checking that the removal of the complexity indicator on the board has been done **on purpose** before we do.

**Comment by ashbike** [comment]
I think it's just went missing unintentionally due to refactoring the Board for collapse/expand tasks feature. 'time spent on column' and 'complexity' was coexisting earlier.

**Comment by fguillot** [comment]
I just removed temporarily the complexity because there is too much stuff on a card now.

Don't worry the complexity will be back, I just need to find how to display everything correctly.

**Comment by sparkles645** [comment]
* I fully recognize the "crowded" card situation.
* Some sort of filter function would perform just as well as an indicator on the card itself.

I'm no coder, but a "drag bar" for filtering values within a range - like Price, eg: 

$ 0
<--------------------||||LOW|||---------------------------------|||HIGH||||------------->
                                                                                                      $ 100

would perhaps do the trick - but I do not know how to implement.

**Comment by ashbike** [comment]
Just a thought. Since there will be only one category, the complexity can come before it. (red circle). Or the time spent stuff can move to the footer (blue arrow) and complexity can come there. My monitor is 1366x768px and I put 9 columns to see how it comes along. It looks good!

![image](https://cloud.githubusercontent.com/assets/7455931/6203932/a6c15f84-b55e-11e4-80b4-20fb4eeec582.png)

**Comment by sparkles645** [comment]
:+1:

Our monitors run 1920 x 1080 - we have established a practical limit of MAX 12 columns.

**Comment by fguillot** [comment]
I restored the task complexity, now it's displayed on the bottom left. And the task age is displayed on the top right.

I also possible to scroll horizontally when the number of columns is too high. So there is no limit anymore on the number of columns. I tested with several screen resolution 1366x768, 2880x1800 and my ipad retina.

**Comment by ashbike** [comment]
:+1:

**Comment by ashbike** [comment]
After playing with it a bit, somehow I'm not getting very comfortable with the horizontal scroll. I understand that too many columns can not fit into an window. At the same time, looking at the whole board has it's value. 
May be a configuration option per user or global? Something like, show scrollbar if columns > 10.
