### ISSUE TITLE
Trello import script

### ISSUE THREAD

**Issue by matueranet** [fguillot/kanboard#624]
Hi,

I have created an import script to help easily move from Trello to Kanboard. Any suggestions are welcome. If it's mature enough, it might be an idea to add this to the kanboard cli commands? Or maybe we can set up a migration guide that mentions this tool?

https://github.com/matueranet/kanboard-import-trello

Thanks for creating a great product!

**Comment by BlueTeck** [comment]
Maybe @fguillot could put it here: https://github.com/fguillot/kanboard/blob/master/README.markdown#related-projects

**Comment by fguillot** [comment]
Nice, I added your project in the readme file.

I didn't test your script but if that works correctly, I have no problem to add this to the Kanboard cli.

**Comment by matueranet** [comment]
Great thanks! I might have a look at creating a pull request in the feature for the Kanboard CLI. It would probably mean rewriting the script, because on the Kanboard CLI you can access the database directly, no need for the JSON RPC.
