### ISSUE TITLE
Read access for a project to all kanboard users

### ISSUE THREAD

**Issue by LiaraAlis** [fguillot/kanboard#625]
Hi,

it would be nice if it were possible to allow read access to a project for only registered users in kanboard and not the whole world.
I think it would be a good way to extend the "public access" area with a checkbox "only for users".

What do you think about this?

Regards from Germany,
Alexander

**Comment by deviloper** [comment]
And if we could set read-only users like in photo?
![proposta](https://cloud.githubusercontent.com/assets/5602328/6412800/ce59902e-be88-11e4-92ff-ad1077bf4198.png)

**Comment by LiaraAlis** [comment]
Hi,

this could be a solution for this, but it is complicated, if we have many members.
But I think, it would not be wrong if this feature is given.

**Comment by deviloper** [comment]
We could have a special "Everyone" row in user list managing general access authorization with the "Access denied" role instead of "Project manager" one.
I don't know how actually roles are implemented in database, so this solution could be hard to apply..

**Comment by macce** [comment]
I really like devilopers proposal from Feb 27. Allowing read-only access for people from other parts of the department so they can follow the development.

Another sensible role could be "Comment-Only Member".

**Comment by tekuton** [comment]
i would like to support this request.

**Comment by BlueTeck** [comment]
:+1: good idea

**Comment by timjcraig** [comment]
Comment-Only member would be great addition to allow project stakeholders to view project progress and comment on tasks.

**Comment by satisfiser** [comment]
We are getting ready to deploy Kanboard and yes a read only option would be perfect.  Our IT staffers would have access to update the projects; but if someone from outside of IT wanted to inquire about a project we could have them log in and look at the project w/o being able to modify it (which is currently a possibility).

**Comment by fguillot** [comment]
There is now a new role "Project Viewer" with read-only access available in the development branch. You could try this feature and report potential bugs if you would like.

**Comment by macce** [comment]
Great! Thanks!

Brgds,
Marcus

**Comment by deviloper** [comment]
Thank you!!

**Comment by creecros** [comment]
https://github.com/creecros/opencomment

Comment-only functionality, tested for over a week, works. Could use help making a nice package with plugin like qualities if anyone wants to tackle.
