### ISSUE TITLE
Collapse and Display the Swimlane after the Backlog

### ISSUE THREAD

**Issue by megacampus** [fguillot/kanboard#630]
Hi, 
Will be nice to have the Swinlane after the Backlog, so the Backlog will be a huge column with all the Issues because right now the Swinlane divide them.
I believe this will improve the drag and drop funcionality from the Backlog list to any  Swinlane like a Release 1.0, Release 1.1, Release 1.2

Will be nice to colapse the Swinlane becase the size of the screen, so the user can have multiple Swinlane and he expand the one his working on if not the user needs to scroll up and down multiple times.

I hope this improve your product, By the way it is very simple and practical. Congratulations!!!

Ronny Torres.

**Comment by BlueTeck** [comment]
It is already in the development version.

**Comment by fguillot** [comment]
You can collapse column or swimlane and you can enable/disable individual column scrolling.
