### ISSUE TITLE
Calendar does not display the tasks

### ISSUE THREAD

**Issue by ashbike** [fguillot/kanboard#631]
Though these tasks have target dates.

![image](https://cloud.githubusercontent.com/assets/7455931/6223683/05cc2b26-b695-11e4-9679-61f30a4c8426.png)

**Comment by fguillot** [comment]
It's weird, that works for me, did you update to the last master?

**Comment by ashbike** [comment]
Sorry, I forgot the mandatory-on-dev-branch 'composer install'... After updating picodb and simple-validator they are showing up.
