### ISSUE TITLE
[FR] Interactive calendar

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#632]
I'd like to be able to change the end date of a task by simply dragging and dropping it on another date.

Bonus: The drop target should match the user's availability. If he only works Tuesdays and Thursdays, then a task can only be moved to one of these days

**Comment by BlueTeck** [comment]
you could already change the due date by drag and drop.

**Comment by oparoz** [comment]
Ah, you're right. So, it's broken on the one which is on the dashboard.

**Comment by fguillot** [comment]
I just activated the drag and drop to change due tasks for user calendar.

**Comment by ashbike** [comment]
Very nice. :+1:

**Comment by oparoz** [comment]
Works, thanks!
