### ISSUE TITLE
Compact Task Board View

### ISSUE THREAD

**Issue by megacampus** [fguillot/kanboard#634]
Hi 

Just for your consideration,

The Kanboard needs a compact task board view to improve its task management so the user can see alot of tasks in a small space and if the user move the mouse over a task it expands with all the infromation its has as the task box appears in the current version. 

The Task Title  should be truncated to a max of to 2 rows in the task box, so if the user also applied the Browser zoom the magic will appear the user will see arround 50 tasks at the same time in the screen without scrolling.

Regards,
Ronny Torres,

**Comment by fguillot** [comment]
It's already in the dev version, you can "stack" cards from the dropdown menu or by using the keyboard shortcut "s".
