### ISSUE TITLE
Cannot leave task unassigned on creation

### ISSUE THREAD

**Issue by matueranet** [fguillot/kanboard#636]
I am running version 1.0.11 and I have found that I am required to assign a new task to a user when I create it. But when editing the task I can update it to unassigned. I'd like to be able to set it as unassigned on creation also. Is this a bug, or am I overlooking something?

**Comment by BlueTeck** [comment]
feature see #436

**Comment by matueranet** [comment]
Ok, thanks. Wasn't clear to me from the UI.
