### ISSUE TITLE
Card quick action menu is not working in collapsed mode

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#637]
When a card is show in full, we have access to a very convenient quick action menu when clicking on the task number.
When we "collapse" the board, clicking on the task number does the same thing clicking on the task name does, it redirects the user to a task editing form. It should be fixed to behave the same way as in the standard mode. Not all actions would be necessary as some require to see the whole card before being able to make a decision, but it would probably be simpler to include all of them to begin with.

Also, the tool tip is wrong, it should say something like "Access menu"

**Comment by fguillot** [comment]
I added the dropdown menu in stacked mode.

**Comment by oparoz** [comment]
Merci!
