### ISSUE TITLE
[UI] Horizontal scroll - feedback/feel?

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#639]
Been playing around a bit with **current dev**

#First impressions:
* the horizontal scroll makes me less efficient and I feel like I've lost the overview-"feel".
(Is it just me?)

* we live happily with v 1 0 1 1 and a practical max limit of 12 columns (rarely that many) with 1920 x 1080.

**Can horizontal scroll be optional - for each board/Project (not forced)?**

I see practical use for the horizontal scroll, but only for maybe 5 % of our boards/Projects (we have 20-something Projects/boards)

**Comment by lathan** [comment]
On my 1366x768 laptop, adding just one more column (5 total) puts it partially outside the screen now. I'd much rather I didn't have to scroll for this.
![oops](https://cloud.githubusercontent.com/assets/1893345/6323474/1b794e96-bb2b-11e4-9fd6-9cf94f93acd5.png)

**Comment by sparkles645** [comment]
Here example w/ 1920 x 1080.
* Really can't get comfortable with the forced horizontal scroll
* Previous setup was better, IMHO.

Example - we have a board listing **months of the year** for showing interdepartmental events/meetings and who's responsible for making the nececcary arrangements:
![example](https://cloud.githubusercontent.com/assets/10092252/6331575/4114755e-bb80-11e4-9dd1-0bebcd1dd4f1.png)

**Comment by ashbike** [comment]
We are also having the same problem, not being able to have the complete view. I created a small patch for this (but I do think it could be done with much less code, thus cleanly) and submitted a pull request. It basically toggles between this new and old behaviour.

**Comment by sparkles645** [comment]
@ashbike:
* Does it discriminate / toggle for **each Project** or does it toggle **globally for all projects**?
(the first would perhaps be is of preference?)

Example - from our use: 
I see maybe **one-out-of-twenty** something Projects where we could use the scroll feature (process with a ridiculous amount of steps)

All of our other Projects work great with the "old behaviour".

**Comment by ashbike** [comment]
It's global as of now. But that should not be a problem since just hitting 'c' you can toggle.

**Comment by ashbike** [comment]
I have a setup running on our test server http://goo.gl/PJD5pr. Check 'Test Project 1'

**Comment by sparkles645** [comment]
* Checked it out.
* Worked great. :+1:
* Personally I could live happily with this solution.

* However, my **concerns**, and thus wishes to **"predetermine"** / **child-proof** the board behaviour a little bit - is in order to take considerations for some of our weaker users. 
* All of our users can not be entitled as "computer whizzes". Though willing and eager to learn / contribute, the bar should not be raised too high (at least not all at once).
* So far, KB is a real success in terms if UI / intuitive interaction.

**Comment by ashbike** [comment]
That's right. best part of Kanboard is, it's simple. Another menu item/hot key will definitely add functionality, but also makes it one level geeky :smile: .

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
I merged/improved the pull-request of @ashbike. You can toggle the compact mode by using the keyboard shortcut "c" or by using the dropdown menu.

In compact mode you might have some text overlapping if there are too much stuff on the card.

**Comment by sparkles645** [comment]
What is set as the **default**? 
Horizontal scroll or "compact / locked column mode"?

**Comment by ashbike** [comment]
By default it's horizontal scroll.

**Comment by sparkles645** [comment]
Just me thinking it should be the other way around?
That is: **Compact mode as default**, horizontal scroll to be activated by 'c'.
Just trying to consider 'what mode is used most often'?

**Comment by sparkles645** [comment]
This is preserved in 1 0 1 3 - both with hotkey and as menu item - closing this one.
