### ISSUE TITLE
Responsive/widescreen layout, or task properties in a sidebar

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#64]
It would be nice if kanboard used my screen space more elegantly for the following pages:

* "Settings" (?controller=config)
* Task properties view:
 * ?controller=task&action=show
 * ?controller=task&action=edit
 * ?controller=task&action=duplicate

At 1920x1080 for example, those pages use the full height of the screen but only ¼ of the width. This space could be divided in responsive columns/sections (with CSS media queries above certain resolutions). It wouldn't change much to the behavior, but it may look nicer and a bit more balanced :)

**Comment by fguillot** [comment]
Now we have popover and many tooltips on the board. I think it's good enough right now, I would like to avoid adding to much complexity in the current code.
