### ISSUE TITLE
Connecting to a remote MySql Server

### ISSUE THREAD

**Issue by createS0ftware** [fguillot/kanboard#640]
i get a PDO driver error when trying to connect to a MySql server . I don't have the details to hand at the moment but i would like to know if this is a known bug 

Thanks

P.S. I will upload the error details later today

**Comment by ashbike** [comment]
We connect to non-local mysql. It works fine.

**Comment by crash5** [comment]
What is the error message? PDO MySQL driver is istalled on the system?
