### ISSUE TITLE
Installation on yunohost

### ISSUE THREAD

**Issue by mbugeia** [fguillot/kanboard#641]
I've made a package to install Kanboard on [Yunohost](https://yunohost.org), you can find it [here](https://github.com/mbugeia/kanboard_ynh) you can add it to documentation if you want.

Installation can't be easier (sorry screenshot are in french):
![2015-02-19 16_58_52-yunohost admin](https://cloud.githubusercontent.com/assets/6364564/6270409/1597e646-b85a-11e4-97af-b3b5b2a6b286.png)
![2015-02-19 16_59_28-yunohost admin](https://cloud.githubusercontent.com/assets/6364564/6270411/19f9a54e-b85a-11e4-83da-eb813c0457f7.png)

click install and that's all the configuration you need.

Kanboard integrates very well with YunoHost, it's configured to use yunohost's mysql database and reverse proxy for authentification.

**Comment by fguillot** [comment]
Nice!

I added a link to your package in the faq https://github.com/fguillot/kanboard/blob/master/docs/faq.markdown#how-to-install-kanboard-on-yunohost and in the readme https://github.com/fguillot/kanboard#related-projects
