### ISSUE TITLE
[UI] Dropdown not visible

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#642]
On the last Task in a column, the dropdown is not fully visible, only after scolling
![kb1](https://cloud.githubusercontent.com/assets/1961634/6284729/9aa7846a-b8f3-11e4-9ce8-3703c7759d5d.PNG)
.

**Comment by fguillot** [comment]
Duplicate with #635

**Comment by BlueTeck** [comment]
ah okay
