### ISSUE TITLE
Tagging tasks - a prototype

### ISSUE THREAD

**Issue by ashbike** [fguillot/kanboard#646]
We started missing tagging/labelling feature in Kanboard :smile:. Tried to come up with an implementation.

There is a basic version running on our demo setup http://goo.gl/Y5PrgO. You can add/edit tags, and they show up on board. No fancy tag input ui as of now. Just put your tags separated by comma. Tags can only contain a-z, 0-9, . <dot> <whitespace>, - <hyphen>,  _< underscore>. Always comma separated and lower case. It will remove all special characters, empty tags etc. Screenshot below.

### Caveat 1

* We already have colors and categories in Kanboard. They are system defined, and one can be selected at a time. 
* Tag/labels are user defined can have multiple values and somewhat free form.

As we see it, they complement each other.

*Note: In our implementation we color coded tags. It's not dynamic, rather controlled by css. You can specify common tags with their color codes in css. However, with tasks already colored, the board gets unpleasantly colorful. :smiley: .  

### Caveat 2

About the implementation, we thought of doing it in couple of ways. First choice was to do it in very formal way, normalized data model etc. One TAGS table, one TAG-TASK mapping table. But implementation got too complex very soon. Two more tables to join and lack of an standard aggregate functions to simplify things, extra queries while inserting, deleting etc. etc. It would have offered good flexibility, but then we thought if we really need that kind of complexities. Finally aborted. [ https://github.com/ashbike/kanboard/tree/tagging-orig ]

Other option was very simple, keep tags comma separated and put in the task table itself. WIth some string manipulation and stereotype queries, most of the functionalities can be achieved. Tag based grouping by can be done at PHP level. Not at database level. There will be some limitation but 90% can be achieved. So we took this route. [ https://github.com/ashbike/kanboard/tree/tagging ]

![image](https://cloud.githubusercontent.com/assets/7455931/6315073/821b92ea-ba1c-11e4-8c9f-8b87ee799590.png)

**Comment by oparoz** [comment]
That looks really good and would be very useful when using hooks. but I'm a little bit worried about robustness. How about storing something like a serialized object?

About colours, I think it could work quite well if the main colours were replaced by shades of one colour per example, but overall, it's not too shocking. Pastel colours could maybe be used for the main tasks.

**Comment by BlueTeck** [comment]
Looks nice, but i think categories could be removed then, and it should be possible to filter/search by tags.

**Comment by ashbike** [comment]
@oparoz you mean serialize the tag array as json and then store? Most tagging input libraries take comma delimited tags, that's why i kept it csv.

@BlueTeck Yes, filter/search should be there. But, I didn't implement it since I do not know it's future :smiley: . 
About the category, well, it may be redundant unless you want to have some system defined values.

**Comment by fguillot** [comment]
Nice job :)

- Categories are there, so I don't want to remove this feature, it's actually used by people.
- Tags can be complementary
- I don't think we need to serialize this data, CSV format seems fine, there is no need to make an extra sql query to display all tags for a task.
- However, we should be able to search for tasks based on tags and that need to be fast enough. Searching in the tag field with a LIKE operator might slow because you will do a full table scan.
- The tag label should not be restricted with alphanumeric characters, people would like to use their own language (French, Portuguese...).

I don't know what is the best solution, looking in other open source project might interesting to find some inspiration.

By the way, how do you apply a color to a label?

**Comment by ashbike** [comment]
* I think LIKE will not be a problem practically since number of rows will not be that high. For example, I just tried a count(*) with a like match of 3 words in 5 words scenario on 520,000 rows and 1,200,000 rows on my desktop mysql (default xampp installation) and get .450ms and 1.1s respectively. without LIKE it was .150 and .400ms. 
* Tag labels can be anything. Except perhaps a few delimiters like , ; | etc.
* These colors are defined in css for now. It's a set of defined css classes like: .color-<tagname>. However they can be made like github. Right now there is no tag management as such. You type and you have a tag. I didn't like the tag colors much since there is already a color associated with a task.

The other option may be, make the category a multiple choice. That may simplify everything.

**Comment by sparkles645** [comment]
> Categories are there, so I don't want to remove this feature, it's actually used by people.

**Very much so.** :pray:

:+1: **tags**, but as complementary.

**Comment by sparkles645** [comment]
Perhaps auto-suggest based on previously entered tags in the Project**?**
![20150224221030](https://cloud.githubusercontent.com/assets/10092252/6359330/8fa81d5e-bc72-11e4-8e80-3b1b24bcffbe.gif)

**Comment by fguillot** [comment]
There is also some edge case with the CSV field method, by example if you have a tag "user" and another tag "user interface" and you want to get all tasks with the tag "user" by using "LIKE %user%" you will have the tasks tagged "user interface" too.

Basically, I think there is 3 methods to store the tags:

1. The CSV method (everything in one column, super easy to implement, autocomplete harder to implement)
2. 3 tables: "tasks", "tags" and "tasks_tags" as a junction table (slower insert but ok, more complex, works in all case, should be fast with some index)
3. A table "tags" with a foreign key "task_id" to the task table (not perfect but can work)

**Comment by ashbike** [comment]
@fguillot  
Yes. I actually removed that possibility by doing LIKE ',mytag,' . 
For autocompletion: I concatenated tag columns and then did a word count. (str_word_count()... in php space). That gives me an Associative Array with tag names in index and number of occurrence in values. So, I can use named keys for autocompletion, and the whole array to show how many tasks under each tag.

I actually started off with # 2 but the queries got very complex and I had to create views and all. (Perhaps others can simplify it) .

**Comment by fguillot** [comment]
@ashbike if you have a working prototype with the "cvs method", you can send a pull-request. So it will be easier to test/improve.

**Comment by ashbike** [comment]
@fguillot I sent a pull request.

**Comment by dbinagi** [comment]
@ashbike this was an awesome feature, is this expected to be added soon?

Thank you in advance.

**Comment by reachingmike** [comment]
Hoping this can be implemented - tags would be a great addition.

**Comment by mtruijen** [comment]
I hear tag, label, category. You tag or label a card with a category. A label is a way of categorization. Not sure if we need labels, tags in addition to categories. We simply need the ability to tag/label multiple categories to a card.

**Comment by peripatetic-sojourner** [comment]
@mtruijen Right now, you can have automatic actions triggered based off of categories. If there is no distinguishing between tags and categories, how should those those automatic actions be handled? What happens if there's a conflict between actions? I think that alone provides good reason to make them separate, even if their purpose is similar. I think they are more like subcategories.

@fguillot Are you wanting this as multiple db tables, since it leaves the most flexibility?

**Comment by fguillot** [comment]
Yes the tags feature will use multiple tables but there is so many other things to improve before.

**Comment by peripatetic-sojourner** [comment]
@fguillot do you have a list of priorities or a roadmap lying around? Or do you have a way to chat (e.g gitter.im) or irc?

I would like to help and it sounds like you have a plan for where this is going.

**Comment by golharam** [comment]
+1 for multiple tags/categories.  Is there any expected ETA for this?

**Comment by menegrete** [comment]
+1 for multiple tags/categories

**Comment by ptman** [comment]
Postgres would have arrays that could be used instead of the csv-method. But really a join-table would make sense. Tags/labels would be very useful

**Comment by fguillot** [comment]
There are many ways to implement tags, I opened a new issue concerning the implementation in the user interface #2331

**Comment by fguillot** [comment]
Tags are now available in the development branch.
