### ISSUE TITLE
Updating kanban

### ISSUE THREAD

**Issue by labo-css** [fguillot/kanboard#648]
Hello, i may be a bit stupid tonight but i didn't see how i can contact the author of this marvelous script, so i post here.

How i can update kanban from 1.0.11 to 1.0.12, i didn't see any documentation about updating an existing installation. Should i just copy and paste all files on my server and then update the config?

Thanx for your time.

**Comment by sparkles645** [comment]
Documentation of upgrade here:
<http://kanboard.net/documentation/update>

**Comment by fguillot** [comment]
Basically, you just have to backup your data before and then copy the files like described in the documentation.
