### ISSUE TITLE
[Discuss] More Keyboad Shortscuts in Board View

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#649]
The new shortcuts are really nice! What about more?

For example for the board actions:
 Collapse tasks (already binded "s")
 Search 
 Completed tasks
 Activity
 Calendar
 Analytics
 Configure

Or is it to much?

**Comment by fguillot** [comment]
I think the next step for keyboard shortcuts will be to navigate through the task on the board with the arrows and j k.

Be able to select multiple tasks can be useful too, example ctrl+shit+a to select all tasks in one column and move them to another column. Same thing with ctrl+mouse click.

**Comment by BlueTeck** [comment]
Yes that is an important step for keyboard shortcuts, if you could select tasks via keyboard.

**Comment by ashbike** [comment]
This is useful for bulk operations too. Like category/color change.
