### ISSUE TITLE
Option to send notifications only for assignee

### ISSUE THREAD

**Issue by fabdelgado** [fguillot/kanboard#652]
Hi, we are using kanboard for our projects.
We have been looking for some way to help get emails only to members when they are selected for a task, right now notifies all tasks in board.
Is this option could be added in a new update?
I await your response.
thanyou

**Comment by fguillot** [comment]
If I understand correctly, you want to receive email notifications only for the assignee, right?

**Comment by fabdelgado** [comment]
Exactly, notify the user that a new task.

**Comment by fabdelgado** [comment]
@fguillot  This feature is ready?

**Comment by fguillot** [comment]
nope

The notifications code will be refactored to take into account several feature requests, but also to be more flexible and send more relevant notifications.

**Comment by fabdelgado** [comment]
Ok, thankyou

**Comment by databigot** [comment]
So, I'm trying to solve this too by hacking something together.  
Originally I attacked the Notification code, but now I'm having second thoughts:

I'm wondering if this could be solved by creating some actions such as "app/Action/NotifyAssignee" and "app/Action/NotifyAdmin" which could be triggered by setting up Automated Action on Event TASK::EVENT_ASSIGNEE_CHANGE.  

What do you think?

**Comment by fguillot** [comment]
@fabdelgado It's now implemented in the development branch.

**Comment by fabdelgado** [comment]
Who is development branch for download?
See master.

**Comment by fabdelgado** [comment]
Tested is ready, in that version it will be included?
