### ISSUE TITLE
My tasks don't display tasks from 'Done' column

### ISSUE THREAD

**Issue by jwhited** [fguillot/kanboard#653]
It would be nice to have an option to disable My tasks from displaying tasks that are in the 'Done' column. My tasks can become quite cluttered if you prefer to leave tasks on the board in Done

Love this tool!

**Comment by ashbike** [comment]
This certainly makes it more usable. However, an item is not closed if put on done (well, theoretically). Also, Done is just a name of that column and for example, we have something called "Deployed". And it varies from board to board making it more complex. Instead, how about showing the column name in My Tasks? Or any other thoughts?

**Comment by fguillot** [comment]
To hide a task from the board you just need to close the task.

You can also do that with an automatic action.
