### ISSUE TITLE
Encrypted comments or notes

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#658]
It could be useful to store some confidential information in a task in order to quickly find a password related to the task per example.
The user's password would be used to encrypt content where the "encrypt" box is ticked. There would be a "decrypt"  button which shows up when the content is encrypted.
I guess for it to work well on comments, we would need a comment title, so that we know what the comment is about, unless "notes" are introduced

What do you guys think?

**Comment by ashbike** [comment]
Problem is, nobody else will be able to see it since it's encrypted with your password. It will sort of become a personal note. Is that what you want?

**Comment by fguillot** [comment]
There is probably more appropriate tools to encrypt sensitive data.

**Comment by oparoz** [comment]
@fguillot - Maybe, but that means getting everybody to install the same browser extension or app, exchanging keys, etc. In the end, someone will just paste the password in a comment because "it's too complicated"
@ashbike - Actually, you could share notes between project members. You simply encrypt the project's key using the key of each project member.The project's key is used to encrypt all "private" notes.

Looking at https://github.com/owncloud/core/tree/master/apps/files_encryption , this might be too big of an addition though. In my quick search I couldn't find a PHP library which was flexible enough to handle shared keys.

**Comment by nlights** [comment]
I would also like this feature, client side encryption should do the trick and would be safe!?!
Long time ago I used this plugin with dokuwiki: http://www.brickies.net/wiki/dokucrypt:start. Don't know if it still works but it shows the principle.
