### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Rogieee** [fguillot/kanboard#662]
Hope this is the correct place. if not im sorry to bother you.
Very new to this and I am trying to learn with bothering anyone but this one is way over my head

Re the Kanboard calendar
On creation of a job and assignment of a due date lets say 2015/2/26 it appears fine in the top of the main dashboard page calendar.
If you then move it to an assigned time for that day or any day it moves over fine and appears in the assigned time ok, but as soon as you leave the page all occurrences of that task disappear from all calendars completely.
Am i doing something wrong.
The same thing happens on my own VPS version and the official demo version.

Please help if you can or point me in the correct direction.

Cheers.

Rogieee

**Comment by sebelk** [comment]
+1 In fact the task time is moved to 31/12/1969. It could be nice that this bug is fixed.

Thanks in advance!

**Comment by thoth-caos** [comment]
+1 :-)

**Comment by fguillot** [comment]
This bug is fixed in the development branch.

Note: The due date doesn't contain the time, only the date.

**Comment by Rogieee** [comment]
OK Brilliant. It Works. Many thanks....

Any deadline on when the time slot allocation can be saved.
see video below.
http://web-disk.co.uk/files/issue.mp4

**Comment by Rogieee** [comment]
Is it at all possible to make the time slot save instead of reverting back to all-day?

Please see example videos of bug.
Please help !

http://web-disk.co.uk/files/issue.mp4
http://web-disk.co.uk/files/cal_bug.mp4

Many thanks.
