### ISSUE TITLE
Possibility to add checklists

### ISSUE THREAD

**Issue by scoopex** [fguillot/kanboard#671]
I really love kanboard - thanks for this great piece of software.

The only thing i miss: 
The creation and management of checklists comparable to Trello (https://trello.com/).

Creation:
* create/delete one or more checklists
* give each checklist a name
* order them

Management:
* adding/removing of checklist items
* possibility to order checklist items
* support for hooking and unhooking a checklist item
* create comments on modification of hooking status

**Comment by BlueTeck** [comment]
In Kanboard you have subtasks instead of a checklist. Isn't that the same?

**Comment by fguillot** [comment]
Sorry, for me it's the same thing as subtasks.
