### ISSUE TITLE
[Bug] missing translation

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#673]
If you search in the board selector and no project matches, it says "No results match". This text is not translatable at the moment.

German example screenshot:
![kbgerman](https://cloud.githubusercontent.com/assets/1961634/6394679/597cb9da-bdd3-11e4-8c17-e2932aa935ba.PNG)

**Comment by BlueTeck** [comment]
Also in the Filter box, but it is the source from chosen js code.

**Comment by fguillot** [comment]
Thanks, it's fixed in master.

**Comment by BlueTeck** [comment]
Thx
