### ISSUE TITLE
Update from 1.0.10 to 1.0.12

### ISSUE THREAD

**Issue by aaron832** [fguillot/kanboard#674]
I have following the instructions for updating the kanboard.
I create a new folder kanboard-new
Extract the kanboard-1.0.12.zip to kanboard-new
Delete data folder
Copy data folder from backup (preserve permissions).
Visit kanboard-new/kanboard
PHP runs at close to 100% cpu and the browser hangs for a bit.... then gives up.

**Comment by aaron832** [comment]
Oh, also, I should note that performing the same upgrade method above when upgrading to 1.0.11 works.

**Comment by aaron832** [comment]
Through some experimentation I found out that reducing the number of entries in the "tasks" table made the upgrade succeed.  Currently my tasks table has 784 entries.  Deleting entries down to 1/3 (from the beginning or end or middle) enabled the database port to work.

**Comment by fguillot** [comment]
Do you have any php errors when you upgrade from one version to another? What database do you use: sqlite, mysql or postgres?

It's maybe related to the maximum memory allowed for php, hard to say without any errors.

**Comment by aaron832** [comment]
Ok, figured it out.  Finally was able to find some useful log information.

2015/03/03 09:25:37 [error] 25940#0: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/www/htdocs/kanboard-test/kanboard/app/Schema/Sqlite.php on line 74" while reading response header from upstream

So this can be fixed by increasing/setting the max_execution_time in the php.ini file.

It seems like this could be an issue for others as the default is 30 seconds.  It looks like a better solution would be using set_time_limit while updating the database in between commands.
