### ISSUE TITLE
Completed tasks are forced to remain hidden

### ISSUE THREAD

**Issue by PeGa** [fguillot/kanboard#680]
If I place an automated action to close a task when moving to "Done", the task disappears from the board the precise time I raise my finger from the mouse. I feel this have two drawbacks:

1. The whole column loses its sense if I close the tasks automatically
2. I cannot have an instant tracking of finished AND closed tasks simultaneously.

A possible workaround of this is to create an additional column, let's say, "closed", where I drop closed tasks, but the second point remains unsolved.

Might it be possible to make closed tasks remain in the column through an option that says "show/hide completed tasks" or something like that?

Thanks in advance!

**Comment by hamzasheikh** [comment]
> Might it be possible to make closed tasks remain in the column through an option that says "show/hide completed tasks" or something like that?

I like this feature, too. Closed tasks should be viewable with an on/off toggle. Right now the only way I have found to view closed tasks in Kanboard is to export the project tasks to CSV.

**Comment by aaron832** [comment]
You can view closed tasks under the "Actions" (upper left menu) -> "Completed Tasks"

**Comment by PeGa** [comment]
@aaron832 , indeed that is the current way of viewing completed tasks; what I'm saying is that I am not able to see completed tasks **inside the board** once the task is completed.
The rationale for this is in my first post.

Thank you.

**Comment by docwhat** [comment]
A feature like show closed tasks in this column that were closed in the last NN days would be handy... then I could see the tasks completed in this iteration.

Currently, I drop stuff in done, then use a script to close the tasks via the API.

**Comment by sebelk** [comment]
+1

**Comment by fguillot** [comment]
With the current development version, you can now see closed tasks in the board, however you cannot move those tasks.
