### ISSUE TITLE
Dashboard - Assigned Subtasks

### ISSUE THREAD

**Issue by v0khjxVi** [fguillot/kanboard#682]
It would make it easier to handle a bigger amount of subtasks - if there would be a column "task title" after the project name column..

At the moment we solve this by adding a prefix to the title of the subtasks - but this doesnt work out really handy.

**Comment by BlueTeck** [comment]
:+1: I have also noticed that and it would be very handy.

**Comment by fguillot** [comment]
Sorry, I don't get it, can you elaborate with a use case or an example?

**Comment by v0khjxVi** [comment]
In the moment the block  "My Subtasks" in the dashboard is composed of the fields "id, project, subtask, time tracking". As the element "task (title)" is missing - it is not instantly visible to wich task the subtask belongs.

Example: You have 30 assigned tasks for which you have to collect - as a subtask -  the requirements. So the subtask will be (30 times) "collect requirments". In the dashboard view it is not possible to distinguish between the different tasks, as there will be 30 times "collect requirements".

The combination from *assignee* and *subtask title* is not (logically) unique in a project, while the combination *assignee*-*task*-*subtask title* is a candidate for a unique statement.

To improve this, I would recommend to have an additional column "task title" after "project" in the dashboard element "My Subtasks"

**Comment by BlueTeck** [comment]
something like this, just a little change:
![kb_dash_subtask](https://cloud.githubusercontent.com/assets/1961634/6458730/2ccc2864-c187-11e4-8193-f3b5a9a2f337.PNG)

**Comment by BlueTeck** [comment]
It's in the master branch now, issue could be closed.
