### ISSUE TITLE
How to set default view of calendar to month?

### ISSUE THREAD

**Issue by svenn71** [fguillot/kanboard#683]
Is there an option I have missed, or what line in source should I change to get monthly view in calendars?
I don't mind to change this manually each time I update kanboard, but week view is a too fine view for me right now.

**Comment by BlueTeck** [comment]
There is no option, but you could change the code:
http://github.com/fguillot/kanboard/blob/8214aae1d6c60b3d6726729d7532d8ee0df629ce/assets/js/src/calendar.js#L33

**Comment by svenn71** [comment]
Thanks a lot.

**Comment by Carlitoss** [comment]
Hi, I was trying to made the proposed change, but either 'month' neither 'agendaDay' works. It still shows only the agendaWeek. I've reloaded the page, deleted the cache, etc.

¿What else can I do?

Thank you so much!
