### ISSUE TITLE
Project timeline dispay

### ISSUE THREAD

**Issue by jeffvfren** [fguillot/kanboard#686]
Not sure whether have any plan to make kanboard with timeline calendar view?
kanboard is very helpful for me to manage my project and make the project have a clear picture.

When I want to discuss a project in daily briefing, the timeline will be very important to follow up for the task. Because a project may relate to many parties.

Example (url):
1) construction-projects.com/wp-content/uploads/2014/11/project_timeline.jpg
2) i1-win.softpedia-static.com/screenshots/Project-Timeline_4.png

**Comment by fguillot** [comment]
Same as Gantt chart, see #725
