### ISSUE TITLE
Mysql alternative Port

### ISSUE THREAD

**Issue by dansou901** [fguillot/kanboard#689]
Hi,
I want to use kanboard with mysql on a non standard port. If I configure it like 
define('DB_HOSTNAME', 'host:port');
I get a PHP Fatal Error in http error log. Can you add an option for mysql on a non standard port? Thanks!
Regards,
dansou901

**Comment by fguillot** [comment]
It's done in the development version, you can use:

```define('DB_PORT', 1234);```

**Comment by dansou901** [comment]
I'll try on monday when I'm back in office. Thanks for the quick implementation!

**Comment by dansou901** [comment]
Works perfectly, thanks again!

**Comment by EmersonMellado** [comment]
You could use your server:port on Config.php

example:
define('DB_HOSTNAME', 'localhost:3307');
