### ISSUE TITLE
Complexity digit on card overlaps summary text.

### ISSUE THREAD

**Issue by aaron832** [fguillot/kanboard#690]
![overlap](https://cloud.githubusercontent.com/assets/9599328/6468591/020e62c8-c18b-11e4-94f9-a7cd8a3ffacb.jpg)

**Comment by aaron832** [comment]
I created a branch with a fix.  Likely not a very good fix... but might help.
https://github.com/aaron832/kanboard/tree/feature/ComplexityOverlapFix

**Comment by adamcstephens** [comment]
Can we get a pull request made from this?

@fguillot isn't this a bug instead of an improvement?

**Comment by fguillot** [comment]
It's fixed in the development branch. I moved the complexity to the bottom right.
