### ISSUE TITLE
Activity log within the task detail

### ISSUE THREAD

**Issue by greg35** [fguillot/kanboard#693]
Hi all,

It could be useful to have the full list of activities summed up in the task detail.
For the moment, when we opened a task we have :
[Task detail]
[Date & Time tracking]
[Description]
[Subtask]
[Comments]

Why not add a part [Activity] with the activity log (eg : John move the card to "In progress", Max close the Task....)

Or include these logs with the comments.

Thanks for you feedback

**Comment by BlueTeck** [comment]
good idea

@greg35 There is already an automatic action, that adds a comment when the task is moved to another column

**Comment by greg35** [comment]
OK I will try this feature thanks a lot for the information.

**Comment by fguillot** [comment]
The activity stream is now available in the task view.
