### ISSUE TITLE
[Bug] could not display all types of "is_image"

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#694]
**EDIT:**
It is also wrong at the moment, not only in my future plans, see comment below.
I will fix it with my file attachment approvments and make a pull request.

**Original Message:**
Hi @fguillot 

at the moment every attachment that passes the function getimagesize is uploaded as "is_image" (
https://github.com/fguillot/kanboard/blob/master/app/Model/File.php#L122).

That includes the following image extensions:
[IMAGETYPE_GIF] 
[IMAGETYPE_JPEG] 
[IMAGETYPE_PNG] 
[IMAGETYPE_SWF] 
[IMAGETYPE_PSD] 
[IMAGETYPE_BMP]
[IMAGETYPE_TIFF_II] 
[IMAGETYPE_TIFF_MM] 
[IMAGETYPE_JPC] 
[IMAGETYPE_JP2] 
[IMAGETYPE_JPX]
[IMAGETYPE_JB2] 
[IMAGETYPE_SWC] 
[IMAGETYPE_IFF] 
[IMAGETYPE_WBMP] 
[IMAGETYPE_JPEG2000] 
[IMAGETYPE_XBM] 
[IMAGETYPE_ICO]

For the new Image View in the Task Details (#307 https://github.com/fguillot/kanboard/issues/307#issuecomment-76602088) i want to use thumbnails for a better performance. The way i want to generate the thumnals "on the fly" only supports jpg, jpeg, png and gif. (https://gist.github.com/BlueTeck/d50c3955d3add2cf31f1)

Could i restrict the file upload "is_image" to jpg jpeg png gif? If you upload .ico .psd etc there are "just" files without the "is_image" flag? Or do you want it as it is?

**Comment by BlueTeck** [comment]
Okay i will restrict the image types, because it is not working at the moment.

If you upload a .tif file, you will get the open button behind the file (because of "is_image"), but my browser chrome is not able to display this.

Screenshot from stable version:
![tif1](https://cloud.githubusercontent.com/assets/1961634/6508414/e54d7dde-c358-11e4-918c-bc2ea899a312.PNG)
![tif2](https://cloud.githubusercontent.com/assets/1961634/6508415/e54f7558-c358-11e4-8d3b-4c968eba546d.PNG)

**Comment by fguillot** [comment]
Actually, the purpose of `isImage()` is to display or not the popover. I mean a file that can be viewed in the browser. So it can be restricted to only some file types.
