### ISSUE TITLE
[FR] add swimlane to task edit form

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#696]
In the new task form, add swimlane like column dropdown:
![add_swimlane](https://cloud.githubusercontent.com/assets/1961634/6522254/44d1e864-c3e3-11e4-94a9-968a21733a0a.PNG)

**Comment by oparoz** [comment]
I agree, it would save some time depending on how swimlanes are used

**Comment by oparoz** [comment]
It's in "task add", but still missing from "task edit"

**Comment by fguillot** [comment]
It's already available, the dropdown is visible when there is at least one swim-lane.
