### ISSUE TITLE
Dashboard - My Projects : projects missing

### ISSUE THREAD

**Issue by Yaponchik** [fguillot/kanboard#698]
Hi,

In my dashboard, My projects section, I don't see all the projects, even if there are task in it. 
And if I create a new project, I see it but my co-workers don't see it in their dashboard.

Is there something I have to set so that everybody can see those projects ? 

Thanks for your answer,
Xavier.

**Comment by BlueTeck** [comment]
Are they members of your project?

**Comment by Yaponchik** [comment]
I checked "Authorize everybody to access this project", but it didn't work.
I have to authorize each member one by one to have it work.
Thanks for your quick answer.
Yaponchik.

**Comment by fguillot** [comment]
I just changed this behavior in the current development branch. Now, you just have to check the box "allow everybody".
