### ISSUE TITLE
Tooltip for titles in collapsed mode

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#701]
The titles are shortened in collapsed mode and it's sometimes difficult to tell tasks apart without having to uncollapse the whole board which changes the view and is not really a viable option.

So, it would be great if the title could show up when rolling over the title.
Another option could be to quickly uncollapse just one task via a dropdown-like button.

**Comment by macce** [comment]
Great idea! Also, in collapsed mode, the small icons that show task links and the description when hovering over them could be shown!

**Comment by fguillot** [comment]
Now, there is a tooltip for task title in the master branch.
