### ISSUE TITLE
Plug-in API

### ISSUE THREAD

**Issue by rnaby** [fguillot/kanboard#703]
I've two queries--

1. Does Kanboard has any plug-in API like WordPress has? Cause I made some modification in Kanboard. So now I wanna share this with every body. If there is a plug-in API that should be better for me. 

2. Which framework you've used to develop Kanboard? 

Thank You.

**Comment by fguillot** [comment]
1) There is no plugin api at the moment. 
2) As you can see in the source code, there is no framework, it's just a MVC web application that use a couple of libraries...
