### ISSUE TITLE
I don't receive the email notifications

### ISSUE THREAD

**Issue by Yaponchik** [fguillot/kanboard#707]
Hi,

In my team, one developper receives the email notifications when we change a task, but the others don't receive them. For each one, I've correctly set the option to receive the emails for each project. For info, we use Gmail accounts. I've checked in the spam, no Kanboard email.

Do you have an idea why we don't receive the emails ? 
Thanks for your help,
Yaponchik.

**Comment by fguillot** [comment]
All people are members of the projects? Everybody have a valid email address and enabled notifications? No errors?

**Comment by Yaponchik** [comment]
Yes, I'm member of the project, with a valid email address and the notification is enabled.
There is no error.

Perhaps a problem on our server ?

**Comment by Yaponchik** [comment]
I think it's a server problem. I close this issue.
