### ISSUE TITLE
MarkDown for to-do lists

### ISSUE THREAD

**Issue by Cathryne** [fguillot/kanboard#708]
Hello!

I am testing Kanboard in a laboratory environment. Thus, my task/card descriptions often include text (ideas, observations, etc.) and lists (materials, protocol steps, etc.) alternatingly. This works quite well, up to the point where a list should be a to-do list (preparations & follow-up to experiments, etc.). Could maybe [GitHub-flavored MarkDown](https://help.github.com/articles/github-flavored-markdown/) be implemented?

```
- [ ] to do
- [x] done
```

- [ ] to do
- [x] done

[Haroopad](https://github.com/rhiokim/haroopad) for example [does this as well](http://pad.haroopress.com/page.html?f=how-to-manage-tasklist) and has syncing between the clickable check-boxes and the raw MD code.

**Comment by fguillot** [comment]
As far I know, the library use to parse the Markdown content doesn't support yet the checkboxes. That can probably done with a custom extension.

However, you can still create subtasks, there are 3 different states: "todo", "in progress" and "done".
