### ISSUE TITLE
Add option to use non default port for mysql connection

### ISSUE THREAD

**Issue by JohnnyGW** [fguillot/kanboard#711]
I'm trying to deploy kanboard but connections to mysql fail because I cannot specify a port and my database setup involves using a non default port. Would it be possible to add an extra parameter to specify the port?

**Comment by BlueTeck** [comment]
see #689

**Comment by BlueTeck** [comment]
if you want to change it in the stable version see commit 313318a40da51575212c8d299fa1b2ed4c83ca1b

**Comment by JohnnyGW** [comment]
Thanks a lot
