### ISSUE TITLE
Table Prefix

### ISSUE THREAD

**Issue by frederikheld** [fguillot/kanboard#712]
It would be great to have a config option to define a DB table prefix so it would be easier to put kanboard in a DB together with other applications.

I think of an entry in config.php like this:

    define('DB_TABLE_PREFIX', 'kb_');

As I'm not really familiar with the way you implement things in Kanboard I abstained to implement it myself. But if you tell me where to put this, I can do the work...

Thanks in advance,
Frederik

**Comment by fguillot** [comment]
The way it's currently made, that will require too much changes to implement that.

**Comment by iPublicis** [comment]
Hi there.

I was looking to the code (not all the code) and noticed that this is more or less common:

`const TABLE = 'project_activities';`

Wouldn't it be easy to convert it to?

`const TABLE = DB_TABLE_PREFIX . 'project_activities';`

**Comment by oliviermaridat** [comment]
@iPublicis Unfortunately, before PHP 5.6, "const" accepts only static scalar (number, string or other constant like true, false, null, __FILE__) (see http://php.net/manual/fr/language.constants.syntax.php).

So, this code will fail priori to PHP 5.6:

    const TABLE = DB_TABLE_PREFIX . 'some_table_name';

And yes, that is a pity.

**Comment by juehv** [comment]
So why shouldn't we go for PHP 5.6 or higher?

For me, the feature would be very handy!

**Comment by fguillot** [comment]
To be compatible with all versions of PHP, you could use a method to build the table name instead of a class constant. If you guys really need that feature, I let you make a pull-request.
