### ISSUE TITLE
How to migrate base Sqlite to Mysql/MariaDB ?

### ISSUE THREAD

**Issue by kiterfoo** [fguillot/kanboard#716]

**Comment by fguillot** [comment]
At the moment there is no automatic procedure to migrate from one database to another one.

That could be a great addition to the command line tool.

**Comment by kiterfoo** [comment]
it would be nice as tools.

**Comment by BlueTeck** [comment]
There are tools in the internet for this:
https://www.google.com/webhp?q=migrate+sqlite+to+mysql

**Comment by kiterfoo** [comment]
This is the solution I have tested first, more I spent PYTHON filter.
However, the result does not work, there's a concern to the creation of a table, and if I create tables with KANBOARD to import the data, the order of fields is not the same and does not work .
thank you

**Comment by valessiobrito** [comment]
Action still seems to be manual[1]. Settings download[2] the base is incompatible with import to MySQL. Maybe this is a new feature to export the data in raw SQL compatible with any others.

[1] https://otland.net/threads/convert-sqlite-to-mysql-database-with-pictures.47742/
[2] /kanboard/?controller=config&action=downloadDb

**Comment by bertux** [comment]
Now it seems easier when reading http://kanboard.net/documentation/mysql-configuration
Thank you for this documentation on this easy migration process
