### ISSUE TITLE
Request - Color based categories? 

### ISSUE THREAD

**Issue by woollensocks** [fguillot/kanboard#720]
Hey,

So I use colors as a way of organizing tasks into sudo categories.  Example Red=Bug, Green=Request and so on.  

What do you think of the option of being able to define what these colors mean from within settings?  And possibly showing a legend at the bottom of the board.

**Comment by fguillot** [comment]
You can already define those colors automatically with automatic actions. Have a look to the section "examples" of the page http://kanboard.net/documentation/automatic-actions
