### ISSUE TITLE
1.0.12 dashboard and searches don't show projects enabled as Allow Everybody

### ISSUE THREAD

**Issue by efetzer** [fguillot/kanboard#722]
I have several projects marked as Allow Everybody, but they don't show up on dashboards, drop down's or searches.  Only specifically assigned projects show up.

**Comment by efetzer** [comment]
Same as #698

**Comment by fguillot** [comment]
I just fixed that in the current development branch.

**Comment by efetzer** [comment]
Thanks much.  When do you expect the next stable release?

Thanks,
Erik

**Comment by fguillot** [comment]
Probably early April for the next stable version.

**Comment by shimza** [comment]
When's the next stable build released?

Cheers,

Shimon

**Comment by BlueTeck** [comment]
7 hours ago http://kanboard.net/news/version-1.0.13
