### ISSUE TITLE
Allow Plugins for Automatic Actions

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#724]
Hi,

Would it be possible to allow developers to create their own external providers for automatic actions (or is it possible already?) in a way that will be 'safe' if/when I upgrade the copy of Kanboard?

I'd like to link up our internal bug reporting software to Kanboard ... now, I know I can do this already through the REST-API, but it would be really cool if I could allow it to be used in the 'automatic actions' bit instead, so that users could customise it based on the project and use it just like they would github etc.

Thanks,
Algy

ps - great work on Kanboard, it's superb :)

**Comment by fguillot** [comment]
It's now possible with the current development version by using plugins, see:

- https://github.com/kanboard/plugin-example-automatic-action
- https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown#extend-automatic-actions
