### ISSUE TITLE
Gantt Charts

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#725]
Hi,

Is it possible to add a Gantt chart (http://en.wikipedia.org/wiki/Gantt_chart)-type functionality to the Kanboard dashboard, or perhaps to one of the project or analytics pages?  It'd be incredibly helpful :)

Thanks,
Algy

**Comment by valessiobrito** [comment]
Gantt charts the a project using JQuery: http://taitems.github.io/jQuery.Gantt/

**Comment by fguillot** [comment]
Duplicate of #832

**Comment by fguillot** [comment]
Gantt chart is available in the dev version, see https://github.com/fguillot/kanboard/blob/master/docs/gantt-chart.markdown
