### ISSUE TITLE
Request: non admin user should be able to open public projects

### ISSUE THREAD

**Issue by muehli** [fguillot/kanboard#726]
Hi all,
meanwhile we have a lot of users working with this great tool.
But most of their projects require several members. So a public one is needed.
I would be very helpful if they could create their one public projects.

I hope this is feasible.

Kind regards
muehli

**Comment by BlueTeck** [comment]
Already requested ;) #521

**Comment by fguillot** [comment]
It's now possible in master branch, there is a new group "project admins" for that.
