### ISSUE TITLE
Request: etherpad-lite integration

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#727]
Integration Etherpad-lite ( https://github.com/ether/etherpad-lite ) its possible with API ( https://github.com/ether/etherpad-lite/wiki/HTTP-API );

The proposal:
- Set configuration URL and token API of etherpad-lite in kanboard;
- All description or text-area using alternative method with etherpad-lite.

Example:  http://www.odoohelp.com/odoo-etherpad-integration-formerly-openerp/

**Comment by BlueTeck** [comment]
Could you give me an example, why do you need every textarea as realtime collaboration textfield?

**Comment by valessiobrito** [comment]
(etherpad+webrtc)[1] embedded within a task can function as a system for working together to brainstorm, meetings, documentation production, etc.

[1] https://pad.textb.org/p/kanboard

**Comment by fguillot** [comment]
Sorry, for me it's out of the scope of Kanboard, this software focus on simplicity.
