### ISSUE TITLE
Board selector when everybody is allowed

### ISSUE THREAD

**Issue by Pybou** [fguillot/kanboard#729]
Hello,

First of all, thanks for this fantastic project, you are doing a very good job!

I have a question, I don't really know if it's a bug or if it's normal but I don't understand why the board selector doesn't appear for everybody when we checked "Everybody is allowed" in project settings.

Thanks a lot

**Comment by BlueTeck** [comment]
Duplicate #722

**Comment by BlueTeck** [comment]
And duplicate of 698

**Comment by BlueTeck** [comment]
#698

**Comment by Pybou** [comment]
Ok, sorry for that ;-)

Thanks

**Comment by fguillot** [comment]
It's fixed in the master branch.

**Comment by Pybou** [comment]
Works perfectly ;-)
Cheers
