### ISSUE TITLE
Notifications : Unable to change the E-mail address ("From" header )

### ISSUE THREAD

**Issue by vfarcy** [fguillot/kanboard#733]
It seems possible to change the default notification email adress. 

So, I changed line 13  - define('MAIL_FROM', 'newemailadress@aomain.tldl') - in config.default.php file accordingly, but I still receive notification from the original one.

Anyway, congrats, very great work.

**Comment by fguillot** [comment]
Just to be sure, did you rename the file `config.default.php` to `config.php`?

**Comment by vfarcy** [comment]
No, I didn't . I will try .
