### ISSUE TITLE
Bug in task list for other user's dashboard

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#734]
Hi,

If I go on to "All users", click on one other than myself, then click "User dashboard", it brings up that user's dashboard (yay!). However, when I click the "next" button, the task list reverts to my one.

This is simply because the URI doesn't contain a user_id - if you add it in to the URI yourself (eg append "&user_id=5"), it works fine :)

Cheers,
Algy

**Comment by fguillot** [comment]
Thanks. It's fixed in the development version.

**Comment by AlgyTaylor** [comment]
Thanks :)
