### ISSUE TITLE
Renaming folder problem

### ISSUE THREAD

**Issue by jsmith000** [fguillot/kanboard#736]
Hello,

I'm trying to rename the folder name "kanboard" into something else and use it but I only get a blank page.

Any ideas/suggestions?

Thank you!

**Comment by fguillot** [comment]
You can use any folder name or no folder at all. Do you have any php errors?

**Comment by jsmith000** [comment]
No php errors at all just a blank page. I am using MySQL if that matters. If I name the folder kanboard it works great. If I rename that folder nothing shows up :/

**Comment by fguillot** [comment]
if you have an error 500, you should see an error in your log files (apache error logs)? What is your environment os/php version?

**Comment by jsmith000** [comment]
Here are the log errors:
[Tue Mar 24 21:55:20.666677 2015] [fcgid:warn] [pid 36188] [client xxx] mod_fcgid: stderr: PHP Warning:  require(/home/xxx/public_html/xxx/kanboard/app/check_setup.php): failed to open stream: No such file or directory in /home/xxx/public_html/xxx/board/index.php on line 3

[Tue Mar 24 21:55:20.666692 2015] [fcgid:warn] [pid 36188] [client xxx] mod_fcgid: stderr: PHP Fatal error:  require(): Failed opening required '/home/xxx/public_html/xxx/kanboard/app/check_setup.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/xxx/public_html/xxx/board/index.php on line 3

It seems like the __DIR__ points to kanboard :/
I'm running Ubuntu 14.04 with PHP 5.5.9

**Comment by jsmith000** [comment]
It was a cache problem after all..
