### ISSUE TITLE
BruteForce protection

### ISSUE THREAD

**Issue by jsmith000** [fguillot/kanboard#737]
Hello,

I was wondering if it would be possible to block IPs/users that fail to login X times within a specific period. Also maybe store that info somewhere so the admin is aware of the attack?

Thank you!

**Comment by fguillot** [comment]
This feature is not yet implemented but I plan to add an optional 2 factors authentication.

**Comment by valessiobrito** [comment]
@jsmith000 using http://www.fail2ban.org

Example with wordpress:  http://serverfault.com/questions/614599/fail2ban-to-block-wordpress-brute-force-attacks-on-wp-login-php

**Comment by fguillot** [comment]
There is now a bruteforce protection into the development version see
https://github.com/fguillot/kanboard/blob/master/docs/bruteforce-protection.markdown
