### ISSUE TITLE
Request: Toggle Display Of Values For "Task age in days, Days in this column"

### ISSUE THREAD

**Issue by genesis-github-admin** [fguillot/kanboard#741]
Hi there.

I know that if I collapse the task - it hides the "Task age in days, Days in this column", but it would be great to remove or be able to hide the "Task age in days, Days in this column" values when the task item is expanded.

It would keep it more visually clean when those two values are not used.

Thank-you for your consideration!

**Comment by BlueTeck** [comment]
You could remove it from your code: https://github.com/fguillot/kanboard/blob/master/app/Template/board/task_private.php#L34

**Comment by genesis-github-admin** [comment]
Thanks for the suggestion!  My board is sexy again!

**Comment by nekohayo** [comment]
I'd also be in favor of an option for this; while it makes sense in a highly agile environment, various teams I'm involved with are using kanboard to track long-term projects and the age/age-in-column metrics just don't apply in this scenario, it just creates information overload and issues like #948.

**Comment by fguillot** [comment]
Temporary, you can use the custom stylesheet to hide those metrics:

```css
.task-board-days { display: none }
```

**Comment by nekohayo** [comment]
Not sure I understood properly, I tried setting the display: none; property on .task-board-days inside assets/css/src/task.css, or in assets/css/src/board.css, and it didn't work (tried a hard refresh with ctrl+F5)

**Comment by BlueTeck** [comment]
you could do it via settings
![image](https://cloud.githubusercontent.com/assets/1961634/8416816/91c3dae0-1ea8-11e5-8cf7-da14098e3d4a.png)

**Comment by fguillot** [comment]
The position
