### ISSUE TITLE
Consider add/change to task's comments as a "task modified" event for webhooks.

### ISSUE THREAD

**Issue by tranquility-base** [fguillot/kanboard#753]
Feature request: consider creation or modification of a task's comments to be a modification to the task, and trigger the "task modified" webhook, with the comment data in the payload of the event.

Motivation: Our team is using kanboard for internal project management (and we love it!), but we have to tie into an institution-wide tracking system (RT). We wrote code to equate a task in kanboard with a ticket in RT, and have it working so a change in one system automatically creates the comparable change in the other -- except that creating or modifying a comment in kanboard does not trigger a "task modified" webhook. Thus we cannot keep RT synchronized with comments added to kanboard tasks.

**Comment by fguillot** [comment]
The webhook system have been changed in the current development branch. Now, all internal events of Kanboard are sent to a webhook url if defined. That will be part of the next stable release.

The doc is here: https://github.com/fguillot/kanboard/blob/master/docs/webhooks.markdown

**Comment by fguillot** [comment]
In your case, you can synchronize comments now.
