### ISSUE TITLE
[Bug] Different date formats

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#754]
In my german testinstallation, i have found a "bug". The date format is different in budget and activities for example:

Correct:
![right1](https://cloud.githubusercontent.com/assets/1961634/6926261/680d0c80-d7e5-11e4-8f89-3dd394d55ea9.PNG)
![right2](https://cloud.githubusercontent.com/assets/1961634/6926262/680e8eca-d7e5-11e4-996a-17bcc9162e93.PNG)

Wrong:
![wrong1](https://cloud.githubusercontent.com/assets/1961634/6926268/6d9fdd3a-d7e5-11e4-9d78-83bfabbb3d2d.PNG)

**Comment by fguillot** [comment]
The date is not translated on the budget view

**Comment by fguillot** [comment]
Should be fixed in master.

**Comment by GrCOTE7** [comment]
Helloo, about date...

I had a first version that get date perfectly translated in the dashboard.


I just do a new installation now of the stable version...

All is well, but dates in board are in english ?!?

Do you know how to soluce that ? What is the file we do change/modify?

Thanks.
