### ISSUE TITLE
[Bug] : Not compatible with Postgresql 8.1

### ISSUE THREAD

**Issue by nadley** [fguillot/kanboard#755]
Hi,

I know I should not use postgresql 8.1 as it is end of life since long time.

But there is no precision about which version of PostgreSQL is compatible with PostgreSQL.
[How to use with PostgreSQL](http://kanboard.net/documentation/postgresql-configuration)

So this is not a real issue but I open it just to keep track of this problem, and to recommend adding precision about version compatibility on documentation side.

As I understand the error is the "IF NOT EXISTS" clause which is not supported. This clause is supported on PostgreSQL 9.1 and above.

Regards

**Comment by fguillot** [comment]
Actually, I test only with Postgresql 9.4.

If you cannot upgrade Postgres, you can try to modify the code to make it work. The only place with a `IF NOT EXISTS` is the schema version table used by PicoDb. So by creating manually the table and commenting the line that should work. 

- https://github.com/fguillot/picoDb/blob/master/lib/PicoDb/Driver/Postgres.php#L42
- `CREATE TABLE schema_version (version SMALLINT DEFAULT 0)`

**Comment by nadley** [comment]
Thanks for your answer.

I had the ability to update my Postgres server. This "issue" was just opened to track this situation and give information to the community ;-).

Regards
