### ISSUE TITLE
Improvement of the list of users of a project

### ISSUE THREAD

**Issue by epaiva** [fguillot/kanboard#758]
The list is getting too long when selecting authorized users for a project. I suggest implementing the same selecting tool used for selecting projects (upper right corner).

**Comment by valessiobrito** [comment]
@SamuelMoraesF this seems to be easy to solve. What do you think?

![test_edit_project_access_list_-_2015-04-05_23 32 16](https://cloud.githubusercontent.com/assets/310049/6999846/48649f0a-dbec-11e4-8b37-47fa5b9ff229.png)

Use the same type to select board in select user list. Allowing filter a long list.

**Comment by SamuelMoraesF** [comment]
I can open an PR to solve this issue and implement the same select system for users temporally.

In the redesign(#766) I want to implement an left menu with the user's projects(order by activity) and the search/filter system. And for users, an new list-based search system(or something like).

**Comment by fguillot** [comment]
It's now available in the development branch.

**Comment by valessiobrito** [comment]
Thanks!!!
Congratulations.
