### ISSUE TITLE
Add "Delete Task" to task dropdown.

### ISSUE THREAD

**Issue by tranquility-base** [fguillot/kanboard#762]
Please add a "Delete Task" to the task drop-down. To protect against accidental deletion, it could bring up an "Are you sure?" dialog headed with the task name.

**Comment by BlueTeck** [comment]
Is this really needed? I think the close task option is enough. Normally you close a task and don't delete it.

**Comment by tranquility-base** [comment]
Our situation: we're tying Kanboard in to our service/server alert system. If something goes wrong, a task is generated to notify us and to track its resolution. However, false positives occur, sometimes many at once if, say, a sensor is bad. Sometimes it's a real problem, but there are dozens of alerts and you only want to keep one of them. Or, there might be a legitimate problem (cranky LDAP server anyone?) that causes many spurious alerts due to dependencies. Even a simple misconfigured alert could do it (easy enough when you have hundreds to thousands). If you close the resulting tickets it skews your metrics something awful and makes your history difficult to search through. To get meaningful metrics and history you need to delete them instead.

Same kinds of issue could come from automated build systems.

**Comment by mcorteel** [comment]
I agree, and it made me think about the dropdown menu. Why are "Change assignee", "Change category", "Change description" and "Edit task" different entries. Everything coud (and IMHO should) be in the "Edit task" form, which would greatly simplify this menu.
But this would be another ticket I guess.

**Comment by fguillot** [comment]
The dropdown menu is now the same in all views. The delete task action is present too.
