### ISSUE TITLE
Activity stream for each Task

### ISSUE THREAD

**Issue by jregusci** [fguillot/kanboard#764]
I belive that having an "Activity stream" for each task would be of great value in issue tracking types of boards.

The activity stream could be a mix of comments and activity for the task. For instance, you coud have something like this:

Datetime - Comment 1 for "Task 1"
Datetime - The User moved "Task 1" to "In Progress"
Datetime - The User moved "Task 1" to "Done"
Datetime - Comment 2 form "Task 1"

**Comment by BlueTeck** [comment]
Its already in the current dev version.

**Comment by jregusci** [comment]
Great! Thanks for your reply.
Kanboard is an awesome tool and you guys are making it more powerful every day. Congratulations.

**Comment by valessiobrito** [comment]
:+1: :cool:
