### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by SamuelMoraesF** [fguillot/kanboard#766]
How about an redesign?

I started an model based on [Flat-UI](https://designmodo.github.io/Flat-UI/)

(currently I just changed the header menu)

![firefox_screenshot_2015-04-04t18-37-08 284z](https://cloud.githubusercontent.com/assets/3705263/6994035/7bcc8806-dae0-11e4-9382-8b4249c03942.png)

**Comment by SamuelMoraesF** [comment]
PS.: without Bootstrap :wink:

**Comment by valessiobrito** [comment]
Please, Mobile First.
Any proposed interface is welcome. But I think we should first think for mobile devices.
The kanboard is fantastic. If there is a focus on mobile interfaces. We can gain a powerful Mobile WebApp.

[1] http://zurb.com/word/mobile-first

**Comment by SamuelMoraesF** [comment]
@valessiobrito, yes, I'll use Mobile First :wink:

I think that will be an good idea an grid system. Recomendations?

Maybe the [grid system of Zurb Foundation](http://foundation.zurb.com/grid.html)

**Comment by valessiobrito** [comment]
@SamuelMoraesF many options exist. We can work to have a framework of themes to Kanboard?
Eg.  Theme with Bootstrap, or with Zurb, Jquery, pure CSS, etc;

**Comment by SamuelMoraesF** [comment]
Yeap, It's an good idea, we can create an theme based on Zurb(our own fork with custom styles).
@fguillot, Are you ok with it?

**Comment by valessiobrito** [comment]
Example of a structure of themes:  https://github.com/q2a/question2answer/tree/master/qa-theme

**Comment by phsc** [comment]
Looking forward to test this! :+1:

**Comment by phsc** [comment]
What about this (as an addition to Zurb grid system)?
=> http://fortawesome.github.io/Font-Awesome/

**Comment by bastiao** [comment]
Seems quite nice. How about mobile support? Now, It is quite difficult to use in iOS (iPad or iPhone).

**Comment by SamuelMoraesF** [comment]
@phsc and @bastiao, yes, I'll use FontAwesome and Mobile-First.

An preview(now I working in the menu):

![imagem da pagina 2015-04-12 - 18 12 25](https://cloud.githubusercontent.com/assets/3705263/7107604/6179f234-e140-11e4-8605-205a70a5d321.png)

**Comment by SamuelMoraesF** [comment]
I working on the layout, after this done, I'll customize the color scheme and others details.

**Comment by shimza** [comment]
Looking really good.

**Comment by bastiao** [comment]
Seems great! :)

**Comment by valessiobrito** [comment]
@SamuelMoraesF fork Trello design, Libreboard, see: http://git.libreboard.com/libreboard/libreboard

**Comment by cheoAlejo** [comment]
Wow, great job.

**Comment by phsc** [comment]
Any news on this? @SamuelMoraesF

**Comment by SamuelMoraesF** [comment]
@phsc, I'm working in a personal project with Kanboard and the redesign is in our backlog :)

The SASS files are at [@samuelmoraesf/kanboard-ui](https://github.com/SamuelMoraesF/kanboard-ui) and Kanboard are at [@666/kanboard-redesign](http://github.com/666/kanboard-redesign/).

I'll keep [this issue](https://github.com/666/kanboard-redesign/issues/1) updated with the progress of the redesign.

**Comment by fguillot** [comment]
If you want to redesign Kanboard or to create a theme, you can use a plugin to do that (only with the development version at the moment).

More information here:
- https://github.com/fguillot/kanboard/blob/master/doc/plugins.markdown
- https://github.com/kanboard/plugin-example-theme
- https://github.com/kanboard/plugin-example-css

**Comment by gideoni** [comment]
Dear,
I am interested in your theme to Kanboard. There is a version ready for testing?
Regards,
Gideoni

**Comment by defcon1702** [comment]
Are there any news in the "theme" section?
