### ISSUE TITLE
Project Templates

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#769]
Ability to create "Template Project"
1. As an administrator can create a project and define what a "Template"
2. As a user, when creating a new project, list all available templates.

A new design based on the template, is a clone of the board settings and possible task structures.

A list of different possibilities and needs to support different templates: http://kanboard.net/documentation/usage-examples

This structure can solve #289

**Comment by valessiobrito** [comment]
a) Create a project, adjust board and tasks. Mark/set with "Template project";
b) Users or admins, create a 'new project' select a template or "default/blank".

I can configure templates projects: development, events, party, to-do, etc;

**Comment by fguillot** [comment]
With KB 1.0.25, when you can create a new project from another one. So it's like having templates.

**Comment by Snajper88** [comment]
HOW IS THAT NOT A THING
