### ISSUE TITLE
Add Time tracking in linked task view

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#775]
It could be useful to have a column "Time tracking" (as it is done for subtasks) in the "Links" table of a task view. This simplify the visualization of time spent on a task. 

Typical use case:
* One task is a milestone and therefore have a link "is a milestone of" with several other tasks
* The manager of this milestone will add subtasks ("Management", "Validation", ...) to estimate and track the time spent around this task.
* The manager can see quickly the time spent on the subtasks of this milestone, and on the tasks that targets this milestone.

**Comment by oliviermaridat** [comment]
FYI: I am working on a PR for this.

**Comment by fguillot** [comment]
See master.
