### ISSUE TITLE
After upgrading to 1.0.13, getAllProjects() stopped working

### ISSUE THREAD

**Issue by russell-phillips** [fguillot/kanboard#776]
I upgraded from 1.0.12 to 1.0.13 this morning, and the getAllProjects() API call has stopped working. I have several projects, but it's returning NULL (in PHP).

I've not been using Kanboard for very long, and this the first time I've upgraded, so it's possible that I did something wrong :-/

**Comment by sparkles645** [comment]
Upgrade to 1.0.13 works fine here so far.

**Comment by BlueTeck** [comment]
Upgraded also and can't confirm your issue. 

My Chrome Extension https://chrome.google.com/webstore/detail/kanboard-quickmenu/akjbeplnnihghabpgcfmfhfmifjljneh uses this API call, and it works fine.

**Comment by russell-phillips** [comment]
Sounds like I broke something during the upgrade, then :(

**Comment by russell-phillips** [comment]
Some more information, in the hope that someone will be able to help me work out what's wrong:

I'm running PHP v5.3.10 on Apache v2.2.22

I tried @BlueTeck's Chrome extension, and it gives an error ("Error due API call.") In the Apache logs I see this line:

    PHP Fatal error:  Can't use method return value in write context in kanboard/jsonrpc.php on line 121

**Comment by fguillot** [comment]
The issue have been fixed in the development version. It was a PHP 5.3 compatibility issue.

If you don't want to wait the next stable version, you can apply the fix manually, the diff is here: https://github.com/fguillot/kanboard/commit/8330123f3469ebf963d1d7711fff2bf8b03c97c3

Thanks to report the bug!

**Comment by russell-phillips** [comment]
Just commenting to note that the diff fixed the issue for me. Thanks :) :+1:
