### ISSUE TITLE
Hipchat/slack integration : restrict it to one project

### ISSUE THREAD

**Issue by labo-css** [fguillot/kanboard#778]
I use hipchat and i tested your new feature, but... all my private projets got notifications to hipchat and i can't choose to notify only one project.

**Comment by timjcraig** [comment]
Moving HipChat notifications to project settings  would be great as we generally have HipChat room assigned to each project and also using automatic actions to customise message when user creates, moves task etc.

**Comment by fguillot** [comment]
I will see how to add this feature by project. Should be easy to implement.

**Comment by fguillot** [comment]
It's now possible in the master branch.
