### ISSUE TITLE
Burndown Chart - Cumulative Flow

### ISSUE THREAD

**Issue by jregusci** [fguillot/kanboard#781]
It would be great feature  to have a Burndown Chart built based on the Complexity field. 

At the moment the cummulative flow provides a great chart that is built on the quantity of tasks rather thant on the complexity which is a more accurate meassure for the task (i.e.: story points in software, revenues in sales, and any other that you can define).

Thanks! and again great work!!

**Comment by fguillot** [comment]
There is a burdown chart now in the dev version. For the moment, it's pretty basic but that can do the job.

Here an example with sample data:

![Burndown chart](http://kanboard.net/screenshots/documentation/burndown-chart.png)

**Comment by jregusci** [comment]
Thanks Frédéric. It looks great!
How does it work? The points shown in the graph are the complexity values for all Open tasks (sum for all columns at a given date)? is this correct? 

It would be great if you could add the estimated finish date for the chart, whether as a label next to the chart or as a projection in the chart itself (date when it becomes 0). Do you think that info could be added?

Once again, thanks!

**Comment by fguillot** [comment]
Yes, correct.

Each time a task is updated, created or moved, the sum of story points for open tasks are recorded in the database for the given day and for each column. With that graph, you have the sum of points for all columns for each day.

For the moment, I want to keep this chart like that. I will see in the future if that need more information.
