### ISSUE TITLE
Unable to change default calendar view

### ISSUE THREAD

**Issue by Carlitoss** [fguillot/kanboard#783]
Hi all,

First of all, I would like to thank you all for you GREAT job done in this project.

I have a question/bug because I've tried to change the default calendar view to "month" as indicated in issue https://github.com/fguillot/kanboard/issues/683 but nothing works.

Do I need to change anything else? Is it working for you?

Thank you so much.

Best regards,
Carlos.

**Comment by fguillot** [comment]
If you change the Javascript don't forget to rebuild assets: https://github.com/fguillot/kanboard/blob/master/docs/assets.markdown
