### ISSUE TITLE
Accidentially dragged tasks

### ISSUE THREAD

**Issue by frederikheld** [fguillot/kanboard#786]
I really like the drag & drop interface of Kanboard. And I like that it also works on touch devices. But it has one major flaw: If you click or tap a task accidentially it is immediately dragged out of it's place and there is no way to find out where it came from. So I have to put it back where I think it came from and check the changelog afterwards to find out if I guessed right.

This especcially happens when scrolling on touch devices and leads to a lot of unnecessary entries in the changelog which confuse my coworkers.

It would be nice to have a feature to cancel d&d operations like in Windows, where you can simply hit the Esc key.

Thanks for your good work!
Frederik

**Comment by fguillot** [comment]
There is now a special icon to move task on touch devices to avoid accidental moves.

**Comment by frederikheld** [comment]
Thank you!
