### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by hicter00** [fguillot/kanboard#787]
Is there a way to print a board?  My client doesn't have access to our intranet and it's easiest for us to email them a copy of the board.  When I click file / print, I lose all of the formatting, which makes the print unusable.  Any thoughts?  I found

**Comment by akluthe** [comment]
It's funny that this got posted 22 hours ago. I was just coming here to search and trying to find a way to improve the printability of individual cards as well.

The "Public Link" versions seem to be the best option for that for me right now.

**Comment by fguillot** [comment]
I have to add a stylesheet optimized for print. I never thought that people would like to print the board.

**Comment by fguillot** [comment]
I have added a print stylesheet in the development version but you might have some issues with boards with a lot of columns (doesn't necessary fit in the page).

**Comment by EthraZa** [comment]
Just tryed to print a board and it got... strange. 

But I was looking for to print cards/tasks to use then as stickers on a white board. Same as Chrome addon called **Board printer for Trello** does.
So maybe o CSS for print tasks only or maybe a export tasks option would be cool.

Electronic boards are cool, but if you don't have a TV to display it, people will forgot about it. It needs to be always visible to everyone, as a clock on a kitchen's wall.

**Comment by erpnedir** [comment]
Hi,
How can I test the print stylesheet ?

**Comment by cboulanger** [comment]
Hi, I would be interested, too. Being able to print the present state of the board would be a good addition.
