### ISSUE TITLE
[Website] RSS feed broken

### ISSUE THREAD

**Issue by EpocDotFr** [fguillot/kanboard#789]
The [RSS feed](http://kanboard.net/feed) of the kanboard news is broken : http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fkanboard.net%2Ffeed

All parsers fail parsing because of a special caracter (`&`) in the last article title. Maybe an issue linked to picoFeed (if you use it to write feeds) ?

**Comment by fguillot** [comment]
Thanks, it's fixed now.
