### ISSUE TITLE
Have categories for projects

### ISSUE THREAD

**Issue by hicter00** [fguillot/kanboard#790]
A new feature might be to have groups of projects combined into a program. I have multiple programs that I run, each with many projects (or boards).  The list under "display other project" can get very long and hard to find if you have so many projects.  Thoughts?

**Comment by fguillot** [comment]
What do you mean by "programs", a category?

**Comment by shimza** [comment]
No, category is used for many different things by people.

Programs are groups of projects...
Say ms office is a program and word is a project. You wouldn't say ms office a category, would you?

Cheers,

Shimon Friedman 
Mob: 0403067613

**Comment by hicter00** [comment]
The way I think of it is a main project and sub-project .  You could then allow PM / admin rights to "part" of the application to them.

ie.,Project/program Launch new product
sub-project new microsite for product
sub-project new packaging 
sub-project new marketing

each of these is a project , but under the program of launch new product

**Comment by fguillot** [comment]
Sorry, I prefer to keep Kanboard simple so this feature won't be developed.

**Comment by atelierscym** [comment]
Hello all,
I was searching for a way to 'categorize' projects in KB, I'm disappointed that this feature will not be implemented. My use case would be to manage separately projects, for instance with a list of all projects regarding "security", then another list regarding "budget", a 3rd on regarding "equipment", etc. Project and sub-projects could be an option : as simple as adding a field 'id_parent' in project table ;-P (I know it's not that simple). As well tags should do the job.
Regards, and congrats for the nice program ;-)
