### ISSUE TITLE
[FR] Menu item or hotkey - Expland all swimlanes + reset all filters

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#793]
I'm a bit off the KB issue forum wagon, haven't read up on the issues list lately, so appologize if this is a duplicate.

After raiding and rambling with filters on a board to zoom down on a specific thing I want to work with or check out, I wish to "zoom back out" in a quick way - that is: expand all swimlanes and empty all filters. 

**Use case:** Board with tasks for several people and categories/swimlanes to separate things.

Wish for this as function on menu or hotkey.
Currently running on 1.0.13 - I like it! =)

**Comment by fguillot** [comment]
There is now a keyboard shortcut to reset all filters (key "r").

**Comment by sparkles645** [comment]
Tnx. =)
