### ISSUE TITLE
[FR] Filters - Due today, Past Due, Upcoming

### ISSUE THREAD

**Issue by hicter00** [fguillot/kanboard#795]
In a large board, the ability to filter on dates would be beneficial.  Yes, you can see it in calendar view, but, that means when walking the board you have to change views.

**Comment by BlueTeck** [comment]
:+1:

**Comment by BlueTeck** [comment]
This is possible: https://github.com/fguillot/kanboard/blob/master/doc/search.markdown#search-by-the-due-date

Issue could be closed.
