### ISSUE TITLE
Automation move task to different project does not work

### ISSUE THREAD

**Issue by lasselicht** [fguillot/kanboard#797]
The automation to move a task on close or change column does not work. 

We use mysql and only have two projects.

**Comment by fguillot** [comment]
I'm sorry but I'm not able to reproduce your issue, can you describe the exact procedure? Do you have any error message?

**Comment by nedelenbos** [comment]
As a colleague of @lasselicht, I can confirm that this one was a mistake on our side, so this issue can be closed :)
