### ISSUE TITLE
[Open Q] - is KB at risk of catching featureitis?

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#799]
Perhaps @fguillot does not wish this discussion out there - **if so, please close/delete this issue.**

After observing the development of the issues list over a few months after I got KB-hooked, there is no doubt that the **number of FR's** are quickly adding up.

@fguillot , as a proclaimed minimalist -  is perhaps not happy/willing to follow through with all requests - in order to protect the simplicity. 

So far, IMHO, @fguillot has been doing a nice job as "captain of the ship" in sorting out what is useful and what is "for special needs only". A lot of featues have been added in the latest versions, yet KB is still being kept within a framework of simplicity. 

**The utter simplicity** is what attracted me to KB in the first place, a claim that might be true for more of you - and is perhaps what will be the trigger also for future users/discoverers.

After screening the FR's currently in the list:
Is KB at risk of heading towards "over-complification"?
**How to prevent KB from getting "featur-itis"?**

**Out of respect**, the following needs to be mentioned: 
@fguillot does most of the heavy lifting, with good help from a small minority contributing with actual code - but the majority of us, myself included, are perhaps just "asking for more" without putting in the work nor considering the consequences for the direction KB is taking. Thus, the opinions from heavy, long time users & active contributors should weigh-in the most.

**Please comment**: how to prioritize heading forwards: 
**Keep it simple at all cost, or allow adding certain layers of complexity, even though that might scare away new users?**

![featureitis](https://cloud.githubusercontent.com/assets/10092252/7105707/1c5f6266-e126-11e4-9703-df2c521a9242.jpg)

**Comment by fguillot** [comment]
Don't worry, Kanboard will not become a bloated and a complex software.

Features can be added if:

- That improve something, by example make the user interface more efficient to use
- Add a business value
- Doesn't slow down the software
- The source code is simple and doesn't bring too much external dependencies

Everything else should be only improvements of the existing features.

If people wants a software very configurable with unlimited options there is Jira for that.

I don't necessary implement all asked features. Same thing for the cool frameworks or libraries of the moment, I don't care about hipster technologies.

**Comment by AlgyTaylor** [comment]
Thin @fguillot is doing a pretty good job already at keeping everything focused.

I'd guess perhaps the way forward would be just to keep within the unix philosophy - allow anything to hook up to the input/output of kanboard. so that it remains a (very strong) component which does one thing very well. Then you can 'pipe' other components in to / out of it and have your purpose-built custom system if you want ... or just use KB as a standalone piece of software.

**Comment by ashbike** [comment]
:+1:  Though slightly off-topic, it appears Aaron Seigo (Core KDE contributor) find Kanboard 'a must-have tool' http://goo.gl/YU0Xsk and like the way it does things.
