### ISSUE TITLE
Support mention @users in comments or cards

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#801]
Support mention eg. '@user' in comments or description in cards.

**Comment by BlueTeck** [comment]
And what should happen if mention a user in the description?

**Comment by valessiobrito** [comment]
Add notification in task or timeline?!  Support link to profile or filter others tasks with mention in project?!

**Comment by nedelenbos** [comment]
An e-mail could be sent as well, or perhaps support for custom integrations (ex: in our team we use Slack for instant messaging, it would be cool if we could configure Kanboard to post a message on slack messaging someone that he/she has been notified..)

**Comment by prospeh** [comment]
the @username would be such a fantastic feature, especially used together with Slack. Would love to see this

**Comment by DoumeDuSud** [comment]
+1 for this fonction :-)

**Comment by mcbejn** [comment]
another +1 here :D

**Comment by maxpowis** [comment]
I looking forward to this one too!

**Comment by letsgo008** [comment]
+1

**Comment by imeleges** [comment]
+1 it will be great to have this option!

**Comment by imeleges** [comment]
+1 it will be great to have this option!

**Comment by gabrielprioli** [comment]
+1

**Comment by gbc921** [comment]
+1

**Comment by dromek** [comment]
+1

**Comment by samwilson** [comment]
+1

**Comment by mcbejn** [comment]
Guys this is one of the top 5 feature requests as I can see on the list. 
@fguillot is there any chance you could give us some info on if and when this might be implemented?

Or surprise us and say that it's already on the way? :)
Thanks

**Comment by fguillot** [comment]
@mcbejn I cannot give a date, there is so many stuff to improve and my time is limited. But I agree this feature is interesting.

**Comment by mcbejn** [comment]
Completely understandable and thank you for the quick answer, hope you get some time for it soon :beers:

**Comment by valessiobrito** [comment]
@fguillot @mcbejn If each person vote with $$$ collaboration can speed up the implementation.
I create the issue in  https://www.bountysource.com/issues/11051693-support-mention-users-in-comments-or-cards

You using and would like to support this functionality, make a small contribution.

**Comment by epaiva** [comment]
+1 = US$5 

this would be a really useful issue!!

**Comment by fguillot** [comment]
Hi guys,

I started to implement this feature, at the moment the application is able to parse the Markdown content to detect @user mentions and link that to the profile of the user.

What do you expect from this feature? What kind of notification the mentioned user should receive from a task or a comment?

**Comment by prospeh** [comment]
That sounds great Frederic, thanks!
And great idea of @valessiobrito to start the campaign to support it - we will definitely do a +1. Didn't see it so far, sorry.

As for the feature, it would be fantastic if we could see a notification when a user is mentioned in a comment or task description. For us really the implementation doesn't matter that much as long as we can have our devs just somehow be notified in Slack so they know they should check out the task.

Example: I want a user to check out a discussion on task #123 so i tag him with @user . 
A notification can be posted on a specific Slack channel saying "Hey @user, you were mentioned in task #123. Click on this URL to see what it's about ". This way Slack will automatically notify the user (because of @user).

Or even better - the notification might be send directly to the user. This would be perfect

**Comment by fguillot** [comment]
User mentions are now available in the development branch, so you can try the feature and report potential bugs.

**Comment by valessiobrito** [comment]
owwww, thanks a lot!  clap clap clap

**Comment by fguillot** [comment]
The first iteration of this feature is available in the new stable version: http://kanboard.net/news/version-1.0.23

**Comment by marcosaccioly** [comment]
As of 1.0.30 this feature does not work. I have seen an issue somewhere related to the markdown WYSIWYG box, but could not find it to link here. How is this going?

@valessiobrito the campaign is a great idea! I've also donated. 

P.S.: just as an off topic, you and I have already met in person, @valessiobrito at the Claro 2011 Campus Mobile at USP. Funny thing.

**Comment by idchlife** [comment]
@fguillot user mentions still don't work. Maybe I'm not seeing instructions how to enable them?

1.0.23

**Comment by fguillot** [comment]
See #2045
