### ISSUE TITLE
Kanboard on IIS7

### ISSUE THREAD

**Issue by gbrethen** [fguillot/kanboard#802]
PHP 5.6 installed using Web Platform Installer.  PHPInfo working well.

Kanboard unzipped.  

I go to Localhost/kanboard and nothing?  just sits there.  No error, nothing.

What am I missing?

**Comment by BlueTeck** [comment]
Did you read the help?
http://kanboard.net/documentation/windows-iis-installation

**Comment by gbrethen** [comment]
yes...I have followed the instructions.

**Comment by fguillot** [comment]
What do you mean by nothing? error 500, blank page? nothing in the error log of IIS?

**Comment by gbrethen** [comment]
blank page...looking in chrome developer tools, I see 500 internal server error

**Comment by gbrethen** [comment]
installed on local box (Windows 8, IIS 8) everything works fine.  Not sure what is missing on the server.

**Comment by fguillot** [comment]
You should see the exact error message in the IIS error log files. Maybe there is a php extension not enabled?

**Comment by gbrethen** [comment]
nothing in the event viewer

**Comment by gbrethen** [comment]
IIS Manager could not load type 'Web.Management.PHP.PHPProvider, Web.Management.PHP, Version=1.2.0.0, Culture=neutral, PublicKeyToken=8175de49a9aec91d' for module provider 'PHP' that is declared in %windir%\system32\inetsrv\config\administration.config.

**Comment by akluthe** [comment]
Worked fine for me this week with Windows Server 2008 R2 (php 5.4) and Windows 7(php 5.5) both running IIS 7.5 without additional config besides making data folder writable. 

I even managed to hack in Active Directory support using IIS Windows Authentication and Reverse Proxy mode when I couldn't get the default LDAP stuff to work with our AD setup via php's LDAP extensions. Wouldn't want to expose it to world like that, but for an intranet situation (where you'll most likely be forced to working with IIS) this was just what we needed.

As for your issue, I've seen this related to weird stuff in the web.config. I didn't need a web.config in the root of my applications folder for kanboard. Do you have one in yours?

**Comment by gbrethen** [comment]
Got it working.  needed C++ redist.  works fine now, and even got it working with Active Directory.
