### ISSUE TITLE
What changed in v1.0.13? :-)

### ISSUE THREAD

**Issue by richmaclannan** [fguillot/kanboard#803]
Just downloaded the latest version. Could you let us know briefly what changed? 

Apologies if you've already issued release notes; I couldn't find them.

And thank you. This product is *very* useful.

**Comment by BlueTeck** [comment]
See the news on kanboard.net

**Comment by richmaclannan** [comment]
What a muppet I am. I even looked there.

Thank you, and sorry for the distraction.

Rich M

Am Dienstag, 14. April 2015 schrieb Timo :

> See the news on kanboard.net
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fguillot/kanboard/issues/803#issuecomment-92762575>.
>


-- 
Sent from a mobile device; please excuse typos or unusual brevity. :-)
