### ISSUE TITLE
Toggling Compact view and Horizontal scrolling does not work in IE - (KB v 1 0 1 3)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#804]
Tested toggling between Compact view / Horizontal scrolling with Firefox v 37 0 1 - **works like a charm**. 

Tested with IE v 9 and with IE v 11. 
Result: Stuck in Horizontal scrolling.

* Hotkey 'c' does not work, **nothing happens**.
* Menu item "Compact view" does not work, **nothing happens**.

(Why on green earth would you use IE, you say? Am I mentally challenged?)
Answer: Policy. No free choice.

This is a hitch in terms of implementing KB 1 0 1 3 on our "big server".

**Comment by diego-betto** [comment]
.board-container-compact #board {
	table-layout: auto;
}

**Comment by fguillot** [comment]
@diego-betto Thanks for the fix

@sparkles645 It's now fixed in the development branch, thanks for reporting this issue.
