### ISSUE TITLE
Ability to enable two factor at user level, but "Administrator" cannot disable

### ISSUE THREAD

**Issue by worsco** [fguillot/kanboard#806]
I am running kanboard-latest.zip (April 6, 2015) on CentOS 6.6 with php56 (5.6.7) installed from the remi repo.

I can enable two factor and test the two factor code successfully with FreeOTP Version 1.5 (Android) on a user account.  However, attempting to log in with two factor fails.

Since that user account can no longer log into Kanboard, I don't see a method (logged in as an Administrator account) to disable two factor on another account.  

Can a Administrator account disable two factor or do I have to issue a SQL command into the DB to manually to disable two factor?

**Comment by fguillot** [comment]
Yes, I need to add this feature for the next version, at the moment admins can't reset the 2FA for a user.

Temporarily, you can update the user profile directly in the database, a sql query like that should work:

```sql
UPDATE users SET twofactor_activated=0, twofactor_secret='' WHERE username=?;
```
( replace the username value)

**Comment by worsco** [comment]
Here's the full how-to for those using the default sqlite database and the sqlite command line interface:

1. Change to the 'data' directory for kanban (I was sudo as root -- just ensure that your user has the permissions to write the the db.sqlite file -- typically 'apache' or the user of your web server)
2. Launch sqlite3 command line specifying sqlite database file
'''
sqlite3 db.sqlite
'''
3. Then disable two factor (replace "?" with the actual username):
'''
UPDATE users SET twofactor_activated=0, twofactor_secret='' WHERE username=?;
'''
4. ^D to exit sqlite cli (or .quit or .exit)

**Comment by fguillot** [comment]
It's now possible in the development branch.
