### ISSUE TITLE
Dude with spanish translation

### ISSUE THREAD

**Issue by EstebanMonge** [fguillot/kanboard#807]
Hello:

I have one dude with spanish translation. For example:
'Tasks exportation for "%s"' => 'Exportación de tareas para "%s"',

In other cases I found:
'Tasks exportation for "%s"' => 'Exportación de tareas para «%s»',

And finally:
'Tasks exportation for "%s"' => 'Exportación de tareas para %s',

What is the correct way?

**Comment by dbinagi** [comment]
Hello Esteban, I assume that by "Dude" you meant "Doubt" right?

About your question, i think all of them are correct. 

If you use the first one, you are adding commas to the string.
Second one you will add that symbol "«" surrounding the string.
And last, you just have the string with no additions.

Depends on how you want to show the information which you chosse.

Regards.

**Comment by fguillot** [comment]
The « and » are the French quotation marks (http://en.wikipedia.org/wiki/Guillemet). I think they have been copy/pasted from the french translation by previous contributors.

The Spanish translation should use the Spanish quotation marks notation: http://en.wikipedia.org/wiki/Quotation_mark#Spanish

I'm not Spanish but I think that should be  « and » without spaces according to Wikipedia.
