### ISSUE TITLE
Expand search scope

### ISSUE THREAD

**Issue by JohnnyGW** [fguillot/kanboard#811]
I've found from my tests (correct me if I'm wrong) that the search box only searches within titles and doesn't search descriptions or other fields. It would be good to search at least descriptions too.

**Comment by epaiva** [comment]
We also miss a lot this feature!

**Comment by elfalem** [comment]
I would also appreciate this feature.

**Comment by fguillot** [comment]
With the last dev version, you can search inside task description with the attribute description: `description:"my text to find"`.

**Comment by raphaelbastide** [comment]
Just curious: What is the reason searches in descriptions are not the default behavior?

**Comment by fguillot** [comment]
Because it might be slower.
