### ISSUE TITLE
Task cannot load if url in description too long

### ISSUE THREAD

**Issue by JohnnyGW** [fguillot/kanboard#813]
If I insert a link of the type [My link title](http://kanboard.net/) in the description field of a task and the URL is very long I get an error when trying to access that task.

**Comment by fguillot** [comment]
Do you have an example of description?

**Comment by fguillot** [comment]
If you want me to fix the bug, I need to be able to reproduce the issue...

**Comment by JohnnyGW** [comment]
Sorry I didn't see your emails before.

I tried to add a description like this one:

[PMO 20150249 - Supernet Empresas](
http://kosmos.produban.gs.corp/group/seguimiento-pmos-bbdd-ssmm-boadilla/home/-/blogs/pmo-20141486-ibero-sareb?_33_redirect=http%3A%2F%2Fkosmos.produban.gs.corp%2Fgroup%2Fseguimiento-pmos-bbdd-ssmm-boadilla%2Fhome%3Fp_p_id%3D33%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-2%26p_p_col_pos%3D2%26p_p_col_count%3D3
)

That causes an  ERR_CONNECTION_RESET error in Chrome when trying to click
the task to see its details.

I know I can shorten that url by taking out everything after the question
mark but some of the users of our kanboard site have incurred in the same
problem. That forces me to edit the comment field in the database (I'm
using MySQL and the latest stable version of kanboard *1.0.13*)

Maybe the problem is not the length but something in the url. I didn't
think about that before.

Thanks a lot and sorry for not replying sooner

**Comment by fguillot** [comment]
I'm not able to reproduce the issue. I can put your example in the task description or in a comment without any problem. However, the link seems to be broken, the domain name doesn't resolve but that nothing to do with Kanboard.

**Comment by JohnnyGW** [comment]
That's strange. I've tried in two different kanboard installations and I
get the same error. I'll try to do a bit more testing to send you my
conclusions (different database, different version of kanboard, etc). Thanks
