### ISSUE TITLE
Question: Install Postgresql Problem

### ISSUE THREAD

**Issue by tekuton** [fguillot/kanboard#814]
Hi, I always get a blank page when trying to install with Debian Wheezy, Apache and Postgres.
Any hints?
thank you
tekuton

**Comment by fguillot** [comment]
Check the apache/php error logs, you should see the exact error.

**Comment by tekuton** [comment]
The setup of a postgres is something to be better supported elsewhere.
My setup is working now. Anyone in need of little help with a psql set-up - may drop me message.
Thx
