### ISSUE TITLE
Simple task query for better search

### ISSUE THREAD

**Issue by yuichi1004** [fguillot/kanboard#816]
I use Kanbord for my project but sometimes it is hard to find the old tasks. I think that simple task query language would improve the task search. The example query looks like the following:

```
My Keyword status:closed category:feature before:2015/04/20 assignee:me 
```

This would enable Kanbord to support advanced task search feature while we can keep the UI simple.

I'm thinking see if I can contribute to the code. I think it is better to implement this feature on TaskFinder.php or separated model class so that we can possibly reuse the mechanism to the other features.

Anybody agree? Thought?

**Comment by fguillot** [comment]
Yes, it's interesting. The most difficult part seems to build the query parser.

**Comment by fguillot** [comment]
The same feature can be used directly on the board. Then the board could display dynamically the result of any query.

Having something similar to Github issues (search/filter box) will be very interesting.

**Comment by yuichi1004** [comment]
+1 to dynamic board result.
I'd like to keep the simple code. So I would start playing with regex or some simple parser libraries.

**Comment by fguillot** [comment]
To some extent, I'm thinking about replacing the filter box that looks like an input field by a search box. And a display mode toggle button. Then it will be easy to display the search result as a list view, a board view or a calendar view.

**Comment by yuichi1004** [comment]
I like the idea that can reuse the same filter/search UI to each view.

**Comment by yuichi1004** [comment]
I have found that it is difficult to parse the query with regex if we introduce some complexed query with brackets/quotations. I am looking into some PHP parser library like the following.

* https://github.com/hafriedlander/php-peg
* https://github.com/relaxnow/QueryLang

I am working on experiments with those libraries...

**Comment by yuichi1004** [comment]
Sorry to a bit late update but the prototype of the parser is implemented. The parser code can be implemented minimal codes and flexible to change thanks to php-peg.

The following is the example of queries and their result.
https://gist.github.com/yuichi1004/51ded0a963815124eaac

Currently I am planning to start implementing the search based on the following.
https://github.com/yuichi1004/kanboard/blob/feature/task_query/docs/advanced-search.markdown

**Comment by fguillot** [comment]
What about using a simple Lexer?

After reading some articles I build a quick and dirty prototype to test the idea:

```php
<?php

class Lexer
{
    protected $tokenMap = array(
        "/^(OR)/"           => 'T_OR',
        "/^(assignee:)/"    => 'T_ASSIGNEE',
        "/^(color:)/"       => 'T_COLOR',
        "/^(\s+)/"          => 'T_WHITESPACE',
        "/^(\w+)/"          => 'T_IDENTIFIER',
    );

    public function tokenize($input)
    {
        $tokens = array();
        $offset = 0;

        while (isset($input[$offset])) {

            $result = $this->match($input, $offset);

            if ($result === false) {
                throw new Exception('Unable to parse query');
            }

            $tokens[] = $result;
            $offset += strlen($result['match']);
        }

        return $tokens;
    }

    public function match($input, $offset)
    {
        $string = substr($input, $offset);

        foreach ($this->tokenMap as $pattern => $name) {
            if (preg_match($pattern, $string, $matches)) {
                return array(
                    'match' => $matches[1],
                    'token' => $name,
                );
            }
        }

        return false;
    }
}


class Compiler
{
    public function build(array $tokens)
    {
        $query = 'SELECT * FROM tasks WHERE ';
        $conditions = array();

        while (false !== ($token = current($tokens))) {

            switch ($token['token']) {

                case 'T_ASSIGNEE':
                    $nextToken = next($tokens);
                    $conditions[] = 'owner_id = '.$nextToken['match'];
                    break;

                case 'T_COLOR':
                    $nextToken = next($tokens);
                    $conditions[] = 'color_id = '.$nextToken['match'];
                    break;
            }

            next($tokens);
        }

        return $query.implode(' AND ', $conditions);
    }
}

$lexer = new Lexer;
$tokens = $lexer->tokenize('assignee:me color:blue');

$compiler = new Compiler;
echo $compiler->build($tokens).PHP_EOL; // SELECT * FROM tasks WHERE owner_id = me AND color_id = blue
```

The lexer parse the query and output all tokens:

```php
Array
(
    [0] => Array
        (
            [match] => assignee:
            [token] => T_ASSIGNEE
        )

    [1] => Array
        (
            [match] => me
            [token] => T_IDENTIFIER
        )

    [2] => Array
        (
            [match] =>
            [token] => T_WHITESPACE
        )

    [3] => Array
        (
            [match] => color:
            [token] => T_COLOR
        )

    [4] => Array
        (
            [match] => blue
            [token] => T_IDENTIFIER
        )

)
```

From there, the Compiler class can build a SQL query or use PicoDb to generate the SQL.

Here are some reading:
- http://nitschinger.at/Writing-a-simple-lexer-in-PHP
- http://nikic.github.io/2011/10/23/Improving-lexing-performance-in-PHP.html
- http://jwage.com/post/31623163785/writing-a-parser-in-php-with-the-help-of-doctrine

I think this approach still simple enough and it's easier to understand than an external library than generate code from a grammar. What do you think?

**Comment by yuichi1004** [comment]
I think that works for simple cases. This approach gets complexed if we introduce phrasing or grouping like the following cause the tokenizer needs to be aware of its context.

```
assignee:"John Smith" NOT (category:Research OR category:"Bug Fix")
```

The advantage of my prototype is minimal lines of code.
https://github.com/yuichi1004/kanboard/blob/feature/task_query/app/Libs/KQLParser.peg.inc

I think it's tradeoff between our code complexity and dependency to the 3rd party. I prefer to keep our code minimal so I took this approach but I am also comfortable to write our tokenizer.

**Comment by fguillot** [comment]
With both methods you have to build a sql query based on the output array tree (http://en.wikipedia.org/wiki/Abstract_syntax_tree).

It's always possible to improve the basic Lexer above to parse a subquery with another regex, by example  `'/^(\([^\)]+\))/'` match everything in parentheses.

The thing I don't like is that php-peg generates php code and the result array is hard to manipulate to build the final sql query. I prefer to have less feature, maybe something too simple but with a code that I can understand...

I will see if I can get some examples from other open source projects. Maybe I'm wrong...

**Comment by yuichi1004** [comment]
I understand your point. I agree that PHP code generation process is the biggest cons of pho-peg.
Let's start with something small and improve it later.
I would start working with lexicer

**Comment by fguillot** [comment]
Did you make any progress?

It's ok if you don't have time, I will try to improve my prototype and make it work in Kanboard...

**Comment by fguillot** [comment]
It's rainy today, so I started to implement the "advanced" search query. At the moment, it's very alpha, there is only 3 criteria: "assignee, due and color", more attributes are coming...

The queries are inspired by the search syntax of Github Issue and your proposition. I don't support complex query with OR/AND and parenthesis to keep the code simple.

You can do queries like that: `assignee:me due:tomorrow color:"Light Green" my task title` or `due:>=2015-07-01 assignee:"John Doe"` etc... More example in the doc: https://github.com/fguillot/kanboard/blob/master/docs/search.markdown

I will probably change the user interface to have a global search page and see if I can use the same system to filter tasks on the board.
