### ISSUE TITLE
Error in counting listing tasks using filter

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#817]
In list filter tasks by category the count in the column does not update. 

![bug-count-list-tasks](https://cloud.githubusercontent.com/assets/310049/7218164/73123428-e633-11e4-804a-b64d62d702dc.png)

Proposal: This count could be performed on the client side, using JS, providing real-time count.

**Comment by fguillot** [comment]
This doesn't happen anymore with the last master.
