### ISSUE TITLE
Ability to add a custom stylesheet to an individual board.

### ISSUE THREAD

**Issue by labo-css** [fguillot/kanboard#819]
That would be nice for branding, additional info, etc...

**Comment by fguillot** [comment]
You can already do that.

- Go to Settings > Application > Custom stylesheet
- Each board have a unique css class "board-project-ID", by example "board-project-2"
- So each board can be customized and probably anything in the user interface

**Comment by labo-css** [comment]
I think i love you.
Many thanx!
