### ISSUE TITLE
receiving directory "data" must be writeable by your web server user on new kanboard install (W2012R2/IIS8.5)

### ISSUE THREAD

**Issue by mwatson2020** [fguillot/kanboard#823]
hi, I'm attempting to install kanboard version 06-april-2015 on Windows 2012R2/IIS 8.5 using PHP 5.3.28. and I receive the error: 'The directory "data" must be writeable by your web server user' when I browse to 
-I verified PHP is installed correctly (successfully see PHP information by browsing to phpinfo.php inside of the root directory in IIS)
The ApplicationPoolIdentity (DefaultAppPool user) has write permissions to .../kanboard/data/.

I cannot put my finger on why kanboard is reporting that it cannot write to the kanboard/data folder.  

any help would be appreciated...

thanks!

**Comment by mwatson2020** [comment]
Well, I sort of got it working.  I went ahead and granted Write permissions to the local user [computername]\users on the data folder.  I thought IIS would be using the [computername]\IIS_IUSRS or DefaultAppPool account.  I even tried to use my own domain account as the account for the app to run under and granted my domain account write permissions to the data folder and it didn't work.  

anyways, any ideas on how to make it more elegant - that would be great.

**Comment by fguillot** [comment]
Windows permissions management are always funny... Sometimes the issue come from the parent directory.

**Comment by erpnedir** [comment]
You saved my day! Sounds silly but giving permissions to Users group solved the issue for me too.
Thanks.
