### ISSUE TITLE
Not able to see "Cumulative flow diagram"

### ISSUE THREAD

**Issue by hbulgarini** [fguillot/kanboard#825]
Hello, 

First of all i really would like to thank you for the excellent application that you are providing.

I'm actually running the stable version of kanboard but i was not able to run the "cumulative flow diagram".

Basically i have created tasks for one user with start dates,categories and time estimated in every column.
Once the tasks are created i proceed to execute the following command , which i think populates the table "project_daily_summaries":

./kanboard   projects:daily-summary

Then i proceed to go to Analytics-> Cumulative flow Diagram and i always recieve the same result it doesn't matter what start/end date i define:

"Not enough data to show the graph."

The message is really clear to me, but what i don't understand is why i recieve that when i have existing tasks created in each column. Is it maybe that i'm missunderstanding the purpose of the cumulative flow report function?
Actually i have checked the table "project_daily_summaries" and the quantity of tasks per column matches with the number of tasks created.

Another question, are you currently planning to include tags for each activity? Has the current stable version that functionality?

Thanks in advance!
Hector

**Comment by fguillot** [comment]
You need to have at least 2 days of data to show the graph, is it your case?

**Comment by hbulgarini** [comment]
Hello, no. Is not my case.. i will wait 2 days .

Thanks!
