### ISSUE TITLE
Upgrade kanboard and msgs error.log apache

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#826]
Hi all,  I update kanboard from git master and msg error.log in apache:

[Thu Apr 23 20:08:34.168919 2015] [:error] [pid 1094] [client xxxx:58391] PHP Catchable fatal error:  Object of class PicoDb\\Table could not be converted to string in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 231, referer: http://xxx/kanboard/?controller=task&action=duplicate&task_id=433&project_id=26

[Thu Apr 23 20:09:37.117091 2015] [:error] [pid 442] [client xxxx:34387] PHP Catchable fatal error:  Object of class PicoDb\\Table could not be converted to string in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 231, referer: http://xxxx/kanboard/?controller=task&action=description&task_id=190&project_id=26

[Thu Apr 23 20:15:14.488578 2015] [:error] [pid 1128] [client xxxx:58409] PHP Catchable fatal error:  Object of class PicoDb\\Table could not be converted to string in /var/www/html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php on line 231, referer: http://xxxxx/kanboard/?controller=task&action=edit&task_id=434&project_id=26

**Comment by fguillot** [comment]
I cannot reproduce your issue. Did you run a `composer install`?

You can use the nightly build package if you prefer: http://kanboard.net/kanboard-nightly-build.zip

**Comment by valessiobrito** [comment]
@fguillot thanks for the attention and the work being done in kanboard.

In a new installation (from nightly build) presents no error message in the log (error.log).

Updating my production version (kanboard from git), the error appears when I save a new task. Getting the blank page.

I believe it may have been something in the database that did not migrate / upgrade done correctly. 

http://domain.local/kanboard/?controller=task&action=save&project_id=1

**Comment by valessiobrito** [comment]
I removed the old installation. Set up a new installation preserving only /data/files

The errors in log stopped.

I believe that can be /data/cache or something related to that.

Thanks.
