### ISSUE TITLE
Search doesn't find any task

### ISSUE THREAD

**Issue by oparoz** [fguillot/kanboard#828]
### Steps to reproduce
1. Go to a project
2. Type a few words

### Actual result
Nothing happens

### Expected result
There should be a list of tasks matching that query

### Logs
Firefox complains with `no element found`
The URL is 304.
`?controller=board&action=check&project_id=1&timestamp=1429883551&_=1429883551870`

**Comment by fguillot** [comment]
I cannot reproduce your issue. The url that you mention have nothing to do with the search, it's to check if the board have been modified by someone else.

Are you talking about about the search box on the page `?controller=project&action=search&project_id=ID`?

**Comment by oparoz** [comment]
Yes, I'm talking about the search box sitting at the top of the board, in the middle. I get a "No results match" as soon as I type anything.
That project controller is never called. The only calls which are made, are made to the board controller.
Filtering by "due date" or "recently updated" works, but that's not calling anything on the server side.

**Comment by oparoz** [comment]
I've tested on Chrome and as an admin and same result. That field doesn't send any event to the server.

**Comment by oparoz** [comment]
Maybe it's simply a misunderstanding about what the field can do.
It says "More filters". I assumed I could add some key words and only get the tasks containing those words.

**Comment by fguillot** [comment]
It's not a search box, it's just a field to add one or more filters.

However, in the future that will be replaced by a search box as discussed in the ticket #816.

**Comment by oparoz** [comment]
Great :). Closing this then.
