### ISSUE TITLE
JSON API for getting/setting task links.

### ISSUE THREAD

**Issue by macce** [fguillot/kanboard#833]
I am thinking of writing a python script that fetches tasks from a kanboard project and outputs a graphviz file to display tasks with dependencies shown as arrows. It seems as if *jsonrpc.php* is missing API functionality for exposing the task link structures though. Being able to access the links would be valuable!

Brgds,
Marcus

**Comment by fguillot** [comment]
It's now available in the development version, see here: https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getalllinks

**Comment by macce** [comment]
Great, thanks a lot!

/Marcus
