### ISSUE TITLE
iFrame with Sharepoint

### ISSUE THREAD

**Issue by iM4rv** [fguillot/kanboard#834]
Hey there, remarkable work. I tried to integrate the kanboard in my Sharepoint 2013 Site using iFrames (<iframe src="myurl/kanboard" style="width:1000px; height: 600px; </iframe>) but as discussed in #309 and #466 iFrames dont work :( 

I unsuccessfully tried the solutions provided in #309 and #466 so can you give me a detailed step by step instruction? I'm quite sure i ve tested the provided solutions properly so im not exactly sure what ive done wrong.

Thx in advance 
Best,
Marv

**Comment by BlueTeck** [comment]
Maybe this could help: https://github.com/fguillot/kanboard/issues/466#issuecomment-84463003

**Comment by iM4rv** [comment]
@BlueTeck I tried define('ENABLE_XFRAME', false); and define('ENABLE_XFRAME', true); but there s still a white, blank page with no error or something. Just white screen.

**Comment by iM4rv** [comment]
Solution: Set both to false as seen below 


// Enable or disable "Strict-Transport-Security" HTTP header
define('ENABLE_HSTS', false);

// Enable or disable "X-Frame-Options: DENY" HTTP header
define('ENABLE_XFRAME', false);

**Comment by fguillot** [comment]
Issue seems to be solved.
