### ISSUE TITLE
Task Linking is not working

### ISSUE THREAD

**Issue by noktork** [fguillot/kanboard#837]
Hello!
Really have to thank you for a fantastic implementation of Kanban!
I'm running 1.0.13 on a debian 7 server. We have trouble getting the task linking to function.
It doesn't matter what label we select, there is no list of task to select for linking.
What ever we type in the Task box does not make the save button clickable.

**Comment by oliviermaridat** [comment]
Hi noktork,

Normally, if you start typing the title of one of your task in the field, you should see the dropdown list. Once a valid task has been selected, the "Save" button becomes clickable.

![capture d ecran - 29042015 - 15 36 36](https://cloud.githubusercontent.com/assets/953989/7392121/db53616a-ee85-11e4-840d-67278d371649.png)

**Comment by noktork** [comment]
Hello!
Thanks for the information, i missed that part.
We tried with ticket number, then no list present it self.
Thanks again!

**Comment by oliviermaridat** [comment]
I had the same reaction. Make this field work with both a task number and a task title could be great (see #669).

**Comment by fguillot** [comment]
The auto-completion works with the task number now (master branch).
