### ISSUE TITLE
No acess to "User management" for remote users (created via LDAP)  

### ISSUE THREAD

**Issue by edrthomas** [fguillot/kanboard#838]
I have successfully configured LDAP authentication. When I log in with LDAP credentials, a new remote user is created. 

But when I create a new project with this user, I don't see the "User management" section in the project configuration. So I can't add other users.

Also when I log in as admin, I do see the section but no user shows up which makes sense since all the users have been created the same way so far (after a first login with LDAP credentials.)

![user](https://cloud.githubusercontent.com/assets/8439341/7401936/24c59290-eec8-11e4-88b9-3847d7366deb.jpg)

**Comment by BlueTeck** [comment]
Did you create a private or public project?  See http://kanboard.net/documentation/creating-projects

**Comment by edrthomas** [comment]
I created a private project. Does private mean only for me?

-------- Original message --------
From: Timo
Date:30/04/2015 07:50 (GMT+01:00)
To: fguillot/kanboard
Cc: "Thomas, E.D.R. (Emmanuel)"
Subject: Re: [kanboard] No acess to "User management" for remote users (created via LDAP) (#838)


Did you create a private or public project? See http://kanboard.net/documentation/creating-projects

—
Reply to this email directly or view it on GitHub<https://github.com/fguillot/kanboard/issues/838#issuecomment-97669524>.
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by edrthomas** [comment]
For information, I have made the project public but it doesn't change anything.

**Comment by lazki** [comment]
Yes, private means **only you**. As an LDAP user, I've managed to create a new project and User Management appears in the menu.

**Comment by edrthomas** [comment]
Thanks @lazki ! I had indeed created a private project. By setting the LDAP user as Administrator, I can now create team projects and add other users.

That being said, isn't it a bit odd that you need to be Administrator to create team projects ? Project leader and Administrator are different roles and usually different persons too, aren't they ?
