### ISSUE TITLE
Kanboard Presenter

### ISSUE THREAD

**Issue by davideberlein** [fguillot/kanboard#839]
Hey,

I have implemented a AngularJS based presenter for your Kanboard:
https://github.com/davideberlein/kanboard-presenter

The goal is to present all impotent projects of a development team on a TV screen and cycle them through to have an overview of what the current status is.

Tell me what you think of it.

Best Regards,

David

**Comment by fguillot** [comment]
Awesome!

I added your project to the list of related projects (https://github.com/fguillot/kanboard#related-projects) and I posted a link to your project in the last Kanboard news http://kanboard.net/news/version-1.0.14
