### ISSUE TITLE
Make a non-private project private.

### ISSUE THREAD

**Issue by vext01** [fguillot/kanboard#840]
Is this possible? Sorry if it is, I couldn't find it.

**Comment by vext01** [comment]
Ah, I might have figured it out. You just revoke all other users?

**Comment by fguillot** [comment]
It's not yet possible with the user interface but you can do it directly in the database if you really want to do it. In the table "projects" set the flag "private" to the value "1".

**Comment by fguillot** [comment]
It's now possible in the development branch, see https://github.com/fguillot/kanboard/blob/master/docs/editing-projects.markdown
