### ISSUE TITLE
Notifications over jabber

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#842]
Hi! Is It possible to send notifications over jabber?

**Comment by fguillot** [comment]
Yep, that coming soon...

**Comment by freekoder** [comment]
Thanks, I'll waiting for it.

**Comment by fguillot** [comment]
Basically, that will works like Hipchat and Slack integrations, notifications will be sent to a conference room.

**Comment by fguillot** [comment]
It's now available in the master branch, for more information see http://kanboard.net/documentation/jabber

At the moment, it's only tested in local with the Prosody XMPP server.

**Comment by freekoder** [comment]
Thanks a lot. Thats great! But is it hard to add personal notifications over jabber?
User profile may have jabber address field similar to email address.

**Comment by fguillot** [comment]
That require more changes to the code. But I will see that later, when I will make the notifications more flexible. Because the same feature can be added to Hipchat and Slack.

**Comment by fguillot** [comment]
With the last dev version, the jabber integration is now a external plugin and it's possible now to receive individual notifications.

**Comment by fguillot** [comment]
See https://github.com/kanboard/plugin-jabber
