### ISSUE TITLE
assignee dialog default focus should be in the username 

### ISSUE THREAD

**Issue by alexitosrv** [fguillot/kanboard#843]
Currently is like this:

![behavior unfocused field in assignee change dialog](https://cloud.githubusercontent.com/assets/3821436/7448871/517db508-f1eb-11e4-8fd3-110265f01006.png)

It should be better if the change assignee dialog were like this

![make default focus when changing assignee to the assignee fiedl](https://cloud.githubusercontent.com/assets/3821436/7448875/74386912-f1eb-11e4-90ea-d8a69164a071.png)

**Comment by fguillot** [comment]
It's now the case in master, you can change the assignee with the keyboard arrows by example.

Thanks.
