### ISSUE TITLE
db upgrade failed on 1.0.14 using mysql

### ISSUE THREAD

**Issue by c99ipnerd** [fguillot/kanboard#845]
Hello Frédéric,

i would like to reopen the issue #751. I tried updating from 1.0.12 -> 1.0.14. I did also try an update with the git tag 1.0.13, but that showed the same message.
```
Unable to migrate database schema:

\Schema\version_48 => SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'files' already exists
```
Yep, it exists and it is not the only table it complaints on after I deleted the table. The table schema_version shows 47.

I had set the DEBUG to true in config.php, but it didn't create a log file.

Thanks in advance.

best wishes,
Alwin

**Comment by fguillot** [comment]
The migration seems to block in the version 48. Try to run manually the sql queries of the version_48() https://github.com/fguillot/kanboard/blob/master/app/Schema/Mysql.php#L223-L227 then change the version number to 48 in the schema_version table and try to load again kanboard.

The migration process run each function one by one and if there is something wrong a rollback is performed.

**Comment by c99ipnerd** [comment]
Thanks, for your fast answer.
I have tried your suggestion, but that didn't help. I found a bug in my MySQL version 5.5.39. (Bug 19584379) After upgrading MySQL to 5.5.42 the kanboard upgrade went without failure.

http://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-41.html
