### ISSUE TITLE
Open file explorer to referenced location

### ISSUE THREAD

**Issue by McodeMe** [fguillot/kanboard#851]
As we are having a constellation where it is impossible to integrate all data necessary for a task into the board (the amount of data/files is too big) we established a file system where each folder belongs to a task. 
Is it possible to add the location of a folder to the task (i.e create something like a file_reference) that can then be clicked to open the folder in explorer on the local system?

**Comment by fguillot** [comment]
It's too specific to be implemented. But you can add a link in the task description by example: `file:///path/to/my/local/folder` or `file:///c:/path/to/thefile.txt` if I understand correctly what you ask for.

**Comment by McodeMe** [comment]
Thank you. That works just fine for me (except for chrome because of security implementation). It's going to take a bit of effort to update the link via Json-RPC as it is somewhere in the description, but it is manageable.
