### ISSUE TITLE
Q: How can I reset the admin pw?

### ISSUE THREAD

**Issue by stbc** [fguillot/kanboard#853]
Quick and dirty? Thx.

**Comment by fguillot** [comment]
1. Generate a new password with the function `password_hash()` from a PHP >= 5.5 shell:

```bash
$ php -a
Interactive shell

php > echo password_hash('admin', PASSWORD_DEFAULT);
$2y$10$i1VwOewr1H8NGHisJutM/eFkudRoFjWE2PaTIbEUsphDcbZXgsyG6
```

2. Replace the existing password in the database:

```sql
UPDATE users SET password='replace_me' WHERE username='admin';
```

**Comment by stbc** [comment]
Thx a lot. I solved it in a similar way in the meantime. But this will help other as well, I am sure :dancer:

**Comment by Numa-Q** [comment]
I don't have access to the interactive shell... (ovh serveur mutualisé).
I have only one user (the admin user) and changed the default password, then forgot it :/
I copied db.sqlite from my web server to my local drive. 
Renamed server/db.sqlite > db.sqlite_old
Used SQLite DataBase Browser to execute this query: 
* UPDATE users SET password='' WHERE username='admin';

Then saved the change and upload the modified db.sqlite to my server.
But I can't login, the password input needs a value :/

Second try:
* UPDATE users SET password='azerty' WHERE username='admin';

Still have a "Identifiant ou mot de passe incorrect"
How can I change admin password ?
Do I have to reinstall everything ?

**Comment by BlueTeck** [comment]
The password is hashed -> php password_hash()

You could generate a password hash or use the default one in your db update $2y$10$i1VwOewr1H8NGHisJutM/eFkudRoFjWE2PaTIbEUsphDcbZXgsyG6

**Comment by Numa-Q** [comment]
UPDATE users SET password='$2y$10$i1VwOewr1H8NGHisJutM/eFkudRoFjWE2PaTIbEUsphDcbZXgsyG6' WHERE username='admin';

Great ! It's ok ! Thank you !

**Comment by s2000coder** [comment]
What do you do if you have PHP 5.3.3 and the function password_hash return "PHP Fatal error: Call to undefined function"?

Forgot the admin password.
