### ISSUE TITLE
when removing swimlanes, it does not show the cards

### ISSUE THREAD

**Issue by valessiobrito** [fguillot/kanboard#855]
The bug happens when:
1. Add a new Swimlanes
2. Enable hidden Swimlanes as default
3. Remove new Swimlanes

It doesn't show cards on Swimlanes default.

**Comment by fguillot** [comment]
When you remove a swimlane, all tasks goes to the the default swimlane (swimlane_id=0).

I just tested on a new installation and that works, do you have any errors or something like that?
