### ISSUE TITLE
Redisigned python client

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#856]
Hi all! First of all, thanks for the great project.
I start a small project with kanboard python client library redesign.
Goals are: simplify python clients creation and hiding json-rpc 
complexity over python classes.

Here is simple task creation example:
```python
board = kanboard.Kanboard('http://localhost:8080/jsonrpc.php',
                          '347a020cb5ce709441aa42b2d5652fbb8b02e477104d1d9789f7b2d40df0')

project = board.get_project_by_name('Test')
column = project.get_column_by_name('Work in progress')
task = column.create_task('Test title', description='test descr', color=Task.COLOR_ORANGE)
```

I start project a week ago and not all API methods are implemented.
Bugs are also possible. 

Link to repo: https://github.com/freekoder/kanboard-py

**Comment by fguillot** [comment]
I added your project into the list of related projects: https://github.com/fguillot/kanboard#related-projects

**Comment by freekoder** [comment]
thanx. I hope it would be helpful.
