### ISSUE TITLE
RSS links are pointing to localhost, rather than the server name

### ISSUE THREAD

**Issue by blysik** [fguillot/kanboard#857]
My RSS links are pointing to localhost, rather than the real server name:
```
<link rel="alternate" href="http://localhost:31670/?controller=task&action=show&task_id=36"/>
```

Am I missing some configuration somewhere?  In the Application Settings page, the Application URL is set properly.

**Comment by levlaz** [comment]
I was running into a similar issue when I was running kanboard inside of a container and accessing it through an nginx proxy. Can you elaborate on the nature of your kanboard configuration? I think this will help us troubleshoot why this is happening.

**Comment by blysik** [comment]
My deployment is in a private PaaS and behind nginx proxy. Sounds like yours. :)

**Comment by fguillot** [comment]
I will fix that in the next couple of days to use the application url if defined. Actually that detect automatically the web server url.

**Comment by fguillot** [comment]
It's fixed in the master branch.

Thanks to report this issue.
