### ISSUE TITLE
Ability to pre-link OAuth accounts

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#86]
I tried the new Google authentication feature in Kanboard, works nicely once you've linked the account. However, I would like, as an administrator, to be able to "pre-link" accounts; that is, the user shouldn't have to know that the feature exists, I should be able to create a user and say "allow logging in with this google email ID"... that way, zero setup needed for new users, and no new password for them to remember.

**Comment by fguillot** [comment]
With the development version, you can pre-link oauth2 accounts if you know the Google or Github unique id of the user. The form is available in the user profile > Edit authentication.
