### ISSUE TITLE
Possible Vagrant Documentation Error

### ISSUE THREAD

**Issue by levlaz** [fguillot/kanboard#862]
I set up a Vagrant environment following this guide: 

https://github.com/fguillot/kanboard/blob/master/docs/vagrant.markdown 

Maybe I am doing this wrong, but when I ran composer install I had permissions errors and had to run `sudo composer install` instead. 

This was on a debian7 virtualbox instance made with vagrant. I accessed the box via `vagrant ssh`

**Comment by levlaz** [comment]
It looks this was updated in the last commit. Thanks! 

https://github.com/fguillot/kanboard/commit/22f44ef78820e75ce21913140b50d15c7213ccca

**Comment by fguillot** [comment]
The doc was outdated, I updated the doc...

The installation process is not always fully automated and can require some manual configuration in the virtual machine. Adapt the commands according to the distribution...
