### ISSUE TITLE
Call index.php without parameters dies with 'Page not found!'

### ISSUE THREAD

**Issue by falkoschumann** [fguillot/kanboard#863]
The call of my Kanboard homepage without parameters generates a redirect with parameters `http://kanban.muspellheim.de/?controller=auth&amp;action=login&amp;redirect_query=`. The ampersand are escaped with entities.

With the right parameters `http://kanban.muspellheim.de/?controller=auth&action=login&redirect_query=` the login page will be shown and the site works perfectly.

This happens with Kanboard 1.0.14. With 1.0.12 not, all works.

**Comment by fguillot** [comment]
It's weird, I'm not able to reproduce your issue. You should not have `&amp;` in the url.

- After installing from scratch the 1.0.14, the redirect from the root folder is correct for me.
- The redirect_query for expired session is working for me too.

Do you have any specific settings on your server Apache/php.ini ?

**Comment by falkoschumann** [comment]
I can not change server settings because it's on a shared host (Hosteurope). It's the same webspace I run 1.0.12 until yesterday. I download my installations (1.0.12 and updated 1.0.14) and run it local with MAMP, locally there ist no problem. The redirect works.

After I create a phpinfo.php locally and remote I found a different. The `arg_separator.output` setting ist locally "&" and remote "&amp;amp;". This setting must be the cause. If I change locally `arg_separator.output` to "&amp;amp;" then I can reproduce the issue.

**Comment by fguillot** [comment]
Can you override the default php.ini values with a `.htaccess`?

```
php_value arg_separator.output "&"
```

or try temporary to change the value in php, by example if you add a `config.php` file with:

```php
ini_set('arg_separator.output', '&');
```

**Comment by falkoschumann** [comment]
Both solutions works for me. I use now a `.htaccess` to overwrite the strange server setting. Thanks.

**Comment by fguillot** [comment]
FAQ updated for this issue: https://github.com/fguillot/kanboard/blob/master/docs/faq.markdown#page-not-found-and-the-url-seems-wrong-amp

**Comment by gludie** [comment]
Hi there,

I experienced the same behavior at my installation. Due to server limitations, I am not allowed to use any .htaccess settings, but will try now to set the setting in options.php. I get the same error only using root directory without any args - Fails at /login page not found ... adding the args here (or from my local installation / log ... I can login, and see projects, etc. but next actions same error ...

Hmm, the test shows, that login works, but not any further actions

any hints ? thanks a lot in advance, kr
