### ISSUE TITLE
create/modify webhook suggestions

### ISSUE THREAD

**Issue by blysik** [fguillot/kanboard#864]
Just some suggested modifications to the webhooks json payload for create and modify:

* Include an owner_name field, with the full name.  External systems will have to do extra work to figure out what owner_id is.
* For modify webhooks, a json field called 'changes', or something similar.  This would be an array of the fields which were updated.  Right now, an external system has no idea what is different, unless it kept state.

Thanks for the awesome work!

**Comment by fguillot** [comment]
The event "task.update" contains a new field "changes" now (in master branch). See https://github.com/fguillot/kanboard/blob/master/docs/webhooks.markdown#examples-of-event-payloads
