### ISSUE TITLE
[API] getSwimlanes vs getAllSwimlanes

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#869]
Hi. Yet another API issue. There are some redundancy with 2 similar API-methods - getSwimlanes and getAllSwimlanes. The problem is that getAllSwimlanes does not return
default swimlane info. getSwimlanes return all swimlanes but not full info (is_active, position). Is it possible to add default swimlane to getAllSwimlanes?

**Comment by freekoder** [comment]
And it seems that getSwimlane does not return default swimlane info

**Comment by fguillot** [comment]
The api have been updated in the development version, see the difference here:

- https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getactiveswimlanes
- https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getallswimlanes
