### ISSUE TITLE
[API] createTask method does not create event 

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#870]
Hi. Got the next issue on task creation with API: has no task creation event at dashboard activity stream.

**Comment by fguillot** [comment]
The activity stream show only events from logged users.

**Comment by freekoder** [comment]
Well, but it leads to assigned user can miss new task. And I think there is no difference between tasks created by logged users and task created via API.

**Comment by McodeMe** [comment]
A user can check their dashboard to see all assigned tasks. As long as there aren't tons of tasks a new one wont be missed.
In general i like the concept that API actions are not in the activity stream as you can do some background work like positioning without overloading the activity stream.

**Comment by fguillot** [comment]
The activity stream is to show actions of users, by example: "Bob created the task #12" and with the current api there is no user (no session) linked to the action.

However, in the future I will add a "user api" to facilitate the creation of mobile clients, in this case the end-user will be identified in the same way as the user interface.

**Comment by freekoder** [comment]
ok
