### ISSUE TITLE
XMPP with TLS

### ISSUE THREAD

**Issue by bluewindthings** [fguillot/kanboard#871]
Is XMPP integration supporting TLS auth? And in this case TLS with self signed certs also?

**Comment by fguillot** [comment]
I didn't try yet but according to the library used, TLS should work: https://github.com/fabiang/xmpp#documentation

**Comment by etcube** [comment]
I was trying the XMPP integration and there was no response. I was hoping to find some logs to find out what went wrong. However, i see no log file in data/ ?

I deliberately set the URL to a bogus IP and still see no log. Anyone with similar problem?

**Comment by etcube** [comment]
I could not find log info in /data nor syslog.
But I found the following in /var/log/httpd/error_log

[Mon Jun 01 18:11:42.700605 2015] [:error] [pid 2033] [client 10.237.44.115:61832] PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/kanboard/vendor/fabiang/xmpp/src/Stream/XMLStream.php on line 384, referer: http://10.237.255.60/kanboard/?controller=board&action=show&project_id=1

**Comment by rkaldung** [comment]
@etcube It looks like you don't have the xml extension available.

**Comment by etcube** [comment]
Thank you rkaldung. After installing php-xml, that error is gone.
However, I still cannot get the XMPP to work. This is my current /var/log/httpd/error_log.

[Tue Jun 02 12:23:03.581550 2015] [auth_digest:notice] [pid 881] AH01757: generating secret for digest authentication ...
[Tue Jun 02 12:23:03.582866 2015] [lbmethod_heartbeat:notice] [pid 881] AH02282: No slotmem from mod_heartmonitor
[Tue Jun 02 12:23:03.736252 2015] [mpm_prefork:notice] [pid 881] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Tue Jun 02 12:23:03.736322 2015] [core:notice] [pid 881] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Tue Jun 02 12:29:08.648571 2015] [mpm_prefork:notice] [pid 881] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Jun 02 12:29:40.065925 2015] [suexec:notice] [pid 856] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Tue Jun 02 12:29:40.114688 2015] [auth_digest:notice] [pid 856] AH01757: generating secret for digest authentication ...
[Tue Jun 02 12:29:40.115138 2015] [lbmethod_heartbeat:notice] [pid 856] AH02282: No slotmem from mod_heartmonitor
[Tue Jun 02 12:29:40.604873 2015] [mpm_prefork:notice] [pid 856] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Tue Jun 02 12:29:40.604912 2015] [core:notice] [pid 856] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

1. Could it be something I have to set on my XMPP server? I am using openfire...maybe something to do with security?

**Comment by etcube** [comment]
Sorry for this super noob question:

To use the XMPP feature of kanboard, do i need to install composer?

**Comment by etcube** [comment]
Ok. I installed composer anyway. The instructions says:
Add the following to your composer file:
{
    "require": {
        "fabiang/xmpp": "*"
    }
}

I think I have create a composer.json file with the above content and run "composer install".
Where should the composer.json be placed?

**Comment by rkaldung** [comment]
As you mentioned it days 'Add', not create ;-)
Take a look into the composer.json in the root folder of the project, there is a composer.json and it still contains the dependency.
Did you missed to run composer after the installation?

**Comment by etcube** [comment]
Thank you for the comments. 
I installed kanboard by this instruction:
http://kanboard.net/documentation/centos-installation

cd /var/www/html
wget http://kanboard.net/kanboard-latest.zip
unzip kanboard-latest.zip
chown -R apache:apache kanboard/data
rm kanboard-latest.zip

In my kanboard directory, there is no composer.json file.

**Comment by rkaldung** [comment]
The zip contains the xmpp lib, there must be a directory vendor/fabiang/xmpp/
I recommend doublecheck your config and increase the loglevel to figure it out

**Comment by etcube** [comment]
I think I might have gotten it to work.
When Kanboard sends the message to XMPP, does it remain logged on to XMPP?
My Kanboard user logs in, send the msg to the chatroom, then logs out immediately...is this proper?
