### ISSUE TITLE
[FR] Make Task from Subtask

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#873]
Possibilty to transform a subtask to a main task, which is linked to the original task.

Before:
- Task 1:
  - Subtask A [Transfer to Task]
  - Subtask B [Transfer to Task]

After:
- Task 1: (Link to Subtask A)
  - Subtask B [Transfer to Task]
- Subtask A: (Link to Task 1)

**Comment by fguillot** [comment]
This feature is now available in master. (simplified version without links).

**Comment by BlueTeck** [comment]
Thanks :)
