### ISSUE TITLE
Attachment filename and description

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#876]
Filename of attachments can not be long (picodb exception raised).
Attachment description will be very usefull.

**Comment by fguillot** [comment]
How long is your filename? can you give me an example to reproduce the issue?

**Comment by freekoder** [comment]
I got this issue with png image 53 symbols filename lenght. The same image with 50 symbol filename lenght uploaded successfully. Tested on debian with mysql.

**Comment by fguillot** [comment]
This issue have been fixed in the master branch.

The file name length is increased to 255 characters for Mysql, it was defined to 50 characters before. If longer than 255, the name will be truncated.

Thanks to report this issue.
