### ISSUE TITLE
Privilege escalation: non-admin user can convert private to public simply by renaming project

### ISSUE THREAD

**Issue by mkt95** [fguillot/kanboard#877]
Steps to reproduce:

1. Log in as a bog standard user
2. "New private project" and choose a name
3. Observe that project is private and that "User management" is not available in Actions tab
4. "Edit project" and enter a new name
5. Observe that project is no longer private and that "User management" is now an available action
6. Profit

(Well, maybe not 6, but...)

**Comment by fguillot** [comment]
Thanks to report this issue, it's fixed now in master.
