### ISSUE TITLE
[FR]: Possibility to copy actions from template into existing project

### ISSUE THREAD

**Issue by daroganadir** [fguillot/kanboard#879]
Hello, 

I am setting up a new installation of kanboard and so I do have to create quite some projects. In this projects I do have automatic actions which occur in nearly every project. I do know that you can duplicate a project (but you will have a new project then) but it would be nice if you would be able to build action groups which you are able to paste into existing projects. 

May this would be possible some da ?

Greetings,
Nadir

**Comment by fguillot** [comment]
With the last development branch, you can import automatic actions from another project.
