### ISSUE TITLE
Attachment description

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#880]
Some times attachment description is needed.

**Comment by fguillot** [comment]
Why not use the task description?

**Comment by freekoder** [comment]
well, it could be done via task description, but it could be cleaner to use separate description for attachment. if you use task description you should use some conventions and it could pollute main task info.

**Comment by fguillot** [comment]
Sorry, I prefer to keep Kanboard simple so this feature won't be developed.

**Comment by peter58228** [comment]
Everything need description, include tag, category, link...
I believe, keep work simple is important then keep Kanboard simple. This is why we use and love KB.
