### ISSUE TITLE
Default color for board

### ISSUE THREAD

**Issue by thedragon013** [fguillot/kanboard#882]
Hello, 
I am not sure, if I just missed it or if there isn't such an option.

I would like to define default colors for the columns when creating it. E.g. a new task in backlog will be red for default (at the moment the selected color when creating a task is yellow. Is there an option anywhere to do this ? 

Thanks in advance!
Dragon013

**Comment by fguillot** [comment]
You can do that with automatic actions, choose the action "Assign a color when the task is moved to a specific column".

In the development version, the event "task creation" have been added in addition to "move to another column".
