### ISSUE TITLE
logging to stdout?

### ISSUE THREAD

**Issue by blysik** [fguillot/kanboard#883]
Hi,

In a heroku-type env, apps should log to STDOUT.  Would it be possible to make an option to allow debug logs to go to php://stdout ?

**Comment by blysik** [comment]
I wonder if this should be about adopting something like monologger.  While trying to debug the xmpp integration, I couldn't get any logging until I just added in monologger so I can hand a PSR-2 compatible logging object to fabian/xmpp.

**Comment by fguillot** [comment]
I added a logger for the XMPP integration. You have to update to the last master and update the composer dependencies as well. My library is now compatible with PSR-2 and PSR-3.

You should be able to see all debug message from the XMPP library.

If you would like to redirect the debug messages to `stderr` or `stdout`, just add that in your custom `config.php`:

```php
<?php

define('DEBUG', true);
define('DEBUG_FILE', 'php://stdout');
```
