### ISSUE TITLE
Task update event fires twice

### ISSUE THREAD

**Issue by Pybou** [fguillot/kanboard#886]
Hello,

Once again, thanks for this wonderful project and keep improving it, it's getting better and better.

I tried searching on my side where could come this problem but I can not find the solution.
When updating a task and then go to see the activity stream of the task, the event "update task" appears twice. It also appears twice in the table "project_activities" with the same "date_creation".
I feel that we are passing twice in the function "taskModification-> update".

Anyone find a solution ?

Cheers!

P.S : I tested on the demo kanboard website when changing the category

**Comment by fguillot** [comment]
Yes that happen when you have one or more automatic actions enabled, events fire multiple times.

The activity stream will be improved later to be more explicit about the changes made on the task.
