### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#887]
I need to debug some of the notification classes and make some changes. I was wondering how do you go about debugging the code? Is there some IDE that can run this in interactive debugging mode? Or some debug function to log into a text file?

**Comment by Pybou** [comment]
You can enable the debug mode in the config.php file. You will be able to log the SQL requests in the debug.log file which is saved in /data folder.

**Comment by fguillot** [comment]
You can probably use PHPStorm to facilitate the debugging otherwise there is only a debug file like mentioned above.
