### ISSUE TITLE
Show Kanboard based on selected User

### ISSUE THREAD

**Issue by iM4rv** [fguillot/kanboard#889]
This is a feature request. For my company its extremely important to view a kanboard based on selected users. Example: i have a meeting with 5 users and i want to check their progress. My wish: i select all of them and see all their assigned tasks in one board.

Further more it would be nice to link two cards and if i move card 1 to "finished" it automatically moves card 2 to "finished".

**Comment by fguillot** [comment]
You can simply filter the board by assignee to do that.
