### ISSUE TITLE
iCalendar Feed

### ISSUE THREAD

**Issue by splite07** [fguillot/kanboard#890]
Hello, 

By any chance, is there any way to have a iCalendar Feed to get all the due date in thunderbird or do we have to code it ?

Thanks

**Comment by oliviermaridat** [comment]
It is available in the master branch: [iCal subscriptions](https://github.com/fguillot/kanboard/blob/master/docs/ical.markdown)

**Comment by fguillot** [comment]
Yes it's already available in the development branch and that will be released in the next couple of days if I don't find obvious bugs.
