### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#891]
Windows 8.1. IE 11. 

The board has the following problems:
* The header area is distorted. 
* The switch project dropdown is broken.
* Dragging cards does not work if cursor has been on any of the links on the card. You have to precisely pick an empty space inside the card. 
* While dragging, selection mode comes up and the whole swimlane of tasks get selected. 
* After dropping, the position of the card is not saved. Refreshing page shows the cards have not been really moved. 

Header problem:
![image](https://cloud.githubusercontent.com/assets/1611494/7912490/d84c116c-085f-11e5-9284-c8386fb89138.png)

Drag problem:
![image](https://cloud.githubusercontent.com/assets/1611494/7912499/eadb1148-085f-11e5-813a-e9340606a4ec.png)

Cards get into selection mode while dragging:

![image](https://cloud.githubusercontent.com/assets/1611494/7912508/ff94c30e-085f-11e5-8fcc-ca35bf16449b.png)

**Comment by fguillot** [comment]
Are you sure that everything is installed correctly on your server? I cannot reproduce your issue with Win7 and IE11. I will try later with a Windows 8.1 virtual machine...

You must see a Javascript error somewhere in the console...

Do you have the same issue with the demo version of Kanboard, http://demo.kanboard.net/ ?

**Comment by oazabir** [comment]
Found the problem. It happens when Compatibility View settings are turned on in Enterprise policy. 

I have added this after <head> tag in Layout.php and it fixes the problem:

<meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by fguillot** [comment]
This meta tag is now added in the master branch, thanks.
