### ISSUE TITLE
Project ics URL

### ISSUE THREAD

**Issue by efetzer** [fguillot/kanboard#892]
Where is the Project Calendar ICS URL in 1.0.15?  I have no problem finding it for the USER ICS.  The documentation isn't clear where the Project ICS URL is.

Thanks,
Erik

**Comment by fguillot** [comment]
Go to the project settings > Public access > iCal feed

**Comment by efetzer** [comment]
This is just confusing in the documentation because I went to the project and then to Actions and public settings and nothing is there.  So you are describing going to:  Project Management... Select the project... Public Access...  iCal Feed.  Got it. thanks for the clarification.
