### ISSUE TITLE
Email notification changes

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#893]
I have made the following changes:

* Email notifications are sent to only creator and assigned person, not to everyone in the project.
* Overdue email notification is sent to only the assigned persons. 
* A daily reminder email of tasks that are due this week. 
 * Email template enhancements. 

Would you like me to merge these changes to your codebase?

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
You can always send a pull-request.

**Comment by fguillot** [comment]
By the way, I'm currently refactoring the notification code to be more flexible...

**Comment by fguillot** [comment]
The notifications are more flexible now in the master branch... Don't hesitate to send a pull-request for any possible improvements.

**Comment by asangansi** [comment]
Hi, sorry if this is not the right place to ask this, but I wanted to know how to activate these email reminders in my kanboard install. I'm using 1.0.28
Thanks
