### ISSUE TITLE
[API] createFile contract

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#896]
Hi. First of all thanx for the attachment manipulations API methods.
There is one note for return value of createFile.
At this moment createFile return true or false. But it would be better to return file_id at success
as it done at createTask method.
It would allow to create file wrapper object at API libraries by calling getFile method with file_id after createFile.

**Comment by fguillot** [comment]
It's now available in the master branch, the method `createFile` returns the `file_id` and doesn't use anymore the parameter `is_image`.

See https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#createfile

**Comment by fguillot** [comment]
Sorry it was #894
