### ISSUE TITLE
[BUG] createFile API call cause exception

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#897]
Got this Uncaught exception 'ReflectionException' with message 'Invocation of method Api\File::createFile() failed' in /home/user/PhpstormProjects/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/Server.php:553
with warning PHP Warning:  Parameter 5 to Api\File::createFile() expected to be a reference, value given in /home/user/PhpstormProjects/kanboard/vendor/fguillot/json-rpc/src/JsonRPC/Server.php on line 553.
Environment: Linux Debian, PHP Version 5.6.7-1

Fix this issue with next patch:
```patch
diff --git a/app/Api/File.php b/app/Api/File.php
index 11c4840..65dff72 100644
--- a/app/Api/File.php
+++ b/app/Api/File.php
@@ -36,7 +36,7 @@ class File extends Base
         return '';
     }
 
-    public function createFile($project_id, $task_id, $filename, $is_image, &$blob)
+    public function createFile($project_id, $task_id, $filename, $is_image, $blob)
     {
         return $this->file->uploadContent($project_id, $task_id, $filename, $is_image, $blob);
     }

```

**Comment by fguillot** [comment]
It's weird I don't reproduce the issue with PHP 5.6.9 on Mac OS... anyway it's fixed in master.

Thanks.
