### ISSUE TITLE
[FR] attachment content-type info

### ISSUE THREAD

**Issue by freekoder** [fguillot/kanboard#899]
if store content-type of attachment at database it would be possible to show file type icon before filename. And it can simplify createFile method with is_image argument reduction.

**Comment by BlueTeck** [comment]
BTW: the attachment Icon is based on the Filename: https://github.com/fguillot/kanboard/blob/eeac2329baab1fdae7cbf6c707ed2ffd8beb4c1b/app/Helper/File.php#L20

**Comment by fguillot** [comment]
The parameter `is_image` is now removed from the api call, it's only used internally to generate a thumbnail.
