### ISSUE TITLE
Use Calendar Timeslots for planning

### ISSUE THREAD

**Issue by MatFluor** [fguillot/kanboard#905]
Hi there - first of all: amazing work ;-)

It would be cool, if you have a lot of Tasks on a due date, you could pull them from "all-day" state onto the hourly table (which is possible already - in a way) and so create your schedule for the day (or more).

Problem are:
* the schedule won't get saved
* Odd behavior, pulled tasks seemed copied right next to each other

Thanks for your work.

**Comment by Rogieee** [comment]
Hi Mat.
See https://github.com/fguillot/kanboard/issues/794

**Comment by MatFluor** [comment]
Hi Rogieee,

Thanks. I'll close it.
