### ISSUE TITLE
Failed to add new js library

### ISSUE THREAD

**Issue by hussam789** [fguillot/kanboard#910]
I'm trying to use [vue.js](http://vuejs.org/) library, i added vue.js.min to **assets/vendor** folder and run **make-assets.sh** when i use the library i get this error:
## Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'".

**Comment by fguillot** [comment]
The CSP rules of Kanboard doesn't allow inline javascript and stuff like eval for security reasons.

**Comment by hussam789** [comment]
i added js file in assets/js/src and added it to app_js in make_assets.sh. javascript isn't inline!

i just wanted to add [TreeView](http://vuejs.org/examples/tree-view.html) , and copy-paste the code from examples page

**Comment by fguillot** [comment]
Your js library seems to use the function `eval`. It's disabled to avoid potential XSS security issues. If you really need that, you can always adjust the csp rules of Kanboard.

What are you trying to accomplish with that?

**Comment by alamnaryab** [comment]
I tried many things like
<meta http-equiv="Content-Security-Policy allow 'self'; media-src *; img-src *; script-src 'self' 'unsafe-inline' https://ajax.googleapis.com www.google-analytics.com; style-src 'self' 'unsafe-inline';"> 
but not working
