### ISSUE TITLE
Custom features?

### ISSUE THREAD

**Issue by jregusci** [fguillot/kanboard#911]
Hi Frédéric!

We're very happy with kanboard and we've been using it more and more in our development projects with great results.
However, to be able to use it across all projects, we need some features that currently are not included and we also don't know if they could or would be added in the future.

Having that in mind, what would you advise us to do? 
Do you recommend that we start our own development and merge with future updates? 
Is there a way in which we could get a quote from you to develop it in the main version? i.e. some sort of paid priority feature request.

Looking forward for your comments.

Regards.

**Comment by BlueTeck** [comment]
Maybe this will help you: https://github.com/fguillot/kanboard/blob/master/docs/contributing.markdown

**Comment by fguillot** [comment]
Which features do you need exactly? do you have any examples with use cases?

If the missing features can benefits to everybody, it's always possible to include that in the main version. However, that must respect the "philosophy" of the software: **keep it simple**.

I already added some "sponsored features" in the past. So, it's possible but that should be included in the open source version to avoid maintaining several versions of the software. If you need a quote, you can contact me directly by email fred@kanboard.net

If you feel more comfortable to do the development yourself, you can send pull-requests to be merged upstream but if it's really specific to your business you will have to maintain your own fork.

Finally, that depends of your needs.

For your information, the next stable version will be mainly improvements of existing features:

- More flexible and more accurate notifications
- Better time tracking
- Reports
- Budget section

**Comment by jregusci** [comment]
Ok, thank you. I'll put together our requirements and contact you directly
at your mail.

In general, our needs are:

- Tags
- Table view with filters (including tags) + Excel download
- What i call advanced burndown chart. We have that burndown in excel and
we fill it in every sprint. That burndown give us the velocity, ETA to
finish, and added complexity in every sprint. It sounds complex but in fact
its very simple since all are excel formulas.

I'll give you more detail in the mail.

Kind Regards.

2015-06-07 15:22 GMT-03:00 Frédéric Guillot <notifications@github.com>:
