### ISSUE TITLE
Task ID

### ISSUE THREAD

**Issue by mtruijen** [fguillot/kanboard#912]
In our instance we load tasks from an external application (ticket/release/bug). Those have also a number assigned and that is what we refer to. Is there a way to either:
- Replace the Task ID shown on the kanban card with the ID (number) that was assigned in the source application? The Task ID as currently is, isn't very useful to use and is taking up unnecessary white space on the card.
- Add a number to the kanban card that is clickable and would open the ticket/release/bug in the source application when clicked on it?
This way we would be more easily able to link the kanboard cards with the actual ticket/release/bug in the source application.

**Comment by fguillot** [comment]
There is a column "reference" in the table tasks, you can use that to store external ticket id.

It's actually used by the Github/Gitlab webhooks to synchronize issues in Kanboard. The url to the ticket is appended to the task description. The external id is shown on the card if not empty next to the Kanboard task id.

How do you load tasks into Kanboard from your external application?

**Comment by mtruijen** [comment]
Thanks for the quick and prompt response.

I use python and jsonrpc api. I love your application and we have big plans
to start using it in our IT teams.
OK, so I should be able to use the reference? Will I be able to set/provide
the reference (URL) to external application? If that works, I am all set.

**Comment by mtruijen** [comment]
I am having trouble with creating a reference between a task on the
Kanboard and a unique record (ticket/release/bug) in an external
application.
Creating tasks in Kanboard using createTask works awesome. But how do I
update if I don't know the relationship between task_id and the record in
the external application.
I guess, I could use title but that isn't 100% accurate. Titles can change,
are not unique, etc.

Now if I could generate my own unique task_id, based on an id in an
external application, I would be all set.
However the task_id appears like I have no control over.

**Comment by fguillot** [comment]
I modified the API to facilitate that (only in master branch). Use the field "reference" to store your external id (ticket number or whatever, 50 chars max, must be unique for each project).

1) Create a task with an external reference, here an example of payload:

```json
{
    "jsonrpc": "2.0",
    "method": "createTask",
    "id": 2094512567,
    "params": {
        "title": "Task with external ticket number",
        "reference": "TICKET-1234",
        "project_id": 1,
        "description": "[Link to my ticket](http:\/\/my-ticketing-system\/1234)"
    }
}
```
The url to your external ticket is defined in the description (in markdown format). You can do the same with the method `updateTask`.

2) If you would like to fetch this task later with the api, use the method `getTaskByReference`. See https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#gettaskbyreference

With Kanboard the task_id is an autoincrement field, you cannot modify this field.
