### ISSUE TITLE
small bug with long names boards in Russian

### ISSUE THREAD

**Issue by vsk-space** [fguillot/kanboard#914]
Good day! I found a small bug with long names boards in Russian. 

![kanboard php lang error](https://cloud.githubusercontent.com/assets/12798989/8037033/3325d4e8-0e04-11e5-83a6-f91d4279f8df.png)

**Comment by fguillot** [comment]
Can you copy/paste the original title here, so I can easily reproduce and fix that bug? Thanks

**Comment by vsk-space** [comment]
Yes - "Настольная реклама в фудкорте ГЧ"

**Comment by fguillot** [comment]
Thanks, it's fixed in the development version.
