### ISSUE TITLE
Integration with Mailgun - Notifications

### ISSUE THREAD

**Issue by fabdelgado** [fguillot/kanboard#915]
Integration to notify users through email using Mailgun?
The parameters to be configured SMTP settings? (http://kanboard.net/documentation/email-configuration)

Documentation using Mailgun is not explained

**Comment by fguillot** [comment]
You can use the standard SMTP method with the stable version. With the development version (master branch) you can use directly the Mailgun API, see https://github.com/fguillot/kanboard/blob/master/docs/email-configuration.markdown#mailgun-http-api

**Comment by fabdelgado** [comment]
ok, this functionality is available in the next release of the stable version?
When it will be available to implement the upgrade production?
Thankyou

**Comment by fguillot** [comment]
There is a new stable approximately every month.
