### ISSUE TITLE
Board link on email notifications

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#917]
Looking for a function to get the board link on an email template please.

**Comment by fguillot** [comment]
I don't know if that answer to your question: https://github.com/fguillot/kanboard/blob/master/docs/email-configuration.markdown#how-to-display-a-link-to-the-task-in-notifications

**Comment by oazabir** [comment]
Looks like I can get the kanboard URL, but what would be good to get a function which takes project_id, task_id and produces the board URL.

**Comment by fguillot** [comment]
I added the link to the board in the notification templates, see an example here: https://github.com/fguillot/kanboard/blob/master/app/Template/notification/footer.php#L6
