### ISSUE TITLE
Support linking of tasks together

### ISSUE THREAD

**Issue by oliviermaridat** [fguillot/kanboard#92]
I would like to suggest a new feature: the ability to link too tasks together. If the link as a meaning (e.g. "related to", see below for more), it is possible to explain the relation between too tasks and organize better the work. This also simplify the browsing between tasks.

Examples of links:
* #1 Related to #7
* #1 Waits for #7 (and #7 prevents #1)
* #1 Subtask of #7 (and #7 parent task of #1)

Technically, a link contains: the source task id, the link meaning, the target task id. Each task should be able to have several links (#1 is a subtask of #8 but is also the parent task of #3 and is related to #17).
 If a link is created on #1, it appears on the task, for example as below:
![2014-05-16_555x368_scrot](https://cloud.githubusercontent.com/assets/953989/2998720/2ad733f4-dd0e-11e3-9ff9-31249b099585.png)
and the inverse link appears automatically on the linked task.

What do you?

**Comment by oliviermaridat** [comment]
It should be fixed by now:
* A task can't be linked to itself anymore
* The "array to string conversion" error seems to be removed 
* I have added the duplication of links when a project or a task is duplicated. For a task duplication, the link label of the original project is used. Note that when editing the new duplicated task links, only the link labels of the current project are available (which is quite logical). Actually, this is similar to linking 2 tasks from 2 different projects: it works, but one project is always using the link labels of the other project. I don't know yet if this is a real issue.

**Comment by oliviermaridat** [comment]
I am currently preparing the pull request, so:
* I have made some enhancement and clarification in the UI to show / edit links
* it is not possible anymore to have duplication of links
* I have added a French translation for the link feature
* [oliviermaridat/kanboard/master](https://github.com/oliviermaridat/kanboard) is now up to date with fguillot/kanboard/master (wow, loads of updates!).
* I didn't test this for Postgres...

It seems fine for me now. I will do a final check this week and then send a pull request.

**Comment by BlueTeck** [comment]
I will test it again later ;)

**Comment by BlueTeck** [comment]
I am not sure if I made is mistake or not ;) Got the following message: 

Fatal error: Class 'SimpleLogger\Logger' not found in /var/www/virtual/########.de/htdocs/todo_dev/app/ServiceProvider/LoggingProvider.php on line 15

**Comment by BlueTeck** [comment]
SimpleLogger is not in my Vendor Folder...

**Comment by oliviermaridat** [comment]
"composer.lock" problem is now solved.
My pull request will contain a lot of commit messages, but I don't know to handle that more properly. So I will send a PR and hope to be accepted, or to receive indications to clean this :-)

**Comment by poikilotherm** [comment]
The term you are looking for is "squashing". When you have finished your development, make a new branch from master and do a `git merge --squash <your-dev-branch-name-here>`. Of course you would have to create a new PR for this.

I think @fguillot does squashing before merging, too. Maybe don't worry then... ;)

**Comment by oliviermaridat** [comment]
Thanks for this explanation poikilotherm. My fork history is too messy for that at the moment, but I will use it next time.

**Comment by ashbike** [comment]
Nice :+1: . Just checked out and it is working fine. Doing more testing.
Just two small points (feel free to ignore :smile: )  
1. How about adding a menu item on the tasks on board? Like the screenshot below.
2. Wouldn't FontAwesome .fa-link be more appropriate as icon than .fa-code-fork? Like the screenshot. 

![image](https://cloud.githubusercontent.com/assets/7455931/6150208/08d181be-b234-11e4-89e8-6efdb3e720fe.png)

I was playing with the task menu... this line around line # 49 app/Template/Board/task.php creates the menu item.
`<li><i class="fa fa-link"></i> <?= $this->a(t('Add a link'), 'tasklink', 'create', array('task_id' => $task['id'], 'project_id' => $task['project_id'])) ?></li>`

**Comment by oliviermaridat** [comment]
Thanks for your testing ashbike!

1. Good idea! I will keep it like that at the moment, this is already a big PR.
2. If I am not wrong, .fa-link was used for attached file. I like .fa-code-fork, it avoids confusion with hypertext links. But I am fine with .fa-link.

**Comment by fguillot** [comment]
Task links are in master now.
