### ISSUE TITLE
Days in Column does not reset when using updateTask

### ISSUE THREAD

**Issue by mtruijen** [fguillot/kanboard#920]
When I use the updateTask Json-RPC procedure to change the column, the Days in Column value appears like it is NOT getting updated/reset.

**Comment by fguillot** [comment]
You should use the method `moveTaskPosition()` to move the task to another column or position or swimlane. That will trigger the events that update the different timestamps.

To enforce that, I changed the method `updateTask()` in the development version. The arguments `column_id` and `swimlane_id` have been removed.

Thanks to report that.

**Comment by mtruijen** [comment]
Awesome. Thanks for the super great support of this awesome software that
you have created!
