### ISSUE TITLE
Simplify user creation

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#924]
Right now a project member creation requires the following steps:

* Create the user from user management.
* After creating the user, open the user, change email preference to get email notification.
* Go to project -> user management and add that user.

Let's simplify it. If a user is created with a default project, the user should be automatically assigned to that project as a member, and let's make the email notification default turned on.

**Comment by fguillot** [comment]
In the development version, I removed the field "default_project_id" because it's useless now. However, when you create a new user, it can be added to a project automatically and you can enable notifications in the same time.
