### ISSUE TITLE
Problem with network addresses in descriptions and comments

### ISSUE THREAD

**Issue by marcosaccioly** [fguillot/kanboard#925]
Hey guys, 

While using Kanboard at our institution, we've noticed that when pasting network addresses in the form 

 `\\monaco\Producao_de_Materiais\_DESIGN\Site\Cead\Banner_Portal\2014\Dia_Namorados`

kanboard automatically replaces some of the backward slashes resulting in this:

`\monaco\Producao_de_Materiais_DESIGN\Site\Cead\Banner_Portal\2014\Dia_Namorados`

and we are forced to use the backward accent (`) all the time to avoid losing characters. 

**Is this an expected behaviour or a bug?**

**Comment by fguillot** [comment]
Markdown escaping.. see this example of the Markdown parser used by Kanboard: http://parsedown.org/tests/escaping/

**Comment by marcosaccioly** [comment]
Hey Fred, 

So there's no way around, as far as I can see... We'll keep on using the backtick '`' then.

Thank you
