### ISSUE TITLE
Some files can't be uploaded 

### ISSUE THREAD

**Issue by marcosaccioly** [fguillot/kanboard#926]
Hello, 

Some of the files we try to upload don't get uploaded. We couldn't trace the reason, not even a wild guess. 

I have uploaded one of these files to Google Drive so that you can test because I tried it today. Here it is: https://drive.google.com/file/d/0B2MBLG2-JAkhS05TRm5ieHZ2Z1k/view?usp=sharing

Here's the screenshot of what happens: 

![image](https://cloud.githubusercontent.com/assets/1198117/8133855/22c11d1a-1101-11e5-9aac-e371a497900a.png)

Cheers,

**Comment by fguillot** [comment]
I downloaded your file from Google Drive then uploaded the PDF into Kanboard and it's ok, everything works for me.

According to your screenshot, there is an error 500 returned by the web server. If you use Apache, you should see the error in the apache log files (error_log). It's probably the only way to see what is wrong.

**Comment by marcosaccioly** [comment]
Thanks for testing it. I'll check the server to see what's going on. 

Chhers,
