### ISSUE TITLE
Cookies not limited to single port

### ISSUE THREAD

**Issue by aaronrobertson** [fguillot/kanboard#927]
I'm running kanboard in docker containers, so I have multiple instances on a single IP.

For example:
http://10.0.1.111:20080/kanboard/?controller=board 
http://10.0.1.111:30080/kanboard/?controller=board
http://10.0.1.111:40080/kanboard/?controller=board
All three point to separate kanboard container instances.

All three instances try to share the same cookie in the browser. 
This causes issues when trying to access the instances simultaneously in the browser.

Not really an important issue, just thought it was interesting.

**Comment by fguillot** [comment]
Apparently, cookies doesn't provide isolation by port. See http://stackoverflow.com/questions/1612177/are-http-cookies-port-specific

In your case, you can setup a reverse-proxy configured with sticky session.
