### ISSUE TITLE
Hide Swimlane if empty option

### ISSUE THREAD

**Issue by mtruijen** [fguillot/kanboard#929]
Would it be possible to add an option to the Swimlane properties that would allow a swimlane to NOT display (hide) on the Kanboard if no tasks are assigned to that swimlane?

Real-estate is expensive on any board and it would be good if I could hide any sections if there is currently no data for it. E.g. I would like to keep the Default Swimlane but don't want it to show if no tasks have been assigned.

**Comment by fguillot** [comment]
You can always hide a swimlane with the icon on the left.

**Comment by mtruijen** [comment]
Was this hide/show option removed from the public board? I don't see this
(anymore) when opening the public link... Maybe it was never available
(can't remember).
Yes that is true, however on a public board (displayed in a public location
in our building) this isn't really workable.
This is a nice to have, but would be a good enhancement.

**Comment by fguillot** [comment]
The option is not there on the public board.

**Comment by fguillot** [comment]
Empty swimlanes are not shown anymore in the public view (only in dev version at the moment).

**Comment by sandromario** [comment]
What is the public and the dev view? Not sure why this should depend on the view.
The intuitive solution would be to auto-collapse a swimlane if there are no tasks in the currently visible columns. Is this not possible?
