### ISSUE TITLE
Testing TaskFinder

### ISSUE THREAD

**Issue by oazabir** [fguillot/kanboard#930]
I would like to test a new function that I have added in TaskFinder. How do I go about unit testing TaskFInder only? Is there's a way I can interactively test it from php?

**Comment by fguillot** [comment]
`phpunit -c tests/units.sqlite.xml tests/units/TaskFinderTest.php`

**Comment by oazabir** [comment]
I am not getting tests folder in my installation.

**Comment by fguillot** [comment]
Don't use the packaged version, but clone the repo with git to get the development version.
