### ISSUE TITLE
Convert private project to a multiple user project not only for admin

### ISSUE THREAD

**Issue by middeke** [fguillot/kanboard#931]
The feature of changing private projects to multiple user projects is great!
It is necessary to do this, even when you are the creator / manager of the project.
I did a hack in app/Template/project/edit.php line 16, adding isAdmin or isManager to show the checkbox
and in app/Controller/Project.php line 143 disabling isAdmin-check to write to databas.

I don't know, if it is the right place, please check and give it to the source.
THX, Martin

**Comment by jbenoit1010** [comment]
Can you provide exact changes to line 16 (edit.php) and line 143 (Project.php) please?  I am very new to PHP but would like to add this capability. 

edit.php line 16  "if ($this->user->isAdmin()): ?>" change to ?
project.php line 143 "if ($project['is_private'] == 1 && $this->userSession->isAdmin() && ! isset($values['is_private'])) {"  change to ?

Thank your for any assistance!

**Comment by middeke** [comment]
Hi,
I use Kanboard  1.0.15.
In app/Template/project/edit.php I changed line 16 from:
    <?php if ($this->user->isAdmin()): ?>
to:
    <?php if ($this->user->isAdmin() || $this->user->isManager($project['id'])): ?>
 to show the checkbox "Private Project".

In app/Controller/Project.php I changed line 143 from:
        if ($project['is_private'] == 1 && $this->userSession->isAdmin() && ! isset($values['is_private'])) {
to:
        if ($project['is_private'] == 1 && ($this->userSession->isAdmin() || true) && ! isset($values['is_private'])) {
to allow writing the state to the database not only for Admins. The statement "|| true" is a workaround until I find a possibility to check, if the signed in user is a "Project manager".

Hope that help,
Martin

**Comment by jbenoit1010** [comment]
Martin - That was very helpful and it worked great for my needs.  Thank you!
