### ISSUE TITLE
Error when deleting a subtask

### ISSUE THREAD

**Issue by thedragon013** [fguillot/kanboard#935]
Hello,

when deleting a subtask in version 1.0.14, I get the following message:

Warning: sprintf() [function.sprintf]: Too few arguments in /xxxx/app/Core/Translator.php on line 52

The subtask is deleted, though. I use german as language.

Regards,
dragon013

**Comment by fguillot** [comment]
It's now fixed in the development version with the patch of @crwilliams.

Thanks to report this issue.
