### ISSUE TITLE
Long waiting time after board modification

### ISSUE THREAD

**Issue by elnicko** [fguillot/kanboard#940]
Is it just me, or does it bother also other users that when multiple tasks are moved around one after the other on the board there is a "refresh" happening that nullifies subsequent actions?

E. g. I would like to move 3 tasks from Column A to Column B in 2 sec. I move all three, then a refresh of the board happens and the second two moves are reversed. Seems to be a refresh of the board after the first command happening to take a long time. What could be the reason for such a behaviour?

PS: This happens on a server over the internet, LAN and localhost. Latest version: 1.0.15, but it was the same also on pervious versions.

**Comment by BlueTeck** [comment]
You're right. The Task-Move updates the board, but the response seems to be to slow in your system.

https://github.com/fguillot/kanboard/blob/master/assets/js/src/board.js#L242

**Comment by elnicko** [comment]
OK. Is there anything I could do to the system to improve it, o ris it something that should be improved within kanboard?

Thanks.

**Comment by fguillot** [comment]
The first step will be to enable the debug mode to see where is the bottleneck: http://kanboard.net/documentation/config

In the debug file, you will see the time taken for each sql query and the time to render each page, but also the time to send emails.

Actually everything is done synchronously so:

- Sending email notifications might slow down everything when enabled if your smtp server is slow. Sending an email can take a couple of seconds sometimes. It's the reason I added the support of the http api of Mailgun/Sendgrid/Postmark.
- You may have a webhook and it take too much time to respond
- Integrations like Hipchat/Slack/Jabber work in the same way, that contact a external system

Try to disable/enable each feature that communicate with an external system to see.

But which databases are you using Mysql/Postgres/Sqlite? and how many tasks do you have on the board? how many users? Which operating system? if you use sqlite what kind of disk storage is it ssd/sata/nfs mount/network san?

**Comment by elnicko** [comment]
Thank you for the pointers. It's good to know that I'm the only one because a wrong server setup is easier to fix than hunting for an unknown bug I guess...

The server has no external integration but the storage part is pretty actual. We use sqlite and have a bunch of tasks. I'll test a bit while enabling debug and if I don't move forward come back to you.

thanks and cheers.
