### ISSUE TITLE
description Field for subtasks

### ISSUE THREAD

**Issue by jknapp82** [fguillot/kanboard#943]
Hi,

first of all: thanks for the great app!!! I was searching for years for THIS app!

Only thing I'm Missing is an description/Comment fielt for subtasks.

Thanks
jknapp82

**Comment by fguillot** [comment]
I don't understand the need to have description/comments/due date or whatever for subtasks since you already have that for task? Why not just link tasks together?

What is your use case?

**Comment by BlueTeck** [comment]
-> #176

**Comment by jknapp82** [comment]
#176 describes exactly what I need. Your (fguillot) comment was 
"Otherwise a textarea for a long markdown description can be added."
This would be perfekt!

a little bit of background: I'm "influenced" by the "getting things done" philosophie, and breaking Tasks into subtasks with a detailed description what to do for each subtask is a basic thing there. The reason is, that you don't want to search for the details, needed for your subtask in the "big overall description" which cost time and concentration.

Thanks a lot!

**Comment by fguillot** [comment]
Ok, so I close that ticket because that duplicate #176
