### ISSUE TITLE
Sub tasks not on the board

### ISSUE THREAD

**Issue by kwijk** [fguillot/kanboard#945]
One can add a subtask to a 'normal' Task. 

 would like to place subtasks as separate items on the board, so their status&progress can be followed individually.
I know about issue #371, metioning that it should be possible on the development version, which I am using. But I cannot seem to get subtasks as separate items on the board. 
I do not want to use the task linking feature.

**Comment by fguillot** [comment]
Ticket #371 is about showing subtasks in the dashboard not the board.

Subtasks are not displayed on the board, however you can see the status of each subtasks with the tooltip when you mouse over the subtasks progress status.

I don't plan in the future to display subtasks on the board in the same way as tasks.
