### ISSUE TITLE
When space is constrained, assignee name overlaps the task age indicators

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#948]
As this screenshot illustrates:

![foo](https://cloud.githubusercontent.com/assets/479401/8358543/c7c28c18-1b2e-11e5-8479-371a37a446b7.png)

**Comment by fguillot** [comment]
In master, the task age is now hidden when the board is in compact mode. I don't have better solution right now. Maybe having avatar to save space will solve the issue.

**Comment by nekohayo** [comment]
Yep, that already helps a bit for this usecase, thanks!
