### ISSUE TITLE
Horizontal scrollbar should be at the bottom?

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#949]
As you can see in the screenshot below, when you have a board that is much wider than tall (ex: many columns and collapsed tasks), there is a horizontal scrollbar but it appears at an arbitrary height in the browser's window.

![foo](https://cloud.githubusercontent.com/assets/479401/8358832/8dae2eae-1b30-11e5-8498-324f6aa44bea.png)

Normally, I would expect it to show at the bottom of the browser window, as if it was a "normal" horizontal browser scrollbar. Trello does that (it also does per-column scrolling like in issue #576), for what it's worth.

**Comment by fguillot** [comment]
I changed that in master, now the board size have the window height and there is individual column scrolling.

Note: The scrollbar doesn't appear with some os like mac os
