### ISSUE TITLE
Overview of member workload, visual component

### ISSUE THREAD

**Issue by nrgetik** [fguillot/kanboard#950]
Maybe this is a feature that is already implemented and I'm having trouble figuring it out, or the request has already been made, but...

It would be incredibly useful, from a project manager's standpoint, to be able to see the workload (assigned tasks that are not blocked?) of all members across all projects quickly and easily, in order to make decisions about who to assign future tasks to.

**Comment by fguillot** [comment]
It's now available in the dev branch.

**Comment by nrgetik** [comment]
I didn't see a dev branch in the repo, so I just grabbed the nightly build this morning, and I can't seem to find this feature or make it work. Can you elaborate?

**Comment by oliviermaridat** [comment]
In the dashboard (Kanboard home), select "Project Management" and then "Users overview".

**Comment by nrgetik** [comment]
Ok, so from there, I would be selecting "Open Tasks" and selecting each user in the drop-down menu to get an understanding of their workload?

**Comment by fguillot** [comment]
Correct. It's not yet documented because that might be changed/improved.

- Login with a user that is admin or project admin
- Go to project management > Users overview
- Select a user and choose "open tasks"
- You will see the list of open tasks across all projects for this user

**Comment by nrgetik** [comment]
Very good, thank you!

**Comment by rtockner** [comment]
Great feature, 
displaing the list of assigned subtasks and showing the field "estimated time" would be very very nice.
