### ISSUE TITLE
master-branch: Unable to migrate database schema

### ISSUE THREAD

**Issue by kingfisher77** [fguillot/kanboard#952]
Hi,
just tried to git pull current changes in master branch with this result:

Unable to migrate database schema: 
\Schema\version_75 => SQLSTATE[HY000]: General error: 1025 Error on rename of './kanboard2/comments' to './kanboard2/#sql2-3f2-12cfd5' (errno: 152)

Found a few issues about that from the past - without a glue how to fix it.

Any hint?

$ mysql -V
mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by kingfisher77** [comment]
After more research we found out that it has to something with a foreign key:

mysql> SHOW ENGINE INNODB STATUS;
------------------------
LATEST FOREIGN KEY ERROR
------------------------
150626 21:36:07 Error in dropping of a foreign key constraint of table "kanboard2"."comments",
in SQL command
ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2
Cannot find a constraint with the given id "comments_ibfk_2".

Does this help?

**Comment by fguillot** [comment]
Can you please send me the result of the command of `SHOW CREATE TABLE comments\G` to see the difference with my own setup?

**Comment by kingfisher77** [comment]
Here we are:

mysql>  SHOW CREATE TABLE comments\G
*************************** 1. row ***************************
       Table: comments
Create Table: CREATE TABLE `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `date` int(11) DEFAULT NULL,
  `comment` text,
  `reference` varchar(50) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `comments_reference_idx` (`reference`),
  KEY `comments_task_idx` (`task_id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8

Thank you!
  

On 27 Jun 2015, at 17:23, Frédéric Guillot wrote:

> Can you please send me the result of the command of `SHOW CREATE TABLE comments\G` to see the difference with my own setup?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fguillot/kanboard/issues/952#issuecomment-116088738

-- 
Tobias Kirchhofer
tobias@kirchhofer.net

**Comment by fguillot** [comment]
I don't understand why but constraints are missing in your table.

You can probably fix the issue manually, by removing the first line of the migration 75 (app/Schema/Mysql.php) see https://github.com/fguillot/kanboard/blob/master/app/Schema/Mysql.php#L23

After the schema migration your table should be similar to that:

```sql
mysql> show create table comments\G
*************************** 1. row ***************************
       Table: comments
Create Table: CREATE TABLE `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT '0',
  `date_creation` int(11) NOT NULL,
  `comment` text,
  `reference` varchar(50) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `comments_reference_idx` (`reference`),
  KEY `comments_task_idx` (`task_id`),
  CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
1 row in set (0.00 sec)
```

**Comment by kingfisher77** [comment]
Yes, meanwhile i added the constraints manually and it works now... Strange, didn't touch the database ...  

On 27 Jun 2015, at 22:44, Frédéric Guillot wrote:

> I don't understand why but constraints are missing in your table.
>
> You can probably fix the issue manually, by removing the first line of the migration 75 (app/Schema/Mysql.php) see https://github.com/fguillot/kanboard/blob/master/app/Schema/Mysql.php#L23
>
> After the schema migration your table should be similar to that:
>
> ```sql
> mysql> show create table comments\G
> *************************** 1. row ***************************
>     Table: comments
> Create Table: CREATE TABLE `comments` (
> `id` int(11) NOT NULL AUTO_INCREMENT,
> `task_id` int(11) NOT NULL,
> `user_id` int(11) DEFAULT '0',
> `date_creation` int(11) NOT NULL,
> `comment` text,
> `reference` varchar(50) DEFAULT '',
> PRIMARY KEY (`id`),
> KEY `user_id` (`user_id`),
> KEY `comments_reference_idx` (`reference`),
> KEY `comments_task_idx` (`task_id`),
> CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
> ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
> 1 row in set (0.00 sec)
> ```
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fguillot/kanboard/issues/952#issuecomment-116138708

-- 
Tobias Kirchhofer
tobias@kirchhofer.net
