### ISSUE TITLE
Close a popup with escape

### ISSUE THREAD

**Issue by raphaelbastide** [fguillot/kanboard#953]
Doesn’t work on Firefox 38.0.5

**Comment by fguillot** [comment]
That works for me, this feature works only if the focus is not in a form field.

**Comment by raphaelbastide** [comment]
That is right. Isn’t it possible to close the dialog even if the focus is in a field, as the focus is in the title input by default?

**Comment by fguillot** [comment]
I just changed that in the dev version, it was annoying for me too.
