### ISSUE TITLE
Sort comments newest/oldest on top

### ISSUE THREAD

**Issue by c99ipnerd** [fguillot/kanboard#956]
Hi,

I would like to make a feature request. May you please add the possibility to sort the comments within a task to have the newest or oldest ones on top? As in #236. If you have a long list of comments you wouldn't need to scroll down till you get to the latest answer. Could this also be made permanent as a setting. 

Thanks in advance.

Cheers
Alwin

**Comment by c99ipnerd** [comment]
Sorry, I may have not clarified my intent enough, I thought about a user setting &/ some clickable sort feature on the "Comments" headline.

Cheers
Alwin

**Comment by fguillot** [comment]
Duplicate with #236
