### ISSUE TITLE
INFO - Toggling Compact view and Horizontal scrolling does not work in IE v 9, but does work with IE v 11- (KB v 1 0 1 6)

### ISSUE THREAD

**Issue by sparkles645** [fguillot/kanboard#957]
* Same as #804 

* It worked with KB v 1 0 1 5

Tested toggling between Compact view / Horizontal scrolling with Firefox v 38 0 5 - works like a charm.

Tested with IE v 9.

Result: Stuck in Horizontal scrolling.

Edit:
**WORKS WITH IE v 11**

    Hotkey 'c' does not work, nothing happens.
    Menu item "Compact view" does not work, nothing happens.

(Why on green earth would you use IE, you say? Am I mentally challenged?)
Answer: Policy. No free choice.

This is a hitch in terms of implementing KB 1 0 1 6 on our "big server".

**Comment by sparkles645** [comment]
Tested With IE v 11.0.96 and that works just fine. I can live With that.
So - information for those affected - IE < v 11 (?) - compact mode will not work

**Comment by fguillot** [comment]
I don't test Kanboard on IE9, only IE11, Chrome, Safari and Firefox.
