### ISSUE TITLE
Some task does not appear in the feed calendar

### ISSUE THREAD

**Issue by fheslouin** [fguillot/kanboard#964]
It seem some task does not appear in the calendar feed. 
When looking at the .ics file some task are missing. Apparently it only happen with old task.

Does any body experienced that ?Thank

**Comment by fguillot** [comment]
At the moment, the ical feed export only tasks between -1 month to +2 months from today. If you have tasks older than 1 month they are not exported, is it your case?

**Comment by fheslouin** [comment]
Thanks, I did not know about this (It could be added in the doc), some of my task where +2 months from today. 

I have also seen one or two task in my calendar but not in my board, that confused me a little bit. Those tasks were actually not closed and without any categories or swimlane, so they were a little bit phantom task...

**Comment by fguillot** [comment]
I increased the date range, now it's -2 months to +6 months from today and updated the doc.
