### ISSUE TITLE
Restore database (different src/dst DB type)

### ISSUE THREAD

**Issue by neurocis** [fguillot/kanboard#966]
Hi, is there presently any way to restore the database? Is it presently a case of having to use a converter tool to preserve my boards / settings?

In my case it would be to migrate from sqlite to mysql.

Cheers.

**Comment by fguillot** [comment]
At the moment, there is nothing to migrate a sqlite db to mysql or postgres.

**Comment by froschdesign** [comment]
@neurocis 
>  In my case it would be to migrate from sqlite to mysql.

Use external (database) tools to migrate your database. ([example](http://stackoverflow.com/questions/18671/quick-easy-way-to-migrate-sqlite3-to-mysql))

@fguillot 
> At the moment, there is nothing to migrate a sqlite db to mysql or postgres.

This is not a task of Kanboard! ([feature creep](https://en.wikipedia.org/wiki/Feature_creep))
