### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by mterron** [fguillot/kanboard#969]
It'd be useful to have integration with currencylayer.com (or some other currency conversion API) for automatic currency rate conversion, maybe updated daily?

**Comment by froschdesign** [comment]
I see no reason why this should be implemented in the core.

@mterron 
Create a simple external script and update the database table `currencies`. (Maybe a API access would be nice here.)

**Comment by fguillot** [comment]
Anyone can write a plugin for that.
