### ISSUE TITLE
API: return URLs (of Project for example)

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#970]
New API function or add new field for existing methods, to get the correspngind url for Tasks and Projects.

A) new method getTaskUrl($taskid), getProjectUrl($projectid)
B) enhance getTask, getAllTasks, getProject, getAllProjects

@fguillot what do you think is the better way?

Regards,
Timo

**Comment by fguillot** [comment]
I implemented the solution B in master.

For projects you will have the urls of the board, calendar and the list view: https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getprojectbyid

For tasks: https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#gettask

**Comment by BlueTeck** [comment]
Very nice, thank you :D
