### ISSUE TITLE
Moving a task from a project to another with multiple swimlanes throws the task into the water

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#972]
I have a board/project with a single swimlane and multiple columns, and I tried moving a task from it to another board that has multiple columns _and_ swimlanes; the result is that the task is moved but doesn't appear anywhere on the new board. The only thing I can do is move it back to the old board by staying on ?controller=task&action=edit

**Comment by fguillot** [comment]
If you move a task from a project with no swimlane to a project with swimlanes, the default swimlane will be assigned to the task. If the default swimlane is disabled/hidden, you will see nothing on the board.

I will try to implement #973 before the next release to improve usability.

**Comment by nekohayo** [comment]
Aaah, I didn't think of the hidden "default swimlane" at all. Shouldn't this be considered a bug that the task doesn't get into the first _visible_ swimlane instead of going into a hidden swimlane?
