### ISSUE TITLE
Ask to update the task parameters when moving it from one project/board to another

### ISSUE THREAD

**Issue by nekohayo** [fguillot/kanboard#973]
When moving or duplicating a task from one board to another, it might make sense to prompt the user to specify the new:
* Category
* Column
* Swimlane (bug #972)

**Comment by fguillot** [comment]
It's now available in master, see http://kanboard.net/documentation/duplicate-move-tasks

Let me know if you found any bugs.

**Comment by nekohayo** [comment]
Seems to work, woohoo!
A small UX suggestion I can offer, but not a big deal and it's up to you: it might be nice to have a "reminder" of what the previous values were besides each field. For example, you could have

```
Category
[ combobox ]   (previously: foobar)
```

With the "previously" text in gray so it doesn't stand out too much. Or maybe do that as a tooltip on the combobox itself (so it only appears when the mouse goes over it, instead of being shown directly on the page). Otherwise you need to have multiple tabs open to know what were the previous parameters if you want to match them.

**Comment by nekohayo** [comment]
In addition to this UX nitpick above, found a possible perf bug: #1041

**Comment by fguillot** [comment]
I added the previous/current value.
