### ISSUE TITLE
problem with mailgun

### ISSUE THREAD

**Issue by fabdelgado** [fguillot/kanboard#974]
Hi create this config in the file config.php
This config not send email and not get anything in the logs of mailgun.
Need to run more then?

define('MAIL_TRANSPORT', 'smtp');
// SMTP configuration to use when the "smtp" transport is chosen
define('MAIL_SMTP_HOSTNAME', 'smtp.mailgun.org');
define('MAIL_SMTP_PORT', 587);
define('MAIL_SMTP_USERNAME', 'postmaster@mydomain.com');
define('MAIL_SMTP_PASSWORD', 'mykey');
define('MAIL_SMTP_ENCRYPTION', null); // Valid values are "null", "ssl" or "tls"

Thankyou

**Comment by fguillot** [comment]
Here an example if you would like to use the SMTP of Mailgun:

```php
define('MAIL_TRANSPORT', 'smtp');
define('MAIL_FROM', 'the mailgun configured sender email');
define('MAIL_SMTP_HOSTNAME', 'smtp.mailgun.org');
define('MAIL_SMTP_PORT', 465);
define('MAIL_SMTP_USERNAME', 'the mailgun email address');
define('MAIL_SMTP_PASSWORD', 'your_mailgun_password');
define('MAIL_SMTP_ENCRYPTION', 'ssl');
```

Or use their HTTP API (faster than SMTP):

```php
define('MAIL_TRANSPORT', 'mailgun');
define('MAILGUN_API_TOKEN', 'key-XXXX');
define('MAILGUN_DOMAIN', 'your mailgun domain.tld');
define('MAIL_FROM', 'your mailgun sender email address');
```
If something is doesn't work, enable the debug mode and check the log file.

**Comment by fabdelgado** [comment]
thankyou!
Please add to documentation.
