### ISSUE TITLE
Show user initials in mimimized task mode

### ISSUE THREAD

**Issue by Danipon** [fguillot/kanboard#975]
It would be nice to see user initials in "minimized task" mode. I managed to do in a *dirty* way (I'm not a php programmer). The proper way requires a change in the user configuration i guess.
![2015-07-03_093447](https://cloud.githubusercontent.com/assets/13162448/8494621/d6bc9e6e-2166-11e5-84d0-8bdf7c800ec7.png)

**Comment by BlueTeck** [comment]
:+1:

**Comment by fguillot** [comment]
It's now in the master branch.

Thanks for the suggestion.
