### ISSUE TITLE
[FR] Show Assignee instead of creator in iCal integration

### ISSUE THREAD

**Issue by Danipon** [fguillot/kanboard#980]
It would be great to see the assignee instead of the task creator using the iCal integration. I added the calendar to outlook and this is the result. More difficult (but nice) I guess is preserve the task color.
![2015-07-03_154410](https://cloud.githubusercontent.com/assets/13162448/8500231/758a24b6-219a-11e5-9161-86c7bf6c7369.png)

**Comment by fguillot** [comment]
I changed that in the current development version.
