### ISSUE TITLE
Time Format

### ISSUE THREAD

**Issue by osborng** [fguillot/kanboard#982]
Anywhere times are displayed (i.e. activity stream, time tracking, etc), the time is displayed in what appears to be a combination of 12 and 24 hour time. For example 21:17 PM instead of 9:17 PM or 21:17. The time should be either one format or the other and should be configurable, if possible.

**Comment by froschdesign** [comment]
:+1: 

I think the standard formatting should be based on the language and timezone settings (simple with PHP's [`IntlDateFormatter` class](http://php.net/manual/en/class.intldateformatter.php)) and options for customizations.

**Comment by fguillot** [comment]
With the version 1.0.25 you can choose your preferred date time format in application settings.
