### ISSUE TITLE
Multiple categories (Transform Categories into tags)

### ISSUE THREAD

**Issue by mterron** [fguillot/kanboard#983]
It'd be useful for us to be able to have multiple categories for each task. My thinking is along the lines of tagging tasks. At the moment only one category can be applied but I think tags would be an enhancement to the current behaviour, as you can always only use 1 tag and will have the same behaviour as it currently do.

**Comment by BlueTeck** [comment]
see #262 #646

**Comment by fguillot** [comment]
Closing duplicate.
