### ISSUE TITLE
Cumulative flow diagram - interpolation artifacts

### ISSUE THREAD

**Issue by miczajko** [fguillot/kanboard#985]
After upgrading to version 1.0.16 the cumulative flow diagram turned weird due to the interpolation artifacts:
![cumulative](https://cloud.githubusercontent.com/assets/13198706/8520715/37a735d6-23dd-11e5-9106-e0a03a2daee7.png)

I suggest reverting back to linear interpolation between time points to solve this issue.

**Comment by fguillot** [comment]
Are you running the cronjob to calculate the stats everyday?

**Comment by miczajko** [comment]
Yes, I do, however the machine was down for a few days, so that's why there are the periods of inactivity in the charts.

**Comment by fguillot** [comment]
I changed x axis to category instead of timeserie in the master branch. That should fix this issue.
