### ISSUE TITLE
API: css colornames color_id

### ISSUE THREAD

**Issue by BlueTeck** [fguillot/kanboard#986]
Hi @fguillot,

the api returns a color_id for each task. With the new colors from 1.0.16 the colors does match the css colornames: http://www.w3schools.com/cssref/css_colornames.asp

Could that be changed? Or add a new field with color data from kanboard/app/Model/Color.php?

Regards, 
Timo

**Comment by fguillot** [comment]
The color_id can be anything, that don't need to match any "standard" color name. Especially, if I add a color picker in the future.

Adding a new api procedure to get colors is probably the best solution.

**Comment by BlueTeck** [comment]
Option A) new API method that returns kanboard/app/Model/Color.php->default colors

Option B) enhance task method instead of color_id: "Amber" return
color: { name : "Amber", background: '#ffe082', border: '#ffa000' }

**Comment by fguillot** [comment]
New API procedures available in master:

- https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getdefaulttaskcolors
- https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getdefaulttaskcolor
- https://github.com/fguillot/kanboard/blob/master/docs/api-json-rpc.markdown#getcolorlist

And task properties contains a new item "color" with all color details of the task.
