### ISSUE TITLE
Display the current version on screens

### ISSUE THREAD

**Issue by fabrice-regnier** [fguillot/kanboard#987]
Hi all,

This is a not a bug ! This is a request instead. Is it possible to have the current version of the app (ie 1.0.16) written on the pages ? Thus, I'd know if i need to upgrade.

By the way, i'd like to thank the contributors for this exellent/light/efficient piece of software

regards,

fabrice.

**Comment by BlueTeck** [comment]
With current version you mean the latest release, not your installed version, right? 

Autoupdater is also requested #894

**Comment by fabrice-regnier** [comment]
I meant the installed version. So that i can compare with the latest release version on the main website.

And if i need to upgrade, i do. Actualy, this is a step before #894 

regards,

f.

**Comment by BlueTeck** [comment]
Could be found in your settings
![unbenannt](https://cloud.githubusercontent.com/assets/1961634/8526891/bd3d8dae-2409-11e5-8ee9-7f0d23dd1781.PNG)

**Comment by fabrice-regnier** [comment]
I was connected as a normal user so i couldn't see the current version.
Sorry for the noise and thank-you.

regards,

f.
