### ISSUE TITLE
Search field on every page, instead of hidden.

### ISSUE THREAD

**Issue by oxydron** [fguillot/kanboard#988]
Make the search field globally visible, it's very usefull.

![kanboard](https://cloud.githubusercontent.com/assets/331134/8526729/bf3b8cf8-23de-11e5-9601-277cca9668ee.png)

**Comment by fguillot** [comment]
This feature have already been completely changed in the current development version.

Now you have a global search for all projects and a search/filter box for board/calendar/list view. Here an example:

![search](https://cloud.githubusercontent.com/assets/323546/8533725/05057f0c-2405-11e5-9c3e-12e6d52a5d39.png)

**Comment by oxydron** [comment]
Very nice, thanks for the fast feedback.

Best regards.
