### ISSUE TITLE
Slack use of "empty(expression)"

### ISSUE THREAD

**Issue by cesaric** [fguillot/kanboard#991]
If targeting PHP 5.3 * 5.4, I don't think you'll want to use expressions in "empty()": 

**PHP Fatal error:  Can't use method return value in write context in /var/www/html/kanban/app/Integration/SlackWebhook.php on line 51**

if (! empty($this->config->get('integration_slack_webhook_channel'))) {

Pulling the expression out into a variable fixes it.

**Comment by fguillot** [comment]
Thanks, it's fixed in master.
