### ISSUE TITLE
No creator when duplicating a task

### ISSUE THREAD

**Issue by Pybou** [fguillot/kanboard#993]
Hello,

I observe that when duplicating a task, the creator id of the new task is set to 0. In consequence, the user which created the task can't remove it because the creator id doesn't match with the user id. Only an admin our a project manager can remove the new task.
The creator id is set to 0 because the creator id field is not duplicate (not add in the array $fields_to_duplicate in the TaskDuplication model). But it is correct because the creator id of the original task can be different with the user id of the user duplicating the task.

I think it is possible to add the following line in the copyFields function in TaskDuplication model but I don't if this is the good way.
```
$values['creator_id'] = $this->userSession->getId();
```

Thanks a lot

**Comment by fguillot** [comment]
Thanks to report this issue, it's fixed in master.
