### ISSUE TITLE
Quick-Add subtaks

### ISSUE THREAD

**Issue by dvr123** [fguillot/kanboard#994]
Hi,

We are using Kanboard succesfully in our company for about 5 months now, with aprox. 30 users.
When a sub-task is added to a task there will be an input field for quick adding other sub-tasks on the task summary, neat!
But a request that I get a lot is that they would like that when adding the sub-task they can assign a user right away, is that possible?

![image](https://cloud.githubusercontent.com/assets/10432529/8545474/47fd58ca-24af-11e5-9f6c-ccaeeb67d1cb.png)

**Comment by sparkles645** [comment]
@dvr123 : Recognize the request - we're basically same number of users and implemented at about the same time as you describe. 

Our "workaround" for this:
1. Add all the sub-tasks 
2. Then open them as separate tabs by clicking the scroll-button on the mouse 
3. Visit each tab and assign user, estimate time
It's not perfect, but it's more efficient than editing them one at a time.

**Comment by fguillot** [comment]
Basically, you would like to have the assignee dropdown and the estimate field on the form under the subtasks list, right?

**Comment by dvr123** [comment]
Yes that's right, that would improve the workflow dramatically for us.

**Comment by fguillot** [comment]
It's now part of the dev branch.
