### ISSUE TITLE
Slack integration working only globaly, not for specific project

### ISSUE THREAD

**Issue by prospeh** [fguillot/kanboard#995]
Hi guys,

We have started using kanboard and are really happy with it. Still, even though we updated to the latest version because we wanted to have per-board notifications via Slack hooks, we still can't manage to make it work. 

Setting a global notification for all project works, but we need it to run per-project-per-channel ... Are we missing something or is this feature not operational maybe at this point?

Greets and thanks!

**Comment by ashbike** [comment]
I can confirm the latest release 1.0.16 and the current Git version works fine.

**Comment by fguillot** [comment]
That also works for me, basically you just have to copy and paste the Slack webhook url into Project settings > Integration > Slack.

If that really don't work and you think everything is configured correctly, enable the debug mode, and check what happen in the debug file, you should see the response of the API call sent to Slack.
