### ISSUE TITLE
include changelog in zipfile

### ISSUE THREAD

**Issue by jniggemann** [fguillot/kanboard#996]
Title says it all, please include the changelog in the distribution zip file

**Comment by fguillot** [comment]
The news posted on the website are not enough? http://kanboard.net/news/version-1.0.16

**Comment by jniggemann** [comment]
There may be times when the file is available but internet access is not...
Anyway, thank you for KB, it's really great!

**Comment by froschdesign** [comment]
@fguillot 
> The news posted on the website are not enough?

- release notes with issue numbers would be fine
- more informations on the page "releases" ([compare with Doctrine](https://github.com/doctrine/doctrine2/releases)) or use the same informations from the website news

**Comment by fguillot** [comment]
I added a simple changelog file in the repo that will be added to the next stable archive: https://github.com/fguillot/kanboard/blob/master/ChangeLog

**Comment by jniggemann** [comment]
Great, thank you!
