### ISSUE TITLE
1.15: Empty swimlane uses vertical space

### ISSUE THREAD

**Issue by jniggemann** [fguillot/kanboard#997]
In case a swimlane is empty, its name should move up one column, freeing the unused vertical space of the line below the headers:
![kanboard](https://cloud.githubusercontent.com/assets/1318059/8554899/f921883c-24ec-11e5-8e1c-e2d582eb1d49.png)

The target for (drag and) drop would then have to be the header of course...

**Comment by fguillot** [comment]
The swimlane layout has been changed in master, column headers are not duplicated anymore.
