### ISSUE TITLE
Are Tags Available?

### ISSUE THREAD

**Issue by Sorasma** [fguillot/kanboard#998]
This is a question related to this https://github.com/fguillot/kanboard/issues/646 
I've tried to find if we have option for tags but can't find that option, so was wandering if that feature is available or not.

Thanks

**Comment by BlueTeck** [comment]
At the moment it is not availiable.

**Comment by gmalone** [comment]
I use the Description field as an ad-hoc tag collector in tasks.  But a real tag system would be very useful.

GREAT WORK with Kanboard!!   Just posted a donation.

**Comment by fguillot** [comment]
@gmalone Tags will be available later, just be patient, there is so much things to improve, thanks for the donation :)

**Comment by gmalone** [comment]
Hey, Kanboard is excellent even as it is.  You've done a really good 
job.  No sweat about tags.  All is well.

Greg Malone
greg@gregmalone.me
www.gregmalone.me
